### ISSUE TITLE
how to fix  CVE 2020 15522 based on BC 1.61

### ISSUE THREAD

**Issue by mujunhan** [bcgit/bc-java#1004]
Hello, we're using android BC 1.61 in our product.
In order to fix CVE 2020 15522 in BC 1.61, we have found 2 patches:
https://github.com/bcgit/bc-java/commit/87ab5d8470829879219e50213912bab6b1ab8fe8   
https://github.com/bcgit/bc-java/commit/744c0dc2958870899d8b604bc3cc1a1a1ef04db5

My question is:
To solve this problem, in addition to the above two patches,  is there any other patch need?
In other words, are the two patches independent, or they need to rely on other patches? 

Look forward to your reply.

Best regard,

Lee

**Comment by peterdettman** [comment]
Sorry for the long delay. Those patches are all that you need.
