### ISSUE TITLE
ASN.1: Cannot set AUTOMATIC TAGS for BERTaggedObject

### ISSUE THREAD

**Issue by emirmo** [bcgit/bc-java#1008]
BERTaggedObject constructor takes an "explicit" argument to define explicit or implicit tags, as well as tag number.

Are these the only options? Can I set tags as automatic? Or is there something about the standard that I'm misunderstanding?

**Comment by peterdettman** [comment]
"AUTOMATIC TAGS" is syntactic sugar in ASN.1 module syntax, causing the elements of e.g. a SEQUENCE, SET or CHOICE type declaration to automatically get tag declarations (starting from 0 in declaration order).

Actual tagged encodings (instances of the declared ASN.1 type) are always either implicitly or explicitly tagged, and as far as the BC library is concerned, you would need to have already resolved which is expected for any given encoding.

If you can provide some details of the ASN.1 type(s) you are trying to work with, we might be able to advise what the expected tagging is.

**Comment by emirmo** [comment]
Thank you for your response. 

I'm attempting a simple BER encode of a sequence consisting mostly of integer values, something like:

```
// Adding data to vector
ASN1EncodableVector vector = new ASN1EncodableVector(); 
vector.add(new ASN1Integer(new BigInteger("1000")));

// Encoding the sequence
BERSequence sequence = new BERSequence(vector);
byte[] encoded = sequence.getEncoded();

// Printing result
System.out.println(DatatypeConverter.printHexBinary(encoded));
```
The printed result does not match the encoding produced by the online encoders such as:
https://asn1.io/asn1playground/

The results are closer when using IMPLICIT or EXPLICIT tags with the online encoder.

**Comment by peterdettman** [comment]
OK, but you still didn't tell me an actual example, or point to the ASN.1 type definition (what specification are you working from?).

**Comment by emirmo** [comment]
It is possible that I don't fully understand your question, but here's a simplified example of the specification and data I'm trying to encode:

Specification:
```
GeneratedSchema DEFINITIONS AUTOMATIC TAGS ::= 
BEGIN
  Example ::= SEQUENCE       
  {
     itemId     INTEGER
  }                                                     
END
```
Value:
```
value Example ::= {
  itemId     1000
}
```

**Comment by peterdettman** [comment]
Because of "AUTOMATIC TAGS" being given as the default tagging mode, it is as if `itemId` was declared:
```
    itemId [0] IMPLICIT INTEGER
```

If there were further elements of Example, they would then get consecutive tags "as if declared" like this:
```
    itemId [0] IMPLICIT INTEGER,
    secondItemId [1] IMPLICIT INTEGER,
    thirdItemId [2] IMPLICIT INTEGER
```

So to answer your original question, you would use `explicit==false` when constructing the BERTaggedObject for each of those INTEGERs, along with the consecutive tag numbers 0, 1, 2...

This stackoverflow answer might be of help too: https://stackoverflow.com/a/64003112/264294 .

**Comment by emirmo** [comment]
Thank you for your response, the solution is now clearer.
