### ISSUE TITLE
Bouncycastle Subkey Selection

### ISSUE THREAD

**Issue by joechristensen-taulia** [bcgit/bc-java#1009]
My organization currently uses Bouncycastle for our PGP encryption/deception. We are working with a vendor that has sent us a certificate containing an expired subkey (as well as current, unexpired subkeys).

- The vendor refused to update their certificate with the expired key removed
- For our current internal implementation, the certificate exists as an .asc file that lives in our file system (we don't use a gpg tool to import
- Bouncycastle keeps selecting the expired subkey rather than a current or valid key

1. The expired subkey appears first in the certificates subkey list. Is Bouncycastle always going to select the first subkey?
2. Is there a config setting (or alternative way) that ensures Bouncycastle utilizes a non-expired key?

**Comment by vanitasvitae** [comment]
How exactly are you using Bouncycastle? I guess the classes from the example package are not really intended for production use, rather as a demonstration for how certain functionality could be implemented.

If you need a production-ready OpenPGP implementation that uses Bouncycastle and takes care of key expiration etc., I can recommend [PGPainless](https://github.com/pgpainless/pgpainless) (disclaimer, author here).
