### ISSUE TITLE
GitHub mirror URL uses HTTP

### ISSUE THREAD

**Issue by Marcono1234** [bcgit/bc-java#1012]
Hello,
it appears the mirror URL of this GitHub repository uses (unencrypted) HTTP instead of HTTPS:
![Mirror info screenshot](https://user-images.githubusercontent.com/11685886/131044499-4113871c-f2b1-4248-bbcc-bc349c2beecf.png)

It looks like there is little information available about how such mirror repositories on GitHub work, so maybe there are additional integrity checks performed in the background (or whether your internal Git repository just pushes the changes to here).
Though as someone external having a look at this repository, seeing a mirror using HTTP is somewhat concerning.

Could you please explain whether this is something to worry about?

(The same also applies to your other mirrored repositories)

**Comment by dghgit** [comment]
GitHub is actively pulling.

**Comment by Marcono1234** [comment]
Thanks for the clarification. Wouldn't it be safer then to use HTTPS (if possible)?
Developers are using the state of this GitHub repository (and not your internal Git repository) to create their own modifications or test things out. This repository has currently 890 forks and there might be more users who have cloned the source without having created a fork.

If someone were to perform a man-in-the-middle attack between GitHub and your internal repository, they could affect all those forks and future users cloning the source. Despite being unlikely, it might be good nonetheless to switch to HTTPS in case your Git repository supports it. What do you think?

**Comment by dghgit** [comment]
We're not the right people to take this up with. We can already support https. You are welcome to take this up with github, we're more than happy to explore other ways of mirroring.

**Comment by Marcono1234** [comment]
I think you will have more success than me when you contact GitHub from your `bcgit` account here: https://support.github.com/request
The topic you choose on that page probably does not matter (maybe "Account or billing issues" works); they usually redirect the ticket then to the appropriate team.

I would imagine that they are reluctant to change any mirror settings when I (not being a member of this project) contact them.

**Comment by dghgit** [comment]
Actually, no, we'll have more success if you raise it with them first. I don't think they appreciate the perception issue yet, they're only going to do that if people who are not involved in the project contact them. I'm happy to ping them as soon as you have to follow up on it.

**Comment by Marcono1234** [comment]
They responded to me:

> If you aren't a maintainer of this project, its best to ask them to reach out to us directly to update any existing mirror links.

They also suggested to switch from this legacy mirror approach to a push-mirror instead:

> We do however recommend that instead of creating a legacy mirror, that maintainers configure their external repository to push to a repository on GitHub.com via a periodic job or post-receive hook, on their external server, which follows the guide here:
> 
> https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/duplicating-a-repository#mirroring-a-repository

Though I guess if you do not want to switch to a push-mirror approach (yet), it would be good if you could contact them and ask them to change the mirror settings for all your repositories to use HTTPS in the interim.

**Comment by dghgit** [comment]
Well it's still more progress than I've made to date. I've got a feeling the push mirror would be the answer though.

**Comment by dghgit** [comment]
Now fixed.
