### ISSUE TITLE
What is the purpose of  SMIMESignedGenerator.generateEncapsulated() (in bcmail-fips)

### ISSUE THREAD

**Issue by skadoosh007** [bcgit/bc-java#1014]
It was mentioned that : 
When we create encapsulated signed content the receiver will not be able to read the content if they could not verify the signature.

But i see that outlook/thunderbird are able to read the content even if they could not verify the signature.

Am i missing something here ?

**Comment by dghgit** [comment]
Not exactly. The convention used to be to not display encapsulated signed content to the end user without verification if it could not be verified. The mail readers in question may have chosen to treat the content in the same way as multi-part signed.

**Comment by skadoosh007** [comment]
> Not exactly. The convention used to be to not display encapsulated signed content to the end user without verification if it could not be verified. The mail readers in question may have chosen to treat the content in the same way as multi-part signed.

How is the client able to read the encapsulate content ?
I sent a mail to outlook and it could not verify the signature because it doesn't have the public key of the sender.
But it could still decrypt the content.
Does encapsulation doesn't mean we are encrypting with sender's private key ?

**Comment by dghgit** [comment]
Encapsulation just means the signed data is encoded inside the signature block using ASN,1 - generally not very easy for a human to read without help. Not encrypted.

**Comment by skadoosh007** [comment]
> Encapsulation just means the signed data is encoded inside the signature block using ASN,1 - generally not very easy for a human to read without help. Not encrypted.

That makes it clear.
Thank you
