### ISSUE TITLE
gpg: WARNING: cipher algorithm AES not found in recipient preferences

### ISSUE THREAD

**Issue by Susmit07** [bcgit/bc-java#1016]
Hello Guys,

We encrypted the document using bouncy castle, below is the encrypted document:

```
-----BEGIN PGP MESSAGE-----
Version: BCPG v1.68
hQIMA9PzAu37oU7/AQ//S4Jne/jwoNuPkOUo+iqsnp2gPWljZT4f1kBkgrg6odoU
tb/ugFmxP5a0h5CYlOOFkmyCS20+M0mfDBhE5QUWyDjp9HucmkhYjWUsT17adRnt
a0sQyuZKX8RfHugUzotrML9tTMY8ljwxI5TM9a3DkNFMuHJNK9gTLByh8R4aEoVS
1TNA6JIFsTko9es5GRUl28Ecsm2wYNaOBlAICVuZEEFEgxzug7lRj+KHfRDdJ8rz
sgW/ceyHtjUd0erfla9vuqEnc0F1GOhWhIhkZQBB5Uu6dKoLb0kFR3JnOjtMGQIK
G+EIAidqlwAaZmwzaQq7xwmeffNxYAxH+Sh8p3ZzPjjkdxw4syOBQNtbppC/EjPA
3RVBK5xDPsOX9dc9ajQGhDQdAJTLp6ZoYLZwM7sDu6GvwKXxIqxLDopJsMmuLjdU
1iVnyvYwWMv2ajKJWX+PXdAApduk6JAF99USSi9R3to9sCE/XJUG6hiSgynzPwjC
Jcgz+kWiAd2+gT4hd4Oj/Oc0NZx8HT6lVYrxMzleIksId50gTX4lyO/E8kdCqhUf
xG/UB+dv5wrXtasK8tFpGTTe86aGLmttTr4Asi8/kL5JBhxSyVRWME/3yYpmvw3X
DSvkPcxOfDwbnl0wVf+XmOACL33Pb0QQ3HHnAHLj0VaH8HmDUIi5gx/fUIkTpYHS
rQEark54+HEbi387QbsAAxXIMbodmSXX48Nvp5rHiIJ7pHYpMVVXiIx9gzWK/0B3
6NJzSXAnmV0t1zlJTAgTXCi5Sp2M7m65Egn0KeCrHVS7cgc0suDODKUhJoiNm05e
kSFJfJSNelqzvtcJCZr3yqczWx8lT6qh0u9ndpybCQaTfBcDNonmyJwBfHQlo1qW
ycg9jJM+S0GJP1QkqfbPTA5p+BhEJIb/BRVn4Xwb
=TYA5
-----END PGP MESSAGE-----
```
Encryption Algorithm used: aes-128, shared the public key.

Now we imported the private key (created by bouncy castle apis) to gpg and tried decrypting it using secret key, shared the secret key.

Then GPG shows this warning message:

gpg: WARNING: cipher algorithm AES not found in recipient preferences

but it is able to decrypt the file

gpg --version
gpg (GnuPG) 2.2.17-unknown

$ gpg --verbose --symmetric
gpg: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg: waiting for the agent to come up ... (5s)
gpg: connection to agent established
gpg: pinentry launched (514 w32 1.1.0 /dev/pty0 xterm needs-to-be-defined)
gpg: pinentry launched (515 w32 1.1.0 /dev/pty0 xterm needs-to-be-defined)
**gpg: using cipher AES**
gpg: writing to stdout
gpg: signal Interrupt caught ... exiting

Need your help how can we fix the warning issue, we are using same preference cipher aes-128 during encrypt via BC apis and decrypt via GnuPG so its strange why we are getting the warning

[Server1DecKeyPublic.pgp.txt](https://github.com/bcgit/bc-java/files/7099063/Server1DecKeyPublic.pgp.txt)
[secret_key.txt](https://github.com/bcgit/bc-java/files/7099070/secret_key.txt)

**Comment by Susmit07** [comment]
@peterdettman @dghgit

**Comment by dghgit** [comment]
I appreciate your profile describes you as lazy, however if you are going to use PGP protocol you really should read RFC 4880 at least. It's obvious both from the warning and the dump of the key that the packet discussed in section 5.2.3.7 is either missing from the user certification, or missing AES, on the secret key. In this case the sub packet is missing.

Please note, if you are in a rush, commercial level support for the APIs is available.

**Comment by Susmit07** [comment]
Yeah lazy minds always finds a shortcut, but thank you to guide me with the RFC, as I was not aware, as far as I understand so there may be it may issue with the secret key, may be it's not getting created in the right way
