### ISSUE TITLE
BC provider fails to load certain P12 keystores under Java 17 (pad block corrupted)

### ISSUE THREAD

**Issue by e4711s** [bcgit/bc-java#1018]
The attached example runs fine with BouncyCastle 1.69 on Java 16 and below, yet it fails on Java 17.
[java17bc.zip](https://github.com/bcgit/bc-java/files/7104916/java17bc.zip)

It is loading a PKCS#12 keystore with the following structure, according to OpenSSL:

        MAC: sha256, Iteration 100000
        MAC length: 32, salt length: 32
        PKCS7 Data
        Shrouded Keybag: PBES2, PBKDF2, AES-256-CBC, Iteration 100000, PRF hmacWithSHA256
        PKCS7 Encrypted data: PBES2, PBKDF2, AES-256-CBC, Iteration 100000, PRF hmacWithSHA256
        Certificate bag

On Java 17 the following exception is thrown:

      java.io.IOException: exception unwrapping private key - java.security.InvalidKeyException: pad block corrupted
              at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.unwrapKey(Unknown Source)
              at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
              at org.bouncycastle.jcajce.provider.keystore.util.AdaptingKeyStoreSpi.engineLoad(Unknown Source)
              at java.base/java.security.KeyStore.load(KeyStore.java:1473)
              at demo.java17bc.Java17Bc.main(Java17Bc.java:17)

JRE Info:

        openjdk version "17-ea" 2021-09-14
        OpenJDK Runtime Environment Zulu17+81-CA (build 17-ea+35)
        OpenJDK 64-Bit Server VM Zulu17+81-CA (build 17-ea+35, mixed mode, sharing)

**Comment by e4711s** [comment]
Any news on this? Java 17 was officially released in the meantime.

**Comment by dghgit** [comment]
I've got a feeling this is because the PKCS12 implementation was relying on provider precedence for getting the cipher, rather than it's helper. A similar issue was reported for the keytool but it only shows up with Java 17 as well. Now fixed.

**Comment by lazydays79** [comment]
So ist this now fixed? In bountycastle? Because we are facing the same issue and had to remove bountycastle as the KeyStore provider when opening pkcs12 files.

**Comment by dghgit** [comment]
Try https://www.bouncycastle.org/betas 170b12 or later. Let me know how it goes.
