### ISSUE TITLE
InvalidCipherTextException: mac check in GCM failed

### ISSUE THREAD

**Issue by 15989206052** [bcgit/bc-java#1019]
16:18:42  org.bouncycastle.tls.TlsFatalAlert: bad_record_mac(20)
16:18:42  	at org.bouncycastle.tls.crypto.impl.bc.BcTlsAEADCipherImpl.doFinal(Unknown Source)
16:18:42  	at org.bouncycastle.tls.crypto.impl.TlsAEADCipher.decodeCiphertext(TlsAEADCipher.java:250)
16:18:42  	at org.bouncycastle.tls.DTLSRecordLayer.processRecord(Unknown Source)
16:18:42  	at org.bouncycastle.tls.DTLSRecordLayer.receive(Unknown Source)
16:18:42  	at org.bouncycastle.tls.DTLSTransport.receive(Unknown Source)
16:18:42  	at com.ericsson.cces.ueinfo.ipfix.collector.dtls.DTLSSession.decodeNonHandShakeMessage(DTLSSession.java:163)
16:18:42  	at com.ericsson.cces.ueinfo.ipfix.collector.dtls.DTLSSession.decode(DTLSSession.java:137)
16:18:42  	at com.ericsson.cces.ueinfo.ipfix.collector.traffic.southbound.business.handler.udp.DTLSDecodingHandler.channelRead0(DTLSDecodingHandler.java:31)
16:18:42  	at com.ericsson.cces.ueinfo.ipfix.collector.traffic.southbound.business.handler.udp.DTLSDecodingHandler.channelRead0(DTLSDecodingHandler.java:20)
16:18:42  	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
16:18:42  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
16:18:42  	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
16:18:42  	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
16:18:42  	at io.netty.util.concurrent.UnorderedThreadPoolEventExecutor$NonNotifyRunnable.run(UnorderedThreadPoolEventExecutor.java:292)
16:18:42  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
16:18:42  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
16:18:42  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
16:18:42  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
16:18:42  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
16:18:42  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
16:18:42  	at java.base/java.lang.Thread.run(Thread.java:834)
16:18:42  Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed
16:18:42  	at org.bouncycastle.crypto.modes.GCMBlockCipher.doFinal(Unknown Source)
16:18:42  	... 21 common frames omitted

Looking forward to your help

**Comment by peterdettman** [comment]
There's not really enough to go on here. If the failures are intermittent I might suspect an issue related to the (apparently) multi-threaded usage. Does this happen on the very first packet received or at some random time later?

**Comment by 15989206052** [comment]
> There's not really enough to go on here. If the failures are intermittent I might suspect an issue related to the (apparently) multi-threaded usage. Does this happen on the very first packet received or at some random time later?

I am very grateful for your reply.
the failures are intermittent， Our component test will only send one or two packets, so we can't determine when it happened. The first thing I thought of was the issue of multi-threading, but I did not troubleshoot the issue of multi-threading. 
I will continue to troubleshoot multi-threading issues later。

**Comment by 15989206052** [comment]
> There's not really enough to go on here. If the failures are intermittent I might suspect an issue related to the (apparently) multi-threaded usage. Does this happen on the very first packet received or at some random time later?

sorry to disturb you again after so long.

this issue is exhausting me, seems it happened on the first two packet received, i use bc with netty, i dont sure that is it related to netty. 

there is no difference between the packet sent by client & the packet received by server. And it seems that the client does not have thread safety issues.

does the bad_record_mac must be packet mess?

**Comment by peterdettman** [comment]
The stack trace you provided clearly shows the code running in a thread pool, so multithreading is a possible issue if you did the handshake on one thread and then switched to processing application data on other threads. I assume this stack trace is from the server?

- What version of BC are you using? Is it the latest?
- What software is the other side (client) using?
- Do you know if the client and/or server work properly when connecting to some other implementation?
- If you try negotiating a different cipher suite do things then work?

bad_record_mac could mean some sort of packet corruption on-the-wire, but it's not common in practice. Especially if you see the error reliably then more likely the client/server somehow didn't agree on the cipher key correctly (which shouldn't happen if the handshake succeeded successfully), or as I said maybe some thread safety issue is leading to corrupted calculation/data.

**Comment by 15989206052** [comment]
> The stack trace you provided clearly shows the code running in a thread pool, so multithreading is a possible issue if you did the handshake on one thread and then switched to processing application data on other threads. I assume this stack trace is from the server?
> 
> * What version of BC are you using? Is it the latest?
> * What software is the other side (client) using?
> * Do you know if the client and/or server work properly when connecting to some other implementation?
> * If you try negotiating a different cipher suite do things then work?
> 
> bad_record_mac could mean some sort of packet corruption on-the-wire, but it's not common in practice. Especially if you see the error reliably then more likely the client/server somehow didn't agree on the cipher key correctly (which shouldn't happen if the handshake succeeded successfully), or as I said maybe some thread safety issue is leading to corrupted calculation/data.
> 
> e.g. If you change the server to do the whole handshake and application-data processing in a single thread, does it then work?

Really appreciate you reply.
Because of the VPN problem, I am very sorry to see your answer so late.

1. Q: so multithreading is a possible issue if you did the handshake on one thread and then switched to processing application data on other threads.
A: it's impossible as ConcurrentHashMap is used to store dtls sessions

2.  I assume this stack trace is from the server?  -- yes

3. What version of BC are you using? Is it the latest?    -- Almost latest

4. What software is the other side (client) using?    -- jmeter plugin with bc & netty

5. Do you know if the client and/or server work properly when connecting to some other implementation?  -- not yet

6. If you try negotiating a different cipher suite do things then work?  -- maybe try later

7. bad_record_mac could mean some sort of packet corruption on-the-wire, but it's not common in practice. Especially if you see the error reliably then more likely the client/server somehow didn't agree on the cipher key correctly (which shouldn't happen if the handshake succeeded successfully)    --  some changes. I said before it happened on the first two packet received, But now it happens with a probability of one in tens of millions，maybe this is data corruption during network transmission?

8. If you change the server to do the whole handshake and application-data processing in a single thread, does it then work?  -- This may affect performance，but if this problem remains unresolved, i will try it. 

Many thanks.

**Comment by peterdettman** [comment]
Developing a single-threaded version of the server will be the best test of whether the issue is related to a race condition (i.e. multithreading). "a probability of one in tens of millions" is consistent with a race condition.

I guess it _could_ also be packet corruption in the network; in my experience that has never been an issue, but obviously networks can have varying quality, so I can't rule it out.

Such rare failure implies at least that the handshake is basically working i.e. both sides agree on the cryptographic settings and are accepting each others' 'Finished' messages. So I think testing a simple single-threaded version will clarify the source of the problem.

**Comment by 15989206052** [comment]
> Developing a single-threaded version of the server will be the best test of whether the issue is related to a race condition (i.e. multithreading). "a probability of one in tens of millions" is consistent with a race condition.
> 
> I guess it _could_ also be packet corruption in the network; in my experience that has never been an issue, but obviously networks can have varying quality, so I can't rule it out.
> 
> Such rare failure implies at least that the handshake is basically working i.e. both sides agree on the cryptographic settings and are accepting each others' 'Finished' messages. So I think testing a simple single-threaded version will clarify the source of the problem.

Great thanks.

We did a three-day stability test. If the network environment is stable, the issue of bad_record_mac has not occurred, so I suspect it is related to the previous network access method. 

I will continue to observe this problem.

**Comment by dghgit** [comment]
Appears resolved.
