### ISSUE TITLE
PGPSecretKey.copyWithNewPassword defaults to S2K USAGE_CHECKSUM

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#1020]
Hey!

When setting a passphrase on a key which previously was unencrypted, [BC chooses S2K usage `USAGE_CHECKSUM`](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pg/src/main/java/org/bouncycastle/openpgp/PGPSecretKey.java#L815-L818) which is not an ideal choice.

OpenPGP.js for instance rejects this S2K usage as insecure.

Could you instead change the implementation of `PGPSecretKey.copyWithNewPassword()` to default to `USAGE_SHA1` as default if the previous usage was NONE?

**Comment by dghgit** [comment]
This is now done. I needed to add an extra method to allow a PGPDigestCalculator to do it first. In line with the current RFC only SHA-1 is accepted for it. Should show up on github soon.
