### ISSUE TITLE
Feature Request - Add the possibility to envelop the signed digest it in the original document 

### ISSUE THREAD

**Issue by p4535992** [bcgit/bc-java#1021]
Add the possibility (or if it already exists I have not found it) having the digest signed (p7s file) to envelop it in the original document and consequently generate a signed file (p7m file).

Below I try to highlight the steps of the use case in the clearest possible way:

![img](https://i.imgur.com/uOBnJDx.png)

Is there any way to achieve this?

**Comment by dghgit** [comment]
I think you're talking about CMSSignedData but with encapsulate set to true - this will contain the document in the PKCS#7 structure so there is just a single blob involved in sending the data.

**Comment by p4535992** [comment]
hi @dghgit sorry to bother, could you give me an example? unfortunately I can't do it alone. I am attaching what little code I had prepared for CADES and PADES envelope as a starting point. This code seem to do the work, but then when i verify the signature i have some red warning so i must do something wrong.

[EnvelopedHashToFileCades.java.txt](https://github.com/bcgit/bc-java/files/7861129/EnvelopedHashToFileCades.java.txt)
[EnvelopedHashToFilePades.java.txt](https://github.com/bcgit/bc-java/files/7861130/EnvelopedHashToFilePades.java.txt)

**Comment by dghgit** [comment]
I'm sorry but I have no idea what a red warning is.

There's examples of encapsulated signing here:

https://github.com/bcgit/bc-java/blob/269be030d1158a907f0a99c0247187b43250ef35/pkix/src/test/java/org/bouncycastle/cms/test/NewSignedDataTest.java#L1734
