### ISSUE TITLE
PGP OnePassSignaturePacket's isNested Flag

### ISSUE THREAD

**Issue by mdusina** [bcgit/bc-java#1023]
The OnePassSignaturePacket accepts a field called [isNested](https://github.com/bcgit/bc-java/blob/2b976f5364cfdbc37d3086019d93483c983eb80b/pg/src/main/java/org/bouncycastle/bcpg/OnePassSignaturePacket.java#L44) and roundtrips it through serialized/deserialized forms. However, it doesn't expose a getter for it and is appears to be otherwise completely unused.

The [PGP spec](https://datatracker.ietf.org/doc/html/rfc4880#section-5.4) describes the field as follows:

       A one-octet number holding a flag showing whether the signature
       is nested.  A zero value indicates that the next packet is
       another One-Pass Signature packet that describes another
       signature to be applied to the same message data.

As a reminder, multiple one pass signatures look like:

      OnePassSignature1, OnePassSignature2, LiteralData, Signature2, Signature1

But can be interpreted in one of two ways (depending on the flag):

      OnePassSignature1 (OnePassSignature2 (LiteralData) Signature2) Signature1
      OnePassSignature1 (LiteralData) Signature1 and OnePassSignature2 (LiteralData) Signature2

If I'm understanding the spec correctly, when a 0 value is used for this flag it means the signatures are *not* nested which means they're independent signatures over the data stream of LiteralData. You could change or delete the inner signature and the outer signature would still verify.

When a 1 value is used for this flag, is means the signatures *are* nested. The inner signature is treated the same (it signs over the data stream of LiteralData) but the outer signature is different.  It signs over the inner signature and the data stream.

OnePassSignaturePacket appears to invert this though:
```
this.nested = (isNested) ? 0 : 1;
```

**Question 1:**
Is it correct to write a 0 when `isNested` is true and a 1 when it's false?  It's entirely possibly I'm misreading the spec.

**Question 2**
Either way, should `isNested` by exposed by a getter on OnePassSignaturePacket so calling code can correctly verify nested signatures?

**Question 3**
Can Bouncy Castle expose a higher-level primitive that makes it easier to verify nested signatures? Even if OnePassSignaturePacket exposed the `isNested` flag, I wouldn't know what (besides the data stream) I need to pass into `PGPSignature.update()`.

----

FYI. I think gpg uses the terminology "last" instead of "isNested".  But this is what it does when you ask it to sign with 2 keys:

```
gpg --sign -u {KEY1} -u {KEY2} plaintext.txt

...

:onepass_sig packet: keyid {KEY2}
        version 3, sigclass 0x00, digest #, pubkey #, last=0
:onepass_sig packet: keyid {KEY1}
        version 3, sigclass 0x00, digest #, pubkey #, last=1
```

**Comment by tonywasher** [comment]
GPG is using the correct terminology. The flag is purely used as an indicator as to whether the OnePassSignaturePacket is the last such packet in the sequence of  OnePassSignaturePackets. However the OpenPGP specification (RFC4880) refers to the flag as nested which leads to this sort of confusion.

When parsing the incoming packets, you receive the details as a PGPOnePassSignatureList, which holds the details of OnePassSignaturePackets in order. As such it is obvious as to which packet is "last", and there is no value is exposing the confusing isNested field.

As you quote from the PGP spec the signatures are calculate over the **same** message data. Therefore of the two possible interpretations that you show, only the second is correct. The first is implied by the field being called nested, but is incorrect.

Answer 1 - Yes it is correct. Names are just confusing.
Answer 2 - No need
Answer 3 - No need. Verification is always over the same literal data regardless of the value of nested

**Comment by dghgit** [comment]
I doubt I could have said it better myself. Thanks.

**Comment by mdusina** [comment]
It looks like this project switched course with how it treats the `isNested` / `isLast` / `isContaining` / `isEncapsulating` flag with [this pull](https://github.com/bcgit/bc-java/pull/1232) and [this pull](https://github.com/bcgit/bc-java/pull/1233).

I just want to verify the answers to the 3 questions I posed above in light of that because the spec remains very much ambiguous. I also don't know how to explain gpg's naming convention and what it does by default when you ask it to sign with two keys. Maybe the answer is, "the spec allows for nested signatures but no one does that and most implementations ignore these flags/set them wrong anyway".

For question 1, it still seems backwards to do `this.isEncapsulating = (isNested) ? 0 : 1;`. 

For question 2, it looks like there is a public getter now (and a constructor).

For question 3, it seems like this is a possible way of constructing signatures:

> When a 1 value is used for this flag, is means the signatures are nested. The inner signature is treated the same (it signs over the data stream of LiteralData) but the outer signature is different. It signs over the inner signature and the data stream.

But that nested signature support has to be done by client code manually serializing the nested signature packets to update the signature calculation to be more than just the `LiteralDataPacket` (which is now possible due to the visible constructor).
