### ISSUE TITLE
 Does bctls-jdk15on suport TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC ?

### ISSUE THREAD

**Issue by AntonGDdeveloper** [bcgit/bc-java#1025]
I use version 1.69
```
<dependency>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bctls-jdk15on</artifactId>
        <version>1.69</version>
</dependency>
```
[this commit](https://github.com/bcgit/bc-java/commit/8fd95d9c0e84199428321f5d16d8a7919229215f ) has ```TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC``` alghoritm  but  when I try to connect to server which uses TLSv1.2 and  this alghoritm I get ```org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40)``` exception

**Comment by peterdettman** [comment]
Not yet, it's very early work based on the draft RFC.
