### ISSUE TITLE
No such algorithm: SHA256withECDSA for provider BC

### ISSUE THREAD

**Issue by ma99us** [bcgit/bc-java#1031]
I was using "ECDSA" algorithm with BC version 1.69 without issue, but as I came to learn ECDSA is a placeholder for SHA1withECDSA (is that right?), When I try to switch to "SHA256withECDSA" and generate new keys get the following exception:
 java.security.NoSuchAlgorithmException: no such algorithm: SHA256withECDSA for provider BC
	at sun.security.jca.GetInstance.getService(GetInstance.java:87)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
	at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:279)
although i clearly see that SHA256withECDSA is supposed to be supported by the latest Bouncy Castle lib.
What am i missing?

**Comment by peterdettman** [comment]
SHA256withECDSA is a (supported) **signature algorithm**. So it is used when creating a `Signature`. For a `KeyPairGenerator`, "ECDSA" is appropriate (or just "EC" should be fine too).
