### ISSUE TITLE
RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING from SunJCE is not correctly emulated.

### ISSUE THREAD

**Issue by tawek** [bcgit/bc-java#1033]
SunJCE in RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING is using SHA-256 for label hash and SHA-1 for MGF1 (if parameters are not present). 
BC is using SHA-256 for label hash and for MFG1 both for its own RSA/NONE/OAEPWITHSHA256ANDMGF1PADDING and when "simulating" SunJCE's RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING.

This leads to padding errors which are difficult to resolve since both parties are referring to the same algorithm by its name but underneath it is really different padding.

Expectation: either support SunJCE algorithm name as SunJCE does it or don't support it at all since if BC is installed before SunJCE it will take over SunJCE algorithm name.

This can be fixed by changing conditions at https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/rsa/CipherSpi.java#L225 to use proper MFG1 hash when matching against SunJCE names.

**Comment by dghgit** [comment]
We're not simulating anything.

This is actually a known defect in the SUN provider - the MGF PRF should operate  at the same level of security as the hash being used for the message digest. I'll admit the situation kind of sucks, but our OAEP implementation is actually the older one, and this issue over the PRF used in MGF1 was raised as a bug against the SUN provider years ago as no-one else did this either. Apart from that in a FIPS environment the SUN interpretation is most definitely wrong. I think we're all stuck.

You can use the OAEPParameterSpec parameters to trigger a compatible implementation. These should be provided with the encrypted data. The ASN.1 should show that SHA-256 is used for the label and that SHA-1 is the MGF PRF.

**Comment by pramitha1166** [comment]
Below mentioned sample code example. 

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;


import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.logging.Logger;

@Service
public class EncryptionUtil {
    private static final Logger LOGGER = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);

    @Value("${crypto.private-key}")
    private String base64PrivateKey;
    @Value("${crypto.public-key}")
    private String base64PublicKey;

    public PublicKey getBase64PublicKey(){

        StringBuilder x509Lines = new StringBuilder();

        try (BufferedReader rdr = new BufferedReader(new FileReader(base64PublicKey))) {
            String line;
            while ((line = rdr.readLine()) != null) {
                x509Lines.append(line);
            }

            String pkcs8Pem = x509Lines.toString();
            pkcs8Pem = pkcs8Pem.replace("-----BEGIN PUBLIC KEY-----", "");
            pkcs8Pem = pkcs8Pem.replace("-----END PUBLIC KEY-----", "");
            pkcs8Pem = pkcs8Pem.replaceAll("\\s+","");

            String finalPkcs8Pem = pkcs8Pem;
            LOGGER.info(() -> "Public Key -> " + finalPkcs8Pem);


            byte [] x509EncodedBytes = Base64.getDecoder().decode(pkcs8Pem);

            X509EncodedKeySpec x509publicKey = new X509EncodedKeySpec(x509EncodedBytes);
            KeyFactory kf = KeyFactory.getInstance("RSA");
            return kf.generatePublic(x509publicKey);

        }catch (IOException | InvalidKeySpecException | NoSuchAlgorithmException e) {
            throw new DataEncryptionException(e.getMessage());
        }
    }

    private PrivateKey getBase64PrivateKey() throws DataEncryptionException {
        StringBuilder pkcs8Lines = new StringBuilder();

        try (BufferedReader rdr = new BufferedReader(new FileReader(base64PrivateKey))) {
            String line;
            while ((line = rdr.readLine()) != null) {
                pkcs8Lines.append(line);
            }

            String pkcs8Pem = pkcs8Lines.toString();
            pkcs8Pem = pkcs8Pem.replace("-----BEGIN PRIVATE KEY-----", "");
            pkcs8Pem = pkcs8Pem.replace("-----END PRIVATE KEY-----", "");
            pkcs8Pem = pkcs8Pem.replaceAll("\\s+","");

            byte [] pkcs8EncodedBytes = Base64.getDecoder().decode(pkcs8Pem);

            PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(pkcs8EncodedBytes);
            KeyFactory kf = KeyFactory.getInstance("RSA");
            return kf.generatePrivate(keySpec);
        }catch (IOException | InvalidKeySpecException | NoSuchAlgorithmException e) {
            throw new DataEncryptionException(e.getMessage());
        }

    }

    private byte[] decryptByteArray(String encryptedMessage) throws NoSuchPaddingException, NoSuchAlgorithmException, InvalidKeyException, IllegalBlockSizeException, BadPaddingException {
        Cipher decryptCipher = Cipher.getInstance("RSA/ECB/OAEPWithSHA-256AndMGF1Padding");
        decryptCipher.init(Cipher.DECRYPT_MODE, getBase64PrivateKey());
        return decryptCipher.doFinal(Base64.getDecoder().decode(encryptedMessage));
    }

    public String decrypt(String encryptedMessage) throws NoSuchPaddingException, IllegalBlockSizeException, NoSuchAlgorithmException,  BadPaddingException, InvalidKeyException {
        LOGGER.info(() -> "Start decrypting data.");
        return new String(decryptByteArray(encryptedMessage), StandardCharsets.UTF_8);
    }

    private byte[] encryptByteArray(String encryptedMessage) throws NoSuchPaddingException, NoSuchAlgorithmException, InvalidKeyException, IllegalBlockSizeException, BadPaddingException {
        Cipher encryptCipher = Cipher.getInstance("RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING");
        encryptCipher.init(Cipher.ENCRYPT_MODE, getBase64PublicKey());
        return encryptCipher.doFinal(encryptedMessage.getBytes(StandardCharsets.UTF_8));
    }

    public String encrypt(String text) throws NoSuchPaddingException, IllegalBlockSizeException, NoSuchAlgorithmException, BadPaddingException, InvalidKeyException {
        return Base64.getEncoder().encodeToString(encryptByteArray(text));
    }

}

**Comment by dghgit** [comment]
RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING was supported by BC prior to the JCE introducing it. Several other providers also did this, it is not our fault that they did not implement it correctly anymore than we could change it now as there are far more people relying on the fact we implement it correctly. It is possible to emulate the the JCE implementation using the OAEPParameterSpec, please feel free to do so.
