### ISSUE TITLE
Valid PKCS7 Signature Verification Fails

### ISSUE THREAD

**Issue by exception-al** [bcgit/bc-java#1034]
I am trying to implement a SCEP service using bouncy castle routines and for requests generated using node.js it fails.

Attempted to verify the node.js CMS Signature using Openssl and it verifies just fine.

B64 of the Signed CMS Message : 
`MIIKyQYJKoZIhvcNAQcCoIIKujCCCrYCAQExCzAJBgUrDgMCGgUAMIIEmwYJKoZIhvcNAQcBoIIEjASCBIgwggSEBgkqhkiG9w0BBwOgggR1MIIEcQIBADGCAZUwggGRAgEAMHkwdDETMBEGCgmSJomT8ixkARkWA29yZzEWMBQGCgmSJomT8ixkARkWBnNpbXBsZTETMBEGA1UECgwKU2ltcGxlIEluYzEXMBUGA1UECwwOU2ltcGxlIFJvb3QgQ0ExFzAVBgNVBAMMDlNpbXBsZSBSb290IENBAgECMA0GCSqGSIb3DQEBAQUABIIBAJTdnUNDHKbVMZR0qo4JFEd4nKTH+/PdxOV3QnsvuIvVSy5KqKM24xhJ6B+TlQ1Xs6Ga++EbLXNZkaQXQb7BIQtqhnbEphV2yHVG4zJOQY9vK428hghtMB4y2/6IDdW7+VSUSZElX8SD2dZ3yGThFlsF9BxFq1tG6LPj7cyXmSSa+UmD9o/oMm6zbx6Ts+sL3VAbAxWuCH21xjWCx8uQo9GhxMg4YOM44fEzNOhJEBGXzxQqDrEx/eSHjndGn3XrEJyE5R3rn6VPDbdx72bzf49MGy45WwyTffR7XRhcF2Sj5dQGturVE2tl0Tay1xJx2TOZ8pNnnU6QnhHy4VIK750wggLRBgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcECHxmSB522vzUoIICrASCAqipuDoCOn0iPXXj7p1G7d0HpvWkoNEkZagc4ftgcr28puB7thJdIS1g5AO3oVESjHvTem8+uSJtdkUm8Y3O+YH+EpvBYHnw8dtnKJHV7+tSg4HXaUgnS45F78xXQ/eSIZwxlWYGemaJGA9opjVmEgPBdCPH5AMFp5jQ/Jij5MmWP5LgmfbkrqrRIGrn3lSXfzquWJCRxpKDaIHc4nJbfbdKccauResSgAn0uoCKhHidq/K22XRJVnwpIrKFXBAj01ASPQbYVJ4AHJnwTdv6rFoI1wT+Ty01RLZ+9X+QNkm4oHo/oGz1I+FLicue++/i2RWrjOT34eQwdouHSfbz8CWPlsgsDn/eBv4bkyqHFt/7/S6KboO0NvqnDQFbfa/PkZPM06VV32Yihgm8FSxZB4h7dfgP/yvU/r9wxdbQW6lTUM4Xn76azmXSoFO3qcdMH26e/x1V4uleaX9AXiD6exdXBJzxRtrwQ01rsoXfV7b07X0pJG3U4YYM2lSpKg/5bu3efms+kZPefsh+emkyc7Pu8IPSD2DxQPMzxGooPE0/l7YHTsdJkDQA0mKobWoRdZ38vpPhoSa58e3x+vx2Exntlovc96C22HnpnKJxsbdgScvCHoeyMzVh813sQN3QFzPBNWlJHhimTX7EFg6DfvY/cOhn2BHXxeW5c/BY81Z5BCtOTSSIHFPDXKKF9UKx3JcJiSI+zkbquYN5mG4OB+UMpxr9addDGNrtAH6mkEgoHz9SNqjHqLV7KPyvEd5xHj3Qq2W7/l/fhG7aL7h2ZE8E7/CF2//CAMom4Iw9J9F3u1YO9gG6CgEik8WtA0RCpWYk/ONxSnkjrSnuKgThliY5J9I7WLLBCv3iPtUmHfx6M5XTVjaPa26TSZupF/EYheGnBmjPxZpAiqCCA9MwggPPMIICt6ADAgECAgECMA0GCSqGSIb3DQEBBQUAMHQxEzARBgoJkiaJk/IsZAEZFgNvcmcxFjAUBgoJkiaJk/IsZAEZFgZzaW1wbGUxEzARBgNVBAoMClNpbXBsZSBJbmMxFzAVBgNVBAsMDlNpbXBsZSBSb290IENBMRcwFQYDVQQDDA5TaW1wbGUgUm9vdCBDQTAeFw0yMTA5MjcxNDQ4NTlaFw0zMTA5MjcxNDQ4NTlaMHoxEzARBgoJkiaJk/IsZAEZFgNvcmcxFjAUBgoJkiaJk/IsZAEZFgZzaW1wbGUxEzARBgNVBAoMClNpbXBsZSBJbmMxGjAYBgNVBAsMEVNpbXBsZSBTaWduaW5nIENBMRowGAYDVQQDDBFTaW1wbGUgU2lnbmluZyBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALwI3w33rgcHxmXv4wTN1BjARGW7vBwvN6XKARZa3bZ0saQG11fgyXEEMEcCQEMvdNNHuKwO1/FwYpXYcTvonEA1C7dtpe2ZnYpbzl5om8SNROzCBHs1lVQyHGpJtwptBP4Qvtf1V6AI2xu8P3ArjTXMXMCAX251+myRydO6VMFeUWZfZlXxDUfEWOhOt0ReGdBJniu1SRR4s8PKc3pFQghy8HusNUGsufPxxjAU81cdEXj28rGI/Hg598sftfZ9cKwd0fTUNHcuXtn9ZqTBan3bD5/H0zVKHLsQ8R5CLfOBBku6bQYLLKHmQkgCNJ7SzUivdo58oQ+WKQHNkPzY8NsCAwEAAaNmMGQwDgYDVR0PAQH/BAQDAgGmMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFHJbfRmzFT/NxskJIIXIBD5B1bF8MB8GA1UdIwQYMBaAFPmxpz+yl+S23PqaIIltnUBo+KneMA0GCSqGSIb3DQEBBQUAA4IBAQBP9B644oKYXUFw8kkbmNJP0S2R0kW5s33MeBR/ZlXggkVjeAmLOYVeerUdLep6gFYsQkJaTnsAhKP8if0vouoqWOI3nmugQ0LPpJGQ7qhfeaTwYgJnXNUeKLQC4zTR+epG2Z+kuxbsCZedZULMQk5heACl3HAY54O7NTQ97zndRDhQA1T4hfG6ros75F0p/MW1W2AicmX9sf+5H0t1qsFqmRLiIB1rm/qBAToFkaaPl8HPkKcAh90J5NMCh+y+XjOdcfpoWVkLO3KHGXhpuelAHRqAZjoFb14qC+4XvRoI8RJnkCaSKD1mqg3plplQDbCqFiDZe11qlOrFr9O5j257MYICLDCCAigCAQEweTB0MRMwEQYKCZImiZPyLGQBGRYDb3JnMRYwFAYKCZImiZPyLGQBGRYGc2ltcGxlMRMwEQYDVQQKDApTaW1wbGUgSW5jMRcwFQYDVQQLDA5TaW1wbGUgUm9vdCBDQTEXMBUGA1UEAwwOU2ltcGxlIFJvb3QgQ0ECAQIwCQYFKw4DAhoFAKCBiTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMCMGCSqGSIb3DQEJBDEWBBS/ECiM2NrRsx+Ahpq4ZWcAPSKQLjASBgpghkgBhvhFAQkCMQQTAjE5MCAGCmCGSAGG+EUBCQUxEgQQHLG/acFtcN/gQYqLB3E9UDASBgpghkgBhvhFAQkHMQQTAjAyMA0GCSqGSIb3DQEBAQUABIIBAAKIn9IFT1HFGhD2kY+nPJSKP/GxbZ5W3hSh7WVO3SyOOQHZKtHpLZYxLnlryDni0Ysihq6R7KLFfc15ebASCLHx1NB4YlVNdTddPQa/mr63jogRNLP7upZl6+4EaWcHYHGTfhrZe0mZsxSEQJ9dFIB4RdIA9Y3uHKkOXntODwfzMYo6nHMXcYYFxr/HVyqIR/V558EcGqgdEJbDX5+phidquvb7Dc7gTIABQL6pL/CdF4NmAj1G6R9jJdyfhoEv0GvmqG6Mm8KQaFkWMtEUtS2GYnS93L4XdHk43pyXiwywvSFtbU5KECzMkuKAC+CNDSBsF9hu/8Fyq8ULLR//RMM=`

Signing Cert :
-----BEGIN CERTIFICATE-----
MIIDzzCCAregAwIBAgIBAjANBgkqhkiG9w0BAQUFADB0MRMwEQYKCZImiZPyLGQB
GRYDb3JnMRYwFAYKCZImiZPyLGQBGRYGc2ltcGxlMRMwEQYDVQQKDApTaW1wbGUg
SW5jMRcwFQYDVQQLDA5TaW1wbGUgUm9vdCBDQTEXMBUGA1UEAwwOU2ltcGxlIFJv
b3QgQ0EwHhcNMjEwOTI3MTQ0ODU5WhcNMzEwOTI3MTQ0ODU5WjB6MRMwEQYKCZIm
iZPyLGQBGRYDb3JnMRYwFAYKCZImiZPyLGQBGRYGc2ltcGxlMRMwEQYDVQQKDApT
aW1wbGUgSW5jMRowGAYDVQQLDBFTaW1wbGUgU2lnbmluZyBDQTEaMBgGA1UEAwwR
U2ltcGxlIFNpZ25pbmcgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQC8CN8N964HB8Zl7+MEzdQYwERlu7wcLzelygEWWt22dLGkBtdX4MlxBDBHAkBD
L3TTR7isDtfxcGKV2HE76JxANQu3baXtmZ2KW85eaJvEjUTswgR7NZVUMhxqSbcK
bQT+EL7X9VegCNsbvD9wK401zFzAgF9udfpskcnTulTBXlFmX2ZV8Q1HxFjoTrdE
XhnQSZ4rtUkUeLPDynN6RUIIcvB7rDVBrLnz8cYwFPNXHRF49vKxiPx4OffLH7X2
fXCsHdH01DR3Ll7Z/WakwWp92w+fx9M1Shy7EPEeQi3zgQZLum0GCyyh5kJIAjSe
0s1Ir3aOfKEPlikBzZD82PDbAgMBAAGjZjBkMA4GA1UdDwEB/wQEAwIBpjASBgNV
HRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBRyW30ZsxU/zcbJCSCFyAQ+QdWxfDAf
BgNVHSMEGDAWgBT5sac/spfkttz6miCJbZ1AaPip3jANBgkqhkiG9w0BAQUFAAOC
AQEAT/QeuOKCmF1BcPJJG5jST9EtkdJFubN9zHgUf2ZV4IJFY3gJizmFXnq1HS3q
eoBWLEJCWk57AISj/In9L6LqKljiN55roENCz6SRkO6oX3mk8GICZ1zVHii0AuM0
0fnqRtmfpLsW7AmXnWVCzEJOYXgApdxwGOeDuzU0Pe853UQ4UANU+IXxuq6LO+Rd
KfzFtVtgInJl/bH/uR9LdarBapkS4iAda5v6gQE6BZGmj5fBz5CnAIfdCeTTAofs
vl4znXH6aFlZCztyhxl4abnpQB0agGY6BW9eKgvuF70aCPESZ5Amkig9ZqoN6ZaZ
UA2wqhYg2XtdapTqxa/TuY9uew==
-----END CERTIFICATE-----

CA Cert:
-----BEGIN CERTIFICATE-----
MIIDxjCCAq6gAwIBAgIBATANBgkqhkiG9w0BAQUFADB0MRMwEQYKCZImiZPyLGQB
GRYDb3JnMRYwFAYKCZImiZPyLGQBGRYGc2ltcGxlMRMwEQYDVQQKDApTaW1wbGUg
SW5jMRcwFQYDVQQLDA5TaW1wbGUgUm9vdCBDQTEXMBUGA1UEAwwOU2ltcGxlIFJv
b3QgQ0EwHhcNMjEwOTI3MTQ0ODUwWhcNMzEwOTI3MTQ0ODUxWjB0MRMwEQYKCZIm
iZPyLGQBGRYDb3JnMRYwFAYKCZImiZPyLGQBGRYGc2ltcGxlMRMwEQYDVQQKDApT
aW1wbGUgSW5jMRcwFQYDVQQLDA5TaW1wbGUgUm9vdCBDQTEXMBUGA1UEAwwOU2lt
cGxlIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJp7Ii
ZxqAfgFQpY8UYcTcnagZOGXZVaw4uSv2YOV4muiebycaTx970zsbrtuIvOeJ00jZ
o1nOy7lJmSchcfm6SwWIDS+IezLNsKqtO4oexXEeSypxXViDoKCCDTiqphunivbZ
5Sw4osUHtYyqkJ/aCISTneX+JonFJx5Dzrxl4odaCscJ678mgRK90ao/cPkgBwFd
cGT9vDbcPY0JBOS9HSO15oX04IBMCenTdBaNR/WI6mY65vEvR6DksNmWn7SS/Nbj
r4Do7tsoWN3FBe2U61tieHzQDW3yhzfmtYxEeLDrDGgnY719C7c+30qMc4OiZM61
Cya0AAyjA+I3f12jAgMBAAGjYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8E
BTADAQH/MB0GA1UdDgQWBBT5sac/spfkttz6miCJbZ1AaPip3jAfBgNVHSMEGDAW
gBT5sac/spfkttz6miCJbZ1AaPip3jANBgkqhkiG9w0BAQUFAAOCAQEAr/7avSHT
mIwyZyp9cUr252MPIk3LND/UZa/kiZPcdyGHbDS5pAUAhTNDbL/CgeRVJZdphN6K
PdpEGiqmwcaqv8sdEAzAasR9TY6Lk7blIJhPq28BvKpeuHYqtRixm6IYIal2G7QM
4cSVAmLr5Di0ju7sqpMX0EOfmKT5AZ81UcqScNbGuZT6/gjaCev7giaoEODNEoVA
Rr+XmzKtAnA6JtJVlQcpaM2YiMvyfQSY7wkfzfs9Xp+RNElCQ1IuaCk8aiJCUUdb
D1EL+XtvaA5EdGzguClxkvRstPTFv4+Swvuo+uuhbDlz7jtH1wkqpPRl7UT3ZNn5
YkKsNpvTQ/xLlQ==
-----END CERTIFICATE-----

Signature Verification works with OpenSSL and the C# libraries of Bouncy Castle as well.
Only the Java Library fails on the verification and returns false. (used JcaSimpleSignerInfoVerifierBuilder with certificate and public key as well).

On debugging the verification function, it seems that there is some issue with "decrypting" the "signature" and it throws a BadPaddingException of some sorts. The Stack Trace is : 

```
Thread [main] (Suspended)	
	BadPaddingException.<init>(String) line: 58	
	RSAPadding.unpadV15(byte[]) line: not available	
	RSAPadding.unpad(byte[]) line: not available	
	RSASignature$SHA1withRSA(RSASignature).engineVerify(byte[]) line: not available	
	Signature$Delegate.engineVerify(byte[]) line: not available	
	Signature$Delegate(Signature).verify(byte[]) line: not available	
	JcaContentVerifierProviderBuilder$RawSigVerifier(JcaContentVerifierProviderBuilder$SigVerifier).verify(byte[]) line: 315	
	JcaContentVerifierProviderBuilder$RawSigVerifier.verify(byte[]) line: 340	
	SignerInformation.doVerify(SignerInformationVerifier) line: 581	
	SignerInformation.verify(SignerInformationVerifier) line: 616	
	verifyCMSSig.main(String[]) line: 38	
```

Kindly assist.

**Comment by dghgit** [comment]
The stack trace is not from the Bouncy Castle provider.

**Comment by dghgit** [comment]
Not a BC issue.
