### ISSUE TITLE
performance issue with BCFIPS library in NON Approved Mode

### ISSUE THREAD

**Issue by msumit87** [bcgit/bc-java#1038]
Hi @peterdettman ,
Need your inputs on this:
Observed Performance Issue:
BC version: bc-fips-1.0.2.jar
Approved Only Mode: False
Java Version: 1.8.0
Trust Store Type: BCFKS 

Description:

We are facing a huge performance issue while making an outbound call(it is taking around 15-19 seconds ) to do primality test on all  the certificates in the truststore file (Default Truststore file shipped with Java but converted in BCFKS format). 

Please find below the stack trace.
Please let us know your comments and suggestions
Question 1: Is the BC library working correctly i.e why the module is performing FIPS 186-3/SP 800-89 Assurances self-test in  NON Approved Mode ?
Question 2: Is there any property or any other workaround to disable this key validation ?
Question 3: If it is a bug , Is there any plan to fix in future?

"Default-thread-7" #41 prio=5 os_prio=0 cpu=3073.08ms elapsed=277.71s tid=0x00007fab98019800 nid=0x14c5 runnable  [0x00007fab96ff4000]
    236    java.lang.Thread.State: RUNNABLE
    237         at java.math.BigInteger.oddModPow(java.base@11.0.10/BigInteger.java:3081)
    238         at java.math.BigInteger.modPow(java.base@11.0.10/BigInteger.java:2741)
    239         at org.bouncycastle.math.internal.Primes.enhancedMRProbablePrimeTest(Unknown Source)
    240         at org.bouncycastle.crypto.asymmetric.KeyUtils.validatedModulus(Unknown Source)
    241         at org.bouncycastle.crypto.asymmetric.KeyUtils.validated(Unknown Source)
    242         at org.bouncycastle.crypto.asymmetric.AsymmetricRSAPublicKey.<init>(Unknown Source)
    243         at org.bouncycastle.crypto.asymmetric.AsymmetricRSAPublicKey.<init>(Unknown Source)
    244         at org.bouncycastle.jcajce.provider.ProvRSA$RSAKeyFactory.generatePublic(Unknown Source)
    245         at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.getPublicKey(Unknown Source)
    246         at org.bouncycastle.jcajce.provider.X509CertificateObject.getPublicKey(Unknown Source)
    247         at sun.security.validator.PKIXValidator.setTrustedSubjects(java.base@11.0.10/PKIXValidator.java:154)
    248         at sun.security.validator.PKIXValidator.<init>(java.base@11.0.10/PKIXValidator.java:110)
    249         at sun.security.validator.Validator.getInstance(java.base@11.0.10/Validator.java:181)
    250         at sun.security.ssl.X509TrustManagerImpl.getValidator(java.base@11.0.10/X509TrustManagerImpl.java:300)
    251         at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(java.base@11.0.10/X509TrustManagerImpl.java:176)
    252         - locked <0x00000000cb385fa0> (a sun.security.ssl.X509TrustManagerImpl)
    253         at sun.security.ssl.X509TrustManagerImpl.checkTrusted(java.base@11.0.10/X509TrustManagerImpl.java:189)
    254         at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(java.base@11.0.10/X509TrustManagerImpl.java:110)
    255         at com.glide.communications.GlideX509TrustManager.checkServerTrusted(GlideX509TrustManager.java:85)
    256         at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(java.base@11.0.10/SSLContextImpl.java:1510)
    257         at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(java.base@11.0.10/CertificateMessage.java:638)
    258         at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(java.base@11.0.10/CertificateMessage.java:473)
    259         at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(java.base@11.0.10/CertificateMessage.java:369)
    260         at sun.security.ssl.SSLHandshake.consume(java.base@11.0.10/SSLHandshake.java:392)
    261         at sun.security.ssl.HandshakeContext.dispatch(java.base@11.0.10/HandshakeContext.java:443)
    262         at sun.security.ssl.HandshakeContext.dispatch(java.base@11.0.10/HandshakeContext.java:421)
    263         at sun.security.ssl.TransportContext.dispatch(java.base@11.0.10/TransportContext.java:182)
    264         at sun.security.ssl.SSLTransport.decode(java.base@11.0.10/SSLTransport.java:171)
    265         at sun.security.ssl.SSLSocketImpl.decode(java.base@11.0.10/SSLSocketImpl.java:1408)
    266         at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(java.base@11.0.10/SSLSocketImpl.java:1314)
    267         at sun.security.ssl.SSLSocketImpl.startHandshake(java.base@11.0.10/SSLSocketImpl.java:440)
    268         at sun.security.ssl.SSLSocketImpl.ensureNegotiated(java.base@11.0.10/SSLSocketImpl.java:819)
    269         at sun.security.ssl.SSLSocketImpl.getSession(java.ba
    
    Please let me know if you need any other details.

**Comment by dghgit** [comment]
In answer to 1. It's supposed to regardless, the same applies to the start up and other health tests.
The answer to the other 2 is no. For the reason given above.
The provider uses a weak reference cache to minimize the amount of times the testing is done. You should be able to keep it loaded by holding on to the moduluses. I'd also check you are not running out of entropy.
