### ISSUE TITLE
Cannot load bcprov on linux/macos and Java 11

### ISSUE THREAD

**Issue by gstanchev** [bcgit/bc-java#1041]
Trying to run a simple program that fails to load on Linux and MacOS but succeeds on Windows. Not sure if BC issue or Java issue but it doesn't occur without BC. We have modified a Java 11 java.security in preparation for running in approved-only FIPS mode. See attached files for more information on the issue, reproduce instructions. It seems it is choking on the X9.62 curves in the "jdk.disabled.namedCurves". Pruning those work on all OSes. Please advise on the nature of this issue..

[files-to-reproduce-and-output.zip](https://github.com/bcgit/bc-java/files/7332957/files-to-reproduce-and-output.zip)
.

**Comment by dghgit** [comment]
I couldn't actually reproduce this. One thing securerandom.strongAlgorithms should read:

securerandom.strongAlgorithms=NativePRNGBlocking:SUN

and I'd recommend getting rid of 

security.provider.4=com.sun.net.ssl.internal.ssl.Provider BCFIPS

and doing a "fips:org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider" on the BCJSSE instead. With Java 11 loading a provider by name from another provider on startup did suddenly become a bit problematic.

**Comment by mouse07410** [comment]
@dghgit could you help figuring out how to add security providers to Java-11 and Java-17 config? I've two additional security providers - BC and OpenSC-PKCS11. On attempt to use them, app aborts with "class not found". I suspect it's related to ability or inability to locate the module/jar that contains the relevant Providers class...

What should java.security changes look like, if those extra jars in question reside in /Library/Java/Extensions directory?

**Comment by dghgit** [comment]
No idea on this one. Sorry. Java 11 did get rid of jre/lib/ext which is the Linux equivalent (in some ways), these days in my world things usually need to be on the module path or the class path explicitly. The same might have happened with the Apple JVM.
