### ISSUE TITLE
Can't access user keying material (UKM) from KeyAgreeRecipientInformation

### ISSUE THREAD

**Issue by gnarea** [bcgit/bc-java#1043]
I'm using BC to produce some `EnvelopedData` values with `KeyAgreeRecipientInfo`, and I want to write a unit test to make sure that my implementation is generating and setting the UKM. However, there's no way to get the UKM from a `KeyAgreeRecipientInformation`: This value is available under the [private field `KeyAgreeRecipientInformation.info`](https://github.com/bcgit/bc-java/blob/f91b10a67ffdb5a1318ca24fdc07322f6591a6be/pkix/src/main/java/org/bouncycastle/cms/KeyAgreeRecipientInformation.java#L26) and `KeyAgreeRecipientInformation` doesn't offer any way to get the UKM.

Would you accept a PR that exposes the UKM via `KeyAgreeRecipientInformation.getUserKeyingMaterial()`? Alternatively, we could make the `KeyAgreeRecipientInfo` instance public but that's probably an overkill.

**Comment by dghgit** [comment]
I've added the getUserKeyingMaterial() method. Should appear on github shortly.
