### ISSUE TITLE
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting ECIESwithAES

### ISSUE THREAD

**Issue by gopikrishna1998** [bcgit/bc-java#1046]
Facing the following error after upgrading from BouncyCastleCrypto-1.54 to BouncyCastleCrypto-1.67.
```
Caused by: java.lang.RuntimeException: Could not generate a cipher with algorithm <ECIESwithAES>
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting ECIESwithAES
```
It seems from [here](https://github.com/bcgit/bc-java/commit/9385b0ebd277724b167fe1d1456e3c112112be1f#diff-17a8120271fb3d31b7112618aa8b048244d27d3c8711e36b5f8102ada07fe9ca) the support for this algorithm is no longer present. I could not find any suggestions for the replacement algorithm that can be used. Could someone please help to understand why this algorithm is no longer supported and what is the recommendation for its replacement?

**Comment by dghgit** [comment]
The approach isn't regarded as safe.

You could implement the old approach again using the BC low-level API classes for backwards compatibility reasons, I'd regard it as a very short term strategy though.
