### ISSUE TITLE
BC-FIPS causing 100% CPU

### ISSUE THREAD

**Issue by gugan21** [bcgit/bc-java#1048]
Our application is using BCFIPS for signing and verification. It was noticed that after integrating BC-FIPS libraries, CPU was hitting 100% usage, for concurrent 12k requests on our component. On monitoring via jvisualvm it was found that SAML threads were taking lot of CPU. Reason for more CPU usage in SAML threads was because of request signing and response sign verification by BC-FIPS library functions.

<img width="1405" alt="bcfips" src="https://user-images.githubusercontent.com/8341271/138632819-1428f9c7-f712-4622-b2ba-8e12b1d803e9.png">

If we use the alternatives including the BouncyCastleProvider (Without FIPS), we are not observing the issue.

**Comment by dghgit** [comment]
It's doing a full RSA key validation, as required. Usually the trick with this is to make sure the RSA key only has to be imported into the module once - this means it either needs to be in a certificate created by the module, or passed through a key factory that is created from the module before being used for signing operations.

**Comment by dghgit** [comment]
Appears to be dead.
