### ISSUE TITLE
OCSP: SASSA_PSS multiple digest algorithms

### ISSUE THREAD

**Issue by MicheleOcchipinti** [bcgit/bc-java#1049]
Parsing an instance of "org.bouncycastle.asn1.ocsp.BasicOCSPResponse" I see that the the resp.signatureAlgorithm has parameters that contains the identifier for digest algorithm and the identifier for Mask generation function. Is There a method that automatically switch between the possible parameters of the signature Algorithms?
In other word How to determinate the sha algorithm in case of RSASSA_PSS, The identifier "1.2.840.11354.1.1.10" could be related to SHA1-SHA224-SHA512-SHA384

![image](https://user-images.githubusercontent.com/47862950/138723951-96a6b823-d06f-4598-a015-0f3a8b1b59fb.png)

**Comment by dghgit** [comment]
We probably should at least be checking it...

**Comment by dghgit** [comment]
I've added org.bouncycastle.operator.DefaultSignatureNameFinder - it's basically a refactoring of what was in OperatorHelper.
