### ISSUE TITLE
BCPG ArmoredInputStream does not handle mixed EOL types in headers.

### ISSUE THREAD

**Issue by JackDca** [bcgit/bc-java#1056]
In org.bouncycastle.bcpg.ArmoredInputStream, the method parseHeaders() sets a boolean crLf if it sees a CR-LF line ending anywhere in the headers. After parsing the header (at line 283 in commit bd99562 dated 2021-10-12), and if crLf is true, it reads and discards one byte with the intention of discarding the LF. Unfortunately, some armored data mixes both types of line endings. If the header line ended with LF only, the character that is discarded is the first character of the next line. If the blank line between headers and the base64 body has LF only, while any of the preceding header lines has CR-LF, the first character of the base64 body is lost, making the base64 data unusable.

It could be argued that an armored message should use just one type of line ending, which is a fair comment.

On the other hand, the point of armored data is to avoid this kind of problem, especially since email servers have a bad habit of messing with line endings. Also, there is data out there which has inconsistent line endings. Specifically, I encountered the issue when using (as test data) a [Autocrypt setup message](https://autocrypt.org/level1.html#autocrypt-setup-message) generated by [Delta Chat](https://delta.chat/en/). (I'm using Debian's libbcpg-java 1.68.) Notably, GnuPG processes the same data without a problem.

I am a complete newbie to Bouncy Castle but am willing to submit a PR for a fix but there is probably someone in the Legion who could do this and test it much quicker than I could.

Many thanks to the developers for making Bouncy Castle available!!

**Comment by JackDca** [comment]
Created an issue on [Delta Chat](https://github.com/deltachat/deltachat-android/issues/2119).

**Comment by dghgit** [comment]
I hate to be the bearer of bad news, but systems use one of "\r\n", "\r", and "\n", it's not just "\r" and "\r\n". We need to be able to deal with all three. In the context of this request a "\r" followed later by a "\r\n" should mean the second line end is interpreted as a blank line, whereas a blank line should probably be "\r\r".  This one sounds awfully like something which could easily cause unintended consequences.

**Comment by JackDca** [comment]
Agreed. There are some mixed line ending combinations which are ambiguous and can't be fixed with certainty. (Hence the Deltachat issue referenced above.) But in the example given, BC discards a "printable" character, which can never be the right thing to do. 

One approach would be to treat every "\r" and "\n" as a line ending, **except** that a "\n" which immediately follows a "\r" is discarded. This would at least handle every **non-ambiguous** line ending correctly (including the example given). I think that's usually what the existing code does, but not always.

From the issue on Deltachat:

`If the only types of line endings were LF (e.g. 'nix) and CR-LF (e.g. Windows) it would be possible to program around mixed line endings by discarding all CRs. Unfortunately some systems, notably old (< OSX) Macs use CR alone as a line ending. So if a header line ends CR-LF and the goal is to accept any mixture of line endings, there is a fundamental ambiguity (is there a blank line or not?) that can only be resolved by more complex analysis of the data.`

**Comment by dghgit** [comment]
Yes, unfortunately the comment from Deltachat is not how things work.

I think it would make more sense to write a filter that corrects the line endings explicitly, apart from anything this would work with other software as well, but it would also mean you could take into account local interpretation in line with your own policy. We're trying to produce a general purpose API, consistency is everything.

**Comment by dghgit** [comment]
I'm closing this one off, I have made one change though - if crlf is now true, rather than swallowing the next character, we'll at least check it's what we expect it to be and flag an error if it isn't. It will, at least, provide people with a pointer to what the actual problem with a file is. The change should show up in github shortly.

**Comment by JackDca** [comment]
Agreed - that's a safe approach. Thanks.
