### ISSUE TITLE
cannot handle supplied parameter spec: NONCE in IES Parameters needs to be 16 bytes long

### ISSUE THREAD

**Issue by gopikrishna1998** [bcgit/bc-java#1057]
Updated encryption algorithm from `ECIESwithAES` to `ECIESwithSHA384andAES-CBC` and started getting the following error (using BouncyCastleCrypto provider) while decrypting in unit testing. I am a beginner in cryptography. Could someone please help to understand what this issue means and how to resolve?
```
cannot handle supplied parameter spec: NONCE in IES Parameters needs to be 16 bytes long
```

**Comment by dghgit** [comment]
The nonce is used as an initialization vector for the block cipher in this case. AES has a block size of 16 bytes so the nonce needs to reflect that.
