### ISSUE TITLE
CMSProcessableInputStream is package private - why?

### ISSUE THREAD

**Issue by erik-wramner** [bcgit/bc-java#1058]
I would like to use `CMSProcessableInputStream`, but it is package private while `CMSProcessableByteArray` and `CMSProcessableFile` are public. Converting the input stream I have into a byte array is not optimal as it may not fit in memory. Likewise I would like to avoid temporary files if possible.

I can submit a PR (it is just the word `public` in front of the class), but is there a good reason for not making that class public? I can't see why it would be in worse shape than the byte buffer or file options?

EDIT: `CMSReadable` is also package private, which makes it hard to create a compatible class outside the library.

**Comment by dghgit** [comment]
Usually people use the *StreamGenerator classes for this. Is there a reason why this wouldn't work? If you are dealing with large files the classes that take the Processable objects are likely to run out of memory.

**Comment by erik-wramner** [comment]
I'm dealing with an existing code base (Camel) that does things like:

```
    private byte[] createSignature(MimeEntity data, CMSSignedDataGenerator signer) throws IOException, CMSException {
        try (ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
            data.writeTo(bos);
            bos.flush();
            CMSTypedData contentData = new CMSProcessableByteArray(bos.toByteArray());
            CMSSignedData signedData = signer.generate(contentData, false);
            return signedData.getEncoded();
        }
    }

```
I'm trying to refactor the code to support large entities and `CMSProcessableInputStream` seemed to be the natural replacement. I'll see if I can get something working with `CMSSignedDataStreamGenerator`.

**Comment by erik-wramner** [comment]
It worked. I still find it a bit weird that `CMSProcessableFile` is public but not `CMSProcessableInputStream`, but then all frameworks have their wrinkles.
