### ISSUE TITLE
Unneccessary Keccak toHexString conversation

### ISSUE THREAD

**Issue by Karasiq** [bcgit/bc-java#1065]
It slows Keccak hash computation significantly.

https://github.com/bcgit/bc-java/blob/97c8dc72e8ed2df9527155af5a8f56d60b11c462/core/src/main/java/org/bouncycastle/crypto/digests/KeccakDigest.java#L318

**Comment by peterdettman** [comment]
Thanks, I've reverted the code from this unfortunate debug commit.
