### ISSUE TITLE
EC AlgorithmParameters getEncoded is not right

### ISSUE THREAD

**Issue by xiezhaokun** [bcgit/bc-java#1069]
When using AlgorithmParameters init NamedCurve, the value obtained by calling the getEncoded method is different from the value obtained by the JDK calling getEncoded.
```
Provider bc = new BouncyCastleProvider();
NamedCurve namedCurve = CurveDB.lookup("secp256r1");
byte[] bcBytes= ECUtil.encodeECParameterSpec(bc,namedCurve);

Provider ec = new SunEC();
byte[] ecBytes = ECUtil.encodeECParameterSpec(ec,namedCurve);
if(!Arrays.equals(bcBytes,ecBytes)) {
     System.err.println("Not equal");
}
```

**Comment by dghgit** [comment]
Sorry, but this does not make any sense, NamedCurve is an internal sun class, there's no way we could provide support for it.

Exactly what are you trying to do?

**Comment by xiezhaokun** [comment]
> 
Version 11.0.12 of jdk supports calling the lookup method of NamedCurve to create an instance of NamedCurve, where lookup is a public method.

**Comment by xiezhaokun** [comment]
> Sorry, but this does not make any sense, NamedCurve is an internal sun class, there's no way we could provide support for it.
> 
> Exactly what are you trying to do?
Version 11.0.12 of jdk supports calling the lookup method of NamedCurve to create an instance of NamedCurve, where lookup is a public method.

**Comment by dghgit** [comment]
It's still an internal class, they may well change it. There's no way we can go near it.

If you want to do it in a portable fashion you can use ECGenParameterSpec to generate parameters for named curves.
