### ISSUE TITLE
bctls-jdk15on 1.70 not (yet) on Maven Central

### ISSUE THREAD

**Issue by bkrahl-nli** [bcgit/bc-java#1070]
After upgrade our Bouncy Castle libs from 1.69 to 1.70 I noticed that [bctls-jdk15on](https://search.maven.org/artifact/org.bouncycastle/bctls-jdk15on) is not on Maven Central.

Could you please push the lib?

**Comment by moonfruit** [comment]
Add [bcprov-ext-jdk15on](https://search.maven.org/artifact/org.bouncycastle/bcprov-ext-jdk15on) 1.70 is also not in Maven Central.

**Comment by jebeaudet** [comment]
We're having the same errors here

It's listed here : 
https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on

But not here : 
https://search.maven.org/search?q=a:bcprov-ext-jdk15on

And it's breaking our build so something is messed up somewhere! Thanks

**Comment by dghgit** [comment]
Okay, these artifacts are now uploaded correctly.
