### ISSUE TITLE
Using BouncyCastle to retrieve the acceptable client CA names from TlsCertificate

### ISSUE THREAD

**Issue by ccarv** [bcgit/bc-java#1071]
I'm trying to identify the acceptable CA names ([RFC 5246](https://www.rfc-editor.org/rfc/rfc5246#page-53)) using BouncyCastle, if that's even at all possible. I've searched for documentation in regards to this but haven't had any luck. I typically use `openssl` to retrieve this list and want to automate this process. The Java API, from my understanding, does not provide this level of information which is why I've turned to BC.

If this is possible, how would I write the code with the following implementation?

```java
Socket socket = ...
TlsClientProtocol protocol = ...

protocol.connect(new DefaultTlsClient(new BcTlsCrypto(new SecureRandom())) {

    @Override
    public TlsAuthentication getAuthentication() throws IOException {
        return new ServerOnlyTlsAuthentication() {
    
            @Override
            public void notifyServerCertificate(final Certificate cert) throws IOException {
                TlsCertificate[] certs = cert.getCertificate().getCertificateList();

                for (int i = 0; i < certs.length; i++) {
                    System.out.println("Cert: " + ((Certificate) certs[i]).getIssuer().toString()):
                }
            }
        };
    }
}
```

**Comment by peterdettman** [comment]
Do you mean the list of acceptable CAs from the CertificateRequest message? That would be used for guiding selection of a client certificate. The CertificateRequest is passed as an argument to `TlsAuthentication.getClientCredentials`, and the list of CAs is available via `CertificateRequest.getCertificateAuthorities`, which returns (either null or) a `java.util.Vector` of `org.bouncycastle.asn1.x500.X500Name`, each corresponding to an acceptable CA.

**Comment by ccarv** [comment]
@peterdettman Big thank you!
