### ISSUE TITLE
bcjmail-jdk15on 1.70 not available from maven central

### ISSUE THREAD

**Issue by yersan** [bcgit/bc-java#1072]
Recently BC 1.70 was released, however, at the moment of writing, the Jakarta EE 9+ artifact is not yet available in maven central:

https://repo.maven.apache.org/maven2/org/bouncycastle/bcjmail-jdk15on/

Looks like it is still pending its release.

**Comment by dghgit** [comment]
Now fixed, Apologies.

**Comment by yersan** [comment]
Thanks, @dghgit , however, what about the `bcjmail-jdk15on` artifact? I can see `bcmail-jdk15to18` in maven central, but I'm still missing `bcjmail-jdk15on`

**Comment by dghgit** [comment]
It should show up soon, if not by now already - I can see it repo1.maven.org, things should be quietly propagating in the background. If it still hasn't shown up in a couple of hours let me know here and I'll see if there's anything I can do to kick the process along a bit.
