### ISSUE TITLE
JcaContentSignerBuilder() frozen on BC 1.70 and perhaps BC 1.69.

### ISSUE THREAD

**Issue by textbrowser** [bcgit/bc-java#1073]
Hello.

I'm using bcpkix-jdk15on-170.jar and bcprov-ext-jdk15on-170.jar (downloaded from https://bouncycastle.org/download) in an Android application.

public class ...
{
static
{
 Security.addProvider(new BouncyCastleProvider());
 new JcaContentSignerBuilder("SHA256WithRSA").setProvider("BC");
 Log.e("F.", "F.");
}
}

The statement Log.e() is not reached.

The same application on the same device using BC 1.68 functions correctly.

Thanks! :)

**Comment by dghgit** [comment]
This smells an awful lot like a classloader issue. I suspect you'll find the same issue applies with 1.68, you're just not seeing it here. If you have a look at the source for the class concerned, you'll see it's a simple constructor, I'd look for the BC classes appearing somewhere else in the classpath.

**Comment by textbrowser** [comment]
Very interesting. I'm not familiar with the class loader. I'll look there next. Thank you for the help. :)

**Comment by textbrowser** [comment]
OK.

I removed my local libraries.

And changed

dependencies {
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:appcompat-v7:25.4.0'
    implementation 'com.android.support:design:25.4.0'
    implementation 'com.android.support:support-v4:25.4.0'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation files('libs/bcpkix-jdk15on-168.jar')
    implementation files('libs/bcprov-ext-jdk15on-168.jar')
    testImplementation 'junit:junit:4.12'
}

to

dependencies {
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:appcompat-v7:25.4.0'
    implementation 'com.android.support:design:25.4.0'
    implementation 'com.android.support:support-v4:25.4.0'
    implementation 'org.bouncycastle:bcpkix-jdk15on:1.70'
    implementation 'org.bouncycastle:bcprov-jdk15on:1.70'
    testImplementation 'junit:junit:4.12'
}

in build.gradle. Then it magically works. :) I'm closing!
