### ISSUE TITLE
Few more bc jars missing from Maven Central for 1.70 release

### ISSUE THREAD

**Issue by chrismathews** [bcgit/bc-java#1074]
Hey everybody,

I think there are still a handful of jars missing from Maven Central for the 1.70 release. The vast majority are there but I could not find the 1.70 jars for the following:
- bcprov-ext-debug-jdk14: https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-ext-debug-jdk14/
- bcprov-debug-jdk14: https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-debug-jdk14/
- bcprov-ext-debug-jdk15on: https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-ext-debug-jdk15on/
- bcprov-ext-debug-jdk15to18: https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-ext-debug-jdk15to18/

If those are uploaded then I think everything will be in order. I know the release process for Maven Central is a bit painful and I appreciate the work that you all do!

**Comment by dghgit** [comment]
These should also be starting to appear. Sorry for the delay.
