### ISSUE TITLE
Is it thread-safe => BouncyCastleProvider  ?

### ISSUE THREAD

**Issue by kevincaradant** [bcgit/bc-java#1075]
Hi guys

I'm wondering if this object is thread-safe ? BouncyCastleProvider
Why I'm asking that, it''s because I read on stackoverflow and here that BouncyCastleProvider() has a memory leak. 
              - https://stackoverflow.com/questions/63909806/memory-leak-at-bouncycastle-jce-provider
              - https://bugs.openjdk.java.net/browse/JDK-8168469

So intead to have this: `encryptorBuilder.setProvider(new BouncyCastleProvider());`

I replaced by this: `encryptorBuilder.setProvider(getinstance());`

So we have this after the workaround:
```
JceOpenSSLPKCS8EncryptorBuilder encryptorBuilder = new JceOpenSSLPKCS8EncryptorBuilder();
			encryptorBuilder.setProvider(getinstance());
			encryptorBuilder.setRandom(new SecureRandom());
			encryptorBuilder.setPassword(passphrase.toCharArray());
			OutputEncryptor encryptor = encryptorBuilder.build();
```

And I transformed the instance into a singleton like this:

```
private static synchronized BouncyCastleProvider getinstance () {
	  if (bouncycastleprovider == null) {
	      bouncycastleprovider = new BouncyCastleProvider();
	  }
	  return bouncycastleprovider;
}
```

I checked with some performances tests and no RAM issues anymore like that :)
	
But now I would know if it's thread safe because using a singleton, i guess it could be an issue to have something not thread-safe ? 

Thank you in advance for your answer 

Regards

**Comment by dghgit** [comment]
Yes, it's safe to use this as a singleton. The JCA relies on it.
