### ISSUE TITLE
Memory leak on bouncycastle.jce.provider ?

### ISSUE THREAD

**Issue by kevincaradant** [bcgit/bc-java#1076]
Hi,

During huge performance tests, we saw that `encryptorBuilder.setProvider(new BouncyCastleProvider()); ` generated a memory leak with RAM which increased continiously  until the server crash for an issue of out of memory.

It's seems known since some months / years.
  - https://bugs.openjdk.java.net/browse/JDK-8168469
  - https://stackoverflow.com/questions/63909806/memory-leak-at-bouncycastle-jce-provider

But I didn't see a fix about it since it was reported. 
I'm running on the latest version available (v1.70) and I can confirm the problem is still here.
We're running on JDK11.

We use this one : 
```
https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on/1.70
```

Are you aware about the problem ? 
Do you know if it will be fixed soon ? 

Thanks 

Regards

**Comment by dghgit** [comment]
We've heard of it, but sorry we have no insight on when/whether this is likely to be fixed. It's a bit of an odd one - providers are usually managed as singletons so I can sort of see why Oracle wouldn't be regarding this as a high priority item. I'm wondering if providing a getInstance() method of our own would help here.

**Comment by kevincaradant** [comment]
I think it could help to add this method.

That could help us to create an instance without have a memory leak ;)

We didn't find a lot of documentation about thread-safe so we didn't was sure to use the good implementation with the getInstance(). You confirmed ([ in the otherticket](https://github.com/bcgit/bc-java/issues/1075) )  that it was the right implementation so perfect.

If you add in the next releases this method, don't hesitate to tell me about it.

Thank you

Regards
