### ISSUE TITLE
OpenPGP broken on versions > 1.66

### ISSUE THREAD

**Issue by Redirion** [bcgit/bc-java#1078]
Hi everyone,

this commit does not seem to have been backed into the releases:
https://github.com/bcgit/bc-java/commit/dbf0f6159253f4334d0f8dfe0e05d3aab81a5350

the methods modOddInverse and modOddInverseVar are missing in the BigIntegers.class in the bcprov-jdk15on jars.

But as bcpg-jdk15on tries to use them for the PGPSecretKey extractPrivateKey method it fails with a NoSuchMethodError.

Please let me know if I did anything wrong. I also checked the debug and ext releases, in all cases these two methods are absent.

As soon as I downgrade to 1.66 it works.

**Comment by peterdettman** [comment]
Are you using the latest version of all the jars? Are you sure you don't have old versions in the classpath?

**Comment by Redirion** [comment]
okay, strange. `javap -cp bcprov-jdk15on-1.67.jar org.bouncycastle.util.BigIntegers` shows that the methods exist
` public static java.math.BigInteger modOddInverse(java.math.BigInteger, java.math.BigInteger);
  public static java.math.BigInteger modOddInverseVar(java.math.BigInteger, java.math.BigInteger);`

**Comment by Redirion** [comment]
found the issue. 
PDFBox standalone 2.0.24 contains bouncycastle in an older version (< 1.67). This was shadowing the new BigIntegers class

Thanks @peterdettman
