### ISSUE TITLE
No such algorithm exception for all digest algorithms.

### ISSUE THREAD

**Issue by dtsonov** [bcgit/bc-java#1080]
I get:
"no such algorithm: SHA3-256 for provider BC"
when try to use SHA3-256 digest. 
Also I get "no such algorithm: "exception for all digest algos.
I did try BC v.1.57, 1.65, 1.70 from into an empty Andorid studio project, as dependecy in gradle.build: 
implementation 'org.bouncycastle:bcpkix-jdk15on:1.70'

my test code:
---
import java.security.Security;
import java.security.MessageDigest;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
. . .
public byte[] getDigest(byte[] data) throws GeneralSecurityException {
            Security.addProvider(new BouncyCastleProvider());
            MessageDigest hash = MessageDigest.getInstance("SHA3-256", "BC");
            return hash.digest(data);
   }
---
Any help is welcome.

**Comment by dghgit** [comment]
The provider is in bcprov-jdk15on. You mention Android though, you might be better off with bcprov-jdk15to18.

**Comment by dtsonov** [comment]
Actually the prblem was that I was init the provider this way: 
Security.addProvider(new BouncyCastleProvider());
instead of  Security.getProvider(BouncyCastleProvider.PROVIDER_NAME);
But you're right, the correct provider version is important too.
