### ISSUE TITLE
Equals() Method of BCECPublicKey

### ISSUE THREAD

**Issue by kaikramer** [bcgit/bc-java#1083]
If there is the same EC public key once as an `ECPublicKeyImpl` object and once as `BCECPublicKey`, then the result of the `equals() ` method is `true` for the `ECPublicKeyImpl` variant (which is obviously correct because it is the same key) and `false` for the `BCECPublicKey` version. 

That is because the implementation of `BCECPublicKey` checks for `instanceof BCECPublicKey`:
```
public boolean equals(Object o)
{
    if (!(o instanceof BCECPublicKey))
    {
        return false;
    }

    BCECPublicKey other = (BCECPublicKey)o;

    return ecPublicKey.getQ().equals(other.ecPublicKey.getQ()) && (engineGetSpec().equals(other.engineGetSpec()));
}
```

Instead it should check for `instanceof ECPublicKey` and then maybe compare the DER encoding of the two public keys.

For RSA keys this issue does not exist, because the equals() method of  `BCRSAPublicKey` checks for `instanceof RSAPublicKey`.

**Comment by dghgit** [comment]
There's a bit of history here - unlike the RSA key, the BC EC public key predates the JVM internal one by about 10 years... I can see why it seems a bit odd so I've done as asked. There's still a bit of a nit with hashCode() but it's probably not a good idea for me to change that.

**Comment by dghgit** [comment]
This is now up in https://www.bouncycastle.org/betas 171 b04 or later.
