### ISSUE TITLE
ECUtil.getCurveName() does not recognize Ed25519 curves

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#1087]
When calling
```
ECPublicBCPGKey key = ... // generate/load PGP key based on Ed25519
ASN1ObjectIdentifier identifier = key.getCurveOID(); // "1.3.6.1.4.1.11591.15.1"
String curveName = ECUtil.getCurveName(identifier); // expect "ed25519", got null
```

I get `null` as curveName while I expect "ed25519".
See http://oid-info.com/get/1.3.6.1.4.1.11591.15.1

The curve is likely not properly entered into BCs curve tables.

**Comment by dghgit** [comment]
It's a little more complicated than that... while they're both EC algorithms the mathematical presentation for them is different, so while there's an overlap as one curve X25519 is specified in both forms, the regular EC curves and the Ed curves are not quite the same thing. I've added a method on PGPUtil for looking up the curve name - it will return a name in the same way as the OID is described in the draft RFC.

**Comment by dghgit** [comment]
Okay, this should now be in place. The new method is at:

https://github.com/bcgit/bc-java/blob/269be030d1158a907f0a99c0247187b43250ef35/pg/src/main/java/org/bouncycastle/openpgp/PGPUtil.java#L130

I think it should do the trick. Now also up in https://www.bouncycastle.org/betas 171 b04 or later.

**Comment by vanitasvitae** [comment]
Apparently the patch does use some wrong curve OIDs. See #1142 for details.
