### ISSUE TITLE
SignedMailValidator cannot access jakarta.mail.internet.MimeMessage

### ISSUE THREAD

**Issue by shred** [bcgit/bc-java#1092]
I'm using `bcjmail-jdk15on` 1.70, which is the jakarta mail flavor of bcmail. However, when I try to validate a S/MIME signature, I get this exception:

`
java.lang.IllegalAccessError: class org.bouncycastle.mail.smime.validator.SignedMailValidator (in module org.bouncycastle.mail) cannot access class jakarta.mail.internet.MimeMessage (in module jakarta.mail) because module org.bouncycastle.mail does not read module jakarta.mail
`

If I see it correctly, there should be a `requires jakarta.mail;` added to bcjmail's `module-info.java` file. Or do I miss something important here?

**Comment by dghgit** [comment]
No it should have been there. Try the latest on https://www.bouncycastle.org/betas

**Comment by shred** [comment]
I can confirm it's working with bcjmail-jdk18on-171b07 now. Thank you!

**Comment by dghgit** [comment]
And thank you!
