### ISSUE TITLE
"additional data" in HMacDSAKCalculator

### ISSUE THREAD

**Issue by schildbach** [bcgit/bc-java#1097]
This is a feature request.

In `HMacDSAKCalculator`, allow for the "additional data" field as per https://datatracker.ietf.org/doc/html/rfc6979#section-3.6

It's needed to grind for low R values, and probably other usecases as well, see https://github.com/bitcoin/bitcoin/pull/13666

**Comment by peterdettman** [comment]
I've added an overridable method `HMacDSAKCalculator#initAdditionalInput0` in which the `HMac` may be updated with additional input at the relevant point. Please note that a signer may be used for multiple signatures and therefore a single instance of `HMacDSAKCalculator` may perform several calculations.

**Comment by schildbach** [comment]
For the records, I just found another adaption of the class here: https://github.com/bitcoin-s/bitcoin-s/blob/master/crypto/.jvm/src/main/scala/org/bitcoins/crypto/HMacDSAKCalculatorWithEntropy.scala

**Comment by schildbach** [comment]
Have you pushed your PR / commit already? I can't find it.

**Comment by peterdettman** [comment]
It takes time to mirror. At a quick glance it should let you avoid duplicating most of that class, and subclass instead.

**Comment by zpv** [comment]
Hey @peterdettman, I noticed that this additional data is only added to the first call of `HMac_K`, whereas other implementations (e.g. [bitcoin-s](https://github.com/bitcoin-s/bitcoin-s/blob/4913b124313cdc19cc627f195eb923c866b0092b/crypto/.jvm/src/main/scala/org/bitcoins/crypto/HMacDSAKCalculatorWithEntropy.scala#L71-L85) and secp256k1) append it to the second call as well. This is resulting in divergent signatures when providing the same additional data across bouncy-castle vs. other impls.

Re-reading the spec, the correct behavior is ambiguous :/

**Comment by peterdettman** [comment]
I've now added a second overridable method `HMacDSAKCalculator#initAdditionalInput1` to make this more flexible.
