### ISSUE TITLE
Safe Curves

### ISSUE THREAD

**Issue by franziskuskiefer** [bcgit/bc-java#110]
Hi all,

I wonder if anyone thought about implementing some of the safe curves for ECC (cf. http://safecurves.cr.yp.to/)? I noticed there's currently no Java implementation for any of them (despite WhisperSystems [curve25519](https://github.com/WhisperSystems/curve25519-java), which is GPLv3). If this is not on anyone's agenda, I might give it a try when I find some time.

**Comment by peterdettman** [comment]
Sort of: see the org.bouncycastle.math.ec.custom.djb package for an implementation of curve25519, but it uses (short) Weierstrass form and the same formulae as our other curves; we are still missing a few utility methods that you'd want for interoperating with the usual implementation. It's usable via CustomNamedCurves.getByName("curve25519") (and see some relevant comments in CustomNamedCurves.curve25519.createParameters).

I should add that, although this curve is included in our test suites, it's not been tested for interop at all. Most of the benefits from choosing curve25519 are lacking, including performance being around the same as P-256.

We do hope to extend our APIs to support other curve forms (particularly Edwards and Montgomery) more directly, but there's no real timeline.
