### ISSUE TITLE
Performance - KeyPairGenerator - EC

### ISSUE THREAD

**Issue by boaks** [bcgit/bc-java#1100]
Bouncy Castle - bcprov-jdk15on - 1.70

I tried to analyze a left over in the open source project [Eclipse/Californium](https://github.com/eclipse/californium) from last year [Long loading time for class XECDHECryptography](https://github.com/eclipse/californium/issues/1649).

Californium checks on startup, if a list of curves is supported by the JCE. Therefore it mainly generates a EC keypair for the provided curves. With SunEC that takes time, but we didn't receive complaints about that. BC takes much longer, it seems, especially on some android systems. There up to 10s have been reported.

```
try {
	String algo = "secp256r1";
	long times[] = new long[3];
	long start = System.nanoTime();
	KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("EC", provider);
	times[0] = System.nanoTime() - start;
	ECGenParameterSpec genParams = new ECGenParameterSpec(algo);
	keyPairGenerator.initialize(genParams, random);
	times[1] = System.nanoTime() - start;
	keyPairGenerator.generateKeyPair().getPublic();
	times[2] = System.nanoTime() - start;
	System.out.format("%18s %s: %10d%n", provider.toString(), algo, times[2]);
	System.out.format("   %10d %10d%n", times[0], times[1]);
} catch (InvalidAlgorithmParameterException ex) {
	ex.printStackTrace();
} catch (NoSuchAlgorithmException ex) {
	ex.printStackTrace();
}
```

My times on ubuntu/java8:

```
SunEC version 1.8 secp256r1:   17260094
        59473     357506
    BC version 1.7 secp256r1:  197245461
     12276845  178087941
    BC version 1.7 secp256r1:    1900402
        13105      51357
```

I read a lot of comments in stackoverflow or similar platforms, about the SecureRandom. 
What makes me struggling: It seems, that this affects only the first time when such a key pair is constructed.
A new SecureRandom is still fast for the second time a ec key pair is created.

1. is there a way to speed up also the first time a key pair is created?
2. is experience with android available?

**Comment by boaks** [comment]
I'm not sure, if this is related to #143. Maybe, there is also a solution for ECDH?

**Comment by peterdettman** [comment]
SecureRandom can be slow to init when there is a lack of entropy. Just call nextInt() once before your other timings to exclude that from the initialization benchmark.

However there is certainly a sort of "static initialization cascade" happening here, which leads to all our curves getting fully configured on the first attempt to use any of them. We do attempt to do this lazily, but it is being unnecessarily forced as a side-effect of the EC5Util static constructor. I am working on a patch to this.

ECGOST3410NamedCurves also doesn't properly use the lazy init, and is a big contributor to this issue. This is straightforward to fix.

Finally, it is probably excessive to try and actually generate a KeyPair. In the BCJSSE code we have the same concern over what curve names are supported. See https://github.com/bcgit/bc-java/blob/5d51c20fd2deaaf7642853381e58733328a954e1/tls/src/main/java/org/bouncycastle/tls/crypto/impl/jcajce/ECUtil.java#L203, which calls through to https://github.com/bcgit/bc-java/blob/5d51c20fd2deaaf7642853381e58733328a954e1/tls/src/main/java/org/bouncycastle/tls/crypto/impl/jcajce/ECUtil.java#L141 . You can see that we consider the curve supported if we can generate an ECParameterSpec for it, although we also will then try generating a KeyPair.

We have some experience of Android, but in this case I would recommend coming back to that after the above is addressed, because it may just be a case of a magnified effect on low-power platforms.

**Comment by boaks** [comment]
> However there is certainly a sort of "static initialization cascade" happening here, which leads to all our curves getting fully configured on the first attempt to use any of them.

:-), Californium does the same in [XECDHECryptography.SupportedGroup](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/XECDHECryptography.java). So switching to a "lazy" bc implementation, I need to add a "preselection" for the intended curves to enable an application to limit that. 
Currently, there is no way to configure BC to only initialize a subset of these curves? Maybe that's a faster way to go, to limit the curves by preselection. Sure that looks more like a specific work-around for Californium, so if it's not considered, that's ok for me.

**Comment by peterdettman** [comment]
I've pushed some changes that definitely speed up your example code (takes time to mirror - we will provide a new beta soon that you can test with).

However I also observe that quite a bit of the time is spent in classloading (it's a bit hard to untangle the classloading per se from our static constructors). So the comparison might be misleading if SunEC has already run through its classloading and/or curve registry initialization before it gets to user code.

I don't think there's currently a way to limit the curve set. I guess it would be possible to support something like that in provider configuration, but anything of that type incurs a compile-time dependency on BC and could lead to confusion. At the moment I expect the laziness approach can still be improved, probably to a satisfactory level of performance.

**Comment by boaks** [comment]
Thanks in advance!

**Comment by dghgit** [comment]
I think this is now up on https://www.bouncycastle.org/betas

**Comment by boaks** [comment]
Thanks! I will test with them.

[bctls-jdk18on-171b07.jar](https://downloads.bouncycastle.org/betas/bctls-jdk18on-171b07.jar) seems to be empty.

**Comment by boaks** [comment]
In first tests, it's 3 times faster. Great!
Does bc have something as "SNAPSHOT" to try it for maven builds?
(If not, I will check it with maven, when it gets released.)

**Comment by dghgit** [comment]
I've replaced the bctls jar. Not sure what the cause of that was, think the download area may have temporarily run out of space. Sorry.

**Comment by boaks** [comment]
> I've replaced the bctls jar. 

Thanks!

> Assuming renaming it to 1.71-SNAPSHOT will do?

For maven dependencies to SNAPSHOTS, usually a SNAPSHOT "maven repo" is required.
e.g. [Eclipse / Snapshot Repository](https://github.com/eclipse/californium/blob/master/pom.xml#L121-L125) and something as "CI nightly build".

For my tests I found [Stackoverflow - Install the JAR into your local Maven repository](https://stackoverflow.com/questions/4955635/how-to-add-local-jar-files-to-a-maven-project?rq=1), I will try, if that works for me.

**Comment by boaks** [comment]
[bcutil-jdk18on-171b07.jar](https://downloads.bouncycastle.org/betas/bcutil-jdk18on-171b07.jar) seems to be broken, even on jar level.

**Comment by boaks** [comment]
One additional question: the name change from "jdk15on" to "jdk18on", does that imply the supported JDK version?

**Comment by boaks** [comment]
I get:

```
javax.crypto.AEADBadTagException: mac check in GCM failed
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$AEADGenericBlockCipher.doFinal(BaseBlockCipher.java:1538)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1173)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2260)
```

with 1.70, that was working.

**Comment by dghgit** [comment]
Yes. For the last few releases we've been doing jdk15on and jdk15to18 - meaning the base version is Java 5. We ended up with this because we got caught mid-release by some issues with multi-release jars (turned out things didn't quite work as expected). It's become obvious we still going to need to do jdk15to18 so for the "onward" release we're lifting to jdk18 (1.8 not 18) as it will allow us to better support later JVMs.

**Comment by dghgit** [comment]
Interesting. Is that happening a lot, or just once in a while?

**Comment by boaks** [comment]
I've just started analyzing ...

**Comment by boaks** [comment]
My setup: Ubuntu 18.0, openjdk version "11.0.13" 2021-10-19.

```
javax.crypto.AEADBadTagException: mac check in GCM failed
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$AEADGenericBlockCipher.doFinal(BaseBlockCipher.java:1538)

	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1173)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2260)
	at org.eclipse.californium.scandium.dtls.cipher.AeadBlockCipher.jreDecrypt(AeadBlockCipher.java:130)
```

It fails always.  
[psk_gcm.pcapng.gz](https://github.com/bcgit/bc-java/files/8015744/psk_gcm.pcapng.gz)

According wireshark, the records are fine.
The other peer is openssl based. With BC 1.70. the test succeeds.
Used secret: `secretPSK` (hex 73656372657450534B)

**Comment by boaks** [comment]
[psk_gcm.pcapng.gz](https://github.com/bcgit/bc-java/files/8015912/psk_gcm.pcapng.gz)

Capture for bc client / openssl server.

Seems, that all works well, but the application records then are somehow mixed up.
Sure, that may be also an effect of Californium. My experience with interoperability is quite good. Changing back to BC 1.70 it works again.

**Comment by boaks** [comment]
If you prefer, I open an new issue.

**Comment by dghgit** [comment]
Yes, I think a new issue for this one and close this one off if you're happy the original problem is dealt with. If there's any additional info you can provide about the OpenSSL version it would help to.

We're not really sure why the changing between the two would make a difference at the moment, so I'd expect a bit of a journey (hopefully not to long!) on this one.

**Comment by boaks** [comment]
In the meantime I assume, the initial issue in Californium in combination with Android is related to the startup of `SecureRandom`, which sporadically  blocks, if entropy is missing.
