### ISSUE TITLE
add hasUsages method to NetscapeCertType

### ISSUE THREAD

**Issue by ralfhauser** [bcgit/bc-java#1105]
like for X509-cert usages, please also add

public boolean hasUsages(int usages)
	    {
	        return (intValue() & usages) == usages;
	    }

**Comment by dghgit** [comment]
Good point. I've added the method, it's now in https://www.bouncycastle.org/betas 171b13 or later.

Enum's are a bit tricky, there's a lot of 1.4 still out there, as well as a lot of code that expects these to be ints.
