### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder

### ISSUE THREAD

**Issue by RenQingWan** [bcgit/bc-java#1109]
I have correctly used bcpkix-fips and turned on approval-only mode, why is MD5 still usable, isn't MD5 an unsafe algorithm? How can I disable it?
I also encountered a problem. When I use jsign, in an environment, I get an error: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder. Both the project compile time and run time No error is reported, this error occurs only in one environment. I found that jsign uses bcpkix-jdk15on, I referenced both bcpkix-jdk15on and bcpkix-fips, they both contain the DefaultSignatureAlgorithmIdentifierFinder class, and have the same name and location. I am sure that my project contains these two jars. How can I do this?
Looking forward to hearing from you, thank you~

**Comment by dghgit** [comment]
MD5 is usable providing your are using it as allowed by the security policy, which is in accordance with the recommendations in NIST SP 800-52 (TLS handshake only).

It's not possible to mix the FIPS and non-FIPS jars. The duplicate pkix library is probably your issue.
