### ISSUE TITLE
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder

### ISSUE THREAD

**Issue by RenQingWan** [bcgit/bc-java#1110]
In my project, I used many third-party packages, some of them depend on FIPS jar, some depend on non-FIPS jar, error: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.operator .DefaultSignatureAlgorithmIdentifierFinder, a conflict occurred. How can I do this?

**Comment by dghgit** [comment]
It's not possible to combine the FIPS and non-FIPS jars. It must be one or the other.
