### ISSUE TITLE
bcprov-jdk15:1.45 -> bcprov-jdk15on:1.69 : non-signing chain certificates no longer in P12

### ISSUE THREAD

**Issue by BNPPF-MMI** [bcgit/bc-java#1117]
I recently changed from bcprov-jdk15:1.45 to bcprov-jdk15on:1.69 due to jdk compatibility.

Before the change, when I had bcprov-jdk15:1.45 as dependency, I was able to create a P12 package with some certificates that were not part of the signing chain of the leaf private key.
The result was a package with :
1. the private key
2. the intermediate CA certificate which is the signer of the private key (1)
3. the root CA certificate which is the signer of the intermediate certificate (2)
4. one or more other certificates which are not part of the signing chain of the private key

We need this because we want that the "other certificates" (the ones that are not part of the signing chain) are installed as trusted CA certificates at the same time the package is installed.

Since I change to bcprov-jdk15on:1.69 dependency, the "other certificates" (the ones that are not part of the signing chain) are no longer part of the P12 package.

here is my code for generating P12 package :

```java
Security.addProvider(new BouncyCastleProvider());
KeyStore keyStore = KeyStore.getInstance("PKCS12", "BC");
keyStore.load(null, null);
keyStore.setKeyEntry(commonName
                     privateKey,
                     a_password.toCharArray(),
                     new Certificate[]{leafCertificate, // the one of the private key
                                       intermediateCACertificate,
                                       rootCACertificate,
                                       otherCertificate1,
                                       otherCertificate2,
                                       ...});
File file = createFile(key, packageFormat);
try (FileOutputStream fileOutputStream = new FileOutputStream(file)) {
    keyStore.store(fileOutputStream, another_password.toCharArray());
}
```

**Comment by peterdettman** [comment]
The certificates for a PrivateKeyEntry (as created by setKeyEntry) are supposed to only be the chain corresponding to the private key. Extraneous certificates in no case should establish trusted CAs, so I am unclear how this code could have ever been working in the way you describe (although to be fair 1.49 is _very_ old).

If you want to add other trusted certificates to a KeyStore, they should be added as separate TrustedCertificateEntry entries (usually using setCertificateEntry). Please refer to the javadoc: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/security/KeyStore.html .

Perhaps there is some other software involved here that processes these key stores and gives a different meaning to (some of) the certificates in a PrivateKeyEntry. If so I would suggest reviewing that design.

**Comment by dghgit** [comment]
Assumed resolved.

**Comment by BNPPF-MMI** [comment]
> If you want to add other trusted certificates to a KeyStore, they should be added as separate TrustedCertificateEntry entries (usually using setCertificateEntry). Please refer to the javadoc: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/security/KeyStore.html .

That was the solution.

Thank you.
