### ISSUE TITLE
Umlauts in ArmoredOutputStream headers are not properly encoded

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#1120]
When I add a header such as a comment to the `ArmoredOutputStream` which contains umlauts, the resulting ASCII armored output did not properly encode the header value.

The following test demonstrates this behavior:
```
package org.bouncycastle.openpgp.test;

import org.bouncycastle.bcpg.ArmoredOutputStream;
import org.bouncycastle.util.test.SimpleTest;

import java.io.ByteArrayOutputStream;
import java.nio.charset.Charset;

public class ArmoredOutputStreamUTF8Test extends SimpleTest {

    private static final Charset utf8 = Charset.forName("UTF8");

    public static void main(String[] args) {
        runTest(new ArmoredOutputStreamUTF8Test());
    }

    @Override
    public String getName() {
        return ArmoredOutputStreamUTF8Test.class.getSimpleName();
    }

    @Override
    public void performTest() throws Exception {
        String utf8WithUmlauts = "ÄÖÜß&Umlauts";

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        ArmoredOutputStream armorOut = new ArmoredOutputStream(out);
        armorOut.setHeader("Comment", utf8WithUmlauts);

        armorOut.write("Foo\nBar".getBytes(utf8));

        armorOut.close();

        String armoredOutput = out.toString();
        String[] lines = armoredOutput.split("\n");
        String comment = null;
        for (String line : lines) {
            if (line.startsWith("Comment: ")) {
                comment = line.substring("Comment: ".length());
                break;
            }
        }

        isTrue("We did not find the comment line. This MUST never happen.", comment != null);
        isEquals("Comment was not properly encoded. Expected: "  +utf8WithUmlauts + ", Actual: " + comment, comment, utf8WithUmlauts);
    }
}
```

The test results in the following error:
```
ArmoredOutputStreamUTF8Test: Comment was not properly encoded. Expected: ÄÖÜß&Umlauts, Actual: ����&Umlauts
```

I tracked down the issue of this bug to the [ArmoredOutputStream using](https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/bcpg/ArmoredOutputStream.java#L308-L311) `out.write(value.charAt(i));` when writing header values, which causes encoding issues.

Compare:
```
        String utf8 = "ÄÖÜß";

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        for (int i = 0; i < utf8.length(); i++) {
            char c = utf8.charAt(i);
            out.write(c);
        }
        System.out.println(out.toString("UTF8")); // Encoding issues

        // Fixed by using OutputStreamWriter
        out = new ByteArrayOutputStream();
        OutputStreamWriter writer = new OutputStreamWriter(out, "UTF8");
        for (int i = 0; i < utf8.length(); i++) {
            char c = utf8.charAt(i);
            writer.write(c);
        }
        writer.flush();
        System.out.println(out.toString("UTF8")); // Expected Behavior
```

Is this expected behavior? If not, would wrapping the ArmorOutputStreams internal `out` in an `OutputStreamWriter` configured to use UTF8 encoding fix the issue?

Related Downstream Issue: https://github.com/pgpainless/pgpainless/issues/256

**Comment by vanitasvitae** [comment]
Section [6.2](https://datatracker.ietf.org/doc/html/rfc4880#section-6.2) of rfc4880 reads

>      - "Comment", a user-defined comment.  OpenPGP defines all text to
>       be in UTF-8.  A comment may be any UTF-8 string.  However, the
>       whole point of armoring is to provide seven-bit-clean data.
>       Consequently, if a comment has characters that are outside the
>       US-ASCII range of UTF, they may very well not survive transport.

Does that mean that what I see is expected behavior?

**Comment by dghgit** [comment]
This is a bit of an odd one, especially given the way it is worded... what does the latest version of GPG do in this situation? My instincts tell me we should do that - "may very well" makes it sound like perhaps it should be copied cleanly where possible.

**Comment by vanitasvitae** [comment]
I checked via `$ gpg --armor --comment "ÄÖÜß" --export <keyid>` and the output looks like
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: ÄÖÜß

mFIEXhtfCBMIKoZIzj0DAQcCAwT...
```

So GnuPG is using proper encoding.

**Comment by dghgit** [comment]
Okay, in keeping with one of the Internet's more established traditions, on this one, we'll do it their way.

I've uploaded a new beta 171b18 which does this at https://www.bouncycastle.org/betas

**Comment by vanitasvitae** [comment]
Great! Thanks for your work :)
