### ISSUE TITLE
 bc-fips:1.02.1 upgrade from 1.02 leads 90% TPS drop..any knwon issue

### ISSUE THREAD

**Issue by klebaka** [bcgit/bc-java#1122]
We have upgraded BC-FIPS from 1.0.2 to 1.0.2.1
bcpkix-fips-1.0.5.
bcmail-fips-1.0.3

Post that we have 90% performance degradation while generating the cert and during handshake 

54.95%    16464  sun.security.pkcs11.wrapper.PKCS11.C_SignInit

Is it know issues?

**Comment by dghgit** [comment]
No, never heard that, but try 1.0.2.3.
