### ISSUE TITLE
Use of DEROctetString / ASN1OctetString 

### ISSUE THREAD

**Issue by DBatOWL** [bcgit/bc-java#1123]
I was recently creating a CMP request, using Java, and had the following lines of code:

```
byte[] randomBytes = new byte[16];

GeneralName snd = new GeneralName(GeneralName.directoryName, "cn=MyName");
GeneralName rec = new GeneralName(GeneralName.directoryName, "cn=CMPserver");
PKIHeaderBuilder builder = new PKIHeaderBuilder(2, snd, rec);

randomSource.nextBytes(randomBytes);
builder.setTransactionID(randomBytes);

randomSource.nextBytes(randomBytes);
builder.setSenderNonce(randomBytes);
```

Looking at the request I noticed that the transactionId and nonce were the same value.  Checking into the implementation I see it calls DEROctetString and then ASN1OctetString which stores a reference to the passed value, making the assignment of new random bytes in the second nextBytes override the first.

Sure I could make a copy before calling but I think this may highlight other cases where I don't know the parent of a class being called that could also be impacted.

I feel it would be safer for ASN1OctetString to make a defensive copy of the provided byte array instead of storing the reference.

Is a fix like this already planned or has it been discussed and deemed not appropriate?

**Comment by dghgit** [comment]
I've changed the PKIHeaderBuilder to do the defensive copying. Unfortunately there's a lot of performance issues around making DEROctetString copy. Changes should appear on github shortly and in this week's beta (I'll note it here when it's done).

**Comment by dghgit** [comment]
This is now up on https://www.bouncycastle.org/betas 171 b19 or later.
