### ISSUE TITLE
Blake3 ASN1ObjectIdentifier missing

### ISSUE THREAD

**Issue by raubv0gel** [bcgit/bc-java#1124]
In [`java/org/bouncycastle/asn1/misc/MiscObjectIdentifiers.java`](https://github.com/bcgit/bc-java/blob/e0b194c869a9798d6dd2bb421773bee8759a5187/core/src/main/java/org/bouncycastle/asn1/misc/MiscObjectIdentifiers.java#L127) Blake3 (OID is 1.3.6.1.4.1.1722.12.2.3.8) is missing (Blake2 is present). One cannot choose Blake3 to
```java
digestCalculatorProvider.get( new AlgorithmIdentifier(new ASN1ObjectIdentifier("1.3.6.1.4.1.1722.12.2.3.8")));
```

**Comment by raubv0gel** [comment]
Seems Blake3 is missing at [https://github.com/bcgit/bc-java/tree/master/prov/src/main/java/org/bouncycastle/jcajce/provider/digest](https://github.com/bcgit/bc-java/tree/master/prov/src/main/java/org/bouncycastle/jcajce/provider/digest) too.

**Comment by dghgit** [comment]
Blake3 and Blake3-256 now added. Haven't found a decent reference for any other OIDs yet.

**Comment by dghgit** [comment]
Now up in https://www.bouncycastle.org/betas 171b18 or later.
