### ISSUE TITLE
Attaching sources for eclipse

### ISSUE THREAD

**Issue by ssenegas** [bcgit/bc-java#1125]
In Eclipse, does anyone know how to attach BC sources using archive files provided on the website?

Usually dedicated source jar archive is used and then you can define in Source Attachment Configuration the jar location containing the source for a library.

Sources and Javadoc are available here in section source and Javadoc
https://www.bouncycastle.org/latest_releases.html

**Comment by boaks** [comment]
I'm not sure, if I understand your question.

So let me start with, that I use maven. 

```
<dependency>
	<groupId>org.bouncycastle</groupId>
	<artifactId>bctls-jdk15on</artifactId>
	<version>1.70</version>
</dependency>
<dependency>
	<groupId>org.bouncycastle</groupId>
	<artifactId>bcutil-jdk15on</artifactId>
	<version>1.70</version>
</dependency>
```

With the eclipse maven plugin the BC source are attached without any special "to do". It just works. So, mayb just using maven as build systems works for you as well?

> Usually dedicated source jar archive is used and then you can define in Source Attachment Configuration the jar location containing the source for a library.

Not sure, if I understand that. You setup Eclipse IDE as usual, but with the BC sources from that downloads it doesn't work?

Maybe you try out the jars ([class](https://search.maven.org/remotecontent?filepath=org/bouncycastle/bctls-jdk15on/1.70/bctls-jdk15on-1.70.jar) + [source](https://search.maven.org/remotecontent?filepath=org/bouncycastle/bctls-jdk15on/1.70/bctls-jdk15on-1.70-sources.jar)) from maven central?

**Comment by ssenegas** [comment]
Thank you for the inputs Achim.
I was finally able to configure Eclipse to access the BC source code by using the source jars available on maven central.
