### ISSUE TITLE
Is it possible, to add descriptive name to entropy gatherer thread?

### ISSUE THREAD

**Issue by boaks** [bcgit/bc-java#1126]
BC starts from time to time an anonymous [thread to gather some entropy](https://github.com/bcgit/bc-java/blob/master/prov/src/main/java/org/bouncycastle/jcajce/provider/drbg/DRBG.java#L459).

```
Thread gatherer = new Thread(new EntropyGatherer(byteLength));
```

Would it be possible, to use a name e.g. "BC-DRBG" or "BC-entrophy"? 
That makes it a easier, to distinguish that intended thread, from other sticking threads from where ever (outside of BC).

**Comment by dghgit** [comment]
Yes, I can see the merit in that. It's now called "BC-ENTROPY-GATHERER". See the latest in https://www.bouncycastle.org/betas 171b19 or later.

**Comment by boaks** [comment]
Thanks a lot!
