### ISSUE TITLE
JcaPKIXIdentityBuilder does not work with File objects

### ISSUE THREAD

**Issue by wundrian** [bcgit/bc-java#1127]
Quite clearly in
https://github.com/bcgit/bc-java/blob/5b69c09f4fcdd480ba87d571dd581527dc35379e/pkix/src/main/java/org/bouncycastle/openssl/jcajce/JcaPKIXIdentityBuilder.java#L125
it should read
```
if (!file.canRead())
```
to pass as soon as the file can be read and only enter further checks if that's not the case.

**Comment by dghgit** [comment]
Thanks for the report. This should now be fixed in the latest beta 171b18. Available att https://www.bouncycastle.org/betas
