### ISSUE TITLE
PSK TLS 1.3: bc-client to OpenSSL-server - where to set psk binders?

### ISSUE THREAD

**Issue by datrodavgol19** [bcgit/bc-java#1136]
After a long debug session of trying 
to connect an android java bc-client 
(overriding PSKTlsClient) 
to an openssl windows console server 
(using: openssl s_server -psk 1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A -ciphersuites TLS_AES_128_GCM_SHA256 -debug -state -msg -nocert -accept 23232 -tls1_3) 
by PSK TLS 1.3
I found out by sniffing network that the difference between a working TLS 1.3 Client Hello from openssl windows console client and the packet that my bc-client is sending:

**Extension: pre_share_key** 

So I have tried this bc-method:
```
        PskIdentity identity = new PskIdentity(MainActivity.TLS_PSK_IDENTITY.getBytes(StandardCharsets.UTF_8), 0);
        Vector vec = new Vector();
        vec.addElement(identity);
        TlsExtensionsUtils.addPreSharedKeyClientHello(clientExtensions, new OfferedPsks(vec));
```

This method does create a well formed "Extension: pre_share_key" in the client hello packet, BUT it does not add the following elements as seen in the sniffed packet: **"PSK Binders length:"** & **"PSK Binders"**
In the correct Client Hello packet from openssl these two values are set correctly.

My question: How do I set the **"PSK Binders length:"** & **"PSK Binders"** correctly from bc-java-API?

**Comment by datrodavgol19** [comment]
Thank you @peterdettman. Issue resolved, all worked

**Comment by bwcc60** [comment]
I have the similar case, using BC177 and the MockPskTls13Client/Server.java to compile code. but I found BC client can not talk with openssl s_server, (openssl s_server -security_debug_verbose  -ciphersuites TLS_CHACHA20_POLY1305_SHA256 -debug -state -msg -nocert -tls1_3 -psk 787290c30f01888ecf5afa3ccdcb2d106dacb1815a5eca681aa96a6c3d83d4ded8c09fd7b7601337028db561a8332cb9222ede530ce22aeafc4cccedfc1c991e).  The result shows as the following:

`[user@localhost bc-java]$ openssl s_server -security_debug_verbose -ciphersuites TLS_CHACHA20_POLY1305_SHA256 -debug -state -msg -nocert -tls1_3 -psk 787290c30f01888ecf5afa3ccdcb2d106dacb1815a5eca681aa96a6c3d83d4ded8c09fd7b7601337028db561a8332cb9222ede530ce22aeafc4cccedfc1c991e
Using default temp DH parameters
PSK key given, setting server callback
ACCEPT
Security callback: Version=TLS 1.3: yes
Security callback: Version=TLS 1.3: yes
SSL_accept:before SSL initialization
read from 0x112a0c0 [0x11359a3] (5 bytes => 5 (0x5))
0000 - 16 03 01 01 17                                    .....
<<< ??? [length 0005]
    16 03 01 01 17
read from 0x112a0c0 [0x11359a8] (279 bytes => 279 (0x117))
0000 - 01 00 01 13 03 03 fc ad-e3 44 19 38 a8 e8 7b c2   .........D.8..{.
0010 - 32 c3 a9 54 69 85 3e 11-0e 06 d2 e4 4a a6 6e e5   2..Ti.>.....J.n.
0020 - 86 c0 f1 a2 21 89 20 00-f3 d4 50 23 dd 25 e6 d0   ....!. ...P#.%..
0030 - 42 6c af 7f ad 40 71 5a-6e 2a 1b e4 2e ec 33 eb   Bl...@qZn*....3.
0040 - 88 53 bc 8a 0a 2b 4d 00-04 13 03 00 ff 01 00 00   .S...+M.........
0050 - c6 00 2b 00 03 02 03 04-00 0a 00 10 00 0e 00 1d   ..+.............
0060 - 00 1e 00 17 00 18 01 00-01 01 01 02 00 33 00 26   .............3.&
0070 - 00 24 00 1d 00 20 a2 44-c7 70 ce f3 50 0e ba fe   .$... .D.p..P...
0080 - e9 3c d3 9f 76 f0 4b 07-bd 58 f7 a2 e0 d1 da e5   .<..v.K..X......
0090 - 4c b5 5f 4e 1c 20 00 05-00 05 01 00 00 00 00 00   L._N. ..........
00a0 - 0d 00 30 00 2e 08 07 08-08 04 03 05 03 06 03 08   ..0.............
00b0 - 04 08 05 08 06 08 09 08-0a 08 0b 04 01 05 01 06   ................
00c0 - 01 04 02 05 02 06 02 03-03 03 01 03 02 02 03 02   ................
00d0 - 01 02 02 00 2d 00 02 01-01 00 29 00 3a 00 15 00   ....-.....).:...
00e0 - 0f 43 6c 69 65 6e 74 5f-69 64 65 6e 74 69 74 79   .Client_identity
00f0 - 00 00 00 00 00 21 20 9e-c8 4f 69 51 fb c3 f0 5b   .....! ..OiQ...[
0100 - b3 5d 11 9c 60 67 06 1a-06 f6 e7 0c fc a8 16 cb   .]..`g..........
0110 - 04 54 4f f3 3e f8 00                              .TO.>..
SSL_accept:before SSL initialization
<<< TLS 1.3, Handshake [length 0117], ClientHello
    01 00 01 13 03 03 fc ad e3 44 19 38 a8 e8 7b c2
    32 c3 a9 54 69 85 3e 11 0e 06 d2 e4 4a a6 6e e5
    86 c0 f1 a2 21 89 20 00 f3 d4 50 23 dd 25 e6 d0
    42 6c af 7f ad 40 71 5a 6e 2a 1b e4 2e ec 33 eb
    88 53 bc 8a 0a 2b 4d 00 04 13 03 00 ff 01 00 00
    c6 00 2b 00 03 02 03 04 00 0a 00 10 00 0e 00 1d
    00 1e 00 17 00 18 01 00 01 01 01 02 00 33 00 26
    00 24 00 1d 00 20 a2 44 c7 70 ce f3 50 0e ba fe
    e9 3c d3 9f 76 f0 4b 07 bd 58 f7 a2 e0 d1 da e5
    4c b5 5f 4e 1c 20 00 05 00 05 01 00 00 00 00 00
    0d 00 30 00 2e 08 07 08 08 04 03 05 03 06 03 08
    04 08 05 08 06 08 09 08 0a 08 0b 04 01 05 01 06
    01 04 02 05 02 06 02 03 03 03 01 03 02 02 03 02
    01 02 02 00 2d 00 02 01 01 00 29 00 3a 00 15 00
    0f 43 6c 69 65 6e 74 5f 69 64 65 6e 74 69 74 79
    00 00 00 00 00 21 20 9e c8 4f 69 51 fb c3 f0 5b
    b3 5d 11 9c 60 67 06 1a 06 f6 e7 0c fc a8 16 cb
    04 54 4f f3 3e f8 00
Security callback: Version=TLS 1.3: yes
Security callback: Shared Ciphersuite=TLS_CHACHA20_POLY1305_SHA256, security bits=256: yes
>>> ??? [length 0005]
    15 03 03 00 02
write to 0x112a0c0 [0x113ecb0] (7 bytes => 7 (0x7))
0000 - 15 03 03 00 02 02 2f                              ....../
>>> TLS 1.3, Alert [length 0002], fatal illegal_parameter
    02 2f
SSL3 alert write:fatal:illegal parameter
SSL_accept:error in error
ERROR
140257662437184:error:141FA0FD:SSL routines:tls_psk_do_binder:binder does not verify:ssl/statem/extensions.c:1604:
shutting down SSL
CONNECTION CLOSED
`

after debugging BC code, the client sends ClientHello message with Extension: pre_share_key. but the message can not be handled by openssl1.1.1d. 

I have questions: 
1. why int prfAlgorithm = PRFAlgorithm.tls13_hkdf_sha256 at MockPskTls13Client::getExternalPSKs() is used? can I change to other settings?
2. at openssl, there is parameter -groups that can choose, e.g. P-256? how to set "group" at BC side? 

Thanks!

**Comment by peterdettman** [comment]
@bwcc60

1. Each out of band PSK has an associated KDF hash algorithm. You can change it but the client and server have to have the same value.
2. If you are subclassing AbstractTlsClient, you can override AbstractTlsClient#getSupportedGroups to control what groups are supported. Check that method's implementation for details on how to check the underlying cryptography supports a group before adding it though.

Note that out of band PSKs also have an associated identity, which also needs to match between client and server. In particular our test is using "client" (as UTF-8), whereas I believe openssl's default PSK identity is "Client_identity".

**Comment by bwcc60** [comment]
@peterdettman Thank you for the reply! As to 1, 2. I will jump deep to check both openssl and BC sides. As to the identity, I had changed it to the "Client_identity" at BC side to test before I put the comment.

**Comment by bwcc60** [comment]
@peterdettman, I managed to use the right "supported groups" and "PSK key exchange 
 mode", which 
![compare](https://github.com/bcgit/bc-java/assets/53788756/707c1443-ab42-4d84-bc5b-ec1b8637ddf1)
are same as the C++ client. but I still meet the same error. the attached 2 pcap files shows the same C++ server program response "ClientHello" from C++ client and Java Client. There are several extra extensions showed at C++ client. I don't know whether those are related.  Please take a look. Because I can't upload pcap file. so I attached the screenshot. 

As to 1, tls13_hkdf_sha256. I tried other tls13 options, which shows "PSK meet IOException error : org.bouncycastle.tls.TlsFatalAlert: internal_error(80); External PSK incompatible with offered cipher suites" so i assume  tls13_hkdf_sha256 is the right one. I will check openssl about this issue. 

Thanks!

**Comment by bwcc60** [comment]
@peterdettman I downloaded the openssl 3.2.1 and installed. then tested with its openssl s_server with same setting as openssl 1.1.1d. and java clients, I got the same kind of error. 

///////////
openssl 3.4.1

>>> TLS 1.3, Alert [length 0002], fatal illegal_parameter
    02 2f
SSL3 alert write:fatal:illegal parameter
SSL_accept:error in error
ERROR
4007A40E797F0000:error:0A0000FD:SSL routines:(unknown function):binder does not verify:ssl/statem/extensions.c:1686:

line 1686: is at the function int tls_psk_do_binder() function

openssl 1.1.1d

>>> TLS 1.3, Alert [length 0002], fatal illegal_parameter
    02 2f
SSL3 alert write:fatal:illegal parameter
SSL_accept:error in error
ERROR
139625499162432:error:141FA0FD:SSL routines:tls_psk_do_binder:binder does not verify:ssl/statem/extensions.c:1604:
shutting down SSL
CONNECTION CLOSED

//////////////////

It seems like the PSK_binder doesn't match between openssl s_server and java client. 
![PSK_binder_issue_openssl_s_server_java_client](https://github.com/bcgit/bc-java/assets/53788756/d1fb8a6e-0d24-4422-a2eb-eeec0c905a5b)

I am wondering does the BC PSKTlsClientTest.java talks with openssl s_server?

**Comment by bwcc60** [comment]
@peterdettman.  I resolve the issue. BC uses utf-8 for identity and key, while openssl uses hex for key, byte for identity. once I iron out this one. everything works. Thanks
