### ISSUE TITLE
PKIFailureInfo

### ISSUE THREAD

**Issue by Hans-MartinHannibalLauridsen** [bcgit/bc-java#1137]
It seems there is a bug in the TimeStampResponseGenerator.
The way the PKIFailureInfo in generated by assuming that if failInfo is not set if the value in `0`, unfortunately badAlg has the value of ´0´ meaning that the generator cannot create a response with the ´badAlg´ identifier as specified by the [RFC](https://www.ietf.org/rfc/rfc3161.txt)

**Comment by dghgit** [comment]
badAlg is bit zero, not the value zero. The bit string syntax says which bit is set for a particular status.
