### ISSUE TITLE
Version 1.71 not available on Maven Central

### ISSUE THREAD

**Issue by schildbach** [bcgit/bc-java#1139]
From my developer machine, and from a GitHub actions runner, I get this error:

```
   > Could not find org.bouncycastle:bcprov-jdk15to18:1.71.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15to18/1.71/bcprov-jdk15to18-1.71.pom
```

See https://github.com/bitcoinj/bitcoinj/pull/2373/checks

**Comment by trcoelho** [comment]
Is there any updates on this?
I can see that 1.71 version was released however is not available on Maven Repository.

Thanks in advance.

**Comment by schildbach** [comment]
It's now on Maven Central. Thanks!

**Comment by andreasrosdal** [comment]
Bouncy castle 1.71 is still not in Maven central. Please publish it to maven central.

**Comment by schildbach** [comment]
https://search.maven.org/artifact/org.bouncycastle/bcprov-jdk15to18 → version 1.71

@andreasrosdal What artifact ID are you using?

**Comment by andreasrosdal** [comment]
I am using this:  https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on
