### ISSUE TITLE
Support AEAD encryption for OpenPGP

### ISSUE THREAD

**Issue by seba174** [bcgit/bc-java#1140]
Support AEAD encryption mode for OpenPGP ([SPEC](https://datatracker.ietf.org/doc/html/draft-ietf-openpgp-rfc4880bis-04#section-5.16)).

It is supported by [gnupg](https://gnupg.org/), so files encrypted with it using this mode fail when trying to decrypt using BountyCastle lib. Other popular OpenPGP libraries (like [openpgpjs](https://github.com/openpgpjs/openpgpjs), [RNP](https://github.com/rnpgp/rnp)) support that mode from a long time.

**Comment by vanitasvitae** [comment]
For the record: The current version of the OpenPGP spec that gets worked on is [crypto-refresh-05](https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-05.html).

**Comment by didisoft** [comment]
We at DidiSoft, have implemented AEAD decryption available here : https://github.com/didisoft/bc-java/tree/AEAD_DECRYPTION

**Comment by vanitasvitae** [comment]
@didisoft will you attempt to get this merged upstream?

**Comment by dghgit** [comment]
Hi, so I just found this while I was actually adding for the AEAD draft. Somehow we don't have any record. At the moment the support is only for a single data chunk.

@didisoft I've had a look at your updates, it'll be a couple of weeks before I'm likely to look at this again. If you're interested in modifying your stream class so it works in org.bouncycastle.openpgp.operator.jcajce.OperatorHelper (see line 202), we'd be happy to accept a PR. I'm not sure who you emailed but we don't seem to have any record on this one. Apologies.

**Comment by dghgit** [comment]
Okay, things moved a bit faster than I expected. The update to handle chunking on parsing is now in place as well.

**Comment by dghgit** [comment]
Encryption has now been added. Final code should appear on github shortly and appear in 172b11 on https://www.bouncycastle.org/betas in the next couple of days.

**Comment by ecki** [comment]
I asked on crypto-dev about the version 1/2 differences. (And I haven’t looked a key packets yet, is it more then new ciphers?)

**Comment by vanitasvitae** [comment]
The currently implementation of AEAD in BCPG differs in a few places from the one proposed in the I-D document.

I am actually currently working on adding support for I-D-style AEAD to bouncy castle and was able to successfully decrypt the test vector messages 2 days ago.

**Comment by ecki** [comment]
If I see it correctly you could keep both - at least for decryption, right? (For compat with GnuPG and others who used the old draft)

Does that only affect data packsts or also key packets or their signatures somehow?

**Comment by vanitasvitae** [comment]
For decryption you can support both simultaneously. I think the I-D will introduce version 6 keys, so for encryption you can determine which algorithm your peer supports by looking at their key. If its a v5 key which advertises AEAD as a feature, use GnuPG-style AEAD, and if its a v6 key, use I-D-style AEAD.

There are some differences in the packet format. GnuPG-style introduces a new packet type (AEADEncryptedData), while the I-D document defines a version 2 SymmetricallyEncryptedIntegrityProtectedData packet. The rest is similar, but there are subtle changes in what goes into HKDFs etc.
