### ISSUE TITLE
Performance issue with BCFips security provider

### ISSUE THREAD

**Issue by chavdarch** [bcgit/bc-java#1146]
Hi team,

My company is planning to use bouncy castle to enforce fips compliance for encryption. I've used a simple jmh benchmark that is running in a loop with a lot of encryptions/ decryptions using java cipher for AES.
I ran the attached benchmark on my machine(mac) and on our local bamboo server(linux) and got the following results
`mvn clean -B verify --file pom.xml exec:java`  

```
Benchmark                                      Mode  Cnt        Score        Error  Units
EncryptionBenchmark.fipsBcProviderEncryption  thrpt   25    32008.062 ±   3524.149  ops/s
EncryptionBenchmark.nonfipsEncryption         thrpt   25  3235114.417 ± 136671.753  ops/s
```

where nonfipsEncryption is using SunJCE version 16 security provider
and fipsBcProviderEncryption is using  BCFIPS version 1.000203

So it looks like BCFIPS is about 100x slower(i. terms of ops/sec) than the standard SunJCE.

I also did some profiling on the same test and it looks like the hotspot is in  **org.bouncycastle.cryptor.fips.AESEngine.generateWorkingKey** where 62 % of the cpu time is spent.

Do you have any suggestions/recommendations on how to improve the performance of the BCFips?

[cchernashki-bc-fips-benchmark](https://github.com/bcgit/bc-java/files/8471027/cchernashki-bc-fips-benchmark-e9ab4bf8b335.zip)

<img width="1668" alt="Screen Shot 2022-04-12 at 1 02 55 pm" src="https://user-images.githubusercontent.com/3097306/162920039-f8fa15e1-58d6-4237-8929-63f9eb902748.png">
<img width="1675" alt="Screen Shot 2022-04-12 at 1 04 43 pm" src="https://user-images.githubusercontent.com/3097306/162920063-8d10e329-9330-4176-9f1e-f6c49f2fc2a3.png">

In comparison this is how the same test looks like with the Sun Jce
<img width="1664" alt="Screen Shot 2022-04-12 at 1 16 53 pm" src="https://user-images.githubusercontent.com/3097306/162920295-a8d73262-8c27-490e-8c4e-cfb54b5c3f92.png">
<img width="1677" alt="Screen Shot 2022-04-12 at 1 18 31 pm" src="https://user-images.githubusercontent.com/3097306/162920341-20599213-c124-41e4-a48c-67cca4491fdc.png">

**Comment by chavdarch** [comment]
The results differ depending on the OS/JVM/hardware, do you have any recommendation for the hardware?

**Comment by chavdarch** [comment]
Thanks a lot for your suggestion. I have added additional test, that have separate ciphers for encryption and decryption, that are initialised once at setup

https://gist.github.com/chavdarch/85ca0851e4f5b157972ee918e0d2e761

and yes, that improved significantly the throughput.

```
Benchmark                                                    Mode  Cnt        Score         Error  Units
EncryptionBenchmark.fipsBcProviderEncryption                thrpt    5    35588.794 ±   49889.559  ops/s
EncryptionBenchmark.fipsBcProviderEncryptionLessCipherInit  thrpt    5  1256556.315 ±  171060.646  ops/s
EncryptionBenchmark.nonfipsEncryption                       thrpt    5  2531095.084 ± 1001084.087  ops/s
```
fipsBcProviderEncryptionLessCipherInit is now just 2x slower than nonfipsEncryption.

This is great, unfortunately we are using aws encryption sdk and in the call chain I can see a call
https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/internal/CipherHandler.java#L57

which is calling init and then doFinal in the same way as the `fipsBcProviderEncryption` so i guess that needs to be patched, unless bc has a way to optimise the Cipher.init.

<img width="1680" alt="Screen Shot 2022-04-12 at 11 12 04 pm" src="https://user-images.githubusercontent.com/3097306/162970183-8f7b45fd-e61f-427a-94b6-b020bb3aed01.png">

**Comment by peterdettman** [comment]
We could look at improving checks for same-key initialization (for AES/GCM I think this is something of a known issue already), but you likely couldn't expect a new version of the FIPS provider with such a feature before next year.

Unfortunately the CipherHandler case cannot really be "fixed" because at least the nonce will need to be changed for each operation, so the init calls cannot be avoided. You could check whether CipherHandler is actually re-used though, maybe there's a different key for each operation anyway (I don't know the context).

**Comment by chavdarch** [comment]
thank you for your answers! We will wait for the new version when it comes and in the meantime we will see what can we do with the encryptions sdk

**Comment by dghgit** [comment]
Appears resolved.
