### ISSUE TITLE
Blake algorithms missing in class DefaultAlgorithmNameFinder

### ISSUE THREAD

**Issue by raubv0gel** [bcgit/bc-java#1147]
Blake algorithms are missing in [pkix/src/main/java/org/bouncycastle/operator/DefaultAlgorithmNameFinder.java](pkix/src/main/java/org/bouncycastle/operator/DefaultAlgorithmNameFinder.java), but defined in [core/src/main/java/org/bouncycastle/asn1/misc/MiscObjectIdentifiers.java](core/src/main/java/org/bouncycastle/asn1/misc/MiscObjectIdentifiers.java).

**Comment by raubv0gel** [comment]
I should be able to fix it. Do you want me to create a pull request?

**Comment by peterdettman** [comment]
Sure, feel free to open a PR.

**Comment by dghgit** [comment]
One last tweak - the algorithm names were missing "-". Now merged.

**Comment by raubv0gel** [comment]
I have taken the names from [http://oid-info.com/get/1.3.6.1.4.1.1722.12.2.1.5](http://oid-info.com/get/1.3.6.1.4.1.1722.12.2.1.5) and alike.

**Comment by dghgit** [comment]
There are variations, in this case it works better if they actually match what's in the provider.
