### ISSUE TITLE
Broken secp256k1 multiplication

### ISSUE THREAD

**Issue by saturn4er** [bcgit/bc-java#1150]
For some reason, multiplication for secp256k1 returns invalid results. Here's a simple script:
```java
public static void main(
        String[]    args)
    {
        X9ECParameters secp = CustomNamedCurves.getByName("secp256k1");
        BigInteger v = new BigInteger("2", 16);
        ECPoint base = secp.getCurve().getMultiplier().multiply(secp.getG(), v);
        System.out.println(base);
    }
```
which prints: ```(7d152c041ea8e1dc2191843d1fa9db55b68f88fef695e2c791d40444b365afc2,56915849f52cc8f76f5fd7e4bf60db4a43bf633e1b1383f85fe89164bfadcbdb,9075b4ee4d4788cabb49f7f81c221151fa2f68914d0aa833388fa11ff621a970)```

But correct values are:```(c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5, 1ae168fea63dc339a3c58419466ceaeef7f632653266d0e1236431a950cfe52a)```
 At least this results shows Golang implementation and [this](https://github.com/MrMaxweII/Secp256k1-Calculator ) calculator.

**Comment by peterdettman** [comment]
The raw point is in projective coordinates, call normalize on the point to get an affine point (or at least bring Z to 1).

**Comment by saturn4er** [comment]
@peterdettman thanks a lot
