### ISSUE TITLE
"PGPException: unknown public key algorithm encountered" at least say which one

### ISSUE THREAD

**Issue by ralfhauser** [bcgit/bc-java#1152]
org.bouncycastle.openpgp.PGPException: unknown public key algorithm encountered
	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.getPublicKey(329)

Please

1) give some hint on what is visible about the not yet supported algorithm

2) support it

[naharronak@gmail.com_6A4A18D8A80D2C025C2F65A49FAD90D84CD488DC.asc.zip](https://github.com/bcgit/bc-java/files/8510632/naharronak%40gmail.com_6A4A18D8A80D2C025C2F65A49FAD90D84CD488DC.asc.zip)

https://keys.openpgp.org/vks/v1/by-fingerprint/6A4A18D8A80D2C025C2F65A49FAD90D84CD488DC

**Comment by dghgit** [comment]
I've added the algorithm number. Which version of BC is this? The keyring appears to contain EdDSA and ECDH keys - both of which we support.

**Comment by ralfhauser** [comment]
Thanks  - will soon go from 1.64 to 1.71 ;)

**Comment by dghgit** [comment]
Resolved.
