### ISSUE TITLE
jdk15on and jdk15to18 compatibility issues

### ISSUE THREAD

**Issue by unnamedw** [bcgit/bc-java#1161]
I implement two dependencies. 
They depends on jdk15on and jdk15to18 for each.

This seems to be conflict at build time because they use duplicate classes.

In this situation, What is the best option I can choose?
Should I exclude one class? If so, should I exclude jdk15on or jdk15to18? 
The versions are assumed to be the same.

There is no solution anywhere to solve the dependency conflict problem using these different kinds of bouncycastle. 
Please reply on this issue. thank you.

**Comment by dghgit** [comment]
Use 15to18

**Comment by unnamedw** [comment]
> Use 15to18

Sorry for asking such a basic question.

Library A uses jdk15to18 1.69, 
library B uses jdk15on 1.68. 

Is it okay to exclude jdk15on from transitive dependencies in this case?
