### ISSUE TITLE
Build errors with Intellij

### ISSUE THREAD

**Issue by raubv0gel** [bcgit/bc-java#1162]
If I do a fresh `git clone` on the bc-java repro and do a build in Intellij, I get:

![grafik](https://user-images.githubusercontent.com/9824146/167120431-db95d1fb-41dc-4ddd-b058-70f65edebad0.png)

`Projects\bc-java-2\core\src\main\java\org\bouncycastle\pqc\crypto\cmce\CMCEEngine.java:240: error: unmappable character (0x90) for encoding windows-1252
            // If anything fails, this set δ �?δ′ (the next last 32 bytes of E) and restart the algorithm.`

Any suggestions to fix this?

**Comment by dghgit** [comment]
odd.. I use IntelliJ myself. I've replace the offending character with '='.
