### ISSUE TITLE
Inconsistent constructor for blake2b and blake3

### ISSUE THREAD

**Issue by polarker** [bcgit/bc-java#1168]
`Blake2bDigest`'s sized constructor uses size in bits: https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/digests/Blake2bDigest.java#L134-L139

`Blake3Digest`'s sized constructor uses size in bytes: https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/digests/Blake3Digest.java#L265-L270

there might be similar inconsistencies among other digest algorithms.

**Comment by dghgit** [comment]
Yes, I agree that sucks... afraid we're stuck with it now though. Sorry. I've added specific mention of the sizing to the JavaDoc.

**Comment by dghgit** [comment]
Okay, it's now bits, if the value is less than 100 it assumes bytes. Not ideal, but a lot less confusing.
