### ISSUE TITLE
Compatibility to Jakarta Mail 2.x.x

### ISSUE THREAD

**Issue by anothernode** [bcgit/bc-java#1174]
The [namespace for the Jakarta Mail packages changed](https://github.com/eclipse-ee4j/mail/releases/tag/2.0.0) from `javax.mail.*` to `jakarta.mail.*` going from version 1.6.x to version 2.x.x.

In a project I'm working on, this breaks the code where Bouncy Castle interfaces with Jakarta Mail. For example:

```
import org.bouncycastle.mail.smime.SMIMESignedGenerator;
import jakarta.mail.internet.MimeMessage;

var signer = new SMIMESignedGenerator();
var email = new MimeMessage();
signer.generate(email);
```

This fails because `signer.generate()` expects a `javax.mail.internet.MimeMessage`, not a `jakarta.mail.internet.MimeMessage`.

According to the Jakarta Mail release notes, the different package namespace was the only change in Jakarta Mail 2.0.0 (see link above).

I'm using `org.bouncycastle:bcmail-jdk15on:1.70`, the latest version I could find on [mvnrepository.com](https://mvnrepository.com/artifact/org.bouncycastle/bcmail-jdk15on).

**Comment by tonywasher** [comment]
A Jakarta Mail compatible jar was added in 1.69. Please try org.bouncycastle:bcjmail-jdk15on:1.70

**Comment by anothernode** [comment]
> A Jakarta Mail compatible jar was added in 1.69. Please try org.bouncycastle:bcjmail-jdk15on:1.70

@tonywasher, thanks for your reply!

If you read what I wrote in the issue, you can see, that `org.bouncycastle:bcjmail-jdk15on:1.70` is exactly what I'm using and that I'm not talking about compatibility to Jakarta Mail in general, but compatibility to Jakarta Mail **2.x** specifically.

**Comment by anothernode** [comment]
I'm sorry, I missed that little `j`! I guess that's actually the solution for my problem then. Thanks for your help!
