### ISSUE TITLE
org.bouncycastle.openpgp.examples.ClearSignedFileProcessor.verifyFile() does not write output in case of a single line clear text section.

### ISSUE THREAD

**Issue by gitolathe** [bcgit/bc-java#118]
Verifying a single line message like the one below using `ClearSignedFileProcessor.verifyFile()` doesn't save the clear text to the `out` output stream. This is because the call to `readInputLine()` [`ClearSignedFileProcessor.java:128`] switches the `ArmoredInputStream`'s `clearText` variable to `false` when it detects the dash on the succeeding line thus the `if` statement [`ClearSignedFileProcessor.java:131`] is false and the `ByteArrayOutputStream` is never saved to disk.

    -----BEGIN PGP SIGNED MESSAGE-----
    Hash: SHA1
    
    This is a test payload!
    -----BEGIN PGP SIGNATURE-----
    Version: BCPG v1.52
    
    iQFcBAEBAgBGBQJV2zJmPxxPbGEgVGhlYW5kZXIgKENlcnQgZm9yIHVuaXQgdGVz
    dGluZykgPG9sYS50aGVhbmRlckBuYXNkYXEuY29tPgAKCRCa4AVZRxMEL7oQCACS
    grNJiNRxv8nO42okU9oUJlP1oIebPenTynUzgEtSoLCZ2zjOVQYpC6w6UgRjzcIG
    JD/1rv0upTmsi5sgRTEaOp+wkFJ93waYjFCgXTGJM2LfkDo+YZHMDROlekacwire
    N3m/cOhTB0hc9pmzd/Vg8NLonXfeVl2LZepkN9nTxMmIodE615OaMa6AhWkVIBuK
    iiIAFpN0JKCqtf84rr/vew134Za6qA6AkoG10TDyzes9gIndCqo6GIfBClAsyY3q
    TQR5x58liLRdlsX4vhvIdJ0wj8cA5adapN30wEj3MMvNGbAtAgvdXeJ7fPy2tQJo
    vOkzOVQo9JWZ/s7hcuTy
    =RCyW
    -----END PGP SIGNATURE-----

For multi-line clear text `verifyFile()` works as expected.

**Comment by bcgit** [comment]
Thanks for the report. Now fixed.
