### ISSUE TITLE
Weird ASN.1 data with CMSSignedDataGenerator

### ISSUE THREAD

**Issue by adrienbricchi** [bcgit/bc-java#120]
Hi,

In a standard PKCS7 signature, generated with BouncyCastle, the ASN.1 signature data seems not perfect.
Some Sequence objects length are always set with a 0x80 (undefined) value.

Everything else is correct, though. The length is well set for every other data type.
If I use the sun.security packages to wrap the Bouncy signature in a PKCS7, every length is well set (same data to sign and same signature certificate) :
http://img11.hostingpics.net/pics/479305bouncy.png (Boucy)
http://img15.hostingpics.net/pics/803744sun.png (sun.security)

OpenSSL seems to have a hard time reading a p7s generated without these valid lengths.
The verification is successful using Bouncy or Spongy libraries, but fails with OpenSSL.
The Iaik PKCS#7 wrapper get its lengths right too.

So I sign with Bouncy and wraps with Sun, it do the trick.
But this CMSSignedDataGenerator would be useful on Android, or any other Sun-free JVM.

**Comment by bcgit** [comment]
0x80 is the BER length value for indefinite-length, as CMS/PKCS7 is defined for BER this is correct usage, it is also the only way to handle very large data streams for signing in a limited memory environment. 

CMSSignedData.toASN1Structure().getEncoded(ASN1Encoding.DL)

will produce a definite-length wrapper around the CMS SignedData object.

Please do not report "bugs" without at least checking the standards concerned.
