### ISSUE TITLE
requires org.bouncycastle.util should probably be transitive

### ISSUE THREAD

**Issue by torakiki** [bcgit/bc-java#1205]
Hi,
I'm in the process of moving a project from classpath to modulepath. I got a compile error which boils down to `CMSEnvelopedData` public constructor taking a `ContentInfo` argument https://github.com/bcgit/bc-java/blob/36e75a9a26479420d44008cefd28de2f2db083c3/pkix/src/main/java/org/bouncycastle/cms/CMSEnvelopedData.java#L68 which implies readability on the `org.bouncycastle.util` module where `ContentInfo` resides and it should be expressed by including the `transitive` modifier: `requires transitive org.bouncycastle.util`

**Comment by dghgit** [comment]
I've made this change - it's now in 172 b14 as well - see https://www.bouncycastle.org/betas for details
