### ISSUE TITLE
[junit] Test org.bouncycastle.cms.test.AllTests FAILED

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#121]
Today's Github version of BC fails CMS and I18N tests. I'm concerned of the CMS failure.

* Name: testOpenSSLVectors
* Status: Error
* Type: N/A   
```
java.lang.NullPointerException
at java.io.Reader.<init>(Reader.java:78)
at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
at org.bouncycastle.cms.test.NewEnvelopedDataTest.testOpenSSLVectors(Unknown Source)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)
```

![bc-fails-opensslvectors](https://cloud.githubusercontent.com/assets/5923577/10504033/19275064-72ca-11e5-8686-aaa30fb99c5d.png)

**Comment by bcgit** [comment]
Sorry. Fixed.

**Comment by mouse07410** [comment]
Sorry, it is not fixed. Just pulled the fresh stuff from Github, and hitting the same failure:

![bc-java-fails-opensslvectors](https://cloud.githubusercontent.com/assets/5923577/10514917/c9fbadf0-731e-11e5-9d1d-0818ba07b35d.png)

**Comment by bcgit** [comment]
Not sure what happened there for some reason the mirror hasn't picked up the change to the ant file, I've touched the file and recommited it. The mirror seems to have picked up the change this time, it should appear on github shortly. Change is in ant/bc+-build.xml

**Comment by mouse07410** [comment]
I confirm that the current Github stuff fixed the above problem.

Thanks!
