### ISSUE TITLE
Contribution process

### ISSUE THREAD

**Issue by maratkalibek** [bcgit/bc-java#1211]
Hello!
In our country we have specific format of key store and signature mechanism (little endian vs big endian).
My idea is to contribute to BC in order to support our formats.

Please, can you point me a link to contribution guide.

**Comment by dghgit** [comment]
It's at the bottom of the master README... a more helpful suggestion would  to implement one thing and then send a pull request. It's very difficult to review submissions with lots of files, it's better to send us a few things at a time. Thanks.

**Comment by dghgit** [comment]
Regarded as answered.
