### ISSUE TITLE
Missing modifiers in several NTRU-PQC classes (e.g. BCNTRULPRimePrivateKey.java and BCNTRULPRimePublicKey.java)

### ISSUE THREAD

**Issue by java-crypto** [bcgit/bc-java#1213]
Dear BC-Team,
I'm trying to rebuild the private and public keys for the PQC algorithms "SNtruPrime" and "NtruLPRime". I found that some
methods are not available because the "public" modifier ist missing. Using Reflection I could retrieve the values and the
key rebuilding is working as expected.

Kindly add the "public" modifier to these methods:

```
https://github.com/bcgit/bc-java/blob/master/prov/src/main/java/org/bouncycastle/pqc/jcajce/provider/ntruprime/BCNTRULPRimePrivateKey.java
    NTRULPRimePrivateKeyParameters getKeyParams()
    {
        return params;
    }

https://github.com/bcgit/bc-java/blob/master/prov/src/main/java/org/bouncycastle/pqc/jcajce/provider/ntruprime/BCNTRULPRimePublicKey.java
    NTRULPRimePublicKeyParameters getKeyParams()
    {
        return params;
    }

https://github.com/bcgit/bc-java/blob/master/prov/src/main/java/org/bouncycastle/pqc/jcajce/provider/ntruprime/BCSNTRUPrimePrivateKey.java
    SNTRUPrimePrivateKeyParameters getKeyParams()
    {
        return params;
    }

https://github.com/bcgit/bc-java/blob/master/prov/src/main/java/org/bouncycastle/pqc/jcajce/provider/ntruprime/BCSNTRUPrimePublicKey.java
    SNTRUPrimePublicKeyParameters getKeyParams()
    {
        return params;
    }

Btw: when editing you should change the comment in the private key classes, looks like a copy & paste error:

    /**
     * Compare this SPHINCS-256 private key with another object.
     *
     * @param o the other object
     * @return the result of the comparison
     */
public boolean equals(Object o)
...
```

Greetings and thanks, Michael

**Comment by dghgit** [comment]
Thanks, I fixed the comment.

The methods you are referring to are restricted for a reason. Examples of doing encoding and decoding of keys in the JCA can be found in:

https://github.com/bcgit/bc-java/blob/master/prov/src/test/java/org/bouncycastle/pqc/jcajce/provider/test/NTRULPRimeKeyPairGeneratorTest.java

https://github.com/bcgit/bc-java/blob/master/prov/src/test/java/org/bouncycastle/pqc/jcajce/provider/test/SNTRUPrimeKeyPairGeneratorTest.java

**Comment by java-crypto** [comment]
Dear David, Thanks for your respond.
Your linked examples are working very well, but shifting the problem just another place. As the NTRULPRimeKEMGenerator is accepting a (AsymmetricKeyParameter) publicKey and NTRULPRimeKEMExtractor takes (AsymmetricKeyParameter) privateKey only we need to serialize the AsymmetricKeyParameter key's - 
but doing that I receive a java.io.NotSerializableException: org.bouncycastle.pqc.crypto.ntruprime.NTRULPRimePublicKeyParameters.
So the main question remains - how to get the private and public keys as (encoded) byte arrays AND rebuild the original keys, sorry for asking again.
Thanks and greetings, Michael

**Comment by dghgit** [comment]
First decide if you are going to use the low level API or the JCA - don't mix them. There's s currently no direct API support for KEMs in the JCA, however if you look in the test classes for the BCPQC provider you'll see an avenue exists via the KeyGenerator class to make use of the KEM API.

If you are using the low level API you can serialise the keys in a portable fashion by using PrivateKeyInfoFactory and SubjectPublicKeyInfoFactory in ...pqc.util, they will produce encoded ASN.1 data representing the keys. If you are using the JCA level you need to use PKCS8EncodedKeySpec and X509EncodedKeySpec and the KeyFactory class.

**Comment by dghgit** [comment]
Assuming question now resolved.
