### ISSUE TITLE
Duplicate escaped spaces in X500 Name in BCStyle and RFC4519Style

### ISSUE THREAD

**Issue by coder4712** [bcgit/bc-java#1215]
Hallo,
There is a bug in org.bouncycastle.asn1.x500.style.IETFUtils.valueToString(ASN1Encodable). If a RDN contains only spaces, the algorithm fails and escape characters twice.

> OU=<with one space>
> will be escaped to
> OU=\\ 

> OU=<with three space>
> will be escaped to
> OU=OU=\ \ \\\\ 

Test code:

	String ou = " ";// same for all strings with only spaces in it
	X500NameStyle style = BCStyle.INSTANCE;// same for org.bouncycastle.asn1.x500.style.RFC4519Style
        X500NameBuilder builder = new X500NameBuilder(style);
        builder.addRDN(BCStyle.OU, ou);
        X500Name n = builder.build();
        String s = n.toString();
        
        System.out.println(""+s);
        
        X500Name n2 = new X500Name(style, s);// parse it back to object
        if (!n.equals(n2)) // compare both objects, should be equal
        	throw new AssertionError("Failed");
        	
The bug is in org.bouncycastle.asn1.x500.style.IETFUtils.valueToString(ASN1Encodable)	

If the RDN contains only spaces, it escapes the string from start to end and partly twice from end to start.

        int start = 0;
        if (vBuf.length() > 0)
        {
            while (vBuf.length() > start && vBuf.charAt(start) == ' ')
            {
                vBuf.insert(start, "\\");
                start += 2;
            }
        }

        int endBuf = vBuf.length() - 1;

        while (endBuf >= 0 && vBuf.charAt(endBuf) == ' ')
        {
            vBuf.insert(endBuf, '\\');
            endBuf--;
        }

        return vBuf.toString();

My proposal for change (second loop only from end up to position from first loop):

        int start = 0;
        if (vBuf.length() > 0)
        {
            while (vBuf.length() > start && vBuf.charAt(start) == ' ')
            {
                vBuf.insert(start, "\\");
                start += 2;
            }
        }

        int endBuf = vBuf.length() - 1;
        
        while (endBuf >= start && vBuf.charAt(endBuf) == ' ')
        {
            vBuf.insert(endBuf, '\\');
            endBuf--;
        }
        
        return vBuf.toString();

Thanks

**Comment by dghgit** [comment]
Thanks for the report. Done!
