### ISSUE TITLE
Building bcpkix and bcprov sources using Maven

### ISSUE THREAD

**Issue by adityamalik** [bcgit/bc-java#122]
Hello,

I am interested in compiling the source files for bcpkix-jdk15on-1.51-sources and bcprov-jdk15on-1.51-sources myself. I found the corresponding JAR files from these two locations: 
http://repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk15on/1.51/
http://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.51/

What is the best way to compile these source files? I am fairly new to using Maven, but I noticed that the libraries have associated pom.xml files. Would building with these POM files in Eclipse be sufficient for compiling the source files? 

Thanks,
Aditya

**Comment by bcgit** [comment]
Sorry, I have no idea on this one - the best I recommend is try it and see. The POM files should at least give Eclipse what dependencies are required, it may need some extra help in generating the final assemblies though.
