### ISSUE TITLE
Bouncy Castle is throwing "mac check in OCB failed" when trying to decrypt an AES message

### ISSUE THREAD

**Issue by vmf** [bcgit/bc-java#1220]
Hey guys!
I need to decrypt an AES message. I was able to make it work on python(using the pycryptodome library) but I wasn't successful on kotlin/java. Since the decryption mode is OCB and Java does not support it by default, I had to use the Bouncy Castle library.

Here's the working python code:
```
def decrypt_aes_message(shared_key, encrypted_message):
    encrypted_msg = b64decode(encrypted_message["encryptedMessage"].encode())
    tag = b64decode(encrypted_message["tag"].encode())
    nonce = b64decode(encrypted_message["nonce"].encode())
    cipher = AES.new(shared_key.encode(), AES.MODE_OCB, nonce=nonce)
    return cipher.decrypt_and_verify(encrypted_msg, tag).decode()
```

Here's the java code:
```
fun decryptAesMessage2(sharedKey: String, encryptedMessageData: Map<String, String>): ByteArray {
    var encryptedMessage = encryptedMessageData["encryptedMessage"]!!.utf8Base64Decode()
    var tag = encryptedMessageData["tag"]!!.utf8Base64Decode()
    var nonce = encryptedMessageData["nonce"]!!.utf8Base64Decode()

    var key = KeyParameter(sharedKey.toByteArray(Charsets.UTF_8))
    var params = AEADParameters(key, tag.size*8, nonce)
    var cipher = OCBBlockCipher(AESEngine(), AESEngine())

    cipher.init(false, params)

    val out = ByteArray(cipher.getOutputSize(encryptedMessage.size))
    var offset = cipher.processBytes(encryptedMessage, 0, encryptedMessage.size, out, 0)
    offset += cipher.doFinal(out, offset) // Throwing exception here

    return out
}
```

The java code is throwing the exception **org.bouncycastle.crypto.InvalidCipherTextException: mac check in OCB failed** on cipher.doFinal

The file [debug.zip](https://github.com/bcgit/bc-java/files/9463481/debug.zip) has the complete problem reproducer.
Inside the zip file you'll find:

- **py_working_code.py** - the working python script(needs pycryptodome in order to work. You can install pycryptodome using `pip install pycryptodome`)
- **bc-debug** - gradle project reproducing the problem

**Comment by mouse07410** [comment]
Providing a **complete** problem reproducer would make it much easier our attempt to debug your problem.

As it is, I don't have time to write the correct complete wrapper in both Python and Java to run the tests locally.

**Comment by vmf** [comment]
@mouse07410 You'll find in this [debug.zip](https://github.com/bcgit/bc-java/files/9463481/debug.zip) file the complete problem reproducer.
Inside the zip file you'll see:

- **py_working_code.py** - the working python script(needs pycryptodome in order to work. You can install pycryptodome using `pip install pycryptodome`)
- **bc-debug** - gradle project reproducing the problem

**Comment by vmf** [comment]
@mouse07410 I've updated the issue with the complete problem reproducer

**Comment by mouse07410** [comment]
Here's what I get from my Java-only program (unrelated to yours) that uses AES-OCB:
```
AES/OCB using AEADParameters()

Got working AES/OCB Keysize=256 bits  Blocksize=16 Plaintext.length=63
AES/OCB len: reserved 75 bytes for encr buf; processBytes() can write 48 bytes
AES/OCB enc: 16 bytes written 47 of PT remaining
AES/OCB enc: 16 bytes written 31 of PT remaining
AES/OCB enc: 16 bytes written 15 of PT remaining
AES/OCB enc: 0 bytes written 15 of PT remaining
AES/OCB fin: 27 bytes written
AES/OCB AAD: Authenticated Text #12
AES/OCB Par: Nonce=000102030405060708090a0b len=12
AES/OCB TAG: 8956c91b0df6284c0655ac78 TAGlen=12 bytes or 96 bits
AES/OCB PT : 000102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e len=63
AES/OCB CT : 0d7a07f77bdbcd558ba7b88b04e7fa6e3f7b49995364ef783096c15bc1ad76750619b702a1a9384234982c51bbd2ecae229b591d0648f7225ae7573d3dd2978956c91b0df6284c0655ac78 len=75
AES/OCB len: reserved 63 bytes for dec buf;  processBytes() can write 48 bytes
AES/OCB dec: 48 bytes written
AES/OCB fin: 15 bytes written
AES/OCB PTd: 000102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e len=63
```

> I've updated the issue with a complete problem reproducer

My apologies - I hoped for a **compact** self-complete reproducer, not the entire project. I don't program in Kotlin, so can't help you there - but I'll check what your Python code is doing, and will try to replicate that in Java.

**Comment by vmf** [comment]
@mouse07410 If it helps, here is a java file reproducing the problem:

```

import org.bouncycastle.crypto.InvalidCipherTextException;
import org.bouncycastle.crypto.engines.AESEngine;
import org.bouncycastle.crypto.modes.OCBBlockCipher;
import org.bouncycastle.crypto.params.AEADParameters;
import org.bouncycastle.crypto.params.KeyParameter;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;

public class CipherTest {
    public static void main(String[] args) throws InvalidCipherTextException {
        var key = "f009Cip5hM4Obbb6E2MT5npJBHlc82vD";
        var messageData = new HashMap<String, String>();
        messageData.put("encryptedMessage", "XMQx/xbVVTbMdpMiTXVp5XPICm11Vw2pgALpVI0NgbdqLLmikhPuu9M+qQzyOVZlZZBRlscijpyAZDsLGcTSPP54O35oKNp//PuOrWsN/ZZMkCByKCSBysJLRiZV1OjZDg01gi5/nYNbUgGGd8uRGKfBaKjjXngZ1J89GOvDeWPQcjbfbdzd9w+jbZGZ5jnAIChOL1Uqohf+6KHtjR/H06fFTHwB1abzAQrGbCNBNXBmN9+zEu7Auy3NPWKrZ+SL5Nk=");
        messageData.put("tag", "ZcqXSBqYU5TjgdMC+bMeUQ==");
        messageData.put("nonce", "knQgYf1MsOs8smx9GtWM");

        decryptAesMessage(key, messageData);
    }

    private static byte[] decryptAesMessage(String sharedKey, Map<String, String> messageData) throws InvalidCipherTextException {
        var encryptedMessage = utf8Base64Decode(messageData.get("encryptedMessage"));
        var tag = utf8Base64Decode(messageData.get("tag"));
        var nonce = utf8Base64Decode(messageData.get("nonce"));

        var key = new KeyParameter(sharedKey.getBytes(StandardCharsets.UTF_8));
        var params = new AEADParameters(key, tag.length*8, nonce);
        var cipher = new OCBBlockCipher(new AESEngine(), new AESEngine());

        cipher.init(false, params);

        var out = new byte[cipher.getOutputSize(encryptedMessage.length)];
        var offset = cipher.processBytes(encryptedMessage, 0, encryptedMessage.length, out, 0);
        offset += cipher.doFinal(out, offset);

        return out;
    }

    private static byte[] utf8Base64Decode(String value) {
        return Base64.getDecoder().decode(value.getBytes(StandardCharsets.UTF_8));
    }
}

```

**Comment by mouse07410** [comment]
Please show Python **encryption** code, hopefully comparable in size to `py_working_code.py`

**Comment by mouse07410** [comment]
I made a few trials, and found surprising lack of interoperability between Cryptodome and BouncyCastle. In short, even after spending some time on this ~~crap~~ stuff, I could not encrypt-decrypt successfully either across Python-Java platforms, or within Python (obviously, there is a way to get it working, but it must require more time than I was able to dedicate to it). All I could achieve was encrypting-decrypting within the Java code.

**Comment by peterdettman** [comment]
The specification BC follows is [RFC 7253](https://www.rfc-editor.org/rfc/rfc7253), which AFAICT pycryptodome also claims to follow. Our test suite includes the test vectors from Appendix A. It would be worth establishing first that pycryptodome also passes those test vectors.

**Comment by mouse07410** [comment]
So far, the bulkt of problems seems to be with pycryptodome, and going back-and-forth between JSON, Base64, and `byte []`. "Normal" Java code is, at least, self-consistent - unlike Python code (in my experience).

**Comment by mouse07410** [comment]
> I've also posted this question [here](https://stackoverflow.com/questions/73557729/bouncy-castle-is-throwing-mac-check-in-ocb-failed-when-trying-to-decrypt-an-ae/73561592#73561592)

They gave an excellent answer. I'll experiment more, but so far they seem to be right on the spot: the problem is in the Python library, and the 3rd party that provides you with encrypted messages, needs to implement a workaround. Until then, you can use a suggested hack-fix (truncate received nonce from 15 bytes to 14).

**Comment by dghgit** [comment]
Does not appear to be a BC related bug.
