### ISSUE TITLE
RSA signatures fail validation testing since version 1.69

### ISSUE THREAD

**Issue by gsharris** [bcgit/bc-java#1221]
Producing an RSA signature with the bouncycastle library starts failing after version 1.68 and seems to affect 1.69, 1.70, and 1.71.

How to repeat:
1. Generate any RSA 4096 certificate/private key pair
2. Use the bouncy castle library to sign a precomputed hash like so:
DigestAlgorithmIdentifierFinder hashAlgorithmFinder = new DefaultDigestAlgorithmIdentifierFinder();
AlgorithmIdentifier hashingAlgorithmIdentifier = hashAlgorithmFinder.find("SHA-512");
DigestInfo digestInfo = new DigestInfo(hashingAlgorithmIdentifier, hash);
Signature signature = Signature.getInstance("NONEwithRSA", "BC");
signature.initSign(privateKey);
signature.update(digestInfo.getEncoded());
byte[] signed = signature.sign();
(we also used the Cipher methods for "RSA/ECB/PKCS1Padding" and it produced the same correct results for 1.68 but not 1.69/1.70/1.71)
3. Compare bytes against openssl verify command and public key as follows: It works in version 1.60,1.68, but fails in 1.69, 1.70, 1.71:
openssl dgst -sha512 -verify certificate.pem -signature rsa.bin

**Comment by dghgit** [comment]
It's the DefaultDigestAlgorithmIdentifierFinder. It's actually a CMS support class, not a PKCS#1 support class. PKCS#1 requires the use of DER NULL for SHA-512. CMS does not.

**Comment by dghgit** [comment]
Not actually a bug.

**Comment by gsharris** [comment]
@dghgit Thanks for the response, it was helpful. I've confirmed your solution. I had to change to find the algorithm without the DerNull encoding, and then create a new instance of the AlgorithmIdentifier with the DerNull encoding instance as shown below.  Is there a cleaner way to get the algorithm with the DerNull encoding like you could in 1.68 through a different library?  Thanks for your help. 

(Revised code, works on 1.69/1.70/1.71):
DigestAlgorithmIdentifierFinder hashAlgorithmFinder = new DefaultDigestAlgorithmIdentifierFinder();
AlgorithmIdentifier hashingAlgorithmIdentifier = hashAlgorithmFinder.find("SHA-512");
AlgorithmIdentifier hashingAlgorithmIdWithDerNullEncoding = new AlgorithmIdentifier(hashingAlgorithmIdentifier.getAlgorithm(), DERNull.INSTANCE);
        DigestInfo digestInfo = new DigestInfo(hashingAlgorithmIdWithDerNullEncoding, hash);
Signature signature = Signature.getInstance("NONEwithRSA", "BC");
signature.initSign(privateKey);
signature.update(digestInfo.getEncoded());
byte[] signed = signature.sign();
