### ISSUE TITLE
License info in POM states Apache 1.1 instead of Apache 2.0 for bcpg-Jars 

### ISSUE THREAD

**Issue by ohecker** [bcgit/bc-java#1222]
The pom.xml files of bcpg* packages on Maven Central state Apache 1.1 as applicable license (besides the Bounce Castle License), see e.g. https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/1.71.1/bcpg-jdk18on-1.71.1.pom .

This should be checked/corrected as the overall [Readme](https://github.com/bcgit/bc-java/blob/master/README.md) as well as the headers of the included BZIP2 implementation source files (https://github.com/bcgit/bc-java/tree/master/pg/src/main/java/org/bouncycastle/apache/bzip2) state Apache 2.0 as applicable license.

**Comment by dghgit** [comment]
Thanks for the report. This should be corrected in the next release.
