### ISSUE TITLE
ChaCha20Poly1305 AAD_LIMIT overflows

### ISSUE THREAD

**Issue by brandonweeks** [bcgit/bc-java#1224]
In bac5367 `AAD_LIMIT` limit was from `Long.MAX_VALUE` to `Long.MAX_VALUE - Long.MIN_VALUE`, which overflows resulting in a practical value of -1. It doesn't appear possible to have a `AAD_LIMIT` value of 2^64 - 1 without using `BigInteger` instead of `long`.

**Comment by peterdettman** [comment]
It's being used as an unsigned 64 bit value in calculations. So -1 actually means 2^64 - 1; see the `incrementCount` method. Let us know if you think there is a problem with it in operation.

**Comment by brandonweeks** [comment]
Ah I see that now, my test had a bug.

```java
aadCount: -1, (BigInteger)aadCount: 18446744073709551615, increment: 1
IllegalStateException
```

That's a neat trick to fake a uint. :) Apologies for the noise.
