### ISSUE TITLE
what's the deal with version 1.71.1 ?

### ISSUE THREAD

**Issue by e4711s** [bcgit/bc-java#1225]
Renovatebot recently detected a new version 1.71.1 of BouncyCastle. Our build using that version fail because e.g. https://repo1.maven.org/maven2/org/bouncycastle/bcprov-ext-jdk18on/ only contains a 1.71 version, but not 1.71.1 .
Also, there has been no release anouncement on bouncycastle.org or tag in this repo for 1.71.1 .
Any information on this? Should anyone even be using 1.71.1, yet?

**Comment by mpshah** [comment]
I am also looking for the same info.  We need to file for a third party product inclusion for our software.  I would like to know the latest version we can use for OpenPGP.  I see 1.71.1 on maven.
1. Is 1.71.1 the latest we should use ?  If so, can you please point me to the source path for this specific version?
2. If 1.71 is the latest instead, please can you point me to the source path for 1.71 ? Thanks.

**Comment by dghgit** [comment]
1.71.1 was a special release to update the SPHINCS+ implementation to 3.1. Other than that it's 1.71.

1.72 should be coming out in the next couple of weeks - I would recommend waiting for that (1.71.1 was because one of the support customers really really couldn't wait and needed a patch release).

**Comment by dghgit** [comment]
1.72 now out!
