### ISSUE TITLE
BouncyCastle fips does not support 2048-bit key size?

### ISSUE THREAD

**Issue by esnyderCPI** [bcgit/bc-java#1231]
Hello,

   I am trying to implement a bouncy castle fips solution.  It appears that there is a defined maximum of 256 set on the setSecurityStrength() method in the org.bouncycastle.crypto.fips.FipsDRGB.Builder package.  The minimum today for that is 2048 bits so I was wondering if there is some way to make that check more "up-to-date" or if there is a different way to enter the key size value?  It also seems that the recommended entropy size should be at least equal to the RSA key size?

Thanks

**Comment by dghgit** [comment]
The security strength is not the same as the bit length. For example a 2048 bit RSA key has a security strength of 112 bits. You need to configure the key size via the KeyPairGenerator for the algorithm concerned.
