### ISSUE TITLE
org.bouncycastle.asn1.DlSequence can not cast to org.bouncycastle.asn1.ASN1Integer

### ISSUE THREAD

**Issue by mishrashivam216** [bcgit/bc-java#1236]
Issue Description
- this issue occurs when we send mail from web to mobile
-  Exception : read content exception
-  Exception throw at: 
CMSEnvelopedDataParser dataParser = new CMSEnvelopedDataParser(sharedInputstreamobject)
- we are reading private key correctly
- this case occurs only sign+ encryption case

**Comment by dghgit** [comment]
Without a stack trace it's impossible to even make a suggestion here.

**Comment by dghgit** [comment]
Closing as inactive and insufficient data.
