### ISSUE TITLE
Maven delay?

### ISSUE THREAD

**Issue by OrangeDog** [bcgit/bc-java#1237]
1.72 was released two days ago, but still no sign of it in the Central repo:

https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk18on/

**Comment by vanitasvitae** [comment]
Unfortunately, there is usually a delay for publication on Maven Central (see eg. #1139, #1070, ...).
So from experience I'd be patient :)

**Comment by dghgit** [comment]
They should now be up. I've confirmed they've appeared on repo1 so they should be madly propagating at this point.

**Comment by OrangeDog** [comment]
Can the delay be investigated and fixed then?

Most projects are fully available within hours of their release.

**Comment by dghgit** [comment]
I can say the delay isn't due to sonatype/maven central. It's definitely on our end. Part of the process is manual which is the biggest contributor, we'll see what we can do.
