### ISSUE TITLE
OCBBlockCipher license prevents from using bcprov artifact in some legal contexts

### ISSUE THREAD

**Issue by mickaelistria** [bcgit/bc-java#1240]
Eclipse ecosystem does use the bcprov jar extensively for some actions (download PGP signatures check, Git commit signatures...). Some Eclipse IP rules are checked to verify the library that are used do not introduce some legal risk upon the Eclipse project and its adopters. Those rules have determined (for a long time) that OCBBlockCipher is such a legal risk; and there has been a habit of using a and delivering a re-packaged bcprov to exclude this particular class in most Eclipse distributions. However this situation is a bit cumbersome as the Eclpse ecosystem is getting closer from Maven one and would like to avoid having parallel artifacts.
The particular concern is expressed at https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/3286#note_1020671 ( @waynebeaton can probably tell more if you ask him).
What we'd love to see is a solution that would make bcprov "safe" to use as-it from IP perspective at Eclipse. One proposal can be for example that the OCBBlockCipher get moved to another artifact, either an existing one with other IP-challenging stuff, or into its dedicated bcocb artifact, to clean the central bcprov from this particular concern.
Are there other approaches one can recommend? If not, is the former proposal acceptable? We could most likely take care of implementing the refactoring if the proposal is acceptable.

**Comment by dghgit** [comment]
In view of:
https://mailarchive.ietf.org/arch/msg/cfrg/qLTveWOdTJcLn4HP3ev-vrj05Vg/

Would you clarify what the risk is?

**Comment by mickaelistria** [comment]
@dghgit thanks, I was not aware of that. I'm not the one who actually evaluate whether there is a legal risk or not (this service is provided by Eclipse Foundation, @waynebeaton would be the representative here). I'll make sure they are aware of this matter and can decide to re-evaluate that. In the meantime, I think that the OCBBlockCipher.java file should then present an updated header, clarifying that the underlying algorithm is public domain and dropping everything that mentions patent.

**Comment by waynebeaton** [comment]
I'm pretty sure that this is good news. I'll need go through our notes to confirm, but this is helpful. Thanks @dghgit.

**Comment by dghgit** [comment]
Good point, I'll get the JavaDoc updated as well.

**Comment by dghgit** [comment]
JavaDoc now updated to properly reflect the current standing, having including the owner's original text as well.

**Comment by mickaelistria** [comment]
Thank you very much @dghgit , your insights here have drastically improved things on Eclipse end!
