### ISSUE TITLE
IOException: Unexpected protocol during https TLS1.2 two-way authentication tls handshake on Android Q or above

### ISSUE THREAD

**Issue by cuijiufeng** [bcgit/bc-java#1245]
`securityParameters.applicationProtocol = TlsExtensionsUtils.getALPNExtensionServer(serverExtensions);`
If the server does not return `EXT_ServerHello_ application_ layer_ protocol_ negotiation`, Then `securityParameters.applicationProtocol` will be null. Then the `getApplicationProtocol (SecurityParameters)` method of JsseUtil will return the "" string.

        ProtocolName applicationProtocol = securityParameters.getApplicationProtocol();
        if (null == applicationProtocol) {
            return "";
        }

On the other hand, in the Android environment, okhttp is running RealConnection's `void connectTls (int readTimeout, int writeTimeout,ConnectionSpecSelector connectionSpecSelector)`

        // Success! Save the handshake and the ALPN protocol.
        String maybeProtocol = connectionSpec.supportsTlsExtensions()
                ? Platform.get().getSelectedProtocol(sslSocket)
                : null;
        socket = sslSocket;
        source = Okio.buffer(Okio.source(socket));
        sink = Okio.buffer(Okio.sink(socket));
        handshake = unverifiedHandshake;
        protocol = maybeProtocol != null
                ? Protocol.get(maybeProtocol)
                : Protocol.HTTP_1_1;

On Android Q, click `Platform. get() GetSelectedProtocol (sslSocket)` method adds `return socket. getApplicationProtocol();`. Then the `maybeProtocol `is the "" string instead of null, and the default Protocol will not be used HTTP_ 1_ 1. The error `throw new IOException ("Unexpected protocol:"+protocol)` is reported when the string "" cannot be parsed;

**Comment by peterdettman** [comment]
See javadoc, e.g. https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLEngine.html#getApplicationProtocol--:

> null if it has not yet been determined if application protocols might be used for this connection, an empty String if application protocols values will not be used, or a non-empty application protocol String if a value was successfully negotiated.

In any case the empty string is not a valid ProtocolName, (which has length from 1 to 255 (RFC 7301):

`opaque ProtocolName<1..2^8-1>;`

I suggest opening an issue with okhttp.

**Comment by cuijiufeng** [comment]
thanks
