### ISSUE TITLE
org.bouncycastle.provider module doesn't export org.bouncycastle.asn1.cryptlib but needs to

### ISSUE THREAD

**Issue by mikehearn** [bcgit/bc-java#1247]
With the new Bouncy Castle release there's been a regression in PGP signing when using certain types of elliptic curves keys. The cause is that the core module doesn't export the `org.bouncycastle.asn1.cryptlib` package that contains `CryptlibObjectIdentifiers`, but the `PGPPublicKey` class tries to use that class in the `init` method (line 96 in the 1.72 release). The result is an `IllegalAccessException`.

**Comment by dghgit** [comment]
Further to this, there is now a new version of the PGP API 172.1 on the https://www.bouncycastle.org/latest_releases.html it should avoid the cryptlib issue.

**Comment by mikehearn** [comment]
Thanks!
