### ISSUE TITLE
Remove support for Dual_EC_DRBG

### ISSUE THREAD

**Issue by rhymoid** [bcgit/bc-java#125]
Dual_EC_DRBG is suspected by cryptography researchers to contain a backdoor. For example, NIST retracted support on 2014-04-21 and urged users to transition to a different PRNG.

It would be wise to remove Dual_EC_DRBG from BouncyCastle, if only to prevent accidental use of this mistrusted algorithm.

**Comment by rhymoid** [comment]
ping @peterdettman

**Comment by bcgit** [comment]
It's on the list, but we're still working out what to do about it. We're not going to remove it totally as it's still in use (in the research sense), we'll probably just make it harder to go to.

**Comment by mouse07410** [comment]
"Suspected"... I always thought that security researchers should have a *healthy* dose of paranoia, but see now that sky is the limit...

I suggest doing nothing with or about it, just make sure other RNGs are easily available. And have at least one that can include RDRAND (and RDSEED if available) output into the mix.

**Comment by rhymoid** [comment]
If not removing the implementation, don't build it by default. Force the user to set a flag that feels like they're signing their name in blood on the dotted line.

Any serious library should prevent the use of broken and backdoored cryptographic primitives, unless the user is really explicit about wanting to use them. If it's really used in "research" settings, the researcher will figure out soon enough that their setup stopped working, and after consulting a changelog and/or other documentation, enable it again.

But please, protect the average programmer against themselves, because they just grab some off-the-shelf library. Are you aware that bc-java has been copy-pasted into numerous projects, meaning that they'll probably never apply any security updates? And that's just the FOSS tip of the iceberg.

Programmers are clueless about security. How critical their application is doesn't matter; I can tell you some stories of their stupidity. Protect their users from them, and don't build this code by default.

**Comment by bcgit** [comment]
The class is no longer accessible for use with the SP800SecureRandomBuilder. We'll probably review this again later, but at the moment it would take a bit of work to get to.
