### ISSUE TITLE
BCPGInputStream may return invalid packet tags when underlying stream is not buffered

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#1257]
Hey!
I noticed, that when basing a `BCPGInputStream` on an unbuffered `InputStream`, `nextPacketTag()` would sometimes return invalid packet tags / nonsensical data.

```java
InputStream decrypted = publicKeyEncryptedData.getDataStream(decryptorFactory);
BCPGInputStream bcpgIn = BCPGInputStream.wrap(decrypted);
int nextPacket = bcpgIn.nextPacketTag(); // would return e.g. -53
```

I found out that I can solve this by wrapping `decrypted` into a `BufferedInputStream`.
Unfortunately, I have not yet found out why the `BCPGInputStream` is struggling with unbuffered streams.

Still, I thought it might be worthwhile reporting this issue and my workaround.

**Comment by dghgit** [comment]
There was an error in #1179 - the offset's missing in the for loop. I guess it must be mostly zero, occasionally not. Try what's in https://www.bouncycastle.org/betas 173b04 or later.

Change should appear in PGPEncryptedData shortly.

**Comment by vanitasvitae** [comment]
Ah damn, I had hoped that this error was not caused by one of my PRs :/.
Glad you found the cause though. I will give 173b04 a try and close this if it solves the issue!

**Comment by dghgit** [comment]
well... I probably should have noticed it. You'll need to do a second download, there were actually two. The updated file should arrive on github in about half an hour if you want to make sure you've got the right one. Think we'll need to do a 172.1 for the PG APIs, need to make sure it's really fixed first though.

**Comment by vanitasvitae** [comment]
Just tried the new b04 (sha1: 03d333fe5fd60fecdba719a1cd357d575eaef22b), but a buffered stream still behaves differently from an unbuffered one.

The symptoms in my case are, that closing closing integrity-protected encrypted data streams via `encryptedData.verify()` fails.
My usage of BCPG is not straight forward though, so let me try to create a minimal, BC-only test case for this.

**Comment by dghgit** [comment]
Check:

https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/PGPEncryptedData.java

against what you have - the second patch is now on github.

**Comment by vanitasvitae** [comment]
Huh, I just took one test vector that fails in PGPainless and wrote a minimal test for it using BC, and there the issue does not happen.
Perhaps now there is still some user error or now-obsolete workaround on my side left? I will continue to investigate.

**Comment by vanitasvitae** [comment]
It turns out, my test vector was working with both BC172 as well as BC173b04, but use of BC is somehow broken.

**Comment by dghgit** [comment]
Great! 172.1 for the BC PG API is now on https://www.bouncycastle.org/latest_releases.html 
Give it a go and let me know if there's any issues. Assuming it checks out I'll publish it to Maven Central.

**Comment by vanitasvitae** [comment]
What will be the version number of the new artefact on Maven Central? 1.72.1?
