### ISSUE TITLE
Remediation for Bad OpenSSL Versions

### ISSUE THREAD

**Issue by witmitchell** [bcgit/bc-java#1267]
Hi,
When uploading my Android app to the store i get this feedback from google: https://support.google.com/faqs/answer/12576638
We are using your library in our project: org.bouncycastle:bcpkix-jdk18on:1.72. I can see that the library is using openSSL, is it using a version between 1.1.1b and 1.1.1h? Where a runtime error could occur?

Thanks in advance.

**Comment by dghgit** [comment]
Sorry, it must be something else. We don't use OpenSSL.
