### ISSUE TITLE
VMPCMAC update method code error

### ISSUE THREAD

**Issue by Steppenwolfe65** [bcgit/bc-java#127]
Code is:
public void update(byte[] in, int inOff, int len)
        throws DataLengthException, IllegalStateException
    {
        if ((inOff + len) > in.length)
        {
            throw new DataLengthException("input buffer too short");
        }

        for (int i = 0; i < len; i++)
        {
            update(in[i]);
        }
    }

Note that 
update(in[i]); 
should be 
update(in[inOff + i]);

**Comment by peterdettman** [comment]
This is now fixed and the test modified to exercise the offset. Thanks for the bug report.
