### ISSUE TITLE
TaggedCertificationRequest Missing Getters

### ISSUE THREAD

**Issue by KyleBS** [bcgit/bc-java#1274]
Hello!

It appears that TaggedCertificationRequest objects (https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/core/src/main/java/org/bouncycastle/asn1/cmc/TaggedCertificationRequest.java) can be constructed but are missing corresponding getters for the bodyPartID and certificationRequest variables. The consequence of this is that the structure needs to be converted to an ASN1Seqence in order to extract them, defeating the point of the class.

Would it be possible to add these getters please?

Best,
Kyle

**Comment by divyansh-gupta** [comment]
Hello, this functionality would be useful for me too.

**Comment by dghgit** [comment]
Oops. Thanks for the report. The missing get() methods have been added. These are now added to the latest beta in https://www.bouncycastle.org/betas (173b09 or later)
