### ISSUE TITLE
PEMUtil ----readPEMObject

### ISSUE THREAD

**Issue by whao189** [bcgit/bc-java#1275]
`String cert = "-----BEGIN CERTIFICATE-----\n" +
                "MIIFVzCCBD+gAwIBAgIQQKY1foNn0BsYOq8TIk8hojANBgkqhkiG9w0BAQUFADCB\n" +
                "tTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL\n" +
                "ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTswOQYDVQQLEzJUZXJtcyBvZiB1c2Ug\n" +
                "YXQgaHR0cHM6Ly93d3cudmVyaXNpZ24uY29tL3JwYSAoYykxMDEvMC0GA1UEAxMm\n" +
                "VmVyaVNpZ24gQ2xhc3MgMyBTZWN1cmUgU2VydmVyIENBIC0gRzMwHhcNMTUwNTI3\n" +
                "MDAwMDAwWhcNMTUxMjI4MjM1OTU5WjCBqTELMAkGA1UEBhMCQ04xEDAOBgNVBAgT\n" +
                "B2JlaWppbmcxEDAOBgNVBAcUB2JlaWppbmcxOTA3BgNVBAoUMEJlaUppbmcgQmFp\n" +
                "ZHUgTmV0Y29tIFNjaWVuY2UgVGVjaG5vbG9neSBDby4sIEx0ZDElMCMGA1UECxQc\n" +
                "c2VydmljZSBvcGVyYXRpb24gZGVwYXJ0bWVudDEUMBIGA1UEAxQLKi5iYWlkdS5j\n" +
                "b20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDS4pfHYsHL5ML9ltnk\n" +
                "LdXG5axFxAw4wkR+AohS75V1CAsFPVi4S67ZJuJAoo7+CLHmakWZenwXzxysvce6\n" +
                "bE9BT27qQe3OCwJueUX/VO8FkmiqK+A9QH9Lgl6egdw1hRV9vvX9fxiGIP/RaafF\n" +
                "rlZLtI23c+z0SfAlyWVQDfc6mnsK5MT7aDreezkDbzJ1poTVVikIJo4+UjLoWheY\n" +
                "cJk8I+3epr3Xb6I5Ga8c0JF8Yotv0gBHfbKS4lhAZjOhsqxmUJKvusNsXCOzSH9G\n" +
                "P41QdjB3bqKPN29QqobDX25SpSOmetBnD4r77Xv+cSRQxPLTBiRPyL/9aNWPfBTe\n" +
                "+D01AgMBAAGjggFrMIIBZzAhBgNVHREEGjAYggsqLmJhaWR1LmNvbYIJYmFpZHUu\n" +
                "Y29tMAkGA1UdEwQCMAAwDgYDVR0PAQH/BAQDAgWgMCsGA1UdHwQkMCIwIKAeoByG\n" +
                "Gmh0dHA6Ly9zZC5zeW1jYi5jb20vc2QuY3JsMGEGA1UdIARaMFgwVgYGZ4EMAQIC\n" +
                "MEwwIwYIKwYBBQUHAgEWF2h0dHBzOi8vZC5zeW1jYi5jb20vY3BzMCUGCCsGAQUF\n" +
                "BwICMBkMF2h0dHBzOi8vZC5zeW1jYi5jb20vcnBhMB0GA1UdJQQWMBQGCCsGAQUF\n" +
                "BwMBBggrBgEFBQcDAjAfBgNVHSMEGDAWgBQNRFwWU0TBgn4dIKsl9AFj2L55pTBX\n" +
                "BggrBgEFBQcBAQRLMEkwHwYIKwYBBQUHMAGGE2h0dHA6Ly9zZC5zeW1jZC5jb20w\n" +
                "JgYIKwYBBQUHMAKGGmh0dHA6Ly9zZC5zeW1jYi5jb20vc2QuY3J0MA0GCSqGSIb3\n" +
                "DQEBBQUAA4IBAQAO0aL9AO6S3zEod2DDIWSz3PP+YXXQNpKF9Kv4KzzFsxPjj1hd\n" +
                "wdlMj/OcOPQ4PSeHyHCSbQ2m5vX2E+0DhUf0rwMhn4oOHQFuzqHKlWPxA51U5pSJ\n" +
                "njTpkS1Hpj7GAz0z0+b2dV7a3//rawJojk2kEog9aVw5U+9fBnXWeO3lhCtNSMrj\n" +
                "Ay/+7hGd/9g59JBSSskd2yoCM0I1wJ7HK1AYoWtZRO1Ufe2I1PfbeY7k520C0x9h\n" +
                "IEXDDVdjurHOiUU2rNz7AjENeXtjpcn8ejx0V92X8ZnA00bZSrVrOYe+0L56yJxh\n" +
                "FUm2aNeOPAaTGk7M7CwWQv0t0FhzcfT08UwL\n" +
                "-----END CERTIFICATE-----";`
parse certificate by BCProvider. PEMUtil ----readPEMObject
code 1 ：
` while (header == null && (line = readLine(in)) != null)
        {
            header = getBoundaries(line);
            if (header != null && !header.isTheExpectedHeader(line))
            {
                throw new IOException("malformed PEM data: found footer where header was expected");
            }
        }

        if (header == null)
        {
            if (!isFirst)
            {
                // just ignore the data
                return null;
            }
            throw new IOException("malformed PEM data: no header found");
        }
`

code 2：
` while (footer == null && (line = readLine(in)) != null)
        {
            footer = getBoundaries(line);
            if (footer != null)
            {
                if (!header.isTheExpectedFooter(line))
                {
                    throw new IOException("malformed PEM data: header/footer mismatch");
                }
            }
            else
            {
                pemBuf.append(line);
            }
        }
`
pass code 1 phase , inpustream can't read it again .  in code 2 phase , `!header.isTheExpectedFooter(line)--------- public boolean isTheExpectedFooter(String line)
        {
            return line.startsWith(_footer);
        }`
the code should be endsWith(_footer) ????

**Comment by dghgit** [comment]
I'm sorry but I have no idea what this is about.

**Comment by winfriedgerlach** [comment]
Closed question due to initial author not responding.
