### ISSUE TITLE
PKCS12 BER encoding

### ISSUE THREAD

**Issue by lgtti** [bcgit/bc-java#1276]
Hi, I have a problem with the PKCS12 generation using BouncyCastle.

With this code 
```
KeyStore store = KeyStore.getInstance("PKCS12", "BC");
store.load(null, null);
store.setKeyEntry(alias, keyPair.getPrivate(), null, new X509Certificate[]{certificate});
```

I generate a p12 from a private key and a certificate.

Using the 1.57 library version, the PKCS12 ASN.1 encoding uses DER format (we see that every sequence defines a static len):
30 82 0B 1C

Using the 1.70 library version, th same PKCS12 is encoded using the upper-level BER format:
30 80 ..... 00 00

This is a problem for some clients (for example, golang client doesn't supports BER encoding - pkcs12: error reading P12 data: asn1: syntax error: indefinite length found (not DER)). 
I haven't found any log of this change in the release notes.

Is this behavior correcty from you view? How can I force the DER encoding during the PKC12 generation?

**Comment by peterdettman** [comment]
You can use the `KeyStore.store `method taking a `LoadStoreParameter` argument and pass an `org.bouncycastle.jcajce.PKCS12StoreParameter` as the argument. You can specify `forDEREncoding` in the `PKCS12StoreParameter` constructor.

**Comment by lgtti** [comment]
Hi @peterdettman, it works. We have generated a new p12 file after the fix and the structure is DER compliant.

The next question is: how can i detect a change like this from the release note? Honestly, i have searched and i haven't found any mention to this update.
After this fix we will implement an integration test to check the DER compliance in the future but we need to identify this problems before going in production environment.

**Comment by dghgit** [comment]
The class was added early 2015. Sadly, specific mention is missing from the release notes - it used in the test classes though and the JavaDoc specifically mentions DER encoding. Apologies.
