### ISSUE TITLE
ArmoredOutputStream reports BouncyCastle version to be v1.72b04

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#1279]
This is not a big deal and probably an oversight, but I thought I better report it anyway.
This is using bcpg 172.1.

**Comment by dghgit** [comment]
Okay, this is ridiculous. Try https://www.bouncycastle.org/bcpg-jdk18on-1.72.2.zip and let me know how it goes.

**Comment by dghgit** [comment]
I've just pushed a 1.72.2 version to maven for jdk1.5tojdk1.8 and jdk1.8on. It includes #1268
