### ISSUE TITLE
Problem with CMAC

### ISSUE THREAD

**Issue by Steppenwolfe65** [bcgit/bc-java#128]
Your update method is flawed:
If len is equal to the cipher block size, the first block will not be processed, but is buffered and overwritten on the next block cycle. 
To verify this, step through the public void update(byte[] in, int inOff, int len) method, using an array that is a multiple of the ciphers block size (ex. 64 bytes), using the block size (16 bytes) as the len argument to the method. Remember that each block must be processed by the cipher to the mac code. With your method, the first block is copied, then when the next block is processed, it is immediately overwritten, without ever having been run through the cipher.

Here are my own routines (C#) for these methods, you should be able to extrapolate correct methods:

        public void BlockUpdate(byte[] Input, int InOffset, int Length)
        {
            if ((InOffset + Length) > Input.Length)
                throw new CryptoMacException("CMAC:BlockUpdate", "The Input buffer is too short!", new ArgumentOutOfRangeException());

            if (_wrkOffset == _blockSize)
            {
                _cipherMode.Transform(_wrkBuffer, 0, _msgCode, 0);
                _wrkOffset = 0;
            }

            int diff = _blockSize - _wrkOffset;
            if (Length > diff)
            {
                Buffer.BlockCopy(Input, InOffset, _wrkBuffer, _wrkOffset, diff);
                _cipherMode.Transform(_wrkBuffer, 0, _msgCode, 0);
                _wrkOffset = 0;
                Length -= diff;
                InOffset += diff;

                while (Length > _blockSize)
                {
                    _cipherMode.Transform(Input, InOffset, _msgCode, 0);
                    Length -= _blockSize;
                    InOffset += _blockSize;
                }
            }

            if (Length > 0)
            {
                Buffer.BlockCopy(Input, InOffset, _wrkBuffer, _wrkOffset, Length);
                _wrkOffset += Length;
            }
        }

        public int DoFinal(byte[] Output, int OutOffset)
        {
            if (Output.Length - OutOffset < _macSize)
                throw new CryptoMacException("CMAC:DoFinal", "The Output buffer is too short!", new ArgumentOutOfRangeException());

            if (_wrkOffset != _blockSize)
	        {
		        ISO7816 pad =  new ISO7816();
		        pad.AddPadding(_wrkBuffer, _wrkOffset);
                for (int i = 0; i < _msgCode.Length; i++)
                    _wrkBuffer[i] ^= _K2[i];
	        }
	        else
	        {
                for (int i = 0; i < _msgCode.Length; i++)
                    _wrkBuffer[i] ^= _K1[i];
	        }

	        _cipherMode.Transform(_wrkBuffer, 0, _msgCode, 0);
            Buffer.BlockCopy(_msgCode, 0, Output, OutOffset, _macSize);
	        Reset();

            return _macSize;
        }

**Comment by bcgit** [comment]
bufOff is not able to become more than the blockSize. When you say "if bufOff is a multiple of the blocksize" would you point out where that can happen?

**Comment by Steppenwolfe65** [comment]
You're right about offset, but I'm right about buffer..

**Comment by bcgit** [comment]
If the buffer is full, gapLen is zero.

**Comment by Steppenwolfe65** [comment]
If gaLen is zero it processes it yes, but before it processes the existing buffer, it overwrites with the new block.. 

if (len > gapLen)
        {
            System.arraycopy(in, inOff, buf, bufOff, gapLen);

**Comment by bcgit** [comment]
Exactly how many bytes do you think it will copy if gapLen is zero?

**Comment by Steppenwolfe65** [comment]
You got me.. not a bug after all (was throwing in my c++ version on memcpy, so I thought it was bug and rewrote it). Sorry for the trouble, you can delete the thread.

**Comment by bcgit** [comment]
No problem. It pays to be sure.
