### ISSUE TITLE
Could not find org.bouncycastle:bcprov-bcpg-jdk15to18-172.2:1.72.2

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#1281]
It appears there is a bug in the [POM file of bcpg-jdk15to18](https://central.sonatype.dev/artifact/org.bouncycastle/bcpg-jdk15to18/1.72.2):
```
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-bcpg-jdk15to18-172.2</artifactId>
      <version>1.72.2</version>
      <type>jar</type>
    </dependency>
```

Or is this a specialized artifact which is not yet available on maven central?

**Comment by vanitasvitae** [comment]
A dirty workaround:
```
dependencies {
    [...]
    implementation 'org.bouncycastle:bcpg-jdk15to18:1.72.2'
    modules {
        module('org.bouncycastle:bcprov-bcpg-jdk15to18-172.2') {
            replacedBy 'org.bouncycastle:bcprov-jdk15to18', 'Fix dependency'
        }
    }
    [...]
}
```

However, this workaround would need to be used in all consumer projects, which renders it useless for library projects.

**Comment by vanitasvitae** [comment]
Is this perhaps caused by a faulty `bc-build.user.properties` file?

**Comment by dghgit** [comment]
Okay, so for 15to18 there is now a bcpg 1.72.3. This is messing with my OCD a bit, but I'm too terrified to touch 18on... as it's correct.

**Comment by dghgit** [comment]
Thanks, closing as resolved. Every now and then you have one of those releases... I guess this one was ours.

**Comment by vanitasvitae** [comment]
Thanks for the quick fix! :)

**Comment by dghgit** [comment]
And thank you, for the quick report!
