### ISSUE TITLE
Question on MD5 hashing in FIPS mode

### ISSUE THREAD

**Issue by Bonn93** [bcgit/bc-java#1282]
Hello, 

I've got a SpringBoot / Java 11 application that I'm using to validate and test BouncyCastle as a the primary JCA/JCE in FIPS mode.  Our application starts up and seems to be working fine and the providers appears to be in the correct order. 

Output of `getProviders(Security.getProviders()` 
```
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider
security.provider.3=sun.security.provider.Sun
``` 

The java.security settings also have a few references like this

```
jdk.jar.disabledAlgorithms=MD2, MD5, RSA keySize < 1024, \
      DSA keySize < 1024
```

And Also set the JVM flat `-Dorg.bouncycastle.fips.approved_only=true`

To my understanding, and testing other runtimes like Node for example, is that MD5 hashing should fail and throw a no such algo type error. However, in a test endpoint we developed that allows the use of either SHA-256 or MD5, both are working, but we expect MD5 to fail. Throwing in some debug logs I can see that it seems to use `Cipher class path: org.bouncycastle.jcajce.provider.ProvSecureHash.MD5MessageDigest` and `BCFIPS: MessageDigest.MD5 -> org.bouncycastle.jcajce.provider.ProvSecureHash$MD5$Digest
` 

Why does MD5 still work, is extra configuration needed?

**Comment by dghgit** [comment]
See table 7 of the security policy, it's allowed for use with the JSSE. That said, only with the JSSE. Any other use in approved only mode is not allowed.

**Comment by Bonn93** [comment]
Does this refer to page 14 here? https://downloads.bouncycastle.org/fips-java/BC-FJA-SecurityPolicy-1.0.2.pdf 

So if the JSSE is included, MD5 will still work, but it doesn't have context if its part of a class or function that's doing TLS? 

Say this example program under springboot - we expect this to fail, but also need the JSSE to handle TLS in FIPS mode too, how can we achieve both or prevent the use of MD5 outside of JSSE use cases? 

```
String hashString(@RequestParam("cipher") Optional<String> cipher,
                      @RequestParam("input") Optional<String> plaintext) throws NoSuchAlgorithmException {
        log.debug("Received a hashing request.");
        Set<String> approvedCiphers = new HashSet<String>(Arrays.asList("MD5", "SHA-256"));
        String ciphertext;

        if (cipher.isEmpty() || plaintext.isEmpty()) {
            return "Please provide an input string to encrypt and a cipher to " +
                    "perform the encryption with via the input and cipher parameters respectively.";
        } else if (!approvedCiphers.contains(cipher.get())) {
            return "Cipher must be one of \"MD5\" or \"SHA-256\"";
        } else {
            ciphertext = getHash(cipher.get(), plaintext.get());
            return "Input Plaintext: " + plaintext.get() + "<br>" + cipher.get() + " Ciphertext: " + ciphertext;
        }
    }
    ```

**Comment by dghgit** [comment]
That's correct the MD5 implementation doesn't have any context, but it's available for TLS.

As far the Spring Boot app goes, you can't block MD5 automatically, you'll need to rely on telling your developers not to do it. If you want FIPS compliance the module can only be used in accordance with the security policy.

I guess the other thing I should add, which might help (or might not) it's not the use of MD5 outside of TLS that is the problem, it's the use of MD5 outside of TLS as a **cryptographic message digest** that's the problem. For example, say someone was using MD5 in a Bloom filter, that would be allowed, in that case it's just a hash function.

**Comment by Bonn93** [comment]
Okay, great. Thanks very much for the response @dghgit, I really appreciate it. :+1:
