### ISSUE TITLE
Exception in checksum verification swallowed by PGPPublicKeyRing in 1.72

### ISSUE THREAD

**Issue by eejbyfeldt** [bcgit/bc-java#1283]
After the following commit: https://github.com/bcgit/bc-java/commit/5d63b6fd84370d91cb5e3171c7401f66975e234e Checksums errors like the one produced in [ArmoredInputStream](https://github.com/bcgit/bc-java/blob/r1rv72/pg/src/main/java/org/bouncycastle/bcpg/ArmoredInputStream.java#L452) will just be swallowed and ignored while prior to 1.72 they would be forwarded to the client code. Is this an intentional change in 1.72 and the new behavior is the desired one?

**Comment by dghgit** [comment]
I'd say that was an unintended side effect - while I wouldn't put a lot of stock in an ascii checksum, I think we can do better than this, I've added a subclass of IOException which is handled differently when a parsing error related to armored input is found,
