### ISSUE TITLE
bcjmail-1.72 depends on the full Jakarta mail implementation instead of the API only

### ISSUE THREAD

**Issue by theit** [bcgit/bc-java#1286]
Hi,

I've just seen that the (Maven) dependency org.bouncycastle:bcjmail-jdk18on:1.72 depends on the full Jakarta Mail implementation:
```xml
<dependency>
    <groupId>com.sun.mail</groupId>
    <artifactId>jakarta.mail</artifactId>
    <version>[2.0,3.0)</version>
</dependency>
```
whereas the former releases 1.71 and 1.71.1 (correctly) only have a dependency to the mail API:
```xml
<dependency>
    <groupId>jakarta.mail</groupId>
    <artifactId>jakarta.mail-api</artifactId>
    <version>[2.0,3.0)</version>
</dependency>
 ```

Unfortunately I haven't seen in the repository where this comes from; otherwise I'd supplied a PR...

**Comment by robert-scheck** [comment]
I'm also interested in this, because `bcprov.jar` raises from 4.2 MB (1.71) to 9.0 MB (1.72) here.

**Comment by dghgit** [comment]
This was a result of a bug report - the jakarta.mail-api jar is really only around to be compiled against, for use the bcjmail API which is usually what happens if someone  is build an app with maven using bcjmail an app requires the actual jakarta.mail.jar. Or am I missing something?

**Comment by dghgit** [comment]
The argument from the other side was just as compelling, different of course. 

So this really sounds like dammed if you do, dammed if you don't. Does anyone else want to weight on this?

**Comment by theit** [comment]
I see your point, but I'd still suggest to revert to the dependency behavior as of 1.71, i.e. only use the API. If you need to have an *implementation* in your application code, you can use one of your choice, for example [Angus Mail](https://github.com/eclipse-ee4j/angus-mail), [Geronimo Javamail](https://github.com/apache/geronimo-javamail), the older one from [Jakarta Mail](https://github.com/jakartaee/mail-api), whatever.

Actually I'm having to use a dependency exclusion for com.sun.mail:jakarta.mail in our application because we use bcjmail but with a different mail API implementation...

**Comment by dghgit** [comment]
I've dropped the dependency, it seems to provide the "best solution".
