### ISSUE TITLE
Using custom DH groups

### ISSUE THREAD

**Issue by ottoka** [bcgit/bc-java#1297]
I recently noticed that bc-java can parse the _java.security_ property for custom DH groups (`jdk.tls.server.defaultDHEParameters`), but then does not use it in DHE-based TLS connections. The feature may be useful to anyone who needs to connect to legacy devices or in environments with prescribed DH parameters. I created a little patch for `ProvTlsServer` that fixes this, and will provide it as a PR (see #1298). Let me know what you think, and if you need me to change anything.

**Comment by peterdettman** [comment]
Resolved by #1298 .
