### ISSUE TITLE
Not consistent JavaAesEncoder.decrypt

### ISSUE THREAD

**Issue by Vivango** [bcgit/bc-java#1300]
When using this on a windows machine, I receive different characters than on a centos machine. Issues with characters having an umlaut.
              String decryptedText = JavaAesEncoder.decrypt(JavaAesEncoder.buildKey(args[1], Hex.decode(args[2])),
                            Base64.decode(args[3]), Hex.decode(args[4]));
                    System.out.println(decryptedText);

**Comment by dghgit** [comment]
Sorry, no idea what this is about, not our class, although it sounds like an 8 bit character encoder is used in the decrypt() method.
