### ISSUE TITLE
Versions of bctls-jdk15on 1.71 and 1.72 are not published to maven central

### ISSUE THREAD

**Issue by iiordanov** [bcgit/bc-java#1307]
Hi guys,

I pulled the repo and saw there are a couple of new tags

r1rv71
r1rv72

but no corresponding artifacts published to https://mvnrepository.com/artifact/org.bouncycastle/bctls-jdk15on.

Is this intentional? If not would you kindly build and publish those artifacts if possible?

Thank you!

**Comment by dghgit** [comment]
It's intentional - use either jdk18on or jdk15to18.
