### ISSUE TITLE
About sha256WithRSAEncryption signature analysis using old version of bc

### ISSUE THREAD

**Issue by y-k-m-r** [bcgit/bc-java#1308]
When using BC v1.71 to send a signed message using sha256WithRSAEncryption, if BC v1.37 is used for receiving, an error occurs in signature parsing.

Error Description
no such algorithm: SHA256with1.2.840.113549.1.1.11 for provider BC

The same problem does not occur with version 1.54 of the library used in sending signature messages.
It seems to occur with library version 1.55.
Please let me know which fix in the 1.55 release notes is causing this event.
I would also be glad to know the purpose of the modification.

**Comment by dghgit** [comment]
It'll be because 1.37 has errors in it.
