### ISSUE TITLE
AttributeTypeAndValue argument not supported by the CertificateRequestMessageBuilder

### ISSUE THREAD

**Issue by kuehne-trustable-de** [bcgit/bc-java#1311]
Although the CertReqMsg class supports the AttributeTypeAndValue array, it is missing in the CertificateRequestMessageBuilder.

The [PR 1310](https://github.com/bcgit/bc-java/pull/1310) adds the option to provide an 'AttributeTypeAndValue' array to the CertificateRequestMessageBuilder.

**Comment by dghgit** [comment]
PR 1310 now merged.
