### ISSUE TITLE
New Feature: Messaging Layer Security

### ISSUE THREAD

**Issue by bifurcation** [bcgit/bc-java#1317]
The IETF is close to finalizing a specification for [Messaging Layer Security](https://datatracker.ietf.org/doc/draft-ietf-mls-protocol/), an efficient and well-vetted group key management protocol, in particular for use in end-to-end encryption systems.  There is a small but growing [ecosystem of MLS implementations](https://github.com/mlswg/mls-implementations/blob/main/implementation_list.md).  Draft versions of MLS has been deployed in production for E2E encryption in [Webex](https://www.cisco.com/c/en/us/solutions/collateral/collaboration/white-paper-c11-744553.html) and [RingCentral](https://www.ringcentral.com/us/en/blog/ringcentral-update-e2ee-2022/).

As MLS expands into more environments that rely on Java and Kotlin, it would be helpful to have a widely available MLS library in those languages, for much the same reasons that motivate the TLS functionality in BouncyCastle.  The proposal here would be to add an `mls` module parallel to the `tls` module.

For context: I am the lead maintainer on the [Cisco C++ MLS implementation](https://github.com/cisco/mlspp), and would be glad to contribute to work on this issue.  But before doing that, I wanted to file an issue to get feedback on how folks would feel about including this functionality in BouncyCastle.

**Comment by dghgit** [comment]
Hi, sorry for the delay in getting back. Yes, we'd be happy to add this to Bouncy Castle. What did you have in mind? Thanks.

**Comment by bifurcation** [comment]
Great, glad to hear it!  In terms of what I have in mind: To first order, implementing the MLS specification, in terms of the message formats and cryptography.

The main question in my mind is the API, which is less clear cut than in the TLS case, since it's a group thing and not merely a socket abstraction (there's nothing like JSSE to look to for inspiration).  There are a couple of design patterns emerging if you look at some of the other existing implementations:

* A low-level API based on individual, immutable states of the group, as in [MLSpp](https://github.com/cisco/mlspp/blob/main/include/mls/state.h)
* A high-level API based on a mutable group state, as in [OpenMLS](https://openmls.tech/book/) and [MLSpp](https://github.com/cisco/mlspp/blob/main/include/mls/session.h)

I suspect that the right answer will be "both".  There are use cases for both; sometimes you want something easy to use, but sometimes you need more control.  And the obvious way to build the high-level one is to build using the low-level one, so it's mainly a question of whether the low-level one gets exposed.

In any case, feedback / guidance would be very welcome (in general, not just on the API). I'm new to BC and not all that fluent in Java idioms.  I have started some work in [a branch of a fork](https://github.com/bifurcation/bc-java/tree/mls), but that only has a few low-level things at the moment.

**Comment by bifurcation** [comment]
@dghgit @roy-basmacier Glad to see this merged!  When does your release schedule have this ending up in release BC?

**Comment by dghgit** [comment]
@bifurcation I've just uploaded a new beta of 1.79 to https://downloads.bouncycastle.org/betas that should contain these changes if you want to try them out now.
