### ISSUE TITLE
java.lang.classnotfoundexception: org.bouncycastle.asn1.eac.eacobjectidentifiers - Bouncy Castle 1.72

### ISSUE THREAD

**Issue by RealMasterZen** [bcgit/bc-java#1318]
Hi everyone, i would like to report a possible bug about the latest version of bouncy castle for java ( 1.72 )

When i try to use the library to send an email using TLS, adding the provider to the Security, it return an error about the following class not found: org.bouncycastle.asn1.eac.eacobjectidentifiers

I've seen that using 1.71 version it works fine, also with the version 1.66 works as well
I would like to know if there's something that i might miss or it's a possible bug of the latest version.
PS: i'm using jdk 1.7.0_67

Thanks!

**Comment by dghgit** [comment]
It sounds like bcutil is missing from the class path.

**Comment by RealMasterZen** [comment]
> It sounds like bcutil is missing from the class path.

I actually noticed that with the test with version 1.71 i was using the bcutil too... Instead for the tests with the 1.72, neither util and prov-ext has been used. I will make a test as soon as possible with the 1.72 USING bcutil !

Thanks for the tip !
