### ISSUE TITLE
Memory Leakage Noticed

### ISSUE THREAD

**Issue by Syed-SnapLogic** [bcgit/bc-java#1319]
Hi Folks,
   I have used the BouncyCastleProvider in my application to parse a private key.
  However, when I am running my application, I am getting memory leakage as follows:
    - The standalone maven-based java app is here: https://github.com/Syed-SnapLogic/SyedsPublicRepo/commit/b1806387b6b4dd722c4cda047a5331f1d0b2e954
    - The above application generates the heap dump before terminating, and save it in a temp folder.
    - When we open the heap dump using eclipse memory analyser tool, and browse the leak suspects, this is the top suspect.
    
![image](https://user-images.githubusercontent.com/5888194/212136852-f7758faa-0e3d-4fdc-b3be-90befb271519.png)

![image](https://user-images.githubusercontent.com/5888194/212136676-45c87e1d-819c-455a-b136-d1c3fc18f843.png)

  I am reachout out here to find out if there is a possibility of any bug in the bouncy castle library?  Or is there a config change that I can do in my app to avoid this leakage?  Any guidance would be appreciated.

**Comment by dghgit** [comment]
Nothing we are aware of, or is this one of those container situations where the app is being loaded and unloaded regularly?

**Comment by Syed-SnapLogic** [comment]
> Nothing we are aware of, or is this one of those container situations where the app is being loaded and unloaded regularly?

Yes, its loaded and unloaded.

**Comment by Syed-SnapLogic** [comment]
BTW, is BouncyCastleProvider thread-safe?  Can I just use one static final instance of it in the multiple parallel threads?

**Comment by dghgit** [comment]
Try what's on https://www.bouncycastle.org/betas 173b11 or later. Let me know how it goes. Thanks.

**Comment by dghgit** [comment]
Assumed dealt with.
