### ISSUE TITLE
Dilithium AES Implementation Mismatching KAT Values

### ISSUE THREAD

**Issue by chris-dunne-clarity** [bcgit/bc-java#1322]
I apologize in advance if this not where you are supposed to post issues for issues for betas of BouncyCastle (specifically lcrypto-jdk18on-173b11), but when running Dilithium2 using AES and the parameters provided in the first test in Dilithium's Round 3 Submission in dilithium/KAT/dilithium2-AES/PQCsignKAT_2544.rsp file, the secret message generated by BouncyCastle differs from the secret message provided in said KAT file.

The KAT file lists the secret message as:
A5B85669808946A65A6730A93585E7F9F5D95C7023B7843735EABECDBDB0EA70032FD9AC896B7D9B96F7A79FCBBFDF4ED3D8FDC7243ED915CEC36DB085C956CBD425A7D91FE19E0BBB58D3EAC4DAC69772E48FA1F49C2E4C5D27C243AA4AFB44B3ECF7FA4DF10F4B19752A01AD55529D8E8469988C43743586A321A31BEDDA2476FCDE6315095C4C14A7536C4A18501C5A9225C7BBAC5D4A90A9CAC24FB55E9E0306A9EC234605DE74AF88AFB661826981CBA46F92052592FAFCD5C09D8777D24EA7887F0CB6EA8D6020E24D176D98F17F4A63730E8167E1251A75C1C58A1B3C77905C99A481C918AA69C46BB4E18A5E4CB40B7DAFAB2D10537C144E3CE01755AA1E84035106709735FE7C113287AEE71DCEE1A3236CD9F33C5C75631D10B95D0C15A2F0460EB607545AD2B125E3FCFB96EB83F50FD0822257B1BEA507669DCA152B3B2640FE742A099F7BA81C21542789D716C02C25F47DAF69145682ADCB2A8D2C75DB546AED52FBCF5A2C6C4F70C77584ACDB14B186F8BE37C6F6F14C4A258DD54E542CDD440B26628F0BA9CBFEB5209263B2786EFCD6193A8432CBEAE7724842361A8A1FE397A170D9F245133F7C09AAD299816760F87A019877EFFD3A5716E599A9E936A530E1E5807E74DF2B38F95B91B62D7DB14B3E4652CC8A28E8BB40947AFB68818AED0B753B04E3BD1E2A3D48132D48BE014CA0B915684E10E95ADF32797D3CA6E68EA82465702180694A14EA86A61EFAC97E5F03B59FB38A19AD5ACA5DD9A4AC2D95B878FC791EBEBA968F0B6CEC8047B314814604AA5D7E5D0905364F127ED931013589DA7539C4B87F9E07E70C02E75D0C698F4ED6DBE01221A9999DBD6D03C50BB15DEA83D643F5AED09C737CD2668B6F96080529A65EF86291654E0A21A25075FF65AC88C559902C11401730DBED3F6711185AC22EE703B9553BBA2A9571EF23001763FAD1A3C9DA008A5043987BD0CC7E06D87898503225C2CF98E56A24DD9BFFDECA19F90A7F17B67ACA02F68D62CC371DA6AC160F4F9F72F2F84502C1352609F3868CA039993273291C8E7304988DD74CF9A12226B0B5C3447DDF922D6BAE4AD79BD876A1C3F24E509222E624677D44FEC0ECEA854CE9E120D26A0EF0337DED2F955DE8AF3B493132F3C0F3D420C8CBD7ECA8E9E581EF1D4F6A15A31912D9D357FACB602B121EC9DB6FF3FE01049612928CBABA0DFC9F2195418994065C52FEF4F4D74AD8A08E14B76C0B14033F0AE884B2EC71F30FFEFD70372ECABBD02638B180AA233FBE982E36747AF47771886FAAA135063FCFFBBABBCC729E59465651DD1737E03212A907E109854D18B57D5B00EBD6C267C98DD2B3CBFA3469A06F86128A7219AB28341E4F731DC4A93706F4474FC81869F43FD9392E6029D1AF9DE62E810B2B4B29CD41A388B7B4F853DE373AD4B21CF2FD2B72B9F83191DB9C9BAEBF5F5869E5FD2DEE1F5980150FB6F28E9148F3147BE7FA9A08C5D804FA168B090386CA93F17140D0D82940E55DC2DE89B946003EE5807B0EFD0AB434EEE71C4379977ACCB0EC92BDA9CA288C8F9A26B75C046FEDB9C4573B38783ED2875383C46E1ABDD4230FFCE09AF8F567118EDE73F0DC13E283EBF30E68B836E8ACD8E002C4A169AB4CE16AC3F8D5CE192E2375CA761191AE79FC570E484C2F51F38919A406D5C3E5D26E91623508162100AA2BA73F609DD04A4DE731FDE38AB696D25B291AF007C5A435D8260C11BADF27D2004410371128A9C2A14E86E54726CBCE6241CFD8F1EDC6E0212DA1CCB6374BD1B410344C47D8A463E2DA428854E773F313C95715F6BFC52C0B2BC6A605B78C956622A113891405DEE9837AD369787038FD6F778628048D0EC0F68EADBA1E2A55755E511028E3001BB69CAD48F88FA9C7C8E1B419E10BDF37067EE6A7F0844802531013269A7255D03163B56E500DA8AA15DC64BF5FAC9BF24C5AC6220A3E72F59C6641F79D6FAA98DAB02E990A52984389726E3BA13D3A0A51A9341DA4870331CDD68C9E6424CFFCCEE30DCA1FBE8900EAAC654C89E003EB05E8E303D79481EEC128A0E2BF78C1F96E1083E4F1BDB104E5687A43732B5484131E4AAC486AE9CEDF7A504EC83533F5E1BD08B48F406BDD674AEC316ACC59AEC93A866DCE0FCA271C7C2CD033E14B96FD3D4FAF6E391EAF8B58149159E009AD11C4620D8D285CCE3F5D8FE082610302534C42D7D37EA72E383B279FFF0FA150F726668DDCE4012981D27826BB30A073647CFD86B18F1DB283F6E3303BCDE0A86AF841506A5C92F24676CC855A64220385FE03A3BA02D48D61A7E8597E5D2222F6E8D96FF02F48368D99E82C2CA143A7974605FE2EBFC8A572424CC9A897572CFF6680701EC7FA5729B3E51D6C864A3E748DD3365573816487ACF1FE4526B0049ABF967597C008127D0CB79D28B6BE92B8262A17DF6CF0236FF0CA48F103904E7A877BC767274A6E5ACDC44E4C81BBB34776254D4D3BE99CB9E2F5FF6D9CFA0A66DA576E610F396BE4177F40410D69B7E615C342410FCDCBCEC1BAD0A39FB6594391B4BDCB9FEC2C89AD6E4AC95C99CAC94E26F3247C1AE39DF4C9DFBF19EB383890238C2876CC63095C2C3C65A9A31396CBF95921A675F9253D46621456D1C3CA240A0E0BCEF697AE8C8EB1966DAA622A211CAFD322AA550DA8DEB04F7E0F6D4B537F09EC0E5B6D33CC30F029A8BE829DD5082A19ED531108EB801EEA433AF91BD52965778BBF2B87957C4A3662A4D4450445A5A44363D6D227EF706F302BD8C5EB6C7294732345ED3DE8A35D619D7923444573620CA62BF4B33A4A025E5AACC86DD9215E42A51B6CF6E529FEA772ECB41AE4DC197A3C7D0E5A3A50B8F2629EC9255A69E3B34467934BB20BB44F6DFA697B055A9AA5BAE93C745851D9F61D0DCD2873D593DBE7EDE1385154CA6D499F90A030DDD475FCBBC718A3D067930F874C5E203EA0D0F159110C4EA7A1A0C091616F7819940B37B51AB9BE3C99486F36D9B9279172DF18C2274BA613424D93E9DBC659D96C4022F9BCF9D703F6D6A8BA34193C0B542A194ECB2C7C52188FA122CD37A3C1C9D1860EF850D358F7B3538B264B55617F1CCA9F0E334CBB20164DD52032D6F613334AFA3ABE89A2646B3F037DCC36ED117F27B3096C6FCE81E8C7E6AB0CE1959D52FFB1957DD64AC10D541F82DAE4EDBD173320806D1D4CE4EE65C512DE3C36ECA5EA692B31197F220AB2A94ABEFCDF5EFD20A5ABB165177772D7AC609F998DFEA9DE7D09272D140A980580E69C1415C99AE2167B31BE5489C7CFCDAD121E2B4647607F909A9B9EA6AEE5FD03131C1E1F333A414C5F6669A5A9B3B6DCDDEBF4011314303B4E52797B909598C2CBE6F7131726383E486E787982A8AAC4C9D5D8EFF0F6000000000000000000000F233346D81C4D8D734FCBFBEADE3D3F8A039FAA2A2C9957E835AD55B22E75BF57BB556AC8

Whereas BouncyCastle generates:
AF5920774603D20E98A79AA3ABFA32B6E22519E673E37AC4AC73FE85341E2C2923C1992E1B0BBE3873D7C8FC5662F207BF58EA381CD4A3A0C062DEC45BDAF8BA0AA52BEF6FA14F3F6CF28F7620BF94A92CC27D045414A64D65C014963052802428BF3987A2D47516CA5C78AAB96B7BE11BCA5F2C5A26F3FCE3A26E8E09A2738F386F75D448F937EF19A846BD4DD949CAAF36DB5629884AF53A023E3F180FE4C0FAFF7BE5DFE4E89ADE3095A65600421461AD08C129D6CEA851BB39C0D7A7D151405689A091FA4DEBAC373CF54AE078F0AF7557BBC6F06A535AE8949E0C65308A59840072375295802D0E2CE9A3DA98426A00FF03FE80218C0EEC8EFE581CB9CC9A7D66B20645A8CD0490D3CE4F7E6FEAE9C9EB7A57F964D0EBC7C90B7A9F86300B3E8095E64D1294CFC4B4D9E272E8FA8DB5707D7004AF22DBFF9CFD4863DF573FE004341DA3CD4A3082532C2620455FA37C562BAFD5684EA128AFC79E01FC9B31E8433BAD7C029F2F13CC10592D2332E3E08B80D350463DE72750B1F806F493E143BD5FCA7D1698081B31BF876B2A1BC9DF50952D13B6C1321B1111172145A627AE0B4427B98975CBFFF7D68275754B45B682D709E168522E84FEA7DD3BB0F41505FF71926431D1A90D4CBF9A527AD4E284976FFF8BD9D6224A4F260391A987FB6DA6EE42C2A4900F407CE1F02E322475D313FBEBB68C2E05730809448A7428A5940139EBDF1B5556FCC5D42E1A13F32230CB6F0724831D0D071BBA5A6704806F475B74BA91B6E385D48620958D0AB1BF2B184E10F3E753B71337BE9EB653786785B43AC7E5C494AC1BCB043D461425B36098AC93055A0105AB8523B61D024A6E9B56A42D3C04726512AE4CFE05710446B06F694234EE4FA8FEEDDDC5F28A65EDE2EB58E965FE3627A571BC45B397ED092AB4BE00041729C4D192FE30678279D223A848CF4366E92B3F68DEE97C9B4A7FF22F937BE6C56639961DB29FA3CFECFFF293140886FFB92EBC79DAB59CEAF869C64F8EAF585CE97DD6B78F892772DB88A958CF0AB557A7FAA83FE621477E2B84497AB5A8ECF4A7BD32DFB902F05D2CA31047D0F1919ADDE1EE6DFD58E59BC4DAB3CCBBA36AAAF6AFCCC7B095CA94A195BE9A289526B588C3A9C56876FC415D521D442BAC0298D302419AD527DA249C2A660CD064213FFAD563183F37972578EEB9F70AC67AEE6CC2B71F283A95930B554738555791C25E7A399E685636D58D69CB6BE793B45C1969E7D5615627EBC32EED45440F87880D2829FA4FC871866164D259ED95D2731871017FF51894066FAE1FFA6F4B4A6F84FCFFDA09E718FA17135EDB3F48558D5BA67F9E6F0900340BD04DFE59B7BD67745884FB84AE3F8EE763D202743652D4F7333450580490B9C744935B19C1D5FB0DB5FBB461411362838037EB7EC3F63F26C893E7CC1C3B3F4767ABAE00FEB7BB99B1420BB29EA614747896D9EDCF8107FE504C9C308A8264DACE318D87CFE4761803E9A60DEFA6144AABC1F10A45B140DED754E73586C467BB7BF19EDEF25BE0C65E93C5E5EB8F880CCE4A858757F8FF56062B1067F4106F76B7007F6EA6F945047E85BD0FAD9D26994F678A0612B87CCF9C0CF9A433D889C96E4C12BE372277005B06AD127105D16D8FB142AEAE5373ABD61D9ADCFC5550D623CA3B8824B0E2E08C2BF4E2841EAC4C5DC56CF8954CF207C263F27C9F309F10307C0D84A65878425031375DD810D2D7E51098A3814350795C4A077FA40DD44F0FA7510F7C3F631407CF34F604C7B335632A20D2AD419BD7CC6D4242B1C66C35E5A5EDCCB13CA37D3B50465F3B4AAFF7E3161E7936088AE08401FD2C37D67A2FF91D3E6F08686D64BC2FC6C57106E49FA384AC22219F07EE8996CA3DFF59DCC5092A4BADBE87AEDE7F69A04C79B33BDF35D4A0E4CB4B55019CB0BF275295B93BDABEA516CA2B616A56918600B724BE7A01EC4EF54312B30D66F507815F2780FFEE7C30F8425A92252CE550FAB4E902E7B382D46DBD20EFE1BB0EF8A496873C09C4CEB0303C7F1DABA0102DE94190B6AC6DC810F72BCA3AA292FF38BD51A7FAB8509EC4FBE0EAA3C986166A674B7871155C348C477EF8CEDC832B5ABEE71A8D18D06DD0F5221160ABEB71E6E82CFABF731EA3515A76EF07B2C16C63B37F7AB73B67F005929A753E453B930C0AF432277FD77D8A1EB8022CDE9665763B014F0A672A04160B0A06F5540F4C264B7F22740690A2352DC863B588303AD51F0AE162BF79797F07B534501CBBFDB713A724AA98E19532187180CCFADC6EBE3142FA7DB66CD4DE7B9FBD4C8235686DB68CAF489AFA4E1E87AEF0CEFD8037E3A578EE62EB7F94ED5BC0B58EEA4B4C45FC56D31D29944D095AC96C29083DA2C77181D97A55FE6E903A2F2783DE0BAA5F47D704785C33E8D5C87ED61E65459167310EB7A99574EF819AE9161A3BD09634803D9E1E4EC7386D7946984517213AB9CF66AEA551CC457C39F86AF294CF7B073F563ED4DAB9419BDF004BD05C92B4E80EC3CFEAC97E1DDA554FDA625C4B9B039BAA7C5A2F6F97057792483CF5F852D4C3AC71AD50F779953DCFE2F63ED235D8E1D5345D6C6DF0555CC2631DEAD9B714BC4C16501E01261381F3679715345123388C852D57DCF1941D0911D49FEA7143FD2FC343A5075B64CCA48291DC28B83F76074589EAB217C7847840652C0E3AE278B3B6FB0D800C5E7DB79D5CB9CC1A87450C00B7677812D22EE20FDE8C1753A7FB93BA8BBB8595A6393DF54AA9CDB6E0879A26E49BD3B01513C6053A0746C8596CE5E5B225CFCA26AB8BF12F1FE0A647A9E4453039A1226194C46E8B98ACD710F18FB7EC05476C1CD8FC3112CCDDB1582B8817C18FE315353E7A47C821E9EE3A43CADE1B80D92A0AE8DCEB4DFF766A54DF3665FEFE3C252B72DAD7B1E3359E7FA25562C3E39DB521CE1874111FB090DBD38B3180AD034B57B031DC4DD6AF7C1A8AF3F6CE7EDB1A9E4B6D4A5920E3620818820659762EF7A4243F51DF2D8A900737D58105699B4E10CBCB359C7F3A4007697C482050EC33CF8041916A3B919A50D96EF0F589FD4556F30DBDD942EAB79DFA97C07E30247074352E1BF98E349CC7EFA5A1B8FCE4F18F1FAF6F07C99C321448B0395C8A9CBC466412F89C1A98BF5715842844F0E8236FA4696C4658B8FDE4425D09D67A38AC7258E5D5966F2D3FF66A0C0CE76E7F6B81A1BCD047FD3A205BF0CCAEA3B11079909C6CE5698F32E1F3409658FFA01EAECB4AE2B092B78989DAAD6623BB11F49F0F8F8699EC05661502FFCAD03CF415191A222D3C4C7B8AB0B5B9BBC2D9DCEFF7202D3F4244494F525364666974C4D9E6F5FA0001041927373D5A7680B8C1C9FE2029383B3C484D565F65799D9EA6A9ADD2DEE5E7F7F9000000000000000012243248

**Comment by dghgit** [comment]
Hmmm. Where did the submission come from? The test vector printed for BC is from PQCsignKAT_Dilithium2.rsp, not the AES variant. I'd also point out that BC generates detached signatures so the signature is not concatenated with the original message.

**Comment by dghgit** [comment]
Closed as appears to be a misunderstanding of the test vectors.
