### ISSUE TITLE
SunJSSE Compatibility Issues - Endpoint Identification

### ISSUE THREAD

**Issue by jliu1970** [bcgit/bc-java#1331]
https://downloads.bouncycastle.org/fips-java/BC-FJA-%28D%29TLSUserGuide-1.0.12.pdf document recommended two options:

1. Set the system property “jdk.tls.trustNameService” to “true”.  When we tried this option in a java 8 service, the handshake still fails with exception org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40). Any other changes that may be needed for this to work?

2. The second (and recommended) alternative is to set a customized SSLSocketFactory on the
HttpsURLConnection, is there an example of how to do this in HttpClient?

Thanks

**Comment by jliu1970** [comment]
By the way, we also tried the option:
“org.bouncycastle.jsse.client.assumeOriginalHostName” is an alternative system property to
“jdk.tls.trustNameService” that will only affect BCJSSE. The caveats above still apply
in https://downloads.bouncycastle.org/fips-java/BC-FJA-%28D%29TLSUserGuide-1.0.13.pdf and got the same exception org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40).

**Comment by peterdettman** [comment]
1. The preferred property these days is "org.bouncycastle.jsse.client.assumeOriginalHostName" since it will only affect BCJSSE. handshake_failure alert can happen for any reasons; please give the stack trace.
2. We provide a utility class org.bouncycastle.jsse.util.URLConnectionUtil that you can use to invoke URL.openConnection and automatically apply an org.bouncycastle.jsse.util.SNISocketFactory to fix up the SNI configuration.

**Comment by jliu1970** [comment]
@peterdettman Thanks, Peter, I will grab the stack trace and post it here. I will also try out URLConnectionUtil

**Comment by jliu1970** [comment]
Here is the stack trace with option 1: 
{"@timestamp":"2023-02-10T21:28:50.195Z","log.level": "INFO","message":"Client raised fatal(2) certificate_unknown(46) alert: Failed to read record", "ecs.version": "1.2.0","service.name":"unit-management-service","event.dataset":"unit-management-service","process.thread.name":"Thread-88","log.logger":"org.bouncycastle.jsse.provider.ProvTlsClient","hostName":"CYL019-ZBK15G5","msg":"Client raised fatal(2) certificate_unknown(46) alert: Failed to read record","log":{"origin":{"file":{"name":"ProvTlsClient.java","line":422},"function":"notifyAlertRaised"}},"error.type":"org.bouncycastle.tls.TlsFatalAlert","error.message":"certificate_unknown(46)","error.stack_trace":"org.bouncycastle.tls.TlsFatalAlert: certificate_unknown(46)\r\n\tat org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(ProvSSLSocketDirect.java:135)\r\n\tat org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(ProvTlsClient.java:348)\r\n\tat org.bouncycastle.tls.TlsUtils.processServerCertificate(TlsUtils.java:4642)\r\n\tat org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(TlsClientProtocol.java:790)\r\n\tat org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(TlsClientProtocol.java:676)\r\n\tat org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:635)\r\n\tat org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:524)\r\n\tat org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:245)\r\n\tat org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:783)\r\n\tat org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:371)\r\n\tat org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:86)\r\n\tat org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:445)\r\n\tat org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:426)\r\n\tat sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)\r\n\tat sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)\r\n\tat sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)\r\n\tat org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76)\r\n\tat org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)\r\n\tat org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)\r\n\tat org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:782)\r\n\tat org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)\r\n\tat org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:474)\r\n\tat com.msi.location.oauth.OAuthTokenHandler.refreshOAuthToken(OAuthTokenHandler.java:114)\r\n\tat com.msi.location.oauth.OAuthTokenHandler.getOAuthToken(OAuthTokenHandler.java:98)\r\n\tat com.msi.location.unitmanagementservice.services.dataretrieval.DataRetriever.getDataFromProvisioningService(DataRetriever.java:98)\r\n\tat com.msi.location.unitmanagementservice.services.dataretrieval.DataRetriever.retrieveData(DataRetriever.java:66)\r\n\tat com.msi.location.unitmanagementservice.services.ProvisionedDataDownloader.retrieveAllProvisionedData(ProvisionedDataDownloader.java:200)\r\n\tat com.msi.location.unitmanagementservice.services.ProvisionedDataDownloader.syncCache(ProvisionedDataDownloader.java:152)\r\n\tat com.msi.location.unitmanagementservice.UnitManagementServiceApplication.lambda$run$0(UnitManagementServiceApplication.java:87)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\nCaused by: java.security.cert.CertificateException: No subject alternative name found matching domain name idm.pi.commandcentral.com\r\n\tat org.bouncycastle.jsse.provider.HostnameUtil.checkHostname(HostnameUtil.java:97)\r\n\tat org.bouncycastle.jsse.provider.ProvX509TrustManager.checkEndpointID(ProvX509TrustManager.java:325)\r\n\tat org.bouncycastle.jsse.provider.ProvX509TrustManager.checkEndpointID(ProvX509TrustManager.java:444)\r\n\tat org.bouncycastle.jsse.provider.ProvX509TrustManager.checkExtendedTrust(ProvX509TrustManager.java:353)\r\n\tat org.bouncycastle.jsse.provider.ProvX509TrustManager.checkTrusted(ProvX509TrustManager.java:274)\r\n\tat org.bouncycastle.jsse.provider.ProvX509TrustManager.checkServerTrusted(ProvX509TrustManager.java:181)\r\n\tat org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(ProvSSLSocketDirect.java:131)\r\n\t... 29 more\r\n"}

**Comment by jliu1970** [comment]
Here is the stack trace for option 1: 
{"@timestamp":"2023-02-10T21:28:50.195Z","log.level": "INFO","message":"Client raised fatal(2) certificate_unknown(46) alert: Failed to read record", "ecs.version": "1.2.0","process.thread.name":"Thread-88","log.logger":"org.bouncycastle.jsse.provider.ProvTlsClient","msg":"Client raised fatal(2) certificate_unknown(46) alert: Failed to read record","log":{"origin":{"file":{"name":"ProvTlsClient.java","line":422},"function":"notifyAlertRaised"}},"error.type":"org.bouncycastle.tls.TlsFatalAlert","error.message":"certificate_unknown(46)","error.stack_trace":"org.bouncycastle.tls.TlsFatalAlert: certificate_unknown(46)\r\n\tat org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(ProvSSLSocketDirect.java:135)\r\n\tat org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(ProvTlsClient.java:348)\r\n\tat org.bouncycastle.tls.TlsUtils.processServerCertificate(TlsUtils.java:4642)\r\n\tat org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(TlsClientProtocol.java:790)\r\n\tat org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(TlsClientProtocol.java:676)\r\n\tat org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:635)\r\n\tat org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:524)\r\n\tat org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:245)\r\n\tat org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:783)\r\n\tat org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:371)\r\n\tat org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:86)\r\n\tat org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:445)\r\n\tat org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:426)\r\n\tat sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)\r\n\tat sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)\r\n\tat sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)\r\n\tat org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76)\r\n\tat org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)\r\n\tat org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)\r\n\tat org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:782)\r\n\tat org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)\r\n\tat org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:474)\r\n\tat com.msi.location.oauth.OAuthTokenHandler.refreshOAuthToken(OAuthTokenHandler.java:114)\r\n\tat com.msi.location.oauth.OAuthTokenHandler.getOAuthToken(OAuthTokenHandler.java:98)\r\n\tat com.msi.location.unitmanagementservice.services.dataretrieval.DataRetriever.getDataFromProvisioningService(DataRetriever.java:98)\r\n\tat com.msi.location.unitmanagementservice.services.dataretrieval.DataRetriever.retrieveData(DataRetriever.java:66)\r\n\tat com.msi.location.unitmanagementservice.services.ProvisionedDataDownloader.retrieveAllProvisionedData(ProvisionedDataDownloader.java:200)\r\n\tat com.msi.location.unitmanagementservice.services.ProvisionedDataDownloader.syncCache(ProvisionedDataDownloader.java:152)\r\n\tat com.msi.location.unitmanagementservice.UnitManagementServiceApplication.lambda$run$0(UnitManagementServiceApplication.java:87)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\nCaused by: java.security.cert.CertificateException: No subject alternative name found matching domain name idm.pi.commandcentral.com\r\n\tat org.bouncycastle.jsse.provider.HostnameUtil.checkHostname(HostnameUtil.java:97)\r\n\tat org.bouncycastle.jsse.provider.ProvX509TrustManager.checkEndpointID(ProvX509TrustManager.java:325)\r\n\tat org.bouncycastle.jsse.provider.ProvX509TrustManager.checkEndpointID(ProvX509TrustManager.java:444)\r\n\tat org.bouncycastle.jsse.provider.ProvX509TrustManager.checkExtendedTrust(ProvX509TrustManager.java:353)\r\n\tat org.bouncycastle.jsse.provider.ProvX509TrustManager.checkTrusted(ProvX509TrustManager.java:274)\r\n\tat org.bouncycastle.jsse.provider.ProvX509TrustManager.checkServerTrusted(ProvX509TrustManager.java:181)\r\n\tat org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(ProvSSLSocketDirect.java:131)\r\n\t... 29 more\r\n"}

**Comment by peterdettman** [comment]
So you are connecting to "idm.pi.commandcentral.com" and then the hostname verification cannot match that against the server certificate's name(s). Since the name is present (and not just an IP), then this issue is not about the SNI workarounds (that part is working), it's about why your client doesn't trust the server certificate.

Are you able to dump the server certificate somehow so we can check what names it thinks it's for?

Also, are you sure you are connecting to the right hostname (not just the right machine, but at the appropriate named endpoint)?

**Comment by winfriedgerlach** [comment]
@jliu1970 have you resolved your issue? Can this question be closed?

**Comment by peterdettman** [comment]
Closing as obsolete.

Note that the current preferred endpoint ID fix is based on `org.bouncycastle.jsse.util.SetHostSocketFactory`, which `org.bouncycastle.jsse.util.URLConnectionUtil` now uses internally also.
