### ISSUE TITLE
Expired PGP key when checked in , giving validity of 136 years

### ISSUE THREAD

**Issue by 4devwithgit** [bcgit/bc-java#1336]
We are using following BC jars,

bcmail-jdk15on-168.jar
bcpg-jdk15on-168.jar
bcpkix-jdk15on-168.jar
bcprov-ext-jdk15on-168.jar
bcprov-jdk15on-168.jar

We have created keys with 1 day validity and then once its expired we happened to update the key usage of that key.
Now, if we checkout the public key from this master key and checkin in another system, it holds the validity of 49708 days, ie year 2159.
But if they expired PGP secret key is not updated in any way, and then its checked out from there as public key, and subsequently we checkin that key in another system, it shows the right expiry dates.

When we are doing a checkin of the key in our implementation, we are using below call,
**pgpPublicKey.getValidSeconds()** 

So, need help here to understand whats going wrong with the updated key.

**Comment by 4devwithgit** [comment]
Do you have any feedback on this? Thanks

**Comment by dghgit** [comment]
My guess would be the update to KeyUsage is updating the KeyExpireTime or more likely, removing it, meaning the key has no expiry time.

**Comment by dghgit** [comment]
Appears to have been resolved.

**Comment by dghgit** [comment]
I was assuming the problem was in how the code was using the library. Given the lack of response why would I think otherwise? Have  you checked what is happening when key usage is updated.

**Comment by 4devwithgit** [comment]
So, we had confusion here, :) but thats allright.

For the PGP KeyUsage and KeyExpireTime, we rely on the BC API calls. Thats there the controls goes from our code to BC, and we didnt had control on that. Another thing to be noed is that this happens only for the expired keys, not for the non-expired keys.
So, we will try to use the latest BC jars 1.72 or 1.73 and see if at it changes this behavior.
Thanks
Dev

**Comment by dghgit** [comment]
Just keep in mind that changing a signature sub-packet requires replacing the entire subpacket vector - if you don't preserve the original ones those values are lost.
