### ISSUE TITLE
ConcurrentLinkedDeque used by in jdk15 version of bcprov

### ISSUE THREAD

**Issue by sampov2** [bcgit/bc-java#1338]
bcprov-jdk15to18 version 1.72 uses java.util.concurrent.ConcurrentLinkedDeque, which is only available in JDK 1.7 onwards and thus breaks compatibility with older JDKs

**Comment by dghgit** [comment]
I think this is now fixed. Sorry.

**Comment by dghgit** [comment]
Definitely fixed now. 1.73 now published.
