### ISSUE TITLE
Missing 1.72.2 tag

### ISSUE THREAD

**Issue by dbkreling** [bcgit/bc-java#1342]
Hi, @peterdettman / @dghgit  We need to build 1.72.2 from source, and we are missing a tag for that.

I can see some discussion started [here](https://github.com/bcgit/bc-java/issues/1305), but no conclusion yet.

Would it be possible to tag version 1.72.2, please?

Thanks!

**Comment by dghgit** [comment]
There's now a tag [r1rv72v2](https://github.com/bcgit/bc-java/releases/tag/r1rv72v2) which has the PGP updates in it.

Let me know how you go with it.

**Comment by dbkreling** [comment]
The build worked just fine from the tag. Thank you, @dghgit
