### ISSUE TITLE
With SDK 8.0.7.20, BouncyCastle API X509v3CertificateBuilder.build  throws IllegalArgumentException while generating certificate with long subject name.

### ISSUE THREAD

**Issue by monishaSriNokExt** [bcgit/bc-java#1348]
My application for generating certificates works fine with IBM SDK 8.0.7.11.

Although, with IBM SDK 8.0.7.20, I am seeing below failure in certificate generation where subject name is too long:
javax.ejb.TransactionRolledbackLocalException:  ; nested exception is: java.lang.IllegalArgumentException: cannot produce certificate signature
              at org.bouncycastle.cert.X509v3CertificateBuilder.build(Unknown Source)
 
Some examples of subject names with which I am seeing failure:
example1: uid=testuser1234,ou=people,ou=accounts,dc=dcxx,dc=test12,dc=net,dc=in
example2: uid=testuser1234,ou=people,ou=accounts,dc=dcxx,dc=1234567891234567891234
example3: uid=testuser1234,ou=people,ou=accounts,dc=dcxx,dc=LengthyDomainNameInSub
example4: uid=testuser1234,ou=people,ou=accounts,dc=dcxx,dc=LenghtDom,dc=SubName 
example5: uid=testuser1234,ou=people,ou=accounts,dc=dcxx,dc=1234567891234567891234

Some observations:
1. With 3 dc attributes, problem is observed if total length of subject is more than 58 characters.
2. With 2 dc attributes, problem is observed if total length of subject is more than 71 characters.

Is this issue observed by anyone? If yes, is there any resolution? Kindly suggest.

**Comment by timw** [comment]
The root exception is unfortunately being eaten [here](https://github.com/bcgit/bc-java/blob/master/pkix/src/main/java/org/bouncycastle/cert/X509v3CertificateBuilder.java#L385).

From a quick look, the only obvious path for this failure is a something going wrong either during the ASN.1 encoding (unlikely if it works on one SDK version and not the other) or a failure during a Signature update (which sounds more like something that would break between versions of the SDK).

I'd suggest debugging with a breakpoint where that `IOException` is caught and inspecting the stack trace for it - I suspect it will come from one of the `write` methods in `SignatureUpdatingOutputStream`.

**Comment by dghgit** [comment]
Can't say we've ever heard this one before. I'd be fascinated to know what's causing it. 

I've fixed the exception throwing to nest the IOException as well now. You can find a version of bcpkix which will do this at https://www.bouncycastle.org/betas you want 173b21 or later. Hopefully you will get a better stacktrace out of it, let us know.

**Comment by monishaSriNokExt** [comment]
Hello,
I picked the 172b21 jars and tried again, but without much luck. I mean, the IOException did not tell anything new.

javax.ejb.TransactionRolledbackLocalException:  ; nested exception is: java.lang.IllegalArgumentException: cannot produce certificate signature
        at org.bouncycastle.cert.X509v3CertificateBuilder.build(Unknown Source)

Thanks

**Comment by dghgit** [comment]
There should be an exception under that which will give the IOException details now. Can you get a full stack trace?

**Comment by monishaSriNokExt** [comment]
Unfortunately the whole stack trace is not printing. I am using IBM java.

**Comment by dghgit** [comment]
If you can replicate this in a small program you should be able to call getCause() on the underlying exception and see what the IOException is returning.

**Comment by monishaSriNokExt** [comment]
Here is the IOException:


java.io.IOException: Failure in engineUpdate
        at org.bouncycastle.jcajce.io.SignatureUpdatingOutputStream.write(SignatureUpdatingOutputStream.java:27)
        at org.bouncycastle.asn1.ASN1OutputStream.write(ASN1OutputStream.java:118)
        at org.bouncycastle.asn1.ASN1OutputStream.writeDL(ASN1OutputStream.java:107)
        at org.bouncycastle.asn1.DERSequence.encode(DERSequence.java:101)
        at org.bouncycastle.asn1.DERSequence.encode(DERSequence.java:126)
        at org.bouncycastle.asn1.DEROutputStream.writePrimitive(DEROutputStream.java:33)
        at org.bouncycastle.asn1.ASN1Primitive.encodeTo(ASN1Primitive.java:26)
        at org.bouncycastle.asn1.ASN1Object.encodeTo(ASN1Object.java:22)
        at org.bouncycastle.cert.X509v3CertificateBuilder.generateSig(X509v3CertificateBuilder.java:436)
        at org.bouncycastle.cert.X509v3CertificateBuilder.build(X509v3CertificateBuilder.java:382)

**Comment by dghgit** [comment]
That's interesting. It's the underlying signature class that's failing. I don't think it's using the BC provider though - is there a setProvider("BC") on the ContentSigner - what may have happened is the IBM provider has added an algorithm that was previously only supported by BC so the wrong Signature instance is being returned.
