### ISSUE TITLE
Possible error at example method

### ISSUE THREAD

**Issue by polyakoff** [bcgit/bc-java#135]
Trying ty compile  method `readSecretKey` from [this](https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/examples/PGPExampleUtil.java) example class I get the following error:
`Error: java: incompatible types: java.io.InputStream cannot be converted to java.lang.String`
that relates to this line of code:
`PGPSecretKey secKey = readSecretKey(keyIn);`
I'm using this bouncy castle version `org.bouncycastle:bcpg-jdk14:1.50`
Is it possible there is a mistake in the code?

**Comment by bcgit** [comment]
No. It might be that you need to use the latest version of the PGP library though. 1.50 is over 2 years old.
