### ISSUE TITLE
EdDSA JCE keys don't work in SunJSSE certificate authentication

### ISSUE THREAD

**Issue by timw** [bcgit/bc-java#1352]
EdDSA (public and private) keys generated by BC report `Ed25519` or `Ed448` in the `java.security.Key#getAlgorithm` method, as compared to the SunJCE keys that report `EdDSA`.

In the SunJSSE TLS implementation, this is expected to be `EdDSA` in two areas where signature scheme/certificate selection is performed:
- to authenticate a server presenting an `EdDSA` cert
- to authenticate a client  presenting an `EdDSA` cert

In both of these cases when trying to negotiate the `Ed25519`/`Ed448` signature schemes, it is looking for a certificate with an `EdDSA` key type, and this doesn't match (even though there are `Ed25519` certificates in the key manager in my test cases).

This failure to match is then exhibited as a handshake failure (in the case of the server cert auth) or a bad certificate failure (in the case of the client auth, when it fails to find a certificate to present for authentication).

If I round-trip the keys/certs through PKCS12 (e.g. loaded into a PKCS12 `KeyStore` from the `SUN` Provider, then the generated EdDSA keys/certs work in all scenarios.

I suspect other PKIX functions implemented in the Sun code (like validating cert chains) will fail in similar ways, but haven't tested those yet.

**Comment by dghgit** [comment]
Oh well... okay, I've actually had a couple of emails about this. Try 173b21 on https://www.bouncycastle.org/betas - if you set the system/security property org.bouncycastle.emulate.oracle it will now try and mimic the SunJCE provider for these keys.

**Comment by dghgit** [comment]
1.73 now out, so use of the new system property should deal with this.
