### ISSUE TITLE
java.io.IOException: error constructing MAC: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by Karathra** [bcgit/bc-java#1354]
Hi
Getting exception as below
java.io.IOException: error constructing MAC: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
	at org.bouncycastle.jce.provider.JDKPKCS12KeyStore.engineLoad(JDKPKCS12KeyStore.java:802)
	at java.security.KeyStore.load(KeyStore.java:1238)

after migrating the JAVA Version to 7.0.11.0 in WAS version 8.5.5.21
Due to some constraints not able to move to java 8 and higher versions for time being.

BC jars using is bcprov-jdk14-130.jar.
the functionality was working properly with Java versions 7.0.10.15
Request you to please share any pointers on this exception

**Comment by dghgit** [comment]
The provider jar is way out of date for the JVM you are trying to use. Actually it's way out of date in general. I would update the provider to a more recent one.

**Comment by Karathra** [comment]
Hi 
Thanks for the update. 
Any pointers on version of provider jar need to use with the java version 7.0.11.0 ?

**Comment by dghgit** [comment]
bcprov-jdk15to18-172

**Comment by Karathra** [comment]
We have tested the bcprov-jdk15to18-172  , but getting the same error.
Is there any specific steps to deploy the signed jars in WAS environment ?

**Comment by dghgit** [comment]
For the JCE the jar cannot be tampered with or unpacked. The JVM will refuse to validate it.
