### ISSUE TITLE
Breaking API change between v1.71 and v1.72?

### ISSUE THREAD

**Issue by qiangdavidliu** [bcgit/bc-java#1356]
Hi.

In v1.71 (and earlier), the `contains(long keyID)` method in `PGPSecretKeyRingCollection.java` throws `PGPException` in the method signature. ([link](https://github.com/bcgit/bc-java/blob/r1rv71/pg/src/main/java/org/bouncycastle/openpgp/PGPSecretKeyRingCollection.java#L270))

In v1.72, the same method no longer throw `PGPException`. ([link](https://github.com/bcgit/bc-java/blob/r1rv72/pg/src/main/java/org/bouncycastle/openpgp/PGPSecretKeyRingCollection.java#L260))

This seem to be a breaking API change between the versions. Was this intended to change with 1.72?

**Comment by dghgit** [comment]
Actually I'd say that was a bit of an oversight on our part. Sorry. It would not be prudent to change it back though.

**Comment by qiangdavidliu** [comment]
Appreciate you looking into this. 

The issue with this breaking API change is that it make upgrades from 15on to 18on difficult to validate. As an example, in our internal upgrade, we actually hit internal use cases where code needs to be fixed due to the API change. 

For internal code, this is fine and we can deal with it by changing the code. However my concern is with 3rd party transitive dependencies that may also be impacted, and we have no way of knowing what may break ahead of time. Do you have any sense of how common `PGPException` is caught in open source usages of bouncycastle, and these may need to be changed/updated?

**Comment by dghgit** [comment]
Yes, I can see the problem although in this space sometimes API changes are necessary, if only to stop the sins of the past being repeated (unfortunately not true in this case).

No idea on the answer to the question, although usually if this going to be a problem you'll see other artifacts attempting to suck in older versions of the API.
