### ISSUE TITLE
testJCE fails on "Tampered AEAD ciphertext should fail with Exception"

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#1357]
```
index 80 ChaCha20Poly1305: Tampered AEAD ciphertext should fail with AEADBadTagException when available. 

junit.framework.AssertionFailedError: index 80 ChaCha20Poly1305: Tampered AEAD ciphertext should fail with AEADBadTagException when available. 
at org.bouncycastle.jce.provider.test.SimpleTestTest.testJCE(SimpleTestTest.java:26) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23) 
at junit.extensions.TestSetup$1.protect(TestSetup.java:23) 
at junit.extensions.TestSetup.run(TestSetup.java:27)
```

**Comment by dghgit** [comment]
Hmmm... that's a bit odd. What JVM is this on?

**Comment by mouse07410** [comment]
> Hmmm... that's a bit odd. What JVM is this on?

Amazon Corretto JDK 17.0.6

**Comment by dghgit** [comment]
Okay, well that didn't work... There's a couple of spots in the test with:

            if (aeadAvailable)
            {
                if (!e.getClass().getName().equals("javax.crypto.AEADBadTagException"))
                {
                    fail("Tampered AEAD ciphertext should fail with AEADBadTagException when available.");
                }
            }

I've got a feeling this will be the name test is the actual issue, but it looks like you'd have to be building with the Corretto JDK as well. Assuming you are building with Corretto, would you be able to find out what it's producing? Thanks.

**Comment by mouse07410** [comment]
> it looks like you'd have to be building with the Corretto JDK as well.

That I certainly did.

> Assuming you are building with Corretto, would you be able to find out what it's producing?

Could you please be more specific? Find out exactly what? And how? Guidance (detailed) would be appreciated.

**Comment by dghgit** [comment]
I think we just need to know what e.getClass().getName() is returning in org.bouncycastle.jce.provider.test.ChaCha20Poly1305Test at the line given above. I'm pretty sure that's the one that is causing grief.

**Comment by mouse07410** [comment]
Hmm... I don't know what to say - last night pulled the updates from GitHub and re-built, tests passed. No idea if the problem was a fluke, or an intermittent bug that only shows up sometimes.  All I can say - it was consistent until the last update.

Let me close for now - I'll re-open if it re-appears. Thanks!
