### ISSUE TITLE
problem of 1.70-CMSSignedData

### ISSUE THREAD

**Issue by lourenxiang** [bcgit/bc-java#1360]

**Comment by dghgit** [comment]
I'd need some sample data for this one. It's impossible to work out what's going on from the details above as we can't reproduce them here.

**Comment by lourenxiang** [comment]
I've fixed the problem because of a code problem written by the individual. Please delete this issue because it contains the company code. Thank you!

**Comment by mouse07410** [comment]
Add far as I know, GitHub allows to close issues, but not too delete them.

**Comment by dghgit** [comment]
Sorry, but @mouse07410 appears to be correct.
