### ISSUE TITLE
FIPS Jakarta Mail version

### ISSUE THREAD

**Issue by phax** [bcgit/bc-java#1361]
Hi guys,

Do you plan to make a FIPS version of the BCMail component on Jakarta API basis?

This would be needed for https://github.com/phax/as2-lib/issues/146

Thanks, Philip

**Comment by mkoncek** [comment]
Adding to this, as a Java package maintainer, I would appreciate if this project ported the old `javax` dependencies for `jakarta` components. AFAIK there is currently the old `activation` and `mail`.

**Comment by dghgit** [comment]
Answered by @phax. Thanks!
