### ISSUE TITLE
ArrayIndexOutOfBoundsException in PKCS10CertificationRequest.getRequestedExtensions()

### ISSUE THREAD

**Issue by ILMTitan** [bcgit/bc-java#1368]
I generated a basically empty CSR using OpenSSL to test misconfiguration scenarios. I was prepared to handles null return values, but instead I got an `ArrayIndexOutOfBoundsException` when I called `PKCS10CertificationRequest.getRequestedExtensions()`

Code to reproduce:

```java

import org.bouncycastle.pkcs.PKCS10CertificationRequest;
import org.bouncycastle.openssl.PEMParser;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import java.io.StringReader;

//...

        Security.addProvider(new BouncyCastleProvider());

//...

        PKCS10CertificationRequest csr;
        try (PEMParser reader = new PEMParser(new StringReader(Resources.CSR_EMPTY_PEM))) {
            csr = (PKCS10CertificationRequest) reader.readObject();
        }

        assertDoesNotThrow(csr::getRequestedExtensions);
```

`Resources.CSR_EMPTY_PEM` has a value of :

```pem
-----BEGIN CERTIFICATE REQUEST-----
MIICVDCCATwCAQAwADCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKy8
4oC/QPFkRBE04LIA5njEulZx/EEh+J2spnThoRwk+oycYEVKp95NSfGTAoNjTwUv
TdB9c1PCPE1DmgZIVLEVvouB7sZbMbLSI0d//oMO/Wr/CZmvjPGB8DID7RJs0eqO
gLgSuyBVrwbcSKtxH4NrNDsS5IZXCcE3xzkxMDdz72m9jvIrl2ivi+YmJ7cJo3N+
DBEqHZW28oytOmVo+8zhxvnHb9w26GJEOxN5zYbiIVW2vU9OfeF9te+Rhnks43Pk
YDDP2U4hR7q0BYrdkeWdA1ReleYyn/haeAoIVLZMANIOXobiqASKqSusVq9tLD67
7TAywl5AVq8GOBzlXZUCAwEAAaAPMA0GCSqGSIb3DQEJDjEAMA0GCSqGSIb3DQEB
CwUAA4IBAQAXck62gJw1deVOLVFAwBNVNXgJarHtDg3pauHTHvN+pSbdOTe1aRzb
Tt4/govtuuGZsGWlUqiglLpl6qeS7Pe9m+WJwhH5yXnJ3yvy2Lc/XkeVQ0kt8uFg
30UyrgKng6LDgUGFjDSiFr3dK8S/iYpDu/qpl1bWJPWmfmnIXzZWWvBdUTKlfoD9
/NLIWINEzHQIBXGy2uLhutYOvDq0WDGOgtdFC8my/QajaJh5lo6mM/PlmcYjK286
EdGSIxdME7hoW/ljA5355S820QZDkYx1tI/Y/YaY5KVOntwfDQzQiwWZ2PtpTqSK
KYe2Ujb362yaERCE13DJC4Us9j8OOXcW
-----END CERTIFICATE REQUEST-----
```

**Comment by dghgit** [comment]
Thanks for the report. I've had a look at this and i've been able to confirm what you're seeing. Yes, I don't think the current behavior is what we're striving for.

I know this is probably going to sound dreadful, but I'm heavily inclined to get this to throw an IllegalStateException - if the attribute is there you'd really think the originator would have intended to put something in it. I don't think null, while not a wrong response, is really the best response as in any sensible situation letting it got through will result in a certificate going back to the originator that is probably missing the extension they thought they were requesting. In a situation like this it's really better for the originator to get their house in order.

**Comment by dghgit** [comment]
No further activity. IllegalStateException with a more meaningful message (hopefully) now thrown.
