### ISSUE TITLE
org.bouncycastle.asn1.DLSequenceParser cannot be cast to org.bouncycastle.asn1.ASN1SetParser

### ISSUE THREAD

**Issue by lhuynh-cs** [bcgit/bc-java#1372]
Hi

Got java.lang.ClassCastException: org.bouncycastle.asn1.DLSequenceParser cannot be cast to org.bouncycastle.asn1.ASN1SetParser
	at org.bouncycastle.asn1.cms.SignedDataParser.getSignerInfos(Unknown Source)
	at org.bouncycastle.cms.CMSSignedDataParser.getSignerInfos(Unknown Source)
	at TestSCEPReq.main(TestSCEPReq.java:62)
when calling getSignerInfos() after reading CMS data from https://github.com/jscep/jscep/blob/master/src/samples/scep_req2.der using CMSSignedDataParser

Source code attached
[TestSCEPReq.zip](https://github.com/bcgit/bc-java/files/11177469/TestSCEPReq.zip)

**Comment by dghgit** [comment]
The object contains encapsulated signed content you need to do a:

 csdp.getSignedContent().drain();

before trying to parse the signerInfos. getSignedContent() will return null if there is none present.
