### ISSUE TITLE
question about class loader validation

### ISSUE THREAD

**Issue by cstmgl** [bcgit/bc-java#1373]
hi all,
I have an issue that I think is not really related to the bouncy castle itself but I'm not really sure how to validate this or how to move forward to try and isolate the issue.

I'm using kafka connect to connect some kafka instance to snowflake.
As part of that I use a key that needs to be de-crypted.
For that snowflake uses bouncy castle to decrypt the private key
https://docs.snowflake.com/en/user-guide/kafka-connector-install#download-the-kafka-connector-jar-files

```
'org.bouncycastle:bc-fips:1.0.1'
'org.bouncycastle:bcpkix-fips:1.0.3'
```

I know that snowflake provides a fatJar with all it's dependencies except for the bouncy castle itself, because I know the bouncy castle jar itself cannot be provided inside a fatJar and should not be modified (I faced that error in the past).

Anyway today I was doing some updates and my environment stopped working with this error in the log:

`Caused by: java.lang.SecurityException: class "org.bouncycastle.util.test.TestRandomBigInteger"'s signer information does not match signer information of other classes in the same package
`

I'm pretty sure I have the correct bc-fips and bcpkix-fips jars in my classpath but I wanted to know how can I debug and ensure that my bouncy castle jars are correct? 
The only main difference I noticed is that I'm inheriting a new dependency that depends on 
```
org.bouncycastle:bcprov-jdk18on-1.72
org.bouncycastle:bcutil-jdk18on-1.72
```

I looked and I don't see any cross dependency between bcprov and bcutil and (bc-fips or bcpkix) but I have no idea.

I read this thread already but did not help me much.
https://stackoverflow.com/questions/41937877/java-lang-securityexception-class-org-bouncycastle-asn1-derencodable

Anyone experienced this error in the past and can give me some pointers?

The only thing I know is that for sure the signatures inside the META-INF for the packages bcpkix-fips-1.0.3 and bc-fips-1.0.1 are different, but I assume they are supposed to be?

**Comment by dghgit** [comment]
Yes, FIPS and non-FIPS cannot be used together. So bc-fips is the FIPS version of bcprov (more or less, there are some FIPS related differences, but it's basically the same thing). There's FIPS equivalents for the additional BC APIs as well, these are written to respect the FIPS restrictions.
