### ISSUE TITLE
1.73 not available via Maven central repository

### ISSUE THREAD

**Issue by thestinger** [bcgit/bc-java#1374]
This is still documented as supported but it's not uploaded there.

https://www.bouncycastle.org/latest_releases.html

> The BC jars are now mirrored on the Maven central repository. You can find them at https://repo1.maven.org/maven2/org/bouncycastle.

**Comment by dghgit** [comment]
Sorry, it's a manual process, it takes a while.

**Comment by dghgit** [comment]
Now published.

**Comment by OrangeDog** [comment]
@dghgit 1.74 is also not published, despite being released three days ago.

Can this be improved (ideally automated) in future? Why isn't publishing to Maven in your release process by default?

This is especially problematic when a release discloses a security issue. The fixed versions need to be available asap.

**Comment by dghgit** [comment]
It was published to Maven central hours ago. You may need to wait for your local version of the repository to sync up.

It is on repo1 already if you wish to use that, example below:

https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk18on/1.74/

**Comment by OrangeDog** [comment]
Ha, I checked https://repo.maven.apache.org/maven2/org/bouncycastle/bcutil-jdk18on/ which appears to be the only one that isn't synced yet. All the other packages there have.

Though, that's still a couple days delay to get it published. A process improvement would still be good, for everyone.
