### ISSUE TITLE
Bug: Library size doubled from 1.71 to 1.72

### ISSUE THREAD

**Issue by michaeltroger** [bcgit/bc-java#1377]
The `bcprov-jdk15to18` library size doubled from version 1.71 to 1.72.
In other words it increased by 4MB

See:
https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15to18/1.71
https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15to18/1.72

Is this expected?

**Comment by stardrift1** [comment]
Is this a bug? if we can't revert to the older version ,how can we reduce the Library size? @dghgit

**Comment by dghgit** [comment]
1.72 added the PQC algorithms BIKE, Kyber, Dilithium, Falcon, HQC, NTRU, NTRUPrime, Picnic, SIKE, and Sphincs+. So it wasn't a bug, more a product of an awful lot of hard work. These are mostly algorithms people should be trying out as well.

There are some legacy PQC algorithms in there which we are planning to retire soon and obviously SIKE is now dead so you can expect 1.74 to be smaller that 1.73. If you check the jar you'll see that SIKE is actually responsible for a lot of the extra space.

I would not recommend reverting though, encryption software never ages well. We're aiming to release 1.74 early June, so you'll get some relief then. I could provide a custom version of 1.73 which has the SIKE resource files removed from it. If you try building one yourself you'll see it reduces the file size by a couple of meg at least.

**Comment by dghgit** [comment]
Just an update to this, we've removed SIKE, the 1.74 15to18 providers now weigh in at:

6204 -rw-rw-r-- 1 dgh dgh 6349750 May 20 10:08 build/artifacts/jdk1.5/jars/bcprov-ext-jdk15to18-174b02.jar
6140 -rw-rw-r-- 1 dgh dgh 6285096 May 20 10:08 build/artifacts/jdk1.5/jars/bcprov-jdk15to18-174b02.jar

**Comment by vlsi** [comment]
@dghgit , have you considered housing different algorithms in their own jars?

Then people could use what they need rather than a single jar that includes all the possible algorithms.

**Comment by dghgit** [comment]
I'd be a huge fan of that. There's actually an example of this in the FIPS APIs (sort of), the PQC jar. Unfortunately the underlying provider system doesn't work like that -all the classes related to a JCA implementation have to be in the same jar, we'd have to replicate all the infrastructure classes such as the ASN.1 library and implementing hybrid algorithms and certificate support would be challenging at best. The alternative would be to not provide JCA support for the PQC algorithms and limited encoding support which would be a huge barrier for a lot of our user community who don't use the low-level APIs.

We can probably retire some more code when PQC round 4 comes to the end, but there are more algorithms coming as well so while I would expect the jar to increase much at this point it's probably going to see stuff getting added at about the rate stuff is getting shoveled out.

**Comment by vlsi** [comment]
Just wondering, could you please clarify where does the requirement of "all the classes related to a JCA implementation have to be in the same jar" comes from?

> certificate support would be challenging

Do you mean something like "certificate could use any algorithm, so we'd better include all of them just in case"?
What if bc-java locates algorithm implementations with `META-INF/services`? Then it could dynamically discover the algorithms that are present.

**Comment by dghgit** [comment]
Originally this was detailed in the document about writing your own JCE provider. I looked this up again though, and as of Java 11 it appears the document now appears to imply that you're allowed to use the module structure as long as the individual jars making up the module are signed with a JCE signing certificate. I'll have to try it. I'm not sure it will really help in this case as the jar concerned predates the use of modules.

**Comment by stardrift1** [comment]
>Maybe we can test some features of version 1.74

**Comment by vlsi** [comment]
As far as I see, the major contributor to the library size are `.properties` files for `pqc`.
What if those `.properties` are moved to a separate jar?

It might probably make sense to convert properties to binary format. It would reduce both memory and CPU overheads on loading the data.

**Comment by dghgit** [comment]
It went better than expected, converted to binary, then compressed using GZIP:

5852 -rw-rw-r--  1 dgh dgh 5991317 May 23 10:28 bcprov-ext-jdk15to18-174b04.jar
5788 -rw-rw-r--  1 dgh dgh 5926663 May 23 10:28 bcprov-jdk15to18-174b04.jar

**Comment by dghgit** [comment]
@stardrift1 are there any jars required other than the provider?

**Comment by dghgit** [comment]
Yes, the picnic compression is in 1.74. Have a look at https://www.bouncycastle.org/betas the jdk18on beta jars are available there.

**Comment by dghgit** [comment]
1.74 is now appearing on the BC website. Should also be on Maven central in a couple of days.

**Comment by dghgit** [comment]
The release tag should appear in the next hour or so.

**Comment by dghgit** [comment]
Believed resolved.

**Comment by vlsi** [comment]
For reference,

4.3M https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15to18/1.71
6.2M https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15to18/1.74

**Comment by dghgit** [comment]
I'm afraid that's as small as it's going to get for now - the difference at this point is the PQC algorithm set.

**Comment by stardrift1** [comment]
> I'm afraid that's as small as it's going to get for now - the difference at this point is the PQC algorithm set.

if we don't use PQC, is there any way to remove the PQC algorithm set?

**Comment by dghgit** [comment]
Yes, you could remove org.bouncycastle.crypto.pqc. There would be a couple of other classes to clean up as some of the PQC algorithms are referenced from the BC provider so certificates can be dealt with, but it should be fairly simple to deal with.
