### ISSUE TITLE
Validation of id-aa-ets-archiveTimestampv2 fails from version 1.73

### ISSUE THREAD

**Issue by bsanchezb** [bcgit/bc-java#1378]
Hello,

Starting from version 1.73, the validation of _id-aa-ets-archiveTimestamp-v2_ fails on our legacy signatures with BER-encoded content info.
It seems that the problem has been introduced with commit for the issue #1349, that uses a DER encoding within a BEROctetString. In our case, this removes some characters contained within the original data.

Please see the unit test below that passes on 1.72 and before and fails with 1.7.3:
```
    @Test
    public void contentInfoTest() throws IOException {
        File contentInfoBytesFile = new File("contentInfoBytes");
        byte[] contentInfoBytes = Files.readAllBytes(contentInfoBytesFile.toPath());
        ContentInfo contentInfo = ContentInfo.getInstance(contentInfoBytes);
        assertArrayEquals(contentInfoBytes, contentInfo.getEncoded());
    }
```
The target file is within the ZIP archive.

Best regards,
Aleksandr.

[contentInfoBytes.zip](https://github.com/bcgit/bc-java/files/11274218/contentInfoBytes.zip)

**Comment by dghgit** [comment]
Thanks for the report. Try https://www.bouncycastle.org/betas 174b03 or later I think that should fix both this problem and the original one.

**Comment by bsanchezb** [comment]
Hi @dghgit ,

I made a test with 174b04 version and the issue seems to be fixed! I did not do tests on all available signatures with arc-tst-v2 so, but only on the failed one.

Thanks!

Best regards,
Aleksandr.
