### ISSUE TITLE
Question Regarding Gradle and module-info.class

### ISSUE THREAD

**Issue by Annette0127** [bcgit/bc-java#1385]
Hello!
I encountered some issues while building the project using Gradle, as the `module-info.class` files were missing. However, I managed to resolve the issue by using the bash scripts (i.e., the ones to build and add modules) that come with the project. And I have a couple of questions regarding this:

- Is it possible to build the project using Gradle without the need for the bash scripts? I’m concerned I may be misusing the Gradle configuration for building. 
- Why are the build script and `add_module.sh` files separated, i.e., why is it that `module-info.java` files and the other Java source files seem to be compiled separately? There seems to be some kind of design advantage of compiling them separately, but I can’t determine what exactly that may be.

**Comment by dghgit** [comment]
There's two reasons: the BC distributions are built using ant (usually), the second is we started add multi-release support well before it was available in gradle (hence the script, which at the time was a necessity). Both these are clearly historical, it is actually possible now to get gradle to compile using different JVMs so you can do almost everything add_module.sh does in an appropriately written gradle script.

**Comment by Annette0127** [comment]
I see. Thank you very much for the detailed explanation. It has been very helpful, and I truly appreciate it! 😊
