### ISSUE TITLE
`IntegerFunctions.modPow` has faulty overflow check

### ISSUE THREAD

**Issue by Marcono1234** [bcgit/bc-java#1388]
The `(n * n) > Integer.MAX_VALUE` check here is faulty:
https://github.com/bcgit/bc-java/blob/876bd0cf02811282707ddd38e4f0f9212a9f4d1f/core/src/main/java/org/bouncycastle/pqc/legacy/math/linearalgebra/IntegerFunctions.java#L486

`n` is an `int`, so `(n * n)` also has type `int` and therefore cannot be `> Integer.MAX_VALUE`.

Maybe the solution would be to cast one of the arguments of the multiplication to `long`, but I am not sure if that fix could cause issues for users who rely on the current broken implementation.

**Comment by peterdettman** [comment]
Agree the comparison is incorrect. Method can be deleted as it is unused and already marked as legacy.

**Comment by dghgit** [comment]
I've actually fixed this one, but as Peter says, that particular section of the code base is not long for this world.
