### ISSUE TITLE
j2me `BigInteger.makeMagnitude` has faulty byte comparisons

### ISSUE THREAD

**Issue by Marcono1234** [bcgit/bc-java#1389]
`BigInteger.makeMagnitude` contains the following faulty byte comparisons:
- https://github.com/bcgit/bc-java/blob/876bd0cf02811282707ddd38e4f0f9212a9f4d1f/core/src/main/j2me/java/math/BigInteger.java#L429
- https://github.com/bcgit/bc-java/blob/876bd0cf02811282707ddd38e4f0f9212a9f4d1f/core/src/main/j2me/java/math/BigInteger.java#L435

`bval` is a `byte` array and the maximum `byte` value is 127, however both `0xff` and `0x80` are > 127. Maybe the code is missing `& 0xFF` before performing the comparison?

I don't know what effect those incorrect comparisons have though.

**Comment by peterdettman** [comment]
They are not faulty. 0xFF and 0x80 are negative values, they are not > 127. In this context we are mainly interested in them as a bit pattern anyway, since we are stripping redundant leading 1 bits from a two's-complement value.

**Comment by Marcono1234** [comment]
But `0xff` and `0x80` are `int` literals (there are no `byte` literals), so they are actually 255 and 128 respectively. And it appears for the comparison numeric promotion is performed so the `byte` in range -128 to 127 is converted to `int`.

For example the following is `false`:
```java
byte b = (byte) 0xff;
b == 0xff
```

Or can you provide any `byte` value where the condition <code>_byte_ == 0xff</code> is true?
(Maybe I am overlooking something here?)

**Comment by peterdettman** [comment]
Actually you are correct, sorry for misreading it the first time around. Will fix.

**Comment by Marcono1234** [comment]
Thanks for fixing this in 46d3f724216526c46dcb5646badf70d5e3066895! Can the issue then be closed?
