### ISSUE TITLE
Bouncy Castle Fails under Intelij - Java 17

### ISSUE THREAD

**Issue by jcarnus** [bcgit/bc-java#1392]
Hi,
I am using the following part of code to read a "ENCRYPTED PRIVATE KEY". BC 1.73, Java 17

`try (PEMParser pemParser = new PEMParser(reader)) {
	Object object = pemParser.readObject();
	JcaPEMKeyConverter converter = new JcaPEMKeyConverter().setProvider(PROVIDER_NAME);
	if (object instanceof PKCS8EncryptedPrivateKeyInfo encryptedPrivateKeyInfo) {
		InputDecryptorProvider inputDecryptorProvider =
				new JcePKCSPBEInputDecryptorProviderBuilder().setProvider(PROVIDER_NAME)
						.build(password.toCharArray());
		PrivateKeyInfo privateKeyInfo =
				encryptedPrivateKeyInfo.decryptPrivateKeyInfo(inputDecryptorProvider);
		return converter.getPrivateKey(privateKeyInfo);
	} else {
		throw new IOException("Unsupported object type " + object.getClass());
	}
} catch (IOException | PKCSException e) {
	throw new CertificateException(e.getMessage(), e);
}`

For the same input of PEM string and password, I am getting a javax.crypto.BadPaddingException: pad block corrupted when running the code under an intelij Plugins. What could be the reason of having this ?

Thanks

**Comment by dghgit** [comment]
It smells a bit like there's another provider involved somewhere. What does the stack trace look like?

**Comment by jcarnus** [comment]
Hi,
I finally found the issue which is explained here : https://dkimitsa.github.io/2018/07/27/intellij-idea-bouncy-castle-2/

I close the issue
