### ISSUE TITLE
Does Bouncy Castle still not support AES Native Instructions?

### ISSUE THREAD

**Issue by softpudding** [bcgit/bc-java#1396]
Hi, I'm curious if Bouncy Castle support AES Native Instructions. I noticed that as mentioned in [Does Bouncy Castle support AES native instructions (AES-NI)? #221 ](https://github.com/bcgit/bc-java/issues/221), it was said that BC does not support AES NI. Since the issue was in 2017, I wonder if we support AES NI now (in 2023)?

**Comment by dghgit** [comment]
Have a look at: https://www.bouncycastle.org/lts-java - it has support for Intel's instruction set.

**Comment by mouse07410** [comment]
I'm sorry, but I found the referred page rather confusing. 

1. Will there be an LTS release of BouncyCastle? Will it be a separate branch/repo/whatever, or would you just designate certain releases, like 1.74, to be LTS (as JDK itself does)?

2. How do I tell what native instruction sets a given release supports? The referred page seemed to have only generic information, and I didn't understand how to drill down for this specific piece. 

3. Nowadays, ARM is as important as Intel, maybe even comparably widespread. And it also includes AES instructions set. Does your LTS support native AES instructions for ARM64 as well? If not, may I suggest adding it?

**Comment by dghgit** [comment]
We're still setting everything up so you'll have to bare with us.

In answer to the questions:

1. Yes, it's based on 1.73 with some changes which are also going into 1.74. It doesn't currently include the post-quantum code, although we'll probably add LMS soon with the other algorithms following as they are formally standardized. We will do non-API-breaking updates for 4 years, with the last year being the usually security updates only. If people are willing to stump up some cash we are willing to provide the resources to support longer term usage where required, we just need to be able to cover it. It'll be a separate repository, git branching is great, but it only gets you so far... 
2.  "java -cp bc-lts8on-2.73.0-SNAPSHOT.jar org.bouncycastle.util.DumpInfo" will tell you what the jar will support on your hardware, as for the jar itself "jar tf bcprov-lts8on-2.73.0-SNAPSHOT-sources.jar | egrep native" will tell you what's in there (I'll admit at the moment this lists .so files, as I said we're still sorting out the last bits of packaging, but I'll fix it so the source is included).
3. ARM's definitely on the list, but it was not what the sponsors supporting the effort were after and we were offered, and did receive, extremely good support from Intel, meaning this time around it's Intel. We would be happy to add support for ARM as resources allow, but the improvements in throughput the current JNI code allows have made it worthwhile releasing what we currently have.

**Comment by leandropadua** [comment]
@dghgit Is the ARM supported version also FIPS validated?
I wonder if we could use it in ARM64 FedRAMP environments.

**Comment by dghgit** [comment]
Sorry, it's intel native only in FIPS. The LTS release now provides ARM support as well.
