### ISSUE TITLE
Falcon-512 Key Size Issue

### ISSUE THREAD

**Issue by normasw98** [bcgit/bc-java#1397]
* hi~
* When comparing the key length between the Falcon standard specification and BC, the key length generated by BC is 1 byte shorter. When attempting to load the generated BC based Falcon key file on another system, an error occurs.

* Falcon Parameter set summary
 : Falcon-512 : **897** bytes(PublicKey Size), **1281** bytes(SecretKey Size)
 : reference : https://openquantumsafe.org/liboqs/algorithms/sig/falcon.html

* sample code
```
		SecureRandom random = new SecureRandom();
		FalconKeyPairGenerator keyGen = new FalconKeyPairGenerator();
		keyGen.init(new FalconKeyGenerationParameters(random, FalconParameters.falcon_512));
		
		AsymmetricCipherKeyPair keyPair = keyGen.generateKeyPair();
		AsymmetricKeyParameter priKeyParam = (AsymmetricKeyParameter) keyPair.getPrivate();
		FalconPrivateKeyParameters priParams = (FalconPrivateKeyParameters) priKeyParam;

		System.out.println("encode : " +priParams.getEncoded().length);
		System.out.println("f : " +priParams.getSpolyf().length);
		System.out.println("F : " +priParams.getSpolyF().length);
		System.out.println("G : " +priParams.getG().length);
		System.out.println("PK : " +priParams.getPublicKey().length);
```

* result
encode : **1280**
f : 384
F : 512
G : 384
PK : **896**

![image](https://github.com/bcgit/bc-java/assets/117900193/0c2bcafe-35d6-48d2-b3ef-c0903b02d356)

* dependency
```
 	<dependency>
		<groupId>org.bouncycastle</groupId>
		<artifactId>bcpkix-jdk18on</artifactId>
		<version>1.73</version>
	</dependency>
```

**Comment by dghgit** [comment]
The BC encoding is based on:

https://www.ietf.org/archive/id/draft-uni-qsckeys-falcon-00.txt

Which has now (just) expired. There doesn't appear to be another proposal though so I'm not sure what will happen next.

At any rate, the difference is the type byte is missing from the start of the encoding (the draft only used h) these are:

0x09 falcon-512 public key
0x59 falcon-512 private key

0x0a falcon-1024 public key
0x5a falcon-1024 private key

If you concatenate the appropriate byte above to the start of the key you should find it works.

**Comment by normasw98** [comment]
Thank you for answer.

**Comment by mouse07410** [comment]
@dghgit AFAIK, `qsckeys` draft had no support at IETF and died natural death. 

Perhaps, just follow the NIST approach and pass byte arrays?

**Comment by dghgit** [comment]
Yes, it's just curious that something else has not emerged yet. I have heard that NIST are planning to take a more active interest in the encoding side of things with these algorithms, but they haven't actually expressed a position yet on this. The encodings used in the reference implementations were simply the ones chosen by the submission teams.

About the only thing I can say for now is encodings for certificates usually represent the most economic use of bytes possible for a given algorithm, so it's unlikely a type byte would be included if the decision is made to specify different OIDs for the parameter sets involved (which is definitely a NIST thing, and seems likely).

**Comment by mouse07410** [comment]
Well, encoding of _certificates_ is a different story. But keys, signatures, and cipher texts of MIST PQC algorithms are simply byte arrays or octet strings. There is no reason to complicate or over-think this. A byte string is a byte string. Anybody can send and receive them as-is. Which probably is why the qsc draft withered - like a fifth wheel on a cart.
