### ISSUE TITLE
Feature request: Expose PGPPublicKeyRing API

### ISSUE THREAD

**Issue by ov7a** [bcgit/bc-java#1399]
It would be nice to have some public API for getting a number of keys in PGPPublicKeyRing. Right now it is possible to get it via [public keys iterator](https://github.com/bcgit/bc-java/blob/876bd0cf02811282707ddd38e4f0f9212a9f4d1f/pg/src/main/java/org/bouncycastle/openpgp/PGPPublicKeyRing.java#L226), but it would require O(n) time.

Note that  `Collections.unmodifiableList` is used in the implementation, so this list or its method can be exposed.

**Comment by dghgit** [comment]
Good point... funny this one hasn't come up already. I've added a size() method to PGPSecretKeyRing and PGPPublicKeyRing. Thanks for the report.
