### ISSUE TITLE
Java core dump SIGSEGV in docker.

### ISSUE THREAD

**Issue by javadevmtl** [bcgit/bc-java#1417]
Hi I'm using the SMBJ (Samba) lib to put files from Java/Linux/Docker to Windows shares. When Bouncy Castle does it's encryption thing the app exits with a SIGSEV error. Initially I though it was maybe an image thing so I posted it to the Azul guys, but they say it's a docker/kernel issue.

Here is the issue and it has attached dump file etc...

https://github.com/zulu-openjdk/zulu-openjdk/issues/215

**Comment by dghgit** [comment]
If you're seeing it across multiple platforms it could be a JIT error - it's been a while since we've seen something like this, but it's probably worth getting someone to check what is been done with byte code around that method.

**Comment by dghgit** [comment]
Appears to be the JIT.
