### ISSUE TITLE
DefaultJcaJceHelper does not support SHA256

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#1428]
A slight issue I found when working with the JcaPGPObjectFactory class:
The JcaPGPObjectFactory class internally uses a JcaKeyFingerprintCalculator, which in turn uses the DefaultJcaJceHelper which does not support SHA256.
Unfortunately, the JcaPGPObjectFactory has no way of injecting a modified JcaKeyFingerprintCalculator with injected ProviderJcaJceHelper.
Therefore, the JcaPGPObjectFactory class cannot be used out of the box to parse e.g. OpenPGP v6 keys, whose fingerprints are calculated using SHA256.

I was able to work around this by replacing my use of JcaPGPObjectFactory with the following code:
```java
PGPObjectFactory objFact = new PGPObjectFactory(inputStream, new JcaKeyFingerprintCalculator().setProvider(new BouncyCastleProvider()));
```

Still, I thought it would be worth mentioning this issue.

**Comment by dghgit** [comment]
The more general name is "SHA-256" this is supported by both Oracle and BC. I've changed it to use "SHA-256".
