### ISSUE TITLE
First DH keypair generation takes too long

### ISSUE THREAD

**Issue by xipki** [bcgit/bc-java#143]
Tested with bcprov-jdk15on versions 1.54 and 1.55b12 on MacOSx 10.10.5.

Here the code:

Security.addProvider(new BouncyCastleProvider());
 KeyPairGenerator kpGen = KeyPairGenerator.getInstance("DH", "BC");
 kpGen.initialize(1024, new SecureRandom());
            
 for (int i = 0; i < 5; i++) {
    long start = System.currentTimeMillis();
    kpGen.generateKeyPair();
    long end = System.currentTimeMillis();
    System.out.println("round " + (i + 1) + ": " + (end - start) + " ms");
}

and the ouput

round 1: 56200 ms
round 2: 3 ms
round 3: 3 ms
round 4: 3 ms
round 5: 2 ms

**Comment by peterdettman** [comment]
What's happening is that the first time you ask to generate a key pair, the provider doesn't have any DH parameters for the key size you requested, and generates a new set (which is particularly slow as we search for a Sophie Germain prime). Subsequent requests at the same key size will re-use those parameters.

To avoid that, the provider supports configuring specific DH parameters to be used either VM-wide or for the current thread. See the testConfig() method of [DHTest](https://github.com/bcgit/bc-java/blob/master/prov/src/test/java/org/bouncycastle/jce/provider/test/DHTest.java) for example usage. Either generate your own set of parameters (once only, not per-process), or we have various standardised groups defined in [DHStandardGroups](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/agreement/DHStandardGroups.java).

I would recommend using at least 2048 bits, unless you have specific reasons to use smaller and understand the implications of [Logjam](https://weakdh.org).
