### ISSUE TITLE
cannot identify EdEC/XDH private key: long form definite-length more than 31 bits on OpenJDK 11

### ISSUE THREAD

**Issue by SamAmco** [bcgit/bc-java#1448]
Hi, I'm not sure why but I'm seeing this issue on open jdk 11 but not on oracle jdk 20, so I suspect it may be a bug. I'm using the version: 
'org.bouncycastle:bcprov-lts8on:2.73.2'

If you run the following code: 

```
        val keyGen = KeyPairGenerator.getInstance("X448")
        keyGen.initialize(448)
        val keyPair = keyGen.genKeyPair()

        val cipher = Cipher.getInstance("XIES")
        val cipherParamSpec = IESParameterSpec(
            /* derivation = */ null,
            /* encoding = */ null,
            /* macKeySize = */ 128,
            /* cipherKeySize = */ 256,
            /* nonce = */ null,
            /* usePointCompression = */ false
        )
        cipher.init(Cipher.DECRYPT_MODE, keyPair.private, cipherParamSpec)

```

You get the exception: 

> cannot identify EdEC/XDH private key: long form definite-length more than 31 bits
java.security.InvalidKeyException: cannot identify EdEC/XDH private key: long form definite-length more than 31 bits
	at org.bouncycastle.jcajce.provider.asymmetric.edec.EdECUtil.generatePrivateKeyParameter(EdECUtil.java:78)
	at org.bouncycastle.jcajce.provider.asymmetric.edec.IESCipher.engineInit(IESCipher.java:327)
	at java.base/javax.crypto.Cipher.implInit(Cipher.java:843)
	at java.base/javax.crypto.Cipher.chooseProvider(Cipher.java:901)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1433)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1364)

**Comment by SamAmco** [comment]
Thanks for that. I don't really understand how JDK compatibility is supposed to work but the reason i'm using the lts 8 on version is i'm using this on android where we only have jdk 11 support. Do you expect a fix will come to the lts version?

**Comment by SamAmco** [comment]
No I haven't tested your fix sorry.

**Comment by dghgit** [comment]
It would be worth trying. If there's any further changes required now would be the time, I'm confident we can get everything working in time for the next release if I can get some feedback.

**Comment by SamAmco** [comment]
I'll let you know if I get a chance. Thanks.

**Comment by dghgit** [comment]
We'll be doing another release end of next week. I've migrated the fix to LTS.

**Comment by SamAmco** [comment]
Nice one, thank you very much :)
