### ISSUE TITLE
IDEA and Eclipse can't Debug Step Into any method of class in jar

### ISSUE THREAD

**Issue by dpf371** [bcgit/bc-java#1450]
My environment：
jdk：1.8
jar：bcprov-jdk15on、bcprov-jdk18on

I want to step into（F7） some method of class using JetBrains IDEA，bug I find can't do that and IDEA don't allow me make a breakpoint。I guess that the jar don't contains the line numbers info，maybe miss 'javac' argument '-g'  when compile ?

I need help, please help me, thanks.

**Comment by dghgit** [comment]
Use the -debug versions

**Comment by dpf371** [comment]
> Use the -debug versions

Thanks, I got it just like below , but think this is not a good idea , because I need exclude the dependency and then add the "xxx-debug-xxx" dependency , I suggest the debug version should depend on the debug version jar while not depend on the no debug version . 
 I have no harm , wishes you well , thanks again .

```
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcpkix-debug-jdk15to18</artifactId>
    <version>1.75</version>
    <exclusions>
        <exclusion>
            <artifactId>bcprov-jdk15to18</artifactId>
            <groupId>org.bouncycastle</groupId>
        </exclusion>
        <exclusion>
            <artifactId>bcutil-jdk15to18</artifactId>
            <groupId>org.bouncycastle</groupId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcutil-debug-jdk15to18</artifactId>
    <version>1.75</version>
    <exclusions>
        <exclusion>
            <artifactId>bcprov-jdk15to18</artifactId>
            <groupId>org.bouncycastle</groupId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-debug-jdk15to18</artifactId>
    <version>1.75</version>
</dependency>
```

**Comment by dghgit** [comment]
It's a bit of an odd one... some people want to debug against a particular jar, others want to have everything in debug. I'll try and work out what the most popular one is, either way people will need to override dependencies from time to time.

**Comment by dpf371** [comment]
> 

I got it , I understand your troubles，Thank you again。

**Comment by dpf371** [comment]
> It's a bit of an odd one... some people want to debug against a particular jar, others want to have everything in debug. I'll try and work out what the most popular one is, either way people will need to override dependencies from time to time.

I got it , I understand your troubles，Thank you again。
