### ISSUE TITLE
Timestamp generation does not support SHA3 algorithms

### ISSUE THREAD

**Issue by bsanchezb** [bcgit/bc-java#1455]
Hello,

There is a possibility to define a list of accepted digest algorithms for timestamp generation through the [TimeStampResponseGenerator](https://github.com/bcgit/bc-java/blob/6f5adec70b23f216b2b8a0c3bb164423f1372e30/pkix/src/main/java/org/bouncycastle/tsp/TimeStampResponseGenerator.java#L69) constructor. However, the list of digest algorithms one can use is limited through the [TSPUtil.digestLengths](https://github.com/bcgit/bc-java/blob/r1rv75/pkix/src/main/java/org/bouncycastle/tsp/TSPUtil.java#L43) which defines the hash length of computed value for each digest algorithms. 
When providing an algorithm which is not defined within the map, the method [TSPUtil.getDigestLength()](https://github.com/bcgit/bc-java/blob/r1rv75/pkix/src/main/java/org/bouncycastle/tsp/TSPUtil.java#L181) throws a "digest algorithm cannot be found." exception. This makes it impossible to create timestamps for some digest algorithms such as SHA3.

Is there a good reason why the number of digest algorithms is limited and SHA3 is not included to them? Would it be possible to make the map extendable, or at least populate with other digest algorithms supported within BC implementation?

Thank you!

Best regards,
Aleksandr.

**Comment by dghgit** [comment]
This is now in the current beta at https://www.bouncycastle.org/betas. Let us know if there are any issues. Thanks.

**Comment by dghgit** [comment]
Fixed in 1.76
