### ISSUE TITLE
Why can't I create an elliptic curve cipher with default parameters 

### ISSUE THREAD

**Issue by SamAmco** [bcgit/bc-java#1457]
If I try to generate an elliptic curve key pair and use it to initialise an ECIES cipher as follows: 

```
        val keyGen = KeyPairGenerator.getInstance("EC")
        keyGen.initialize(521)
        val keyPair = keyGen.genKeyPair()


        val cipher = Cipher.getInstance("ECIES")
        cipher.init(Cipher.ENCRYPT_MODE, keyPair.public)
```

The cipher.init line throws the exception: 

```
cannot handle supplied parameter spec: must be passed IES parameters
java.lang.IllegalArgumentException: cannot handle supplied parameter spec: must be passed IES parameters
	at org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher.engineInit(IESCipher.java:367)
```

Looking at the code I can see the reason for this exception in the ed and edec classes IESCipher: 

```
        // NOTE: For secure usage, sender and receiver should agree on a fixed value for the nonce.
//        if (engineSpec == null)
//        {
//            byte[] nonce = null;
//            if (ivLength != 0 && opmode == Cipher.ENCRYPT_MODE)
//            {
//                nonce = new byte[ivLength];
//                random.nextBytes(nonce);
//            }
//            this.engineSpec = IESUtil.guessParameterSpec(engine.getCipher(), nonce);
//        }
//        else
        if (engineSpec instanceof IESParameterSpec)
        {
            this.engineSpec = (IESParameterSpec)engineSpec;
        }
        else
        {
            throw new InvalidAlgorithmParameterException("must be passed IES parameters");
        }
```

The following code however will work: 

```
        val iesParamSpec = IESParameterSpec(
            /* derivation = */ null,
            /* encoding = */ null,
            /* macKeySize = */ 256,
            /* cipherKeySize = */ 256,
            /* nonce = */ null,
            /* usePointCompression = */ false
        )

        val keyGen = KeyPairGenerator.getInstance("EC")
        keyGen.initialize(521)
        val keyPair = keyGen.genKeyPair()


        val cipher = Cipher.getInstance("ECIES")
        cipher.init(Cipher.ENCRYPT_MODE, keyPair.public, iesParamSpec)
```

So it looks to me like you used to support default parameters for ECIES and then removed this support because "For secure usage, sender and receiver should agree on a fixed value for the nonce." but I'm still able to create an IES cipher with a null nonce. 

For reference I'm only using this cipher locally. A user generates a key pair, encrypts data with the public key and decrypts it with the private key. There is no key exchange in my application. 

Is it actually insecure to initialise a cipher with a null nonce value and if not, why not allow default parameters for IES cipher again to better support the JCA interface? If it is insecure maybe you should throw an exception if a user passes a null nonce?

**Comment by SamAmco** [comment]
Perhaps you could tell me what security properties/vulnerabilities IESCipher has when used without a nonce? Looking at the code it looks like you generate a random number and implement a stream based cipher. I'm curious why this is not considered a reasonable default/fallback implementation if the user does not provide IESParameterSpec?

**Comment by peterdettman** [comment]
For algorithms like ECIES (a.k.a ECIESwithSHA1) that don't involve a symmetric cipher, there is no nonce needed (in the code ivLength == 0), so it does appear that engineSpec == null (in engineInit) could still be supported in that case, and the original patch went a little too far.

The security vulnerability being addressed is that a randomly generated nonce has to be communicated to the receiver, and this introduces a malleability problem (nonce -> plaintext) unless that nonce is protected using an authentication mechanism; but we have no way to know whether that is present and so it is a bad idea to just generate such a random nonce as a default behaviour. A user can still choose to use a random nonce if they know it will be safe, but it appears the current recommendation is just to agree on a fixed nonce (if one is needed) to use across many operations (since each operation is using a new random key already).

That concern is clearly moot when no nonce is even needed, so IMO the original functionality should be partially restored for the no-nonce case.

**Comment by peterdettman** [comment]
I've now partially reversed the earlier fix so that a null engineSpec is acceptable if the specific IES algorithm does not require a nonce.

**Comment by SamAmco** [comment]
Sorry for the late reply. Thanks for taking a look.

**Comment by HuyenNguyenVan** [comment]
Hi SamAmco, Have you fixed this problem yet? , if yes, please tell my your solution to fix it, I'm facing that problem

**Comment by SamAmco** [comment]
@HuyenNguyenVan I can confirm that I am now able to initialize an ECIES cipher with no parameter spec yes. I'm not sure what issue you're facing specifically. 

You can see my code here: 

https://github.com/SamAmco/MEND4/blob/master/core-mend/src/main/java/co/samco/mend4/core/crypto/impl/DefaultJCECryptoProvider.kt

Specifically the function: 

``` kotlin
    private fun getAsymmetricEncryptCipher(): Cipher {
        val cipherTransform = settings.getValue(Settings.Name.ASYMMETRIC_CIPHER_TRANSFORM)
            ?: throw NoSuchSettingException(Settings.Name.ASYMMETRIC_CIPHER_TRANSFORM)
        val cipher = Cipher.getInstance(cipherTransform)
        assertValidAsymmetricCipher(cipherTransform)
        cipher.init(Cipher.ENCRYPT_MODE, getPublicKey())
        return cipher
    }
```

Where it is possible for the asymmetric cipher transform to be "ECIES". I appreciate the above fix as it keeps this code more generic and doesn't require special case code depending on the asymmetric cipher transform provided.
