### ISSUE TITLE
How build bc-java?

### ISSUE THREAD

**Issue by johnshajiang** [bcgit/bc-java#1462]
Use the master codes, and run the below command,
```
./gradlew clean build
```
but it cannot find or load the main class `org.gradle.wrapper.GradleWrapperMain`.
It looked no gradle-wrapper jar.

I looked through `gradlew` scripts and found variable `APP_HOME`.
What is that variable? What value should I set?

**Comment by johnshajiang** [comment]
I just installed `Ant` and run the below command,
```
sh build1-5to1-8
```
it worked.

However, just out of curiosity,  could I use `Gradle` for buidling BC?

**Comment by winfriedgerlach** [comment]
Yes, this is explained in detail in the [README.md](https://github.com/bcgit/bc-java/?tab=readme-ov-file#building-overview).

**Comment by winfriedgerlach** [comment]
Yes, this is explained in detail in the [README.md](https://github.com/bcgit/bc-java/?tab=readme-ov-file#building-overview).
