### ISSUE TITLE
Problem using RSA/NONE/OAEPWithSHA512AndMGF1Padding in the pod OS is Alpine Linux

### ISSUE THREAD

**Issue by dimsh7** [bcgit/bc-java#1465]
Hi,

I tried to init Cipher object for preforming data encrypt with next code:
```
Cipher encryptCipher = Cipher.getInstance("RSA/NONE/OAEPWithSHA512AndMGF1Padding", "BCFIPS");
encryptCipher.init(Cipher.ENCRYPT_MODE, publicKey);
encryptCipher.doFinal(secretMessageBytes);
```
When I run this code on Windows machine - everything work fine.
When I run this code  in the pod OS is Alpine Linux (Kernel version 5.10.179-168.710.amzn2.x86_64) I got the next error:

```
Error: java.security.InvalidParameterException: Cipher available for WRAP_MODE and UNWRAP_MODE only (inside  Cipher.getInstance method).
```

I tried to add too
```
EntropySourceProvider entSource = new BasicEntropySourceProvider(new SecureRandom(), true);
		FipsDRBG.Builder drgbBldr = FipsDRBG.SHA512.fromEntropySource(entSource)
				.setSecurityStrength(256)
				.setEntropyBitsRequired(256);
		CryptoServicesRegistrar.setSecureRandom(
				drgbBldr.build(Strings.toByteArray("number only used once"), true));
```

If I use "BC" provider (not fips) - works fine.

Is Cipher object not suits for my purpose in BC-FIPS? What should I do?
Thank in advance.

**Comment by dghgit** [comment]
FIPS does not support the use of RSA, even in OAEP mode, for wrapping arbitrary messages. It's secret keys only.
