### ISSUE TITLE
org.bouncycastle.jcajce.provider.asymmetric.edec.SignatureSpi should throw InvalidKeyException

### ISSUE THREAD

**Issue by pvandenbroucke** [bcgit/bc-java#1473]
Hello,

While testing, we observed that class org.bouncycastle.jcajce.provider.asymmetric.edec.SignatureSpi throws IllegalStateException instead of specified InvalidKeyException (from the Java SignatureSpi definition).

That could cause troubles if this exception is not explicitly managed by tier code.

Regards,

Pierrick

**Comment by dghgit** [comment]
Thanks for the report. This is now changed to InvalidKeyException.
