### ISSUE TITLE
Some potential may exist whitin this project

### ISSUE THREAD

**Issue by 0neand0nly** [bcgit/bc-java#1476]
Thanks for replying previous issue report it had been a great help.

While I was developing my projects additional potential vulnerabilities has been detected within this project.
So I was wondering if you could look into this issue as my prior knowledge is very limited on this subject.

The suspicious files are
1. [MD5Digest.java](https://github.com/bcgit/bc-java/blob/main/core/src/main/java/org/bouncycastle/crypto/digests/MD5Digest.java) : CWE-916: Use of Password Hash With Insufficient Computational Effort ( The MD5 hash (used in org.bouncycastle.crypto.digests.MD5Digest) is insecure. Consider changing it to a secure hash algorithm )

2. [Dump.java](https://github.com/bcgit/bc-java/blob/main/core/src/main/java/org/bouncycastle/asn1/util/Dump.java) : CWE-23:Path Traversal (Unsanitized input from a command line argument flows into java.io.FileInputStream, where it is used as a path. This may result in a Path Traversal vulnerability and allow an attacker to read arbitrary files.)

Best Regards

**Comment by dghgit** [comment]
So both these are okay (MD5Digest is the actual MD5 digest implementation, it's not just a password hash, it's still used in some places like TLS), but looking at it I am inclined to drop Dump.java - it's a wrapper calling the ASN1Dump class - as it doesn't really need to be there, we've got a few utility classes like that spread through the API now, it's probably time to move them all into a single executable style jar.

**Comment by dghgit** [comment]
No further comment.
