### ISSUE TITLE
Is salting being applied in this file?

### ISSUE THREAD

**Issue by 0neand0nly** [bcgit/bc-java#1477]
Hello again!

[Ed25519ctxSigner.java](https://github.com/bcgit/bc-java/blob/main/core/src/main/java/org/bouncycastle/crypto/signers/Ed25519ctxSigner.java)

In the buffer class, the reset() method appears to be utilized for clearing buffers. However, shouldn't there be a requirement for salting to ensure the buffer is cleared adequately?

**Comment by dghgit** [comment]
No. The contents of buffer represent the message being signed or verified, aside from the issues around properly erasing memory (at least on the first time) in a multi-threaded environment, the message is not a critical security parameter of the algorithm.
