### ISSUE TITLE
Fatal alert should terminate DTLS connection

### ISSUE THREAD

**Issue by sscheck** [bcgit/bc-java#148]
RFC 4346 - 7.2.2. Error Alerts

> Error handling in the TLS Handshake protocol is very simple.  When an
> error is detected, the detecting party sends a message to the other
> party.  Upon transmission or receipt of a fatal alert message, both
> parties immediately close the connection.  Servers and clients MUST
> forget any session-identifiers, keys, and secrets associated with a
> failed connection.  Thus, any connection terminated with a fatal
> alert MUST NOT be resumed.

However, in DTLSRecordLayer.java receive() method:

```
            switch (type)
            {
            case ContentType.alert:
            {
                if (plaintext.length == 2)
                {
                    short alertLevel = plaintext[0];
                    short alertDescription = plaintext[1];

                    peer.notifyAlertReceived(alertLevel, alertDescription);

                    if (alertLevel == AlertLevel.fatal)
                    {
                        fail(alertDescription);
                        throw new TlsFatalAlert(alertDescription);
                    }

                    // TODO Can close_notify be a fatal alert?
                    if (alertDescription == AlertDescription.close_notify)
                    {
                        closeTransport();
                    }
                }

                continue;
            }
```

The call to fail() tries to send an alert back to the peer before calling closeTransport(). I think in the case of a generic fatal alert, it should just call closeTransport() immediately and clean up whatever other session state remains. I think it's only the special case of close_notify that needs a special "close handshake" as described in section 7.2.1.

**Comment by peterdettman** [comment]
The echoing of the peer's fatal alert has now been removed. If there was a separate component of this issue relating to the connection not terminating, I think it's covered by #158.
