### ISSUE TITLE
bc-fips compatible with bouncycastle 1.75 and above for ANS.1 core packages ?

### ISSUE THREAD

**Issue by whymaomao** [bcgit/bc-java#1483]
we have a project using bc-fips and bouncycastle lib both. We are using the same code but switching the lib in classpath according to customer's choice. 

The issue happens when we are upgrading bouncycastle lib to 1.75, which has cleaned up all the ASN.1 core packages. Since BC-FIPS lib didn't removed this ASN.1 core functions. So we have troubles to use the same code for both BC-fips and non-fips library. 

e.g: 
`public static String testGeneralName() {

        ASN1EncodableVector otherName = new ASN1EncodableVector();

        otherName.add(new ASN1ObjectIdentifier("1.3.6.1.4.1.311.20.2.3"));

        otherName.add(new DERTaggedObject(true, 0, new DERUTF8String( "devuser@dvam.local")));

        ASN1Object genName = new DERTaggedObject(false, 0, new DERSequence(otherName));

        GeneralName name = GeneralName.getInstance(genName);

        try {

            DERSequence seq = (DERSequence) name.getName();

            ASN1ObjectIdentifier id = (ASN1ObjectIdentifier) seq.getObjectAt(0);

            DERTaggedObject obj = (DERTaggedObject) seq.getObjectAt(1);

            ASN1String string = (ASN1String) obj.getObject();

            return string.getString();

        } catch (ClassCastException ccex ){

            throw new IllegalArgumentException( "Not a UPN X.509 general name? " + name, ccex );
        }
    }`

function: org.bouncycastle.asn1.ASN1TaggedObject#getObject has been removed in BouncyCastle 1.75. But BC-fips would still use it to extract a tagged object. I cannot find any alternatives to extract the tagged object using the function both exists in BC-fips library and bouncy-castle library. 

Can anyone give me some suggestions on it ? 
Thanks

**Comment by peterdettman** [comment]
In this specific example you could use:

ASN1String string = (ASN1String)OtherName.getInstance(name.getName()).getValue();

In general though we don't claim any sort of drop-in compatibility between the FIPS and non-FIPS versions.

**Comment by whymaomao** [comment]
Got it. Thanks @peterdettman !
