### ISSUE TITLE
SignedMailValidatorException: cannot access org.bouncycastle.pkix.util.LocalizedException

### ISSUE THREAD

**Issue by shred** [bcgit/bc-java#1492]
I am using the `org.bouncycastle.mail.smime.validator.SignedMailValidator` class, which can throw a `org.bouncycastle.mail.smime.validator.SignedMailValidatorException` checked exception.

Starting with BC 1.74, I am getting this error when compiling my class:

```
java: cannot access org.bouncycastle.pkix.util.LocalizedException
  class file for org.bouncycastle.pkix.util.LocalizedException not found
```

`SignedMailValidatorException` is extending `LocalizedException`. In version 1.73 it was `org.bouncycastle.i18n.LocalizedException` though. It seems it was refactored to `org.bouncycastle.pkix.util.LocalizedException` in 1.74, but the PKIX `module-info` does not  export `org.bouncycastle.pkix.util`.

**Comment by dghgit** [comment]
Thanks for the report. Try the latest beta on https://www.bouncycastle.org/betas I think that should fix this.

**Comment by shred** [comment]
Yes, 177b11 fixes the issue. Thank you for the quick response!
