### ISSUE TITLE
Bcrypt Implementation in Bouncy Castle 1.76 Produces Identical Hashes for Different Passwords

### ISSUE THREAD

**Issue by cmedianu** [bcgit/bc-java#1496]
Using

    <dependency>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bcprov-ext-jdk15to18</artifactId>
        <version>1.76</version>
    </dependency>

Running this code:

import org.bouncycastle.crypto.generators.BCrypt;
import org.bouncycastle.util.encoders.Hex;

public class TestMain {

    public static void main(String[] args) {
        int workload = 10;

        byte[] salt = new byte[16];
        new java.security.SecureRandom().nextBytes(salt);

        String s = Hex.toHexString(BCrypt.generate("123".getBytes(),salt, workload));
        System.out.println(s);
        s = Hex.toHexString(BCrypt.generate("123123".getBytes(), salt, workload));
        System.out.println(s);
        s = Hex.toHexString(BCrypt.generate("123123123".getBytes(), salt, workload));
        System.out.println(s);
    }
}

outputs

d87b83a9892d5f60dcbeee68c127fc940b7d86f4f10f9ee9
d87b83a9892d5f60dcbeee68c127fc940b7d86f4f10f9ee9
d87b83a9892d5f60dcbeee68c127fc940b7d86f4f10f9ee9

so, if I use this as a password hash, and I set my password to 123123123, I can also log on with 123....

Is this normal? Other implementation of bcrypt does not do this.

**Comment by dghgit** [comment]
You need to use BCrypt.passwordToByteArray("123".toCharArray()) not .getBytes(), bcrypt requires the byte array to be padded with zeros as it's expecting C strings. This is documented in the JavaDoc.

**Comment by cmedianu** [comment]
Thanks for getting back to me. 

It may be helpful to have a more high level function that takes a string and returns $2y$05..... and a similar one for checking the passwords.

**Comment by dghgit** [comment]
Happy to look at a suggestion - it's a bit of an odd one, we use UTF-8 for encoding characters for our passwordToByteArray, not everyone does though.

**Comment by Marcono1234** [comment]
> It may be helpful to have a more high level function that takes a string and returns $2y$05..... and a similar one for checking the passwords.

This functionality is provided by `org.bouncycastle.crypto.generators.OpenBSDBCrypt`, isn't it?

For future reference, it looks like the same issue here for `BCrypt#generate` had been reported as #393 before.
