### ISSUE TITLE
Jython and external security providers (such as BouncyCastle)

### ISSUE THREAD

**Issue by maaaaz** [bcgit/bc-java#150]
Hello dear BouncyCastle team,

I'm cross-posting [here](https://github.com/jythontools/jython/issues/43) an issue I opened on the Jython repo as you might have some ideas about it.
For information the mentioned ported Java code is [this one](https://github.com/maaaaz/weblogicpassworddecryptor/blob/master/weblogicpassworddecryptor.jy).

Cheers.

**Comment by bcgit** [comment]
No sorry. This relates to the JCE provider validation used by the JVM. It's right out of our sphere of influence.

**Comment by maaaaz** [comment]
Ok, thanks for looking at it.
Where do you think I could get some information ? (mailing list, github repos etc.).

Cheers.
