### ISSUE TITLE
CVCertificate incorrectly returns issue date instead of expire date

### ISSUE THREAD

**Issue by Burtsev-Alexey** [bcgit/bc-java#1503]
https://github.com/bcgit/bc-java/blob/e007cbe82622e2f3d2ba0c46cceab7d504d4cf9b/util/src/main/java/org/bouncycastle/asn1/eac/CertificateBody.java#L358C50-L358C50
BC version 1.76
![2023-10-10_08-22-45](https://github.com/bcgit/bc-java/assets/957102/a3fe4e09-47db-4f25-b128-8f4710e44f78)

**Comment by peterdettman** [comment]
Thanks, fixed the reference to `certificateExpirationDate` .

**Comment by Burtsev-Alexey** [comment]
> Thanks, fixed the reference to `certificateExpirationDate` .

When this fixed will be released? It's pretty critical

**Comment by dghgit** [comment]
1.77 is out in the next few days. This is also available now in the current beta at https://www.bouncycastle.org/betas
