### ISSUE TITLE
bcprov-jdk15on-1.69.jar library vulnerability

### ISSUE THREAD

**Issue by PriyatamaB** [bcgit/bc-java#1505]
Hi Team,

We found new vulnerability introduced in bcprov-jdk15on-1.69 library, so we need to get rid of it.

<img width="979" alt="Screenshot 2023-10-11 at 3 48 08 PM" src="https://github.com/bcgit/bc-java/assets/20452358/333353c2-e74a-47b2-8fb0-7f9d1cc668c5">

<img width="1310" alt="Screenshot 2023-10-11 at 3 49 26 PM" src="https://github.com/bcgit/bc-java/assets/20452358/fb46cbd0-94a7-44a4-95d8-f7fe263cd674">

Can any one please confirm, by when bcprov-jdk15on will release next non-vulnerable version?
Thanks.

**Comment by dghgit** [comment]
Hi, this was fixed in 1.74. You need to migrate to a more recent release.
