### ISSUE TITLE
bcprov-jdk15to18-1.69.jar library vulnerability

### ISSUE THREAD

**Issue by PriyatamaB** [bcgit/bc-java#1507]
Hi Team,

We found new vulnerability introduced in bcprov-jdk15on-1.69 library, so we need to get rid of it.

<img width="982" alt="Screenshot 2023-10-13 at 2 09 33 PM" src="https://github.com/bcgit/bc-java/assets/20452358/c46b3967-6fbe-4403-becf-e94f3c1cf97e">
<img width="1307" alt="Screenshot 2023-10-13 at 2 09 51 PM" src="https://github.com/bcgit/bc-java/assets/20452358/9e7d60b2-ed59-4175-b353-c6aefd2e74f6">

We have checked all runtime and compile time dependency, however we could not find  bcprov-jdk15to18-1.69.jar and its dependency.
Also we tried to download and extract war from bamboo artifact and checked under path /WEB_INF/lib, but we didn’t find jar and its dependency there as well.
Can any one please help here ?
Thanks.

**Comment by dghgit** [comment]
Duplicate of #1505
