### ISSUE TITLE
Will you ever make a Python version of BouncyCastle ?

### ISSUE THREAD

**Issue by maaaaz** [bcgit/bc-java#151]
Hello dear team,

The problem is simple: really, there's [no great crypto lib in Python](https://cryptocoding.net/index.php/References#Libraries.2C_APIs.2C_and_toolkits). I don't mean to be rude to anyone or make waves but they all have **serious limitations**. If you need a short example: try to find a lib with PKCS12 version of PBKDF.

The question is simple (and I guess not brand new): will you ever **make a Python version of BouncyCastle** or at least provide bindings ?

Cheers!

**Comment by awbacker** [comment]
I highly doubt they would, but perhaps you could ask on a python group if you need something specific.  We use [PyCrypodome](https://pypi.python.org/pypi/pycryptodome), instead of pycrypto, if that helps.   Not sure what that list you link to is meant to demonstrate, too.

**Comment by maaaaz** [comment]
@awbacker: I really didn't know PyCryptodome, thanks for the heads-up.
And yes I wanted to show that, contrary to BC, there's no over-the-top crypto lib in one of the most popular language...

**Comment by peterdettman** [comment]
Basically no, but if there are changes we could make to ease the life of those providing bindings in other languages, let us know.
