### ISSUE TITLE
CSHAKEDigest clone constructor not marked public

### ISSUE THREAD

**Issue by chungy** [bcgit/bc-java#1512]
I have a program where I need to save and restore the state of a digest, and with standard SHAKE, everything goes swimmingly, but cSHAKE's clone constructor (`CSHAKEDigest(CSHAKEDigest source`) has no access modifier attached to it, so it cannot be used external of the package. Conversely, SHAKEDigest's clone constructor is marked `public` with a JavaDoc attached to it.

Is this an oversight or intentional design?

**Comment by dghgit** [comment]
I've checked this, pretty sure it's just oversight. Will fix.

**Comment by dghgit** [comment]
Fixed.
