### ISSUE TITLE
jar signature of bctls-fips.jar is expired

### ISSUE THREAD

**Issue by dmgping** [bcgit/bc-java#1514]
Downloading jars from https://mvnrepository.com/artifact/org.bouncycastle/bctls-fips and verifying the signature with:
`jarsigner -verify bctls-fips-1.0.16.jar` results in the following output:

```
jar verified.

Warning: 
**This jar contains entries whose signer certificate has expired.** 
This jar contains entries whose certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
The SHA1withDSA signature algorithm is considered a security risk. This algorithm will be disabled in a future update.
The SHA-1 timestamp digest algorithm is considered a security risk. This algorithm will be disabled in a future update.
The DSA signing key has a keysize of 1024 which is considered a security risk. This key size will be disabled in a future update.

Re-run with the -verbose and -certs options for more details.

**The signer certificate expired on 2020-04-25**. However, the JAR will be valid until the timestamp expires on 2031-11-09.
```

It appears the certificate used for jarsigning has expired. 

Can this certificate be replaced with a valid cert and the package be re-released to resolve the warning?

**Comment by dghgit** [comment]
There's two signatures. One of them is valid for recent JVMs, the expired one is required to get the jar to work with older JVMs.

**Comment by dmgping** [comment]
Thanks @dghgit, will the expired cert signature be updated then or is it a known issue?

**Comment by dghgit** [comment]
Certs for that key are no longer issued - the original cert in the old JVMs has expired at this stage as well, so it's a known issue.

**Comment by dmgping** [comment]
Ok thanks for the info - closing issue.
