### ISSUE TITLE
bctls-fips is not reporting CertPathBuilderException on self-signed certificate validation failure

### ISSUE THREAD

**Issue by tpapoyan2** [bcgit/bc-java#1519]
https://github.com/bcgit/bc-java/blob/1cae5431b0f315e1c7dc40392bcd60cf785831b4/tls/src/main/java/org/bouncycastle/jsse/provider/ProvX509TrustManager.java#L318C46-L318C46

Bouncy castle stopped reporting CertPathBuilderException-s after switching from bctl-fips 1.0.12.3 -> 1.0.12.4. On untrusted certificate it throws CertificateException with no cause specified. Here is a exception captured from intellij:

```
ex = {CertificateException@18303} "java.security.cert.CertificateException: No issuer certificate for certificate in certification path found."
 backtrace = {Object[5]@18312} 
 detailMessage = "No issuer certificate for certificate in certification path found."
 cause = null
 stackTrace = {StackTraceElement[34]@18317} 
  0 = {StackTraceElement@18541} "org.bouncycastle.jsse.provider.ProvX509TrustManager.validateChain(ProvX509TrustManager.java:318)"
  1 = {StackTraceElement@18542} "org.bouncycastle.jsse.provider.ProvX509TrustManager.checkTrusted(ProvX509TrustManager.java:273)"
  2 = {StackTraceElement@18543} "org.bouncycastle.jsse.provider.ProvX509TrustManager.checkServerTrusted(ProvX509TrustManager.java:176)"
  3 = {StackTraceElement@18544} "org.bouncycastle.jsse.provider.ExportX509TrustManager_7.checkServerTrusted(ExportX509TrustManager_7.java:49)"
  4 = {StackTraceElement@18545} "com.test.CustomTrustManager.validate(CustomTrustManager.java:445)"
  5 = {StackTraceElement@18546} "com.test.CustomTrustManager.checkServerTrusted(CustomTrustManager.java:161)"
  6 = {StackTraceElement@18547} "org.bouncycastle.jsse.provider.ImportX509TrustManager_5.checkServerTrusted(ImportX509TrustManager_5.java:71)"
  7 = {StackTraceElement@18548} "org.bouncycastle.jsse.provider.ProvSSLSocketWrap.checkServerTrusted(ProvSSLSocketWrap.java:127)"
  8 = {StackTraceElement@18549} "org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(ProvTlsClient.java:360)"
  9 = {StackTraceElement@18550} "org.bouncycastle.tls.TlsUtils.processServerCertificate(TlsUtils.java:4834)"
  10 = {StackTraceElement@18551} "org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(TlsClientProtocol.java:797)"
  11 = {StackTraceElement@18552} "org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(TlsClientProtocol.java:687)"
  12 = {StackTraceElement@18553} "org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:711)"
  13 = {StackTraceElement@18554} "org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:587)"
  14 = {StackTraceElement@18555} "org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:245)"
  15 = {StackTraceElement@18556} "org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:875)"
  16 = {StackTraceElement@18557} "org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:422)"
  17 = {StackTraceElement@18558} "org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:88)"
  18 = {StackTraceElement@18559} "org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:620)"
  19 = {StackTraceElement@18560} "org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:596)"
  20 = {StackTraceElement@18561} "java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)"
  21 = {StackTraceElement@18562} "java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)"
  22 = {StackTraceElement@18563} "java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)"
  ...
 depth = 34
 suppressedExceptions = {Collections$EmptyList@18315}  size = 0
```

Certificate at the endpoint is self-signed. We have a logic built on assumption that in case of self-signed cert we'll be receiving CertificateException with non-null cause of type CertPathBuilderException

**Comment by peterdettman** [comment]
I can see that this changed originally here: https://github.com/bcgit/bc-java/commit/52d11252fa0c3aa397974099b397eb78d36c7f6e .

I don't really like catching the CertPathBuilderException specially there and may update that. However it's not really a good idea to depend on the specific exception to (try to) interpret what specifically is wrong with the certificate (chain). Note that BCJSSE calls out to a CertPathBuilder instance via the provider mechanism, and there isn't a standard for exception types and/or messages.

Note that the current latest bctls-fips jar is v1.0.17, and on a sidenote, based on the stack trace I would suggest that CustomTrustManager implement X509ExtendedTrustManager instead of only X509TrustManager.

**Comment by tpapoyan2** [comment]
> However it's not really a good idea to depend on the specific exception to (try to) interpret what specifically is wrong with the certificate (chain)

Our use case requires us to identify when endpoint cert untrusted (self-signed or signed by untrusted authority) and delegate decision to the user (by showing dialogue with accept/reject options). Implementation of so called trust on first use pattern. So far catching CertPathBuilderException worked for us. What alternative would you suggest?

> current latest bctls-fips jar is v1.0.17, and on a sidenote, based on the stack trace I would suggest that CustomTrustManager implement X509ExtendedTrustManager instead of only X509TrustManager

Noted. I just wanted to point out exact version when this change occurred.

**Comment by peterdettman** [comment]
It will always be unreliable (in the general case) to use the exception itself to determine whether it is an untrusted certificate issue.

Instead I suggest that when checkServerTrusted fails, you could immediately retry - but with the endpoint cert included in trusted certs. Do this _before_ prompting the user. If the retry also fails then it's not a trust issue and there's no point prompting. If the retry succeeds, _then_ prompt the user to decide whether to lock in the change.

**Comment by tpapoyan2** [comment]
Thanks. I ended up comparing endpoint chain certs with the ones in our truststore. If there is no match it means leaf cert is unknown and we delegate to the user.
