### ISSUE TITLE
[ASN.1] No support for writing PRIVATE tag

### ISSUE THREAD

**Issue by swalendzik** [bcgit/bc-java#153]
PRIVATE tags are are mapped into DERApplicationSpecific object so write ASN.1 bytes are differen

example
i have ASN.1 : C00474657374 
`ByteArrayInputStream asnPrivateTag = new ByteArrayInputStream(Hex.decode("C00474657374"));`
`ASN1Primitive asn1Primitive = new ASN1InputStream(asnPrivateTag).readObject();`
`ByteArrayOutputStream outputAsn = new ByteArrayOutputStream();`
`new ASN1OutputStream(outputAsn).writeObject(asn1Primitive);`
After write to output stream i got ASN.1 : 400474657374

**Comment by avin98** [comment]
Whats the workaround for this ?

**Comment by swalendzik** [comment]
You can create DERApplicationSpecific with tag number - 64

example
``
ByteArrayInputStream asnPrivateTag = new ByteArrayInputStream(Hex.decode("C00474657374"));
DERApplicationSpecific asn1Primitive = new ASN1InputStream(asnPrivateTag).readObject();
ByteArrayOutputStream outputAsn = new ByteArrayOutputStream();

DERApplicationSpecific privateTag = new DERApplicationSpecific(asn1Primitive.isConstructed(), asn1Primitive.getApplicationTag() - 64, asn1Primitive.getContents())
new ASN1OutputStream(outputAsn).writeObject(asn1Primitive);
``

**Comment by amannm** [comment]
Yes I was curious why the library was missing this class. The "workaround" seems to work for writing, but it would be better to have an explicit class for private tags coming in.

**Comment by dghgit** [comment]
I've merged 959 with a few corrections. Marking this one as now resolved.
