### ISSUE TITLE
BouncyCastle Java 1.70 Vulnerabilities, No Fix Available

### ISSUE THREAD

**Issue by JimLynchCodes** [bcgit/bc-java#1542]
Hi, I am working on a spring boot java project and ran a scan with raven cli tool to see if my packages had any vulnerabilities.

The scan found two vulnerabilities in Bouncy Castle with no fix available...

- org.bouncycastle:bcprov-jdk15on - 1.70 - Information Exposure - V4 - NotAvailable - https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-5771339

- org.bouncycastle:bcprov-jdk15on - 1.70 - Uncontrolled Resource Consumption ('Resource Exhaustion') - V4 - NotAvailable - https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6084022

Just wondering if anyone has any recommendations on what I should do here in this situation...  🤔

Thanks!

**Comment by meridsa** [comment]
Hi, you should if possible be migrating to bcprov-jdk18on, that has versions above 1.70.

See [bouncycastle latest releases for more information](https://www.bouncycastle.org/latest_releases.html)
