### ISSUE TITLE
Is there a version of bc-fips certified for FIPS 140-3 available on Maven? 

### ISSUE THREAD

**Issue by praneethsf** [bcgit/bc-java#1544]
As per https://www.bouncycastle.org/fips_java_roadmap.html, bc-fips-2.0.0 and bc-fips-1.0.3 will be certified under FIPS 140-3. 
What would be the timeline for their availability on Maven?

**Comment by dghgit** [comment]
1.0.3 is currently suspended. 2.0.0 is available for early access and will be made available on Maven when it's finally certified.

As to when that happens, 2.0.0 was submitted in Jan 2022. So we're expecting it to be done "soon", but when "soon" will be is a matter for the certifying authority, we have no say or control over that.

**Comment by larrywest** [comment]
@dghgit Has that 2.0.0 submission since been amended to include Java (OpenJDK) 21?

🤞

**Comment by dghgit** [comment]
Yes. The ACVP certificate for 2.0.0 is here:

https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?validation=37009

**Comment by dghgit** [comment]
It's here.

https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4743

**Comment by stanpalatnik** [comment]
@dghgit Just following up, is 1.0.3 still suspended or this there a plan to move it forward?
