### ISSUE TITLE
DRBG default implementation ist not the default anymore since BC 1.74

### ISSUE THREAD

**Issue by problemzebra2** [bcgit/bc-java#1549]
The DRBG `DEFAULT` implementation ist not the default anymore since BC 1.74. Instead `NONCEANDIV` is used.

I guess that this change is responsible for this behaviour:

`getService("SecureRandom", "DEFAULT");`

in `BouncyCastleProvider.setup()`.

The following code snippet returns "NONCEANDIV BC":
```
BouncyCastleProvider bouncyCastleProvider = new BouncyCastleProvider();
Security.insertProviderAt(bouncyCastleProvider, 1);
SecureRandom sr = new SecureRandom();
System.out.println(sr.getAlgorithm() + " " + sr.getProvider().getName());
```

Additionally [JDK-8276660](https://bugs.openjdk.org/browse/JDK-8276660) in JDK 18+ almost fixes this issue since both DRBG implementations are avaible again but  `NONCEANDIV` ist still used because it is at postion 0 (see `Provider.getDefaultSecureRandomService`):

![grafik](https://github.com/bcgit/bc-java/assets/46046993/7a420d23-5535-4588-b33d-16c03dc42232)

**Comment by dghgit** [comment]
Fixed in 1.78.
