### ISSUE TITLE
IllegalArgumentException in org.bouncycastle.asn1.ocsp.CertStatus when the OCSP response has unknown status (2)

### ISSUE THREAD

**Issue by jhyoty** [bcgit/bc-java#155]
Applies to version 1.55, 1.54 works. If the OCSP response status is "unknown" (2), creating a CertStatus from a ASN1TaggedObject fails with an IllegalArgumentException: "Unknown tag encountered: 2".

It seems that there is a bug in version 1.55 [CertStatus.java](https://github.com/bcgit/bc-java/blob/r1rv55/core/src/main/java/org/bouncycastle/asn1/ocsp/CertStatus.java#L56) around line 56: a missing break statement causes the case to fall through.

**Comment by bcgit** [comment]
Thanks, now fixed.
