### ISSUE TITLE
How does jdk17 need to introduce bc-fips 1.0.2.4

### ISSUE THREAD

**Issue by BoWu3** [bcgit/bc-java#1550]
Originally, bc-fips was placed under jdk 1.8 /jre/lib/ext, and now jdk17 does not have this directory, how to operate it?

**Comment by larrywest** [comment]
You'll find relevant info in [JEP 220](https://openjdk.org/jeps/220) ("Jigsaw" ≈ modules), which was implemented in Java 9, but I think the general answer is that 3rd-party libraries, like bc-fips, are expected to be found in the classpath: for example declared as a dependency in Maven or Gradle.
