### ISSUE TITLE
sntrup761 prime sharedKeyBytes value not correct?

### ISSUE THREAD

**Issue by norrisjeremy** [bcgit/bc-java#1554]
I am a co-maintainer of [JSch](https://github.com/mwiede/jsch) & recently I began working on integrating support for the [sntrup761x25519-sha512@openssh.com](https://datatracker.ietf.org/doc/draft-josefsson-ntruprime-ssh/) KEX algorithm using Bouncy Castle's SNTRUPrime implementation.

However, I have hit a roadblock, as it appears the `sntrup761` sharedKeyBytes value is defined as 16 bytes, as seen at https://github.com/bcgit/bc-java/blob/1cae5431b0f315e1c7dc40392bcd60cf785831b4/core/src/main/java/org/bouncycastle/pqc/crypto/ntruprime/SNTRUPrimeParameters.java#L13-L14

This differs from OpenSSH's implementation, which defines it as 32 bytes, as seen at https://github.com/openssh/openssh-portable/blob/8241b9c0529228b4b86d88b1a6076fb9f97e4a99/crypto_api.h#L45-L48

Is there a reason that Bouncy Castle defines the sharedKeyBytes value as 16 bytes instead of 32 bytes?
The [Open Quantum Safe](https://openquantumsafe.org/liboqs/algorithms/kem/ntruprime.html) site seems to also define the shared secret size as 32 bytes, agreeing with OpenSSH's definition?

**Comment by norrisjeremy** [comment]
FYI, using the following, the [sntrup761x25519-sha512@openssh.com](https://datatracker.ietf.org/doc/draft-josefsson-ntruprime-ssh/) I've authored for JSch works with OpenSSH:

```
  static SNTRUPrimeParameters sntrup761() {
    try {
      Constructor<SNTRUPrimeParameters> c =
          SNTRUPrimeParameters.class.getDeclaredConstructor(String.class, int.class, int.class,
              int.class, int.class, int.class, int.class, int.class, int.class);
      c.setAccessible(true);
      return c.newInstance("sntrup761", 761, 4591, 286, 1158, 1007, 1158, 1763, 32);
    } catch (Throwable t) {
      return null;
    }
  }
```

**Comment by dghgit** [comment]
Originally we restricted the size of the shared secret to the strength of the security properties as while the test vectors all used 256 bit values there was no guidance around whether this was actually going to happen in the final draft.

So the rule has since come down that it's always 256 bits regardless of the security strength. We have updated NTRU already to follow this, I'll do the same for NTRUPrime.

**Comment by norrisjeremy** [comment]
@dghgit,

Great, thank you for the update!

Thanks,
Jeremy

**Comment by dghgit** [comment]
I've deployed a new beta with the changes now as well - you'll find it at https://www.bouncycastle.org/betas The change is in beta 178b03 or later.

**Comment by norrisjeremy** [comment]
HI @dghgit,

I've tested with the 178b03 beta and can confirm it works with OpenSSH, thanks!

Thanks,
Jeremy
