### ISSUE TITLE
X500NameTokenizer does not parse certificates containing DN with escaped quotes

### ISSUE THREAD

**Issue by erdbeerschnitzel** [bcgit/bc-java#1556]
I guess, due to this code https://github.com/bcgit/bc-java/blob/8ca7bbd856c4077af0150070a9191d47c63f964e/core/src/main/java/org/bouncycastle/asn1/x500/style/X500NameTokenizer.java#L61 a certificate with a DN containing escaped quotes can't be parsed correctly.

Example DN (part of it): Wohnungsbaugenossenschaft "Humboldt-Universität" eG
openssl output: Subject: C = DE, L = Berlin, O = Wohnungsbaugenossenschaft \"Humboldt-Universit\C3\A4t\" eG, CN = transfer.wbg-hub.de

Have a look at the certificate of this website to see an example: https://transfer.wbg-hub.de/intro.xhtml ( [transfer-wbg-hub-de.zip](https://github.com/bcgit/bc-java/files/13778528/transfer-wbg-hub-de.zip) )

I can't find a RFC reference which does not allow quotes in the DN.

**Comment by dghgit** [comment]
C=DE,L=Berlin,O=Wohnungsbaugenossenschaft \"Humboldt-Universität\" eG,CN=transfer.wbg-hub.de

will parse. This is in accordance with https://www.rfc-editor.org/rfc/rfc1779.html

**Comment by dghgit** [comment]
Appears dead.
