### ISSUE TITLE
Jakarta 10 compatible Bouncy castle jar

### ISSUE THREAD

**Issue by khusi1251** [bcgit/bc-java#1559]
Hi All,

we are upgrading our product from javax to Jakarta 10 and We are looking for jakarta 10 compatible BouncyCastle jars to meets our need.  do we have Jakarta compatible bouncy castle jars available, if yes than where can we get those jars?
Please let us know if you need more info with regards to this issue?

Thanks,
Khushboo

**Comment by khusi1251** [comment]
Hi Team,

Any update with regards to this case? This is quite urgent for our product upgrade?

Thanks,
Khushboo

**Comment by dghgit** [comment]
Inactive.
