### ISSUE TITLE
Question: Are bouncycastle versions backward compatible?

### ISSUE THREAD

**Issue by adnsimona** [bcgit/bc-java#1561]
Our project uses multiple bouncycastle versions got from different libraries transitively.
Is it possible to replace jdk15on:1.62, jdk15on:1.67, jdk15on:1.70 and jdk15to18:1.75 with jdk18on:1.77 for a Java 17 Spring Boot application without issue?

**Comment by adnsimona** [comment]
I don't mean it backward compatible, like with JDK, but in business logic. (It would run on JDK 17, so I guess all of them are running on it)

**Comment by dghgit** [comment]
It depends a lot on how they are being used as to whether you'd have issues. I would certainly not recommend using multiple versions like this, if only because it will become quite difficult to deal with any vulnerability reports.

**Comment by dghgit** [comment]
Appears dead.
