### ISSUE TITLE
Inconsistency of ECIES-KEM SingleHashMode with respect to ISO/IEC 18033-2

### ISSUE THREAD

**Issue by cygnusv** [bcgit/bc-java#157]
There is an inconsistency in the semantics of the SingleHashMode parameter of ECIES-KEM with respect to the original ISO/IEC 18033-2 standard. 

In the standard, when this parameter is active ("SingleHashMode = 1"), the encryption and decryption procedures don't include the ephemeral public key (denoted by C_0 in the standard) as part of the input to the KDF. This parameter is set to 0 for improved security.

However, the behavior in the BC implementation is the opposite. When SingleHashMode is active ("SingleHashMode == true"), the ephemeral public key (denoted by C in the BC implementation) is inputed to the KDF. In addition, the default value when this parameter is not specified in the constructor is false, which is equivalent to "SingleHashMode = 1" in the standard. 

See:
https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/kems/ECIESKeyEncapsulation.java#L231

**Comment by bcgit** [comment]
I've fixed the check on the boolean - as this class is only used in the lightweight API I've left the default as false, as it's easy to swap in an "old style" one if required.
