### ISSUE TITLE
Bug during CV Certificate request signature validation.

### ISSUE THREAD

**Issue by Burtsev-Alexey** [bcgit/bc-java#1576]
We are using BC 1.77 to verify signature of CV certificate request like this:
`
//var value = some byte[]
var req = new EACCertificateRequestHolder(value);
var verifier = new JcaEACSignatureVerifierBuilder()...;
req.isInnerSignatureValid(verifier); //Exception here
`

java.lang.NullPointerException: Cannot invoke "org.bouncycastle.asn1.ASN1Primitive.encodeTo(java.io.OutputStream, String)" because the return value of "org.bouncycastle.asn1.ASN1Object.toASN1Primitive()" is null
        at org.bouncycastle.asn1.ASN1Object.getEncoded(ASN1Object.java:48) ~[bcprov-jdk18on-1.77.jar:1.77.00.0]
        at org.bouncycastle.eac.EACCertificateRequestHolder.isInnerSignatureValid(Unknown Source) ~[bcpkix-jdk18on-1.77.jar:1.77.00.0]

I checked BC source code, and I think the problem is in this code
https://github.com/bcgit/bc-java/blob/e007cbe82622e2f3d2ba0c46cceab7d504d4cf9b/util/src/main/java/org/bouncycastle/asn1/eac/CertificateBody.java#L262-L280

CertificateBody.certificateType is neither profileType neither requestType so function return null.
Its perfectly valid for it to be value 15 (dec) by BSI standart if request contains 1,2,4,8 fields
![image](https://github.com/bcgit/bc-java/assets/957102/983bb9c3-0964-4f94-8a69-f8e17b6330f4)

https://github.com/bcgit/bc-java/blob/e007cbe82622e2f3d2ba0c46cceab7d504d4cf9b/util/src/main/java/org/bouncycastle/asn1/eac/CertificateBody.java#L55-L61

**Comment by peterdettman** [comment]
Thanks for the report. I've updated CertificateBody to support optional Certification Authority Reference in a Certificate Request.

**Comment by Burtsev-Alexey** [comment]
> Thanks for the report. I've updated CertificateBody to support optional Certification Authority Reference in a Certificate Request.

Can you provide a link to fixed source code? Probably we will have to build fixed BC from source code, this is a blocking issue for us. This fixed isnt going to be released soon probably...

**Comment by peterdettman** [comment]
This is a mirror that takes a day or three to update. We've initiated a manual push this time so it should show up in an hour or so.

**Comment by cipherboy** [comment]
This is fixed in 45baaff8901a472ae787449084f57254c7776c9f.
