### ISSUE TITLE
Cannot generate BcPGPKeyPair for X448

### ISSUE THREAD

**Issue by hbs** [bcgit/bc-java#1584]
Attempting to do the following fails with a `ClassCastException` when BcPGKeyConverter wrongly assumes its input parameter not being `ECPrivateKeyParameters` means they are X25519.

```
X448KeyPairGenerator xkpg = new X448KeyPairGenerator();
xkpg.init(new KeyGenerationParameters(new SecureRandom(), 0));
BcPGPKeyPair kp = new BcPGPKeyPair(PublicKeyAlgorithmTags.ECDH, xkpg.generateKeyPair(), new Date());
```

**Comment by vanitasvitae** [comment]
I might have a patch for this issue :)

**Comment by vanitasvitae** [comment]
This is now fixed, though you should note that `X448` + `PublicKeyAlgorithmTags.ECDH` is not a valid combination according to the OpenPGP specification. GnuPG might be able to deal with such keys, but other implementations following the official spec might not.

Consider using `X448` + `PublicKeyAlgorithmTags.X448` instead (though GnuPG migh not support this combination -.-).
