### ISSUE TITLE
current main doesn't compile anymore

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#1588]
MacOS Sonoma 14.3.1, Azul JDK-21. `ant` build `bash ./build1-8+`

```
.  .  .
BUILD FAILED
/Users/ur20980/src/bc-java/ant/jdk18+.xml:123: The following error occurred while executing this line:
/Users/ur20980/src/bc-java/ant/bc+-build.xml:1375: /Users/ur20980/src/bc-java/build/artifacts/jdk1.8/bcmail-jdk18on-178/src does not exist.

```

Did you make a decision to kill normal builds (a user builds the JARs for a single JDK from the sources on her machine)?

**Update.** Needless to say, Gradle builds also fail, because nobody sane would keep **four** (mostly outdated) JDKs on their machine:
```
$ gradle build
.  .  .
Looking for JDK ENV 'BC_JDK8' found  null

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ur20980/src/bc-java/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'bc-java'.
> Looking for JDK ENV 'BC_JDK8' but found null, see README 'Environmental variables'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 14s
$
$ echo $BC_JDK21
/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home
$ 
```

**Comment by mouse07410** [comment]
@dghgit to make sure you see this.

**Comment by mwcw** [comment]
Is BC_JDK8 defined?

**Comment by dghgit** [comment]
I think the ant build is now working again - the reason for the failure was an issue with the JVMVersion test. The new build1-8+ script now uses a JAVA_VERSION_PREFIX environment variable. If not defined in the environment, by default it's set to 1.8, for later JVMs it will need to be set to the JVM in use.

This may provide a useful switch for modifying the ant scripts to correctly build for specific JVMs (as opposed to now, where it is always 1.8). I'll need to think about it...

**Comment by mouse07410** [comment]
> I think the ant build is now working again

Yes, thank you!! I confirm that the build is successful again (including tests passing) with JDK-21.

> This may provide a useful switch for modifying the ant scripts to correctly build for specific JVMs (as opposed to now, where it is always 1.8). I'll need to think about it...

I'm pretty sure it should be the case.

**Comment by zliucd** [comment]
I got same issue. After I locate ```JAVA_HOME``` to openjdk@21, it still reports ```Looking for JDK ENV 'BC_JDK8' but found null, see README 'Environmental variables' ```.         

Environment: OSX M1 Monterey

Also, I cannot download openjdk@8 via homebrew:
```
$brew install openjdk@8
openjdk@8: The x86_64 architecture is required for this software.
Error: openjdk@8: An unsatisfied requirement failed this build.
```

**Comment by mouse07410** [comment]
Set
```text
export JAVA_PREFIX_VERSION="21"
export BC_JDK21=/Library/Java/JavaVirtualMachines/<whatever your JDK is>/Contents/Home
```
prior to invoking the build script.
