### ISSUE TITLE
SExpParser fails with GnuPG ed25519 private keys

### ISSUE THREAD

**Issue by cstamas** [bcgit/bc-java#1590]
The SExpParser cannot partse GnuPG private keys if they are ed25519. 

Reason is trivial: this is how GnuPG stores them:
https://github.com/gpg/gnupg/blob/40227e42ea0f2f1cf9c9f506375446648df17e8d/common/t-ssh-utils.c#L179-L199
https://github.com/gpg/gnupg/blob/40227e42ea0f2f1cf9c9f506375446648df17e8d/agent/cvt-openpgp.c#L222-L243

And SExprParser always ends up here:
https://github.com/bcgit/bc-java/blob/bd6e70c7cad0a35fdcba055de13ef2e36f6a151b/pg/src/main/java/org/bouncycastle/gpg/SExprParser.java#L94

As it does not count for `(flags xxx)`.

**Comment by cipherboy** [comment]
Closing as this should be resolved by #1591 being closed; I _think_ this was fixed in d9412c3bf993c751466c8e98e3ca7743dac8a621 but I might be incorrect. Let us know if it doesn't work!
