### ISSUE TITLE
Unable to compile code in sources jars

### ISSUE THREAD

**Issue by jimshowalter** [bcgit/bc-java#1598]
We downloaded the 1.77 versions of org.bouncycastle:bcpg-jdk18on, org.bouncycastle:bcpkix-jdk18on, org.bouncycastle:bcprov-jdk18on, and org.bouncycastle:bcutil-jdk18on, unzipped them into a shared org.bouncycastle root, and tried to compile them in IntelliJ.

Methods and packages were missing.

Is this expected?

**Comment by jimshowalter** [comment]
.../src/main/java/org/bouncycastle/eac/EACCertificateHolder.java:8: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.CVCertificate;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateHolder.java:9: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.PublicKeyDataObject;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateHolder.java:14: error: cannot find symbol
    private CVCertificate cvCertificate;
            ^
  symbol:   class CVCertificate
  location: class EACCertificateHolder
.../src/main/java/org/bouncycastle/eac/EACCertificateHolder.java:16: error: cannot find symbol
    private static CVCertificate parseBytes(byte[] certEncoding)
                   ^
  symbol:   class CVCertificate
  location: class EACCertificateHolder
.../src/main/java/org/bouncycastle/eac/EACCertificateHolder.java:50: error: cannot find symbol
    public EACCertificateHolder(CVCertificate cvCertificate)
                                ^
  symbol:   class CVCertificate
  location: class EACCertificateHolder
.../src/main/java/org/bouncycastle/eac/EACCertificateHolder.java:60: error: cannot find symbol
    public CVCertificate toASN1Structure()
           ^
  symbol:   class CVCertificate
  location: class EACCertificateHolder
.../src/main/java/org/bouncycastle/eac/EACCertificateHolder.java:65: error: cannot find symbol
    public PublicKeyDataObject getPublicKeyDataObject()
           ^
  symbol:   class PublicKeyDataObject
  location: class EACCertificateHolder
.../src/main/java/org/bouncycastle/eac/jcajce/JcaPublicKeyConverter.java:20: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.EACObjectIdentifiers;
                                ^
.../src/main/java/org/bouncycastle/eac/jcajce/JcaPublicKeyConverter.java:21: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.ECDSAPublicKey;
                                ^
.../src/main/java/org/bouncycastle/eac/jcajce/JcaPublicKeyConverter.java:22: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.PublicKeyDataObject;
                                ^
.../src/main/java/org/bouncycastle/eac/jcajce/JcaPublicKeyConverter.java:23: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.RSAPublicKey;
                                ^
.../src/main/java/org/bouncycastle/eac/jcajce/JcaPublicKeyConverter.java:51: error: cannot find symbol
    public PublicKey getKey(PublicKeyDataObject publicKeyDataObject)
                            ^
  symbol:   class PublicKeyDataObject
  location: class JcaPublicKeyConverter
.../src/main/java/org/bouncycastle/eac/jcajce/JcaPublicKeyConverter.java:80: error: cannot find symbol
    private PublicKey getECPublicKeyPublicKey(ECDSAPublicKey key)
                                              ^
  symbol:   class ECDSAPublicKey
  location: class JcaPublicKeyConverter
.../src/main/java/org/bouncycastle/eac/jcajce/JcaPublicKeyConverter.java:104: error: cannot find symbol
    private java.security.spec.ECPoint getPublicPoint(ECDSAPublicKey key)
                                                      ^
  symbol:   class ECDSAPublicKey
  location: class JcaPublicKeyConverter
.../src/main/java/org/bouncycastle/eac/jcajce/JcaPublicKeyConverter.java:119: error: cannot find symbol
    private ECParameterSpec getParams(ECDSAPublicKey key)
                                      ^
  symbol:   class ECDSAPublicKey
  location: class JcaPublicKeyConverter
.../src/main/java/org/bouncycastle/eac/jcajce/JcaPublicKeyConverter.java:139: error: cannot find symbol
    public PublicKeyDataObject getPublicKeyDataObject(ASN1ObjectIdentifier usage, PublicKey publicKey)
           ^
  symbol:   class PublicKeyDataObject
  location: class JcaPublicKeyConverter
.../src/main/java/org/bouncycastle/eac/EACCertificateRequestHolder.java:8: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.CVCertificateRequest;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateRequestHolder.java:9: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.PublicKeyDataObject;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateRequestHolder.java:14: error: cannot find symbol
    private CVCertificateRequest request;
            ^
  symbol:   class CVCertificateRequest
  location: class EACCertificateRequestHolder
.../src/main/java/org/bouncycastle/eac/EACCertificateRequestHolder.java:16: error: cannot find symbol
    private static CVCertificateRequest parseBytes(byte[] requestEncoding)
                   ^
  symbol:   class CVCertificateRequest
  location: class EACCertificateRequestHolder
.../src/main/java/org/bouncycastle/eac/EACCertificateRequestHolder.java:50: error: cannot find symbol
    public EACCertificateRequestHolder(CVCertificateRequest request)
                                       ^
  symbol:   class CVCertificateRequest
  location: class EACCertificateRequestHolder
.../src/main/java/org/bouncycastle/eac/EACCertificateRequestHolder.java:60: error: cannot find symbol
    public CVCertificateRequest toASN1Structure()
           ^
  symbol:   class CVCertificateRequest
  location: class EACCertificateRequestHolder
.../src/main/java/org/bouncycastle/eac/EACCertificateRequestHolder.java:65: error: cannot find symbol
    public PublicKeyDataObject getPublicKeyDataObject()
           ^
  symbol:   class PublicKeyDataObject
  location: class EACCertificateRequestHolder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:10: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.CVCertificate;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:11: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.CertificateBody;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:12: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.CertificateHolderAuthorization;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:13: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.CertificateHolderReference;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:14: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.CertificationAuthorityReference;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:15: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.EACTags;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:16: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.PackedDate;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:17: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.PublicKeyDataObject;
                                ^
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:24: error: cannot find symbol
    private PublicKeyDataObject publicKey;
            ^
  symbol:   class PublicKeyDataObject
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:25: error: cannot find symbol
    private CertificateHolderAuthorization certificateHolderAuthorization;
            ^
  symbol:   class CertificateHolderAuthorization
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:26: error: cannot find symbol
    private PackedDate certificateEffectiveDate;
            ^
  symbol:   class PackedDate
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:27: error: cannot find symbol
    private PackedDate certificateExpirationDate;
            ^
  symbol:   class PackedDate
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:28: error: cannot find symbol
    private CertificateHolderReference certificateHolderReference;
            ^
  symbol:   class CertificateHolderReference
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:29: error: cannot find symbol
    private CertificationAuthorityReference certificationAuthorityReference;
            ^
  symbol:   class CertificationAuthorityReference
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:32: error: cannot find symbol
        CertificationAuthorityReference certificationAuthorityReference,
        ^
  symbol:   class CertificationAuthorityReference
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:33: error: cannot find symbol
        PublicKeyDataObject publicKey,
        ^
  symbol:   class PublicKeyDataObject
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:34: error: cannot find symbol
        CertificateHolderReference certificateHolderReference,
        ^
  symbol:   class CertificateHolderReference
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:35: error: cannot find symbol
        CertificateHolderAuthorization certificateHolderAuthorization,
        ^
  symbol:   class CertificateHolderAuthorization
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:36: error: cannot find symbol
        PackedDate certificateEffectiveDate,
        ^
  symbol:   class PackedDate
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:37: error: cannot find symbol
        PackedDate certificateExpirationDate)
        ^
  symbol:   class PackedDate
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/EACCertificateBuilder.java:47: error: cannot find symbol
    private CertificateBody buildBody()
            ^
  symbol:   class CertificateBody
  location: class EACCertificateBuilder
.../src/main/java/org/bouncycastle/eac/operator/jcajce/EACHelper.java:9: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.EACObjectIdentifiers;
                                ^
.../src/main/java/org/bouncycastle/eac/operator/jcajce/JcaEACSignerBuilder.java:19: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.EACObjectIdentifiers;
                                ^
.../src/main/java/org/bouncycastle/eac/operator/jcajce/JcaEACSignatureVerifierBuilder.java:18: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.EACObjectIdentifiers;
                                ^
.../src/main/java/org/bouncycastle/cmc/SimplePKIResponse.java:6: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.ContentInfo;
                                ^
.../src/main/java/org/bouncycastle/cms/CMSSignedData.java:25: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.ContentInfo;
                                ^
.../src/main/java/org/bouncycastle/cms/CMSSignedData.java:26: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.SignedData;
                                ^
.../src/main/java/org/bouncycastle/cms/CMSSignedData.java:27: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.SignerInfo;
                                ^
.../src/main/java/org/bouncycastle/cmc/SimplePKIResponse.java:26: error: cannot find symbol
    private static ContentInfo parseBytes(byte[] responseEncoding)
                   ^
  symbol:   class ContentInfo
  location: class SimplePKIResponse
.../src/main/java/org/bouncycastle/cmc/SimplePKIResponse.java:56: error: cannot find symbol
    public SimplePKIResponse(ContentInfo signedData)
                             ^
  symbol:   class ContentInfo
  location: class SimplePKIResponse
.../src/main/java/org/bouncycastle/cms/CMSSignedHelper.java:17: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.OtherRevocationInfoFormat;
                                ^
.../src/main/java/org/bouncycastle/cms/CMSSignedHelper.java:19: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.EACObjectIdentifiers;
                                ^
.../src/main/java/org/bouncycastle/operator/DefaultDigestAlgorithmIdentifierFinder.java:12: error: package org.bouncycastle.asn1.bsi does not exist
import org.bouncycastle.asn1.bsi.BSIObjectIdentifiers;
                                ^
.../src/main/java/org/bouncycastle/operator/DefaultDigestAlgorithmIdentifierFinder.java:13: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.CMSObjectIdentifiers;
                                ^
.../src/main/java/org/bouncycastle/operator/DefaultDigestAlgorithmIdentifierFinder.java:15: error: package org.bouncycastle.asn1.eac does not exist
import org.bouncycastle.asn1.eac.EACObjectIdentifiers;
                                ^
.../src/main/java/org/bouncycastle/cms/CMSSignedData.java:73: error: cannot find symbol
    SignedData signedData;
    ^
  symbol:   class SignedData
  location: class CMSSignedData
.../src/main/java/org/bouncycastle/cms/CMSSignedData.java:74: error: cannot find symbol
    ContentInfo contentInfo;
    ^
  symbol:   class ContentInfo
  location: class CMSSignedData
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:19: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.Attribute;
                                ^
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:20: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.AttributeTable;
                                ^
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:21: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.CMSAlgorithmProtection;
                                ^
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:22: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.CMSAttributes;
                                ^
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:23: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.IssuerAndSerialNumber;
                                ^
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:24: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.SignerIdentifier;
                                ^
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:25: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.SignerInfo;
                                ^
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:26: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.Time;
                                ^
.../src/main/java/org/bouncycastle/cms/CMSSignedData.java:144: error: cannot find symbol
        ContentInfo sigData)
        ^
  symbol:   class ContentInfo
  location: class CMSSignedData
.../src/main/java/org/bouncycastle/cms/CMSSignedData.java:179: error: cannot find symbol
        ContentInfo sigData)
        ^
  symbol:   class ContentInfo
  location: class CMSSignedData
.../src/main/java/org/bouncycastle/cms/CMSSignedData.java:188: error: cannot find symbol
        ContentInfo sigData)
        ^
  symbol:   class ContentInfo
  location: class CMSSignedData
.../src/main/java/org/bouncycastle/cms/CMSSignedData.java:217: error: cannot find symbol
    private SignedData getSignedData()
            ^
  symbol:   class SignedData
  location: class CMSSignedData
.../src/main/java/org/bouncycastle/cms/CMSSignedData.java:375: error: cannot find symbol
    public ContentInfo toASN1Structure()
           ^
  symbol:   class ContentInfo
  location: class CMSSignedData
.../src/main/java/org/bouncycastle/cert/selector/X509CertificateHolderSelector.java:6: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.IssuerAndSerialNumber;
                                ^
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:51: error: cannot find symbol
    private AttributeTable signedAttributeValues;
            ^
  symbol:   class AttributeTable
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:52: error: cannot find symbol
    private AttributeTable unsignedAttributeValues;
            ^
  symbol:   class AttributeTable
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:55: error: cannot find symbol
    protected final SignerInfo info;
                    ^
  symbol:   class SignerInfo
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:62: error: cannot find symbol
        SignerInfo info,
        ^
  symbol:   class SignerInfo
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:116: error: cannot find symbol
    protected SignerInformation(SignerInformation baseInfo, SignerInfo info)
                                                            ^
  symbol:   class SignerInfo
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:237: error: cannot find symbol
    public AttributeTable getSignedAttributes()
           ^
  symbol:   class AttributeTable
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:251: error: cannot find symbol
    public AttributeTable getUnsignedAttributes()
           ^
  symbol:   class AttributeTable
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:561: error: cannot find symbol
    private void verifyAlgorithmIdentifierProtectionAttribute(AttributeTable signedAttrTable)
                                                              ^
  symbol:   class AttributeTable
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:606: error: cannot find symbol
    private void verifyCounterSignatureAttribute(AttributeTable signedAttrTable)
                                                 ^
  symbol:   class AttributeTable
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:667: error: cannot find symbol
    public SignerInfo toASN1Structure()
           ^
  symbol:   class SignerInfo
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:713: error: cannot find symbol
    private Time getSigningTime()
            ^
  symbol:   class Time
  location: class SignerInformation
.../src/main/java/org/bouncycastle/cms/SignerInformation.java:745: error: cannot find symbol
        AttributeTable unsignedAttributes)
        ^
  symbol:   class AttributeTable
  location: class SignerInformation
.../src/main/java/org/bouncycastle/gpg/test/AllTests.java:5: error: package junit.extensions does not exist
import junit.extensions.TestSetup;
                       ^
.../src/main/java/org/bouncycastle/gpg/test/AllTests.java:6: error: package junit.framework does not exist
import junit.framework.Test;
                      ^
.../src/main/java/org/bouncycastle/gpg/test/AllTests.java:7: error: package junit.framework does not exist
import junit.framework.TestCase;
                      ^
.../src/main/java/org/bouncycastle/gpg/test/AllTests.java:8: error: package junit.framework does not exist
import junit.framework.TestSuite;
                      ^
.../src/main/java/org/bouncycastle/gpg/test/AllTests.java:10: error: package org.bouncycastle.test does not exist
import org.bouncycastle.test.PrintTestResult;
                            ^
.../src/main/java/org/bouncycastle/gpg/test/AllTests.java:14: error: cannot find symbol
    extends TestCase
            ^
  symbol: class TestCase
.../src/main/java/org/bouncycastle/gpg/test/AllTests.java:41: error: cannot find symbol
    public static Test suite()
                  ^
  symbol:   class Test
  location: class AllTests
.../src/main/java/org/bouncycastle/gpg/test/AllTests.java:51: error: cannot find symbol
        extends TestSetup
                ^
  symbol:   class TestSetup
  location: class AllTests
.../src/main/java/org/bouncycastle/gpg/test/AllTests.java:53: error: cannot find symbol
        public BCTestSetup(Test test)
                           ^
  symbol:   class Test
  location: class BCTestSetup
.../src/main/java/org/bouncycastle/gpg/test/KeyBoxTest.java:10: error: package junit.framework does not exist
import junit.framework.TestCase;
                      ^
.../src/main/java/org/bouncycastle/tsp/ers/ERSEvidenceRecordGenerator.java:6: error: package org.bouncycastle.asn1.tsp does not exist
import org.bouncycastle.asn1.tsp.EvidenceRecord;
                                ^
.../src/main/java/org/bouncycastle/tsp/ers/ERSArchiveTimeStamp.java:7: error: package org.bouncycastle.asn1.tsp does not exist
import org.bouncycastle.asn1.tsp.ArchiveTimeStamp;
                                ^
.../src/main/java/org/bouncycastle/tsp/ers/ERSArchiveTimeStamp.java:8: error: package org.bouncycastle.asn1.tsp does not exist
import org.bouncycastle.asn1.tsp.PartialHashtree;
                                ^
.../src/main/java/org/bouncycastle/tsp/ers/ERSEvidenceRecord.java:15: error: package org.bouncycastle.asn1.cms does not exist
import org.bouncycastle.asn1.cms.CMSObjectIdentifiers;
                                ^
warning: unknown enum constant Status.STABLE
  reason: class file for org.apiguardian.api.API$Status not found
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
100 errors
18 warnings
only showing the first 100 errors, of 1035 total; use -Xmaxerrs if you would like to see more

**Comment by jimshowalter** [comment]
only showing the first 100 errors, of 1035 total; use -Xmaxerrs if you would like to see more

**Comment by jimshowalter** [comment]
![Screenshot 2024-03-08 at 11 57 40 AM](https://github.com/bcgit/bc-java/assets/211780/0a285533-464b-4947-ade6-b331ddda32c3)

**Comment by jimshowalter** [comment]
Copied the org folder from the three folders at the top into the combined org folder that's expanded.

Copied the combined org folder into a git project and tried to build it with Gradle.

**Comment by dghgit** [comment]
I don't see the bcutil jar. Is that included?

**Comment by jimshowalter** [comment]
Ah! Thank you.
