### ISSUE TITLE
java.security.NoSuchAlgorithmException: X.509 KeyManagerFactory not available with FIPS ON

### ISSUE THREAD

**Issue by prakashsatpathy** [bcgit/bc-java#1612]
With FIPS ON, not able to start the "vI18nManager" service.

Error:
------
Protocol handler initialization failed
java.security.NoSuchAlgorithmException: X.509 KeyManagerFactory not available

Version:
--------
openjdk version "11.0.21"
BC Version: bc-fips-1.0.2.3, bctls-fips-1.0.12.3
TLS: v1.2

java.security settings
---------------------
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider C:HYBRID;ENABLE{All}
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.3=SUN
security.provider.4=SunJCE

keystore.type=bcfks

ssl.KeyManagerFactory.algorithm=X.509
ssl.TrustManagerFactory.algorithm=PKIX

Working with FIPS OFF
-----------------------
But FIPS OFF (ssl.KeyManagerFactory.algorithm=SunX509), the service starts successfully.

**Comment by dghgit** [comment]
ssl.KeyManagerFactory.algorithm must be set to PKIX.

**Comment by prakashsatpathy** [comment]
Thanks for the quick response.

It's not working after changing to PKIX as well.

Changed to, 
ssl.KeyManagerFactory.algorithm=PKIX
ssl.TrustManagerFactory.algorithm=PKIX

Error: "java.security.NoSuchAlgorithmException: PKIX KeyManagerFactory not available"

With FIPS ON and below BC version, it wroks,
bc-fips-1.0.2.1
bctls-fips-1.0.11

But doesn't work with bc-fips-1.0.2.3.

Is there any significant changes in bc-fips-1.0.2.3 ?
Am I missing any additional security provider?

**Comment by dghgit** [comment]
If that's the case it's not loading the BCJSSE. Try using:

org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS

I would also recommend using bc-fips-1.0.2.4

**Comment by dghgit** [comment]
Assumed dealt with.
