### ISSUE TITLE
Dilithium implementation variant dropped

### ISSUE THREAD

**Issue by kuehne-trustable-de** [bcgit/bc-java#1616]
I see that the details of PQC algorithms are a moving target.
And it is appreciated that the ML-DSA-87 is implemented. But it is upsetting that the support for OID 1.3.6.1.4.1.2.267.7.8.7 was dropped from BC while the ejbca is happily signing certificates with exactly this OID.

Please amntion a dropped OID in the release notes or even better, mark it as deprecated and support it some a few releases.

**Comment by dghgit** [comment]
Sorry, but it's not just the OID that changed - the OQS OIDs change as the algorithm is tweaked, we just don't have the resources to support multiple variants. Understand the frustration though and we should mention it, hopefully this whole thing will be resolved soon - initial testing is now possible on the ACVP demo system so it looks like everything is going into place for the final standard.

**Comment by kuehne-trustable-de** [comment]
OK, I see!
Thank you for the quick reply. Thomas also promised that ejbca will be using the most recent BC version, soon.
We'll test as soon as possible!
