### ISSUE TITLE
bcpg in release 1.78 now requires bcutil dependency

### ISSUE THREAD

**Issue by pascal-schmidt-hdp** [bcgit/bc-java#1619]
bcpg-jdk18on in release 1.78 needs bcutil-jdk18on dependency because of CryptlibObjectIdentifier now living there. Previously bcutil was not needed. the bcpg-jdk18on-1.78.jar I pulled from Maven central does not state the new dependency in it's pom file, it only lists bcprov-jdk18on.

**Comment by dghgit** [comment]
I'll fix the maven dependency as part of sorting out the OSGI issue. Note, if you're using Java 9, the module entry was also missing from the requires statement - the 1.78.1 release candidate on https://www.bouncycastle.org/betas has this fixed in it as well.

**Comment by smile12456** [comment]
同问

**Comment by smile12456** [comment]
please add tag 1.78

**Comment by dghgit** [comment]
This is now fixed in 1.78.1 which is starting to appear on Maven Central and bouncycastle.org.

And yes, I'm still waiting on that CVE ID. Expecting it any moment now...

**Comment by pascal-schmidt-hdp** [comment]
Confirmed, for my project's Maven build, in version 1.78.1 bcpg now automatically pulls in bcutil.

Thanks!
