### ISSUE TITLE
Which one should the OID of the Dilithium algorithm be used?

### ISSUE THREAD

**Issue by eamonzzz** [bcgit/bc-java#1620]
OID supported by OQS is 1.3.6.1.4.1.2.267.7.x
https://github.com/open-quantum-safe/oqs-provider/blob/main/ALGORITHMS.md

And i couldn't find the OID registration information for 1.3.6.1.4.1.2.267.12.x

<img width="980" alt="image" src="https://github.com/bcgit/bc-java/assets/20869326/fe495096-2bf8-47d2-acb3-2d0dee1cc919">

**Comment by roy-basmacier** [comment]
The OID changes were made following the OID mapping on  the [IETF Hackathon / FIPS 204 Initial Draft](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/docs/oid_mapping.md)
