### ISSUE TITLE
JcaContentSignerBuilder.java TOCTOU issue?

### ISSUE THREAD

**Issue by alvesfonseca** [bcgit/bc-java#1623]
I am using `bcprov-jdk15to18-1.78.jar, bcpkix-jdk15to18-1.78.jar, bcutil-jdk15to18-1.78.jar` and `java-21-openjdk-amd64`.

JcaContentSignerBuilder.java, when invoked by CertTest.java, throws an exception while iterating compositeSignaturesOIDs in `checkCompositeSignatureCertificateCreation()`

It seams that `buildComposite(CompositePrivateKey privateKey)` refers to a uninitialized (**null**) `sigAlgId`, which throws `Exception: java.lang.NullPointerException: Cannot invoke "org.bouncycastle.asn1.x509.AlgorithmIdentifier.getParameters()" because "this.sigAlgId" is null`
when trying  `final ASN1Sequence sigAlgIds = ASN1Sequence.getInstance(sigAlgId.getParameters());`

**Comment by dghgit** [comment]
Have you tried jdk18on?

**Comment by dghgit** [comment]
Hmmm. Try the jars at https://www.bouncycaslte.org/betas this sounds an awful lot like the OSGi issue by a different name. Also check your classpath, there may be different versions of BC in the classpath and the error is actually a class annotation one.

**Comment by alvesfonseca** [comment]
Hi @dghgit ,
I am using Eclipse.
After including jar to the **classpath** (instead of modulespath), I managed to run the tests using versions ` jdk15to18-1.78` and `jdk18on-1.78`.
Thank you very much!
