### ISSUE TITLE
regression in PemReader in 1.78 throws `IOException: -----END CERTIFICATE----- not found`

### ISSUE THREAD

**Issue by ctcpip** [bcgit/bc-java#1641]
previously, `PemReader` was forgiving when parsing a string with leading whitespace in the `-----END` line. however, this behavior recently changed and now throws `IOException`

caused by [this change](https://github.com/pgpainless/bc-java/commit/5ca7b06b49daa50dbb830bd10cce68fa55a555a4#diff-48c0b9379243a3fcaeb26e93481c2df12a271211c03f560a087da87084126ac7R78)

as an aside, ironically the changelog says `Make PEM parsing more forgiving of whitespace` 😅

while the leading whitespace is technically invalid, this change breaks previously working code. possible options are to revert part of the change, or at least call out the breaking behavior in release notes

**Comment by dghgit** [comment]
I'll update the release notes, experience has shown it's much better to try and stick to what's valid, agree with the sense of irony though, this is one of those things where you never win...

**Comment by hytgbn** [comment]
+1 to go back to previous behavior. There are many existing real world cases that comes with leading spaces , not arguing that they are valid but this breaks our customers. Making parser stricter by default seems to be a dangerous step that can break lot of customers. If not, at least there needs to be a flag for more permissive parsing (previous behavior)

**Comment by hytgbn** [comment]
I think it's actually interesting that from this [CR](https://github.com/pgpainless/bc-java/commit/5ca7b06b49daa50dbb830bd10cce68fa55a555a4#diff-48c0b9379243a3fcaeb26e93481c2df12a271211c03f560a087da87084126ac7R78)

`blob2` is supported (trailing WSs after BEGIN line)

``` 
    private static final String blob2 =
        "-----BEGIN BLOB-----   \r\n"
        + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\r\n"
        + "-----END BLOB-----    \r\n";
```

but `blob4` is not supported.

```
    private static final String blob4 =
        "-----BEGIN BLOB-----\r\n"
        + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\r\n"
        + "    -----END BLOB-----\r\n";
```

They don't seem to be consistent in interpreting RFC.

How do you think about adding `trim()` in https://github.com/pgpainless/bc-java/blob/main/core/src/main/java/org/bouncycastle/util/io/pem/PemReader.java#L78?

**Comment by dghgit** [comment]
I'd have to go back through the original emails, but I seem to remember one of the issues with the previous behavior was it resulted in some ambiguity about how things would be read.

We'd be happy to accept a pull request on this, providing it was protected by a system property.

**Comment by dghgit** [comment]
Pull request merged. Thanks.

**Comment by dudaerich** [comment]
@dghgit Hi David, do you know when the fix could be released? Is there any plan? Thank you.
