### ISSUE TITLE
issues with Import-Package, versioning scheme and missing class in 1.78.1

### ISSUE THREAD

**Issue by grgrzybek** [bcgit/bc-java#1644]
With 1.78.1 upgrade I have few problems - similar and different to #1278.

* `org/bouncycastle/asn1/cryptlib/CryptlibObjectIdentifiers.class` is available in bcprov-jdk18on-1.77.jar, but not in `bcprov-jdk18on-1.78.1.jar`
* this class was moved to bcprov-ext-jdk18on, but only at version 1.78 (there's no 1.78.1). In 1.76 it was available in both libraries
* missing 1.78.1 of `bcprov-ext-jdk18on` is something that reminds me of #1278 ;) and it was a bit painful to manage
* `Import-Package` in bcprov-jdk18on-1.78.1.jar contains entries like `java.io;resolution:=optional,java.lang;resolution:=optional, ...`. While this is valid since OSGi Core R7, bcprov-jdk18on had only this:
```
Import-Package: javax.crypto;resolution:=optional,javax.crypto.interfa
 ces;resolution:=optional,javax.crypto.spec;resolution:=optional,javax
 .naming;resolution:=optional,javax.naming.directory;resolution:=optio
 nal,javax.security.auth;resolution:=optional,javax.security.auth.call
 back;resolution:=optional,javax.security.auth.x500;resolution:=option
 al
```

So it looks like a breaking (from OSGi point of view) change...

**Comment by dghgit** [comment]
You need to use bcutil-jdk18on-1.78.1.jar as well.

**Comment by grgrzybek** [comment]
Oh, I see `CryptlibObjectIdentifiers.class` in `bcutil-jdk18on`... But why is it also available in `bcprov-ext-jdk18on`?

**Comment by dghgit** [comment]
bcprov-ext-jdk18on-1.178 was uploaded in error. Don't use it. We're in the process of getting a redirection POM uploaded to point people at bcprov-jdk18on.
