### ISSUE TITLE
ClassCastException: java.lang.String cannot be cast to org.bouncycastle.bcpg.UserIDPacket

### ISSUE THREAD

**Issue by didisoft** [bcgit/bc-java#167]
In [https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/PGPPublicKey.java](url)
line: 1019
`UserIDPacket id = (UserIDPacket)it.next();`

throws ClassCastException: java.lang.String cannot be cast to org.bouncycastle.bcpg.UserIDPacket

The reason is that getUserIDs() returns Iterator over Strings (not UserIDPacket).
Solution:

either change
`UserIDPacket id = (UserIDPacket)it.next();`
to
`String id = (String)it.next();`

or modify getUserIDs() to return Iterator over UserIDPacket

**Comment by bcgit** [comment]
Thanks. Should now be fixed.

**Comment by bcgit** [comment]
okay, now it's really fixed... and tested... should appear on github in the next few days.
