### ISSUE TITLE
bcprov-jdk18on (1.77)  is incompitible with Openjdk17

### ISSUE THREAD

**Issue by longsan777** [bcgit/bc-java#1670]
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/jcajce/provider/asymmetric/edec/BC11XDHPublicKey
        at org.bouncycastle.jcajce.provider.asymmetric.edec.KeyPairGeneratorSpi.generateKeyPair(KeyPairGeneratorSpi.java:110)
        at java.base/java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:721)

**Comment by dghgit** [comment]
It's in versions/11 you'd only see something like this if your container cannot handle multi-release jars. There were some OSGi issues pre-1.78.1 so you might find updating to that helps.

**Comment by longsan777** [comment]
> It's in versions/11 you'd only see something like this if your container cannot handle multi-release jars. There were some OSGi issues pre-1.78.1 so you might find updating to that helps.

Hi dghgit:
       Thank for your reply. I resolved this problem. The root cause is i use maven-assembly-plugin to compile all dependencies into a executable jar but didn't add "Multi-Release" tag as true.
      It makes the multiple-release jar doesn't work.  The solution is  like following:
       <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <archive>
                    	**<manifestEntries>
                            <Multi-Release>true</Multi-Release>
                        </manifestEntries>**
                        <manifest>
                            <mainClass>com.xxxxx</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
