### ISSUE TITLE
org.bouncycastle.dvcs.DVCSResponse constructor does not work as described

### ISSUE THREAD

**Issue by phaethon** [bcgit/bc-java#168]
Documentation states that org.bouncycastle.dvcs.DVCSResponse constructor should take DVCSRequest object and create (supposedly corresponding) DVCSResponse. But the actual code in constructor compares to DVCSResponse ids
```if (!DVCSObjectIdentifiers.id_ct_DVCSResponseData.equals(contentInfo.getContentType()))```
Either code is wrong, or description in the documentation is wrong.

**Comment by bcgit** [comment]
JavaDoc/Error message now fixed.
