### ISSUE TITLE
maven install with maven-shade-plugin failed.

### ISSUE THREAD

**Issue by SkyeBeFreeman** [bcgit/bc-java#1689]
Reproduce repo branch: 

https://github.com/polarismesh/polaris-java/tree/dependabot/maven/polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/org.bouncycastle-bcpkix-jdk18on-1.78

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade (default) on project polaris-all: Error creating shaded jar: Problem shading JAR /home/runner/.m2/repository/org/bouncycastle/bcprov-jdk18on/1.78/bcprov-jdk18on-1.78.jar entry META-INF/versions/21/org/bouncycastle/pqc/jcajce/provider/NTRU$Mappings.class: java.lang.IllegalArgumentException: Unsupported class file major version 65 -> [Help 1]
```

**Comment by dghgit** [comment]
The version of maven isn't correctly identifying a multi-release jar. This isn't a BC bug. You'd need to be using the jdk15to18 version with something like this.

Keep in mind if the shading also involves unpacking the bcprov jar, this will not work on a JVM that requires JCE validation for any algorithm that uses the JCE APIs.
