### ISSUE TITLE
org.bouncycastle.openpgp.PGPPublicKey SHOULD NOT encode Trust packet

### ISSUE THREAD

**Issue by didisoft** [bcgit/bc-java#169]
As per [https://tools.ietf.org/html/rfc4880#section-5.10](https://tools.ietf.org/html/rfc4880#section-5.10) "Trust packets SHOULD NOT be emitted to output streams that are transferred to other users". 

A possible fix can be merged from here:
https://github.com/didisoft/bc-java/commit/029dd17f3aeeda5ee85686b03320351e432f18af

**Comment by bcgit** [comment]
Yes, that's correct.
getEncoded() is supposed to be producing an accurate encoding for the key for storage though. If this is causing confusion I'll add a method taking a boolean which flags the packets are meant to be ignored.

**Comment by didisoft** [comment]
Yes,

something like
getEncoded(boolean forExport) 

will do the job.

**Comment by bcgit** [comment]
Method's added for specifying if key encoding been generated for export/transfer.
