### ISSUE TITLE
Wrong ASN1 encoding of RSASSAPSSparams

### ISSUE THREAD

**Issue by laurids** [bcgit/bc-java#1707]
Hi Castle Bouncers.

The ASN1 encoding in [RSASSAPSSparams.java#L146](https://github.com/bcgit/bc-java/blob/r1rv78/core/src/main/java/org/bouncycastle/asn1/pkcs/RSASSAPSSparams.java#L146) is really weird, because it leaves out default values. As far as I can read, none of the fields are optional according to [rfc8017#appendix-A.2.3](https://www.rfc-editor.org/rfc/rfc8017#appendix-A.2.3).
With this encoding, the class becomes useless for applications where receivers comply with rfc8017 and requires all the fields to be mandatory.

Am I missing something?

Thanks in advance.

**Comment by laurids** [comment]
Okay, I guess it is following [rfc4055](https://www.rfc-editor.org/rfc/rfc4055#section-3.1).
Why oh why is rfc8017 not stating that it is overriding rfc4055? 🙄

Can I ask to add a note in RSASSAPSSparams about it following rfc4055? Just to help future developers be slightly less confused.

However, I still think the rfc4055 encoding is terrible, though I understand if you need to keep it for compatibility.

**Comment by laurids** [comment]
A colleague pointed out that according to [X.690-0207](https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf) section 8.9, DEFAULT values can be omitted, so apparently rfc8017 is not even disagreeing with rfc4055.

I guess I'll just close this issue.

**Comment by peterdettman** [comment]
Yes, it's just a general ASN.1 rule that fields with a DEFAULT may be omitted from encodings (for DER or CER, MUST be omitted) when the actual value matches the default.

**Comment by laurids** [comment]
Hi Peter, thanks for the hint about DER, much appreciated:)
