### ISSUE TITLE
ClassCastException: B cannot be cast to org.bouncycastle.bcpg.UserIDPacket

### ISSUE THREAD

**Issue by didisoft** [bcgit/bc-java#171]
In [https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/PGPPublicKey.java](https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/PGPPublicKey.java)
line: 1051
UserIDPacket id = (UserIDPacket)it.next();

throws ClassCastException: B cannot be cast to org.bouncycastle.bcpg.UserIDPacket

The reason is that getRawUserIDs() returns Iterator over byte array (not UserIDPacket).

This is related to [https://github.com/bcgit/bc-java/issues/167](https://github.com/bcgit/bc-java/issues/167)

**Comment by didisoft** [comment]
A test case has been added to reproduce this error:
[](https://github.com/didisoft/bc-java/commit/dbdae4bd6e1f9edf2c981b14282cb4970429a99a)

**Comment by didisoft** [comment]
Proposed fix can be found here [](https://github.com/didisoft/bc-java/commit/5a74a3f3e3b527a9391c049f2b6546f85ac4bcbc)

**Comment by bcgit** [comment]
I've confirmed this issue is fixed using the included test code.
