### ISSUE TITLE
https://www.bouncycastle.org/ is down

### ISSUE THREAD

**Issue by tiagomlalves** [bcgit/bc-java#1714]
Hi team,

I'm not sure where is the right place to report this but since yesterday I've noticed that https://www.bouncycastle.org/ is down.
Any status on when will it be back?

Kind regards,
   Tiago

**Comment by dghgit** [comment]
It's back (or at least should have shown up about 48 hours after the question). Sorry, not exactly clear what happened, but it seems we've managed to address it.
