### ISSUE TITLE
OSGi BREE manifest header too restrictive in jdk15on JARs

### ISSUE THREAD

**Issue by mnk** [bcgit/bc-java#173]
All "jdk15on" JAR files in the latest(1.56) BouncyCastle release contains the Manifest header Bundle-RequiredExecutionEnvironment with the value "J2SE-1.5, JavaSE-1.6, JavaSE-1.7, JavaSE-1.8, JavaSE-1.9".

This value causes the latest version(0.26) of Eclipse Tycho to fail with a OsgiManifestParserException when building a plugin that depends on BouncyCastle. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=510671

As commented by Martin Schreiber in that bug report, the error is caused by the fact that Equinox has changed the naming of Java 9 from JavaSE-1.9 to JavaSE-9 - adhering to OSGi specification.

According to https://wiki.eclipse.org/Execution_Environments#Setting_the_Execution_Environment, the intention of the Bundle-RequiredExecutionEnvironment header is for the bundle to specify its minimum supported execution environment - not list all supported environments.

For the jdk15on JARs it is therefor suggested to change the value to only contain "J2SE-1.5".

**Comment by mnk** [comment]
See also: http://www.bouncycastle.org/jira/browse/BJA-669

**Comment by bcgit** [comment]
Jar is now set to contain only "J2SE-1.5".
