### ISSUE TITLE
BasicTlsTest is not correctly closing server sockets

### ISSUE THREAD

**Issue by Skywalker-11** [bcgit/bc-java#174]
I noticed that after running the BasicTlsTest.testConnection test the HTTPSServerThread still has the server socket open. This will cause the test to fail if it is run more than once. 

Fix could be to add `sSock.close();` at the end of HTTPSServerThread.run.

**Comment by peterdettman** [comment]
I'm not really seeing the failures, but granted the sockets should be closed, so I've gone through all the TLS tests and added it where it was missing. Changes should mirror here soon if you could check whether the problems persist.
