### ISSUE TITLE
ISAACEngine calls isaac() twice on initialization

### ISSUE THREAD

**Issue by Adam-** [bcgit/bc-java#175]
in setKey() isaac() is called and index is set to 0, but in processBytes() or returnByte() it causes isaac() to be called again due to index == 0.

**Comment by bcgit** [comment]
This appears to be in line with the intention of the original author - the reference implementation at http://www.burtleburtle.net/bob/rand/isaacafa.html first calls  randinit() which includes an initial call to isaac, and then calls isaac again for the actual stream production.
