### ISSUE TITLE
BCUTIL-FIPS 2.0.2 Module resolution exception

### ISSUE THREAD

**Issue by alexeybakhtin** [bcgit/bc-java#1760]
bctls-fips v2.0.19 requires module org.bouncycastle.fips.util
bc-fips v2.0.0 and bcutil-fips v2.0.2 contain the same packages. It causes java.lang.module.ResolutionException:

```
java.lang.module.ResolutionException: Module org.bouncycastle.fips.util contains package org.bouncycastle.asn1.iana, module org.bouncycastle.fips.core exports package org.bouncycastle.asn1.iana to org.bouncycastle.fips.util
```

**Comment by dghgit** [comment]
Try https://downloads.bouncycastle.org/fips-java/bcutil-fips-2.0.3.jar and let me know how it goes. Thanks.

**Comment by alexeybakhtin** [comment]
Thank you. It works now.
Do you have plans to release it soon?

**Comment by dghgit** [comment]
Just give me 5 minutes.

**Comment by dghgit** [comment]
It's now up on Maven Central and the BC website.

**Comment by alexeybakhtin** [comment]
Wow! Awesome! Thank you a lot!
