### ISSUE TITLE
id_alg_zlibCompress is missing after bc upgrade

### ISSUE THREAD

**Issue by marijusGood** [bcgit/bc-java#1777]
Hi team,

We have encountered a problem regarding upgrading to a newer version of bc.

We get errors saying that `id_alg_zlibCompress` is missing and the code can not preceded. 
![id_alg_zlibCompress](https://github.com/user-attachments/assets/8b6eafbc-ba0a-4eab-8a23-8021918333df)

We understand that this might have been legacy code that has been removed, but maybe you could inform us on how to go around this problem or what has `id_alg_zlibCompress` been replaced too.

Thanks!

**Comment by peterdettman** [comment]
Have you added the (relatively new) bcutil jar as a dependency?

**Comment by marijusGood** [comment]
yes we have, we jumped from 1.71 to 1.78

**Comment by peterdettman** [comment]
BTW, PKCSObjectIdentifier.id_alg_zlibCompress is not legacy code that was removed, rather it is a relatively new field (likewise CMSObjectIdentifiers.zlibCompress). If you just have the latest BC installed (e.g. bcprov, bcutil, bcpkix) there really shouldn't be any issue, so my best guess is that you still have an older copy of (probably) bcprov somewhere in the classpath, creating a conflict over the PKCSObjectIdentifiers class.
