### ISSUE TITLE
Unchecked function call on potentially null values in EC5Util.

### ISSUE THREAD

**Issue by loosebazooka** [bcgit/bc-java#1781]
EC5Util can end up with a null pointer exception if a malformed Point is passed in.

https://github.com/bcgit/bc-java/blob/main/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/util/EC5Util.java#L355

Does it make sense to check on point.getAffineXCoord or point.getAffineYCoord to ensure they aren't null and then throw an IllegalArgumentException on a malformed point?

I'm not even sure how our fuzzing test got to this point. I'm trying to find the test case data that caused it and I'll update this bug.

**Comment by winfriedgerlach** [comment]
@loosebazooka any news on this one?

**Comment by loosebazooka** [comment]
Oh sorry, I think I filed this and went looking, but got distracted. I'll have to find this again.
