### ISSUE TITLE
BC-FIPS 2.0 cache eviction throws error when using Hashicorp Vault OCSP responder.

### ISSUE THREAD

**Issue by revanthalampally** [bcgit/bc-java#1789]
1. A TLS JAVA client(using BCFIPS 2.0) is talking to a server which is using Hashicorp Vault issued certificate.

2. The TLS JAVA client(BCFIPS) is doing OCSP validation of the server certificate by sending OCSP request to the vault OCSP responder.

3. The BCFIPS maintains a cache of the OCSP response it gets from the responder.

4. Suppose the TLS java client is trying to make one more connection to the same server after the OCSP interval time (in our case its 12 hours in vault), then BCFIPS is returning error while doing OCSP check of the server cert. The error is "OCSP cache expired."

5. When we investigated this issue and found that the BCFIPS caching logic is not able to evict the expired certificate because of a NULL element present as part of CertID(hashing algorithm) of the OCSP response. 

https://github.com/bcgit/bc-java/blob/455ca6171ab3c86a951cf0cba793a55e46ed6958/prov/src/main/java/org/bouncycastle/jce/provider/OcspCache.java#L81

Hashicorp has responded that setting the hash algorithm parameters field to an explicit ASN.1 NULL value is valid
There are other examples of code doing the same:

https://github.com/snowflakedb/gosnowflake/blob/master/ocsp.go#L279

https://github.com/golang/crypto/blob/master/ocsp/ocsp.go

Example [here](https://lapo.it/asn1js/#MIIB8woBAKCCAewwggHoBgkrBgEFBQcwAQEEggHZMIIB1TCBvqE0MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJSMxgPMjAyNDA4MjUwNzAxMDBaMHUwczBLMAkGBSsOAwIaBQAEFEjayaD7K9MtT_DeaNL1Z7c1-bPEBBQULrMXt1hWy65QCUDmH6-dixTCxgISBMxmhf4fZC3E_qbt_Mk2dWtbgAAYDzIwMjQwODI1MDcwMTAwWqARGA8yMDI0MDkwMTA3MDA1OFowDQYJKoZIhvcNAQELBQADggEBAG0bBdCM0OeznIPi7ww4gHWcFfIVNxUAUeKdnxfP9F4_7aGBOMJpAAfVR-bU14lE-2AlPT8u1Hdha9zXeiiRGWC79PxGYqefdvd_VHjJ7wJS0Q0CHsbPswfGfEYHbngj7wPP_9u6CEJDPiV_kSbDhEQMfJITrorjGy2g7geAaDW7RV7XQsgvGm8FX-TgIs8DTFcAxcVBKE9HvazYxayGI7GpkUZsHu7lOkDhQ9OuDCXpG1IV65TYe7TtNTWZNll1pOyJIscVcttZgzi8NskqScCd-Veh-BbJp1BMC7rR5Y5fszJ16fZqUfqQx0jcZv0Vwdud_nOvCxbwJFD10HxaFg0)

similarly with [www.microsoft.com]: results [here](https://lapo.it/asn1js/#MIIHMgoBAKCCByswggcnBgkrBgEFBQcwAQEEggcYMIIHFDCBxaIWBBSBwmTDZlJEedehWZgwkVunCCutwxgPMjAyNDA4MjYxODU4MjJaMIGZMIGWMEwwCQYFKw4DAhoFAAQUdiTba9CcRL2MkqW8gVmqgZnmpQoEFM4VFjvqAqOma9rZK_3ljFK-elCoAhMzAAPizRBmrY24HAYIAAAAA-LNgAAYDzIwMjQwODI2MTcxMDE0WqARGA8yMDI0MDkwMzE3MzAxNFqhIDAeMBwGCSsGAQQBgjcVBAQPFw0yNDA4MzAxNzIwMTRaMA0GCSqGSIb3DQEBCwUAA4IBAQApJom_1O-01L5VCGWfZNKu3j_Oqfxc4nIgiAGpVElDqTcmZ1d8bPdOQSbwFT5ON7xQAlCckayZutV9DU3YKP5ih2n3_U_8HbUBYoISdJBseSrYe4RjWU5R-ehHP7SNoVV1xxth-T91HVzbXmQvPtavsa3BvMbJO6EboLKPeaDn9xuWbW6e1c7AgHNs6_Q67soAj53nrvWUvLNBHc-iVEwWIDQBxo9gdlJHk0trLAQN-pVkCWdVbWjiYXjlUlnVvxDQSWTuvm9UzmEjscheIhpef0PKQlUcGcGMs_s5HYLkpCLnJKHRnszYKgO9M0-4vwxNQ3rQ3LMzYo1gPRZOtfaSoIIFNDCCBTAwggUsMIIDFKADAgECAhMzAGzrzmYQoNBEGm0RAAAAbOvOMA0GCSqGSIb3DQEBDAUAMF0xCzAJBgNVBAYTAlVTMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLjAsBgNVBAMTJU1pY3Jvc29mdCBBenVyZSBSU0EgVExTIElzc3VpbmcgQ0EgMDcwHhcNMjQwODIzMTU1MDUyWhcNMjQwOTIyMTU1MDUyWjBfMQswCQYDVQQGEwJVUzELMAkGA1UECBMCV0ExEDAOBgNVBAcTB1JlZG1vbmQxEjAQBgNVBAoTCU1pY3Jvc29mdDEdMBsGA1UEAxMUQXp1cmVSU0EwNyBPQ1NQIENlcnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDDtz6g3xxzjmqzb3xL4IRFoFnZbb8aIfy0H8Rg3o_AXqXWVXgoHBLsJ3nX-R-t2rWLyyMg-FaX8mQaC8RE3ukJClZ_f29wwf7TM3ZMfBkUcVvOWVjTvBqF6RpiAtxaZngQnFpklQXz_KNmW3COAA5E0h5O-pjai9IIrlHioA0miFEdf8x55HB2EQl6sTdiSN5dmYu3jtBjXN_Psh9pW9akrbqHrdrFNyjZPEwu16oLrFpnLLi_nY2FTkv21P_mso7gRiT6wNVJb5tYuslEe6LD0DO7D7YouiKi3omr5TLl4oqUaMDWtIm0v7c-y1TcAo4JbBQZ2RkU2X5p4oiFWmGdAgMBAAGjgeIwgd8wDAYDVR0TAQH_BAIwADATBgNVHSUEDDAKBggrBgEFBQcDCTAdBgNVHQ4EFgQUgcJkw2ZSRHnXoVmYMJFbpwgrrcMwHwYDVR0jBBgwFoAUzhUWO-oCo6Zr2tkr_eWMUr56UKgwDgYDVR0PAQH_BAQDAgeAMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCIe91xuB5-tGgoGdLo7QDIfw2h1dg9nXIoH03h8CAWQCARcwGwYJKwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDCTAPBgkrBgEFBQcwAQUEAgUAMA0GCSqGSIb3DQEBDAUAA4ICAQAs2K4j8nmBmDq2YshsHCM5oOyfCR3LHTkuH8WC-TwK6qm6gCga8m_dFUHHFVP78Dqp2BEnALI8gKbQWG4WU0sma9fuFVoBVljIFZBdjMfF1l8-FnFuKVmeizCiF29cpaEwwjtFwKxGsSIjXfT4tzjDuiPT46sISxizvJ8NvMPigR0hry7sAIb7gimsiE11re-VAU-IwKrOf3S9EHrvY2InuT8V7fxN1Hl-nrHqlZsZctxpEv9fMbLe0SOzn669cVrjsY247em7hcTBNK7r4e-XU-UUEpRKcs-xjouRqhHl1l6WfVYvWSENSdWq2RombI5JmKSLJ0XCLNkDZ9xuLk-t9ClwuCeRWaNvjkcUtLyOWb8B0UWTV8E_lNlJp0VM8qhbgeRsGQTBlBtQm3246O3ZTihJwATiQQC1pn_jeGzz7N5iZgrFLsVvGx8AGf_NbM7t6Dhd0xoVfAlVoFXksHctM24ism3yo6V703it0Uf5kspiuyOa1ZrH24oKgKBh1WP_tsNk-kOATBQMPLyjlU3AiIiUYtZye2dnnfF3mbeLN5FEKFPlgCPVlO9gSE6aicOWKBU0gTUM6_JRsdfX97OoeTu44tXGlpBDBV3O2tpl_hlMl9HhLHwoFtFzOSplbyB_yGKLETlaGU_y01zqE_jMnh-9JI4nbW97Bk4MsvPbZw)

This behavior your java client is experiencing appears to be due to the way the BCFIPS library is handling the responses. 

There needs to be a way to ignore the NULL values when  BCFIPS is storing in its responseMap in order to avoid this.

This is blocking us from our fedramp release. Can someone please look into this soon?

**Comment by peterdettman** [comment]
It's not completely clear what the problem is, so could you confirm my understanding please:

1. A first OCSP request is made for a certificate not in the cache. The response goes into the cache indexed by a CertID created locally by BCFIPS.
2. A second OCSP request for the same certificate finds the cached response, however (none of) the CertID(s) contained in the SingleResponse object(s) actually compares equal to the locally-created CertID used by the cache (response validation at step 1 did not detect this).
3. Since the CertID never matches, this response will never be evicted from the cache based on nextUpdate expiry.
4. The reason for the CertID inequality is that the BCFIPS one has CertID.hashAlgorithm.parameters absent, whereas the one in the response that should match actually has an explicit ASN.1 NULL value in CertID.hashAlgorithm.parameters.

FYI, ASN.1 NULL in the parameters field is only really valid for particular digest algorithms (for historical reasons), however in a situation like this we would probably choose to be tolerant. I am curious what the digest algorithm OID (CertID.hashAlgorithm.algorithm) is in this case though.

**Comment by revanthalampally** [comment]
@peterdettman : 1. is correct.
In 2, A second OCSP request is made since this TLS connection is after the cached certID's expiry( i.e. the lastUpdate time of the first OCSP response that gets stored in the responseMap).
Now, when BCFIPS get the OCSP response from Vault, the cache eviction logic kicks in [since](https://github.com/bcgit/bc-java/blob/455ca6171ab3c86a951cf0cba793a55e46ed6958/prov/src/main/java/org/bouncycastle/jce/provider/OcspCache.java#L67) certID from the second response matches the responseMap.get(certID).

Now, cache eviction logic kicks in, and it fails [here](https://github.com/bcgit/bc-java/blob/455ca6171ab3c86a951cf0cba793a55e46ed6958/prov/src/main/java/org/bouncycastle/jce/provider/OcspCache.java#L81) since the certID from the OCSP responder (during the second call) and the certID in the responseMap(stored from the first call's response) are not equal because one has a NULL parameter, whereas the cache has DERNull.


The [RFC](https://datatracker.ietf.org/doc/html/rfc5912#section-3) governs the OCSP response->CertID->hashingAlgorithm says below:

```Example:
--  mda-sha1 DIGEST-ALGORITHM ::= {
--      IDENTIFIER id-sha1
--      PARAMS TYPE NULL ARE preferredAbsent
--  }
```

```ParamOptions ::= ENUMERATED {
   required,         -- Parameters MUST be encoded in structure
   preferredPresent, -- Parameters SHOULD be encoded in structure
   preferredAbsent,  -- Parameters SHOULD NOT be encoded in structure
   absent,           -- Parameters MUST NOT be encoded in structure
   inheritable,      -- Parameters are inherited if not present
   optional,         -- Parameters MAY be encoded in the structure
   ...
}
```

preferredAbsent means  Parameters SHOULD NOT be encoded in structure, should not doesn't mean it can't be, otherwise it would be listed as absent.

**Comment by dghgit** [comment]
@revanthalampally if you register this one with the support portal at Keyfactor we will be able to organise a patch release for you.

**Comment by revanthalampally** [comment]
@dghgit : Im not sure which support portal are you talking about. Could you share the link?
Also we need this in BCFIPS not just commercial BC.

**Comment by dghgit** [comment]
The portal is here -> https://support.keyfactor.com/hc/en-us 

Contract details if you need them available at https://www.keyfactor.com/open-source/bouncy-castle-support/

Note although we can put a patch together quickly, getting a certified update to a FIPS API is not an easy or cheap task.

**Comment by revanthalampally** [comment]
@dghgit : Wondering why do you need  to involve key factor here?

**Comment by dghgit** [comment]
They have the license for support contracts and the BC team is currently working there. It's how we fund this work - the getting of and maintenance of FIPS runs into 100K+ USD, this is not something you can fund using a lemonade stand or a chook raffle.

**Comment by dghgit** [comment]
Underlying issue has been dealt with. Closing this as inactive.
