### ISSUE TITLE
BCTLS FIPS 2.0.19 dropped these ciphers ?

### ISSUE THREAD

**Issue by vmwzhangv** [bcgit/bc-java#1823]
While upgrading the BC FIPS 2.0 libraries on our server, we are seeing the following ciphers are dropped on our TLS server with TLS v1.2:

AES256-GCM-SHA384
   IANA Name: TLS_RSA_WITH_AES_256_GCM_SHA384
AES128-GCM-SHA256
   IANA Name: TLS_RSA_WITH_AES_128_GCM_SHA256
AES256-SHA
   IANA Name: TLS_RSA_WITH_AES_256_CBC_SHA
AES128-SHA
   IANA Name: TLS_RSA_WITH_AES_128_CBC_SHA

Below is the list of jar files we have updated to
bc-fips-2.0.0.jar  bcpkix-fips-2.0.7.jar  bctls-fips-2.0.19.jar  bcutil-fips-2.0.3.jar

These ciphers are available with BC TLS FIPS 1.0 libraries, we were using
bc-fips-1.0.2.4.jar bcpkix-fips.1.0.7.jar bctls-fips.1.0.18.jar

Unfortunately, we cannot find any documentation what ciphers are being dropped by BC FIPS 2.0.
Please help to confirm whether the above change is expected or not.

**Comment by peterdettman** [comment]
1. The ciphers were removed from the default enabled list but are still supported if you want to enable them explicitly.

2. In FIPS mode, the boolean system property "org.bouncycastle.jsse.fips.allowRSAKeyExchange" changed its default value from "true" to "false". This property controls whether RSA cipher suites (names like "TLS_RSA_..."), including the ones you list, are permitted. So it would now be necessary to set the property to allow any RSA cipher suite to be enabled in FIPS mode.

3. If you are in approved-only mode, RSA key exchange isn't permitted by FIPS 140-3 anyway, so in that case none of those cipher suites would work even if configured in BCJSSE.

**Comment by vmwzhangv** [comment]
@peterdettman Thanks, Peter
