### ISSUE TITLE
curve25519 private key parsing fails since 1.74

### ISSUE THREAD

**Issue by njiber** [bcgit/bc-java#1851]
Hello,

I think since bouncycastle version 1.74 there is a bug concerning the curve25519 support.

With bouncy castle version 1.73 the following code works:

~~~
import java.security.Security;
import java.security.KeyFactory;
import java.security.interfaces.ECPrivateKey;

import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.crypto.ec.CustomNamedCurves;
import org.bouncycastle.asn1.x9.X9ECParameters;
import org.bouncycastle.jce.spec.ECParameterSpec;
import org.bouncycastle.jce.spec.ECPrivateKeySpec;
import org.bouncycastle.util.encoders.Hex;

import java.math.BigInteger;

public final class Test {
  @Test
  public void demo() throws InvalidKeySpecException, NoSuchAlgorithmException,
      NoSuchProviderException {
    Security.addProvider(new BouncyCastleProvider());

    KeyFactory kf = KeyFactory.getInstance("EC", "BC");

    X9ECParameters params = CustomNamedCurves.getByName("curve25519");

    ECParameterSpec spec = new ECParameterSpec(params.getCurve(), params.getG(),
        params.getN(), params.getH());

    byte[] s = Hex.decode(
        "36704190D0033DB4ABF4E5A10E692C08D4CC0FEA67EF0AAA63E0BEF440A8F0C5");
    ECPrivateKey targetPrivateKey = (ECPrivateKey) kf
        .generatePrivate(new ECPrivateKeySpec(new BigInteger(s), spec));
  }
}
~~~

Since version 1.74, the code above fails with:

~~~
java.lang.IllegalArgumentException: Scalar is not in the interval [1, n - 1]
~~~

However, I do think that like for other 256 bit ec curves, every 32 bytes value should be a valid private key; or is my understanding of curve25519 incorrect and bouncy castle now behaves proper?

Thank you!

**Comment by peterdettman** [comment]
The relevant standard is "SEC 1: Elliptic Curve Cryptography", where the procedure for generating a private key is:

"1. Randomly or pseudorandomly select an integer d in the interval [1, n - 1]."

So the check is correct.

To clarify a probable confusion: using "curve25519" in this code gives you a Weierstrass curve to be used under the SEC standards (for ECDH, ECDSA, etc.).

However the name "curve25519" would normally imply the Montgomery curve specified in https://cr.yp.to/ecdh.html . Notably, in that specification a secret key can be any random 32 byte value. This is implemented in BC as the "X25519" algorithm (per RFC 7748), which is a standalone algorithm usable with e.g. KeyAgreement, KeyFactory, KeyPairGenerator. It cannot be accessed via "EC" keys and generators, or "ECDH" or "ECDSA" algorithms, which follow the SEC standards.

**Comment by njiber** [comment]
Thank you!

For the record, this means that the key above used in my code is invalid and indeed too long.
