### ISSUE TITLE
AttributeCertificate should implement Serializable

### ISSUE THREAD

**Issue by Blackjack92** [bcgit/bc-java#188]
Hello,

why does the AttributeCertificate not implement Serializable? and would it be possible to change that, so that the AC could easily be send over the network.

Kindly regards
Kevin

**Comment by bcgit** [comment]
X509AttributeCertificateHolder now supports Serializable. I hope that will do the trick.

**Comment by Blackjack92** [comment]
Which commit added the Serializable opportunity? I have not found it.

**Comment by dghbk** [comment]
Sorry, appears to have been a malfunction in the sync. It should show up shortly.

The latest beta on https://www.bouncycastle.org/betas also has the serializable in it.
