### ISSUE TITLE
OpenSSH keys visible from the repo!

### ISSUE THREAD

**Issue by TacticalNuke1** [bcgit/bc-java#1883]
Found this using a google dork, and your openSSH keys and RSA keys are viewable in:
bc-java/prov/src/test/java/org/bouncycastle/jce/provider/test/OpenSSHSpecTests.java

**Comment by mwcw** [comment]
It's a unit test that needs to load keys and verify their properties.

I'll assume this issue was created as a result of running a tool over the code base or simply searching for keyts.

Next time please check the issue is actually an issue before posting.

MW
