### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#1887]
Running tests on the current "main", I get two errors, both related to Argun2:

![Screenshot 2024-10-28 at 12 24 52](https://github.com/user-attachments/assets/2fe1af43-1a96-4620-bc5c-1e3a32f3c3c0)

We need a way to pass "-Xmx4096m" (or such) argument to Java via Ant script. For some reason, having `export JAVA_OPTS=-Xms4096m` does not suffice.

**Comment by dghgit** [comment]
The problem will be the forking that ant's doing to run the tests. I've added a setting for maxmemory which should deal with this - it's set to 4096m for jdk1.8+. Let me know if works.
