### ISSUE TITLE
DEFAULT_VERSION placeholder not substituted in 1.78/1.78.1

### ISSUE THREAD

**Issue by tim-palmer** [bcgit/bc-java#1889]
The source code for org/bouncycastle/bcpg/ArmoredOutputStream.java published for release 1.77 ([bcpg-jdk18on-1.77-sources.jar](https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/1.77/bcpg-jdk18on-1.77-sources.jar)) contains:

```
public static final String DEFAULT_VERSION = "BCPG v1.77.00";
```

The same file in [bcpg-jdk18on-1.78-sources.jar](https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/1.78/bcpg-jdk18on-1.78-sources.jar) and [bcpg-jdk18on-1.78.1-sources.jar](https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/1.78.1/bcpg-jdk18on-1.78.1-sources.jar) contains:

```
public static final String DEFAULT_VERSION = "BCPG v@RELEASE_NAME@";
```

I.e. the RELEASE_NAME placeholder has not been substituted.

See also: https://github.com/gradle/gradle/issues/31035

**Comment by dghgit** [comment]
Sorry about that. This has been fixed in 1.79 (which is now out).
