### ISSUE TITLE
null pointer when doing v6 aead symmetric encryption 

### ISSUE THREAD

**Issue by singpolyma** [bcgit/bc-java#1913]
https://github.com/bcgit/bc-java/blob/main/pg/src/main/java/org/bouncycastle/openpgp/operator/bc/BcPBEKeyEncryptionMethodGenerator.java#L119 expects sessionInfo to be non-null, but https://github.com/bcgit/bc-java/blob/main/pg/src/main/java/org/bouncycastle/openpgp/PGPEncryptedDataGenerator.java#L229 sets it to null when there is only a single symmetric encryption key.

**Comment by vanitasvitae** [comment]
I don't think direct-s2k (using the result of the S2K derivation directly as the key to encrypt the message) is allowed to be used with v6's SEIPDv2 packets. You can work around the NPE by calling [setForceSessionKey(true)](https://github.com/bcgit/bc-java/blob/main/pg/src/main/java/org/bouncycastle/openpgp/PGPEncryptedDataGenerator.java#L126).

A PGPEncryptedDataGenerator for v6 should probably set this value to true by default. In general, it might be a good idea to deprecate the direct-s2k method, as it is a left-over from pre-rfc4880 days.

**Comment by vanitasvitae** [comment]
Just did a re-read of the spec and found the section that [describes direct-s2k](https://www.rfc-editor.org/rfc/rfc9580.html#section-5.3.1-4). Only for version 4 SKESKs, the `encryptedSessionKey` field is defined as [optional](https://www.rfc-editor.org/rfc/rfc9580.html#section-5.3.1-3.4.1). For version 6, this field is [mandatory](https://www.rfc-editor.org/rfc/rfc9580.html#section-5.3.2-3.8.1), so direct-s2k is not possible with v6.

**Comment by ligefeiBouncycastle** [comment]
Fixed in https://github.com/bcgit/bc-java/commit/e2e9bb2e2aad24b3e842092b43770b609470079b
