### ISSUE TITLE
NIST lightweight AEAD ciphers return incorrect outputLength

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#1924]
The Elephant, ISAP, PhotonBeetle and Xoodyak ciphers return incorrect outputLengths on getOutputSize() and getUpdateOutputSize(). In addition the Elephant cipher returns an incorrect count of bytes processed on doFinal().

For ISAP, PhotonBeetle and Xoodyak, this is due to the fact that the message is cached and only processed on doFinal(), and the OutputSize() methods do not take this into account. For Elephant the message is partially cached, and again the OutputSize() methods do not take this into account. For Elephant on doFinal(), the total number of bytes processed is returned rather than the number processed on the doFinal() call.

I have tested and verified a fix for these issues and will raise a pull request.

**Comment by ligefeiBouncycastle** [comment]
Fixed in https://github.com/bcgit/bc-java/commit/4953a48c9c45007706f8c5fa22a27b5678eae6ad
