### ISSUE TITLE
RSA CipherSpi cannot handle P11RSAPrivateKeyInternal keys

### ISSUE THREAD

**Issue by voliveirajr** [bcgit/bc-java#1930]
While trying to Decrypt sun.security.pkcs11.P11Key$P11RSAPrivateKeyInternal it fails at CipherSpi on the check 

if (!(var2 instanceof RSAPrivateKey)) {
https://github.com/bcgit/bc-java/blob/main/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/rsa/CipherSpi.java#L292

As it is not an instance of it even though still a RSA private key

**Comment by dghgit** [comment]
Yes, you can't use a key like this with the BC provider directly, internal means internal, the BC APIs will support it, providing they are used in conjunction with the provider that owns the key and the HSM has the necessary functionality.
