### ISSUE TITLE
2.0 Bc-fips landing on java.lang.UnsupportedOperationException: Renegotiation not supported

### ISSUE THREAD

**Issue by KPranaviReddy** [bcgit/bc-java#1944]
Hi, My application is landing on following exception with 2.0. The same code was working fine with 1.2. 
java.lang.UnsupportedOperationException: Renegotiation not supported
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source) ~[bctls-fips.jar:2.0.19]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source) ~[bctls-fips.jar:2.0.19]
or 
java.lang.UnsupportedOperationException: Renegotiation not supported
        at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(Unknown Source) ~[bctls-fips.jar:2.0.19]
        at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(Unknown Source) ~[bctls-fips.jar:2.0.19]

Java.securities file have the following entries: 

security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider C:DEFRND[SHA256];ENABLE{ALL};
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS
security.provider.3=sun.security.provider.Sun
securerandom.strongAlgorithms=NativePRNGBlocking:SUN,DRBG:SUN
keystore.type=bcfks
ssl.KeyManagerFactory.algorithm=PKIX
ssl.TrustManagerFactory.algorithm=PKIX

java.policy file  has the following entries:

permission org.bouncycastle.crypto.CryptoServicesPermission "tlsAlgorithmsEnabled";
permission org.bouncycastle.crypto.CryptoServicesPermission "exportKeys";

org.bouncycastle.jsse.client.acceptRenegotiation system property is also set to True.

Is there any configuration that I am missing on.

**Comment by peterdettman** [comment]
The exceptions in `startHandshake` indicate your code is trying to initiate renegotiation at the client, which is not supported. I don't believe such a call has ever been supported, so it seems unlikely it was "working fine" with an earlier version.

The system property "org.bouncycastle.jsse.client.acceptRenegotiation" only allows the client to accept a renegotiation that the server initiates (and it will only work for a common, but narrow set of conditions).

It is not clear what versions of what libraries you are referring to with "2.0" and "1.2". Please be clearer about what libraries you are using (and include the Java version).

**Comment by KPranaviReddy** [comment]
Thank you for the response Peter. I was under the understanding that  setting org.bouncycastle.jsse.client.acceptRenegotiation will solve the renegotiation issue. 

We are using Java 8. 

While using bc-fips-1.0.2.3.jar, I was not facing the issue. There are these 2 providers configured. 
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.2=com.sun.net.ssl.internal.ssl.Provider

While using bc-fips-2.0.0,jar along with bctls-fips-2.0.19.jar bcutil-fips-2.0.3.jar am using the above the configuration.
