### ISSUE TITLE
SHA256WITHRSAANDMGF1 Signature not available

### ISSUE THREAD

**Issue by soon-leong** [bcgit/bc-java#1947]
We encountered an NoSuchAlgorithmException when the cipher suite in the server hello is TLS_DHE_RSA_WITH_AES_128_GCM_SHA256.

INFO syserr - Caused by: java.security.NoSuchAlgorithmException: SHA256WITHRSAANDMGF1 Signature not available
INFO syserr - at java.base/java.security.Signature.getInstance(Signature.java:268)
INFO syserr - at org.bouncycastle.jcajce.util.DefaultJcaJceHelper.createSignature(Unknown Source)
	at org.bouncycastle.jcajce.util.DefaultJcaJceHelper.createSignature(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.createStreamVerifier(JcaTlsCrypto.java:1007)
	... 22 more

Here is the call stack leading to the exception

https://github.com/adoptium/jdk17u/blob/jdk-17.0.10%2B7/src/java.base/share/classes/java/security/Signature.java#L264

![image](https://github.com/user-attachments/assets/994b1dcd-68bc-4320-9fc2-0789cc9a3513)

https://github.com/adoptium/jdk17u/blob/jdk-17.0.10%2B7/src/java.base/share/classes/sun/security/jca/GetInstance.java#L114

![image](https://github.com/user-attachments/assets/2663781e-bea3-46d4-9753-6307635246f2)

https://github.com/adoptium/jdk17u/blob/master/src/java.base/share/classes/sun/security/jca/Providers.java#L136

![image](https://github.com/user-attachments/assets/d3d86ba9-35c5-4e46-a3c6-4a50e605ff77)

This function returns the list of system providers as shown here.
[SUN, SunRsaSign, SunEC, SunJSSE, SunJCE, SunJGSS, SunSASL, XMLDSig, SunPCSC, JdkLDAP, JdkSASL, SunMSCAPI, SunPKCS11]

https://github.com/adoptium/jdk17u/blob/jdk-17.0.10%2B7/src/java.base/share/classes/sun/security/jca/ProviderList.java#L400

![image](https://github.com/user-attachments/assets/749265ac-2f1b-4745-bd4d-d833cd6349dd)

This is where the issue is.
The code did not search for the signature algorithm in the list of providers.
It simply creates a ServiceList object that contains the type and algorithm name as shown below.
The object does not have any algorithm in the list.

https://github.com/adoptium/jdk17u/blob/jdk-17.0.10%2B7/src/java.base/share/classes/sun/security/jca/ProviderList.java#L453

![image](https://github.com/user-attachments/assets/1556585c-f11a-46c8-8159-d7274e6860a3)

The constructor simply assign the fields.

https://github.com/adoptium/jdk17u/blob/jdk-17.0.10%2B7/src/java.base/share/classes/java/security/Signature.java#L268

![image](https://github.com/user-attachments/assets/46308154-c6c2-4df6-85be-ab617fb8e779)

There is nothing in the list variable and the iterator has no next().
The code throws NoSuchAlgorithmException.

The java.security has the following settings:
ssl.KeyManagerFactory.algorithm=PKIX
ssl.TrustManagerFactory.algorithm=PKIX

This seems to be a issue in the JDK implementation. Line 400 in sun/security/jca/ProviderList.java.

How can we resolve the issue?

Thanks.

**Comment by dghgit** [comment]
You'll need to speak to Oracle, just supporting Bouncy Castle is enough, the JVM is well outside of our scope of influence. 

One thing, it could also be a class annotation issue, as in the class is "not found" as it not coming from a trusted class loader. How are the provider jars being added to the class path of the application?

**Comment by soon-leong** [comment]
We have been using Bouncy Castle for some time. The provider jars are on the class path as the rest of the third party components  for the application.

The providers are added as follows:
Security.addProvider(new BouncyCastleFipsProvider());
Security.addProvider(new BouncyCastleJsseProvider("fips:BCFIPS"));

**Comment by dghgit** [comment]
This says otherwise:

[SUN, SunRsaSign, SunEC, SunJSSE, SunJCE, SunJGSS, SunSASL, XMLDSig, SunPCSC, JdkLDAP, JdkSASL, SunMSCAPI, SunPKCS11]

Try using the module path and not the classpath.

**Comment by soon-leong** [comment]
Using the module path to specify the jar directory did not resolve the issue.

The issue is not due to missing providers.

The implementation in getServices() does not perform any operations with the list of providers. It will not matter what is in the list of providers.

There is another method getService() that performs the same operation in that class. The only difference is that that method returns a single implementation rather than a list of implementation for the getServices().

https://github.com/adoptium/jdk17u/blob/jdk-17.0.10%2B7/src/java.base/share/classes/sun/security/jca/ProviderList.java#L364

![image](https://github.com/user-attachments/assets/1e38d680-8a06-472d-b395-0d1de3b57c35)


The getService() method performs a search versus the other method which simply create a list without any search. This seems to confirm that the other method was not implemented correctly.

Do you agree that the above issue is due to the JDK implementation?

The JDK issue would impact all of us including other bouncy castle customers and it is hard to tell when that issue would be fixed by Oracle.

That chain of Java method invocations came from here.

https://github.com/bcgit/bc-java/blob/main/prov/src/main/java/org/bouncycastle/jcajce/util/DefaultJcaJceHelper.java#L104

![image](https://github.com/user-attachments/assets/b990035c-f5d9-493e-9c7c-d146c922f97c)


One possible workaround is to replace that line 107: Signature.getInstance(algorithm) with the method implementation from the JDK and change the getServices() to getService(). Is this possible?

**Comment by dghgit** [comment]
This isn't making any sense.

What do you get if you try running:

```
import java.security.Security;
import java.security.Signature;

import org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider;
import org.bouncycastle.jcajce.util.DefaultJcaJceHelper;
import org.bouncycastle.jcajce.util.JcaJceHelper;

public class SigTest
{
    public static void main(String[] args)
        throws Exception
    {
        Security.addProvider(new BouncyCastleFipsProvider());

        JcaJceHelper helper = new DefaultJcaJceHelper();

        Signature sig = helper.createSignature("SHA256WITHRSAANDMGF1");

        System.err.println(sig.getAlgorithm());
        System.err.println(sig.getProvider());
    }
}
```

**Comment by soon-leong** [comment]
David, thanks for your help!

The issue was indeed due to the missing providers for that section even though they were present elsewhere.

**Comment by dghgit** [comment]
Thanks. Glad to hear it is now working.
