### ISSUE TITLE
HQC implementations don't match round 4

### ISSUE THREAD

**Issue by celi0n** [bcgit/bc-java#1949]
The HQC post quantum KEM implementation in both Java and C# are not matching the reference implementation for round 4 https://pqc-hqc.org/implementation.html.  A sigma variable was added on round 3 (2023/04/30) to provide explicit rejection. bouncy castle implementations instead return `ss=0` when decapsulation failed 

https://github.com/bcgit/bc-java/blob/c349210fb47fc14c5fce604f3b4644caa47237a9/core/src/main/java/org/bouncycastle/pqc/crypto/hqc/HQCEngine.java#L266-L273

Be aware that there are 2 bugs in this part of the reference implementation (not fixed yet) that make it deviate from the specifications (https://github.com/open-quantum-safe/liboqs/security/advisories/GHSA-gpf4-vrrw-r8v7).

Also, the code is using non constant time comparison for u, v and d with `Arrays.equal` where the reference implementation (even in round 3) use constant time comparison with `vect_compare`.
https://github.com/bcgit/bc-java/blob/c349210fb47fc14c5fce604f3b4644caa47237a9/core/src/main/java/org/bouncycastle/pqc/crypto/hqc/HQCEngine.java#L251-L264

I don't report this as a security issue as bouncycastle's website states these are `available for experimenting`.

Célian Glénaz (Quarkslab)

**Comment by roy-basmacier** [comment]
Hey @celi0n,

I patched HQC to match the 2024-10-30 reference implementation along with the bug fix.

Thanks for the detailed report,
Roy

**Comment by dghgit** [comment]
New beta has been pushed to https://downloads.bouncycastle.org/betas/ updates should appear on github shortly.
