### ISSUE TITLE
DTLS error

### ISSUE THREAD

**Issue by yu123yue** [bcgit/bc-java#197]
07-07 10:59:16.794 5252-5471/com.test.nodepp.testudp I/System.out: (+1525ms) Received 15 byte datagram:
07-07 10:59:16.794 5252-5471/com.test.nodepp.testudp I/System.out:     15 FE FD 00 00 00 00 00-00 00 01 00 02 02 50
07-07 10:59:16.795 5252-5471/com.test.nodepp.testudp W/System.err: DTLS client received alert: fatal(2), internal_error(80)

Can you tell  me what the error?

**Comment by peterdettman** [comment]
No, that's not nearly enough information to be able to tell you the error. We can observe though that this error message was produced by a DTLS client and that the actual error is an internal_error at the server end. So you should look at the DTLS server to see why it sent a fatal alert.

**Comment by yu123yue** [comment]
ok，thank you
