### ISSUE TITLE
SHA256 RSAkeyPairGenerator

### ISSUE THREAD

**Issue by brubakerjeff** [bcgit/bc-java#200]
Hi,
I'm trying to work my way through this. I'm trying to modify the example RSAKeyPairGenerator.java to 
use SHA256 for hashing and AES for ciphering..

[https://github.com/bcgit/bc-java/blob/5fdb1face92f596300323c25cba9fe18726645e8/pg/src/main/java/org/bouncycastle/openpgp/examples/RSAKeyPairGenerator.java#L53](https://github.com/bcgit/bc-java/blob/5fdb1face92f596300323c25cba9fe18726645e8/pg/src/main/java/org/bouncycastle/openpgp/examples/RSAKeyPairGenerator.java#L53)

I switched the references from SHA1 to SHA256 and the reference from CAST5 to AES

    PGPDigestCalculator sha1Calc = new JcaPGPDigestCalculatorProviderBuilder().build().get(
          HashAlgorithmTags.**SHA1** can't seem to change);

    PGPKeyPair          keyPair = new JcaPGPKeyPair(PGPPublicKey.RSA_GENERAL, pair, new Date());

    PGPSecretKey        secretKey = new PGPSecretKey(
    PGPSignature.DEFAULT_CERTIFICATION, 
    keyPair, 
    identity,  
    sha1Calc, 
    null,  
    null, 
    new  JcaPGPContentSignerBuilder(
          keyPair.getPublicKey().getAlgorithm(),HashAlgorithmTags.**SHA1**->SHA256
    ),
    new JcePBESecretKeyEncryptorBuilder(PGPEncryptedData.**CAST5**->AES_128, 
       sha1Calc).setProvider("BC").build(passPhrase));

        
`

However changing  JcaPGPDigestCalculatorProviderBuilder results in the exception "only SHA1 supported for key checksum calculations" being thrown.
[https://github.com/bcgit/bc-java/blob/07469f7acc4dde2edf1924154dd336303b3cfeb6/pg/src/main/java/org/bouncycastle/openpgp/PGPSecretKey.java#L134](https://github.com/bcgit/bc-java/blob/07469f7acc4dde2edf1924154dd336303b3cfeb6/pg/src/main/java/org/bouncycastle/openpgp/PGPSecretKey.java#L134)

`
 throw new PGPException("only SHA1 supported for key checksum calculations.");
`

Is SHA256 supported for RSA Key generation?

Reading RFC 48800 I see it explicitly calls SHA-1 for the checksum? Do I only need to change the reference to SHA1 in JcaPGPContentSignerBuilder?

     - If the string-to-key usage octet is zero or 255, then a two-octet
       checksum of the plaintext of the algorithm-specific portion (sum
       of all octets, mod 65536).  If the string-to-key usage octet was
       254, then a 20-octet SHA-1 hash of the plaintext of the
       algorithm-specific portion.  This checksum or hash is encrypted
       together with the algorithm-specific fields (if string-to-key
       usage octet is not zero).  Note that for all other values, a
       two-octet checksum is required.

**Comment by bcgit** [comment]
Yes, leave the digest calculator used for the checksum calculation alone. Nothing good will happen if that one gets changed (at least at the moment), as you have found, it is hard coded in the standard.
