### ISSUE TITLE
TLS package differences

### ISSUE THREAD

**Issue by martiwi** [bcgit/bc-java#201]
Hi,

There is now a `org.bouncycastle.tls` package that contains all necessary classes to create a TlsClient or TlsServer and so one in addition to the already existing `org.bouncycastle.crypto.tls`

All files are duplicated but there is differences, what is the purpose and which one should we using ?
For example `TlsExtensionsUtils` class from `org.bouncycastle.tls` has some methods which are not available in the `TlsExtensionsUtils` class from `org.bouncycastle.crypto.tls`:
```
TlsExtensionsUtils#addClientCertificateTypeExtensionClient();
TlsExtensionsUtils#addServerCertificateTypeExtensionClient();
```
Also `TlsProtocol#offerOutput()` method is not available in package `org.bouncycastle.tls` but is defined in `org.bouncycastle.crypto.tls` package.

**Comment by bcgit** [comment]
Use org.bouncycastle.tls the older crypto.tls package will eventually be deprecated.

**Comment by martiwi** [comment]
Thanks.

**Comment by peterdettman** [comment]
FYI, TlsProtocol#offerOutput was renamed to writeApplicationData in the new API.
