### ISSUE TITLE
The function verifySignature of the class SM2Signer has something wrong

### ISSUE THREAD

**Issue by lvtaoleo** [bcgit/bc-java#202]
In your "jce-jdk12-157.jar", it is allowed that r and s can be n in the function verifySignature of class SM2Signer. However,  r∈[1,n-1] and s ∈[1,n-1] is one of the conditions that the Signature is right.

 if(var2.compareTo(ECConstants.ONE) >= 0 && **var2.compareTo(var4) <= 0**) {
            if(var3.compareTo(ECConstants.ONE) >= 0 && **var3.compareTo(var4) <= 0**) {......

I think it should be

if(var2.compareTo(ECConstants.ONE) >= 0 && **var2.compareTo(var4.subtract(ECConstants.ONE)) <= 0**) {
            if(var3.compareTo(ECConstants.ONE) >= 0 && **var3.compareTo(var4.subtract(ECConstants.ONE)) <=0**) {......

**Comment by bcgit** [comment]
Thanks for the report. You are absolutely correct. The fix for this should be appearing shortly and will be in 1.58.
