### ISSUE TITLE
close socket and then connect,it will appear java.net.PortUnreachableException

### ISSUE THREAD

**Issue by yu123yue** [bcgit/bc-java#206]
when i close socket, then Recreate socket and  connect,it will  throw exception java.net.PortUnreachableException all the time.Why?can you tell me

**Comment by peterdettman** [comment]
How does this question relate to the Bouncy Castle APIs?

**Comment by yu123yue** [comment]
yes,It appeared several times

**Comment by yu123yue** [comment]
sometime it  throw exception java.lang.NullPointerException: Attempt to invoke virtual method 'void org.bouncycastle.crypto.tls.DTLSTransport.send(byte[], int, int)' on a null object reference？why？please help me.

**Comment by peterdettman** [comment]
Not obviously BC-related. Closed.
