### ISSUE TITLE
org.bouncycastle.bcprov_1.52.0.v20161004-1854 jar file is corrupted.  

### ISSUE THREAD

**Issue by stevebrunton1** [bcgit/bc-java#211]
For Eclipse the org.bouncycastle.bcprov_1.52.0.v20161004-1854.jar file fails to install on all the mirrors that it tries to pull this from.  Something is wrong with this file. 

I was trying to install Vaadin Ecplise plugin where i discovered this.

**Comment by bcgit** [comment]
No idea on this one... Can you say exactly what the failure is, I may be able to suggest something.

**Comment by bcgit** [comment]
No further info.
