### ISSUE TITLE
IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.DERTaggedObject

### ISSUE THREAD

**Issue by IrynaZhumatiy** [bcgit/bc-java#213]
Hello All,
I use BouncyCastle 1.57 version, the next .jar files:
- bcprov-ext-jdk15on-1.57.jar
- bcpkix-jdk15on-1.57.jar
- bcmail-jdk15on-1.57.jar
- bcprov-jdk15on-1.57.jar.
I have some issue during call ASN1Sequence.getInstance.
My code:
`       ASN1Primitive obj = null;
        try {
            obj = (new ASN1InputStream(new ByteArrayInputStream(value)).readObject());
        }
        catch (java.io.IOException e) {
            SystemLog.logException("Failure while getting alternative sequence", e);
        }
        ASN1Sequence seq = ASN1Sequence.getInstance(obj);`
I get the exception:
Caused by: java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.DERTaggedObject
	at org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source).

Could you please help me with this?
What I do wrong?
Thanks!

Regards,
Iryna

**Comment by bcgit** [comment]
The object isn't a sequence. It might be a tagged sequence, but it isn't a sequence.

Also, use either bcprov-ext or bcprov - not both. You will get classpath conflicts otherwise.

**Comment by IrynaZhumatiy** [comment]
Thanks a lot.
I've resolved this exception.
It was my mistake.
The problem was in certificate.

**Comment by ibaskine** [comment]
@IrynaZhumatiy 
I am seeing similar exception so can you please explain what exactly was wrong with your certificate?

**Comment by IrynaZhumatiy** [comment]
@ibaskine I don't remember well.
I see in my code:
ASN1Primitive oct = null;
        try {
            oct = new ASN1InputStream(new ByteArrayInputStream(value)).readObject();
        }
        catch (java.io.IOException e) {
            SystemLog.logException("Failure while getting alternative sequence", e);
        }
        ASN1Sequence seq = ASN1Sequence.getInstance(oct);
The same when I created a ticket.
So I think I used an advice from @bcgit :
"_The object isn't a sequence. It might be a tagged sequence, but it isn't a sequence.
Also, use either bcprov-ext or bcprov - not both. You will get classpath conflicts otherwise._"
