### ISSUE TITLE
bcprov JAR should contain service loader declaration

### ISSUE THREAD

**Issue by hkalina** [bcgit/bc-java#215]
Would be useful if bcprov JAR would contain service declaration for ServiceLoader:

File `META-INF/services/java.security.Provider` in bcprov JAR should contain something like:
```
org.bouncycastle.jce.provider.BouncyCastleProvider
org.bouncycastle.pqc.jcajce.provider.BouncyCastlePQCProvider
```
This would allow more automatic loading of providers.

More info: https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html

**Comment by romanstrobl** [comment]
+1

**Comment by bcgit** [comment]
This is now done for 1.60.
