### ISSUE TITLE
Decryption on AIX with bouncycastle 1.54 is 2 times slower than decryption in 1.46, used with Java

### ISSUE THREAD

**Issue by vsborisova** [bcgit/bc-java#220]
For encryption and decryptoion is used SHA256 with 2048 key length certificate. Encyption speed is the same, while decryption is 2 times slower. Issue in not observed on Linux.

**Comment by bcgit** [comment]
I suspect part of the difference will be that 1.54 includes mitigation against Lenstra's CRT attack. This adds an extra modPow() I would have expected to see some slowdown on Linux as well though. The other difference will be that from their Java 1.7 JVM IBM moved to using Random.nextInt() to creating big integers from Random, not sure why, but it also happens to be the most expensive and least efficient way of using a SecureRandom. That may account for some of the difference as well as the mitigation includes creating a random value.

**Comment by vsborisova** [comment]
We see you have closed the previous ticket https://github.com/bcgit/bc-java/issues/220. Is there a workaround? Are you planning to fix the performance or implement an option to disable this additional check for Lenstra's CRT attack soon? The performance degradation causes real production problems.
