### ISSUE TITLE
A possible bug with TLS implementation

### ISSUE THREAD

**Issue by AlexITC** [bcgit/bc-java#223]
Hi,

I'm having some issues with the current BC implementation of TLS, specifically, at this part of the code [1], I'm using KeyStore Explorer [2] (KSE) app to create the Java KeyStore and the certificate.

I've generated a Java KeyStore with one Elliptic Curve (secp256r1) certificate inside, when executing some tests for TLS, the flow is getting to `ProvTlsServer#selectCredentials`, the cipher suite is matched to `KeyExchangeAlgorithm.ECDHE_ECDSA` and `keyType` variable gets the value `ECDHE_ECDSA`.

This means that when the code flow gets to this line [1] `km.chooseServerAlias(keyType, issuers, socket)`, the result value is null which breaks the flow with an exception. Turns out that my JKS doesn't have any alias with keyType = `ECDHE_ECDSA` but keyType = `EC`, I've changed that part of the code hard-coding 'EC' instead of `ECDHE_ECDSA` and everything is working as expected.

At this part, I think there should be a bug, it might be at KSE app or BC, based on what I read at [3], KSE app seems to be correct. Also, based on BC code, it seems to be correct as well.

Maybe any of you have a better idea of why is this happening.

Thanks.

References:

[1] - https://github.com/bcgit/bc-java/blob/master/tls/src/main/java/org/bouncycastle/jsse/provider/ProvTlsServer.java#L460

[2] - https://github.com/kaikramer/keystore-explorer/tree/master/kse/src/org/kse

[3] - http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html

**Comment by peterdettman** [comment]
It's a limitation of BCJSSE at the moment that it only works properly with our own "PKIX" KeyManagerFactory implementation. This can be configured by setting the default KMF type to "PKIX" in jre/lib/security/java.security:

ssl.KeyManagerFactory.algorithm=PKIX

(It may also be necessary to ensure BCJSSE provider entry is higher than other JSSE providers.)

AFAICT, the set of "keyType" strings that are meaningful to chooseServerAlias (et.al.) is documented by source code only. Studying the SunJSSE implementations reveals some problems, e.g.:

- "RSA" fails to distinguish encryption (RSA key exchange) from signing (*_RSA key exchanges), and accepts RSA keys with *either* key usage for *either* role.
- "EC" fails to distinguish key agreement (static ECDH_* key exchanges) from signing (*_ECDSA key exchanges) and requires *both* key usages for *either* role.

At present we use the name of the key exchange as the keyType, and our key manager understands those strings and can therefore make proper key usage distinctions. However we do want to find a way to still work with the SunX509 KMF (and others presumably). Suggestions welcome on how to get the best of both worlds without too much of a performance hit - one option is for our KeyManager to support a BC-specific interface that can be tested for at runtime.

**Comment by AlexITC** [comment]
Thanks a lot @peterdettman.
