### ISSUE TITLE
ANS1GeneralizedTime doesn't encode string 2017090721Z

### ISSUE THREAD

**Issue by mashintsev** [bcgit/bc-java#224]
GeneralizedTime must encode/decode values like this:

Local time only. **YYYYMMDDHH[MM[SS[.fff]]]**, where the optional fff is accurate to three decimal places.
Universal time (UTC time) only. **YYYYMMDDHH[MM[SS[.fff]]]Z**.
Difference between local and UTC times. **YYYYMMDDHH[MM[SS[.fff]]]+-HHMM**.
[info](https://www.obj-sys.com/asn1tutorial/node14.html)

But now ANS1GeneralizedTime doens't encode strings without minutes and seconds, like this 2017090721Z.

**Comment by mashintsev** [comment]
`import org.bouncycastle.asn1.ASN1GeneralizedTime;
import org.bouncycastle.asn1.DERSequenceGenerator;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.text.ParseException;

public class ASN1Test {
    public static void main(String[] args) throws IOException, ParseException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
        DERSequenceGenerator seqGen = new DERSequenceGenerator(bOut);

        seqGen.addObject(new ASN1GeneralizedTime("20170907210000Z"));
        seqGen.addObject(new ASN1GeneralizedTime("2017090721Z"));

        seqGen.close();
    }
}`

Exception in thread "main" java.lang.IllegalArgumentException: invalid date string: Unparseable date: "2017090721Z"
	at org.bouncycastle.asn1.ASN1GeneralizedTime.<init>(Unknown Source)
	at ASN1Test.main(ASN1Test.java:14)

**Comment by mashintsev** [comment]
#225

**Comment by bcgit** [comment]
Pull request processed.
