### ISSUE TITLE
#220 Status update

### ISSUE THREAD

**Issue by vsborisova** [bcgit/bc-java#226]
We see you have closed the previous ticket https://github.com/bcgit/bc-java/issues/220. Is there a workaround? Are you planning to fix the performance or implement an option to disable this additional check for Lenstra's CRT attack soon? The performance degradation causes real production problems.

**Comment by resuess** [comment]
As part of this request could we also get information about your support plans so that we can evaluate those? We'll need continued support on this issue until it can be resolved.

**Comment by bcgit** [comment]
You can get support details by emailing us at info@cryptoworkshop.com

**Comment by resuess** [comment]
Hello,
I sent an email asking for support pricing. Look forward to hearing back.

**Comment by resuess** [comment]
Thanks for the support information. We will be in contact soon.

**Comment by ava7ar** [comment]
Hello,

Can we get this one (or 220 respectively) reopened?

**Comment by bcgit** [comment]
It just occurs to me that this might be due to entropy exhaustion as well. Have you checked for that?

**Comment by ava7ar** [comment]
I really doubt that this is the case, considering this is observed on a production environment using /dev/urandom.
