### ISSUE TITLE
PBEWITHSHA-256AND128BITAES-CBC-BC encryption yields different results between v1.52 and v1.53 onwards

### ISSUE THREAD

**Issue by arunelengovan-okta** [bcgit/bc-java#230]
The key used is a PBEKey for the encryption and for the same data and same key it yields different encrypted output in v1.52 and a different one in all other version starting from v1.53 onwards.

**Comment by bcgit** [comment]
I'd have to see how it's been used. I seem to remember there was a fix to the IV handling around then, depending on how the key is been applied, it may be generating a different IV. It is still possible to reproduce the old behavior as well though.

**Comment by arunelengovan-okta** [comment]
For Key generation:
```
SecretKeyFactory pbeSecretKeyFactory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1");
PBEKeySpec keySpec = new PBEKeySpec(passPhrase.toCharArray(), salt, iterations, 256);//keyLength is 256
SecretKey pbeKey = pbeSecretKeyFactory.generateSecret(keySpec);
```
For performing crypto operation:
```
Cipher desCipher = Cipher.getInstance("PBEWITHSHA-256AND128BITAES-CBC-BC", "BC");
cipher.init(Cipher.ENCRYPT_MODE, pbeKey);
```
same input and same key in versions <= BC 1.52  gives one result and versions >=1.53 gives a different result.

**Comment by arunelengovan-okta** [comment]
**Second flavor** where I see a similar issue but here the difference is the `SecretKeyFactory` passes in the provider.

For Key generation:
```
SecretKeyFactory pbeSecretKeyFactory = SecretKeyFactory.getInstance("PBEWITHSHA-256AND128BITAES-CBC-BC", "BC");
PBEKeySpec keySpec = new PBEKeySpec(passPhrase.toCharArray(), salt, iterations, keyLength);
SecretKey pbeKey = pbeSecretKeyFactory.generateSecret(keySpec);
```
For performing crypto operation:
```
Cipher desCipher = Cipher.getInstance("PBEWITHSHA-256AND128BITAES-CBC-BC", "BC");
cipher.init(Cipher.ENCRYPT_MODE, pbeKey);
```

**Comment by bcgit** [comment]
Use:

        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS7Padding", "BC");
        cipher.init(Cipher.ENCRYPT_MODE, new SecretKeySpec(pbeKey.getEncoded(), "AES"), new IvParameterSpec(new byte[16]));

**Comment by arunelengovan-okta** [comment]
@bcgit thanks for the reply, three items I would like to clarify here.

(1) Is the above fix for both flavors of the issue I have mentioned? `<will update results of my test here>`

(2) Can you please point me to the commit which made this change in bcjava repo ? 

(3) I thought we internally used PKCS5 for the `PBEWITHSHA-256AND128BITAES-CBC-BC` cipher. Please feel free to correct me. I understand PKCS#5 padding is defined for 8-byte block sizes whereas PKCS#7 padding would work for any block size (I guess 1 to 255 bytes). But wish to know if I would face any side effect if we change from PKCS#5 to #7. A link to the code in bcjava repo would be useful for educational reasons.

**Comment by bcgit** [comment]
Note sure I follow, I get the same output for both. The code in the 1.52 version of the org.bouncycastle.jcajce.provider.symmetric.util.BaseBockCipher willl show you what the issue was.

PKCS5 and PKCS7 are implemented by the same class. org.bouncycastle.crypto.paddings.PKCS7Padding.

**Comment by arunelengovan-okta** [comment]
@bcgit 
If you look at my second issue again I would like to point out two major differences.
(1) keylength is 128 and not 256 like that of the first issue.
(2) Algo of key generation is different and "BC" is not passed in as provider.
```
// Note: Here I pass the provider "BC" explicitly.
SecretKeyFactory pbeSecretKeyFactory = SecretKeyFactory.getInstance("PBEWITHSHA-256AND128BITAES-CBC-BC", "BC");
PBEKeySpec keySpec = new PBEKeySpec(passPhrase.toCharArray(), salt, iterations, keyLength); //128 bit key
SecretKey pbeKey = pbeSecretKeyFactory.generateSecret(keySpec);

//current code: Cipher cipher = Cipher.getInstance("PBEWITHSHA-256AND128BITAES-CBC-BC", "BC");
//modified code works but without any alterations to the pbeKey
Cipher cipher = Cipher.getInstance("AES/CBC/PKCS7Padding", "BC");
cipher.init(Cipher.ENCRYPT_MODE, pbeKey); //pbeKey without wrapping with SecretKeySpec
// Also above I am not using the IV
```

**Comment by bcgit** [comment]
Ah, okay, sorry, have been in a bit of a rush of late... With the second one the algorithm is PKCS#12 which defines a mechanism for calculating an IV. In this case the calculated IV is passed internally as part of pbeKey. 

PKCS#5 schemes do not provide an IV, so the the HMAC scheme the IV needed to be provided explicitly. The wrong result with the PKCS#12 scheme and the IV occurred because in that situation if the IV is set, it is assumed to be because the user wished to override the generated one.

**Comment by arunelengovan-okta** [comment]
Gotcha! that makes sense. Thanks for confirming!
