### ISSUE TITLE
API changes review for BC Provider

### ISSUE THREAD

**Issue by lvc** [bcgit/bc-java#233]
The review of API changes for the BC Provider library since 1.46 version: https://abi-laboratory.pro/java/tracker/timeline/bcprov-jdk15on/

The report is updated three times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-tracker and https://github.com/lvc/japi-compliance-checker tools.

Thank you.

![bcprov-2](https://user-images.githubusercontent.com/1517837/31002370-67f1e32a-a4fb-11e7-895c-b8075f42273d.png)
![bcprov-1](https://user-images.githubusercontent.com/1517837/31002371-67f3080e-a4fb-11e7-901e-560694ca7041.png)

BC OpenPGP: https://abi-laboratory.pro/java/tracker/timeline/bcpg-jdk15on/
BC PKIX: https://abi-laboratory.pro/java/tracker/timeline/bcpkix-jdk15on/
BC S/MIME: https://abi-laboratory.pro/java/tracker/timeline/bcmail/

**Comment by cipherboy** [comment]
Thank you for the report. I do not think there is anything actionable here, so I'm going ahead and closing it out.
