### ISSUE TITLE
PGP keyring with non-standard EDDSA public key type cannot be imported

### ISSUE THREAD

**Issue by martijnbrinkers** [bcgit/bc-java#237]
If I try to import the attached key ring, PublicKeyPacket throws the following exception "unknown PGP public key algorithm encountered".

The PGP key has a non standard algorithm tag 22. According to https://tools.ietf.org/html/draft-koch-eddsa-for-openpgp-00 the alrgorithm number 22 is used for EdDSA

[unknown-pgp-public-key.asc.zip](https://github.com/bcgit/bc-java/files/1362765/unknown-pgp-public-key.asc.zip)

**Comment by bcgit** [comment]
I'm not sure what to do with this one... the RFC appears to have expired. The update process might leap back to life as EdDSA is becoming more widely supported.

**Comment by martijnbrinkers** [comment]
I'm actually not sure whether EdDSA is widely used with OpenPGP. However the main issue is not so much that BC does not support EdDSA, but that a keyring which has a non standard algorithm tag cannot be imported because an exception is raised. It would be nice to have if there would be some option of skipping unknown keys.

**Comment by bcgit** [comment]
Think we can do that. I'll have a look.

**Comment by bcgit** [comment]
I've added support for at least parsing these - the RFC shows them as having the same format as an ECDSA public key. It's starting to sound like we may have to deal with the signatures as well... I guess we'll find out.
