### ISSUE TITLE
Heap Inspection in HttpAuth

### ISSUE THREAD

**Issue by dkwakkel** [bcgit/bc-java#240]
The method hijack() in HttpAuth.java stores sensitive data in a String object, making it impossible to reliably purge the data from memory:

String userPass = username + ":" + new String(password);
answer.setHeader("Authorization", "Basic " + Base64.toBase64String(userPass.getBytes()));

Explanation: Sensitive data (such as passwords, social security numbers, credit card numbers etc) stored in memory can be leaked if memory is not cleared after use. Often, Strings are used store sensitive data, however, since String objects are immutable, removing the value of a String from memory can only be done by the JVM garbage collector. The garbage collector is not required to run unless the JVM is low on memory, so there is no guarantee as to when garbage collection will take place. In the event of an application crash, a memory dump of the application might reveal sensitive data.

**Comment by bcgit** [comment]
I've rewritten it to avoid the new String(). I should point out it still needs to create a string containing the password though when it sets the header, but I doubt the analyzer will pick that up.

I should also point out the explanation isn't terribly useful as it appears to be written by someone that has never read the JVM spec. The only sentence that is actually accurate is the last one - "In the event of an application crash, a memory dump of the application might reveal sensitive data." Both the garbage collector and threads reserve the right to copy and move memory as they need. While attempting to erase data by zeroing out arrays "narrows the window" the only thing you can be sure of is that you have zeroed out the copy you have access to. Note: I am not suggesting things shouldn't be zeroed out where possible anyway (it doesn't hurt), just that the reality is that if someone can get access to a memory dump there may still be sensitive data in it, even things an inspection of the code would suggest are, or should be, erased. 

Or put another way, no matter how "cleverly" an application may be written, poor deployment will still result in compromises of security.

**Comment by dkwakkel** [comment]
Thanks for removing the new String(). Agree this only narrows the window, for a security library I think that also counts. I guess answer.setHeader is also part of your internal api. If so you can add similar method which take byte[] (need to think about encoding) or char[] as argument then there is no need to convert to String. We ourselves have implemented a Secret class extending AutoClosable resulting in whipping out the data in the close method as soon as the Secret is no longer needed.
