### ISSUE TITLE
Maven Central is missing version 1.58 of bcprov-ext-debug-jdk15on

### ISSUE THREAD

**Issue by arakelian** [bcgit/bc-java#241]
The latest version of BC is 1.58.

As expected, you can download `bcprov-ext-jdk15on` from Maven Central:
http://repo2.maven.org/maven2/org/bouncycastle/bcprov-ext-jdk15on/

However, Maven Central only has up to version 1.57 on Maven Central:
http://repo2.maven.org/maven2/org/bouncycastle/bcprov-ext-debug-jdk15on/

**Comment by bcgit** [comment]
bcprov-ext-debug-jdk15on should now be available on Maven Central.
