### ISSUE TITLE
X509ExtensionUtils & AKI

### ISSUE THREAD

**Issue by wolftobias** [bcgit/bc-java#244]
When I read the [RFC5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.1) it`s saying to use as serial number the issuers certificate serial number. The X509ExtensionUtils.class is using the certificate itself serial number. I think that is a bug.

```
    public AuthorityKeyIdentifier createAuthorityKeyIdentifier(
        X509CertificateHolder certHolder)
    {
        if (certHolder.getVersionNumber() != 3)
        {
            GeneralName genName = new GeneralName(certHolder.getIssuer());
            SubjectPublicKeyInfo info = certHolder.getSubjectPublicKeyInfo();

            return new AuthorityKeyIdentifier(
                           calculateIdentifier(info), new GeneralNames(genName),
 --> certHolder.getSerialNumber() <-- );
        }
```

**Comment by owlstead** [comment]
RFC 5280 is about X.509v3. That statement reads: if not v3, then perform this code. Or am I missing something?

**Comment by bcgit** [comment]
It is using the issuer's serial number. The code is creating an authority key identifier from the passed in certificate, not an authority key identifier for the passed in certificate.

**Comment by wolftobias** [comment]
But "certHolder" is the passed in certificate and not the issuer, right?

**Comment by bcgit** [comment]
yes, that's right. That's why the code uses the "issuer" field not the the "subject".
