### ISSUE TITLE
ECGOST3410-2012-256 wrong paramset for oid 1.2.643.7.1.2.1.1.1

### ISSUE THREAD

**Issue by dpogibenko** [bcgit/bc-java#245]
In org.bouncycastle.asn1.cryptopro.ECGOST3410NamedCurves class used same parameter values for oid 1.2.643.7.1.2.1.1.1 as for oid 1.2.643.2.2.35.1. 
But according to document "р 50.1.114-2016" [https://tc26.ru/standard/rs/%D0%A0%2050.1.114-2016.pdf](url) values should be:
p = FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD97
a = C2173F1513981673AF4892C23035A27CE25E2013BF95AA33B22C656F277E7335
b = 295F9BAE7428ED9CCC20E7C359A9D41A22FCCD9108E17BF7BA9337A6F8AE9513
q = 400000000000000000000000000000000FD8CDDFC87B6635C115AF556C360C67
x = 91E38443A5E82C0D880923425712B2BB658B9196932E02C78B2582FE742DAA28
y = 32879423AB1A0375895786C4BB46E9565FDE0B5344766740AF268ADB32322E5C

**Comment by bcgit** [comment]
Thanks for the report. Even RFC 7863 says this. How embarrassing...

I've pushed the update and uploaded a new version of the provider to:

https://www.bouncycastle.org/betas

Would you confirm they are now correct? Thanks.

**Comment by dpogibenko** [comment]
Thanks a lot for prompt issue correction. Curve parameters are fine now.
Also thanks for English version of the regulatory document. My search in Google for this doc wasn't succesful.
