### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by Vzor-** [bcgit/bc-java#247]
I apologise if this already exists and I am too blind to find it, but I was wondering if you could add a version number constant to the code. 

Currently Bouncycastle is brought into our project via other libraries that package it. This, combined with the fact that many of our customers modify and repackage our code, makes it very hard to know if the version of Bouncycastle running in our customer's code is out of date. To fix this potential security issue we programmatically detect the versions of important libraries, but I can't figure out a way to get a version from Bouncycastle.

Thanks for your time and great lib.

**Comment by Vzor-** [comment]
When I try that, I get version 2.0.7, but that can't be right. Am I missing something?

**Comment by bcgit** [comment]
Try "new BouncyCastleProvider().getVersion()".

**Comment by Vzor-** [comment]
`new BouncyCastleProvider().getVersion()` Worked. Thanks for the help! 

I'm no expert, but I would have never found that method myself. I'm surprised it's not a static class right next to the license class.
