### ISSUE TITLE
Possible regression (1.52->1.53) causing java.security.InvalidAlgorithmParameterException?

### ISSUE THREAD

**Issue by alixwar** [bcgit/bc-java#249]
Hi,
upgrading bcprov-jdk15on beyond 1.52 causes a `java.security.InvalidAlgorithmParameterException` when built on some JDKs: https://github.com/robolectric/robolectric/issues/3288#issuecomment-338658566

Is this a regression in BouncyCastle or is 1.53 stricter somehow (or is the issue in the JDKs)?

**Comment by bcgit** [comment]
I'd need some more details, but in this case I'd suspect is that what's happened is that we've added something between the 2 releases, and the Sun code (from the look of it) has been written assuming their implementation is always the only one that would come back. 

The work on EC AlgorithmParameters is probably the chief suspect. The implementation was added around then, prior to that the BC provider would not have returned an implementation. You might find the issue vanishes if you go up a couple more versions.

**Comment by alixwar** [comment]
@bcgit Actually 1.58 does not work either, but the first version not to work is 1.53. Source: https://github.com/robolectric/robolectric/issues/3288#issuecomment-338658566

**Comment by bcgit** [comment]
A look on grep code indicates that the only an object identifier is accepted in the key parameters for the method concerned. What algorithm parameters are associated with the private key involved?

**Comment by premek** [comment]
FYI for me 1.58 breakes SSL handshake while 1.52 works, both on the same version of openjdk. I will provide more info if possible. Via robolectric/robolectric/pull/3482

**Comment by bcgit** [comment]
It still doesn't suggest an issue with BC (yet), although it still points to a misuse of the EC parameters class. How is the private key being generated? As I've already pointed out it's clear from grep code that the agreement calculator only accepts keys with OID parameters.

**Comment by bcgit** [comment]
Closed as it appears not to be a BC issue.
