### ISSUE TITLE
Decryption on AIX with bouncycastle 1.54 is 2 times slower than decryption in 1.46, used with Java

### ISSUE THREAD

**Issue by ava7ar** [bcgit/bc-java#253]
Ref. [#220](https://github.com/bcgit/bc-java/issues/220); [#226](https://github.com/bcgit/bc-java/issues/226)
[](url)
We have tried to comment out the fix for the Lenstra's CRT attack - the performance gain was insignificant - about 10% in comparison to the 50% degradation.

**Comment by ava7ar** [comment]
Any updates?

**Comment by bcgit** [comment]
Now closed. Appeared to be related to not using buffered streams.
