### ISSUE TITLE
BCPKCS12KeyStore and BCPKCS12KeyStore3DES do not use registered BouncyCastleProvider

### ISSUE THREAD

**Issue by tillmannseidel** [bcgit/bc-java#258]
When classes `BCPKCS12KeyStore` or `BCPKCS12KeyStore3DES` are instantiated, the always use a new instance of `BouncyCastleProvider`. They should check first whether a `BouncyCastleProvider` instance has already been registered at java.security.Security, and use that one if available.

Please note that this is not only a cosmetic code change to make sure all access to the `BouncyCastleProvider` happens the same way. Be aware that the current implementation may cause severe problems in a container environment that uses class loaders to separate modules (like OSGi or Tomcat). Since the two classes mentioned above never use the registered provider, they might cause ugly exceptions because of class loading issues.

**Comment by bcgit** [comment]
fixed.
