### ISSUE TITLE
NPE with BC >= 1.56 using as provider at position #1

### ISSUE THREAD

**Issue by sopgreg** [bcgit/bc-java#259]
Hi,

we're currently migrating BC 1.46 (jdk16) to 1.58 (jdk15on). Until now, we installed BC as provider at position nr. 1 using `Security.insertProviderAt(new BouncyCastleProvider(), 1);` This happened during the deployment phase of our application inside of the RedHat JBoss Application Server.

After migration to 1.58 we receive a NPE while verifying a signature using `Signature#initVerify` (see Stacktrace attached).

We boiled down this problem to the addition of the `org.bouncycastle.jcajce.provider.drbg.DRBG` class in BC 1.56. Up to 1.55 everything works as expected.

Are there any known issues using BC as provider nr. 1 in such a context or is this a bug?

Regards
Greg
[stacktrace.txt](https://github.com/bcgit/bc-java/files/1495591/stacktrace.txt)

**Comment by bcgit** [comment]
Can't say we've seen that before... hmmm. Try the beta on https://www.bouncycastle.org/betas we might have accidently fixed it.

**Comment by sopgreg** [comment]
Beta 159b08 indeed "accidentally" fixes the bug 👍 
Any ETA on the 1.59 release?

**Comment by bcgit** [comment]
Thanks for the feedback. Should be out around the 26th of December.
