### ISSUE TITLE
EC5Util.convertPoint() ignores withCompression parameter

### ISSUE THREAD

**Issue by str4d** [bcgit/bc-java#262]
Introduced in version 1.53 by this change: https://github.com/bcgit/bc-java/commit/8b015046cd1a7232bce578a51d70353c4e47f73b#diff-e02d61345a013a87477324efd23eff27R166

I worked around this in my own code (by implementing `convertPoint()` myself), and confirmed that the underlying code still respects `withCompression`.

**Comment by peterdettman** [comment]
This has finally been addressed as part of a rework of point compression, however the `convertPoint` method itself, while fixed, is now also deprecated (a new method has been added without the `boolean withCompression` parameter).

Looking at the i2p commit mentioned above, the reflection usage is hiding other deprecations too. Both `ECCurve.createPoint(BigInteger, BigInteger, boolean)` and `ECPoint.getEncoded()` are deprecated.

After our next release, I would suggest you change to using `EC5Util.convertPoint(ECParameterSpec, ECPoint)` followed by `ECPoint.getEncoded(boolean)`, passing your `withCompression` parameter in the `getEncoded` call.

**Comment by peterdettman** [comment]
Appears to be resolved.
