### ISSUE TITLE
Base64Encoder.decode fails if whitespace is in within 4 last characters

### ISSUE THREAD

**Issue by bjakke** [bcgit/bc-java#263]
#236 is similar (just mentioning, because that I found via google, however this is an actual bug)

Debugged on (happens in the normal version, but it seems this is needed to step the code)

  	<dependency>
  		<groupId>org.bouncycastle</groupId>
  		<artifactId>bcprov-debug-jdk15on</artifactId>
  		<version>1.58</version>
  	</dependency>

Base64Encoder.decode(String, OutputStream) does subtract 4 from the end index 'int finish'. This finish variable is then used to determine where to end the stream in nextI(String, int, int) in addition to the whitespace skipping part (ignore(char)). 

I have inputted a string read from a file (I probably cannot share that, if this explanation is not enough I can try to make a test string). The last characters are as following (i.e. the line is changed before the last 3 characters and the line is prefixed with spaces):

* Index 6312 'C'
* Index 6313 '\r'
* Index 6314 '\n'
* Index 6315-6322 is spaces ' '
* Index 6323 'g'
* Index 6324-6325 '='

The while loop copied below from the method:
```
        while (i < finish)
        {
            b1 = decodingTable[data.charAt(i++)];
            
            i = nextI(data, i, finish);
            
            b2 = decodingTable[data.charAt(i++)];
            
            i = nextI(data, i, finish);
            
            b3 = decodingTable[data.charAt(i++)];
            
            i = nextI(data, i, finish);
            
            b4 = decodingTable[data.charAt(i++)];

            if ((b1 | b2 | b3 | b4) < 0)
            {
                throw new IOException("invalid characters encountered in base64 data");
            }
```

This means the finish is 6322 as end is 6326. The b1 will be C, then the nextI `should` loop until 6323 to get to the next one 'g' however the finish condition happens before that and instead the space at 6322 is read for b2 resulting the invalid characters exception. 
 
EDIT: I should probably add that if I remove whitespaces manually before entering the String everything works.

**Comment by bjakke** [comment]
Hmm actually it might be something else as even the while block should stop before the finish as the last block is decoded after it.

**Comment by bjakke** [comment]
Created attached junit4 test that can at least reproduce the exception:

```
package test;

import org.bouncycastle.util.encoders.Base64Encoder;
import org.junit.Test;

public class Base64Test {

  @Test
  public void test() throws Exception {
    String data = "dGVzdHN0cmluZw==";
    Base64Encoder enc = new Base64Encoder();
    enc.decode(data, System.out);
    System.out.println("\n");
  }

  @Test
  public void testWithWhitespace() throws Exception {
    String data = "dGVzdHN0cmluZ" + "\r\n" + "               " + "w==";
    Base64Encoder enc = new Base64Encoder();
    enc.decode(data, System.out);
    System.out.println("\n");
  }

}
```
(not that pretty, but should be enough here)

The test() will output "teststring" and the testWithWhitespace() will fail on 
```
java.io.IOException: invalid characters encountered in base64 data
	at org.bouncycastle.util.encoders.Base64Encoder.decode(Base64Encoder.java:251)
	at test.Base64Test.testWithWhitespace(Base64Test.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```

**Comment by bjakke** [comment]
I think I know why this happens now. On the testWithWhitespace the data is 33 characters, so end is index 33. therefore finish is 29. Because of the whitespaces, the last block actually begins on index 12 already ('Z') then there is whitespace and then the last 3 characters "w==". No idea how this could be solved (impossible to know where last block begins if there is whitespaces) unless the whitespaces are replaces before decoding anything.

**Comment by bcgit** [comment]
I think this now fixed.
