### ISSUE TITLE
CertPath::evaluate returns no actual result

### ISSUE THREAD

**Issue by egelke** [bcgit/bc-java#264]
The class `org.bouncycastle.cert.path.CertPathValidationResultBuilder` is basically unimplemented, therefore the method `org.bouncycastle.cert.path.CertPath::evaluate` yields no usable result.

**Comment by bcgit** [comment]
This is now somewhat improved in 1.59 (I hope...). Would appreciate further feedback on this one - as you've probably realized this API item is sort of in the "drop on"/"drop off" state at the moment.

**Comment by bcgit** [comment]
Closed as complete for now.
