### ISSUE TITLE
This TLS support sm2?

### ISSUE THREAD

**Issue by XShandow** [bcgit/bc-java#269]
I see the information about sm2 in the "release notes".But I can not found corresponding ciphersuite in the ‘CipherSuite’ class. Can you give me some help?
Thank you very much.

**Comment by peterdettman** [comment]
Our TLS libraries currently only support IETF cipher suites. I guess you are wanting to use some cipher suites like are mentioned [here](https://github.com/guanzhi/GmSSL/blob/master/README.md), but I don't think any of these are IETF-standardised. On the other hand, it is not too difficult to extend our TLS implementation to support additional user-defined cipher suites, and we have implementations of the underlying SM2/SM3/SM4 algorithms, so perhaps it can work for you.

**Comment by XShandow** [comment]
Thanks for your help.You are right.I will add user-defined cipher suits.Is there an example or document?

**Comment by peterdettman** [comment]
The only example is the implementation itself. I suggest choosing a similar IETF cipher suite to the one you want to add (something like TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256), and seeing how it is referenced in the code, and how it is mapped to the underlying crypto algorithms.

I should say that if you do not understand TLS very well, actually this may not be so easy.

**Comment by changhr2013** [comment]
Is there any plan to support RFC-9998？
