### ISSUE TITLE
SHA1Digest has bad bit-mask when constructing bi-tlength int32

### ISSUE THREAD

**Issue by michael-g** [bcgit/bc-java#272]
File:`core/src/main/java/org/bouncycastle/crypto/digests/SHA1Digest.java` (line [113](https://github.com/bcgit/bc-java/blob/5b1ad7dc7f97a9296b08b9a052224dc4a06f38a6/core/src/main/java/org/bouncycastle/crypto/digests/SHA1Digest.java#L113))

IntelliJ warned about this. In the method `processLength`, the `long` value `bitLength` needs to be written into two `int` values. The higher order `int` is correctly created using `bitLength >>> 32`, but the masking of the lower-order bytes is ineffective: the constant mask value is sign-extended to be `-1L`.
```
bitLength & 0xffffffff
```
Tto make the code-inspection warning disappear, this needs to be 
```
bitLength & 0xffffffffL
```
However, the cast to `(int)` gives the correct result in the end, which begs the question about the necessity of doing the masking operation at all. 

Thanks for all your time and effort, excellent work.

Mike

**Comment by peterdettman** [comment]
Thanks, Mike. Indeed the masking is unnecessary anyway and it has been removed.
