### ISSUE TITLE
DH KeyPairGenerator yields exception when using default M(160)

### ISSUE THREAD

**Issue by houz42** [bcgit/bc-java#274]
I am using DH in BouncyCastle for secret key generation, and exception rises when using default DHParamterSpec to init a KeyPairGenerator as in sample code from [here](http://www.java2s.com/Tutorial/Java/0490__Security/DiffieHellmanKeyAgreement.htm).

below code 
```java
    package me.hou.play.crypto;
    
    import java.math.BigInteger;
    import java.security.KeyPair;
    import java.security.KeyPairGenerator;
    import java.security.SecureRandom;
    import java.security.Security;
    import javax.crypto.KeyAgreement;
    import javax.crypto.spec.DHParameterSpec;
    
    public class MinimalClass {
    
        private static BigInteger p = new BigInteger("16560215747140417249215968347342080587", 16);
        private static BigInteger g = new BigInteger("1234567890", 16);
    
        public static void main(String[] args) throws Exception {
            Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());
    
            DHParameterSpec serverParam = new DHParameterSpec(p, g);
            KeyPairGenerator keyGen = KeyPairGenerator.getInstance("DH", "BC");
            keyGen.initialize(serverParam, new SecureRandom());
    
            KeyAgreement serverAgree = KeyAgreement.getInstance("DH", "BC");
            KeyPair pair = keyGen.generateKeyPair();
            serverAgree.init(pair.getPrivate());
        }
    }
```
will yield exceptions as follow:

```
   Exception in thread "main" java.lang.IllegalArgumentException: 'min' may not be greater than 'max'
	at org.bouncycastle.util.BigIntegers.createRandomInRange(Unknown Source)
	at org.bouncycastle.crypto.generators.DHKeyGeneratorHelper.calculatePrivate(Unknown Source)
	at org.bouncycastle.crypto.generators.DHBasicKeyPairGenerator.generateKeyPair(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.dh.KeyPairGeneratorSpi.generateKeyPair(Unknown Source)
	at me.hou.play.crypto.MinimalClass.main(MinimalClass.java:24)
```

And [this post](http://bouncy-castle.1462172.n4.nabble.com/DH-not-working-after-changing-bcprov-jdk16-137-jar-to-bcprov-jdk16-145-jar-td2967661.html) suggests using a smaller M, which is l in the DHParameterSpec Object. 

Changing line 19 to 

    DHParameterSpec serverParam = new DHParameterSpec(p, g, 128);

will work.

The difference here as my digging into the bouncy castle code is, if initializing a DHParameterSpec without the third parameter(l),  `DHParameters` initialized in `org.bouncycastle.jcajce.provider.asymmetric.dh.KeyPairGeneratorSpi.initialize(AlgorithmParameterSpec, SecureRandom random)` will use `DEFAULT_MINIMUM_LENGTH`(160) as filed m, otherwise it will use smaller one of l or DEFAULT_MINIMUM_LENGTH. And when using the default one, there will be a exception.

I am using bcprov-jdk15on-1.58 on jdk1.8, and the same problem is seen on much older versions.

**Comment by bcgit** [comment]
I've improved the exception. I didn't adjust the minimum down as the group parameters in this case have a security strength of around 9 bits (that's probably generous), however I can see why, for the sake of example, it might be desired to create such keys but they do require a specific l value.

The sample code referred to at the start is frankly appalling, as it fails to show what legitimate (p, g) parameters look like. I just pray that no-one has simply cut and pasted it into production...
