### ISSUE TITLE
Questions to closed issue #278

### ISSUE THREAD

**Issue by Novaax** [bcgit/bc-java#280]
Hello,

Did we have the possibility to get the faulty certificate or to find out the alias? Can the error message still be modified by the alias of the faulty certificate?

**Comment by bcgit** [comment]
The error's happening too far from the certificate to determine what the certificate is. If you have a set of certificates just try doing a getPublicKey on each one and wait for it to explode. Alternately looking at a dump of the certificate data will also show the problem - there'll be an improperly encoded ASN.1 Integer.
