### ISSUE TITLE
Can bcprov-jdk15on-1.5x.jar and bc-fips-1.0.0.jar coexist in same JVM?

### ISSUE THREAD

**Issue by lachezar-angelov** [bcgit/bc-java#282]
Hello,

we're having issues with BouncyCastleProvider and BouncyCastleFipsProvider loaded in same JVM:
```
Security.addProvider(new BouncyCastleFipsProvider());
Security.addProvider(new BouncyCastleProvider());
```
The problem lies in the fact that there are a lot of classes with identical names in both jars, but some of them differ binary.

Depending the order of jars in CLASSPATH different version of those classes are found and strange behavior is observed.
For example:
```
Caused by: java.lang.NoSuchFieldError: id_sha3_224
	at org.bouncycastle.jcajce.provider.ProvSHS$SHA3_224.configure(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	...
```
But the field is present in the "other" version of NISTObjectIdentifiers interface.

Is there a way to have both BC providers in a JVM?

**Comment by bcgit** [comment]
No.

**Comment by mapineiro** [comment]
Can you explain a bit more? I need to use FIPS and non- FIPS, Its imposible? Thank you

**Comment by bcgit** [comment]
Yes, it's impossible. This is really in the "be careful what you wish for though" - why do you need to use both?

**Comment by complanboy2** [comment]
Let's take a scenario where we use OpenSAML 3.4.0 which used bcprov-jdk15on. And now, independently if we want to upgrade BC to BC-FIPS 1.0.2, how do we ensure that OpenSAML is not breaking ?
