### ISSUE TITLE
Elliptic Curve Schnorr Signature Identification

### ISSUE THREAD

**Issue by Xor-el** [bcgit/bc-java#285]
Hi,
Are there any plans to implement Elliptic Curve Schnorr Signature Identification in Bouncy Castle Java??

**Comment by peterdettman** [comment]
Did you have a particular specification in mind, or interoperability with some other software?

**Comment by Xor-el** [comment]
Any specification at all or something similar to this

https://github.com/OkCupid/sfslite/blob/master/crypt/schnorr.C

Just for key creation, signing and verifying.
Thanks..

**Comment by Xor-el** [comment]
So long as it allows using custom curves like secp256k1

**Comment by Xor-el** [comment]
@peterdettman , any updates please??

**Comment by peterdettman** [comment]
As much as it's something we would like to have, we already have far too much on our plate to be able to do this in the short term, so I would have to answer that there are no plans.

**Comment by Xor-el** [comment]
Ok thanks for replying.
When I Implement it, I will contribute to BC Csharp and hope someone would backport it to java.
Regards.

**Comment by erikzhang** [comment]
@Xor-el Hi, did you implement it in BC CSharp? Where can I find it?

**Comment by Xor-el** [comment]
@erikzhang , yes I did implement it according to sipa's specifications found here [Schnorr Sipa](https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki) but unfortunately not in CSharp.

Luckily someone did implement it in CSharp, you can find it [here](https://github.com/MetacoSA/NBitcoin/search?utf8=✓&q=Schnorr&type=)

**Comment by erikzhang** [comment]
Thank you very much!

**Comment by Polve** [comment]
Is there any news about Schnorr support?

I heard Bitcoin Verde created a Java implementation and it would be great if it could be integrated in BC.

**Comment by KovacZan** [comment]
Is there any news about Schnorr signature support in 2020?

**Comment by Giszmo** [comment]
Is there any news about this in 2022?

**Comment by deavmi** [comment]
Schnorr support 2024? Please :), I will pay 25 USD for it

**Comment by deavmi** [comment]
> Is there any news about this in 2022?

Did you ever find an alternative?

**Comment by msgilligan** [comment]
> Schnorr support 2024? Please :), I will pay 25 USD for it

Is that offer still open? 🤣

There is actually a newer, still-open Issue for "Support Schnorr signatures": 

* Issue #1114

In a comment on 1114, I provide information and a link to bitcoinj's new Schnorr-capable secp256k1-jdk library: 

* https://github.com/bcgit/bc-java/issues/1114#issuecomment-4396371302

**Comment by deavmi** [comment]
It may be, but I will need some time to develop some code to see where I last stopped.

And remember, I will pay for non-AI coded slop. 

On 07 May 2026 12:39:42 SAST, Sean Gilligan ***@***.***> wrote:
>msgilligan left a comment (bcgit/bc-java#285)
>
>> Schnorr support 2024? Please :), I will pay 25 USD for it
>
>Is that offer still open? 🤣
>
>There is actually a newer, still-open Issue for "Support Schnorr signatures": 
>
>* Issue #1114
>
>In a comment on 1114, I provide information and a link to bitcoinj's new Schnorr-capable secp256k1-jdk library: 
>
>* https://github.com/bcgit/bc-java/issues/1114#issuecomment-4396371302
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bcgit/bc-java/issues/285#issuecomment-4396379682
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

----
Tristan B. Velloza Kildaire

Web: https://deavmi.assigned.network
BNET IRC: deavmi
Email: ***@***.***

**Comment by msgilligan** [comment]
> It may be, but I will need some time to develop some code to see where I last stopped.
> 
> And remember, I will pay for non-AI coded slop.

It's artisanally hand-coded in California!

It is a serious project and has been getting code reviewed by developers of major Bitcoin wallets. We don't need the $25, but if you test it out feel free to open an issue or PR if you have ideas or enhancements.

A release is coming soon. I will announce it in Issue #1114.
