### ISSUE TITLE
Question in DES_ECB with padding

### ISSUE THREAD

**Issue by OumaSyuu** [bcgit/bc-java#290]
Hi, I want to use this library for encryption like DES_ECB with padding. But it didn't work well for me. Did I do it wrong?
![tim 20180210163127](https://user-images.githubusercontent.com/14196120/36060237-660cea2a-0e80-11e8-8638-b9f17cb7736b.png)

**Comment by bcgit** [comment]
You need to call doFinal() to complete the encryption.

**Comment by OumaSyuu** [comment]
Got it, tkx
