### ISSUE TITLE
AES-256-CFB padding incompatible with OpenSSL

### ISSUE THREAD

**Issue by dgolombek** [bcgit/bc-java#291]
I have some data that was encrypted with BouncyCastle 1.54-1.56, and have been trying to decrypt it with OpenSSL. This has been failing, and it appears to be due to mismatches in the view of blocksize for padding in CFB mode. OpenSSL takes the view that in CFB mode, blocksize is always 1, and no padding is ever applied. BouncyCastle treats AES-256 as always having a 128 bit blocksize, despite being in CFB mode, and so padding is applied. 

If my data was encrypted in OpenSSL, I could work with it in BouncyCastle by using NoPadding mode, but since OpenSSL doesn't allow me to change blocksize of a cipher, there doesn't seem to be a way for me to work with BC encrypted data in OpenSSL.

If I read the 2.49.2 release notes correctly, this may be intentional, but it feels like a very bad incompatibility to me. I'm happy to provide code to replicate this on either the BouncyCastle or OpenSSL side, but given that AES BC code hardcodes the blocksize to 128 bits for CFB mode, I'm not sure it's important.

**Comment by bcgit** [comment]
BC offers CFB8 and CFB128, there's no padding, but the way the cipher is used varies. OpenSSL also offers CFB1 which is different again. The equivalents for OpenSSL to the two BC modes are:
 aes-[128|192|256]-cfb	128/192/256 bit AES in 128 bit CFB mode - "CFB", or "CFB128"
 aes-[128|192|256]-cfb8	128/192/256 bit AES in 8 bit CFB mode - "CFB8"

**Comment by dgolombek** [comment]
The difference is that BouncyCastle is happy to apply padding if you tell it to, while OpenSSL will not apply padding even with a call to EVP_CIPHER_CTX_set_padding (since it views padding as being on by default, but with a 1 byte block size). This is true for all CFB block sizes -- CFB1, CFB8, and CFB128.

A wrapper library I was using was setting the padding mode automatically and incorrectly, so the true bug is in that library. The real bug here is in that library, and I'm working with them to fix it. I think the BC behavior is defensible, but still different from OpenSSL.

```java
        SecretKeySpec secretKey = new SecretKeySpec("ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP".getBytes(), "AES");
        IvParameterSpec ivParameterSpec = new IvParameterSpec("ABCDEFGHIJKLMNOP".getBytes());
        Cipher cipher = Cipher.getInstance("AES/CFB/PKCS5Padding");
        cipher.init(Cipher.ENCRYPT_MODE, secretKey, ivParameterSpec);
        byte[] out = cipher.doFinal("A".getBytes());
        System.out.println("Ciphertext length: " + out.length);
```

This prints "Ciphertext length: 16"

```c
    unsigned char ciphertext[128];
    int length;
    int totallength;
    unsigned char *key = (unsigned char *)"ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP";
    unsigned char *iv = (unsigned char *)"ABCDEFGHIJKLMNOP";
    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    EVP_EncryptInit_ex(ctx, EVP_aes_256_cfb(), NULL, key, iv);
    EVP_EncryptUpdate(ctx, ciphertext, &length, (unsigned char *)"A", 1);
    // This call has no effect
    EVP_CIPHER_CTX_set_padding(ctx, 1);
    totallength = length;
    EVP_EncryptFinal_ex(ctx, ciphertext + length, &length);
    totallength += length;
    printf("Ciphertext length: %d\n", totallength);
```

This prints "Ciphertext length: 1"

**Comment by bcgit** [comment]
This issue now appears to be resolved.
