### ISSUE TITLE
error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by Karathra** [bcgit/bc-java#292]
Hi 
I am getting an error as below while trying to use the BC provider,
<error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC>]^M
------------>>!StackTrace
}
java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
        at java.security.KeyStore.load(KeyStore.java:1226)

kindly request you to please provide any clue on this issue.

**Comment by bcgit** [comment]
The provider jar has either been loaded by an untrusted class loader or the signature has been removed.
