### ISSUE TITLE
ava.lang.IllegalArgumentException: Digest SHA-1 unsupported

### ISSUE THREAD

**Issue by Karathra** [bcgit/bc-java#293]
Hi
while trying to load the BC provider i am getting the below error 

[<Error Message>: <error constructing MAC: java.lang.IllegalArgumentException: Digest SHA-1 unsupported>]^M             
------------>>!StackTrace
}
java.io.IOException: error constructing MAC: java.lang.IllegalArgumentException: Digest SHA-1 unsupported
        at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
        at java.security.KeyStore.load(KeyStore.java:1226)
can anyone help me to get some clue on this issue

**Comment by bcgit** [comment]
The only thing I can think of here is that there are two versions of BC installed on the classpath so a class annotation issue is resulting in a failure to load the digest implementation.

**Comment by bcgit** [comment]
No further info.
