### ISSUE TITLE
Base64Encoder fails to decode small strings

### ISSUE THREAD

**Issue by flooey** [bcgit/bc-java#295]
If you pass a string or byte array with less than 4 characters in it to either overload of `Base64Encoder.decode()`, it throws a {String,Array}IndexOutOfBoundsException, because the call to `decodeLastBlock` assumes that the last 4 characters can be indexed out of the string or array.  A simple reproduction case:

```java
ByteArrayOutputStream out = new ByteArrayOutputStream();
Base64Encoder encoder = new Base64Encoder();
encoder.decode("", out);
```

**Comment by bcgit** [comment]
I can see how that would be annoying. I've fixed it to return 0, or [] for zero length data. Updates should appear shortly,
