### ISSUE TITLE
OperatorCreationException: exception on setup: java.security.NoSuchAlgorithmException: no such algorithm: SHA1WITHRSA for provider BC

### ISSUE THREAD

**Issue by IrynaZhumatiy** [bcgit/bc-java#297]
Hello All,
Could you please help me with such issue:

> 2018-02-13 14:21:02,238| SSO ERROR  [http-nio-8080-exec-14]: [id: 20180129.2142]PKCS#7 failure in certificate extraction.
> org.bouncycastle.cms.CMSException: can't create digest calculator: exception on setup: java.security.NoSuchAlgorithmException: no such algorithm: SHA1WITHRSA for provider BC
> 	at org.bouncycastle.cms.SignerInformation.doVerify(Unknown Source)
> 	at org.bouncycastle.cms.SignerInformation.verify(Unknown Source)
> 	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.apache.soap.server.MessageRouter.invoke(MessageRouter.java:56)
> 	at org.apache.soap.providers.MsgJavaProvider.invoke(MsgJavaProvider.java:125)
> 	at org.apache.soap.server.http.MessageRouterServlet.doPost(MessageRouterServlet.java:379)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
> 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: org.bouncycastle.operator.OperatorCreationException: exception on setup: java.security.NoSuchAlgorithmException: no such algorithm: SHA1WITHRSA for provider BC
> 	at org.bouncycastle.operator.jcajce.JcaDigestCalculatorProviderBuilder$1.get(Unknown Source)
> 	at org.bouncycastle.cms.SignerInformationVerifier.getDigestCalculator(Unknown Source)
> 	... 43 more
> Caused by: java.security.NoSuchAlgorithmException: no such algorithm: SHA1WITHRSA for provider BC
> 	at sun.security.jca.GetInstance.getService(Unknown Source)
> 	at sun.security.jca.GetInstance.getInstance(Unknown Source)
> 	at java.security.Security.getImpl(Unknown Source)
> 	at java.security.MessageDigest.getInstance(Unknown Source)
> 	at org.bouncycastle.jcajce.util.NamedJcaJceHelper.createDigest(Unknown Source)
> 	at org.bouncycastle.operator.jcajce.OperatorHelper.createDigest(Unknown Source)
> 	... 45 
> 
> > more
> 

My code:
```
            Security.addProvider(new BouncyCastleProvider());
            CMSSignedData           signedData = new CMSSignedData(pkcs7Buffer);
            Store                   certStore = signedData.getCertificates();
            SignerInformationStore  signers = signedData.getSignerInfos();
            Collection              c = signers.getSigners();
            Iterator                it = c.iterator();
            while (it.hasNext()) {
                SignerInformation   signer = (SignerInformation) it.next();
                Collection          certCollection = certStore.getMatches(signer.getSID());
                if (certCollection.isEmpty()) {
                    continue;
                }
                else { // use the certificates included in the signature for verification
                    Iterator certIt = certCollection.iterator();
                    X509Certificate cert = new JcaX509CertificateConverter().setProvider(PROVIDER)
                            .getCertificate((X509CertificateHolder)certIt.next()); 
                    boolean isVerified = signer.verify(new JcaSimpleSignerInfoVerifierBuilder().setProvider(PROVIDER).build(cert));
                    if (isVerified) {
                        return cert;
                    } else if (verifyByHand(signer, cert, hashingAlgorithm)) {
                        return cert;
                    }
                }
            }
```
Thanks in advance!

**Comment by IrynaZhumatiy** [comment]
@bcgit Could you please take a look? Thanks in advance!

**Comment by bcgit** [comment]
I don't think it's the code. It is probably the message - it looks like they have used the wrong OID for the digest identifier.

**Comment by IrynaZhumatiy** [comment]
@bcgit Thanks for the reply!
Could you please explain what do you mean under ' wrong OID for the digest identifier'?
So in code we don't have a problem, isn't it?
The problem is in PKCS7 buffer?
How I can fix this issue?
Thanks again!

**Comment by bcgit** [comment]
They would have stored the signature algorithm with the digest algorithm should have been stored - this has resulted in the PKCS#7 parsing attempting to create a digest called "SHA1WITHRSA", when it should just be creating "SHA1".
