### ISSUE TITLE
Possible bug with ProvSSLSessionImpl#getId

### ISSUE THREAD

**Issue by AlexITC** [bcgit/bc-java#298]
I was working replacing the TLS implementation from the Java library with BouncyCastle TLS.

While the program flow works as expected with the Java library, it is failing with BC due to this call `sslSession.getId()`, sadly I don't remember if it was returning `null` or an empty array.

I wonder if there is any known bug related to this, I could try to reproduce the bug again in case that it helps.

Thanks.

**Comment by peterdettman** [comment]
We've now changed getId to never return null (those cases now return empty byte array).
