### ISSUE TITLE
Possible ArrayIndexOutOfBoundException in FilterOutputStream from static analysis.

### ISSUE THREAD

**Issue by ashishrana160796** [bcgit/bc-java#299]
FilterOutputStream extends FileOutputStream, but here is the problematic snippet :
```
    public void write(byte[] b, int offset, int length) throws IOException
    {
        for (int i = 0; i < length; i++)
        {
            write(b[offset + i]);
        }
    }
```
This overriding implementation doesn't provide any checks  like the one in FileOutputStream class :
```
        if (b == null) {
            throw new NullPointerException();
        } else if ((off < 0) || (off > b.length) || (len < 0) ||
                   ((off + len) > b.length) || ((off + len) < 0)) {
            throw new IndexOutOfBoundsException();
        } else if (len == 0) {
            return;
``` 
`b[offset + i]` particular part can end up throwing  `ArrayIndexOutOfBoundException` as there are no checks here. 
If this looks like an important issue a `pr` regarding it can be made.

**Comment by bcgit** [comment]
I've added the necessary checks to the class. Took a while to do this as  I needed to make sure try it on the j2me build first.
