### ISSUE TITLE
IllegalArgumentException thrown when generate CscaMasterList from a ml file.

### ISSUE THREAD

**Issue by shoutao** [bcgit/bc-java#304]
Dear support, 
When the following code used to generate CscaMasterList from a ml file, IllegalArgumentException was thrown
FileInputStream in = new FileInputStream(mlFile);
byte[] byteArr = Streams.readAll(in);
ASN1Primitive asn1 =  ASN1ObjectIdentifier.fromByteArray(byteArr);
CscaMasterList parsedList = CscaMasterList.getInstance(asn1);

The ML file was download from 
https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/ElekAusweise/CSCA/GermanMasterList.html

Exception stack

java.lang.IllegalArgumentException: illegal object in getInstance: org.bouncycastle.asn1.ASN1ObjectIdentifier
	at org.bouncycastle.asn1.ASN1Integer.getInstance(Unknown Source)
	at org.bouncycastle.asn1.icao.CscaMasterList.<init>(Unknown Source)
	at org.bouncycastle.asn1.icao.CscaMasterList.getInstance(Unknown Source)

Please help check what is wrong.

If something wrong with the masterlist file, would you like share a CscaMasterListcan be used?

Thanks a lot.
Shoutao

**Comment by bcgit** [comment]
It's actually a PKCS#7 signed data file. Try:

        FileInputStream in = new FileInputStream(mlFile);
        byte[] byteArr = Streams.readAll(in);
        ContentInfo contInfo = ContentInfo.getInstance(byteArr);
        SignedData signedData = SignedData.getInstance(contInfo.getContent());
        CscaMasterList parsedList = CscaMasterList.getInstance(
            ASN1OctetString.getInstance(signedData.getContentInfo().getContent()).getOctets());

**Comment by shoutao** [comment]
It works like magic. You saved my world.

Thanks a lot.
Shoutao
