### ISSUE TITLE
UserNotice incorrect parsing

### ISSUE THREAD

**Issue by pinguidj** [bcgit/bc-java#305]
Hi, we are trying to add an issuer statement to a certificate.  When we use a null org.bouncycastle.asn1.x509.NoticeReference in org.bouncycastle.asn1.x509.UserNotice constructor UserNotice(NoticeReference,DisplayText) the CertificatePolicy extension is correctly parsed and displayed but when we try to use a not null NoticeReference with Organization and NoticeNumber the extension is not parsed correctly. Any ideas why?

**Comment by bcgit** [comment]
What error are you seeing?

**Comment by pinguidj** [comment]
Hi, I should be able to see something like this:

[image: Inline image 1]

but instead I'm getting

[image: Inline image 2]

Thanks.

**Comment by bcgit** [comment]
I'm sorry, but the screen dumps did not come through.

**Comment by pinguidj** [comment]
Hi, attached you will find two png's with the screenshots.

Thanks.

**Comment by bcgit** [comment]
Try emailing them to feedback-crypto@bouncycastle.org

**Comment by pinguidj** [comment]
Hi, I just did it.

Thanks.

**Comment by bcgit** [comment]
The screendumps didn't actually show anything related to Bouncy Castle. NoticeReference (as defined in the ASN.1 library) appears to correct though. It may be related to the tool being used for displaying the certificate.
