### ISSUE TITLE
KeyStore loading Problem when using the Bouncycastle Provider

### ISSUE THREAD

**Issue by Novaax** [bcgit/bc-java#306]
I have a problem loading a KeyStore with a keypair that has a different password than the KeyStore.

With the following code, I try to load the KeyStore:
`try (InputStream inputStream = new FileInputStream(new File("src\\integrationTest\\test.p12"))) {
        keyStore = KeyStore.getInstance("PKCS12","BC");
        keyStore.load(inputStream, "test".toCharArray());
    }`

The Following Exception is thrown on Runtime:
`java.io.IOException: exception unwrapping private key - java.security.InvalidKeyException: pad block corrupted`

**Comment by bcgit** [comment]
The PKCS12 implementation on BC does not support the use of different key passwords. You can use the org.bouncycastle.pkcs library for doing this.
