### ISSUE TITLE
point not on curve error for valid public GOST public key

### ISSUE THREAD

**Issue by spanov1980** [bcgit/bc-java#307]
Hello,

I got 'point not on curve’ error for valid GOST public key created by certified hardware token or taken from TC26 recommendation.

Code example for GOST public key created by certified hardware token

```
ECParameterSpec ecSpec = ECGOST3410NamedCurveTable.getParameterSpec("Tc26-Gost-3410-12-256-paramSetA");
ECPoint point = ecSpec.getCurve().createPoint(new BigInteger(X, 16), new BigInteger(Y, 16));
ECPublicKeySpec pubKeySpec = new ECPublicKeySpec(point, ecSpec);
KeyFactory keyFactory = KeyFactory.getInstance("ECGOST3410-2012", "BC");	
ECPublicKey pubKey = keyFactory.generatePublic(pubKeySpec);
```
X=8D98C6237BEACBBED3983597B0D8714BF17EA903F64EB7DB8AE25303493EE4C1
Y=3CD498E6877E87A62C74AF8D9FBE91B5C0B3E76C83979F153724D784D15F3990

or for GOST R 3410-2012 512 bits public key taken for TC26 recommendation:

```
ECParameterSpec ecSpec = ECGOST3410NamedCurveTable.getParameterSpec("Tc26-Gost-3410-12-512-paramSetA");
ECPoint point = ecSpec.getCurve().createPoint(new BigInteger(X, 16), new BigInteger(Y, 16));
ECPublicKeySpec pubKeySpec = new ECPublicKeySpec(point, ecSpec);
KeyFactory keyFactory = KeyFactory.getInstance("ECGOST3410-2012", "BC");	
ECPublicKey pubKey = keyFactory.generatePublic(pubKeySpec);
```
X=9B2EC2566F78D6B1F7DBD7C8BE89338D72D41E4A60110E164A013C52BFF58C9B83B8DB64FBA1E70364D526F6793C4E355F5887695928FA1FCC200F424655F395
Y=73506839155122450C153088CDA01ABCBEA04D9B3FCCB1B695F949630D02EFFE0DA2C2CB8488437B0503B331430ED16DFFB9111D44F13523F1385B790317B8EE

I tried to reverse X and Y bytes with no success.
BTW, if I use "GostR3410-2001-CryptoPro-A" parameter spec instead of "Tc26-Gost-3410-12-256-paramSetA", first key is accepted. "Tc26-Gost-3410-12-256-paramSetA should be back compatible with "GostR3410-2001-CryptoPro-A» regards key pair and has different only with hash function. Please check curve settings for "Tc26-Gost-3410-12-256-paramSetA» and "Tc26-Gost-3410-12-512-paramSetA» params.

Thank you!

**Comment by bcgit** [comment]
I'm not sure what to make of this one.

Can I get your thoughts on https://trac.tools.ietf.org/html/rfc7836 and also https://github.com/bcgit/bc-java/issues/245? Originally we were using GostR3410-2001-CryptoPro-A for Tc26-Gost-3410-12-256-paramSetA, however both the RFC and the standard appear to state that is not the case. I just rechecked RFC 7836 and https://tc26.ru/standard/rs/%D0%A0%2050.1.114-2016.pdf as well.

**Comment by spanov1980** [comment]
You're right, I've just consulted with expert from CryptoPro.
He said that RFC 4357 and RFC 7836 still valid as well as https://tc26.ru/standard/rs/Р%2050.1.114-2016.pdf

And OID 1.2.643.2.2.35.1 (GostR3410-2001-CryptoPro-A) can also be applied to ECGOST3410-2012, so a right code for public key with Algorithm GostR3410-2001 and new hash GOST R 34.11-2012 shoud be as following:

```
ECParameterSpec ecSpec = ECGOST3410NamedCurveTable.getParameterSpec("GostR3410-2001-CryptoPro-A");
ECPoint point = ecSpec.getCurve().createPoint(new BigInteger(X, 16), new BigInteger(Y, 16));
ECPublicKeySpec pubKeySpec = new ECPublicKeySpec(point, ecSpec);
KeyFactory keyFactory = KeyFactory.getInstance("ECGOST3410-2012", "BC");	
ECPublicKey pubKey = keyFactory.generatePublic(pubKeySpec);
```

Thank you!
