### ISSUE TITLE
Support all OpenBSD-BCrypt prefixes

### ISSUE THREAD

**Issue by bmarwell** [bcgit/bc-java#308]
Hello Team,

regarding: https://github.com/bcgit/bc-java/issues/207

You added support for the following prefixes:
* `$2a`
* `$2b`
* `$2y`

However, the following prefixes are also valid:
* `$2`
* `$2x`

Hashes are all the same. They just indicate that the hashes were generated with a buggy implementation.

Source: https://stackoverflow.com/a/36225192/1549977

**Comment by dghgit** [comment]
Thanks for the report. This is now fixed.
