### ISSUE TITLE
Only SHA-1 algo in CertificateID

### ISSUE THREAD

**Issue by MentalModel** [bcgit/bc-java#311]
Could you explain why in class org.bouncycastle.cert.ocsp.CertificateID only using sha-1 algo ? If someone need to use more stronger algo, e.g. sha-2, how could it being used ?

**Comment by bcgit** [comment]
CertificateID uses whatever hash algorithm is specified by the DigestCalculator passed to it. There is an algorithm identifier for SHA-1 defined in the class, but that's more as an old time courtesy.
