### ISSUE TITLE
A bug of SM2Engine.decrypt in version[1.59]:  if parameter "inOff" is not 0, it will be wrong

### ISSUE THREAD

**Issue by ZZMarquis** [bcgit/bc-java#318]
`  private byte[] decrypt(byte[] in, int inOff, int inLen)
      throws InvalidCipherTextException {
    
    // .............................
    
    int check = 0;
    for (int i = 0; i != c3.length; i++) {
      // Here，if inOff is not 0，it will be wrong
      // it should  be modified to:
      // check |= c3[i] ^ in[inOff + c1.length + c2.length + i];
      check |= c3[i] ^ in[c1.length + c2.length + i];
    }

    // .........................
    
  }`

**Comment by bcgit** [comment]
Thanks for the report. Fix added.
