### ISSUE TITLE
How to perform X25519 after deriving montgomery keypair?

### ISSUE THREAD

**Issue by vikram919** [bcgit/bc-java#320]
Below is the code, how I have derived montgomery keypair:

> ECParameterSpec ecsp = ECNamedCurveTable.getParameterSpec("curve25519");
		KeyPairGenerator kpg = KeyPairGenerator.getInstance("ECDH", "BC");
		kpg.initialize(ecsp, new SecureRandom());
		return kpg.genKeyPair();

How to perform ECDH using X25519 to derive shared secret?

**Comment by peterdettman** [comment]
X25519 is not yet available through the provider ("curve25519" is not the same thing), however you can use the org.bouncycastle.math.ec.rfc7748.X25519 class directly. Refer to the org.bouncycastle.math.ec.rfc7748.test.X25519Test class to see how to perform ECDH.
