### ISSUE TITLE
Can this JCE generate SM2 key by the keytool ?

### ISSUE THREAD

**Issue by TEE-OS** [bcgit/bc-java#321]
Hi, based on this JCE, can I invoke SM2 and SM3 algorithms in keytool and jarsigner tools?
For example, does the following command would run?

`keytool -keystore xxx -storetype PKCS12 -genkey -alias server -keyalg SM2 -sigalg SM3withSM2
`

**Comment by TEE-OS** [comment]
Hi, suxiaoyv. Thanks for your reply. I want to use java tools to sign an android APK using SM2, so I must use SM2 and SM3 in `keytool` and `jarsigner` tools. Do you mean that the JCE cannot invoke sm2 and sm3 of JCE by `keytool` and `jarsigner` tools? Thanks.

**Comment by TEE-OS** [comment]
@suxiaoyv Thanks a lot.

**Comment by bcgit** [comment]
And thank you!
