### ISSUE TITLE
Unexpected X500Name creation

### ISSUE THREAD

**Issue by MikeSafonov** [bcgit/bc-java#327]
Hello.
I ran into a problem with X500Name creation. 
````
X500Name x500Name= new X500Name ("CN=+Test");
System.out.println(x500Name.toString());
````
Output:
`IllegalArgumentException: badly formatted directory string`
````
X500NameBuilder builder = new X500NameBuilder(BCStyle.INSTANCE);
builder.addRDN(BCStyle.CN, "+Test");
X500Name x500Name = builder.build();
System.out.println(x500Name.toString());
````
Output:
`CN=\+Test`
But actualy i expect somthing like:
`CN=+Test`

**Comment by bcgit** [comment]
+ is normally used to indicate a component of a multivalued RDN - can you tell me a bit more about what you are trying to do, I've got a feeling an empty RDN (which is what the =+ implies) isn't actually legal (on the other hand this is X.500 we're talking about, I'd really have to check to be sure).

**Comment by Djaler** [comment]
I think we should have a way to get unescaped values. What about something like `Map<String,List<String>>map = x500Name.getKeyValues()`

**Comment by MikeSafonov** [comment]
Im trying to store phone number in [E.123 international notation](https://en.wikipedia.org/wiki/E.123)
Exmaple:
```
X500NameBuilder builder = new X500NameBuilder(BCStyle.INSTANCE);
builder.addRDN(BCStyle.CN, "+70710000000");
```

**Comment by dthompson085** [comment]
As bcgit hinted, in the text-string form of X.500 name defined for LDAP and used by nearly everyone else, plussign + is a special character and to be used as a data character must be escaped either as \+ or \2B. See sections 2.4 and 3 in RFCs 2253 and 4514, or 2.3 in the earlier RFCs 1485 and 1779. (Remember in Java to get a backslash in a string or character literal you must double it.)

**Comment by dthompson085** [comment]
As bcgit hinted, in the text-string form of X.500 name defined for LDAP and used by nearly everyone else, plussign + is a special character and to be used as a data character must be escaped either as backslash + or backslash 2 B (spelled out so I don't have to learn yet another set of markdown). See sections 2.4 and 3 in RFCs 2253 and 4514, or 2.3 in the earlier RFCs 1485 and 1779. (Remember in Java to get a backslash in a string or character literal you must double it.)

**Comment by bcgit** [comment]
I've been thinking about this - if you extract the RDN and then extract the value, you would be able to display the string without escape characters. What's causing the issue in this case is the escaping required to prevent the + being interpreted in the full distinguished name. If the actual value was pulled out it would just string type.

**Comment by MikeSafonov** [comment]
@dthompson085 @bcgit, thanks!
