### ISSUE TITLE
Extra data detected in stream

### ISSUE THREAD

**Issue by rsouthpaw** [bcgit/bc-java#328]
I am trying to implement late external signing. I am using (Javascript) digitalBazaar forgejs for creating SignedData using PKCS12. I just want to insert that SignedData in Bouncy Castle and finally inject that into pdf using pdfbox.

When trying this 

    ASN1Sequence.getInstance(signedDataByteArray)

I get Extra data detected in stream. How do I correct this? What Am i missing?

**Comment by bcgit** [comment]
it looks like there is garbage at the end of the stream - I'd suggest checking it first. If it's safe to do so you can create an ASN1InputStream on it and just do a readObject().

**Comment by p4535992** [comment]
> 
> 
> I am trying to implement late external signing. I am using (Javascript) digitalBazaar forgejs for creating SignedData using PKCS12. I just want to insert that SignedData in Bouncy Castle and finally inject that into pdf using pdfbox.
> 
> When trying this
> 
> ```
> ASN1Sequence.getInstance(signedDataByteArray)
> ```
> 
> I get Extra data detected in stream. How do I correct this? What Am i missing?

Have you find a solution?
