### ISSUE TITLE
Make JcePublicKeyDataDecryptorFactoryBuilder support Non-NIST Curves

### ISSUE THREAD

**Issue by Stefan-R2** [bcgit/bc-java#331]
Hi,

I just tried to decrypt PGP content with a brainpool curve (btw encryption works fine) and got an NullPointer in JcePublicKeyDataDecryptorFactoryBuilder.decryptSessionData. Problem is that decryptSessionData assumes that the presented curve is a NISTNamedCurves (line 140):

`X9ECParameters x9Params = NISTNamedCurves.getByOID(ecKey.getCurveOID());`

therefore in line 153 a NullPointer is thrown since x9Params is null

`ECPoint publicPoint = x9Params.getCurve().decodePoint(pEnc);`

I fixed this by changing the the decryptSessionData method to

`PublicKeyPacket pubKeyData = privKey.getPublicKeyPacket();`
`ECDHPublicBCPGKey ecKey = (ECDHPublicBCPGKey) pubKeyData.getKey();`
`ECCurve curve = null;`
`String name = ECNamedCurveTable.getName(ecKey.getCurveOID());`
`if (name != null) {`
`ECNamedCurveParameterSpec spec = ECNamedCurveTable.getParameterSpec(name);`
`if (spec != null) curve = spec.getCurve();`
`}`
`if (curve == null) {`
`	throw new PGPException("Unknown ECC Curve with OID " + ecKey.getCurveOID());`
`}`
`byte[] enc = secKeyData[0];`
`int pLen = ((((enc[0] & 0xff) << 8) + (enc[1] & 0xff)) + 7) / 8;`
`byte[] pEnc = new byte[pLen];`
`System.arraycopy(enc, 2, pEnc, 0, pLen);`
`byte[] keyEnc = new byte[enc[pLen + 2]];`
`System.arraycopy(enc, 2 + pLen + 1, keyEnc, 0, keyEnc.length);`
`ECPoint publicPoint = curve.decodePoint(pEnc);`

could you please consider such a fix for one of the next releases?

regards
stefan

**Comment by bcgit** [comment]
Resolved as part of #369
