### ISSUE TITLE
CertTemplate.getVersion() could trigger a NPE

### ISSUE THREAD

**Issue by Akretsch** [bcgit/bc-java#334]
If the OPTIONAL Version in org.bouncycastle.asn1.crmf.CertTemplate is not set, calling getVersion() triggers a java.lang.NullPointerException. This could happen, if a CertTemplate was created by CertTemplate.getInstance() and the  loaded ASN1Sequence did not contain "version [0] Version       OPTIONAL". 

Proposed fix:

public int getVersion()
    {
        return version!=null?version.getValue().intValue():-1;
    }

**Comment by bcgit** [comment]
Fixed. Thanks!
