### ISSUE TITLE
Creating attached signatures with blocks bigger than 1000 byte

### ISSUE THREAD

**Issue by lapo-luchini** [bcgit/bc-java#337]
[`CMSSignedDataGenerator`](https://github.com/bcgit/bc-java/blob/5fdb1face92f596300323c25cba9fe18726645e8/pkix/src/main/java/org/bouncycastle/cms/CMSSignedDataGenerator.java) uses [`BEROctetString`](https://github.com/bcgit/bc-java/blob/0aac111183c159277819755672569bd6c88dee5b/core/src/main/java/org/bouncycastle/asn1/BEROctetString.java) which uses a fixed `MAX_LENGTH = 1000`.
Given that an attached signature doesn't need to be restricted by DER (and CER, which is the one actually limited to 1000 bytes, isn't even used in any part of CMS signatures), but can be any BER value, it would be better to use bigger chunks or even (especially when input is a `CMSProcessableByteArray`) a primitive form octet string.
It would be nice to be capable to configure that.

**Comment by lapo-luchini** [comment]
AFAICT it would be sufficient to patch [line 170](https://github.com/bcgit/bc-java/blob/5fdb1face92f596300323c25cba9fe18726645e8/pkix/src/main/java/org/bouncycastle/cms/CMSSignedDataGenerator.java#L170) from:
`new BEROctetString(bOut.toByteArray())`
to
`new DEROctetString(bOut.toByteArray())`
to minimize space and complexity of the produced CMS.

**Comment by bcgit** [comment]
Is there a reason why you are not using CMSSignedDataStreamGenerator?

**Comment by lapo-luchini** [comment]
Right, `CMSSignedDataStreamGenerator` can be configured using `setBufferSize`, which is nice.
(It still doesn't produce DER, even when data fits in the buffer size, though.)

**Comment by nurlanarysbaev** [comment]
Hi.
Did you resolve this problem?

**Comment by nurlanarysbaev** [comment]
> Is there a reason why you are not using CMSSignedDataStreamGenerator?

Hi. 
Using CMSSignedDataStreamGenerator did'n help me.
do you have any ideas how we can chnage ber to der?

**Comment by dghgit** [comment]
There's now a CMSSignedDataGenerator.setDefiniteLengthEncoding() method, which should do what's required. Will appear in 171b12 on https://www.bouncycastle.org/betas in the next few days.
