### ISSUE TITLE
CMS : add support of SHA-3 based signatures

### ISSUE THREAD

**Issue by pvandenbroucke** [bcgit/bc-java#339]
Hello, 

It seems that class DefaultCMSSignatureAlgorithmNameGenerator doesn't support SHA-3 based signature algorithms like : 

- rsassa-pkcs1-v1_5-with-sha3-224 
- rsassa-pkcs1-v1_5-with-sha3-256 
- rsassa-pkcs1-v1_5-with-sha3-384 
- rsassa-pkcs1-v1_5-with-sha3-512 
- ecdsa-with-sha3-224 
- ecdsa-with-sha3-256 
- ecdsa-with-sha3-384 
- ecdsa-with-sha3-512 
- dsa-with-sha3-224 
- dsa-with-sha3-256 
- dsa-with-sha3-384 
- dsa-with-sha3-512 

The different algorithms are referred in the class DefaultSignatureAlgorithmIdentifierFinder.

Could you add this support ? 

Thanks in advance,

Pierrick

**Comment by bcgit** [comment]
I think this now be in the latest beta. See https://www.bouncycastle.org/betas

**Comment by pvandenbroucke** [comment]
Thanks for your fast reply. 

I'll test the beta tomorrow with these [files](https://ec.europa.eu/cefdigital/tracker/projects/DSS/issues/DSS-1419). They were generated with IAIK.

Regards,

Pierrick

**Comment by bcgit** [comment]
I've finally added the missing digestAlgs for PSS. The updated version is now available in https://www.bouncycastle.org/betas 160b08 or later.Think this is now all done.

**Comment by pvandenbroucke** [comment]
I tested the latest beta. All is done.

Many thanks.
