### ISSUE TITLE
Encrypt data with Asymmetric Public key ECGOST3410-2012

### ISSUE THREAD

**Issue by nurlanarysbaev** [bcgit/bc-java#341]
Method for encryptData:

        public static byte[] encryptData(byte[] data, X509Certificate encryptionCertificate)
			throws CertificateEncodingException, CMSException, IOException, NoSuchAlgorithmException,
			NoSuchProviderException {
		byte[] encryptedData = null;
		if (null != data && null != encryptionCertificate) {
			CMSEnvelopedDataGenerator cmsEnvelopedDataGenerator = new CMSEnvelopedDataGenerator();
			
			JceKeyTransRecipientInfoGenerator jceKey = new JceKeyTransRecipientInfoGenerator(encryptionCertificate).setProvider("BC");
			cmsEnvelopedDataGenerator.addRecipientInfoGenerator(jceKey);
			CMSTypedData msg = new CMSProcessableByteArray(data);
			OutputEncryptor encryptor = new JceCMSContentEncryptorBuilder(CMSAlgorithm.GOST28147_GCFB).setProvider("BC").build();
			CMSEnvelopedData cmsEnvelopedData = cmsEnvelopedDataGenerator.generate(msg, encryptor);
			encryptedData = cmsEnvelopedData.getEncoded();
		}
		return encryptedData;
	}

    Exception in thread "main" org.bouncycastle.cms.CMSException: exception wrapping content key: cannot create cipher: No such algorithm: 1.2.643.7.1.1.1.2
	at org.bouncycastle.cms.KeyTransRecipientInfoGenerator.generate(KeyTransRecipientInfoGenerator.java:42)
	at org.bouncycastle.cms.CMSEnvelopedDataGenerator.doGenerate(CMSEnvelopedDataGenerator.java:94)
	at org.bouncycastle.cms.CMSEnvelopedDataGenerator.generate(CMSEnvelopedDataGenerator.java:129)
	at com.joymoney.parameter.Boc.encryptData(Boc.java:188)
	at com.joymoney.parameter.Boc.main(Boc.java:109)
    Caused by: org.bouncycastle.operator.OperatorCreationException: cannot create cipher: No such algorithm: 1.2.643.7.1.1.1.2
	at org.bouncycastle.operator.jcajce.OperatorHelper.createAsymmetricWrapper(OperatorHelper.java:201)
	at org.bouncycastle.operator.jcajce.JceAsymmetricKeyWrapper.generateWrappedKey(JceAsymmetricKeyWrapper.java:127)
	at org.bouncycastle.cms.KeyTransRecipientInfoGenerator.generate(KeyTransRecipientInfoGenerator.java:38)
	... 4 more

Could anybody help me? How to do it?

MyTestCert 
[test.txt](https://github.com/bcgit/bc-java/files/1997420/test.txt)

**Comment by bcgit** [comment]
Ah, okay, had not got quite this far... as the release notes say we can only read the messages, not generate them. Looking at it now.

**Comment by nurlanarysbaev** [comment]
Thank you for reply. 
Will it be added in the next release?

**Comment by bcgit** [comment]
We're going to try. Watch this space, we'll probably need some help testing it!

**Comment by bcgit** [comment]
Okay, https://www.bouncycastle.org/betas b12 or later. Give it a try and let us know.

**Comment by nurlanarysbaev** [comment]
Hi. 
a little bit difference in OID

Our result: [https://yadi.sk/i/L72uSHqX3YTonZ](url)
Awaiting result: [https://yadi.sk/i/2MTuFYKA3YTouX](url)

**Comment by bcgit** [comment]
I've uploaded beta 13. That should use the param-Z sbox for Rosstandart curves.

**Comment by nurlanarysbaev** [comment]
Problem with dencryption method.

     public static byte[] decryptData(byte[] encryptedData, PrivateKey decryptionKey) throws CMSException {
		     byte[] decryptedData = null;
		     if (null != encryptedData && null != decryptionKey) {
			CMSEnvelopedData envelopedData = new CMSEnvelopedData(encryptedData);

			Collection<RecipientInformation> recipients = envelopedData.getRecipientInfos().getRecipients();
			KeyTransRecipientInformation recipientInfo = (KeyTransRecipientInformation) recipients.iterator().next();
			JceKeyTransRecipient recipient = new JceKeyTransEnvelopedRecipient(decryptionKey);

			return recipientInfo.getContent(recipient);
		}
		return decryptedData;
	}

Exception with 512 key length:

     Exception in thread "main" org.bouncycastle.cms.CMSException: exception unwrapping key: calculation failed: ECVKO public key has wrong domain parameters
	at 
     org.bouncycastle.cms.jcajce.JceKeyTransRecipient.extractSecretKey(JceKeyTransRecipient.java:190)
	at org.bouncycastle.cms.jcajce.JceKeyTransEnvelopedRecipient.getRecipientOperator(JceKeyTransEnvelopedRecipient.java:26)
	at org.bouncycastle.cms.KeyTransRecipientInformation.getRecipientOperator(KeyTransRecipientInformation.java:48)
	at org.bouncycastle.cms.RecipientInformation.getContentStream(RecipientInformation.java:169)
	at org.bouncycastle.cms.RecipientInformation.getContent(RecipientInformation.java:150)
	at com.joymoney.parameter.Equifax.decryptData(Equifax.java:165)
	at com.joymoney.parameter.Equifax.main(Equifax.java:66)
     Caused by: org.bouncycastle.jcajce.provider.asymmetric.ecgost12.KeyAgreementSpi$1: calculation failed: ECVKO public key has wrong domain parameters
	at org.bouncycastle.jcajce.provider.asymmetric.ecgost12.KeyAgreementSpi.engineDoPhase(KeyAgreementSpi.java:82)
	at javax.crypto.KeyAgreement.doPhase(KeyAgreement.java:567)
	at 
     org.bouncycastle.cms.jcajce.JceKeyTransRecipient.extractSecretKey(JceKeyTransRecipient.java:176)
	... 6 more
     Caused by: java.lang.IllegalStateException: ECVKO public key has wrong domain parameters
	at 
     org.bouncycastle.crypto.agreement.ECVKOAgreement.calculateAgreement(ECVKOAgreement.java:51)
	at org.bouncycastle.jcajce.provider.asymmetric.ecgost12.KeyAgreementSpi.engineDoPhase(KeyAgreementSpi.java:78)
	... 8 more


Exception with 256 key length:

     Exception in thread "main" org.bouncycastle.cms.CMSException: exception unwrapping key: mac mismatch
	ato rg.bouncycastle.cms.jcajce.JceKeyTransRecipient.extractSecretKey(JceKeyTransRecipient.java:190)
	at org.bouncycastle.cms.jcajce.JceKeyTransEnvelopedRecipient.getRecipientOperator(JceKeyTransEnvelopedRecipient.java:26)
	at org.bouncycastle.cms.KeyTransRecipientInformation.getRecipientOperator(KeyTransRecipientInformation.java:48)
	at org.bouncycastle.cms.RecipientInformation.getContentStream(RecipientInformation.java:169)
	at org.bouncycastle.cms.RecipientInformation.getContent(RecipientInformation.java:150)
	at com.joymoney.parameter.Equifax.decryptData(Equifax.java:165)
	at com.joymoney.parameter.Equifax.main(Equifax.java:66) 
     Caused by: java.lang.IllegalStateException: mac mismatch
	at org.bouncycastle.crypto.engines.GOST28147WrapEngine.unwrap(GOST28147WrapEngine.java:90)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseWrapCipher.engineUnwrap(BaseWrapCipher.java:444)
	at javax.crypto.Cipher.unwrap(Cipher.java:2550)
	at org.bouncycastle.cms.jcajce.JceKeyTransRecipient.extractSecretKey(JceKeyTransRecipient.java:186)
	... 6 more

**Comment by nurlanarysbaev** [comment]
[Our result](https://yadi.sk/i/-nsEdRJr3Yb55t)
[Awaiting](https://yadi.sk/i/rpxkgHZo3Yb58x)

Sometimes octed string is = 2®
Can we not divide encrypted data every 1000 bytes?

**Comment by bcgit** [comment]
The first exception would only show up if the public key's domain parameters don't match the private keys. I'm not sure with the 2nd one, but that also could be explained by the wrong private key being used. If this isn't the case, I may need you to send me a sample message.

**Comment by bcgit** [comment]
The stream generator allows setting a different size for the output chunking. Or are you trying to get rid of the chunking altogether? (CMS is supposed to support BER which does allow this).

**Comment by bcgit** [comment]
Sure. Send me a 256 key pair and a simple piece of code. I'll have a look. We have some test coverage on this, but I'm not 100% sure it's all working properly so this is probably the best way to find out one way or another.

**Comment by nurlanarysbaev** [comment]
[Code used](https://github.com/eugenp/tutorials/blob/master/libraries/src/main/java/com/baeldung/bouncycastle/BouncyCastleCrypto.java)
[certs.zip](https://github.com/bcgit/bc-java/files/2164583/certs.zip)

**Comment by nurlanarysbaev** [comment]
Do you speak in Russian? 
[GOST R 34.10-2001](https://github.com/bcgit/bc-java/files/2248585/2001.txt)
[GOST R 34.10-2012](https://github.com/bcgit/bc-java/files/2248586/2012.txt)
Encrypted with GOST 28147-89
Two files are encrypted with difference providers (links are their name)

**Comment by bcgit** [comment]
No, don't speak Russian, although I do enjoy the occasional Vodka...

I can finally start looking at this again. With the files above, what are the private keys and associated certificates? I can confirm they are well formed CMS envelopes, but that's about it. If you'd like me to properly analyze them I'll need a private key and a certificate. There doesn't appear to be anything obviously wrong with the code in the previous note either - with the code, the examples in the pkix package are probably the best to look at, particularly in NewEnvelopedDataTest

**Comment by nurlanarysbaev** [comment]
I've a little bit problems with private key. PK contained in the folder named like "61838f3c.000" and splitted to 6 files with encryption (may be its their security). 
I tried to contain cert and pk to pfx file with their program, but when read file occurred exception 
 
     java.io.IOException: exception unwrapping private key - java.security.NoSuchAlgorithmException: No such algorithm: 1.2.840.113549.1.12.1.80
	     at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.unwrapKey(Unknown Source)
	     at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	     at java.security.KeyStore.load(KeyStore.java:1445)
	     at ru.edu.test.file.PfxReader.main(PfxReader.java:25)

Can u analyze this pk?
I'm using cert and pk for signing and for encrypting using only cert without key.
Can we start with encrypting?

**Comment by nurlanarysbaev** [comment]
[pfx.txt](https://github.com/bcgit/bc-java/files/2252880/pfx.txt)
I'm using [asn1 online](https://lapo.it/asn1js/)

**Comment by nurlanarysbaev** [comment]
Sorry, i forgot about password. 
Password: GreenCard

**Comment by nurlanarysbaev** [comment]
this pfx used only for signing.
to encrypt we using partner cert 
[Test_2018-2019_G12.zip](https://github.com/bcgit/bc-java/files/2257072/Test_2018-2019_G12.zip)

**Comment by bcgit** [comment]
Okay, I can open the pfx without trouble, but I don't seem to be able to get a match on 1.2.840.113549.1.12.1.80 - I understand it eventually ends up as GOST28147 with CFB, but what happens before that to convert the password is currently eluding me...

**Comment by SergeyFedechkin** [comment]
Hi.
@nurlanarysbaev do you solve problem with exception "org.bouncycastle.cms.CMSException: exception unwrapping key: mac mismatch" for GOST-2012 256 bit? I`ve faced same issue. With GOST-2001 everything works perfectly.

**Comment by NLatyshev** [comment]
Hi guys
Any news?
I've noted generated by BC CMS Enveloped Data cannot be decrypted by CryptoPro and vice versa in case of GOST 2012 keys.
I found workaround in case of BC CMS Enveloped Data generation. Look at org.bouncycastle.operator.jcajce.JceAsymmetricKeyWrapper code fragment:
`
if (ephKeyInfo.getAlgorithm().getAlgorithm().on(RosstandartObjectIdentifiers.id_tc26))
{
    transParams = new GostR3410TransportParameters(
            RosstandartObjectIdentifiers.id_tc26_gost_28147_param_Z, ephKeyInfo, ukm);
}
`
if I comment the fragment BC uses 
`CryptoProObjectIdentifiers.id_Gost28147_89_CryptoPro_A_ParamSet`
and CryptoPro can decrypt content.
So it seems problem is in RosstandartObjectIdentifiers.id_tc26_gost_28147_param_Z

Of course it doesn't work if we can decrypt envelope generated by CryptoPro.

If we need keys and data samples I can provide them

**Comment by bcgit** [comment]
It sounds a lot like a different parameter set is in use - interesting, it might just be a matter of making it possible to configure it. If you can provide keypairs and some sample messages that would be a big help. If you use PKCS#12 for the key pair, please make sure the private key is not encrypted using the proprietary cryptopro PBE - we don't actually know what algorithm they use. Thanks.

**Comment by SergeyFedechkin** [comment]
@bcgit , please, check this one Password 01234567

[TestCert2012_new.zip](https://github.com/bcgit/bc-java/files/3183834/TestCert2012_new.zip)

**Comment by jakeostis** [comment]
Hello. I have a problem with encrypting like problems above - i encrypt data using gost28147 for gost-2012-256 cert alg, but proprietary software (CryptoPro) cannot decrypt it. I think this is because BC doesnt use tc 26 parameter Z for encrypting. I am right? If not - give me please code snippet or doc how to do that correct. CryptoPro doesnt support encryption without tc26 param with new Gost alg keys (2012)

**Comment by NLatyshev** [comment]
> It sounds a lot like a different parameter set is in use - interesting, it might just be a matter of making it possible to configure it. If you can provide keypairs and some sample messages that would be a big help. If you use PKCS#12 for the key pair, please make sure the private key is not encrypted using the proprietary cryptopro PBE - we don't actually know what algorithm they use. Thanks.

Hi, sorry for delay
source:
[hello.txt](https://github.com/bcgit/bc-java/files/3339540/hello.txt)
zip with cms enveloped by BC
[hello_enc_bc.zip](https://github.com/bcgit/bc-java/files/3339549/hello_enc_bc.zip)
zip with cms enveloped by BC (patched JceAsymmetricKeyWrapper, please see my comment above)
[hello_enc_bc_p.zip](https://github.com/bcgit/bc-java/files/3339555/hello_enc_bc_p.zip)
zip with cms enveloped by CryptoPro
[hello_enc_cp.zip](https://github.com/bcgit/bc-java/files/3339556/hello_enc_cp.zip)
zip with pfx (password is 1) for BC usage
[winrs2.zip](https://github.com/bcgit/bc-java/files/3339571/winrs2.zip)
zip with cert and CryptoPro keys
[winrs2.000.zip](https://github.com/bcgit/bc-java/files/3339577/winrs2.000.zip)

**Comment by lolyonok** [comment]
Seems like it was fixed in commits:
7201b8e2e50d560cd5266dcfc5aa6267a1f3637c and 8a0d1c1aaa36ac08274e7bf6adee8de7a4a4feb1

After building r1rv62 with these commits cherry-picked I can produce a valid cms that can be decrypted at least with Rutoken Plugin.
Originaly the problem was with computing MAC with wrong paramset (Paramset A was always used despite Paramset Z was set).

**Comment by NLatyshev** [comment]
I will try to check CryptoPro soon

**Comment by lolyonok** [comment]
Any news?

**Comment by NLatyshev** [comment]
I've checked it. BC can decrypt messages generated by CryptoPro and vice versa now (1.63). 
Thanks guys.

**Comment by lolyonok** [comment]
Have you checked the gost34.10-2012-512 keys? I had to [change the key derivation](https://github.com/bcgit/bc-java/pull/588) for them to work

**Comment by NLatyshev** [comment]
> Have you checked the gost34.10-2012-512 keys? I had to [change the key derivation](https://github.com/bcgit/bc-java/pull/588) for them to work

No. It was 256, I don't have such keys. But I believe I can generate them

**Comment by NLatyshev** [comment]
it was 256. I generated 512 and it doesn't work (1.63):
`
java.lang.IllegalStateException: mac mismatch
	at org.bouncycastle.crypto.engines.GOST28147WrapEngine.unwrap(Unknown Source) ~[bcprov-jdk15on-1.63.jar:1.63.0]
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseWrapCipher.engineUnwrap(Unknown Source) ~[bcprov-jdk15on-1.63.jar:1.63.0]
	at javax.crypto.Cipher.unwrap(Cipher.java:2550) ~[na:1.8.0_121]
	at org.bouncycastle.cms.jcajce.JceKeyTransRecipient.extractSecretKey(Unknown Source) ~[bcpkix-jdk15on-1.63.jar:1.63.00.0]
	at org.bouncycastle.cms.jcajce.JceKeyTransEnvelopedRecipient.getRecipientOperator(Unknown Source) ~[bcpkix-jdk15on-1.63.jar:1.63.00.0]
	at org.bouncycastle.cms.KeyTransRecipientInformation.getRecipientOperator(Unknown Source) ~[bcpkix-jdk15on-1.63.jar:1.63.00.0]
	at org.bouncycastle.cms.RecipientInformation.getContentStream(Unknown Source) ~[bcpkix-jdk15on-1.63.jar:1.63.00.0]
	at org.bouncycastle.cms.RecipientInformation.getContent(Unknown Source) ~[bcpkix-jdk15on-1.63.jar:1.63.00.0]
`
BC cannot decrypt generated cms by CryptoPro and vise versa

**Comment by nurlanarysbaev** [comment]
> it was 256. I generated 512 and it doesn't work (1.63):
> `java.lang.IllegalStateException: mac mismatch at org.bouncycastle.crypto.engines.GOST28147WrapEngine.unwrap(Unknown Source) ~[bcprov-jdk15on-1.63.jar:1.63.0] at org.bouncycastle.jcajce.provider.symmetric.util.BaseWrapCipher.engineUnwrap(Unknown Source) ~[bcprov-jdk15on-1.63.jar:1.63.0] at javax.crypto.Cipher.unwrap(Cipher.java:2550) ~[na:1.8.0_121] at org.bouncycastle.cms.jcajce.JceKeyTransRecipient.extractSecretKey(Unknown Source) ~[bcpkix-jdk15on-1.63.jar:1.63.00.0] at org.bouncycastle.cms.jcajce.JceKeyTransEnvelopedRecipient.getRecipientOperator(Unknown Source) ~[bcpkix-jdk15on-1.63.jar:1.63.00.0] at org.bouncycastle.cms.KeyTransRecipientInformation.getRecipientOperator(Unknown Source) ~[bcpkix-jdk15on-1.63.jar:1.63.00.0] at org.bouncycastle.cms.RecipientInformation.getContentStream(Unknown Source) ~[bcpkix-jdk15on-1.63.jar:1.63.00.0] at org.bouncycastle.cms.RecipientInformation.getContent(Unknown Source) ~[bcpkix-jdk15on-1.63.jar:1.63.00.0]`
> BC cannot decrypt generated cms by CryptoPro and vise versa

Hi, I had same exception
I've just resolved by iterating recipients and trying decode data. Perhaps, you add 2 or more recipients and decoding with 1 key. It's work for 1.64

     public byte[] decryptData(byte[] encryptedData, Schema schema) throws Exception {
        PairDTO<X509Certificate, PrivateKey> certAndKeyBySchema = getCertAndKeyBySchema(schema);
        PrivateKey privateKey = certAndKeyBySchema.getT2();
        byte[] decryptedData = null;
        if (null != encryptedData && null != privateKey) {
            CMSEnvelopedData envelopedData = new CMSEnvelopedData(encryptedData);
            Collection<RecipientInformation> recipients = envelopedData.getRecipientInfos().getRecipients();
            JceKeyTransRecipient recipientKey = new JceKeyTransEnvelopedRecipient(privateKey);
            Iterator<RecipientInformation> iterator = recipients.iterator();
            while (iterator.hasNext()) {
                RecipientInformation recipientInformation = iterator.next();
                decryptedData = getContent(recipientKey, recipientInformation);
                if (decryptedData != null)
                    break;
            }
        }
        return decryptedData;
    }

    private byte[] getContent(JceKeyTransRecipient recipientKey, RecipientInformation recipientInfo) {
        try {
            return recipientInfo.getContent(recipientKey);
        } catch (Exception e) {
            return null;
        }
    }

**Comment by NLatyshev** [comment]
I've tested all of them using 1.66. Didn't find any problem. Suppose it fixed and can be closed

**Comment by nurlanarysbaev** [comment]
Thank you
