### ISSUE TITLE
OpenPGP: How to create two RSA (sub)keys like GPG with different key usage?

### ISSUE THREAD

**Issue by user9209** [bcgit/bc-java#353]
Hello,

how can I create a PGP key with two (sub)keys like GPG.

> org.bouncycastle.openpgp.examples.RSAKeyPairGenerator.java

generates a pair with a single key using for signing, encryption and authentification.

![bc](https://user-images.githubusercontent.com/9293951/40274014-c2b08022-5bcc-11e8-925f-14d0736738aa.PNG)

GPG uses two keys: one for **signing and authentification** and an other for **encryption**.

![gpg](https://user-images.githubusercontent.com/9293951/40274015-c2db1c06-5bcc-11e8-8d8c-b19aa9bbc568.PNG)

How can I achieve this with bouncy castle.

Thanks in Advance

**Comment by vanitasvitae** [comment]
@user9209 You would have to set the respective KeyFlags in the hashed sub-packets during key pair creation / sub key adding.

**Comment by dghgit** [comment]
Assumed resolved.
