### ISSUE TITLE
How to sign certificate?

### ISSUE THREAD

**Issue by hpham04** [bcgit/bc-java#354]
I followed the guidance to sign the certificate but this certificate is unable to use
When I use this certificate, it shows the error message:
org.eclipse.paho.client.mqttv3.MqttException: MqttException
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664) ~[org.eclipse.paho.client.mqttv3-1.1.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: decrypt_error

The below is the code that I used to generate signed certificate
The certificate is the new one I want to sign
issuerCertificate is the CA certificate and issuerPrivate is the CA key
Could you please help to advise 
Thank you so much

private static X509Certificate createSignedCertificate(X509Certificate certificate, X509Certificate issuerCertificate, PrivateKey issuerPrivateKey) {
        try {
            Principal issuer = issuerCertificate.getSubjectDN();
            String issuerSigAlg = issuerCertificate.getSigAlgName();

            byte[] inCertBytes = certificate.getTBSCertificate();
            X509CertInfo info = new X509CertInfo(inCertBytes);
            info.set(X509CertInfo.ISSUER, issuer );
            info.set(X509CertInfo.VERSION, new CertificateVersion(CertificateVersion.V1) );
            info.set("serialNumber", new CertificateSerialNumber(new BigInteger(32, new Random())));
            X509CertImpl outCert = new X509CertImpl(info);
            outCert.sign(issuerPrivateKey, issuerSigAlg);
            return outCert;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }

**Comment by dghgit** [comment]
closing as this isn't actually BC...
