### ISSUE TITLE
Timeline for TLS v1.3

### ISSUE THREAD

**Issue by ava7ar** [bcgit/bc-java#355]
Hi,

In regards to the upcoming finalization of TLS v1.3 draft, do you have any timeline (even a high level) about the implementation?

**Comment by bcgit** [comment]
We've already managed to get some support on this one from our existing support contract holders so have started work on it now. Not sure how long it will take.

**Comment by ava7ar** [comment]
I do have a support contract as well (Axway Software). As our customers are gonna push, do you plan to get a mailing list or something to keep us up to date?

**Comment by bcgit** [comment]
You'll see it appearing in the FIPS git repositories as well as here. We'll also be sending out an announcement to the FIPS mailing list.

**Comment by ava7ar** [comment]
Fair enough. Closing this one.
