### ISSUE TITLE
Does SCrypt implement RFC 7914?

### ISSUE THREAD

**Issue by matthew-a-thomas** [bcgit/bc-java#358]
https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/generators/SCrypt.java

Does this ^ implement [RFC 7914](https://tools.ietf.org/html/rfc7914)?

The javadocs say:
> Scrypt was created by Colin Percival and is specified in `draft-josefsson-scrypt-kd`

But [draft-josefsson-scrypt-kd](https://tools.ietf.org/html/draft-josefsson-scrypt-kdf-01) expired in 2013.

On the other hand, I see that changes have been made to this class over time since 2013.

Are the javadocs simply out of date?

**Comment by bcgit** [comment]
Yes, it's now based on RFC 7914. I've updated the JavaDoc.
