### ISSUE TITLE
wrong authorityCertIssuer used in org.bouncycastle.cert.X509ExtensionUtils.createAuthorityKeyIdentifier(X509CertificateHolder certHolder)

### ISSUE THREAD

**Issue by Akretsch** [bcgit/bc-java#360]
According to the javadoc comment of  "public AuthorityKeyIdentifier createAuthorityKeyIdentifier(
        X509CertificateHolder certHolder)" the returned AuthorityKeyIdentifier should refer to the certificate given in  certHolder. But the AuthorityKeyIdentifier is generated out of the ISSUER of the ISSUER certificate given as parameter.
Proposed solution:
Replace 
"GeneralName   genName = new GeneralName(certHolder.getIssuer());" with
"GeneralName   genName = new GeneralName(certHolder.getSubject());"

**Comment by bcgit** [comment]
No the code is correct - a certificate's serial number is related to the issuer of the certificate in question, not the subject.
