### ISSUE TITLE
PBE algorithms

### ISSUE THREAD

**Issue by ava7ar** [bcgit/bc-java#361]
As part of our migration from Certicom to BC, we have stumbled upon the following issue:
Previously encrypted data using Certicom's PBEWithHmacSHA1AndAES-128 cannot be decrypted, or at least we couldn't manage to find the proper cipher.
Can you please advise?

Support contract holder: Axway Software

**Comment by bcgit** [comment]
You'll need to contact us at the support address. We'll need to try a few vectors to work out what they've done.

**Comment by ava7ar** [comment]
Done. Escalated via mail.
