### ISSUE TITLE
Only NIST based EC curves are usable for decryption/verification

### ISSUE THREAD

**Issue by nros** [bcgit/bc-java#364]
https://github.com/bcgit/bc-java/blob/5fdb1face92f596300323c25cba9fe18726645e8/pg/src/main/java/org/bouncycastle/openpgp/operator/jcajce/JcaPGPKeyConverter.java#L199

It seems as if converting JCA keys fails with other than NIST curves eg: "brainpoolP512r1" (see [TeleTrusTNamedCurves](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/asn1/teletrust/TeleTrusTNamedCurves.java#L264))

The following code triggers a `NullPointerException` at [JcaPGPKeyConverter.java line 202](https://github.com/bcgit/bc-java/blob/5fdb1face92f596300323c25cba9fe18726645e8/pg/src/main/java/org/bouncycastle/openpgp/operator/jcajce/JcaPGPKeyConverter.java#L202). `params` is `null` because the curve was not found.

```Java
    public static void main(final String[] args) {

        Security.setProperty("crypto.policy", "unlimited");
        Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());

        PGPKeyPair pgpKeys;

        KeyPairGenerator keyPairGenerator = null;
        try {
            keyPairGenerator = KeyPairGenerator.getInstance("ECDH", "BC");
            keyPairGenerator.initialize(ECNamedCurveTable.getParameterSpec("brainpoolP512r1"), new SecureRandom());

            final KeyPair keys = keyPairGenerator.generateKeyPair();

            // convert to PGP key pair
            pgpKeys = new JcaPGPKeyPair(
                PublicKeyAlgorithmTags.ECDH,
                new PGPKdfParameters(HashAlgorithmTags.SHA512, SymmetricKeyAlgorithmTags.AES_256),
                keys,
                new Date()
            );


        } catch (final Exception e) {
            e.printStackTrace();
        }
    }
```

The example code is based on this article:
https://bouncycastle.org/wiki/display/JA1/Elliptic+Curve+Key+Pair+Generation+and+Key+Factories#EllipticCurveKeyPairGenerationandKeyFactories-UsingaKeyFactory.1

When using NIST curve *P-521*, the core works properly.

Exception thrown is:
```
Exception in thread "main" java.lang.NullPointerException
	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.getPGPPublicKey(JcaPGPKeyConverter.java:202)
	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyPair.getPublicKey(JcaPGPKeyPair.java:29)
	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyPair.<init>(JcaPGPKeyPair.java:65)
	at Test.main(Test.java:40)
```

**Comment by nros** [comment]
Sorry, is the same as #331 - I missed that before

**Comment by nros** [comment]
https://github.com/bcgit/bc-java/blob/5fdb1face92f596300323c25cba9fe18726645e8/pg/src/main/java/org/bouncycastle/openpgp/operator/bc/BcPublicKeyDataDecryptorFactory.java#L102

seems to be a problem at a lot of places. decrypting data with other curves than NIST curves is impossible right now.  I tried to use brainpoolP512r with code from https://subversivebytes.wordpress.com/2012/12/07/pgp-cryptography-with-the-legion-of-the-bouncy-castle-part-2/

IMHO this is a blocker! Curves that are named to be supported can not be used to decrypt/verify.

**Comment by bcgit** [comment]
Thanks for the report, now merged.
