### ISSUE TITLE
RSADigestSigner and GenericSigner should negate forSigning when used as forEncryption arg in engine init

### ISSUE THREAD

**Issue by NumberFour8** [bcgit/bc-java#367]
I was recently stepping through the source code of RSADigestSigner and GenericSigner.
AFAIK, when doing RSA signing it is actually decrypting using the private key, while RSA verification means encryption using the public key.

I was surprised to see that the `forSigning` argument in the RSADigestSigner init method is not negated when put as the `forEncryption` argument in the init method of the underlying RSAEngine. See RSADigestSigner on line 122.

This results in the RSA engine being initialized rather for encryption, although signing means decryption. However, it does probably somehow compensate somewhere, so the engine actually performs decryption during signing. Anyway, this is at least counter-intuitive.

However, there's a problem with ElGamalEngine used with GenericSigner, because ElGamalEngine actually performs an extra check in its init method, and if it is being init'd `forEncryption` while giving the engine a private key, it throws an exception. Therefore, here it causes a problem that the `forSigning` flag is not negated while put as the `forEncryption` argument of the ElGamalEngine init method within GenericSigner.

Is this a bug or am I missing something?

**Comment by bcgit** [comment]
Its not a bug, although I can see how someone might think a private key is always "decryption"... We don't actually support ElGamal signatures either. ElGamal encryption does have a bit in common with RSA in the sense you can process a single block with it, the similarities end there though.
