### ISSUE TITLE
Support GnuPG's keybox file format

### ISSUE THREAD

**Issue by nlmarco** [bcgit/bc-java#372]
Since version 2.1, GnuPG uses the new "keybox" file format. Unfortunately, BouncyCastle cannot read or write it, yet.

See: https://stackoverflow.com/questions/34212230/using-bouncycastle-with-gnupg-2-1s-pubring-kbx-file

I already kindly asked on the mailing list last year (2017-03-29) and I was told that supporting this new file format is already on the list. But since nothing happened so far (at least not that I'm aware of), I'd like to open this issue as a feature-request:

Please, add support for the new "keybox" file format used by GnuPG 2.1 in order to re-establish compatibility with GnuPG.

**Comment by nlmarco** [comment]
I'd like to add that GnuPG 2.1 never uses the old "legacy" file formats for private keys.

What is written about GnuPG's compatibility behaviour in the above stackoverflow-article applies only to the public keys. Private keys are always immediately converted to the new format -- once (!) and afterwards, GnuPG does not care about the legacy private key-ring, anymore.

**Comment by bcgit** [comment]
This is already in the current beta - it should be in the bcpg jar in the beta version https://www.bouncycastle.org/betas. Package is org.bouncycastle.gpg.keybox
