### ISSUE TITLE
Constructor of PGPPublicKeyRing does wrap PGPException in IOException

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#374]
Hi!
This is probably not a bug, but I wonder, why the PGPPublicKeyRing constructor catches PGPExceptions and rethrows them wrapped in an IOException, while other classes like for example the PGPPublicKeyRingCollection, the PGPSecretKeyRing and the PGPSecretKeyRingCollection throw the PGPException directly.

Is this done on purpose?

**Comment by bcgit** [comment]
Purely historical to preserve the original signature. The arrival of PGPException in this case was the result of refactoring after the class was originally added. I guess this one is on the "nit list".
