### ISSUE TITLE
BCrypt hash is not compatible to python3 bcrypt

### ISSUE THREAD

**Issue by agherasim** [bcgit/bc-java#376]
The strict check for salt length differs from python bcrypt library, which in turn causes different hashes between languages.
https://github.com/bcgit/bc-java/blob/7f4e6eb191e56889dffe6ce1da04972ce7d99df1/core/src/main/java/org/bouncycastle/crypto/generators/OpenBSDBCrypt.java#L146

Python implementation: 	
```
if (strlen(salt) * 3 / 4 < BCRYPT_MAXSALT)`, where `BCRYPT_MAXSALT 16
``` 
(see https://github.com/pyca/bcrypt/blob/master/src/_csrc/bcrypt.c#L124).

The problem with implementing the python version would mean 16 byte long salt can no longer be used, a minimum of 22 bytes long should be used.

**Comment by agherasim** [comment]
Problem seems to be caused by python decoding the salt as base64 after checking length. See https://github.com/jeremyh/jBCrypt/blob/master/src/main/java/org/mindrot/BCrypt.java for how to do base64_decoding.

**Comment by bcgit** [comment]
This is not a bug, but I'd say the analysis of the differences is correct. The BC implementation just assumes a byte array, but if you Base64.decode() the salt you are passing with python before you invoke our class, you should get the answer you are looking for.

**Comment by agherasim** [comment]
@bcgit, thanks, I did that and the results are now the same.
