### ISSUE TITLE
Invalid XMSS privateKey derived from PKCS8

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#380]
Hi,
There seems to be a problem with XMSS privateKeys that are derived from the PKCS8 representation.

When the derived key is used to sign a message, a NullPointerException is generated. This appears to be caused by the incorrect initialisation of BDS which when de-serialised from the PKCS8 representation leaves the transient field wotsPlus null.

This needs to be initialised via a call to setXMSS(), and this is done by the Builder in the case where the key is derived from a privateKey, but not when derived from the PKCS8Encoded bytes. 

A similar situation appears by inspection to be present in XMSSMT, but it has not shown as an error in my testing, probably because I am creating the PKCS8Encoding prior to signing messages.

**Comment by bcgit** [comment]
Thanks for the report. I've been able to confirm this, it appears to depend on the state of tree whether it shows up or not, which is why it's only appearing every now and then. I've updated https://www.bouncycastle.org/betas with 161b01 which should fix this issue in a backwards compatible way. Let me know how you go.

**Comment by tonywasher** [comment]
I've tested with the beta version and the fix looks good.
Thanks

**Comment by bcgit** [comment]
Thanks. One last question, we're doing a bit of a survey on XMSS and algorithms like it. If you wouldn't mind answering it, it would help.

Here are the questions:

1. Do you currently use the BC version of XMSS/XMSS^MT? Yes/No

2. If the answer to 1 is no: do you expect to use XMSS/XMSS^MT in an
application in the next 12 months? Yes/No

3. If the answer to 1 or 2 is yes : what kind of application is
XMSS/XMSS^MT used for? (a) financial sector (b) law/legal (c) government
(d) education/teaching (e) other

4. Would you like to see Bouncy Castle add an implementation of LMS as
well? Yes/No

Please respond to feedback-crypto@bouncycastle.org.
