### ISSUE TITLE
Exporting public keys from PGPSecretKeyRing does denote sub keys as normal keys

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#381]
Hi!
My issue is the following: If I create a PGPSecretKeyRing containing a master key and a sub key, and then try to extract a PGPPublicKeyRing from it, the resulting key ring does only contain one key, as the sub keys are ignored. The cause for this is, that the sub keys are not carrying a PUBLIC_SUBKEY packet tag, but instead a PUBLIC_KEY tag. When creating the PGPPublicKeyRing, the sub keys are therefore ignored due to [this line](https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/PGPPublicKeyRing.java#L114).

Inspecting the encoded PGPPublicKeyRing with `gpg --list-packets` also suggests, that only two normal public keys are exported.

I created this [minimal example](https://gist.github.com/vanitasvitae/e125fe669a0e57ccf2420f3e7d59d24f) for you to recreate the issue.

**Comment by vanitasvitae** [comment]
It seems to work now :)
Can you point me to which commit exactly fixed this issue, so I can try to create a workaround for my project until BC 1.61 is released?

**Comment by bcgit** [comment]
Yes, it's the change to PGPKeyRingGenerator

**Comment by vanitasvitae** [comment]
For the record, I created [this workaround](https://gist.github.com/vanitasvitae/9d25270bade20e9d3d16f092a3df407d) for fixing this issue in retrospect on existing keys.
A quick test suggests, that it is working as intended, but I give no guarantees :D
