### ISSUE TITLE
how to set ed25519 and ed448 to be prehash mode?

### ISSUE THREAD

**Issue by dawud-tan** [bcgit/bc-java#382]
@peterdettman how do I turn ed25519 and ed448 into ed25519ph and ed448ph? is it enough by modifying  phflag to be 0x01;  and hash the input first?

**Comment by peterdettman** [comment]
Yes, that should be all that's needed. There are separate test vectors for those in RFC 8032 also, which I would urge you to check your code against if you make modifications.

I hope to add support for Ed25519ctx, Ed25519ph and Ed448ph before the next release.

**Comment by peterdettman** [comment]
In the current release we have only included the (very) low-level implementation of EdDSA. It is ongoing work to make them available in the JCE provider.

**Comment by dawud-tan** [comment]
I'm really love your support 😀

**Comment by peterdettman** [comment]
It's not about being a good thing; the draft is pointing out that CMS (in most cases) is already hashing the message. The resulting hash is included in the signed attributes, which as the name suggests, is what actually gets signed. An extra prehash step as part of the signature algorithm would be redundant in that case.

**Comment by dawud-tan** [comment]
I'm sorry I mean why Mr Bernstein developed two version, from what I read in RFC 8032

>Choosing which variant to use depends on which property is deemed to be more important between 1) collision resilience and 2) a single-pass interface for creating signatures.

Then how do I decide which is important for my app that try to achieve non-repudiation?

**Comment by dawud-tan** [comment]
Does it have something related with the following class org.bouncycastle.crypto.io.SignerInputStream vs org.bouncycastle.crypto.Signer ? Streaming vs blocking?

**Comment by winfriedgerlach** [comment]
@dawud-tan @peterdettman this question seems to be answered, can the issue be closed?
