### ISSUE TITLE
BCStyle have two attributes for email address. Why?

### ISSUE THREAD

**Issue by nekkiy** [bcgit/bc-java#387]
[org.bouncycastle.asn1.x500.style.BCStyle](https://github.com/bcgit/bc-java/blob/r1v60/core/src/main/java/org/bouncycastle/asn1/x500/style/BCStyle.java#L207) have two attributes for email address: [E](https://github.com/bcgit/bc-java/blob/r1v60/core/src/main/java/org/bouncycastle/asn1/x500/style/BCStyle.java#L174) and [EMAILADDRESS](https://github.com/bcgit/bc-java/blob/r1v60/core/src/main/java/org/bouncycastle/asn1/x500/style/BCStyle.java#L163). But [OID 1.2.840.113549.1.9.1](http://oid-info.com/get/1.2.840.113549.1.9.1) have not shortname `E`. However [translate OID to shortname have result `E`](https://github.com/bcgit/bc-java/blob/r1v60/core/src/main/java/org/bouncycastle/asn1/x500/style/BCStyle.java#L207). Please explain the reasons for this behavior (perhaps historical bug or deprecated).  We have the [issue ](https://github.com/luisgoncalves/xades4j/issues/157) and we need explanations

**Comment by bcgit** [comment]
E is recognised as the primary as it was the first representation of the OID we encountered. EMAILADDRESS is also parsed as it is an alternative. You can define your own style by extending off BCStyle if you need to support alternate text encodings.

**Comment by nekkiy** [comment]
Tell me please, has a official documentation reference (RFC or another) describing it?

Thanks for your attention.

**Comment by nekkiy** [comment]
Thanks)
