### ISSUE TITLE
SHA-256 digest error for org/bouncycastle/LICENSE.class

### ISSUE THREAD

**Issue by qingfengqianxiao** [bcgit/bc-java#390]
Information:Gradle tasks [:app:assembleDebug]
Error:Execution failed for task ':app:transformClassesWithAndroidGradleClassShrinkerForDebug'.
> SHA-256 digest error for org/bouncycastle/LICENSE.class
 this is my issue .
This is an android project.

**Comment by bcgit** [comment]
Android ships with a version of Bouncy Castle, this is probably the reason - you should look at using Spongy Castle instead.
