### ISSUE TITLE
trying to sign public key with sample class DirectKeySignature but it not works

### ISSUE THREAD

**Issue by alapierre** [bcgit/bc-java#392]
I tryed to use DirectKeySignature to sign some public key. After run it and import signed key to GPG I tryed check:

`gpg --check-sigs "Adrian (test) <al@p-c.pl>"`

and I got:

`pub   4096R/9D5D4AB8 2018-06-20
sig-     N   E9798A8A 2018-08-04  Test (test) <test@sample.com>
uid                  Adrian (test) <al@p-c.pl>
sig!         9D5D4AB8 2018-06-20  Adrian (test) <al@p-c.pl>

1 incorrect signature`

when run with one parameter, everything looks good:

`Signature date is: Sat Aug 04 12:40:53 CEST 2018
Found Notaion named 'Test (test) <test@sample.com>' with content 'zweryfikowano'.`

Result for key signed in GPG command line:

pub   4096R/220D644A 2018-06-08
uid                  Tt Ctttt <aa.bbi@xxx.pl>
sig!3        220D644A 2018-06-08  Tt Ctttt <aa.bbi@xxx.pl>
sig!         49ED3ECD 2018-06-21  Adrian  <adrian.lapierre@sample.com>
sub   4096R/4CF3B368 2018-06-08
sig!         220D644A 2018-06-08  Tt Ctttt <aa.bbi@xxx.com>

Mayby  I'm doing somethong wrong?

**Comment by alapierre** [comment]
when I added this: 
`Iterator<byte[]> ids = keyToBeSigned.getRawUserIDs();`
`return PGPPublicKey.addCertification(keyToBeSigned, ids.next(), sGen.generate()).getEncoded();`

at the end of method signPublicKey it is makes things better, but pgp still tells that my signature is bad

> gpg2 --verbose --check-sigs "Adrian (test) <xxx@xxx.pl>"
> gpg: 1 good signature
> gpg: 1 bad signature
> pub   rsa4096/9D5D4AB8 2018-06-20 [SCEA]
> uid         [    nieznane   ] Adrian (test) <xxx@xxx.pl>
> sig!         9D5D4AB8 2018-06-20  Adrian (test) <xxx@xxx.pl>
> sig-         1A21C3C6 2018-08-30  YYYY <yyy@yyy.pl>

gpg version (GnuPG) 2.1.11

**Comment by alapierre** [comment]
I've made pull request with fix: https://github.com/bcgit/bc-java/pull/401

**Comment by dghgit** [comment]
See page 20 of RFC 4880 - signature type 0x1F - the sig is calculated directly on the key. I think the issue is that the signature type you need is actually one of the certification types, not a direct key type.
