### ISSUE TITLE
BCrypt.generate(...) same result for different byte[]

### ISSUE THREAD

**Issue by gekoreed** [bcgit/bc-java#393]
I have tested hash calculation of two different passwords and got the same results.
JVM: 1.8.0_171
BC version: 1.54

I wrote a little test to reproduce this bug:

```
public class HashUtilTest {
    @Test
    public void test() {
        String passA = "abcd";
        String passB = "abcdabcd";
        byte[] salt = generateRandomBytes();
        byte[] hashA = hashPassword(passA.getBytes(Charset.forName("UTF-8")), salt);
        byte[] hashB = hashPassword(passB.getBytes(Charset.forName("UTF-8")), salt);
        Assert.assertFalse(Arrays.equals(hashA, hashB));
    }

    private static byte[] hashPassword(byte[] passwordBytes, byte[] salt) {
        return BCrypt.generate(passwordBytes, salt, 4);
    }

    private static byte[] generateRandomBytes() {
        byte[] result = new byte[16];
        ThreadLocalRandom.current().nextBytes(result);

        return result;
    }
}
```

This test fails.

**Comment by bcgit** [comment]
You need to add a trailing zero to the byte array representing the password - the BCrypt algorithm will otherwise produce the same "hash". More recent versions of BCrypt also include a static method 

public static byte[] passwordToByteArray(char[] password)

Which will do this.

**Comment by mouse07410** [comment]
Actually the right fix for problems like this would be including the string length in the hash. I guess it slipped from the BCrypt standard designers.

Adding a zero byte is second best. ;-)

**Comment by bcgit** [comment]
You know, it isn't actually part of the standard, but yes, it's a really good idea. I think I'll add utility method for this as well.
