### ISSUE TITLE
The inner object of the tagged object should be used for instantiating the EncryptedValue

### ISSUE THREAD

**Issue by mtgag** [bcgit/bc-java#394]
.getObject() is missing.

https://github.com/bcgit/bc-java/blob/e04ee7fd0aba1427f300b2675adc9b016d854c05/core/src/main/java/org/bouncycastle/asn1/cmp/CertifiedKeyPair.java#L40

**Comment by bcgit** [comment]
Thanks for the report, now fixed as part of #397
