### ISSUE TITLE
The inner object of the tagged object should be used for instantiating the PKIPublicationInfo

### ISSUE THREAD

**Issue by mtgag** [bcgit/bc-java#395]
.getObject() is missing. The inner object should be used and not the tagged one.

https://github.com/bcgit/bc-java/blob/e04ee7fd0aba1427f300b2675adc9b016d854c05/core/src/main/java/org/bouncycastle/asn1/cmp/CertifiedKeyPair.java#L41

**Comment by bcgit** [comment]
Thanks for the report. Now fixed as part of #397
