### ISSUE TITLE
pubInfos are allowed to be null

### ISSUE THREAD

**Issue by mtgag** [bcgit/bc-java#396]
if (pubInfos != null) {
  v.add(pubInfos); 
}

See https://tools.ietf.org/html/rfc4211#section-6.3

https://github.com/bcgit/bc-java/blob/e04ee7fd0aba1427f300b2675adc9b016d854c05/core/src/main/java/org/bouncycastle/asn1/crmf/PKIPublicationInfo.java#L77

**Comment by bcgit** [comment]
Thanks for the report, fixed as part of 397.
