### ISSUE TITLE
pubInfos are allowed to be null

### ISSUE THREAD

**Issue by mtgag** [bcgit/bc-java#397]
if (size ==2) {
  pubInfos = ASN1Sequence.getInstance(seq.getObjectAt(1)); 
} 

See https://tools.ietf.org/html/rfc4211#section-6.3

https://github.com/bcgit/bc-java/blob/e04ee7fd0aba1427f300b2675adc9b016d854c05/core/src/main/java/org/bouncycastle/asn1/crmf/PKIPublicationInfo.java#L19

**Comment by bcgit** [comment]
This should now be fixed. Actual classes will appear in 161b04 in the next couple of days.
