### ISSUE TITLE
Documentation for JCE package -- OAEPParameterSpecs.DEFAULT cannot be resolved

### ISSUE THREAD

**Issue by sarah-mdv** [bcgit/bc-java#408]
Hello,

When trying to set up an Eclipse IDE using the default folders pulled from git, we made the mistake of adding the jce/src/main/java package to the build path. However, as implicitly specified in the README.md this package must be added as a source folder uniquely if being used with Java 1.3 or earlier and otherwise produces an "OAEPParameterSpecs.DEFAULT cannot be resolved" error on compilation along with a "updateAAD(byte[]) undefined" error. 

Would it be possible to provide an {Eclipse} IDE setup guide?
Thank you,

P.S. Otherwise, is there perhaps a IDE setup cookbook which I may have overlooked?

**Comment by bcgit** [comment]
I've added some additional commentary to the README.md on the clean room JCE.

With IDE support documentation, I am afraid I cannot see that getting done anytime soon. I would say that gradle does, or at least used to, support IDE configuration, although you may need to modify the provided build.gradle to import the appropriate plugin. You might also find importing the gradle build, or a slightly modified version of it, is the easiest approach to take.
