### ISSUE TITLE
asn1 Package missing

### ISSUE THREAD

**Issue by Erlix322** [bcgit/bc-java#409]
Hi,

I recently used this dependency in a java project:
<dependency>
		    <groupId>org.bouncycastle</groupId>
		    <artifactId>bcmail-jdk15on</artifactId>
		    <version>1.60</version>
		</dependency>

  
But everytime I'd like to use PublicKeyDataObject it tells me that it can't be resolved. Which dependency is the right one? Documentation is not very clear on that.

**Comment by bcgit** [comment]
PublicKeyDataObject is in org.bouncycastle.asn1.eac in the bcprov jars. Please note only one of the bcprov jars can be included.
