### ISSUE TITLE
v1.60 Looses first few characters on Java 8 vs v1.59

### ISSUE THREAD

**Issue by omkar9999** [bcgit/bc-java#410]
I was upgrading from v1.57 to v1.60 and observed that v1.60 was losing first few characters while encrypting the file and when I tested the same files with v1.59 it could encrypt and decypt the files just fine.

Surprisingly missing data is found in ld.getFileName() where ld is
 PGPLiteralData ld = (PGPLiteralData)message;

Please look into this.

**Comment by bcgit** [comment]
I'd need an example. It seems a bit odd though - the relevant classes don't appear to have changed over the releases mentioned.

**Comment by bcgit** [comment]
I think I've finally found this issue. It's actually connected with a utility method in PGPUtil. Should appear on github shortly and in the next beta 161b13.
