### ISSUE TITLE
SM3算法OID错误

### ISSUE THREAD

**Issue by wangxuanmin** [bcgit/bc-java#412]
SM3摘要算法类`org.bouncycastle.jcajce.provider.digest.SM3`

其中44行的算法OID应为“1.2.156.10197.1.401”

“1.2.156.197.1.401”是草案阶段使用的OID，正式公布后已改为“1.2.156.10197.1.401”。

**Comment by bcgit** [comment]
Thanks for the report. This is now fixed and available at: https://downloads.bouncycastle.org/betas/
