### ISSUE TITLE
Diffie-Hellman key finalization zero-padding incompatibility

### ISSUE THREAD

**Issue by alrossi** [bcgit/bc-java#413]
We are developers working on the dCache storage system (https://www.dcache.org), which supports multiple I/O protocols for data access.  The system is implemented in Java and we rely on the BouncyCastle library to establish secure connections to our server.

One of the I/O protocols is called _xrootd_ (http://xrootd.org). We implement the _xrootd_ server in Java and our users utilize the _xrootd_ client, called _xrdcp_, provided by http://xrootd.org, to access the data. The client is implemented in C++.

When we switched from BC 1.46 to 1.50, we started to encounter this error:

```
javax.crypto.BadPaddingException: pad block corrupted
        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source) ~[bcprov-jdk15on-1.50.jar:1.50.0]
        at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[na:1.8.0_141]
```

in about 0.5% of the transfers.

We traced the error to the implementation of this function, which changed between 1.46 to 1.5:

`org.bouncycastle.jcajce.provider.asymmetric.dh.KeyAgreementSpi.bigIntToBytes`

where leading-zero padding of the byte array was introduced. This padding was not present in the 1.46 version of this function.

We also discovered that the _xrdcp_ client uses the _openssl_ function

`DH_compute_key`

instead of

`DH_compute_key_padded`

and that is why it fails when used against our system with BC 1.50.

We verified that :

1. We can successfully use the existing _xrdcp_ client against our system with a custom BC jar which reverts to the old (non-padded) implementation of `bigIntToBytes`.
2. Fixing the _xrdcp_ client by replacing `DH_compute_key` with `DH_compute_key_padded` works against our system with the 1.50 BC jar provided by you.

Unfortunately, (2) is not really a solution, as replacing `DH_compute_key`  with `DH_compute_key_padded` makes the client incompatible with the existing server implementations.  Although if there are very strong arguments for using the padded version, we can present these arguments when speaking with the _xrootd_ developers.

For us, it would have been ideal if BC (like _openssl_) could support both the padded and unpadded key finalization/exchange. 

What do you think?

Thanks for your input.

**Comment by dghgit** [comment]
Closing as resolved in BC 1.64.
