### ISSUE TITLE
BC DH key pair gen works for 512 and 2048 sizes, throws exception for 1024

### ISSUE THREAD

**Issue by justincranford** [bcgit/bc-java#419]
BC 1.60 throws a cryptic exception for DH key pair generator with size 1024.

```
java.lang.IllegalArgumentException: 'min' may not be greater than 'max'
	at org.bouncycastle.util.BigIntegers.createRandomInRange(Unknown Source)
	at org.bouncycastle.crypto.generators.DHKeyGeneratorHelper.calculatePrivate(Unknown Source)
	at org.bouncycastle.crypto.generators.DHBasicKeyPairGenerator.generateKeyPair(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.dh.KeyPairGeneratorSpi.generateKeyPair(Unknown Source)
```

I used JDK 8u181 on Windows x86_64 with bcprov-jdk15on-1.60.jar. I looped over providers SunJCE and BC, and I tried to generate sizes 512, 1024, and 2048. BC successfully generates DH key pairs for sizes 512 and 2048, but not 1024.

This is an odd result. DH 1024 key agreement is apparently mandatory for JDK 8 platform but not third-party providers like BC. However, why would BC DH key generation work for DH 512 and 2048 sizes, but not DH 1024?

- https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html
> Every implementation of the JDK 8 platform must support the specified algorithms in the table that follows. These requirements do not apply to 3rd party providers. Consult the release documentation for your implementation to see if any other algorithms are supported.

Here is a code snippet with results to illustrate what I found. Thank you.

```
DH size 512, provider SunJCE: Success=100, Fail=0
DH size 1024, provider SunJCE: Success=100, Fail=0
DH size 2048, provider SunJCE: Success=100, Fail=0
DH size 512, provider BC: Success=100, Fail=0
DH size 1024, provider BC: Success=0, Fail=100
DH size 2048, provider BC: Success=100, Fail=0
```

```
final SecureRandom secureRandom = SecureRandom.getInstanceStrong();
final int          maxTries     = 100;
final int[]        keySizes     = new int[] {512,1024,2048};
final String[]     providers    = new String[] {"SunJCE","BC"};
for (final String provider : providers) {
	for (final int keySize : keySizes) {
		int success=0, fail=0;
		for (int i=0; i<maxTries; i++) {
			try {
				final KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("DH", provider);
				keyPairGenerator.initialize(keySize, secureRandom);
				keyPairGenerator.generateKeyPair();
				success++;
			} catch(Exception e) {
				fail++;
			}
		}
		System.out.println("DH size " + keySize + ", provider " + provider + ": Success=" + success + ", Fail=" + fail);
	}
}
```

**Comment by justincranford** [comment]
I should clarify that BC DH key agreement works with sizes 512, 1024, and 2048. I can generate DH 512, 1024, and 2048 key pair sizes with SunJCE and use them in BC DH key agreement. Only the BC DH key pair generator is giving me an unexpected exception, and only for size 1024.

**Comment by bcgit** [comment]
Thanks for the report. Turned out the m value was too high for the new preconfigured parameters for 1024. Have adjusted it. Should appear in the next 161b14
