### ISSUE TITLE
DH_anon key exchange treated as non-ephemeral

### ISSUE THREAD

**Issue by ncallister** [bcgit/bc-java#421]
I'm using the newer `org.bouncycastle.tls` library and I have run into an issue when using anonymous ciphers.

Because anonymous ciphers don't use a certificate, and thus don't rely on a signature algorithm, both `DH_anon` and `ECDH_anon` cipher suites can be supported at the same time on both client and server.

The problem is that `AbstractTlsClient#getClientExtensions()` only checks for DHE cipher suites when deciding whether or not to offer DH supported groups. This means that if ECDH ciphers are also supported by the client then it will specify EC groups (`secp256r1` and `secp384r1`) but no DH finite field groups.

At the same time `AbstractTlsServer#selectDHConfig()` will specifically look for DH groups for DHE cipher suites but allows the selection of EC groups for DH_anon cipher suites. This leads to a `NullPointerException` when `TlsDHKeyExchange` calls `TlsDHUtils.writeDHConfig` because `getDHGroup` returns `null`.

To replicate: Attempt to connect a `DefaultTlsClient` to a `DefaultTlsServer` where the client supports a `DH_anon` cipher suite and a `ECDH_anon` cipher suite and where the server selects the `DH_anon` cipher suite.

To fix: Add `KeyExchangeAlgorithm.DH_anon` (and probably `KeyExchangeAlgorithm.DH_anon_EXPORT`) to the list in `TlsDHUtils#isDHECipherSuite(int)`.

Disclaimers:

Note that I haven't tested that simpler, more appropriate fix. Because I have to work with released versions of bouncy castle I have customised my server and client implementations to override functions from the abstract classes and work around the problem.

I am also kind of new to encryption. I have tried to confirm the logic behind this but someone with more experience with TLS, and the BC code, may know a more appropriate fix. I am basing my logic on [RFC-2246](https://www.ietf.org/rfc/rfc2246.txt) section 7.4.3 which lists DH_anon along with the DHE key exchanges. I have not yet worked out how the key exchanges are linked to the groups however I can say that when it selects an ffdhe group it works.

**Comment by peterdettman** [comment]
Your analysis is correct, and adding DH_anon (and EXPORT version for completeness) to that list is the appropriate solution. Fix has been pushed to our git. Thanks for the bug report.
