### ISSUE TITLE
SocketFactory autoclose, has different behavior than other JSSE providers

### ISSUE THREAD

**Issue by Gilis95** [bcgit/bc-java#424]
Hello, we've used Certicom JSSE provider up to this moment. We decided to upgrade to BC JSSE and we hit a problem of closed sockets. In case of any failure, during socket read you close the socket if autoclose is set to true, but other libraries are dependent of this socket not to be closed, although there is an exception. You can see this issue described in details here: https://issues.apache.org/jira/browse/HTTPCORE-561

**Comment by peterdettman** [comment]
Thanks, we'll look into it.

**Comment by peterdettman** [comment]
Please confirm the version of the BC jars that you are using. This bug sounds a lot like something that was fixed in 1.60 already. Is the issue only with SocketTimeoutException or exceptions in general?

see

**Comment by Gilis95** [comment]
Thanks a lot. This resolves the issue.
