### ISSUE TITLE
DiffieHellman Jca keys throw NullPointerException on getEncoded()

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#429]
DiffieHellman keys created through the BouncyCastle Jca Provider throw a NullPointer exception on calling getEncoded() in the case when Q != null (as in the rfc7919 groups). 

Sample code follwos

`    
public static void main(final String[] pArgs) {
        /* Register provider */
        Provider BCPROV = new BouncyCastleProvider();
        Security.addProvider(BCPROV);

        try {
            /* Create keyPair */
            KeyPairGenerator kpGen = KeyPairGenerator.getInstance("DH", BCPROV);
            DHDomainParameterSpec mySpec = new DHDomainParameterSpec(DHStandardGroups.rfc7919_ffdhe2048);
            kpGen.initialize(mySpec, new SecureRandom());
            KeyPair kp = kpGen.generateKeyPair();

            /* Obtain encoded keys */
            PKCS8EncodedKeySpec pkcs = new PKCS8EncodedKeySpec(kp.getPrivate().getEncoded());
            X509EncodedKeySpec x509 = new X509EncodedKeySpec(kp.getPublic().getEncoded());

        } catch (InvalidAlgorithmParameterException e) {
            /* Bad algrorithmParameters */
        } catch (NoSuchAlgorithmException e) {
            /* Bad algorithm */
        } catch (NullPointerException e) {
            /* Help!!! */
            System.out.println("Help!!");
        }
    }
`

**Comment by bcgit** [comment]
Thanks for the report. Now fixed, will show up in the next beta 161b20.
