### ISSUE TITLE
Invalid signature for mime messages with unix line breaks

### ISSUE THREAD

**Issue by slowcar** [bcgit/bc-java#430]
I am trying to create signed email messages on Android and have found an issue that involves line breaks.
If the mime message contains text or a text attachment with unix '\n' line breaks the created signature is invalid.
If i replace the line breaks with windows line breaks '\r\n' the created signature is valid.
I am using the following library versions: bcprov-jdk15on:1.59, bcpg-jdk15on:1.59, bcpkix-jdk15on:1.59

This is the code, given a MimeMessage mimeMessage, PrivateKey privateKey and X509Certificate cert.
`ASN1EncodableVector attributes = new ASN1EncodableVector();
attributes.add(new SMIMEEncryptionKeyPreferenceAttribute(new IssuerAndSerialNumber(new X500Name(cert.getIssuerDN().getName()), cert.getSerialNumber())));
SMIMESignedGenerator gen = new SMIMESignedGenerator();
JcaSimpleSignerInfoGeneratorBuilder signInfo = new JcaSimpleSignerInfoGeneratorBuilder();
signInfo.setSignedAttributeGenerator(new AttributeTable(attributes));
SignerInfoGenerator signBuild = signInfo.build("SHA1WithRSA", privateKey, cert);
gen.addSignerInfoGenerator(signBuild);
gen.addCertificates(new JcaCertStore(certificateList));
MimeMultipart signedContent = gen.generate(mimeMessage);
mimeMessage.setContent(signedContent, signedContent.getContentType());
mimeMessage.saveChanges();`

**Comment by bcgit** [comment]
You would expect this. See section 3.1.1.  Canonicalization of RFC 5751 for details as to why.
