### ISSUE TITLE
The method CSHAKEDigest.leftEncode() is incorrect.

### ISSUE THREAD

**Issue by xipki** [bcgit/bc-java#431]
https://github.com/bcgit/bc-java/blob/5d17720a0d5d61f2b6b198a059caccbda811724f/core/src/main/java/org/bouncycastle/crypto/digests/CSHAKEDigest.java#L62

According to the standard NIST SP 800-185, e.g. `leftEncode(1600)` shall be encoded as `0x020640`, but this method returns `0x024006`.

Otherwise, this method cannot handle negative integer as parameter.
An example implementation may be as follows:
```
private byte[] leftEncode(int strLen)
{
    long lx = strLen < 0 ? 0x100000000L + strLen : strLen;
    final int len;
    if (lx >= 0x1000000)
    {
        len = 4;
    }
    else if (lx >= 0x10000)
    {
        len = 3;
    }
    else if (lx >= 0x100)
    {
        len = 2;
    }
    else {
        len = 1;
    }

    byte[] res = new byte[1 + len];
    res[0] = (byte) len;

    long tx = lx;
    for (int i = len; i >= 1; i--)
    {
        res[i] = (byte) tx;
        tx = tx >> 8;
    }

    return res;
}
```

**Comment by bcgit** [comment]
Thanks for the report. Yes, the endianness was wrong! Now fixed, revised function should show up on here shortly and in the next beta 161b20.
