### ISSUE TITLE
In v1.60.0, the 'PBEWithSHA1AndDESede' cipher is not compatible with Sun/JCE's cipher of the same name.

### ISSUE THREAD

**Issue by rodburgett** [bcgit/bc-java#433]
This cipher was not supported in BC v1.52.0.  Requesting it by name, even when BC is registered as the first security provider, returned a Cipher instance from Sun/JCE.

In BC v1.60.0, a request for the cipher returns an instance from BC provider, but this cipher is not compatible with the one returned by Sun/JCE.  An encryption by one cannot be decrypted by the other.

To repro:
1) Register the BC provider at position 1; Security.insertProviderAt( new BouncyCastleProvider(), 1 );
2) Encrypt a string using Sun/JCE provider, name 'SunJCE'.
3) Decrypt the result using no named provider; search will start with BC.
4) Repeat steps 2 and 3 with default/BC to encrypt and Sun/JCE to decrypt.

Using BC v1.52.0, both decryptions work.  Using BC v1.60.0, both decryption attempts throw BadPaddingException.

**Comment by bcgit** [comment]
If you can provide some example code I should be able to tell you what the issue is.

**Comment by rodburgett** [comment]
I agree with the original sentiment that BC SHOULD not be involved in this scenario.  And in v1.52 it is not.  But in v1.60 a BC Cipher instance is returned by Cipher.getInstance(name)

Attaching a simple driver that demonstrates the problem.  Compile with either BC version, then run with BC v1.52.0, then run with BC v1.60.0
[Repro432.zip](https://github.com/bcgit/bc-java/files/2624386/Repro432.zip)

**Comment by bcgit** [comment]
Thanks. I've found the issue. The problem is because of a missing key factory in the BC provider.

If you add:
bcProv.put("Alg.Alias.SecretKeyFactory.PBEWITHSHA1ANDDESEDE", "PBEWITHSHAAND3-KEYTRIPLEDES-CBC");
after you create the provider, it should work.

Updated code should appear on github shortly. It will be in the next beta 161b20 as well.
