### ISSUE TITLE
ISO9797Alg3Mac always adds padding bytes

### ISSUE THREAD

**Issue by j-katz** [bcgit/bc-java#436]
I want to use the ISO9797Alg3Mac class with DESEngine and ZeroBytePadding. Messages with a multiple of the block size (8 bytes) shall not be padded.

If a padding algorithm is passed to the ISO9797Alg3Mac constructor, every message is padded. If the message has a length of the block size, a full block of padding data is added. From the documentation I would not expect this behaviour.

**Comment by worsaae** [comment]
If sender only add padding to some blocks then how do the receiver know if
it should remove padding or not?

**Comment by j-katz** [comment]
I have nothing more than the Wikipedia article: https://en.wikipedia.org/wiki/ISO/IEC_9797-1 which could be wrong: "Padding method 1: If necessary, add bits with value 0 to the end of the data until the padded data is a multiple of n. (If the original data was already a multiple of n, no bits are added.)"

On the other hand, the Python code linked on the Stackexchange link, adds a full block of padding data for the padding method 1 (so it does the same as BouncyCastle).

I can live with this behavior, but I suggest a note to the constructors of class ISO9797Alg3Mac, as from the existing documentation of parameter padding ("the padding to be used to complete the last block.") I did not expect that a complete block of padding data can be added to the message.

Thanks for your response and time!
