### ISSUE TITLE
Using "AES/CBC/PKCS5PADDING" leaves decrypted information in memory

### ISSUE THREAD

**Issue by DavidBlat** [bcgit/bc-java#437]
Using "AES/CBC/PKCS5PADDING" with BC provider leaves decrypted data exposed in memory. See CWE-316 for more details (https://cwe.mitre.org/data/definitions/316.html). 

The text of 'sensitiveClearText' can be enumerated in memory dump, after running the following encryption code : 
   byte[] sensitiveClearText = new byte[] { .....}; //set sensitiveClearText with unique string 
   IvParameterSpec iv = new IvParameterSpec(initVector.getBytes("UTF-8")); 
   SecretKeySpec skeySpec = new SecretKeySpec(key.getBytes("UTF-8"), "AES"); 
   Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING"); 
   cipher.init(Cipher.ENCRYPT_MODE, skeySpec, iv); 
   byte[] encrypted = cipher.doFinal(sensitiveClearText); 
   Arrays.fill(sensitiveClearText, (byte)0); // clear sensitiveClearText from memory (and expect to 0 occurrences in memory) 

< Dump memory and enumerate sensitiveClearText> 

The text of 'sensitiveClearText' can be enumerated in memory dump, after running the following decryption code : 
   IvParameterSpec iv = new IvParameterSpec(initVector.getBytes("UTF-8")); 
   SecretKeySpec skeySpec = new SecretKeySpec(key.getBytes("UTF-8"), "AES"); 
   Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING"); 
   cipher.init(Cipher.DECRYPT_MODE, skeySpec, iv); 
   byte[] sensitiveClearText= new Base64().decode(encrypted.getBytes()); 
   byte[] original = cipher.doFinal(sensitiveClearText); // clear sensitiveClearText from memory (and expect to 0 occurrences in memory) 
   Arrays.fill(original, (byte)0); 

< Dump memory and enumerate sensitiveClearText> 

Thank You,
David

**Comment by bcgit** [comment]
You might find it works better if you use Cipher.getInstance("AES/CBC/PKCS5PADDING", "BC");
