### ISSUE TITLE
Server side SNI support in BCJSSE

### ISSUE THREAD

**Issue by weltreisender** [bcgit/bc-java#439]
Hello,

we are currently missing SNI support on server side in BCJSSE 1.60. 

Normally we would get the SNI by extending the ```javax.net.ssl.X509ExtendedKeyManager``` as follows:

```
@Override
public String chooseEngineServerAlias(final String keyType, 
    final Principal[] issuers, 
    final SSLEngine engine) {

    SSLSession handshakeSession = engine.getHandshakeSession();
    if (handshakeSession instanceof ExtendedSSLSession) {
        ExtendedSSLSession extendedSession = (ExtendedSSLSession) handshakeSession;
        SNIServerName sniServerName = extendedSession.getRequestedServerNames().get(0);
        if (sniServerName.getType() == 0) {
            SNIHostName sniHostName = (SNIHostName)sniServerName;
            return sniHostName.getAsciiName();
        }

    } else {
        return null;
    }
}
```

Unfortunately, this is not yet supported by BCJSSE. 
Currently the ```ProvTlsServer``` imlements the KeyManager call as follows:

```
protected boolean selectCredentials(int cipherSuite) throws IOException
{

    // ... Line 463
    // TODO[jsse] How is this used?
    Socket socket = null;

    String alias = km.chooseServerAlias(keyType, issuers, socket);

    // ...
}
```

This means, that **only** the method ```chooseServerAlias``` is called and not ```chooseEngineServerAlias``` and further more, the socket is fixed set to ```null```.

As this part is clearly marked as TODO, the question is: 
Is there currently someone working on this topic? If so, are there any plans when this will be released? And if not, how could I support here?

Regards
Achim

**Comment by peterdettman** [comment]
Thanks for the report. It's very helpful for us to get concrete examples of missing parts of our JSSE implementation, as it gives us practical use cases to work through. As it happens I am currently trying to improve the keystore/truststore interactions and support for getHandshakeSession is high on my TODO list, which would then allow to rectify your use case above.

Please note that things are complicated by our desire to support an extension API so that e.g. ExtendedSSLSession (JDK 1.7) features are usable back to 1.5.

There should be a release before the end of the year and we would like to improve this area as much as possible before then. I will report any progress here and your support in testing a beta version would be valuable.

**Comment by weltreisender** [comment]
Thank you for the quick reply.
Just let me know, when and where the beta version is available.

**Comment by peterdettman** [comment]
@weltreisender It took a while but the latest beta at https://downloads.bouncycastle.org/betas/ should now support getHandshakeSession (from JDK7) and getRequestedServerNames (from JDK8). We'd appreciate if you could give it a try.

On a side note, I would advise changing the example code in a couple of ways:
- Don't assume the host_name will be the first server name, but loop over all server names until finding one with the expected type. Although only host_name is currently specified (and only one can be in the list), unrecognised types can appear and should be tolerated (ignored).
- Check 'instanceof SNIHostName' before casting, and then create your own instance if necessary with 'new SNIHostName(sniServerName.getEncoded())'.

**Comment by weltreisender** [comment]
Thank for the update. My code above lacks any error handling because I just tried to reduce it as much as possible to describe the use case.

I will inform my colleague who is working on this topic. I'll give you feedback as soon as possible.

**Comment by peterdettman** [comment]
@LarsKaulen Thanks for the confirmation, a full release should be out shortly.

> create your own instance _if necessary_

 i.e.

```
    SNIHostName sniHostName = (sniServerName instanceof SNIHostName)
        ?   (SNIHostName)sniServerName
        :   new SNIHostName(sniServerName.getEncoded());
```
