### ISSUE TITLE
Remove the order and cofactor from ECCurve.F2m

### ISSUE THREAD

**Issue by danielfitzpatrick** [bcgit/bc-java#44]
ECCurve.F2m includes the order n and cofactor h. These don't make sense without the base point G and are not part of ECurve.Fp. I'd suggest removing them from ECCurve.F2m and making sure that the code always uses the order and cofactor from ECDomainParameters.

**Comment by peterdettman** [comment]
So, we kind of went the other way and included cofactor and order for Fp curves too. It's not really correct for these things to be part of the "curve", but we'd prefer not to tinker too much (more) with the current math.ec API.
