### ISSUE TITLE
McEliece Cipher returns incorrect OutputLength

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#441]
When using the the "McEliece" JCA Cipher, the call getOutputSize(inLen) always returns the same value as getBlockSize().

This is incorrect and line 107 in prov/src/main/java/org/bouncycastle/pqc/jcajce/provider/util/AsymmetricBlockCipher.java
should read 

return opMode == ENCRYPT_MODE ? cipherTextSize : maxPlainTextSize;

**Comment by bcgit** [comment]
Thanks for the report. Fixed, will show up in 161b25.
