### ISSUE TITLE
McEliece JCA initialisation with parameters and random is no-op

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#442]
It is not possible to use the initialize(AlgorithmParameterSpec params, SecureRandom random) method to initialise any McEliece JCA cipher. The underlying Java implementation is a no-op and the BC implementation does not supply an override for either standard or CCA2 McEliece. 

Sample code. 

` 

           /* Create and initialise the generator */
            final KeyPairGenerator myGenerator = KeyPairGenerator.getInstance("McEliece", "BCPQC");
            final McElieceKeyGenParameterSpec mySpec = new McElieceKeyGenParameterSpec(McElieceKeyGenParameterSpec.DEFAULT_M,
                    McElieceKeyGenParameterSpec.DEFAULT_T);
            myGenerator.initialize(mySpec, new SecureRandom());

            /*
             * Generate the keyPair. This will generate a NullPointerException since the version of
             * initialise used is a NoOp
             */
            myGenerator.generateKeyPair();
            /* Doesn't reach here */
`
and 

`

            /* Create and initialise the generator */
            final KeyPairGenerator myGenerator = KeyPairGenerator.getInstance("McEliece-CCA2", "BCPQC");
            final McElieceCCA2KeyGenParameterSpec mySpec = new McElieceCCA2KeyGenParameterSpec(McElieceCCA2KeyGenParameterSpec.DEFAULT_M,
                    McElieceCCA2KeyGenParameterSpec.DEFAULT_T, McElieceCCA2KeyGenParameterSpec.SHA512);
            myGenerator.initialize(mySpec, new SecureRandom());

            /*
             * Generate the keyPair. This will generate a NullPointerException since the version of
             * initialise used is a NoOp
             */
            myGenerator.generateKeyPair();
            /* Doesn't reach here */

`

**Comment by bcgit** [comment]
Thanks for the report. Fixed, will show up in 161b25.
