### ISSUE TITLE
Actual DTLS Support

### ISSUE THREAD

**Issue by zmimlitz** [bcgit/bc-java#445]
### Problem
I'm attempting to use Bouncy Castle to encrypt UDP on Android 7. I've imported bctls-jdk15on version 1.60 (which is I believe the latest) and found your implementation of DTLS to be lacking. I'm attempting to interface and Android application with an OpenSSL based C++ application via DTLS and at this point have deemed it impossible.

### Recognition
I have found the test examples for both the DTLS Client and Server and successfully gotten them talking to one another, but cannot get either example to talk to the C++ application. This would indicate that your implementation is not failed, it's simply outside the spec and very difficult to use. I'm aware that DTLS has a vague spec and is not commonly used but it's still an import aspect of modern cryptography. 

### Proposal
Digging through your source code, I have found multiple //TODO comments, uncertain questions, and bad coding practice. The backbone of your implementation doesn't seem to have been touched in years, there are several outstanding issues here from 2016 with problems still applicable today, and most of the conversations I've found relating to using BC for DTLS end with people giving up. So I would like to ask that you dedicate some serious attention in your next release cycle to completing DTLS. Notable problems from my experience over the last several weeks:

- You have no support for HelloVerifyRequest assuming that the client will resend ClientHello, which is outside of the spec and costs users a lot of DOS protection
- DTLSServerProtocol#accept is an unsafe blocking call with no interrupt or timeout functionality
- Error handling throughout the library is terrible, errors are swallowed without being noted or accessible often with unclear or incorrect assumptions about their origin
- Many elements and behavior of the DatagramSocket passed into the API (such as SOTimeout) are overridden with local constants within your library, removing user control
- DTLS Heartbeats seem loosely (if at all) implemented and without them DTLS is difficult to deploy in a real environment
- You seem to implement fewer algorithms for DTLS than TLS despite the fact they should utilize all the same engines under the hood

And that's where I gave up. I found your TLS implementation usable, if convoluted, but DTLS is disappointingly incomplete, and there really no alternative for BC out there.

**Comment by bcgit** [comment]
Support contracts are available from https://www.cryptoworkshop.com

**Comment by zmimlitz** [comment]
Thank you, but I'm not looking for/can't afford support. Just pointing out that one of your advertised features in incomplete in Java.

**Comment by bcgit** [comment]
No problem. Will keep the issues in mind, just cannot say when will be done.

**Comment by 15989206052** [comment]
> ### Problem
> I'm attempting to use Bouncy Castle to encrypt UDP on Android 7. I've imported bctls-jdk15on version 1.60 (which is I believe the latest) and found your implementation of DTLS to be lacking. I'm attempting to interface and Android application with an OpenSSL based C++ application via DTLS and at this point have deemed it impossible.
> 
> ### Recognition
> I have found the test examples for both the DTLS Client and Server and successfully gotten them talking to one another, but cannot get either example to talk to the C++ application. This would indicate that your implementation is not failed, it's simply outside the spec and very difficult to use. I'm aware that DTLS has a vague spec and is not commonly used but it's still an import aspect of modern cryptography.
> 
> ### Proposal
> Digging through your source code, I have found multiple //TODO comments, uncertain questions, and bad coding practice. The backbone of your implementation doesn't seem to have been touched in years, there are several outstanding issues here from 2016 with problems still applicable today, and most of the conversations I've found relating to using BC for DTLS end with people giving up. So I would like to ask that you dedicate some serious attention in your next release cycle to completing DTLS. Notable problems from my experience over the last several weeks:
> 
> * You have no support for HelloVerifyRequest assuming that the client will resend ClientHello, which is outside of the spec and costs users a lot of DOS protection
> * DTLSServerProtocol#accept is an unsafe blocking call with no interrupt or timeout functionality
> * Error handling throughout the library is terrible, errors are swallowed without being noted or accessible often with unclear or incorrect assumptions about their origin
> * Many elements and behavior of the DatagramSocket passed into the API (such as SOTimeout) are overridden with local constants within your library, removing user control
> * DTLS Heartbeats seem loosely (if at all) implemented and without them DTLS is difficult to deploy in a real environment
> * You seem to implement fewer algorithms for DTLS than TLS despite the fact they should utilize all the same engines under the hood
> 
> And that's where I gave up. I found your TLS implementation usable, if convoluted, but DTLS is disappointingly incomplete, and there really no alternative for BC out there.

I am also looking for the implementation of BC DTLS, but there is no gain in a few days. Does the problem you mentioned still exist?
