### ISSUE TITLE
Invalid XMSS/XMSSMT signature after updating and storing privateKey

### ISSUE THREAD

**Issue by UnicornDeluxe** [bcgit/bc-java#446]
Hi,
There seems to be a problem with XMSS/XMSSMT privateKeys serialization.

Regardless with which digestAlg and height/layers used, one privateKey used like: load -> sign -> update -> save, produces invalid signatures after the second signing. (However it seems to be especially consistent for SHA512withXMSSMT height = 4, layers = 2)
Maybe this goes in the same direction as [this](https://github.com/bcgit/bc-java/issues/380).

This happens with the 160 version as well as with the 161b20 beta version.

**Comment by bcgit** [comment]
Can you provide an example for this?

**Comment by bcgit** [comment]
I think I've found it. It was not fun... Try 161b22, it is now up on https://www.bouncycastle.org/betas Let us know how you go. Thanks.

**Comment by UnicornDeluxe** [comment]
Thank you very much for your effort, it works perfectly fine now!

**Comment by bcgit** [comment]
And thank you for your help. Glad to hear it's working.

**Comment by bcgit** [comment]
I'll look into the getState() (getUsagesRemaining()?) method. I think we can add something to do that, have to investigate first though.

**Comment by UnicornDeluxe** [comment]
Perfect thank you very much! Name it whatever you like, the interesting variable actually is : privateKey -> keyparams -> index, but I guess getUsagesRemaining() is way better than getIndex()!

**Comment by bcgit** [comment]
Latest beta  (161b23) now includes a getRemainingUsages() on the keys and StateAwareSignature.isSigningCapable() now returns false if the key is no longer usable as well.

**Comment by UnicornDeluxe** [comment]
Thank you very much!
