### ISSUE TITLE
In some web apps, there is an interaction with the JIT compiler that appears to result in the SHA libraries being run in interpreted mode

### ISSUE THREAD

**Issue by pojoguy** [bcgit/bc-java#447]
Here is the related Oracle bug report.

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8023983

Key features:
1. There is no reliable reproduction. 
2. However, once reproduced in an application it is "always reproducible". 
3. The issue impacts classloader and SSL communications

The classloader impacts can be sidestepped by preloading classes, but the SSL processing continues to be executed in interpreted mode. This provides a hint that that a JIT recompile may be having issues.

**Comment by dghgit** [comment]
This is now listed as resolved on the Oracle bug database.
