### ISSUE TITLE
"RSA modulus has a small prime factor" makes it impossible to load some externally-constructed public keys

### ISSUE THREAD

**Issue by amyodov** [bcgit/bc-java#449]
`RSAKeyParameters`, namely the code in [lines 39–47](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/params/RSAKeyParameters.java#L39), has a security feature to prevent using the public keys with unsafe (short) prime factors. 

The problem is that some other RSA implementations may still generate such unsafe public keys; with the current check, you won’t be able even to load them, even if you accept the fact they are insecure.

Proposed solution:

Create a new constructor, with a new argument like `allowUnsafeModulus` (default `=false`) or `performValidate` (default `=true`) or something; so this argument could be used to use the RSA keys no matter of their safety.

**Comment by davidbarkhuizen** [comment]
Yeah, but if for some reason we have to decrypt a ciphertext that was encrypted using a poor-quality key, then we cannot use this lib to do it.

**Comment by mouse07410** [comment]
You must test keys you generate. Any you must allow loading external keys - warn if you must but do not block.

**Comment by bcgit** [comment]
Yes, actually the "obfuscated" might be better than the word "encrypted" as well. The keys should not be used.

That said, I've added a system property org.bouncycastle.rsa.allow_unsafe_mod which will allow such keys to be used under supervision. It will show up in 162b12 in the betas area.

**Comment by davidbarkhuizen** [comment]
Perfect compromise - thank you.

**Comment by ksgsharma** [comment]
Is this fix available for .NET version as well?
