### ISSUE TITLE
ECIES-KEM fails when Cofactor is utilised

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#451]
When ECIES-KEM is used with either coFactorMode or oldCoFactorMode, the exchange fails and sender and receiver derive different keys.

The offending line appears to be in encrypt() in ECIESKeyEncapsulation.java

            // Compute the static-ephemeral key agreement
            BigInteger rPrime = CofactorMode ? r.multiply(h).mod(n) : r;

This should read 

            BigInteger rPrime = OldCofactorMode ? r.multiply(h).mod(n) : r;

according to [https://www.shoup.net/iso/std4.pdf](url) page 34

Sample code as follows:-

`    /**
     * Main entry.
     * @params pArgs the arguments
     */
    public static void main(final String[] pArgs) {

        /* Create the generator */
        ECKeyPairGenerator myGenerator = new ECKeyPairGenerator();
        SecureRandom myRandom = new SecureRandom();
        String myCurve = "sect571k1"; /* Any curve will do */

        /* Lookup the parameters */
        final X9ECParameters x9 = ECNamedCurveTable.getByName(myCurve);

        /* Initialise the generator */
        final ASN1ObjectIdentifier myOid = ECUtil.getNamedCurveOid(myCurve);
        ECNamedDomainParameters myDomain = new ECNamedDomainParameters(myOid, x9.getCurve(), x9.getG(), x9.getN(), x9.getH(), x9.getSeed());
        ECKeyGenerationParameters myParams = new ECKeyGenerationParameters(myDomain, myRandom);
        myGenerator.init(myParams);

        /* Create the key Pair */
        AsymmetricCipherKeyPair myPair = myGenerator.generateKeyPair();

        /* Determine message length */
        int myFieldSize = x9.getCurve().getFieldSize();
        myFieldSize = (myFieldSize + Byte.SIZE - 1) / Byte.SIZE;
        int myLen = 2 * myFieldSize + 1;
        byte[] myMessage = new byte[myLen];
        int myKeyLen = 256 / Byte.SIZE;

        /* Create agreement */
        //ECIESKeyEncapsulation myAgreement = new ECIESKeyEncapsulation(new KDF2BytesGenerator(new SHA512Digest()), myRandom); // This works
        ECIESKeyEncapsulation myAgreement = new ECIESKeyEncapsulation(new KDF2BytesGenerator(new SHA512Digest()), myRandom, true, false, false); // This fails
        myAgreement.init(myPair.getPublic());
        KeyParameter mySender = (KeyParameter) myAgreement.encrypt(myMessage, myKeyLen);
        byte[] mySenderKey = mySender.getKey();

        /* Accept agreement */
        myAgreement.init(myPair.getPrivate());
        KeyParameter myReceiver = (KeyParameter) myAgreement.decrypt(myMessage, myKeyLen);
        byte[] myReceiverKey = myReceiver.getKey();

        /* Check that keys match  */
        if (!Arrays.areEqual(mySenderKey, myReceiverKey)) {
            System.out.println("ECIES failed");
        }
    }
`

**Comment by bcgit** [comment]
Thanks for the report. Should now be fixed. Will show up in 161b25
