### ISSUE TITLE
Is there a reason why ASN1Object is not Serializable?

### ISSUE THREAD

**Issue by phax** [bcgit/bc-java#464]
Hi,
it would be nice if ASN1Object becomes serializable, so that e.g. derived `ASN1ObjectIdentifier` can be safely used in serialized objects etc.
Thanks,
  Philip

**Comment by bcgit** [comment]
I think this might be a case of being careful what you wish for. It's actually a feature of the ASN.1 API that it doesn't use Java serialization - it means there's no risk of code being executed loading one of the structures.

**Comment by mouse07410** [comment]
The risk actually is with **de**serialization. 

But it didn’t alleviate the fact that it is a useful capability to have.

**Comment by bcgit** [comment]
This is true, but the experience with this has shown that if things are too convenient, very inconvenient things can happen.

**Comment by mouse07410** [comment]
I’ve only 30+ years of experience, and it doesn’t agree with your logic/observation. 

A capability is either needed, or not. You can’t avoid the need to serialize **and deserialize** various objects. You can be attacked just as easily by a malformed encoding of a cert as by a malformed generic object. So, I don’t see much harm in supporting the requested capability.

**Comment by phax** [comment]
I tend to agree here with @mouse07410 - as long as you offer the capability but not actively use it, you are good. Of course from a support perspective, each new capability must be supported and there should be a reason "why". You @bcgit have a reason "why not" which is also fine for me, even though I don't 100% follow your argumentation here.

**Comment by bcgit** [comment]
We'll have to agree to disagree. This is no place for old men to be arguing!

**Comment by mouse07410** [comment]
We should continue this argument in a bar. :-)

P.S. “Space Cowboys”? :-)

**Comment by bcgit** [comment]
Absolutely. On both points!
