### ISSUE TITLE
GOST 3410-2012 (256) signature verify failture

### ISSUE THREAD

**Issue by Ded0k** [bcgit/bc-java#469]
Hello.
I was received several documents with a detached signature, created in accordance with GOST R 34.10-2012 (256) sign algorithm and GOST R 34.11-2012 (256) hash algorithm. And I can't verify part of these files with BouncyCastle java library.
All the files in the example are verified using CryptoARM software (https://www.cryptopro.ru/products/partner/crypto-arm) and using online signature verification at https://www.gosuslugi.ru/pgu/eds/, and they are OK, but BouncyCastle says that the signatures for "C_00153.pdf.sig" and "C_00200.pdf.sig", maked by one user, is invalid.
Digest of files calculated correctly and chain of certificate is correct, I will check it
Tell me what could be the problem?

I try on BouncyCastle 1.61, JDK 1.7.0_67
My code and signature files in attach. Thanks in advance.
[sig.zip](https://github.com/bcgit/bc-java/files/2910735/sig.zip)

**Comment by algv** [comment]
I think problem with signed attributes, check it https://github.com/bcgit/bc-java/issues/286#issuecomment-362770499

**Comment by Ded0k** [comment]
> I think problem with signed attributes, check it [#286 (comment)](https://github.com/bcgit/bc-java/issues/286#issuecomment-362770499)

Yes, you are right. Thanks, it helped me.
