### ISSUE TITLE
Broken ByteBuffer support for AAD

### ISSUE THREAD

**Issue by SalusaSecondus** [bcgit/bc-java#470]
Context:  [BaseBlockCipher.java#L1000](https://github.com/bcgit/bc-java/blob/master/prov/src/main/java/org/bouncycastle/jcajce/provider/symmetric/util/BaseBlockCipher.java#L1000)

There are two issues regarding `ByteBuffer` handling in `BaseBlockCipher`.
1. It does not properly handle those cases when the `ByteBuffer` lacks an accessible backing array.
2. It does not properly set the position to be equal to the limit upon completion

*Details*
[ByteBuffer](https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html) objects are not guaranteed to support [arrayOffset()](https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#arrayOffset--) or [array()](https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#array--). This means that if a consumer passes in a `ByteBuffer` to [Cipher.updateAAD(ByteBuffer)](https://docs.oracle.com/javase/9/docs/api/javax/crypto/Cipher.html#updateAAD-java.nio.ByteBuffer-) which lacks an accessible backing array (such as a read-only `ByteBuffer` or one acquired through almost any other mechanism than `ByteBuffer.wrap`), line 1002 will throw an exception. Prior to calling either `.arrayOffset()` or `.array()`, you must first call [hasArray()](https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#hasArray--). If this returns false you must allocate a new `byte[]` and use [get(byte[])](https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#get-byte:A-) to fill the array.

As per the documentation around [CipherSpi.engineUpdateAAD(ByteBuffer)](https://docs.oracle.com/javase/9/docs/api/javax/crypto/CipherSpi.html#engineUpdateAAD-java.nio.ByteBuffer-), the position must be set equal to the limit upon return.

**Comment by peterdettman** [comment]
Thanks for the report. We've fixed our engineUpdateAAD on both scores (the changes may not mirror here for a couple of days) and will make a new beta version available early next week.

**Comment by SalusaSecondus** [comment]
Thank you. I'll keep an eye on this. ByteBuffers have bitten many systems in the past so exhaustive testing really does matter.

**Comment by bcgit** [comment]
Closing as issue now fixed.
