### ISSUE TITLE
Current master fails one ASN1 test

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#471]
```

testASN1 | Failure | LocaleTest: no message

junit.framework.AssertionFailedError:  LocaleTest: no message 

at org.bouncycastle.asn1.test.AllTests.testASN1(AllTests.java:22)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)
```

<img width="1239" alt="screen shot 2019-03-01 at 4 00 57 pm" src="https://user-images.githubusercontent.com/5923577/53666156-4f23e400-3c3b-11e9-868d-7dfe6b7176b9.png">

**Comment by bcgit** [comment]
Interesting, what JVM is this on? Thanks.

**Comment by mouse07410** [comment]
Oracle JDK-1.8.0_201

**Comment by bcgit** [comment]
Sorry, I'd forgotten about this one. I know this may sound nuts, but I can't reproduce it. Is it still happening to you?

**Comment by mouse07410** [comment]
As a matter of fact, yes I keep getting this - now on Oracle JDK1.8.0_211.

No clue why.

**Comment by peterdettman** [comment]
I can reproduce this. For me the "bad" locale is JP (Japan). If JP is skipped (like TH), the remaining locales pass.

**Comment by peterdettman** [comment]
I guess it has something to do with this: https://blogs.oracle.com/java-platform-group/a-new-japanese-era-for-java .

**Comment by bcgit** [comment]
Ah, that has the ring of plausibility about it. I've modified the test to skip JP as well. It should appear on the mirror soon, let me know how it goes.

**Comment by mouse07410** [comment]
> Ah, that has the ring of plausibility about it...

You can say that again. ;-)

> I've modified the test to skip JP as well ... let me know how it goes

It goes wonderfully. Test failure disappeared.

Thanks!
