### ISSUE TITLE
Unnecessarily recreating constant object

### ISSUE THREAD

**Issue by jessefeinman** [bcgit/bc-java#474]
In https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/params/RSAKeyParameters.java#L40 a `new BigInteger` is created. Since this is a function, call this is created new every time. 

Rather than creating this every time, since it's a constant, it can be defined as a `private static final BigInteger` at the top of the `RSAKeyParameters` class where the `ONE` constant is also created.

**Comment by peterdettman** [comment]
Thanks, we've extracted it as a static constant.
