### ISSUE TITLE
Update XMSS OIDs

### ISSUE THREAD

**Issue by securitykernel** [bcgit/bc-java#482]
We previously contributed a draft-06 XMSS implementation to [Botan](https://botan.randombit.net) and we are currently [updating the implementation](https://github.com/randombit/botan/pull/1858) to conform to the final [RFC 8391](https://tools.ietf.org/html/rfc8391). We used BouncyCastle's implementation to generate fresh test vectors, as the RFC does not provide these. We noticed that BouncyCastle still uses draft-OIDs instead of the ones from the [final RFC 8391](https://tools.ietf.org/html/rfc8391#section-8) in [core/src/main/java/org/bouncycastle/pqc/crypto/xmss/DefaultXMSSOid.java](https://github.com/bcgit/bc-java/blob/738dfc0132323d66ad27e7ec366666ed3e0638ab/core/src/main/java/org/bouncycastle/pqc/crypto/xmss/DefaultXMSSOid.java). Updating these would increase compatibility of Botan's and BouncyCastle's implementation.

**Comment by bcgit** [comment]
Now fixed.
