### ISSUE TITLE
RSADigestSigner does not support equivalent of NONEwithRSA

### ISSUE THREAD

**Issue by oh2mqk** [bcgit/bc-java#485]
Attached patch creates equivalent behaviour with DigestSignatureSpi.
Specifically when digesting algorithm is unknown (or is supplied as null), it will not add RSA-wrapper around the supplied data -- at least when using NullDigester.

[RSADigestSigner.java.patch.txt](https://github.com/bcgit/bc-java/files/3022144/RSADigestSigner.java.patch.txt)

**Comment by bcgit** [comment]
Now added.
