### ISSUE TITLE
Full fingerprint in gpg signature

### ISSUE THREAD

**Issue by gaellalire** [bcgit/bc-java#492]
When I launch `git log --show-signature` I get

```* gpg: Signature made Thu 04 Apr 2019 05:32:02 PM CEST
| gpg:                using RSA key A3A7C19AC7CACB6A
| gpg: Good signature from "Gael Lalire <...>" [ultimate]
| a67950c4d7 - Commit with EGIT (30 hours ago) <Gaël Lalire>
* gpg: Signature made Thu 04 Apr 2019 05:02:39 PM CEST
| gpg:                using RSA key 3BC5BECD90C3F869B6DC8914A3A7C19AC7CACB6A
| gpg: Good signature from "Gael Lalire <...>" [ultimate]
| 3eab0f0913 - BSL-2446 : Commit with command line (13 days ago) <Gaël Lalire>
```
The a67950c4d7 commit is made with EGIT and is using BouncyCastle through JGIT.
The 3eab0f0913 commit is made with command line and is probably using gpg executable or dynamic library.

The BC commit show A3A7C19AC7CACB6A as RSA key while the command line one show the full fingerprint.

I checked the code in JGIT and I think the reason why we only have a partial fingerprint is in BC. 

I saw some gpg attacks where most of fingerprint was identical. Could you put the full fingerprint in gpg signature ?

**Comment by bcgit** [comment]
This looks like it's using the additional packets in the draft RFC revision of 4880. We can certainly start adding support for those. What version of GPG is producing these?

**Comment by gaellalire** [comment]
gpg (GnuPG/MacGPG2) 2.2.8
libgcrypt 1.8.3

also the archlinux one is producing the same output
gnupg 2.2.15

**Comment by tomaswolf** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=553206 .

Would be nice if BC had at least support for the "[Issuer Fingerprint](https://gitlab.com/openpgp-wg/rfc4880bis/blob/master/draft-ietf-openpgp-rfc4880bis-08.txt#L2288)" sub-packet in signatures. That's the one GPG uses.

**Comment by PT400C** [comment]
Did this problem fell under the radar? It still seems to be present in the latest revision of bc-java.

**Comment by bcgit** [comment]
Support for IssuerFingerprint is in the latest beta - see https://www.bouncycastle.org/betas
