### ISSUE TITLE
ECIES with AES CBC not possible to decrypt without giving public known nonce

### ISSUE THREAD

**Issue by Vamillion** [bcgit/bc-java#493]
Hi there,

my team and I have a problem with the upgrade from BC V.1.54 to 1.61. We used the ECIES/AES CBC algorithm to encrypt messages. Unfortunately, we figured out that from V. 1.56 on, an additional public parameter has to be specified. During the encryption, this parameter is apparently generated automatically, but then this value is apparently needed for decryption as well.  

We are not really sureif it is correct to handle a second public element for decrypting an ECIES/AES CBC encrypted message. Are we right in the assumption that we now have to send this random parameter as well?
Was it really your wish to have a second public parameter that has to be carried for decryption?

We would like to get a better description of the implementation idea with a concrete application example.

According to the current state I am forced to create this vector parameter on my own, to encrypt my object with it, to encrypt this parameter for security reasons maybe even additionally, than to send it to Instance B, so that the decryption can be done there correctly. 

From my point of view, the necessary transfer of a public parameter, and this is the main reason why I open this ticket, does not give me a greater security factor, nor is it more user-friendly to perform encryption and decryption. Previously it was used as well, and it was possible to decrypt the message without having to specify this parameter for decryption.

To sum it all up.
-  We would be happy to get a better use case as an example than the tests I can see.
-  Maybe with the reason and an statement, why it is only possible to use the algorithm with this additional parameter.
- If it is really wanted to force the user to carry another public parameter beside the key for each encryption process.

In addition, we have written a small console program which has a Maven dependency of Bouncy Castle V 1.55 and 1.56. In both cases, I would have expected encryption and decryption to work like expected without any errors occurring.

[Test-Projekt-BC-Version155.zip](https://github.com/bcgit/bc-java/files/3046624/Test-Projekt-BC-Version155.zip)
[Test-Projekt-BC-Version156.zip](https://github.com/bcgit/bc-java/files/3046625/Test-Projekt-BC-Version156.zip)

**Comment by bcgit** [comment]
The no-nonce version was removed as it was found to be vulnerable to a padding oracle attack. This is mentioned in the releasenotes for 1.56. Please do not call Spi classes directly for production applications,  they're internal.

Yes, you need to send the nonce to the decrypting party. No, it does not need to be encrypted, but yes it should be random.

**Comment by Vamillion** [comment]
Thank you very much for the quick answer. I thought that would be the answer. However, I always find questions better than assumptions. Thanks for the information regarding the spi, I wrote it this way to make it more precise.
