### ISSUE TITLE
ClassNotFoundException org.bouncycastle.operator.OperatorCreationException

### ISSUE THREAD

**Issue by jbalaz982** [bcgit/bc-java#495]
I created simple project where I included BC 1.61 during runtime I've got ClassNotFoundException 
when call build method on JceOpenSSLPKCS8EncryptorBuilder

**Comment by bcgit** [comment]
is bcpkix in the class path?

**Comment by jbalaz982** [comment]
These are dependencies in my pom.xml 
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.61</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.61</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>

after build I've got these two in lib folder therefore I think that it is.

**Comment by bcgit** [comment]
check the class path of the JVM

**Comment by bcgit** [comment]
Closing as no further contact.
