### ISSUE TITLE
Fixed RFC 5280 / RFC 3280 NameConstraint checking for RDNs

### ISSUE THREAD

**Issue by kaoh** [bcgit/bc-java#497]
The current implementation is comparing if the complete RDNs are matching between the permitted / excluded subtree and the certificate. This is not correct. The subtree must take into account which type of a RDN should be matched. It is legal to add not restricted RDN to the subject or alternative names.

See:  https://tools.ietf.org/html/rfc5280#section-7.1
The test specification from https://csrc.nist.gov/CSRC/media/Projects/PKI-Testing/documents/PKITS.pdf give a valid example in 6.1.5.382 Valid DN nameConstraints Test1 EE:

```
permittedSubtrees:
directoryName: "ou=permittedSubtree1, o=Test Certificates 2011,
c=US"
```

It is OK to have a CN not restricted by the permittedSubtrees:

```
subject: "cn=Valid DN nameConstraints EE Certificate Test1, ou=permittedSubtree1, o=Test
Certificates 2011, c=US"
```

I have created a pull request fixing this: https://github.com/bcgit/bc-java/pull/496 See there for other comments.

**Comment by bcgit** [comment]
Now fixed.
