### ISSUE TITLE
X509CertificateObject is deprecated

### ISSUE THREAD

**Issue by Tomtouta** [bcgit/bc-java#500]
Hello,

I’m currently changing version of bouncycastle from 1.38 to 1.61 inside an application.
The application use the X509CertificateObject at some point, but this class is noted as “deprecated” on the v1.61 of bouncycastle.
I checked into the documentation and found following line : “Do not use this class directly - either use org.bouncycastle.cert (bcpkix) or CertificateFactory.”
But org.bouncycastle.cert refer to a package so I did not found which class inside this package I need to use instead of X509CertificateObject.
Furthermore CertificateFactory is not present in bouncycastle.
Could you help me on this point or send me an example on how to replace this class ?

Kind regards,

**Comment by bcgit** [comment]
org.bouncycastle.cert is in the bcpkix-jdk15on-* jar files. CertificateFactory is actually part of the JCA.
