### ISSUE TITLE
Xof implementation of Blake2s

### ISSUE THREAD

**Issue by Gilthoniel** [bcgit/bc-java#501]
Hi,

In the scope of my work, I need a Java implementation of an eXtendable-Output Function using Blake2s and after some research it doesn't seem to be available anywhere. As we're already using bouncycastle, I was wondering if you guys would be open for such an implementation knowing that the Blake2sDigest would need to be changed in order to change the internal tree configuration?

I have the time to work on this, I only want to make sure it won't be refused ;).

Thanks!

**Comment by bcgit** [comment]
PR merged.
