### ISSUE TITLE
sm2 sm3 sign use OpenSSL EVP Verification signature failed

### ISSUE THREAD

**Issue by yazhouZhang** [bcgit/bc-java#511]
used sm2 sm3 sign，then  use OpenSSL EVP Verification signature failed.
Local Signature Verifies Signature Pass both of sm2 and OpenSSL。
userid 、key、Encrypted content is consistent.
sign 
<30460221 00d1e4b5 d7305bde 11195e11 2e192c45 ac21fb21 0e7f13cd 5d9acbba 1c4d3b1e 2c022100 e1bcf2de 3b1a0732 ae9be2c0 15596f02 55925b0d 6c7c2757 574cc15b 69efc356>
OpenSSL sign
<30450221 0097f07e c863072b 897e6f6b 8d36ebf0 f07f2538 e474f406 efeeeeb2 1accb6ec d2022046 9110e970 076eccc6 9ed2067e 10526181 2b513ebc 5fd52e69 402a5519 7783ba>

**Comment by xipki** [comment]
Hi Yazhou, for bettet analysis, I think you should provide more details:
  - BC version
  - Your java code to generate the signature
  - Your openssl code to verify the signature.

**Comment by bcgit** [comment]
Closed due to lack of information.
