### ISSUE TITLE
organizationIdentifier 2.5.4.97 not properly converted

### ISSUE THREAD

**Issue by ralfhauser** [bcgit/bc-java#516]
when doing
    cert.getIssuerX500Principal().toString();

[kellerAtGmxCh.crt.txt](https://github.com/bcgit/bc-java/files/3162469/kellerAtGmxCh.crt.txt)

**Comment by ralfhauser** [comment]
same when decrypting with transKeyId or after converting it to X509CertSelector

**Comment by bcgit** [comment]
The operational class here is actually an Oracle one,  javax.security.auth.x500.X500Principal. We have zero control over what it does.

You could define:

    public class RFC4519ExtendedStyle
        extends RFC4519Style
    {
        public static final RFC4519ExtendedStyle INSTANCE = new RFC4519ExtendedStyle();

        RFC4519ExtendedStyle()
        {
            defaultSymbols.put(X509ObjectIdentifiers.id_at_organizationIdentifier, "organizationIdentifier");
        }
    }

and use:

        System.err.println(X500Name.getInstance(RFC4519ExtendedStyle.INSTANCE, cert.getIssuerX500Principal().getEncoded()));

to get the desired effect.
