### ISSUE TITLE
Memory Usage of CMSSignedDataParser

### ISSUE THREAD

**Issue by mibollma** [bcgit/bc-java#517]
I noticed that the memory usage for the sample code at https://www.bouncycastle.org/docs/pkixdocs1.5on/org/bouncycastle/cms/CMSSignedDataParser.html increased significantly over time.
With 1.52 it needs 5mb to run, with 1.60 9mb and with 1.61 10mb (e.g. running the sample code in a VM with -Xmx).

Does anyone know the reason for this increase or a way to reduce the memory usage of the streaming API?

**Comment by bcgit** [comment]
Sounds a bit odd. Do you have any further information on this, haven't really seen this here.

**Comment by mibollma** [comment]
I was just trying to minimize memory usage for an embedded device.
For that purpose I was running the streaming decryption within a JUnit test using -Xmx to see how low I can go with the same input data before receiving OutOfMemory exceptions.
That's how I observed a significant difference when switching between those 3 version.

**Comment by dghgit** [comment]
Inactive.
