### ISSUE TITLE
Support for hybrid certificates

### ISSUE THREAD

**Issue by ChrisSch1** [bcgit/bc-java#520]
Hi,

Is there a way to create a hybrid certificate in the current bouncy castle version? I checked the wiki and coudn't find any X.509 extension supporting this. Did I miss the extension (for example https://tools.ietf.org/id/draft-truskovsky-lamps-pq-hybrid-x509-00.html) in the wiki or is there no support implemented? If there is no support, do I have to implement a custom version or is there a better way to do this?

Thank you for your help,
Chris

**Comment by bcgit** [comment]
This RFC has lapsed, apparently there is a significant IPR issue with it.

There are two similar proposals, https://datatracker.ietf.org/doc/draft-pala-composite-crypto/ and https://datatracker.ietf.org/doc/draft-ounsworth-pq-composite-sigs/ , that are IPR free. We've been advised to keep a watch on those.

We currently also support a local extension LinkedCertificate (see org.bouncycastle.asn1.bc) which can be used for this purpose in some cases.

**Comment by aloopkin** [comment]
Hello,

Sorry to post on a closed ticket, but my understanding is that this draft has been released as a standard by ITU/ISO
https://www.itu.int/rec/T-REC-X.509-201910-I 

On top of that, i'm not really sure that the composite approach is fully backwards compatible, unlike this standard... So what about this IPR issues?

Thanks,
Alexandre

PS: In other news (might be not the right place to ask), OIDs are available for Dilithium and Kyber:
https://datatracker.ietf.org/doc/draft-ietf-lamps-dilithium-certificates/
https://datatracker.ietf.org/doc/draft-ietf-lamps-kyber-certificates/
And precisions are available regarding SPHINCS+:
https://datatracker.ietf.org/doc/draft-ietf-lamps-cms-sphincs-plus/
Just to check if all this will be part of 1.73 or if it's for later?
