### ISSUE TITLE
Is there official JDK11 support for Bouncy castle?

### ISSUE THREAD

**Issue by Shanky2304** [bcgit/bc-java#524]
Perhaps a naive question. However, I couldn't find a JDK11 compatible official download or maven repo entry for Bouncy Castle but I read some mentions in other issues here.

Is there a JDK11 compatible version on the way?

**Comment by bcgit** [comment]
Strictly speaking, in most respects 1.61 will work with Java 11. 1.62 is now appearing on 
https://www.bouncycastle.org/latest_releases.html
and should deal with the remaining issues we have found in Java 11.
