### ISSUE TITLE
Problem verifying a certificate

### ISSUE THREAD

**Issue by rgala** [bcgit/bc-java#527]
I have a problem with certificate verification. The certificate looks OK. I can verify it using JRE native mechanisms, like this one:

	@Test
	public void isSignedBy() throws Exception {
		
		String cIssuer = "MIIGijCCBHKgAwIBAgIUfISQyDPXmKeE2/tYh2gjP2679H8wDQYJKoZIhvcNAQENBQAwbzELMAkGA1UEBhMCUEwxHTAbBgNVBAoMFE5hcm9kb3d5IEJhbmsgUG9sc2tpMSYwJAYDVQQDDB1OYXJvZG93ZSBDZW50cnVtIENlcnR5ZmlrYWNqaTEZMBcGA1UEYQwQVkFUUEwtNTI1MDAwODE5ODAeFw0xNzAzMTUxMDE3MzRaFw0yODAzMTUyMzU5NTlaMGUxCzAJBgNVBAYTAlBMMSEwHwYDVQQKDBhBc3NlY28gRGF0YSBTeXN0ZW1zIFMuQS4xGDAWBgNVBAMMD0NlcnR1bSBRQ0EgMjAxNzEZMBcGA1UEYQwQVkFUUEwtNTE3MDM1OTQ1ODCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKqhIng0CRIPhoofahIMMQOBeWmoSdBNs/7a8DjAtBmpD/MD0X2KMFHBJeVMFkA+o9k2rdbHzSR295YKzDPqEniGMhNUyYND999PMcuSH1wN/R3OM6asTugCxLVKiCNdHrZ9MUjOLG9JJOr+NzPbk2h9SZZa3fBwUkfWKJt4rWPn71DQ/swRdrC7UqCm0gDBqq2jSv42lfNxK7trySf/zxC7GnAtfgF8msF5F52O0DooY9lkPENpnGBotytq38oP9TkvQbh8aNV2nj34HyiXciIErF8gNthuIdArvedU7vL1ZQxRNfVie8V/ziJmphbC5CcYXzPUPjG2sxQjYVivs4o+ooSh2bdzuN0+B2utW2vqGgkOhla8ExYPmjoXvErlYjWcXJlv8kXi4pwKALALc7sB8olWCtT6/QnvC906s3wQOjgslEU+TsWSyq48u2hhkjl/ukiS/lEmHsWnoDF96j8Hv5bq+otA3OdR+PNh19fY94w/wCVp2FDXw/hwSarnaNNMlouMW5361gPuYuiVm2QuUUfgvTNOzwP0ia902mxU38E+hyQsUcbzYl/JN8V7ymZE3Jo1A7sle8OLAYAf7KOJL2EYBuM+mnZrL1AqnzuHamgL41gMphRcyl77/z09ATVryP9jTZIxC5oR21wqItHduL17AKusFnu44RV+Y28ZAgMBAAGjggEmMIIBIjAPBgNVHRMBAf8EBTADAQH/MIGsBgNVHSMEgaQwgaGAFCmzyMTfo4f4ZgUSWP1GKriYDXmHoXOkcTBvMQswCQYDVQQGEwJQTDEdMBsGA1UECgwUTmFyb2Rvd3kgQmFuayBQb2xza2kxJjAkBgNVBAMMHU5hcm9kb3dlIENlbnRydW0gQ2VydHlmaWthY2ppMRkwFwYDVQRhDBBWQVRQTC01MjUwMDA4MTk4ghRA+PeKsONkEFaRyNngLPjBxkAKRjAxBgNVHSABAf8EJzAlMCMGBFUdIAAwGzAZBggrBgEFBQcCARYNd3d3Lm5jY2VydC5wbDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFCfx2E5gUGi2Yf5oGyhsbeQLcwlNMA0GCSqGSIb3DQEBDQUAA4ICAQC47g9Dyycy+6JsnGsSJfE4kbo6Q72YB5zwIA8wqlwz9eZko6qmH5SoDjmuCXswGe3WCnErRL8bZ6XD/tkR6HBc4CbxOJCMbD0KcIWXgIuumEQP/mn8UIGPYsqtDufDc47pqPTHntHWvMh4JL8NiIyKNNve7xuYVjm78YiK2KGDABcsKN2ZWeCsgn7qsSmGuMOwe382eNoZZI8brkJ9UizkIIx/Hw1XVXfQ9om8k30Q4ue693mMFHjeEH0ZJdOGyUxNJI6OcgjthOpL0ca6BZsom1Gye6HnkHqCTI0qHiuLMvFsIjr2OpPNHOeLoh5LCZVa5ll/zPzw5UZxckyy+lSky8RPNl0FngzBAwbvB6Zw+E61gotFQnBtw1XEJQumR3rrLzECMsrv59ezuORFTUJpZ5MOc97pnnALkF8oFdiFspu8y/W57HmpP/8vCjtuXT2/aBJtOHTHBWjQ/hyPALzp+zZQn7GcZ9DdQBQrXM10X2Vuazh0U71KLuAAZ6Vh92qitfz16oENWTYm0gGHdrpP+Zu1yS+3HV6qzWCPuHtK9mz7fY5gFSWv7uT0KKnShYx5zfqy9uRL5hoXEy5/uBjWAwHFXFZDitC56/DmqdMpZHHG+966JPvGWLf3Jc7u++D2g5Bd5+uxxsUYDsqikzBh0Jl2Fyqjrh51d6YrUuzp0g==";
		String cSigCert = "MIIImDCCBoCgAwIBAgIQA9RLKbSh3PJLtsVmOHzZZDANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJQTDEhMB8GA1UECgwYQXNzZWNvIERhdGEgU3lzdGVtcyBTLkEuMRgwFgYDVQQDDA9DZXJ0dW0gUUNBIDIwMTcxGTAXBgNVBGEMEFZBVFBMLTUxNzAzNTk0NTgwHhcNMTgwOTEzMTQ1NDE4WhcNMjAwOTEyMTQ1NDE4WjCCATUxLTArBgNVBAMMJE1BUklVU1ogTUFMSU5PV1NLSTsgS29tb3JuaWsgU8SFZG93eTEQMA4GA1UEKgwHTUFSSVVTWjETMBEGA1UEBAwKTUFMSU5PV1NLSTEaMBgGA1UEBRMRUE5PUEwtNzIwNTE0MDIzMTUxGTAXBgNVBGETEFZBVFBMLTg4ODEyMDU2ODUxIDAeBgNVBAoMF0tyYWpvd2EgUmFkYSBLb21vcm5pY3phMTMwJQYDVQQJDB5Qb2xza2llaiBPcmdhbml6YWNqaSBXb2pza293ZWowCgYDVQQJDAMyMUExDzANBgNVBBEMBjg3LTgwMDEUMBIGA1UEBwwLV8WCb2PFgmF3ZWsxGzAZBgNVBAgMEmt1amF3c2tvLXBvbW9yc2tpZTELMAkGA1UEBhMCUEwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCRRnpvBYrkSZOEZTVIkXshYvPfW3C4e1QnMFqmU2BybhWjnM2tNOlawkPg7GXiAPYS823nnbe6bJLWHpBrGSm8gTy2JatOpNyFJY6XypBYggvGp62vKea9bszFAR6lkuxVtL3WJcZxxpQCrz+dMv/j3B8JEnmf0x44WJNAkN4PNY9pCyqWmgXoQsKoj9E8EyLn6gXatiAswlNbYmagIq7qJntV5Fq6KMy2pN6HVEBav7pc/wdrXh67IazLh1sU12DZMr4jRZil1Lv4hkfk+wpw/3CWPQ1b3V2JIMuMXxJExKorqclqNQjYm87dEBJ8gMluxE8oRN+EU/htencneoD9AgMBAAGjggNwMIIDbDAMBgNVHRMBAf8EAjAAMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9xY2EuY3JsLmNlcnR1bS5wbC9xY2FfMjAxNy5jcmwwcgYIKwYBBQUHAQEEZjBkMCwGCCsGAQUFBzABhiBodHRwOi8vcWNhLTIwMTcucW9jc3AtY2VydHVtLmNvbTA0BggrBgEFBQcwAoYoaHR0cDovL3JlcG9zaXRvcnkuY2VydHVtLnBsL3FjYV8yMDE3LmNlcjAfBgNVHSMEGDAWgBQn8dhOYFBotmH+aBsobG3kC3MJTTAdBgNVHQ4EFgQU/aleNYAwikqmrfd5KEExzP6sBUwwDgYDVR0PAQH/BAQDAgbAMIIBewYDVR0gBIIBcjCCAW4wCQYHBACL7EABAjCCAV8GDCqEaAGG9ncCBAEMATCCAU0wLQYIKwYBBQUHAgEWIWh0dHA6Ly93d3cuY2VydHVtLnBsL3JlcG96eXRvcml1bTCCARoGCCsGAQUFBwICMIIBDDAfFhhBc3NlY28gRGF0YSBTeXN0ZW1zIFMuQS4wAwIBAQyB6ENlcnR1bSBRdWFsaWZpZWQgQ2VydGlmaWNhdGUgUG9saWN5IGZvciBQaHlzaWNhbCBhbmQgTmF0dXJhbCBQZXJzb25zIHdpdGggU2VjdXJlIFNpZ25hdHVyZSBDcmVhdGlvbiBEZXZpY2UgKFNTQ0QpLiBNb3JlIGRldGFpbGVkIGluZm9ybWF0aW9uIGNhbiBiZSBmb3VuZCBpbiB0aGUgQ2VydGlmaWNhdGUgUG9saWN5IDEuMy42LjEuNC4xLjM4NjAuMS4yLjEwNC4xLjAgb24gaHR0cDovL3d3dy5jZXJ0dW0uZXUwgcIGCCsGAQUFBwEDBIG1MIGyMAgGBgQAjkYBATAIBgYEAI5GAQQwgYYGBgQAjkYBBTB8MDwWNmh0dHBzOi8vcmVwb3NpdG9yeS5jZXJ0dW0ucGwvUERTL0NlcnR1bV9RQ0EtUERTX0VOLnBkZhMCZW4wPBY2aHR0cHM6Ly9yZXBvc2l0b3J5LmNlcnR1bS5wbC9QRFMvQ2VydHVtX1FDQS1QRFNfUEwucGRmEwJwbDATBgYEAI5GAQYwCQYHBACORgEGATAcBgNVHQkEFTATMBEGA1UEDDEKDAhLb21vcm5pazANBgkqhkiG9w0BAQsFAAOCAgEAnT+jVCDCboJeKo2h0Yr/pQLyZzRF3+7iQQDi5tZI+Vd8FSzgIBC3w+u/gfhXl7Q0thdpyiLFJI/ngoLhBpUMkJM/67h8Y/uLgR+oX1Z/9YnWuzgCOi5bmyT3lkRFcogsRFbvLdXpn1B1p9qUkB81cecz33cmdWUuMc0s5jqz+tl+bAsx0yBt2GZQ3SvznHI/lCzzst3d7aNQ23IXG8UqQl0Zq5VdqQv5LCIdvoPLGvCDSWFwY3QyKCXWZQfFRwtjiazqi+U9Al13Uqot1ZhOIN8cj2d2KlUY+0bf188z1YLZkmWiNC+khRmmTqXKAYwAEc35gKcekqqA0y01xhkgiXBEV1IhoTeLbKlw7qnTTcNGKJ3SqO2rJE5L6TQhDL5UQkYnbLbK2c3nuObaTBcq6apkbwmXv04fSOQRub5zb4bXne07OLG+PmGxQLVD3CZ9QiPe2o1ePxmgAIMaPwr3yVsRLJ4urnHHncQSlkQFZArWPUbsJ/lkRPWKmCIYUJuqkwuHDPabu0OjDom39FQucr/8P7ghRe7xAmbGwfjUPMW63lIF9KHEGPnKw/EgglqOmgb/6bIRdsHtuNTk/lwc+FomuNMtu3Omrvn9FAmt1/B67+04rDRLateqcGuv9o/0cPxhsFKxgm7Q+1WTzt/1W9kF7q8E9v7XZshnHZHfplA=";
		
		CertificateFactory cf = CertificateFactory.getInstance("X.509");
		Certificate issuer = cf.generateCertificate(new ByteArrayInputStream(Base64.getDecoder().decode(cIssuer)));
		Certificate sigCert = cf.generateCertificate(new ByteArrayInputStream(Base64.getDecoder().decode(cSigCert)));
		sigCert.verify(issuer.getPublicKey());
		
	}
	

but when I use the BouncyCastle, I get the following error:

> java.security.SignatureException: certificate does not verify with supplied key

I debugged the code and it fails in this fragment of engineVerify method in DigestSignatureSpi class:

        if (sig.length == expected.length)
        {
            return Arrays.constantTimeAreEqual(sig, expected);
        }

Here is the code to reproduce:

	@Test
	public void isSignedBy() throws Exception {
		
		String cIssuer = "MIIGijCCBHKgAwIBAgIUfISQyDPXmKeE2/tYh2gjP2679H8wDQYJKoZIhvcNAQENBQAwbzELMAkGA1UEBhMCUEwxHTAbBgNVBAoMFE5hcm9kb3d5IEJhbmsgUG9sc2tpMSYwJAYDVQQDDB1OYXJvZG93ZSBDZW50cnVtIENlcnR5ZmlrYWNqaTEZMBcGA1UEYQwQVkFUUEwtNTI1MDAwODE5ODAeFw0xNzAzMTUxMDE3MzRaFw0yODAzMTUyMzU5NTlaMGUxCzAJBgNVBAYTAlBMMSEwHwYDVQQKDBhBc3NlY28gRGF0YSBTeXN0ZW1zIFMuQS4xGDAWBgNVBAMMD0NlcnR1bSBRQ0EgMjAxNzEZMBcGA1UEYQwQVkFUUEwtNTE3MDM1OTQ1ODCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKqhIng0CRIPhoofahIMMQOBeWmoSdBNs/7a8DjAtBmpD/MD0X2KMFHBJeVMFkA+o9k2rdbHzSR295YKzDPqEniGMhNUyYND999PMcuSH1wN/R3OM6asTugCxLVKiCNdHrZ9MUjOLG9JJOr+NzPbk2h9SZZa3fBwUkfWKJt4rWPn71DQ/swRdrC7UqCm0gDBqq2jSv42lfNxK7trySf/zxC7GnAtfgF8msF5F52O0DooY9lkPENpnGBotytq38oP9TkvQbh8aNV2nj34HyiXciIErF8gNthuIdArvedU7vL1ZQxRNfVie8V/ziJmphbC5CcYXzPUPjG2sxQjYVivs4o+ooSh2bdzuN0+B2utW2vqGgkOhla8ExYPmjoXvErlYjWcXJlv8kXi4pwKALALc7sB8olWCtT6/QnvC906s3wQOjgslEU+TsWSyq48u2hhkjl/ukiS/lEmHsWnoDF96j8Hv5bq+otA3OdR+PNh19fY94w/wCVp2FDXw/hwSarnaNNMlouMW5361gPuYuiVm2QuUUfgvTNOzwP0ia902mxU38E+hyQsUcbzYl/JN8V7ymZE3Jo1A7sle8OLAYAf7KOJL2EYBuM+mnZrL1AqnzuHamgL41gMphRcyl77/z09ATVryP9jTZIxC5oR21wqItHduL17AKusFnu44RV+Y28ZAgMBAAGjggEmMIIBIjAPBgNVHRMBAf8EBTADAQH/MIGsBgNVHSMEgaQwgaGAFCmzyMTfo4f4ZgUSWP1GKriYDXmHoXOkcTBvMQswCQYDVQQGEwJQTDEdMBsGA1UECgwUTmFyb2Rvd3kgQmFuayBQb2xza2kxJjAkBgNVBAMMHU5hcm9kb3dlIENlbnRydW0gQ2VydHlmaWthY2ppMRkwFwYDVQRhDBBWQVRQTC01MjUwMDA4MTk4ghRA+PeKsONkEFaRyNngLPjBxkAKRjAxBgNVHSABAf8EJzAlMCMGBFUdIAAwGzAZBggrBgEFBQcCARYNd3d3Lm5jY2VydC5wbDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFCfx2E5gUGi2Yf5oGyhsbeQLcwlNMA0GCSqGSIb3DQEBDQUAA4ICAQC47g9Dyycy+6JsnGsSJfE4kbo6Q72YB5zwIA8wqlwz9eZko6qmH5SoDjmuCXswGe3WCnErRL8bZ6XD/tkR6HBc4CbxOJCMbD0KcIWXgIuumEQP/mn8UIGPYsqtDufDc47pqPTHntHWvMh4JL8NiIyKNNve7xuYVjm78YiK2KGDABcsKN2ZWeCsgn7qsSmGuMOwe382eNoZZI8brkJ9UizkIIx/Hw1XVXfQ9om8k30Q4ue693mMFHjeEH0ZJdOGyUxNJI6OcgjthOpL0ca6BZsom1Gye6HnkHqCTI0qHiuLMvFsIjr2OpPNHOeLoh5LCZVa5ll/zPzw5UZxckyy+lSky8RPNl0FngzBAwbvB6Zw+E61gotFQnBtw1XEJQumR3rrLzECMsrv59ezuORFTUJpZ5MOc97pnnALkF8oFdiFspu8y/W57HmpP/8vCjtuXT2/aBJtOHTHBWjQ/hyPALzp+zZQn7GcZ9DdQBQrXM10X2Vuazh0U71KLuAAZ6Vh92qitfz16oENWTYm0gGHdrpP+Zu1yS+3HV6qzWCPuHtK9mz7fY5gFSWv7uT0KKnShYx5zfqy9uRL5hoXEy5/uBjWAwHFXFZDitC56/DmqdMpZHHG+966JPvGWLf3Jc7u++D2g5Bd5+uxxsUYDsqikzBh0Jl2Fyqjrh51d6YrUuzp0g==";
		String cSigCert = "MIIImDCCBoCgAwIBAgIQA9RLKbSh3PJLtsVmOHzZZDANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJQTDEhMB8GA1UECgwYQXNzZWNvIERhdGEgU3lzdGVtcyBTLkEuMRgwFgYDVQQDDA9DZXJ0dW0gUUNBIDIwMTcxGTAXBgNVBGEMEFZBVFBMLTUxNzAzNTk0NTgwHhcNMTgwOTEzMTQ1NDE4WhcNMjAwOTEyMTQ1NDE4WjCCATUxLTArBgNVBAMMJE1BUklVU1ogTUFMSU5PV1NLSTsgS29tb3JuaWsgU8SFZG93eTEQMA4GA1UEKgwHTUFSSVVTWjETMBEGA1UEBAwKTUFMSU5PV1NLSTEaMBgGA1UEBRMRUE5PUEwtNzIwNTE0MDIzMTUxGTAXBgNVBGETEFZBVFBMLTg4ODEyMDU2ODUxIDAeBgNVBAoMF0tyYWpvd2EgUmFkYSBLb21vcm5pY3phMTMwJQYDVQQJDB5Qb2xza2llaiBPcmdhbml6YWNqaSBXb2pza293ZWowCgYDVQQJDAMyMUExDzANBgNVBBEMBjg3LTgwMDEUMBIGA1UEBwwLV8WCb2PFgmF3ZWsxGzAZBgNVBAgMEmt1amF3c2tvLXBvbW9yc2tpZTELMAkGA1UEBhMCUEwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCRRnpvBYrkSZOEZTVIkXshYvPfW3C4e1QnMFqmU2BybhWjnM2tNOlawkPg7GXiAPYS823nnbe6bJLWHpBrGSm8gTy2JatOpNyFJY6XypBYggvGp62vKea9bszFAR6lkuxVtL3WJcZxxpQCrz+dMv/j3B8JEnmf0x44WJNAkN4PNY9pCyqWmgXoQsKoj9E8EyLn6gXatiAswlNbYmagIq7qJntV5Fq6KMy2pN6HVEBav7pc/wdrXh67IazLh1sU12DZMr4jRZil1Lv4hkfk+wpw/3CWPQ1b3V2JIMuMXxJExKorqclqNQjYm87dEBJ8gMluxE8oRN+EU/htencneoD9AgMBAAGjggNwMIIDbDAMBgNVHRMBAf8EAjAAMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9xY2EuY3JsLmNlcnR1bS5wbC9xY2FfMjAxNy5jcmwwcgYIKwYBBQUHAQEEZjBkMCwGCCsGAQUFBzABhiBodHRwOi8vcWNhLTIwMTcucW9jc3AtY2VydHVtLmNvbTA0BggrBgEFBQcwAoYoaHR0cDovL3JlcG9zaXRvcnkuY2VydHVtLnBsL3FjYV8yMDE3LmNlcjAfBgNVHSMEGDAWgBQn8dhOYFBotmH+aBsobG3kC3MJTTAdBgNVHQ4EFgQU/aleNYAwikqmrfd5KEExzP6sBUwwDgYDVR0PAQH/BAQDAgbAMIIBewYDVR0gBIIBcjCCAW4wCQYHBACL7EABAjCCAV8GDCqEaAGG9ncCBAEMATCCAU0wLQYIKwYBBQUHAgEWIWh0dHA6Ly93d3cuY2VydHVtLnBsL3JlcG96eXRvcml1bTCCARoGCCsGAQUFBwICMIIBDDAfFhhBc3NlY28gRGF0YSBTeXN0ZW1zIFMuQS4wAwIBAQyB6ENlcnR1bSBRdWFsaWZpZWQgQ2VydGlmaWNhdGUgUG9saWN5IGZvciBQaHlzaWNhbCBhbmQgTmF0dXJhbCBQZXJzb25zIHdpdGggU2VjdXJlIFNpZ25hdHVyZSBDcmVhdGlvbiBEZXZpY2UgKFNTQ0QpLiBNb3JlIGRldGFpbGVkIGluZm9ybWF0aW9uIGNhbiBiZSBmb3VuZCBpbiB0aGUgQ2VydGlmaWNhdGUgUG9saWN5IDEuMy42LjEuNC4xLjM4NjAuMS4yLjEwNC4xLjAgb24gaHR0cDovL3d3dy5jZXJ0dW0uZXUwgcIGCCsGAQUFBwEDBIG1MIGyMAgGBgQAjkYBATAIBgYEAI5GAQQwgYYGBgQAjkYBBTB8MDwWNmh0dHBzOi8vcmVwb3NpdG9yeS5jZXJ0dW0ucGwvUERTL0NlcnR1bV9RQ0EtUERTX0VOLnBkZhMCZW4wPBY2aHR0cHM6Ly9yZXBvc2l0b3J5LmNlcnR1bS5wbC9QRFMvQ2VydHVtX1FDQS1QRFNfUEwucGRmEwJwbDATBgYEAI5GAQYwCQYHBACORgEGATAcBgNVHQkEFTATMBEGA1UEDDEKDAhLb21vcm5pazANBgkqhkiG9w0BAQsFAAOCAgEAnT+jVCDCboJeKo2h0Yr/pQLyZzRF3+7iQQDi5tZI+Vd8FSzgIBC3w+u/gfhXl7Q0thdpyiLFJI/ngoLhBpUMkJM/67h8Y/uLgR+oX1Z/9YnWuzgCOi5bmyT3lkRFcogsRFbvLdXpn1B1p9qUkB81cecz33cmdWUuMc0s5jqz+tl+bAsx0yBt2GZQ3SvznHI/lCzzst3d7aNQ23IXG8UqQl0Zq5VdqQv5LCIdvoPLGvCDSWFwY3QyKCXWZQfFRwtjiazqi+U9Al13Uqot1ZhOIN8cj2d2KlUY+0bf188z1YLZkmWiNC+khRmmTqXKAYwAEc35gKcekqqA0y01xhkgiXBEV1IhoTeLbKlw7qnTTcNGKJ3SqO2rJE5L6TQhDL5UQkYnbLbK2c3nuObaTBcq6apkbwmXv04fSOQRub5zb4bXne07OLG+PmGxQLVD3CZ9QiPe2o1ePxmgAIMaPwr3yVsRLJ4urnHHncQSlkQFZArWPUbsJ/lkRPWKmCIYUJuqkwuHDPabu0OjDom39FQucr/8P7ghRe7xAmbGwfjUPMW63lIF9KHEGPnKw/EgglqOmgb/6bIRdsHtuNTk/lwc+FomuNMtu3Omrvn9FAmt1/B67+04rDRLateqcGuv9o/0cPxhsFKxgm7Q+1WTzt/1W9kF7q8E9v7XZshnHZHfplA=";
		Security.addProvider(new BouncyCastleProvider());
		CertificateFactory cf = CertificateFactory.getInstance("X.509", BouncyCastleProvider.PROVIDER_NAME);
		Certificate issuer = cf.generateCertificate(new ByteArrayInputStream(Base64.getDecoder().decode(cIssuer)));
		Certificate sigCert = cf.generateCertificate(new ByteArrayInputStream(Base64.getDecoder().decode(cSigCert)));

		sigCert.verify(issuer.getPublicKey());
		
	}

**Comment by bcgit** [comment]
The certificate signature is invalid. We have no idea why the standard JRE accepts it.

The multi-valued RDN

        Set
            Sequence
                ObjectIdentifier(2.5.4.9)
                UTF8String(Polskiej Organizacji Wojskowej) 
            Sequence
                ObjectIdentifier(2.5.4.9)
                UTF8String(21A) 

Is not being DER encoded for the signature calclation. The ordering is wrong, as a DER encoded entity it should encode as:

            Sequence
                ObjectIdentifier(2.5.4.9)
                UTF8String(21A) 
            Sequence
                ObjectIdentifier(2.5.4.9)
                UTF8String(Polskiej Organizacji Wojskowej)
