### ISSUE TITLE
DSTUMacs fail to auto-reset

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#529]
The DSTU7564Mac and DSTU7624Mac implementations do not call reset() as part of doFinal(), leaving the two MACs as one shot implementations. In addition reset() is not called as part of init(), so that a second identical call to init() will change the MAC state instead of preserving it.

`   /**
     * Run Tests.
     * @param pArgs arguments
     */
    public static void main(final String[] pArgs) {
        TestDSTUreset(new DSTU7564Mac(512));
        TestDSTUreset(new DSTU7624Mac(128, 128));
    }

    /**
     * Test DSTUreset.
     * @param pMac the mac
     */
    private static void TestDSTUreset(final Mac pMac) {
        /* Define message and key */
        final byte[] myMessage = "1234567890123456".getBytes();
        final byte[] myKey = "A123456789B12345".getBytes();
        
        /* Define buffers */
        final int myOutSize = pMac.getMacSize();
        final byte[] myFirst = new byte[myOutSize];
        final byte[] mySecond = new byte[myOutSize];
        
        /* Run the Mac twice without reInitialising */
        pMac.init(new KeyParameter(myKey));
        pMac.update(myMessage, 0, myMessage.length);
        pMac.doFinal(myFirst, 0);
        pMac.update(myMessage, 0, myMessage.length);
        pMac.doFinal(mySecond, 0);
        if (!Arrays.areEqual(myFirst, mySecond)) {
            System.out.println(pMac.getAlgorithmName() + " did not reset after doFinal() properly");
        }

        /* Manually perform the reset */
        pMac.reset();
        
        /* Initialise the mac twice */
        pMac.init(new KeyParameter(myKey));
        pMac.init(new KeyParameter(myKey));
        pMac.update(myMessage, 0, myMessage.length);
        pMac.doFinal(mySecond, 0);
        if (!Arrays.areEqual(myFirst, mySecond)) {
            System.out.println(pMac.getAlgorithmName() + " did not re-init properly");
        }
    }
`

**Comment by bcgit** [comment]
I think you've just set a new record for us. Thanks, will get it fixed as soon as I've finished dealing with 1.62.

**Comment by bcgit** [comment]
Now fixed, will show up in 163b07 in a couple of days. Thanks for the report.
