### ISSUE TITLE
DSTU7564Mac throws exception for certain keyLengths

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#530]
An ArrayIndexOutOfBoundsException is thrown when DSTU7564Mac is initialised with a key that is a multiple of the underlying digest state size.

`    /**
     * Run Tests.
     * @param pArgs arguments
     */
    public static void main(final String[] pArgs) {
        TestDSTUkey(new DSTU7564Mac(512));
    }

    /**
     * Test DSTUreset.
     * @param pMac the mac
     */
    private static void TestDSTUkey(final Mac pMac) {
        /* Define message */
        final byte[] myMessage = "1234567890123456".getBytes();

        /* Determine underlying engine size */
        final int myEngineSize = pMac.getMacSize() == 32 ? 64 : 128;

        /* Define key (can be any multiple of engineSize) */
        final byte[] myKey = new byte[myEngineSize];

        /* Initialise Mac (will fail with ArrayIndexOutOfBoundsException) */
        pMac.init(new KeyParameter(myKey));
        final int myOutSize = pMac.getMacSize();
        final byte[] myOut = new byte[myOutSize];
        pMac.update(myMessage, 0, myMessage.length);
        pMac.doFinal(myOut, 0);
    }
`

**Comment by bcgit** [comment]
Thanks for the report. Turned out the pad length calculation dropped a block when the key size was aligned with the buffer. Now fixed and on https://www.bouncycastle.org/betas
