### ISSUE TITLE
cause=java.lang.NoSuchMethodError: org.bouncycastle.openpgp.PGPObjectFactory

### ISSUE THREAD

**Issue by rakshith32** [bcgit/bc-java#531]
Hi Team,

Please help I am facing below issue,

MFTException [threadName=JCA-work-instance:JMSAdapter-0, errorID=a1610c9b-512c-41ac-8463-ce0b709d26d4, errorDesc=MFT-4401_Exception encountered during execution of callout ArrisPGPDecrypt., cause=java.lang.**NoSuchMethodError**: org.bouncycastle.openpgp.**PGPObjectFactory**.<init>(Ljava/io/InputStream

Using Below jars
bcpg-jdk15on-150.jar
bcprov-jdk15on-150.jar

 JAVA_VERSION="1.8.0_121"

Please add comments ASAP, what might be wrong to face this issue?
Thanks & Regards,
Rakshith

**Comment by bcgit** [comment]
It's likely to be a class path problem - as in there's a different version of the bcpg jar somewhere on the class path.
