### ISSUE TITLE
Performance problems using BC 1.61

### ISSUE THREAD

**Issue by PythEsc** [bcgit/bc-java#532]
Hi,

I'm working on a project where we're developing some kind of TLS proxy that serves as a TLS endpoint and forwards the plaintext messages to a backend system. The private key cryptography is done within a HSM. For the public key operations we currently use Bouncycastle. 
For some use cases we expect up to 600 new connections per second, for each of which we have to perform a handshake. However, our benchmarks have shown that we do not reach this value by far (currently we are at about 90 handshakes/second). 
After analyzing the code using a profiler, we found that most of the time is spent inside Bouncycastle's JCA provider. For testing purposes we did the same benchmarks with the Sun provider and an OpenSSL JCA wrapper and got better results. With the Sun Provider we achieved about 150 handshakes/second and with the OpenSSL wrapper even 500.

During the analysis we noticed that the slowest parts of the handshake are the encoding/decoding of certificates in DER format and the chain validation or more precisely the signature checks.

Both the clients and the server use elliptic curves. The hot spot view of the profiler shows that most of the time is spent within the ECFieldElement class.

The total duration of a handshake where client and server run on the same machine is 477 ms with Bouncycastle, 184 ms with Sun, and 12 ms with the OpenSSL wrapper.

Is this difference to be expected? Are there published benchmarks regarding the performance of Bouncycastle? Is there anything I can do to improve performance, such as using certain settings?

Best regards,

Florian

**Comment by peterdettman** [comment]
No, that's not expected at all. e.g. on my laptop (2.6 GHz i7), running org.bouncycastle.jsse.provider.test.CipherSuitesTestSuite from the BCJSSE test suite currently performs (serially) 53 complete handshakes, including both client and server, with total execution time ~1.4s, including over 0.4s large overhead for the first handshake, reflecting costs of initialization of the providers and the test harness itself. That is around ~20ms average per additional handshake, with the DHE/DSS suites skewing that number higher; for the EC ones it is closer to 10ms.

It should be easy enough to clear up once we collect a bit of information:

1. From "TLS proxy" I assume you are mainly concerned about server performance.
2. Are you using the BCJSSE provider or just writing to the org.bouncycastle.tls API directly?
3. When you say "use elliptic curves" do you mean for both key agreement and signing? Perhaps it's easier to ask if you know what cipher suite is being negotiated.
4. Do you know which elliptic curve group is in use exactly (e.g. secp256r1, brainpoolP256r1, x25519, etc.) - for key agreement? for signing/verification?
5. Do your connections use client authentication? Is it also an EC signature?

We can probably read a lot of the details we need from a wireshark capture if you can provide one. Please also provide stack traces for the hot codepaths (certificate encoding/decoding and ECFieldElement).

BTW, ECFieldElement should only be hot in the profiler if the fallback BigInteger-based elliptic curve implementation is in use (which is very slow). We have custom implementations of most curves (excepting brainpool), but perhaps something about your configuration is not picking them up. Still, this alone can hardly explain 450ms excess.

For such a large discrepancy I would perhaps guess that providers are being repeatedly registered, or (depending on how you are using the TLS library) new instances of JcaTlsCrypto are being created for each handshake (one instance can be shared across all).

Finally, we have just released 1.62, so if you are able to update to that (at least in your test environment), please do so.

**Comment by PythEsc** [comment]
Thank you for the quick response. So here are the details:

> From "TLS proxy" I assume you are mainly concerned about server performance.

Correct

> Are you using the BCJSSE provider or just writing to the org.bouncycastle.tls API directly?

We are using the BCJSSE provider. Or even more precisely we use the constructor that receives a JcaTlsCryptoProvider object. We have created our own implementation that creates a customized JcaTlsCrypto object since we had to override e.g. the hasSignatureAndHashAlgorithm method.

> When you say "use elliptic curves" do you mean for both key agreement and signing? Perhaps it's easier to ask if you know what cipher suite is being negotiated.

Yes we are using elliptic curves for both. The allowed cipher suites are: 

- TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
- TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384

> Do you know which elliptic curve group is in use exactly (e.g. secp256r1, brainpoolP256r1, x25519, etc.) - for key agreement? for signing/verification?

The static keys are brainpoolP256r1. The ephemeral ones are most likely secp256r1 but brainpool must also be supported.

> Do your connections use client authentication? Is it also an EC signature?

Yes

> We can probably read a lot of the details we need from a wireshark capture if you can provide one. Please also provide stack traces for the hot codepaths (certificate encoding/decoding and ECFieldElement).

I am not at work until Tuesday but I will upload more information afterwards

> BTW, ECFieldElement should only be hot in the profiler if the fallback BigInteger-based elliptic curve implementation is in use (which is very slow). We have custom implementations of most curves (excepting brainpool), but perhaps something about your configuration is not picking them up.

You are correct that BigInteger was also between the top 5 hotspots. Unfortunately we have to use brainpool in the environment. Both, client and server, need to.

> For such a large discrepancy I would perhaps guess that providers are being repeatedly registered, or (depending on how you are using the TLS library) new instances of JcaTlsCrypto are being created for each handshake (one instance can be shared across all).

I will check that once I am back at work

> Finally, we have just released 1.62, so if you are able to update to that (at least in your test environment), please do so.

Awesome I will give it a try then

**Comment by peterdettman** [comment]
> > For such a large discrepancy I would perhaps guess that providers are being repeatedly registered, or (depending on how you are using the TLS library) new instances of JcaTlsCrypto are being created for each handshake (one instance can be shared across all).
> 
> I will check that once I am back at work

Since you are using BCJSSE, this should amount to ensuring that you are sharing one SSLContext instance.

**Comment by PythEsc** [comment]
Okay so today I found the time to run the profiler again and made some screenshots (for those of you that do not have yourkit profiler installed).

In the first view you can see how the time is spend within the _handleHandshakeMessage_ method:
![handshake_overview](https://user-images.githubusercontent.com/22145165/59341302-f0750880-8d07-11e9-94d2-1c890dbcea73.png)

I also made a screenshot of the hotspots within the _handleHandshakeMessage_  method:
![handshake_overview_hotspot](https://user-images.githubusercontent.com/22145165/59341403-0f739a80-8d08-11e9-8b69-6d9c17dce17d.png)

Since most of the time is spent within _receiveCertificateMessage_ I made another screenshot that focuses the named method:
![receiveCertificateMessage](https://user-images.githubusercontent.com/22145165/59341498-3df17580-8d08-11e9-8005-a468c1f8aa3f.png)

And then again another screenshot that focuses _PKIXCertPathValidatorSpi_:
![PKIXCertPathValidator](https://user-images.githubusercontent.com/22145165/59341561-624d5200-8d08-11e9-9e2d-5ed88744471f.png)

You can see that both time costly methods are calling _X509CertificateObject.checkSignature_. This is why I made two last screenshots focusing the _Signature.verify_ method. The first one shows the call-tree the second one the hotspots within Signature.verify:
![Signature verify](https://user-images.githubusercontent.com/22145165/59341725-a93b4780-8d08-11e9-90b0-734628873693.png)
![Signature verify_hotspot](https://user-images.githubusercontent.com/22145165/59341732-ab9da180-8d08-11e9-800f-36f68b8d4201.png)

Finally for those of you that can open the snapshot itself:
[TLS-Handshake.zip](https://github.com/bcgit/bc-java/files/3280762/TLS-Handshake.zip)

**Comment by peterdettman** [comment]
OK, thanks, it seems pretty clear it's our brainpool implementation slowing things down. Just to round out the data, could you zoom in on these two (both from the first screenshot):
    - TlsECDHEKeyExchange.generateServerKeyExchange
    - TlsServerProtocol.receiveClientKeyExchangeMessage

I just want to check whether those numbers are for brainpool also.

**Comment by PythEsc** [comment]
Yeah sure

**TlsECDHEKeyExchange.generateServerKeyExchange**:
Call tree
![generateServerKeyExchange](https://user-images.githubusercontent.com/22145165/59366012-d81de180-8d39-11e9-9cf1-0a3975b7d1e1.png)

Hotspots:
![generateServerKeyExchange_hotspot](https://user-images.githubusercontent.com/22145165/59366021-dce29580-8d39-11e9-8a45-2fedbd24f060.png)

**TlsServerProtocol.receiveClientKeyExchangeMessage**
Call tree
![receiveClientKeyExchangeMessage](https://user-images.githubusercontent.com/22145165/59366041-e8ce5780-8d39-11e9-9c5e-c98ec3989be8.png)

Hotspots:
![receiveClientKeyExchangeMessage_hotspot](https://user-images.githubusercontent.com/22145165/59366060-ef5ccf00-8d39-11e9-9ccc-6e1f16e08ec2.png)

**Comment by peterdettman** [comment]
Thanks, very helpful!

I note immediately that precomputation for the ECDHE key generation  (FixedPointUtil$1.precompute) is not being cached, so is being repeated each handshake, making it considerably slower. That would be affecting your client-side numbers too.

That's obviously a deficiency in BCJSSE and I think we'll look into fixing that first.

**Comment by PythEsc** [comment]
Okay, great, that's nice to hear. Unfortunately the KeyExchange is only a small part of the overall time. Will you take a look at the implementation for ECDSASigner? Because this is the class that accounts for 37% of the handshake time in my case.

I have attached another screenshot which shows the signature check in more detail focusing the _ECDSASigner_ class.

Call tree:
![ECDSASigner](https://user-images.githubusercontent.com/22145165/59378232-26d87500-8d54-11e9-845c-31c3b268f47b.png)

Hotspots:
![ECDSASigner_hotspots](https://user-images.githubusercontent.com/22145165/59378238-2b9d2900-8d54-11e9-9ae1-49296683ec4f.png)

**Comment by peterdettman** [comment]
That ECDSA verification is slow is primarily due to our brainpoolP256R1 implementation being slow (and my first impression of the caching thing is that it is also subtly related to the lack of custom curve implementations for brainpool).

Writing a custom curve is a serious piece of work, so we'll look at fixing smaller things first.

e.g. ECAlgorithms.sumOfTwoMultiplies can also be improved a little for the case (this case) where one of the points is the base point. That would also depend on the cacheing being correct first though.

BTW, ideas for workarounds:
- are your connections such that cacheing the certificate validation results for a minute or so could reasonably help?
- how long are the client cert chains (2 apparently?) and could you add any/all the intermediate CA certs to your trusted certs so that only one signature verification would be needed in the common case?

**Comment by PythEsc** [comment]
> Writing a custom curve is a serious piece of work, so we'll look at fixing smaller things first.

Okay I understand that. Any improvement is appreciated :)

> are your connections such that cacheing the certificate validation results for a minute or so could reasonably help?

In our benchmark that would make a huge difference since we are connecting from the same clients over and over again but in the production environment that is a rather artificial use case. It should not happen that one client is connecting over and over again.

> how long are the client cert chains (2 apparently?) and could you add any/all the intermediate CA certs to your trusted certs so that only one signature verification would be needed in the common case?

There are three certificates in total (rootca, subca and endpoint). We will think about such a mechanism to reduce the load. The system is dynamic and one can potentially add and remove certificates from our certificate store.

**Comment by peterdettman** [comment]
A new beta version 163b01 is available at https://downloads.bouncycastle.org/betas/ with some relevant performance improvements:
- it fixes the cacheing issue for ECDHE key generation, which should be considerably faster now.
- there's an ~4% improvement in all EC-base verification speeds from improved precomputation.

Both of these are generic fixes, not brainpool-specific. It would be appreciated if you could rerun your profiling to confirm the improvements.

**Comment by PythEsc** [comment]
Unfortunately I could not profile on the same machine so the total numbers may differ quite much but it is sufficient to see the new patch.

**handleHandshakeMessage**
Call tree:
![handshake_overview](https://user-images.githubusercontent.com/22145165/60268545-e862be80-98ec-11e9-8797-54d1c2f0e33b.png)

Hotspots:
![handshake_overview_hotspots](https://user-images.githubusercontent.com/22145165/60268583-fc0e2500-98ec-11e9-95ea-e14aaeb92375.png)

**generateServerKeyExchange**
Call tree:
![generateServerKeyExchange](https://user-images.githubusercontent.com/22145165/60268596-07615080-98ed-11e9-82e2-49a3a57a7c8f.png)

Hotspots:
![generateServerKeyExchange_hotspot](https://user-images.githubusercontent.com/22145165/60268600-0af4d780-98ed-11e9-9c4e-b082afbe8e0d.png)



> it fixes the cacheing issue for ECDHE key generation, which should be considerably faster now.

The FixedPointUtil.precompute method is definitely much faster now. Its average time went down from 13ms to 0.1

> there's an ~4% improvement in all EC-base verification speeds from improved precomputation.

I think it is not possible to see this difference because the machine is a different one and we are not able to see this 4% change

**Comment by peterdettman** [comment]
Thanks for the feedback. There is now a new beta version 163b02 available at https://downloads.bouncycastle.org/betas/ with a further performance improvement: after an EC public key is used for several verifications, we switch to a faster algorithm (which requires a longer precomputation and is thus not worthwhile for one-off verifications).

For this to kick in, it's necessary to use the same X509Certificate instance each time, as should naturally be the case for your trust anchor certificates, but you should double-check that. The new algorithm is around 55% faster, so if each handshake has 3 verifications, 1 of which is from a trust anchor, you could expect an overall reduction in verification costs of 10-12%.

If you could again profile to confirm this in your system, it would be appreciated.

A further improvement might be to "intern" certificates from the client-sent chain via a small cache, so that especially the intermediate CA verifications could benefit from this too.

This improvement is independent of the curve involved (although the 55% was measured for brainpoolP256r1). I have separately started work on a custom brainpoolP256r1 implementation, and initial measurements suggest it can be ~5x faster than the current one. I can't offer a timeline for that just yet though.

**Comment by PythEsc** [comment]
Hey @peterdettman many thanks for all the improvements. I have a question regarding your built-in improvement: Is the improvement a PKIXCertPathValidator thing? So does the improvement only occur when using a Bouncycastle instance of a CertPathValidator? Or is the optimization within the Signature.verify method and valid outside the PKIXCertPathValidator?

> If you could again profile to confirm this in your system, it would be appreciated.

I will try to do some benchmarks asap

> This improvement is independent of the curve involved (although the 55% was measured for brainpoolP256r1). I have separately started work on a custom brainpoolP256r1 implementation, and initial measurements suggest it can be ~5x faster than the current one. I can't offer a timeline for that just yet though.

That would be huge and definitely very much appreciated. If the result was actually 5x faster, Bouncycastle would be at least on par with the Sun implementation (maybe even a bit faster).

**Comment by PythEsc** [comment]
Another (somehow offtopic) question: Is it normal that the ASN1 parsing is also quite slow? ASN1Object.getEncoded is even among the hotspots at number 3 within the handleHandshakeMessage subtree

**Comment by peterdettman** [comment]
> Hey @peterdettman many thanks for all the improvements.

You're welcome, and thank you for bringing the poor performance to our attention. There are certainly other users who will be glad of the resulting improvements, which have wider application.

> Is the improvement a PKIXCertPathValidator thing? So does the improvement only occur when using a Bouncycastle instance of a CertPathValidator? Or is the optimization within the Signature.verify method and valid outside the PKIXCertPathValidator?

The optimization applies as long as you are using BC for the ECDSA verification with a retained instance of the PublicKey. In these latest BC beta releases, our X509Certificate implementation now caches the getPublicKey return value; other X.509 providers may or may not cache that instance.

We made no special adjustments to our CertPath APIs; they benefit automatically when the X509Certificate instances they are given are stable, by using X509Certificate.getPublicKey as the verification key. Probably other CertPath APIs would work the same, although they are normally bundled in an X.509 provider, so the caveat about the X509Certificate caching may apply.

Of course the certificates in the client chain itself have just been read off the network, so for the optimization to possibly apply there they would have to be interned to a cache in order to "recognize" them.

**Comment by PythEsc** [comment]
> The optimization applies as long as you are using BC for the ECDSA verification with a retained instance of the PublicKey. In these latest BC beta releases, our X509Certificate implementation now caches the getPublicKey return value; other X.509 providers may or may not cache that instance.

Okay that fully answers my question. Since we are using the BC-provider within our CertificateFactory this part should be working.

> We made no special adjustments to our CertPath APIs; they benefit automatically when the X509Certificate instances they are given are stable, by using X509Certificate.getPublicKey as the verification key. Probably other CertPath APIs would work the same, although they are normally bundled in an X.509 provider, so the caveat about the X509Certificate caching may apply.

We are currently using Sun for certificate path validation but bouncycastle for most/all other public key operations.

> Of course the certificates in the client chain itself have just been read off the network, so for the optimization to possibly apply there they would have to be interned to a cache in order to "recognize" them.

We are already caching the root and intermediate certificates. So these should be the same instances

**Comment by peterdettman** [comment]
There is a new beta version 163b08 available at https://downloads.bouncycastle.org/betas/ with further improvements to ECDSA verification performance.

Furthermore, we noted your observations regarding ASN.1 performance and did some testing ourselves, finding several significant issues. So this beta also includes a wide variety of improvements to our X.509 certificates and the underlying ASN.1 code.

The results for the BCJSSE TrustManager (using the BC CertPathBuilder internally) are quite dramatic, but it's not clear how much of that will carry over to your setup.

In any event, it would be great if you could profile against the new beta version, and pay attention both to the verification numbers and also the ASN.1 code.

**Comment by PythEsc** [comment]
That sounds really promising :) Unfortunately I'm not in the office at the moment and can't test anything. But I will get back to you as soon as I have results.

**Comment by peterdettman** [comment]
@PythEsc Bump.

**Comment by PythEsc** [comment]
Hi @peterdettman I'm sorry I didn't answer earlier, but we have quite a lot to do at the moment and I haven't been able to profile the new versions yet. I hope to find the time soon to give you more information. However, I did a short test of BC 1.62 vs 1.63b12 using my local laptop. Depending on the scenario, the throughput increased between 15 and 50%. These numbers could still change on the benchmark machines and unfortunately I don't have any profiling possibilities here either.

**Comment by peterdettman** [comment]
No problem. We will hopefully be releasing 1.63 around the first week of September, so if you can get us one more round of profiler data there's a small window to fix any obvious remaining hotspots (brainpool curve itself will have to wait still).

**Comment by PythEsc** [comment]
Hi @peterdettman ,

Unfortunately I didn't make it before the release. But now I was able to test again and used the final 1.63 version. On average our TLS benchmark shows an improvement of ~35% between 1.62 and 1.63. It is noticeable that "receiveClientKeyExchangeMessage" now takes up the most time

**handleHandshakeMessage**

call tree
![handleHandshakeMessage](https://user-images.githubusercontent.com/22145165/66034295-482ebe00-e509-11e9-9f4c-c52d05fd0896.png)

hotspots
![handleHandshakeMessage_hotspots](https://user-images.githubusercontent.com/22145165/66034305-4c5adb80-e509-11e9-830b-351591a0570f.png)

**ECDSASigner.verifySignature**

call tree
![ECDSASigner-verifySignature](https://user-images.githubusercontent.com/22145165/66034333-5977ca80-e509-11e9-8002-9aed62d9e603.png)

hotspots
![ECDSASigner-verifySignature_hotspots](https://user-images.githubusercontent.com/22145165/66034341-5da3e800-e509-11e9-9c19-09b407f355ac.png)
