### ISSUE TITLE
Bug in using Parm-Z algorithm parameter fo GOST28147 engine

### ISSUE THREAD

**Issue by im-scooter** [bcgit/bc-java#533]
Bug in using Parm-Z algorithm parameter fo GOST28147 engine.
There is is bug in org.bouncycastle.jcajce.provider.symmetric.GOST28147.BaseAlgParams#getSBoxOID(byte[] sBox) method.
Call GOST28147Engine.getSBoxName(sBox) returns name of sBox in uppercase ("PARAM-Z").
Subsequent call org.bouncycastle.jcajce.provider.symmetric.GOST28147.BaseAlgParams#getSBoxOID(String name) can not find ASN1ObjectIdentificator for paramteer with name "PARAM-Z", because java.lang.Map org.bouncycastle.jcajce.provider.symmetric.GOST28147#nameMappings  contains key "Param-Z"

How reproduce:
`
Provider provider = new BouncyCastleProvider();
AlgorithmParameterGenerator apg = AlgorithmParameterGenerator.getInstance("GOST28147", provider);

GOST28147ParameterSpec parameterSpec = new GOST28147ParameterSpec("Param-Z");

apg.init(parameterSpec);

AlgorithmParameters gostZAlgorithmParameters = apg.generateParameters();
`

**Comment by bcgit** [comment]
Patch merged. Thanks!
