### ISSUE TITLE
Create attribute certificate

### ISSUE THREAD

**Issue by vitormc1** [bcgit/bc-java#535]
Hello!
I buy an A3 digital certificate (usb token) to my company.
Now i want to generate attributes certificates to my employers, signing with my A3 certificate.

Im trying to start using the above code, but im really stucked, any one can to give some ideias?

```java
AlgorithmIdentifier sigAlgId = new DefaultSignatureAlgorithmIdentifierFinder().find("SHA256withRSA");

AlgorithmIdentifier digAlgId = new DefaultDigestAlgorithmIdentifierFinder().find(sigAlgId);
ContentSigner authority = null;

// create a bouncy castle content signer convert using our existing private key
authority = new BcRSAContentSignerBuilder(sigAlgId, digAlgId).build(PrivateKeyFactory.createKey(issuerPrivateKey.getEncoded()));
// second, prepare the attribute certificate
// which is expected to be a UUID  like this: 33766a63-5c55-4461-8a84-5936577df450
AttributeCertificateHolder holder = new AttributeCertificateHolder(subjectName);
AttributeCertificateIssuer issuer = new AttributeCertificateIssuer(issuerName);
X509v2AttributeCertificateBuilder builder = new X509v2AttributeCertificateBuilder(holder, issuer, serialNumber, notBefore, notAfter);
			
for (Attribute attribute : attributes) {
    builder.addAttribute(attribute.oid, attribute.value);
}
			
// fourth, sign the attribute certificate
if (authority != null) {
    X509AttributeCertificateHolder cert;
    cert = builder.build(authority);
    //X509AttributeCertificate.valueOf(cert.getEncoded());
    return cert.getEncoded();
}
```

My final goal is generate an attribute certificate like this:

[Decoded attribute certificate](https://lapo.it/asn1js/#MIIDqzCCApMCAQEwdKByMG2kazBpMQswCQYDVQQGEwJCUjETMBEGA1UECgwKSUNQLUJyYXNpbDEmMCQGA1UECwwdVU5JQU8gTkFDSU9OQUwgRE9TIEVTVFVEQU5URVMxHTAbBgNVBAMMFFJlamFuaSBNb3JlaXJhIENvc3RhAgEBoIGaMIGXpIGUMIGRMQswCQYDVQQGEwJCUjETMBEGA1UECgwKSUNQLUJyYXNpbDEOMAwGA1UECwwFVkFMSUQxGzAZBgNVBAsMElBlc3NvYSBKdXJpZGljYSBBMzEYMBYGA1UECwwPQUMgVkFMSUQgQlJBU0lMMSYwJAYDVQQDDB1VTklBTyBOQUNJT05BTCBET1MgRVNUVURBTlRFUzANBgkqhkiG9w0BAQUFAAIEAJD49DAiGA8yMDE5MDQwODAyNTkzM1oYDzIwMjAwMzMxMjM1OTU5WjCBzTBGBgVgTAEKATE9EzsyNTA4MTk2OTMyOTE1NDIwMjk3MDAwMjExNTA1NjEyMjcyMDAwMDAwMDAwMDAwMDAwICAgICAgICAgIDB2BgVgTAEKAjFtE2tGYWN1bGRhZGUgQW5oYW5ndWVyYSBkZSBBbmFwb2xpcyAgICAgICAgU1VQRVJJT1IgICAgICAgUHNpY29sb2dpYSAgICAgICAgICAgICAgICAgICAgQW5hcG9saXMgICAgICAgICAgICBHTzALBgVgTAEEAzECEwAwcjAuBgNVHR8EJzAloSOGIWh0dHBzOi8vdW5lLmRuZS52Yy92MS9jcmwvdW5lLmNybDAdBgNVHSMEFoAUTh7XeOLYwzAdmmVDQAkhh2tVzPswIQYIKwYBBQUHAQEEFTATBggrBgEFBQcwAgQHhgVIVFRQUzANBgkqhkiG9w0BAQUFAAOCAQEABzXx-wy1JoKkY3KlrvsRIfx19TJmL4QYY2llaAFV42LsAfY1CQBzuzT1kTvnFfip3uYy0SprczK51KziclZsjDZhNipp2aiD9HOyc0s31FA-_YYzNyGNAVGybgY1oNlybcgCXxtq9zpCJykLmT2WVLlkSYy_6gUKj450YIV0Gm63uRtfRGWd9pM3Z_BQNeIIeTCQO6XnQhIjFluzoZvcZXuWZjvIdllxWSuiKtwUZkQxRREHciIPww_G7iXRTis7w4B4SOX10kWIMibspf7kullj3Exwq6FBvu27uqUnnEioOccS0WjBzVIi05Do6WIvwOwixOc720nn_HC9YYJ3Iw)

**Comment by dghgit** [comment]
It's a bit late, but you probably need to use the PKCS#11 provider, or some other provider, with your USB token as it's unlikely to make the key available in an encoded format.
