### ISSUE TITLE
Gradle build problem

### ISSUE THREAD

**Issue by Hartland-3** [bcgit/bc-java#538]
getting below error when attempting to build project with Gradle. 

gradle build15+

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/hartland/Documents/bcPlay/bc-java/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'bc-java'.
> Failed to apply plugin [id 'net.saliman.cobertura']
   > Could not create an instance of type net.saliman.gradle.plugin.cobertura.CoberturaExtension.
      > Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by mweissbacher** [comment]
For anybody else arriving here: this can be fixed by removing all references (in all gradle build files) to cobertura. It'll build fine, it's just less coverage output.
