### ISSUE TITLE
Bouncy Castle and Symantec Command Line Tool

### ISSUE THREAD

**Issue by vigneshwarant** [bcgit/bc-java#545]
I'm encrypting and signing a String using Bouncy Castle JAVA code. My recipient is using Symantec PGP Command Line tool to decrypt. The recipient is expecting to see encrypted token by running decrypt PGP command in one step, but the recipient needs to run the command twice to get the String, as the first decrypt process only validates the signature. Is it a expected behavior ? Can I encrypt and sign in one step using Bouncy Castle ?

**Comment by dghgit** [comment]
Encrypt and sign are two steps in PGP. Usually the signed message is contained in the encrypted one though - if you swap the order you might find the tool decrypts and verifies in one step.
