### ISSUE TITLE
GOST3412_2015 CTR mode cannot be initialised via JCA

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#546]
When instantiating the GOST3412_2015 cipher in CTR mode via JCA, there is no valid length of IV that can be supplied. The G3413CTRBlockCipher implementation requires an IV length of half the block size (64 bits), but the JCA wrapper insists on an IV of 128 bits. Both lengths of IV are rejected.

` 
   /**
     * Note the provider.
     */
    private static final Provider BCPROV = new BouncyCastleProvider();

    /**
     * Run Tests.
     * @param pArgs arguments
     */
    public static void main(final String[] pArgs) {
        TestG3413CTRInit("GOST3412-2015", 8);
        TestG3413CTRInit("GOST3412-2015", 16);
    }

    /**
     * Test G3413CTR Init.
     * @param pAlgorithm the algorithm
     * @param pIVLen the ivLength
     */
    private static void TestG3413CTRInit(final String pAlgorithm,
                                         final int pIVLen) {
        /* Catch Exceptions */
        try {
            /* Create the generator and generate a key */
            KeyGenerator myGenerator = KeyGenerator.getInstance(pAlgorithm, BCPROV);

            /* Initialise the generator */
            SecureRandom myRandom = new SecureRandom();
            myGenerator.init(256, myRandom);
            SecretKey myKey = myGenerator.generateKey();

            /* Create IV */
            byte[] myIV = new byte[pIVLen];
            myRandom.nextBytes(myIV);

            /* Create a G3413CTR Cipher */
            Cipher myCipher = Cipher.getInstance(pAlgorithm + "/CTR/NoPadding", BCPROV);
            myCipher.init(Cipher.ENCRYPT_MODE, myKey, new IvParameterSpec(myIV));

            System.out.println(pAlgorithm + " G3413CTR JCA init Bug fixed");

            /* Catch general exceptions */
        } catch (NoSuchPaddingException
                | NoSuchAlgorithmException e) {
            System.out.println("General exception");
            e.printStackTrace();
        } catch (InvalidAlgorithmParameterException e) {
            System.out.println(pAlgorithm + " G3413CTR IV " + pIVLen + " rejected by JCA Wrapper");
        } catch (InvalidKeyException e) {
            System.out.println(pAlgorithm + " G3413CTR IV " + pIVLen + " rejected by CipherMode");
        }
    }
`

**Comment by bcgit** [comment]
Thanks for the report. Now fixed. Will show up in 163 beta 7.
