### ISSUE TITLE
Excessive memory allocation in Argon2

### ISSUE THREAD

**Issue by haumacher** [bcgit/bc-java#550]
The Argon2 password hashing algorithm is designed to require a configurable amout of minimum memory to perform the hash computation. This is reasonable to make it hard to use specialized hardware for brute-force attacs against stolen password hashes. 

Unfortunately, the Argon2 implementation in BC uses a factor of 10 more than the required minimum memory to actually perform the computation. This effectively prevents users from configuring a reasonable amout of memory for their hash computations, because login checks would exhaust all system resources otherwise.

Even if the unneccessary memory allocations are only temporary they at least trigger unwanted GC operations during hash computations and have the risk of loosing cache data in memory-sensitive caches.

Please consider applying the fix available in #541.

**Comment by bcgit** [comment]
We can see the point. The fix has now been applied. It should show in 163b08 and later. You'll be able to find that version on https://www.bouncycastle.org/betas in a couple of days.
