### ISSUE TITLE
ChaCha20-Poly1305 Cipher

### ISSUE THREAD

**Issue by kevinherron** [bcgit/bc-java#554]
I see there's already implementations of ChaCha20 and Poly1305, as well as an implementation of `TlsAEADCipherImpl` (`BcChaCha20Poly1305`) that brings them together in the TLS module, but there doesn't seem to be a Cipher instance available.

I know support for this is available in JDK 11 but I need access to it on JDK 8 via BC provider for now.

Is this something that is planned or would you be open to a PR implementing it?

**Comment by peterdettman** [comment]
It's somewhat in progress, via bc-csharp (https://github.com/bcgit/bc-csharp/pull/209), which we would subsequently port over to Java, but if you want to PR a Java version directly it would speed things along.

**Comment by kevinherron** [comment]
Yes, I'm aware of this PR :)

Liam and I are part of the same group trying to get support for this into
BC.

It seems the implementation of a CipherSpi in bc-java is a bit more
involved than what Liam submitted there, but maybe I'm overthinking it.

I primarily wanted to make sure I'm not stepping on any toes here.

**Comment by peterdettman** [comment]
Not stepping on any toes. We'd eventually get around to this ourselves, but help is always appreciated.

Indeed, in Java the provider wrappers (CipherSpi) are an extra layer compared to the core implementation that Liam is working on. In Java the usual organisation is to have the "lightweight" implementation - basically the core implementation according to BC APIs, then a thin (well, as possible) CipherSpi wrapper (and associated key factories/generators). In any case, we're happy to get PRs.

**Comment by peterdettman** [comment]
We did implement this back in Sep '19, as Cipher.CHACHA20-POLY1305, with misc. aliases and supporting generators, parameters etc.
