### ISSUE TITLE
serialize and deserialize PGPPublickey and PGPPrivateKey

### ISSUE THREAD

**Issue by ashok003** [bcgit/bc-java#555]
what is the best way to serialize and deserialize PGPPublic and PGPPrivate Key in BC-PGP Java?
I want to transmit theses keys over the net

Thanks

**Comment by bcgit** [comment]
It depends a bit on what you want to do at the other end. The classes you actually want to serialize are PGPSecretKey and PGPPublicKey - both objects have getEncoded() methods. Sometime's it's better to manage PGP keys as rings though, so you might want to look at encoding the KeyRing objects instead.

**Comment by bcgit** [comment]
Closed as conversation ceased.
