### ISSUE TITLE
Is there a demo?

### ISSUE THREAD

**Issue by elton-wang-ch** [bcgit/bc-java#558]
dear
I want to use SM2 and RSA,but I dont konw how to use bouncycastle for my program.So,could you please provide SM2 and RSA demo code for encrypting and decrypting and adding signatures and verifying signatures？Or what way to get these demo code?

**Comment by bcgit** [comment]
You can find plenty of examples in the test code for the various APIs. There is also further documentation at: https://www.bouncycastle.org/documentation.html
