### ISSUE TITLE
BouncyCastle method "numberOfLeadingZeros" seems wrong or misleading

### ISSUE THREAD

**Issue by Xor-el** [bcgit/bc-java#560]
going through the newly implemented "numberOfLeadingZeros" method [here](https://github.com/bcgit/bc-java/blob/master/core/src/main/jdk1.4/org/bouncycastle/util/Integers.java#L5), I seem to have come across some discrepancies.

running a few tests confirm this, bouncycastle's version seem to give an answer that is always off by one.

you can confirm this from the sample codes in the links below

[C's numberOfLeadingZeros method](https://ideone.com/pZZKE0)
[Pascal's numberOfLeadingZeros method](https://ideone.com/yBGldp)
[Java's inbuilt numberOfLeadingZeros method](https://ideone.com/OoZvBm)
[Bouncy Castle's numberOfLeadingZeros method implementation takes from the link above](https://ideone.com/xiYT1R)

As we can see from the result, Bouncy Castle's output seems to be the only odd party out.

the fix is straightforward though, just replace [line 17](https://github.com/bcgit/bc-java/blob/master/core/src/main/jdk1.4/org/bouncycastle/util/Integers.java#L17) with this 
`   n -= i >>> 31;
    return n;
`

**Comment by peterdettman** [comment]
Thanks, we have patched both the j2me and jdk1.4 methods with your fix.
