### ISSUE TITLE
Cannot access qTESLA, EdDSA or XDH via JCA from Java9 module

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#563]
The new Asymmetric algorithms qTESLA, EdDSA and XDH that were introduced in 1.61 are not accessible from code running as a java9 module.

Running KeyPairGenerator.getInstance("QTESLA", "BCPQC")

results in the following Exception  

> java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: QTESLA, provider: BCPQC, class: org.bouncycastle.pqc.jcajce.provider.qtesla.KeyPairGeneratorSpi)
....
Caused by: java.lang.IllegalAccessException: class java.security.Provider (in module java.base) cannot access class org.bouncycastle.pqc.jcajce.provider.qtesla.KeyPairGeneratorSpi (in module org.bouncycastle.provider) because module org.bouncycastle.provider does not export org.bouncycastle.pqc.jcajce.provider.qtesla to module java.base
	
You need to at least **open** these packages to **java.base** if you do not wish to fully export them to everyone.

I have created a three file maven project which illustrates the issue

[issue.zip](https://github.com/bcgit/bc-java/files/3405818/issue.zip)

If you have difficulty running the project as a module, place the resulting jar plus the bc provider into a separate directory and invoke

> java --module-path {path_to_jars} -m jcatest

**Comment by bcgit** [comment]
I've been able to reproduce this. Sadly our regression build was using the classpath still, it seems that ignores the export issue. Oh dear. I'm putting together a new regression build now to make sure this is properly captured.

**Comment by bcgit** [comment]
Okay, that was surprisingly difficult... however try the artifacts on: https://www.bouncycastle.org/betas b09 or later and let me know how you go. Thanks.

**Comment by tonywasher** [comment]
I can confirm that the problem is fixed in 163b09

**Comment by bcgit** [comment]
Now closing. Have confirmed regression build now in place properly as well.
