### ISSUE TITLE
custom curve secp128r1 fails on encryption

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#566]
When I use ECElGamal encryption on the custom secp128r1 curve implementation it fails to encrypt/de-crypt a particular constructed point on the curve correctly. The operation is successful when I use the generic curve implementation.

I have built a generic Cipher along the lines of the article at [https://onlinelibrary.wiley.com/doi/pdf/10.1002/sec.1702](url). This advocates mapping a generic sequence of bytes onto the curve in a reversible fashion. I have modified it slightly to define padding bytes, and the mapping proceeds as follows

1. Let N be the number of bytes used to represent an X co-ordinate (secp128r1 = 16). 
2. Take the next N-2 bytes from the message. Suffix with a 0x00 byte and prefix with a 0x01 byte. For messages shorter than N-2, prefix with additional 0x00 bytes until an N-byte buffer is achieved.
3. Check whether this value of x is on the curve. If not, add one to the last byte and re-check. Repeat until a point is found on the curve or the final byte wraps.

Surprisingly enough, this algorithm works well for the majority of the defined curves. The only ones where a point fails to be found are the cv* curves that have a large cofactor. The use of the 0x01 prefix also ensures that the point is less than the N value of the curve.

The point that fails encryption is  X = 00...01FFFF01. The result of encryption followed by decryption for this point on the custom curve implementation, is fffffffe000000000000000001ffff00. The correct result is returned on the generic implementation 

Sample code is as follows

`public class Secp128 {
    /**
     * Max attempts to find a point on the curve.
     */
    private static final int MAXITERATIONS = 1 << Byte.SIZE;

    /**
     * The ECCurve.
     */
    private final ECCurve theCurve;

    /**
     * The Encryptor.
     */
    private final ECElGamalEncryptor theEncryptor;

    /**
     * The Decryptor.
     */
    private final ECElGamalDecryptor theDecryptor;

    /**
     * Main entry.
     * @param pArgs the arguments
     */
    public static void main(final String[] pArgs) {
        try {
            /* Run tests */
            new Secp128(false);
            new Secp128(true);
        } catch (InvalidCipherTextException e) {

        }
    }

    /**
     * Constructor.
     * @params useCustomCurve
     */
    private Secp128(final boolean useCustomCurve) throws InvalidCipherTextException {
        /* Create encryptor/decryptor */
        theEncryptor = new ECElGamalEncryptor();
        theDecryptor = new ECElGamalDecryptor();

        /* Create the generator */
        ECKeyPairGenerator myGenerator = new ECKeyPairGenerator();
        SecureRandom myRandom = new SecureRandom();
        String myCurve = "secp128r1";

        /* Lookup the parameters */
        final X9ECParameters x9 = useCustomCurve
                                  ? ECUtil.getNamedCurveByName(myCurve)
                                  : ECNamedCurveTable.getByName(myCurve);

        /* Initialise the generator */
        final ASN1ObjectIdentifier myOid = ECUtil.getNamedCurveOid(myCurve);
        ECNamedDomainParameters myDomain = new ECNamedDomainParameters(myOid, x9.getCurve(), x9.getG(), x9.getN(), x9.getH(), x9.getSeed());
        ECKeyGenerationParameters myParams = new ECKeyGenerationParameters(myDomain, myRandom);
        myGenerator.init(myParams);

        /* Create the key Pair */
        AsymmetricCipherKeyPair myPair = myGenerator.generateKeyPair();

        /* Initialise for encryption/decryption */
        final ParametersWithRandom myParms = new ParametersWithRandom(myPair.getPublic(), myRandom);
        theEncryptor.init(myParms);
        theDecryptor.init(myPair.getPrivate());

        /* Store the curve */
        theCurve = myDomain.getCurve();

        /* Build buffer to check */
        final byte[] myData = new byte[] { (byte) 0xFF, (byte) 0xFF };

        /* Create the point */
        final ECPoint myPoint = convertToECPoint(myData, 0, myData.length);

        /* Encrypt and decrypt the point */
        final ECPair myEncryptedPair =  theEncryptor.encrypt(myPoint);
        final ECPoint myResolvedPoint = theDecryptor.decrypt(myEncryptedPair);

        /* Check that the resolved point is correct */
        if (!myPoint.equals(myResolvedPoint)) {
            System.out.println("Failed " + useCustomCurve);
        }
    }

    /**
     * Obtain the length of the block.
     * @return the length of the block.
     */
    private int getBlockLength() {
        return (theCurve.getFieldSize() + Byte.SIZE - 1) / Byte.SIZE;
    }

    /**
     * Convert to ECPoint.
     * @param pInBuffer the input buffer
     * @param pInOff the input offset
     * @param pInLen the length of data to process
     * @return the ECPair
     * @throws InvalidCipherTextException on error
     */
    private ECPoint convertToECPoint(final byte[] pInBuffer,
                                     final int pInOff,
                                     final int pInLen) throws InvalidCipherTextException {
        /* Check length */
        final int myLen = getBlockLength();
        if (pInLen > myLen - 2
                || pInLen <= 0) {
            throw new IllegalArgumentException("Invalid input length");
        }
        if (pInBuffer.length - pInOff < pInLen) {
            throw new IllegalArgumentException("Invalid input buffer");
        }

        /* Create the work buffer and copy data in */
        final byte[] myX = new byte[myLen];

        /* Calculate the start position and place data and padding */
        final int myStart = myLen - pInLen - 1;
        System.arraycopy(pInBuffer, pInOff, myX, myStart, pInLen);
        myX[myStart - 1] = 1;

        /* Loop to obtain point on curve */
        for (int i = 0; i < MAXITERATIONS; i++) {
            /* Check to see whether the value is on the curve */
            final ECPoint myPoint = checkOnCurve(myX);

            /* If we have a valid point */
            if (myPoint != null) {
                return myPoint;
            }

            /* Increment the test value */
            myX[myLen - 1]++;
        }

        /* No possible value found */
        throw new InvalidCipherTextException("Unable to find point on curve");
    }

    /**
     * Check whether the point is on the curve.
     * @param pX the byte buffer representing X
     * @return the ECPoint if on curve, else null
     */
    private ECPoint checkOnCurve(final byte[] pX) {
        /* Protect against exceptions */
        try {
            /* Create a compressed point */
            final byte[] myCompressed = new byte[pX.length + 1];
            System.arraycopy(pX, 0, myCompressed, 1, pX.length);
            myCompressed[0] = 2;
            final ECPoint myPoint = theCurve.decodePoint(myCompressed);

            /* Check the point */
            return myPoint.isValid()
                   ? myPoint
                   : null;

            /* Handle invalid coding */
        } catch (IllegalArgumentException e) {
            return null;
        }
    }
}
`

**Comment by peterdettman** [comment]
Thanks for the report, Tony. We have identified and fixed the underlying bug in modular reduction for secp128r1 custom curve. We plan to release a new beta with the fix, hopefully in the next few days.

**Comment by peterdettman** [comment]
https://downloads.bouncycastle.org/betas/ now has version 163b11 with the fix.

**Comment by tonywasher** [comment]
I can confirm that this is fixed in 163b11. Thanks.
