### ISSUE TITLE
parameter "keysize" unused in org.bouncycastle.cms.bc.BcCMSContentEncryptorBuilder.CMSOutputEncryptor#CMSOutputEncryptor

### ISSUE THREAD

**Issue by MadMud** [bcgit/bc-java#568]
Hi,
this is a minor thing, bur there is a discrepacy between the JCE and Lighweight CMSOutput encryptors:
in lightweigt the keysize paarameter is ignored and size is taken from given OID while in jce (org.bouncycastle.cms.jcajce.JceCMSContentEncryptorBuilder.CMSOutputEncryptor#CMSOutputEncryptor) this behavior is present for negative values of keysize. 

Is there a usecase for setting the keysize to something not in keeping with the given algorithm?
If not I propose to remove the superfluous keysize parameter in lightweigtht.
Cheers,
Matthias

**Comment by dghgit** [comment]
Closed as usage now established in both.
