### ISSUE TITLE
PemReader throws StringIndexOutOfBoundsException when a line begins with five hyphens, BEGIN and a space but without five hyphens at the end

### ISSUE THREAD

**Issue by IIDAYosiaki** [bcgit/bc-java#569]
Hello, people.
PemReader seems to throw StringIndexOutOfBoundsException when it reads line like:
-----BEGIN 

It would be nice if it skips such lines.
I tried bcprov-jdk15on-152.jar and bcprov-jdk15on-162.jar.

**Comment by kevinherron** [comment]
Why should it try to handle such lines? The textual encoding is defined by RFC 7468: https://tools.ietf.org/html/rfc7468#page-8

**Comment by bcgit** [comment]
I think it's more that they should probably be ignored...

**Comment by IIDAYosiaki** [comment]
This could happen due to fixed buffer, network failure or file system full.
It would be nice if PemReader just returns null in such case.

**Comment by bcgit** [comment]
Headers are now checked more strictly, a situation like this will now just return null.
