### ISSUE TITLE
FIPS requirement for "bcprov"

### ISSUE THREAD

**Issue by pranavrao1** [bcgit/bc-java#572]
Hello,

I have really enjoyed using bouncy castle over the years.
We are upgrading our products to be FIPS compliant.

I noticed you do not have a version of FIPS for "bcprov" library here: http://central.maven.org/maven2/org/bouncycastle/ does anyone know why?

Sincerely,
Pranav Rao

**Comment by bcgit** [comment]
It's there, it's just called bc-fips.
