### ISSUE TITLE
Use Cryptopp Library elgamal encrypt text, but bouncycastle can't decrypt?

### ISSUE THREAD

**Issue by cjnwan** [bcgit/bc-java#582]
[Detail](https://github.com/weidai11/cryptopp/issues/876)

**Comment by bcgit** [comment]
When you say can't decrypt, what do you mean? The BC ElGamal implementation is also used by our PGP implementation. You might be facing an issue with block encoding though, ElGamal is like RSA you need to use a block encoding mechanism if you want it to work.

**Comment by bcgit** [comment]
Closing due to lack of information.
