### ISSUE TITLE
Must we use brainpool256 or brainpool192 when generating an AES key from brainpool curves?

### ISSUE THREAD

**Issue by conor-hen-123** [bcgit/bc-java#583]
When using the following code to generate an ECC key pair using the brainpool group of curves, only the brainpool192 and brainpool256 curves work when generating an AES key. If I use a higher curve I have to adjust the size of the key.

````
public static KeyPair generateECKeys() {
ECNamedCurveParameterSpec parameterSpec = ECNamedCurveTable.getParameterSpec("brainpoolpt1");
            
KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("ECDH", new org.bouncycastle.jce.provider.BouncyCastleProvider());
keyPairGenerator.initialize(parameterSpec);
KeyPair keyPair = keyPairGenerator.generateKeyPair();
return keyPair;
} 

public static SecretKey generateSharedSecret(PrivateKey privateKey, PublicKey publicKey) {
            
KeyAgreement keyAgreement = KeyAgreement.getInstance("ECDH", new org.bouncycastle.jce.provider.BouncyCastleProvider());
keyAgreement.init(privateKey);
keyAgreement.doPhase(publicKey, true);
SecretKey key =  keyAgreement.generateSecret("AES/CBC/NoPadding");
return key;
}
```

**Comment by bcgit** [comment]
Try generateSecret("AES") - the provider will only truncate the secret if it recognises the algorithm- AES in the above is an algorithm, "CBC/NoPadding" is really how it is being applied. You can also use the object identifier as in:
NISTObjectIdentifiers.id_aes256_CBC.getId()

If you give generateSecret() a name it doesn't know about it will assume you know what you are doing.

Note that when you're using ECDH in this primitive fashion if the curve can't create a key that's big enough you will get an exception. If you need to be sure of the output size, use a DH algorithm that supports a KDF.
