### ISSUE TITLE
Add Curve25519/Curve448 based ECIES

### ISSUE THREAD

**Issue by pod-adr** [bcgit/bc-java#585]
Hi,

It is possible to use ECIES utilizing some standard curves such as secp or brainpool. 

Let there be a random secp521r1 keypair. One can utilize its public part to encrypt data (with ECIES) and its private part to sign them (omitting the fact if it is a good practice or not). 

It would be useful to be able to do the same utilizing the 25519/448 curves.

Best regards,
Adrian

**Comment by dghgit** [comment]
This was done in github #966
