### ISSUE TITLE
Get Key failed: password has been cleared (PKCS12, SunJSSE compat)

### ISSUE THREAD

**Issue by stanio** [bcgit/bc-java#586]
Using Java 8, tried with BC versions 1.61, 1.62 and 1.63 – there appears some incompatibility between the `SunJSSE` and `BC` implementations which causes a `KeyStore.getKey(alias, password)` to fail when the key store is loaded with `SunJSSE` provider but then Bouncy Castle is the first available provider.  I'm reproducing it using the following minimal test:

```java
//package ;

import java.io.InputStream;
import java.security.Key;
import java.security.KeyStore;
import java.security.Security;
import java.util.Collections;

import org.bouncycastle.jce.provider.BouncyCastleProvider;

public class KeyStoreTest {

    public static void main(String[] args) throws Exception {
        //Security.insertProviderAt(new BouncyCastleProvider(), 1);

        KeyStore keyStore = KeyStore.getInstance("PKCS12");
        System.out.println(keyStore.getProvider().getName()
                           + ": " + keyStore.getProvider().getInfo());

        ClassLoader cl = Thread.currentThread().getContextClassLoader();
        try (InputStream in = cl.getResourceAsStream("npoba.p12")) {
            keyStore.load(in, "password".toCharArray());
        }

        Security.insertProviderAt(new BouncyCastleProvider(), 1);

        for (String keyAlias : Collections.list(keyStore.aliases())) {
            Key key = keyStore.getKey(keyAlias, "password".toCharArray());
            System.out.println(keyAlias + ": "
                    + key.getAlgorithm() + " / " + key.getClass().getName());
        }
        System.out.println("Done.");
    }

}
```

currently results in:

```
Exception in thread "main" java.security.UnrecoverableKeyException: Get Key failed: password has been cleared
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:435)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at KeyStoreTest.main(KeyStoreTest.java:28)
Caused by: java.lang.IllegalStateException: password has been cleared
	at javax.crypto.spec.PBEKeySpec.getPassword(PBEKeySpec.java:197)
	at org.bouncycastle.jcajce.provider.symmetric.util.BCPBEKey.getEncoded(BCPBEKey.java:88)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineInit(BaseBlockCipher.java:572)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineInit(BaseBlockCipher.java:974)
	at javax.crypto.Cipher.implInit(Cipher.java:809)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:863)
	at javax.crypto.Cipher.init(Cipher.java:1538)
	at javax.crypto.Cipher.init(Cipher.java:1469)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:370)
	... 2 more
```

[npoba.p12.zip](https://github.com/bcgit/bc-java/files/3595814/npoba.p12.zip)

**Comment by stanio** [comment]
For reference, the given example works o.k. using BC 1.52.

**Comment by stanio** [comment]
Complete example: [bcprov-test.zip](https://github.com/bcgit/bc-java/files/3599611/bcprov-test.zip)

One could try it with: `mvn exec:java -Dexec.mainClass=KeyStoreTest`

**Comment by stanio** [comment]
> For reference, the given example works o.k. using BC 1.52.

Using BC 1.53 to 1.60 (incl.) I'm getting the following:

```
Exception in thread "main" java.security.UnrecoverableKeyException: Get Key failed: pad block corrupted
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:435)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at KeyStoreTest.main(KeyStoreTest.java:28)
Caused by: javax.crypto.BadPaddingException: pad block corrupted
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(BaseBlockCipher.java:1246)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1081)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:371)
	... 2 more
```

**Comment by stanio** [comment]
[`sun.security.pkcs12.PKCS12KeyStore`](https://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/69c4f673b33e/src/share/classes/sun/security/pkcs12/PKCS12KeyStore.java#l821):

```java
    /*
     * Generate PBE key
     */
    private SecretKey getPBEKey(char[] password) throws IOException
    {
        SecretKey skey = null;

        try {
            PBEKeySpec keySpec = new PBEKeySpec(password);
            SecretKeyFactory skFac = SecretKeyFactory.getInstance("PBE");
            skey = skFac.generateSecret(keySpec);
            keySpec.clearPassword();
        } catch (Exception e) {
           throw new IOException("getSecretKey failed: " +
                                 e.getMessage(), e);
        }
        return skey;
    }
```

Looks like it expects the generated `SecretKey` should not try to access the password from the `KeySpec` further (see the `keySpec.clearPassword()` statement above):

[`com.sun.crypto.provider.PBEKeyFactory.engineGenerateSecret(KeySpec)`](https://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/69c4f673b33e/src/share/classes/com/sun/crypto/provider/PBEKeyFactory.java#l219) : [`com.sun.crypto.provider.PBEKey`](https://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/69c4f673b33e/src/share/classes/com/sun/crypto/provider/PBEKey.java#l55) – doesn't hold reference to the given `KeySpec`

This is in contrast with BC [`PBEKeyFactory.engineGenerateSecret(KeySpec)`](/bcgit/bc-java/blob/738dfc013232/prov/src/main/jdk1.3/org/bouncycastle/jce/provider/JCESecretKeyFactory.java#L141) : [`BCPBEKey`](/bcgit/bc-java/blob/738dfc013232/prov/src/main/java/org/bouncycastle/jcajce/provider/symmetric/util/BCPBEKey.java) – holds reference to the given `KeySpec` and later fails when trying to access the password from `getEncoded()`

For some reason with BC 1.52 `SecretKeyFactory.getInstance("PBE")` returns a `com.sun.crypto.provider.PBEKeyFactory` instance even when BC installed as first provider.

**Comment by bcgit** [comment]
PBE doesn't exist in BC 1.52. It's since been added.

**Comment by farrault** [comment]
We hit quite the same incompatibility than KeyStoreTest2 in our project 
It also occurs when a "JKS" keystore load a pkcs12 file, as the jdk now use a DualFormatJKS implementation to fallback from jks to pkcs12 (see KeyStoreTest3 below)

The JDK stacktrace doesn't show that BouncyCastle is involved
and as this code correctly worked before BouncyCastle was added to our classpath (some other framework add the BouncyCastle provider to the JDK unwantedly)
it was not straigthforward to find the link.

So here a slightly different test case : 
```java
import java.io.InputStream;
import java.security.KeyStore;
import java.security.Security;
import java.util.Collections;

import org.bouncycastle.jce.provider.BouncyCastleProvider;

public class KeyStoreTest3 {

    public static void main(String[] args) throws Exception {
        Security.insertProviderAt(new BouncyCastleProvider(), 1);

//        KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType()); 
        KeyStore keyStore = KeyStore.getInstance("jks"); // default is JKS 

        ClassLoader cl = Thread.currentThread().getContextClassLoader();
        try (InputStream in = cl.getResourceAsStream("npoba.p12")) {
            keyStore.load(in, "password".toCharArray());
        }
        System.out.println("Keys: " + Collections.list(keyStore.aliases()));
        System.out.println("Done.");
    }

}
```

Which shows a slightly different stacktrace :
```java
Exception in thread "main" java.io.IOException: keystore password was incorrect
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2059)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:238)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at bouncyCastle.KeyStoreTest3.main(KeyStoreTest3.java:18)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: java.lang.IllegalStateException: password has been cleared
	... 5 more
```

**Comment by stanio** [comment]
> code correctly worked before BouncyCastle was added to our classpath (some other framework add the BouncyCastle provider to the JDK unwantedly)

In our case the issue prevents us from upgrading Bouncy Castle for addressing security issues in past (our current) version.

**Comment by victorbucutea** [comment]
any luck in this regard ? I'm having the same issue with jdk-11.0.3+7

**Comment by stanio** [comment]
No luck so far.  We're just stuck at it.

**Comment by bcgit** [comment]
It took a while, but I think I've found it. Try 165b03 at https://www.bouncycastle.org/betas

**Comment by stanio** [comment]
Using the 165b03 beta all 3 cases given here pass successfully, using both JDK 1.8 and 11.  Thank you very much!

**Comment by mouse07410** [comment]
@bcgit when are you planning to push that code to GitHub (aka - here)?  I thought this master was supposed to track the *current* source, which should be by now at least 165b03 level?

**Comment by bcgit** [comment]
It should appear in the next couple of hours. One of the compatibility builds for earlier JVMs failed, I think we've just fixed that though. Build is running at the moment, assuming it works things should publish.

@stanio thanks for confirmation. I'll mark this one as closed.

**Comment by stanio** [comment]
@bcgit Could you estimate when 1.65 release may be expected?

**Comment by bcgit** [comment]
We're hoping to have it out in the next few weeks.

**Comment by mahaviswana** [comment]
@bcgit  When will we get the release?
