### ISSUE TITLE
Blake2sx XOF not available

### ISSUE THREAD

**Issue by Xor-el** [bcgit/bc-java#591]
According to [here](http://bouncy-castle.1462172.n4.nabble.com/Bouncy-Castle-Crypto-Provider-Package-version-1-62-now-available-td4659639.html) , it says **Blake2sx XOF** has been added to the lightweight API but I can't seem to find it after multiple searches.
Can someone please point me to the source file or where it can be found.
I am thinking someone forgot to make the push but I may be wrong.

Thanks.

**Comment by peterdettman** [comment]
Blake2sx appears to be a typo. I assume you are looking for `org.bouncycastle.crypto.digests.Blake2xsDigest`.

**Comment by Xor-el** [comment]
Thanks, exactly what I was looking for.  :100:
