### ISSUE TITLE
Java OpenSSHPrivateKeyUtil Failing With Ed25519 and OpenSSH

### ISSUE THREAD

**Issue by jamespowenjr** [bcgit/bc-java#592]
I've been trying to programatically generate OpenSSH host keys in my Java application, but I'm unable to get a working Ed25519 key in the OpenSSH v1 key format. Here's my current attempt:

    import org.bouncycastle.crypto.params.Ed25519PrivateKeyParameters;
    import org.bouncycastle.crypto.util.OpenSSHPrivateKeyUtil;

    import java.util.Base64;

    ...

    Ed25519PrivateKeyParamters keyParamters = new Ed25519PrivateKeyParamters(new SecureRandom());
    byte[] encodedPrivateKey = OpenSSHPrivateKeyUtil.encodePrivateKey(keyParameters);
    System.out.println(Base64.getEncoder().encodeToString(encodedPrivateKey));

The output looks like what I'm expecting (similar to the results of an ssh-keygen -t ed25519), but when I put the results into /etc/ssh/sshd_host_ed25519_key (and the corresponding public key into /etc/ssh/sshd_host_ed25519_key.pub), I get the following error from sshd in /var/log/messages:

    auth.err: error: Could not load host key: /etc/ssh/sshd_host_ed25519_key

I'm using the following:

 - centos   7.6
 - java     1.8.0_212
 - openssh  7.4p1-16.e17
 - bouncycastle 1.63

Any help would be appreciated, thanks.

**Comment by peterdettman** [comment]
This was a bug in OpenSSHPrivateKeyUtil.encodePrivateKey. It was failing to add padding to the private key block in the case where it wasn't block-aligned (for some reason unencrypted data is treated as having a block size of 8).

This has now been fixed (and tested that the keys are acceptable to OpenSSH). It may be a few days before we can get a beta version out, but hopefully you can confirm the fix then.

**Comment by peterdettman** [comment]
BTW, in case you're unaware, there are classes in org.bouncycastle.util.io.pem that are helpful for producing PEM-format files:

```
    byte[] content = OpenSSHPrivateKeyUtil.encodePrivateKey(privKey);
    PemObject o = new PemObject("OPENSSH PRIVATE KEY", content);
    PemWriter w = new PemWriter(new OutputStreamWriter(new FileOutputStream(privFile)));
    w.writeObject(o);
    w.close();

```

**Comment by jamespowenjr** [comment]
Peter, thanks for the quick response. I didn't know about the PemWriter. That'll definitely save me some time. I'll be on the lookout for the next release so I can test it out. Thanks.
In the meantime is there anywhere I can see the fix? I checked the file history here (https://github.com/bcgit/bc-java/commits/master/core/src/main/java/org/bouncycastle/crypto/util/OpenSSHPrivateKeyUtil.java) but didn't see anything.

**Comment by peterdettman** [comment]
Our private repo mirrors to GitHub once a day I think, give it time. We'll check whether it needs a kick.

**Comment by peterdettman** [comment]
FYI, there is a new beta release containing this fix (164b01) at https://downloads.bouncycastle.org/betas/ .

**Comment by jamespowenjr** [comment]
Seems to be working well now. Thanks for the quick response and fix.
