### ISSUE TITLE
Constructor BCECGOST3410_2012PublicKey(SubjectPublicKeyInfo info) is not public

### ISSUE THREAD

**Issue by wilx** [bcgit/bc-java#598]
Is there a reason why [`BCECGOST3410_2012PublicKey(SubjectPublicKeyInfo info)`](https://github.com/bcgit/bc-java/blob/738dfc0132323d66ad27e7ec366666ed3e0638ab/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/ecgost12/BCECGOST3410_2012PublicKey.java#L170) constructor is not public? It seems like something I want to use right now.

**Comment by bcgit** [comment]
Use KeyFactory with an X509EncodedKeySpec(info.getEncoded()).
