### ISSUE TITLE
Compile error in org.bouncycastle.openssl.test.ParserTest

### ISSUE THREAD

**Issue by kimmerin** [bcgit/bc-java#599]
Hi,

when working with the sources I always have a compile error. Because it hasn't affected any part I was working on, I simply commented out that block but I'm still wondering.

The error I get is
> Unlikely argument type KeyPurposeId for contains(Object) on a Collection<ASN1ObjectIdentifier>

in ParserTest.java on lines 345 and 354.

One of the culprit code blocks is

```
    if (!trustBlock.getUses().contains(KeyPurposeId.id_kp_OCSPSigning))
    {
        fail("key purpose use not found");
    }
```

I can completely understand why the compiler is complaining. The Set contains elements of type ASN1ObjectIdentifier and it should check if it contains an element of type KeyPurposeId. That can't return true whatsoever.

So that particular test case should fail all the time, even if the class has successfully been compiled with a more lenient compiler than the one I'm using here. Is ParserTest not part of the test suite or do I miss something here?

**Comment by suraj0208** [comment]
'ASN1ObjectIdentifier' is inherited from 'ASN1Primitive' which is an 'ASN1Object'
KeyPurposeId is inherited from 'ASN1Object' directly. 
So both 'ASN1ObjectIdentifier' and 'KeyPurposeId' are 'ASN1Object'

'equals' and 'hashCode' are overridden in 'ASN1Object' and not in their respective subclasses mentioned above.
So 'contains' should work here.

I use intellij to build the project and I get a warning not compiler error.

**Comment by kimmerin** [comment]
Am 29.09.2019 um 16:36 schrieb Suraj:
> 'ASN1ObjectIdentifier' is inherited from 'ASN1Primitive' which is an 'ASN1Object'
> KeyPurposeId is inherited from 'ASN1Object' directly.
> So both 'ASN1ObjectIdentifier' and 'KeyPurposeId' are 'ASN1Object'

Yes, but the Set is declared as Set<ASN1ObjectIdentifier> and not
as Set<ASN1Object>.

> I use intellij to build the project and I get a warning not compiler error.

Is IntelliJ also only coming up with a warning if you declare a
Set<String> and try to add an Integer to it? Both classes
derive from java.lang.Object and only coming up with a warning
instead of an error drives that feature useless.


Cheers, Lothar
-- 
Lothar Kimmeringer                  E-Mail: lothar@kimmeringer.de
                PGP-encrypted mails preferred (Key-ID: 0x8BC3CD81)

Always remember: The answer is forty-two, there can only be wrong
                  questions!

**Comment by suraj0208** [comment]
Yes saw the set declaration and realized it. Removed the comment.

**Comment by bcgit** [comment]
ASN1 objects are compared for equality based on their primitive encoding - classes are really something we introduce over the top. It's done like this as it's not always clear if you are going to be dealing with a primitive encoding of a class, or an actual class object. KeyPurposeId works in this case as it encodes to an ASN1ObjectIdentifier - that said, it does look a bit odd. I've fixed the test to use the correct type.
