### ISSUE TITLE
Feature request: stream-based CMS encryption

### ISSUE THREAD

**Issue by SkyCrawl** [bcgit/bc-java#606]
Hello everyone.

during development, I came up with the following code to generate encoded [EnvelopedData object](https://tools.ietf.org/html/rfc5652#section-6.1):

```
private byte[] encrypt(byte[] plaintext, X509Certificate certificate) throws NoSuchProviderException, 
            IOException, CMSException, CertificateException {
    CMSEnvelopedDataGenerator generator = new CMSEnvelopedDataGenerator();
    generator.addRecipientInfoGenerator(getCertPublicKeyRIG(certificate));

    CMSProcessableByteArray contentToBeEncrypted = new CMSProcessableByteArray(plaintext);
    CMSEnvelopedData envelopedData = generator.generate(contentToBeEncrypted, new JceCMSContentEncryptorBuilder(ALG_ENC_OID)
                .setProvider(BouncyCastleProvider.PROVIDER_NAME).build());
    return envelopedData.getEncoded();
}
```

But, in my circumstances, plaintext can be large and since [CMSEnvelopedDataGenerator](https://github.com/bcgit/bc-java/blob/master/pkix/src/main/java/org/bouncycastle/cms/CMSEnvelopedDataGenerator.java) reads the whole content into a byte array, naturally, that's a problem for me because I don't want to allocate so much memory. Therefore, I would like to request for CMSEnvelopedDataGenerator to support stream processing of content to be encrypted. To my understanding, CMSEnvelopedDataParser already supports it fully on the decryption side (but better not take my word for it).

Ideally, I would like to write something like this instead:
```
InputStream plaintext; // plain-text is read from here (no large buffers)
OutputStream encoded; // encoded EnvelopedData is written here (no large buffers)
CMSProcessableStream contentToBeEncrypted = new CMSProcessableStream(plaintext);
CMSEnvelopedData envelopedData = generator.generate(contentToBeEncrypted, encoded, new JceCMSContentEncryptorBuilder(ALG_ENC_OID)
                .setProvider(BouncyCastleProvider.PROVIDER_NAME).build());
```

Is it even possible (i.e. is there something deep ASN1-related that prevents this)?

Many thanks,
Jiri

**Comment by peterdettman** [comment]
Are you aware that CMSEnvelopedDataStreamGenerator exists?

**Comment by SkyCrawl** [comment]
No, I wasn't aware but now I am :). Thank you very much!
