### ISSUE TITLE
NullPointerException raised in CertificatePolicies.fromExtensions() if no extensions present

### ISSUE THREAD

**Issue by dpond** [bcgit/bc-java#608]
There's no check if extensions is null before calling getExtensionParsedValue() on it at line 46:

return CertificatePolicies.getInstance(extensions.getExtensionParsedValue(Extension.certificatePolicies));

**Comment by peterdettman** [comment]
Thanks for reporting, we've added null guards for this and similar cases, so that null is returned when extensions is null. (Note that the github mirror does not update immediately).
