### ISSUE TITLE
Inconsistent RSA key size under FIPS

### ISSUE THREAD

**Issue by gstanchev** [bcgit/bc-java#616]
I am new to FIPS so excuse me if I have overlooked something obvious but I am curious about differences in how the Java and DotNet BCFIPS providers validate generation of RSA keys and key sizes.

In “bc-fips-1.0.1-sources\crypto\fips\FipsRsa.cs” we see the following code

           internal void Validate()
            {
                …

                if (CryptoServicesRegistrar.IsInApprovedOnlyMode())
                {
                    if (this.keySize != 2048 && this.keySize != 3072)
                    {
                        throw new CryptoUnapprovedOperationError("Attempt to use RSA key size outside of accepted range - requested keySize " + keySize + " bits", Algorithm);
                    }

Whereas the java code “bc-fips-1.0.2-sources\src\org\bouncycastle\crypto\fips\FipsRSA.java” does

        private void validate()
        {
            if (CryptoServicesRegistrar.isInApprovedOnlyMode())
            {
                if (this.keySize < 2048)
                {
                    throw new FipsUnapprovedOperationError("Attempt to use RSA key size outside of accepted range - requested keySize " + keySize + " bits", getAlgorithm());
                }

As we can see the Dot Net code is more restrictive. I did check the security policy doc: https://bouncycastle.org/fips/BCSecurityPolicy.pdf which states that most approved usages are 2048 and 3072 except for Signature Verification…

So my question is why the discrepancy in validation…and is it an issue with BCFIPS?

George

**Comment by bcgit** [comment]
No, it's a question of when the validation was done. The rules changed during that period.
