### ISSUE TITLE
NPE in ProvSSLSessionBase#getCipherSuite under Tomcat

### ISSUE THREAD

**Issue by gstanchev** [bcgit/bc-java#617]
This code:

` 
public String getCipherSuite()
{
        return sslSessionContext.getSSLContext().getCipherSuiteString(getCipherSuiteTLS());
}
`

Throws NPE under Tomcat when the handshake fails. To be more precise, i am running BCFIPS+BCJSSE as JSSE provider for Tomcat 8.5. When the initial handshake fails for any reason, TC still calls SSLEngine.getSession() (which happens to be org.bouncycastle.jsse.provider.ProvSSLEngine) at which point it gets back "ProvSSLSession.NULL_SESSION" because null == connection is true in getSession(). Such null session has null sessionContext both in itself and in the exportSession member. Later in the cycle TC tries to log the request via the AccessLogValve which lazily tries to extract cipher suite, certificate key and other attributes (reference here: 8.5.47-src\java\org\apache\coyote\AbstractProcessor.java#populateSslRequestAttributes()). Because sslSessionContext is null, we get NPE. Code should be changed to check if sslSessionContext is null and return null. Same applies to other sister methods that do sslSessionContext.someCall() in the same file.

**Comment by peterdettman** [comment]
Fixed already in 1.64.

**Comment by gstanchev** [comment]
I should have started with it and I apologize for missing it, but i run into this issue using bctls-fips-1.0.9. How often is the bctls-fips released or is it tied to the bcfips certification?

**Comment by peterdettman** [comment]
FYI bctls-fips is not tied to certification. Fix is long since in bctls-fips and we are currently up to 1.0.11.4 I think, and 1.0.12 will release shortly after bc-java 1.69 (with basically the same BCJSSE functionality).
