### ISSUE TITLE
DefaultSignatureAlgorithmIdentifierFinder unused vars in "generate" method

### ISSUE THREAD

**Issue by svkreml** [bcgit/bc-java#618]
org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.java

in Method 
private static AlgorithmIdentifier generate(String signatureAlgorithm)

there are three vars:
 ```
        AlgorithmIdentifier sigAlgId;
        AlgorithmIdentifier encAlgId;
        AlgorithmIdentifier digAlgId;
```

but then return only "return sigAlgId;"

Maybe its a typo?

**Comment by bcgit** [comment]
Just unused. Cleaned up.
