### ISSUE TITLE
Inconsistent code formatting

### ISSUE THREAD

**Issue by rillig-tk** [bcgit/bc-java#619]
https://github.com/bcgit/bc-java/blob/a66e904a431d992281c8378064fed4cbc4ab1d99/prov/src/main/java/org/bouncycastle/x509/X509V1CertificateGenerator.java#L47-L50

The variable `sigOID` is not aligned vertically with the other variables.
This means that there is no enforced formatting style.
This in turn means it is possible to have misleading indentation, like in the popular `goto fail` bug.

**Comment by kimmerin** [comment]
A good unit test (i.e. providing good coverage of the CUT) should prevent bugs of the "goto fail"-category.

**Comment by bcgit** [comment]
No, it just means the regex for a declaration allows multiple ' '. I agree about misleading indentation though - unit tests help, but it's much better to "write it as you run it"
