### ISSUE TITLE
Does the DTLSServerProtocol send a client verify request?

### ISSUE THREAD

**Issue by roshanrajaratnam** [bcgit/bc-java#622]
Hi, going through he DTLSServerProtocol I found the following comment `// TODO Need to handle sending of HelloVerifyRequest without entering a full connection` [here](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/tls/DTLSServerProtocol.java#L65). Does this mean the current implementtation does not send a ClientHelloVerifyRequest?

This is in references to the following the diagram on section 4.2.2 page 19 of [RFC](https://tools.ietf.org/html/rfc6347#section-4.2.2) 6347.

**Comment by roshanrajaratnam** [comment]
Going through the test package, I found out that verify request is something that has to be handled myself using the `DTLSVerifier`. May be the `TODO` statement was a bit misleading.

**Comment by peterdettman** [comment]
The TODO you mentioned was in the legacy (D)TLS API version (org.bounycastle.crypto.tls package). The legacy API has been removed now, so the "new" API in org.bouncycastle.tls should be used; DTLSVerifier is how HelloVerifyRequest is handled, as you noted, and the TODO is not present there (so not misleading).
