### ISSUE TITLE
Support for TLS_ECJPAKE_WITH_AES_128_CCM_8?

### ISSUE THREAD

**Issue by roshanrajaratnam** [bcgit/bc-java#625]
I noticed that bouncy castle does not support TLS_ECJPAKE_WITH_AES_128_CCM_8 in the list of cipher suites. Is this something that will be added in the future?

**Comment by peterdettman** [comment]
AFAICT, that cipher suite is from a draft RFC that expired almost 3 years ago:
    https://tools.ietf.org/html/draft-cragie-tls-ecjpake-01

We sometimes implement draft RFCs where we anticipate they will be accepted (or to aid in their development). In this case it appears the draft is expired/abandoned, so we would not implement it.

**Comment by roshanrajaratnam** [comment]
Thanks for your response, however there is a RFC filed in 2017 which defined 
 J-PAKE over Ellyptic Curve. https://tools.ietf.org/html/rfc8236

**Comment by peterdettman** [comment]
Your original question was about the TLS_ECJPAKE_WITH_AES_128_CCM_8 cipher suite. RFC 8236 appears to define the cryptographic primitive, but it does not specify how that would be used in TLS.
