### ISSUE TITLE
Missing OSGi imports in bctls

### ISSUE THREAD

**Issue by swaninga** [bcgit/bc-java#626]
We are using bctls (bctls-jdk15on-164.jar) in an OSGi environment.
As soon as we want to initalize a SSLContext with

SSLContext.getInstance("TLSv1.2",new BouncyCastleJsseProvider(new BouncyCastleProvider()));

we get the following error 

java.lang.ClassNotFoundException: javax.net.ssl.SSLContextSpi not found by bctls [15]

If i add the javax.net.ssl import manually everything works for me.

javax.net.ssl;resolution:=optional

Best Regards,
Mathias

**Comment by bcgit** [comment]
Thanks for the report. This should now be fixed as of 165b02 from https://www.bouncycastle.org/betas
