### ISSUE TITLE
java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by pjf000** [bcgit/bc-java#628]
java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)

I don't want to add any configuration in my JDK, and my project build with maven springboot. So what can I do?

**Comment by gstanchev** [comment]
It looks like you have provided wrong password. Check the keystore password

**Comment by bcgit** [comment]
You'd see this if the provider had had its signature removed or there was a class annotation error (as in the provider jar had been loaded using an untrusted class loader before the system class loader picked it up). It is possible to add the provider without changing the JVM's config, but it depends on how you do it.
