### ISSUE TITLE
 Null Dereference 

### ISSUE THREAD

**Issue by Sathishdisys** [bcgit/bc-java#635]
### Issue Description
Explanation Null pointer exceptions usually occur when one or more of the programmer's assumptions is violated. A dereference-after-store error occurs when a program explicitly sets an object to null and dereferences it later. This error is often the result of a programmer initializing a variable to null when it is declared

Most null pointer issues result in general software reliability problems, but if attackers can intentionally trigger a null pointer dereference, they can use the resulting exception to bypass security logic or to cause the application to reveal debugging information that will be valuable in planning subsequent attacks

### Recommendation 
Implement careful checks before dereferencing objects that might be null. When possible, abstract null checks into wrappers around code that manipulates resources to ensure that they are applied in all cases and to minimize the places where mistakes can occur.

### Issue File
 iskan-android​/app​ /libs​/sc-light-jdk15on-1​.47​.0​.2​.jar​ /org​/spongycastle​/asn1​/x509​ /X509Name​.java:1212
iskan-android​/app​ /libs​/sc-light-jdk15on-1​.47​.0​.2​.jar​ /org​/spongycastle​/math​/ntru​ /polynomial​/IntegerPolynomial​ .java:737

**Comment by bcgit** [comment]
Neither of these seem to apply in the current code base.
