### ISSUE TITLE
Support for EdDSA as PGP public key algorithm

### ISSUE THREAD

**Issue by p-** [bcgit/bc-java#636]
Hello,
first of: Thank you for Bouncy Castle!

This feature request might already exist in another form (but I couldn't find it).
When I tried to verify a PGP signature which has been created with a Curve 25519 Public Key.
I got this exception:
`org.bouncycastle.openpgp.PGPException: cannot recognise keyAlgorithm: 22`

So, as I understand that EdDSA is **not** yet part of the OpenPGP standard.
It probably will be in: [openpgp-rfc4880bis](https://tools.ietf.org/html/draft-ietf-openpgp-rfc4880bis-08#section-10.3.1), however.

Assuming that Curve 25519, will be used even more for newer PGP keys it would be nice if Bouncy Castle would support it.

**Comment by bcgit** [comment]
Thanks for the suggestion. Can you provide sample data? It would help.

**Comment by bcgit** [comment]
Okay, so I've found some data. The results are now on https://www.bouncycastle.org/betas 165b14 or later. OpenPGP now support EdDSA and key agreement using Curve25519

**Comment by eshryane** [comment]
Hello @bcgit I'm also having this problem, and still with the 165b14 beta version.

I get an exception when initialising the

`pgpSignature.init(new BcPGPContentVerifierBuilderProvider(), publicKey);
`

Should I do something different? Is there any example code for this scenario?

**Comment by eshryane** [comment]
My failing test:

https://github.com/RIPE-NCC/whois/blob/93719fef213f27b80f9d6565da415c25f8250ae3/whois-update/src/test/java/net/ripe/db/whois/update/keycert/PgpSignedMessageTest.java#L490

**Comment by bcgit** [comment]
Okay, that's using the low-level API, I think that is sorted out as well now. We've rolled that in as well try https://www.bouncycastle.org/betas 165b15 or later.

**Comment by eshryane** [comment]
Hi @bcgit Thanks for your update, I re-tested using 165b15 but the test is still failing.

Let me know if I can help debug this.

**Comment by peterdettman** [comment]
We've made more changes and with latest code I was able to run your test case 'verify_signed_message_with_ed25519_key ' successfully.

Please note that the test case 'verify_signed_message_with_ed25519_key_failure' has a bug; the "replace" that is supposed to modify the signed message is only applied to the last fragment:
`"-----END PGP SIGNATURE-----".replace("First Person", "Some Text")`
which obviously isn't doing anything.

Once that is fixed to actually modify the message, then this failure test also passes.

We'll try to get you a new beta release ASAP.

**Comment by eshryane** [comment]
@peterdettman Many thanks, good to hear. I'll fix my test, and wait for the new beta release.

**Comment by bcgit** [comment]
New beta is up https://www.bouncycastle.org/betas 165b16 or later.

**Comment by eshryane** [comment]
@bcgit I confirm the new beta fixes the issue for me. Many thanks!
