### ISSUE TITLE
Provider doesn't register GOST3411WITHECGOST3410-2012-* signature alg family

### ISSUE THREAD

**Issue by kostousov-ds** [bcgit/bc-java#637]
ECGOST.java line 98 register sign algs:
```
addSignatureAlgorithm(provider, "GOST3411-2012-256", "ECGOST3410-2012-256",
  PREFIX_GOST_2012 + "ECGOST2012SignatureSpi256",
  RosstandartObjectIdentifiers.id_tc26_signwithdigest_gost_3410_12_256);
```
and then the Provides knows `GOST3411-2012-256WITHECGOST3410-2012-256` and `GOST3411-2012-512WITHECGOST3410-2012-512` 

But it doesn't know `GOST3411WITHECGOST3410-2012-256` and `GOST3411WITHECGOST3410-2012-512`.

**Comment by bcgit** [comment]
I've added the missing aliases.
