### ISSUE TITLE
Security alert from play store 

### ISSUE THREAD

**Issue by nileshpatil9999** [bcgit/bc-java#640]
Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article ( https://support.google.com/faqs/answer/9450925 ) for details.

Vulnerable classes:Org.spongycastle.openpgp.operator.jcajce.JcePBEKeyEncryptionMethodGenerator.encryptSessionInfo

**Comment by bcgit** [comment]
You'll need to ask them to  fix the analyzer. I think it's triggering because of the use of the zero IV. This is by definition though.
