### ISSUE TITLE
Should the version number be updated?

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#648]
The current `bc-build.properties` appears to claim the repo master branch is still `1.64`. Is that true? Shouldn't it be at least `165b03`?

https://github.com/bcgit/bc-java/blob/5c487ecdffc1416cadf57c22acad132935f246d1/bc-build.properties#L4

**Comment by bcgit** [comment]
Somehow got added to the IDE's ignore list... Should correct soon.
