### ISSUE TITLE
IES AlgorithmParameter decoding not handling all variants

### ISSUE THREAD

**Issue by diamondq** [bcgit/bc-java#649]
The `org.bouncycastle.jcajce.provider.asymmetric.ies.AlgorithmParameterSpi` attempts to decode the ASN structure in `engineInit` that was written by `engineGetEncoded`. Unfortunately, there are a number of variants that encode, but don't decode.

For example, if your derivation and encoding vectors are null, then it's encoded as a 2 length sequence (the MAC Key Size and Nonce), but it will attempt to decode as either a (Derivation, MAC Key Size) or (Encoding, MAC Key Size). Using only the length of the sequence to determine the variant when 3 out of the 4 fields are optional won't work.

Instead, I would imagine that the best solution would be to look at the actual objects in the `ASN1Sequence`, and depending on whether it's a `ASN1TaggedObject`, an `ASN1Integer` or `ASN1Sequence`, the appropriate decoding can be determined.

**Comment by dghgit** [comment]
Thanks for the report. Yes, I'd say this was fairly tragic. I've now pulled this more in line and made it possible to preserve point compression as well. This will be in 1.70.
