### ISSUE TITLE
IESCipher not responding with correct output size calculations when using update()

### ISSUE THREAD

**Issue by diamondq** [bcgit/bc-java#650]
Within `org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher`, specifically the `engineGetOutputSize`, it doesn't calculate the size correctly if `update` is used before calling `getOutputSize`. In this case, the `buffer` is filled with data. However, `engineGetOutputSize` doesn't pass the size of the buffer through the cipher `getOutputSize` routine. Instead, it just assumes the output size is the size of the buffer. The buffer is the 'pre-ciphered' data, not the 'post-ciphered' data. For most Cipher's there is some form of block size, and by not passing it through the cipher's `getOutputSize`, the block size isn't taken into account.

NOTE: I understand that code can also use the `ShortBufferException` as an indicator to expand the buffer, but the `getOutputSize` is supposed to return the correct value.

This is especially noticeable when using `update` to push the data in, and then calling `getOutputSize` with a length of 0 (since 0 bytes are going to be passed to the `doFinal`).
In the test case below, the output is:
```
Actual size of data: 29
Expected size when only doFinal: 53
Expected size of update/doFinal: 50
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher.engineDoFinal(IESCipher.java:499)
	at javax.crypto.Cipher.doFinal(Cipher.java:2111)
	at SizeTest.main(SizeTest.java:44)
```
When calling the first `getOutputSize(29)`, you get a size of 53 (this is the nearest block size of 16 for the cipher (=32) + 20 for the MAC + 1 extra), but when the update is called with the data, and then a `getOutputSize(0)` (in preparation for the `doFinal(empty)`), it returns 50. This is because the buffer size of 29 isn't passed through the `cipher.getOutputSize`, and thus, isn't padded to the block size (and you get 29 + 20 for the MAC + 1 extra).

```java
    Security.addProvider(new BouncyCastleProvider());

    final byte[] data = "Block of data to be encrypted".getBytes(Charsets.UTF_8);

    System.out.println("Actual size of data: " + data.length);

    /* Generate keys */

    final KeyPairGenerator generator = KeyPairGenerator.getInstance("ECIES", BouncyCastleProvider.PROVIDER_NAME);
    final KeyPair keyPair = generator.generateKeyPair();
    final SecureRandom random = SecureRandom.getInstanceStrong();
    final byte[] nonce = new byte[16];
    random.nextBytes(nonce);

    /* Encrypt */

    final Cipher encryptCipher = Cipher.getInstance("ECIESWITHAES-CBC", BouncyCastleProvider.PROVIDER_NAME);
    final IESParameterSpec spec = new IESParameterSpec(null, null, 128, 128, nonce);
    encryptCipher.init(Cipher.ENCRYPT_MODE, new IEKeySpec(keyPair.getPrivate(), keyPair.getPublic()), spec);

    /* Calculate the size if only doFinal was going to be called */

    final int onlyFinalExpectedSize = encryptCipher.getOutputSize(data.length);

    /* Calculate the size with an update followed by an empty doFinal */

    encryptCipher.update(data);
    final int updateAndFinalExpectedSize = encryptCipher.getOutputSize(0);
    System.out.println("Expected size when only doFinal: " + onlyFinalExpectedSize);
    System.out.println("Expected size of update/doFinal: " + updateAndFinalExpectedSize);
    final byte[] encrypted = new byte[updateAndFinalExpectedSize];
    final int actualEncryptedSize = encryptCipher.doFinal(encrypted, 0);
    System.out.println("Actual encrypted size: " + actualEncryptedSize);
```
This happens for both encryption and decryption, but the sample only shows encryption.

**Comment by dghgit** [comment]
Thanks for the report. I think this is now fixed, the length of the current buffer was being applied at the wrong spot...
