### ISSUE TITLE
Updating from 1.6.3 to 1.6.4 breaks due to the change of getEncoded

### ISSUE THREAD

**Issue by SElab2019** [bcgit/bc-java#651]
When I try to upgrade bcprov-jdk15on from 1.6.3 to 1.6.4. The following code breaks.

```
public static String encodePublicKey(NetPrefix prefix, ECPoint pub) {
    return encodePublicKey(prefix, pub.getEncoded());
}
```
The code should pass, but it throws an error:
```
method getEncoded in class org.bouncycastle.math.ec.ECPoint cannot be applied to given types;
[ERROR]   required: boolean
[ERROR]   found: no arguments
[ERROR]   reason: actual and formal argument lists differ in length
```

**Comment by peterdettman** [comment]
ECPoint.getEncoded() was a deprecated method that was removed in 1.64. Callers should use getEncoded(boolean) instead (the argument controls whether point compression will be used).
