### ISSUE TITLE
BouncyCastle Extremely Slow

### ISSUE THREAD

**Issue by hyperxpro** [bcgit/bc-java#652]
I was testing BouncyCastle and JCE with some AES encryption and found BouncyCastle was 4-5 times slower than JCE.

AES/ECB/PKCS5Padding with 128 Bit Key:
JCE: 200 ms. average
BC: 1000 ms. average

Can Someone Help?

Here is the code:

```Java
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

public class CryptoTest {

    private static final SecretKeySpec secretKey = new SecretKeySpec(new byte[16], 0, 16, "AES");;

    public static void main(String[] args) throws Exception {
        JCE();
        BC();
    }

    public static void JCE()  throws Exception{
        for (int i = 0; i < 10; i++) {
            long start = System.currentTimeMillis();

            Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
            cipher.init(Cipher.ENCRYPT_MODE, secretKey);
            cipher.doFinal(new byte[100000000]);


            System.out.println("JCE Milliseconds: " + (System.currentTimeMillis() - start));
        }
    }

    public static void BC()  throws Exception{
        for (int i = 0; i < 10; i++) {
            long start = System.currentTimeMillis();

            Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding", new BouncyCastleProvider());
            cipher.init(Cipher.ENCRYPT_MODE, secretKey);
            cipher.doFinal(new byte[100000000]);


            System.out.println("BC Milliseconds: " + (System.currentTimeMillis() - start));
        }
    }
}
```

**Comment by pvandenbroucke** [comment]
Hello,

IMHO, the problem comes from this line
`Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding", new BouncyCastleProvider());`

You should instantiate once and use the provider name : 

```
// before the loop
Security.addProvider(new BouncyCastleProvider());

// in the loop
Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding", BouncyCastleProvider.PROVIDER_NAME);

I hope this helps.
```

**Comment by hyperxpro** [comment]
Tried, No luck. Here is the updated code:

```java
import org.bouncycastle.jce.provider.BouncyCastleProvider;

import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import java.security.SecureRandom;
import java.security.Security;

public class CryptoTest {

    private static final SecretKeySpec secretKey = new SecretKeySpec(new byte[16], 0, 16, "AES");
    private static final byte[] data = new byte[100000000];

    public static void main(String[] args) throws Exception {
        Security.addProvider(new BouncyCastleProvider());

        JCE();
        BC();
    }

    public static void JCE() throws Exception {
        for (int i = 0; i < 10; i++) {
            long start = System.currentTimeMillis();

            Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
            cipher.init(Cipher.ENCRYPT_MODE, secretKey, new SecureRandom());
            cipher.doFinal(data);


            System.out.println("JCE Milliseconds: " + (System.currentTimeMillis() - start));
        }
    }

    public static void BC() throws Exception {
        for (int i = 0; i < 10; i++) {
            long start = System.currentTimeMillis();

            Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding", "BC");
            cipher.init(Cipher.ENCRYPT_MODE, secretKey, new SecureRandom());
            cipher.doFinal(data);


            System.out.println("BC Milliseconds: " + (System.currentTimeMillis() - start));
        }
    }
}
```

Output:

JCE Milliseconds: 421
JCE Milliseconds: 235
JCE Milliseconds: 222
JCE Milliseconds: 203
JCE Milliseconds: 199
JCE Milliseconds: 194
JCE Milliseconds: 189
JCE Milliseconds: 190
JCE Milliseconds: 186
JCE Milliseconds: 190
BC Milliseconds: 1075
BC Milliseconds: 1001
BC Milliseconds: 1000
BC Milliseconds: 971
BC Milliseconds: 993
BC Milliseconds: 987
BC Milliseconds: 982
BC Milliseconds: 953
BC Milliseconds: 963
BC Milliseconds: 948

**Comment by pvandenbroucke** [comment]
You also can extract the Cipher creation from the loop (cf [init()](https://docs.oracle.com/javase/7/docs/api/javax/crypto/Cipher.html#init(int,%20java.security.Key,%20java.security.SecureRandom)))

**Comment by kimmerin** [comment]
Most likely because the Java encrypt- and decrypt-implementation has been replaced by an intrinsic native method.

    com.sun.crypto.provider.AESCrypt:
    
    [...]
    // Encryption operation. Possibly replaced with a compiler intrinsic.
    private void implEncryptBlock(byte[] in, int inOffset,
                                  byte[] out, int outOffset)

https://gist.github.com/apangin/7a9b7062a4bd0cd41fcc shows the list of methods that have intrinsic native methods and implEncryptBlock and implDecryptBlock are in there.

**Comment by hyperxpro** [comment]
> Most likely because the Java encrypt- and decrypt-implementation has been replaced by an intrinsic native method.
> 
> ```
> com.sun.crypto.provider.AESCrypt:
> 
> [...]
> // Encryption operation. Possibly replaced with a compiler intrinsic.
> private void implEncryptBlock(byte[] in, int inOffset,
>                               byte[] out, int outOffset)
> ```
> 
> https://gist.github.com/apangin/7a9b7062a4bd0cd41fcc shows the list of methods that have intrinsic native methods and implEncryptBlock and implDecryptBlock are in there.

It makes sense but why BouncyCastle FIPS is even slower than normal BouncyCastle version.

**Comment by hyperxpro** [comment]
```java
import org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider;

import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import java.security.SecureRandom;
import java.security.Security;

public class CryptoTest {

    private static final SecretKeySpec secretKey = new SecretKeySpec(new byte[16], 0, 16, "AES");
    private static final byte[] data = new byte[100000000];

    public static void main(String[] args) throws Exception {
        Security.addProvider(new BouncyCastleFipsProvider());

        JCE();
        BC();
    }

    public static void JCE() throws Exception {
        Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
        cipher.init(Cipher.ENCRYPT_MODE, secretKey, new SecureRandom());

        for (int i = 0; i < 10; i++) {
            long start = System.currentTimeMillis();

            cipher.doFinal(data);

            System.out.println("JCE Milliseconds: " + (System.currentTimeMillis() - start));
        }
    }

    public static void BC() throws Exception {
        Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding", "BCFIPS");
        cipher.init(Cipher.ENCRYPT_MODE, secretKey, new SecureRandom());

        for (int i = 0; i < 10; i++) {
            long start = System.currentTimeMillis();

            cipher.doFinal(data);

            System.out.println("BC Milliseconds: " + (System.currentTimeMillis() - start));
        }
    }
}

```
Output:
JCE Milliseconds: 411
JCE Milliseconds: 213
JCE Milliseconds: 212
JCE Milliseconds: 204
JCE Milliseconds: 204
JCE Milliseconds: 198
JCE Milliseconds: 195
JCE Milliseconds: 189
JCE Milliseconds: 202
JCE Milliseconds: 196
BC Milliseconds: 1816
BC Milliseconds: 1707
BC Milliseconds: 1733
BC Milliseconds: 1710
BC Milliseconds: 1742
BC Milliseconds: 1670
BC Milliseconds: 1664
BC Milliseconds: 1645
BC Milliseconds: 1594
BC Milliseconds: 1615

**Comment by hyperxpro** [comment]
Lemme reopen. Closed it by mistake. Help still needed.

**Comment by dghgit** [comment]
So, the answer concerning intrinsic usage is correct. Your bench mark is about right for BCFIPS if you're using 1.0.2.1 - you may be able to speed things up by not just using doFinal() though. BC FJA-2.0.0 is around 50% slower than BC, so faster than 1.0.2.1. A lot of the other slowness will probably be due to compliance checks and settings - for example a doFinal like this will result in the allocation of a huge intermediate array which will then be zeroed out on completion.

**Comment by hyperxpro** [comment]
Makes sense. Thanks, @dghgit!

**Comment by suaha** [comment]
Hi, @hyperxpro, do you happen to find a way to speed this up?

**Comment by hyperxpro** [comment]
> Hi, @hyperxpro, do you happen to find a way to speed this up?

Sorry for 1 year late reply but nope, this remains slow. I moved to OpenSSL eventually.

**Comment by dghgit** [comment]
Since this conversation has sprung back to life - BC FJA 2.1.0 now includes native support for Intel on Linux and the BC LTS release 2.73.3 (which just came out) includes native support for Intel and ARM on Linux and Darwin.
