### ISSUE TITLE
Please remove tests classes from lib

### ISSUE THREAD

**Issue by mobilekosmos** [bcgit/bc-java#661]
We are integrating the library in an Android project through:
implementation 'org.bouncycastle:bcpkix-jdk15on:1.64'
and the latest version includes test classes which want to access a non-existing file:

org.bouncycastle.pqc.crypto.qtesla.QTeslaKeyEncodingTests.testDecodeEncodePrivateKeyQT3P()
BufferedReader var1 = new BufferedReader(new InputStreamReader(this.getClass().getResourceAsStream("/org/bouncycastle/pqc/crypto/test/q3pIII.txt")));

We have the problem that on Android all found tests are run automatically, also those present in imported libs, thus our CI is failing whlie executing the tests and we don't have a reliable way of excluding files from imported libs, so please if you could fix this!

**Comment by bcgit** [comment]
Can you identify where the class is coming from? The bcpkix jar does not appear to contain it.

**Comment by mobilekosmos** [comment]
Yes, it comes from bcprov-jdk15on-1.64.jar which is added automatically when you add bouncycastle:bcpkix
It's [this class](https://github.com/bcgit/bc-java/blob/master/core/src/test/java/org/bouncycastle/pqc/crypto/qtesla/QTeslaKeyEncodingTests.java)

**Comment by bcgit** [comment]
Thanks, found it. Oh dear... will see that it's removed in 165,

**Comment by mobilekosmos** [comment]
Thanks, will this be in H1 2020?

**Comment by bcgit** [comment]
We're hoping for the next few weeks. It's now up in https://www.bouncycastle.org/betas

**Comment by harri35** [comment]
I have the same issue. I can't update to 1.63 or 1.64 as then my instrumentation tests start failing. And sadly there is no easy way to exclude one instrumentation test from the set. The testOptions DSL only works with unit tests.

**Comment by bcgit** [comment]
does your testing work with the latest beta?

**Comment by harri35** [comment]
Hei!
Yes. If I use the following two artifacts:

- bcprov-jdk15to18-165b10.jar
- bcpkix-jdk15on-165b15.jar

then my Android project both builds fine, and all of my instrumentation tests are green. And there are no extra instrumentation tests included from the "bcprov" artifact.

Just in case I also executed all my integration tests, everything seems to be working fine there also.
So good work!

Just in case if this is in any way relevant - I didn't know which "bcprov" artifact to take and tested with all of them.

The "bcprov-jdk15on-165b15.jar" gave a Jetifier error. I assume it is of a wrong Java version for my build and this is how it should be. (Ignore the artifact name, I renamed it there.)
`* What went wrong:
Execution failed for task ':myappname:javaPreCompileDebug'.
> Could not resolve all files for configuration ':myappname:debugCompileClasspath'.
   > Failed to transform bcprov-jdk15on-1.65b15.jar (org.bouncycastle:bcprov-jdk15on:1.65b15) to match attributes {artifactType=android-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: <my local maven repo path>\maven\org\bouncycastle\bcprov-jdk15on\1.65b15\bcprov-jdk15on-1.65b15.jar.
         > Failed to transform '<my local maven repo path>\maven\org\bouncycastle\bcprov-jdk15on\1.65b15\bcprov-jdk15on-1.65b15.jar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)`

Secondly, maybe more interestingly, the "bcprov-jdk14-165b13.jar" gave this error. Did something change there with the ASN1Encodable class? Or is this also expected?

`<myapppath>/HardwareKeyStore.java:396: error: for-each not applicable to expression type
        for (ASN1Encodable digest : digests) {
                                    ^
  required: array or java.lang.Iterable
  found:    ASN1Set`

Tested with:
- Gradle 6.1.1
- Android Gradlew Plugin 3.5.3
- versionCompileSdk = 28
- versionBuildTools = '28.0.3'
- versionMinSdkVersion = 16
- versionTargetSdk = 23
- Samsung Galaxy Tab S3 9.7 API 28

Thanks again!
