### ISSUE TITLE
Possible Bug in GCMBlockCipher nonce/key reuse check

### ISSUE THREAD

**Issue by sk13** [bcgit/bc-java#662]
Dear BouncyCastle Team,

there might be a bug in GCMBlockCipher.init().
More specific the bug is related to the check, if nonce and key are reused -- lines  140-150

````
if (forEncryption)
        {
            if (nonce != null && Arrays.areEqual(nonce, newNonce))
            {
                if (keyParam == null)
                {
                    throw new IllegalArgumentException("cannot reuse nonce for GCM encryption");
                }
                if (lastKey != null && Arrays.areEqual(lastKey, keyParam.getKey()))
                {
                    throw new IllegalArgumentException("cannot reuse nonce for GCM encryption");
                }
            }
        }
````

So you try to check if the previous nonce and the newNonce are the same. But in fact you do not really do this.

The field 'nonce' is not a copy of the previous nonce value but stores just the reference to the byte array used previously -- line 153

````
nonce = newNonce;
````

So if the application developer will reuse the same byte array for two successive calls to init() the Arrays.areEqual(nonce, newNonce) check will always give true -- because nonce and newNonce refer to the same byte array.

Here is an example code which triggers the problem:

````
1:  byte [] iv=new byte [12];
2: AEADParameters key= new AEADParameters(new KeyParameter(keyvalue, 0, 16), 128, iv, null);
3: cipher.init(true,key);
4: iv[0]=1;
5: cipher.init(true,key);
````

As you can see the nonce in fact has a different value in the two calls to init() -- line 3 and 5.
But line 5 will fail because the check Arrays.areEqual(nonce, newNonce) will actually read like: Arrays.areEqual(iv,iv)

Sincerely,
Stefan Köpsell
 
PS: I guess Arrays.areEqual(lastKey, keyParam.getKey()) will lead to a similar problem...

**Comment by acid1103** [comment]
The existing code is actually correct, as in the constructor for `AEADParameters`, the iv is cloned (line 37.) Likewise, the constructor for `ParametersWithIV` also clones the iv (line 27,) and since those are the only valid `CipherParameters` for a `GCMBlockCipher`, the existing code is fine. In other words, line 4 of your code isn't changing the iv stored in `key`, as `key` contains only a copy of the iv you constructed it with. So, the check and assignment are both fine.

**Comment by dghgit** [comment]
Very eloquent description. Thanks.
