### ISSUE TITLE
Attempting to load the default cacerts fails on Java 9

### ISSUE THREAD

**Issue by hborders** [bcgit/bc-java#663]
With [`JEP-229`](http://openjdk.java.net/jeps/229), Java 9 started defaulting to `javax.net.ssl.trustStoreType=pkcs12` while for Java 8, it was `javax.net.ssl.trustStoreType=JKS`. Java 9 works around this change with their `DualFormatPKCS12` `KeyStoreSpi` that first attempts to load a file as `PKCS12` and then as `JKS`. Unfortunately, when I tried using `bouncycastle` `1.52`, [it failed to load until I manually set `javax.net.ssl.trustStoreType=JKS`](https://stackoverflow.com/a/60472730/9636).

Can you please implement a similar dual format `KeyStoreSpi` so that `bouncycastle` works by default?

Thanks!

**Comment by peterdettman** [comment]
Are you just using the BC provider, or our BCJSSE provider too? Also, 1.52 is 5 years old now - any chance you could report results for our current release (1.64) or even our latest beta (https://downloads.bouncycastle.org/betas/)?

**Comment by hborders** [comment]
I just tested it on `1.64` and the same problem occurs, and the same workaround fixes it. I'm still trying to figure out how to get gradle to use the downloaded beta.

**Comment by hborders** [comment]
I was able to test with `bcprov-jdk15on-165b08.jar` and the same problem occurs, and the same workaround fixes it.

**Comment by bcgit** [comment]
We wouldn't add this to PKCS#12, although we'd consider creating a new keystore type which did both. I'm not very comfortable about the idea of someone thinking they're opening a PKCS12 keystore and getting a JKS keystore instead. For something like cacerts it's not a big deal as it's just dealing with public keys, but there's clearly a problem if private keys are involved. The security profiles of the two types are quite different.

**Comment by hborders** [comment]
That makes total sense. Would you consider a check to PKCS12 so that when this error occurs, you could suggest people use the `JKS` keystore instead? I imagine this error is going to occur for lots of folks when they first adopt JDK 9.

**Comment by kewu21** [comment]
Hi, is there a resolution to this issue? I am running into same error when upgrading JDK and using bc as the security provider.

**Comment by dghgit** [comment]
Yes, try using https://www.bouncycastle.org/betas 169b09 or later.
