### ISSUE TITLE
DLExternal encodes using DERTaggedObject leading to wrong data

### ISSUE THREAD

**Issue by kimmerin** [bcgit/bc-java#664]
[DLExternalTest.zip](https://github.com/bcgit/bc-java/files/4272143/DLExternalTest.zip)

I'm using the BC-ASN1-classes to implement an X.400 client. After upgrading to a more recent version of BC and changing the classes from using DER-classes to their DL counterparts, login to X.400 providers fail because the MSBind contains its elements in the wrong order after it's been added to ConnectP.

The reason is the way DLExternal (which is used in the UserInfo in a ConnectP) encodes itself:

https://github.com/bcgit/bc-java/blob/0299be05103f021a810b5a8797a69e67bb67ba4c/core/src/main/java/org/bouncycastle/asn1/DLExternal.java#L85-L86

The encode-method uses DERTaggedObject to create the external data part which leads to the effect observed above. I've created a test class, attached to this post, that shows the effect.

**Comment by bcgit** [comment]
Thanks for the report. Fixed and test added.
