### ISSUE TITLE
Android - Execution failed for task ':app:transformClassesWithDesugarForDebug'

### ISSUE THREAD

**Issue by MicxSamonte** [bcgit/bc-java#665]
I recently migrated an android project from spongycastle to bouncycastle, but I'm encountering errors when building the app.

I'm using the ff versions:

Gradle `5.6.4`
Java `openjdk 11.0.2`
BC `org.bouncycastle:bcprov-jdk15on:1.63`

**Comment by Jeffiano** [comment]
me too ！And the error message is Error:Illegal class file: Class module-info is missing a super type. The  project build successfully  if I change the version to bcprov-jdk15on:1.60

**Comment by dghgit** [comment]
It's reacting to the presence of the module-info class in the versions directory. Use the bcprov-jdk15to18- jars, they don't have a versions directory.
