### ISSUE TITLE
Certificate expires in April 2020 - any plans to renew it and re-sign jars?

### ISSUE THREAD

**Issue by dadhogy** [bcgit/bc-java#667]
Specifically bcprov-jdk15on-164.jar...thanks....

**Comment by bcgit** [comment]
It's going to be interesting - we can't renew the 1024 bit cert (the one expiring in April). The reason for that can be see in the following output:

Owner: CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Sun Microsystems Inc, L=Palo Alto, ST=CA, C=US
Issuer: CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Sun Microsystems Inc, L=Palo Alto, ST=CA, C=US
Serial number: 10
Valid from: Wed Apr 25 17:00:00 AEST 2001 until: Sat Apr 25 17:00:00 AEST 2020
Certificate fingerprints:
	 MD5:  66:25:5A:78:3E:1A:CA:06:C1:43:A6:15:AE:BE:A5:92
	 SHA1: 57:37:D1:E1:16:2F:F6:FE:26:B9:87:88:D2:86:DA:66:7F:98:54:3C
	 SHA256: 1A:D6:0D:3A:FF:59:9F:72:E8:59:13:3E:F4:EC:44:4B:6D:70:46:AE:38:D5:A8:82:C2:20:9C:E8:32:0B:E9:72
Signature algorithm name: SHA1withDSA
Subject Public Key Algorithm: 1024-bit DSA key
Version: 3

The 1024 bit JCE root certificate is about to expire.

Our 2048 bit key is good till 2022.

**Comment by bcgit** [comment]
Hi, I've checked with Oracle about this. Older JVMs will complain about the expired certificate but should still work.

The new certificate, with the 2030 expiry date, appeared in the following JVMs: Java releases 9+, Java 8u111, Java 7u121, Java 6u131.

Note the latest public release versions of Java 7 and Java 6 are at 6u45 and 7u80 respectively. 

If you need to be running Oracle's versions of Java 7 or Java 6 you can get access to the patched versions if you have Oracle support contract.

**Comment by dghgit** [comment]
Closed. Expired certificate still works, Oracle supported JVMs able to recognise new one.
