### ISSUE TITLE
Reset of all global System-Properties if a single Property is set in o.b.util.Properties

### ISSUE THREAD

**Issue by kimmerin** [bcgit/bc-java#671]
Properties.getPropertyValue is not used very often, but I stumbled over this while answering #645:

https://github.com/bcgit/bc-java/blob/4fe2c910d6d1a16326643f30dd08aef71a4d40dd/core/src/main/java/org/bouncycastle/util/Properties.java#L141-L147

If some value is set, e.g. for "org.bouncycastle.asn1.allow_unsafe_integer", this creates a map that will be added to the thread local threadProperties. If threadProperties returns a map, there is no fallback to the retrieval of a property value if that returned map doesn't contain an entry with a given key. I.e. all globally set system properties that are not "org.bouncycastle.asn1.allow_unsafe_integer" will suddenly be non-existent for that particular thread.

**Comment by peterdettman** [comment]
Thanks Lothar, it's fixed now.

**Comment by bcgit** [comment]
This is now up on https://www.bouncycastle.org/betas
