### ISSUE TITLE
PSKTlsServer/PSKTlsClient should indicate support for DTLS

### ISSUE THREAD

**Issue by NeilMadden** [bcgit/bc-java#672]
The PSKTlsServer and PSKTlsClient classes implement the `getSupportedVersions()` with the following code:

```java
        return ProtocolVersion.TLSv12.downTo(ProtocolVersion.TLSv10);
```

This prevents out-of-the-box use of these classes with DTLS, although simply overriding the method to include `DTLSv12` appears to allow them to work flawlessly with a DTLSProtocol.

Both classes should adjust their `getSupportedVersions()` methods to include DTLS protocol versions.

**Comment by peterdettman** [comment]
It's currently intended that you override to switch to DTLS versions when you are using it with DTLS. It's been assumed that DTLS and TLS versions are not mixed here, so even if it appears to work there could be problems lurking.

e.g. In the ongoing TLS 1.3 work, this array is sent directly to the server. TLS (DTLS) Servers should ignore the DTLS (TLS) protocols, but it's asking for trouble to do it.

**Comment by NeilMadden** [comment]
OK, that's good to know. I can raise a PR that adds some Javadoc to that effect if it helps? (Or add a separate PSKDtlsServer/client sub-class?)

**Comment by peterdettman** [comment]
I've added javadoc to getSupportedVersions. I don't think adding the separate subclasses is necessary.
