### ISSUE TITLE
NPE in ChaCha20Poly1305.processBytes, caused by ChaCha20Poly1305 expecting non-null input

### ISSUE THREAD

**Issue by acid1103** [bcgit/bc-java#674]
Using `bcprov-jdk15on-164` and `bcprov-jdk15on-165b08`, I'm receiving an NPE when using `ChaCha20-Poly1305` to encrypt data in a way that results in the `input` argument of `BaseBlockCipher.engineUpdate(byte[] input, int inputOffset, int inputLen)` to have a length less than `ChaCha20Poly1305.BUF_SIZE (64)` (for example, simply calling `Cipher.update` with a byte array of length 63.)

I think this is caused by `ChaCha20Poly1305.getUpdateOutputSize` returning the wrong result on line 1088 in the `engineUpdate` method mentioned above, resulting in `processBytes` being called with a null `out` argument.

The code to recreate this is roughly as follows:

``` java
Cipher cipher = Cipher.getInstance("CHACHA20-POLY1305", "BC");
cipher.init(/* ... */);
byte[] encrypted = cipher.update(new byte[63]); // error occurs here
```

Here's the stacktrace of the error:

```
java.lang.NullPointerException: 'out' cannot be null
	at org.bouncycastle.crypto.modes.ChaCha20Poly1305.processBytes(ChaCha20Poly1305.java:286)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$AEADGenericBlockCipher.processBytes(BaseBlockCipher.java:1416)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineUpdate(BaseBlockCipher.java:1112)
	at javax.crypto.Cipher.update(Cipher.java:1831)
	...
```

This is probably the underlying cause of #621.

**Comment by peterdettman** [comment]
Thanks for the report. The underlying issue is an API misunderstanding. BaseBlockCipher can pass null for the output buffer when it doesn't expect any actual output, in this case because it called getUpdateOutputSize which (correctly) returned 0. ChaCha20Poly1305 was insisting that the output buffer always be non-null. That check has been disabled as the immediate fix.
