### ISSUE TITLE
Unable to load GOST3410-2012 key from a PKCS#12 store

### ISSUE THREAD

**Issue by mrDoctorWho** [bcgit/bc-java#675]
Hi there,

I'm trying to use Bouncy Castle to sign data with given certificate and key from a PCKS#12 container. But I'm getting this error:

```java
Caused by: java.io.IOException: exception unwrapping private key - java.security.InvalidKeyException: Invalid key encoding.
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.unwrapKey(Unknown Source)
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at BouncyCastleGostTest.main(BouncyCastleGostTest.java:32)
```

The container is created with the following command:
```bash
openssl req -newkey gost2012_256 -pkeyopt paramset:A  -passout pass:test -keyout test.key -out test.crt -x509 -days 3650 
openssl pkcs12 -engine gost -export -in test.crt -inkey test.key -out container.p12 -password pass:test -passin pass:test
```

This is the code I used:

```java
public class BouncyCastleGostTest {

    static {
        BouncyCastleProvider bcProvider = new BouncyCastleProvider();
        String name = bcProvider.getName();
        Security.removeProvider(name);
        Security.addProvider(bcProvider);
    }

    public static void main(String[] args) throws Exception {

        final File file = new File("/tmp/container.p12");

        final byte[] keyStoreData = Files.readAllBytes(file.toPath());

        final String password = "test";
        final String keyPassword = "test";

        final KeyStore keyStore = KeyStore.getInstance("PKCS12", "BC");

        try (ByteArrayInputStream is = new ByteArrayInputStream(keyStoreData)) {
            keyStore.load(is, password.toCharArray());
        }

        final String alias = keyStore.aliases().nextElement();
        keyStore.getKey(alias, keyPassword.toCharArray());
    }
}
```

Is this a bug or am I doing something wrong? I'm using BouncyCastle 1.64.

Thanks!

**Comment by bcgit** [comment]
Can you provide a copy of the PKCS#12 key store? Not all versions of OpenSSL are equal...

**Comment by mrDoctorWho** [comment]
Thanks for your prompt answer!

Here are the files:
Container: https://drop.helldev.net/2f5995ac-054e-4702-b709-81482194206c/container.p12
Certificate: https://drop.helldev.net/4cd20f1d-a685-4efc-8476-ddd8e5a0eeb9/test.crt
Private Key: https://drop.helldev.net/501ab601-7db7-4831-8eef-21e91f683f1f/test.key

All passwords are: test.

I'm using OpenSSL 1.1.1  11 Sep 2018 which is a part of Ubuntu 18.04.4 LTS.

**Comment by bcgit** [comment]
I've uploaded a new beta which I think will fix this - it seems the private key is encoded without a wrapping OCTET STRING, seems to be easy enough to deal with. See https://www.bouncycastle.org/betas for details.

**Comment by mrDoctorWho** [comment]
Thanks a ton for your fix, @bcgit!

It works well now.

**Comment by bcgit** [comment]
And thanks for the report. Will be in 1.65.
