### ISSUE TITLE
QTESLA periodically generates invalid signatures

### ISSUE THREAD

**Issue by tonywasher** [bcgit/bc-java#678]
Every so often (approximately 1 in 1000 times) QTESLA generates a signature that fails verification. This is repeatable and occurs with randomly generated messages and keyPairs as per the following test harness. I can run the harness and get a failure every time. This only happens with PROVABLY_SECURE_I keys.

`    /**
     * The testMessage length.
     */
    private static final int MSGLEN = 1024;

    /**
     * The number of signatures.
     */
    private static final int NUMSIGNS = 10000;

    /**
     * The secureRandom.
     */
    private static final SecureRandom RANDOM = new SecureRandom();

    /**
     * The testMessage.
     */
    private static final byte[] MESSAGE = new byte[MSGLEN];

    /**
     * main.
     * @param pArgs the program arguments
     */
    public static void main(final String[] pArgs) {
        /* Initialise the message */
        RANDOM.nextBytes(MESSAGE);

        /* Create and initialise the generator */
        final QTESLAKeyPairGenerator myGenerator = new QTESLAKeyPairGenerator();
        final KeyGenerationParameters myParams
                = new QTESLAKeyGenerationParameters(QTESLASecurityCategory.PROVABLY_SECURE_I, RANDOM);
        myGenerator.init(myParams);

        /* Generate the keyPair */
        final AsymmetricCipherKeyPair myPair = myGenerator.generateKeyPair();
        final QTESLAPublicKeyParameters myPublicKey = (QTESLAPublicKeyParameters) myPair.getPublic();
        final QTESLAPrivateKeyParameters myPrivateKey = (QTESLAPrivateKeyParameters) myPair.getPrivate();

        /* Initialise signer and verifier */
        final QTESLASigner mySigner = new QTESLASigner();
        mySigner.init(true, new ParametersWithRandom(myPrivateKey, RANDOM));
        final QTESLASigner myVerifier = new QTESLASigner();
        myVerifier.init(false, myPublicKey);

        /* Loop NUMSIGNS times */
        for (int i = 0; i < NUMSIGNS; i++) {
            /* Sign the message */
            final byte[] mySignature =  mySigner.generateSignature(MESSAGE);

            /* Verify the signature */
            if (!myVerifier.verifySignature(MESSAGE, mySignature)) {
                /* Handle failure */
                System.out.println("\rFailed on signature " + (i + 1) + " of " + NUMSIGNS);
                System.exit(1);
            }

            /* Display progress */
            System.out.print("\r" + (i + 1));
        }

        /* Succeeded */
        System.out.println("\rSucceeded");
    }
`

**Comment by bcgit** [comment]
Thanks for the report, we think this is now fixed. It turned out there were a few other changes in the reference implementation as well. These have been rolled across also. Signature values appear to be the same.

**Comment by tonywasher** [comment]
I can confirm that this is fixed in 166b01.
Thanks

**Comment by peterdettman** [comment]
Thanks for confirming the fix. FYI we have just updated qTESLA to v2.8, which is incompatible with previous versions. Subsequent betas will use the new version.
