### ISSUE TITLE
Documentation/Examples TLSClientProtocol in non-blocking mode

### ISSUE THREAD

**Issue by joesam86** [bcgit/bc-java#679]
I couldn't find much examples on how to use TLSClientProtocol in non blocking mode. 
Can you point some links or guides where i can find examples to use TLSClientProtocol in non blocking mode?

**Comment by peterdettman** [comment]
I would suggest studying how TlsProtocol is used by our [SSLEngine implementation](https://github.com/bcgit/bc-java/blob/master/tls/src/main/java/org/bouncycastle/jsse/provider/ProvSSLEngine.java). Actually, it might even be better for you to use an SSLEngine from the BCJSSE provider. There is plenty of documentation on how to use it and many other tools will work with it already.

**Comment by joesam86** [comment]
Sure thanks!!!
