### ISSUE TITLE
BaseBlockCipher#engineDoFinal ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gMan1990** [bcgit/bc-java#680]
https://github.com/bcgit/bc-java/blob/52b0902592e770b8116f80f2eab7a4048b589d7d/prov/src/main/java/org/bouncycastle/jcajce/provider/symmetric/util/BaseBlockCipher.java#L1095
IF `len > tmp.length`

**Comment by bcgit** [comment]
I'd need a stack trace. The underlying cipher would have to be wrong for this to happen, len can only be less than or equal to tmp.length.

**Comment by gMan1990** [comment]
no stack trace, just code review(or debug: change `len` value, make `len > tmp.length`)

**Comment by dghgit** [comment]
Closing as false positive.
