### ISSUE TITLE
Java6 PKIXCertPathChecker

### ISSUE THREAD

**Issue by gaellalire** [bcgit/bc-java#681]
ProvAlgorithmChecker. checkChain call
```java
algorithmChecker.check(chain[i]);
```
which does not exists on Java 6 JDK

Please replace the call by
```java
algorithmChecker.check(chain[i], java.util.Collections.<String>emptySet());
```

**Comment by peterdettman** [comment]
Fixed, thanks. We'll get a new beta up shortly.

**Comment by gaellalire** [comment]
Thanks for your reactivity.
Note that I will need a oracle java 7 signed (jdk15to18) beta to test

**Comment by gaellalire** [comment]
Hello, I saw beta 02 which include this fix was released at https://www.bouncycastle.org/betas. Can you distribute the jdk15to18 ?

**Comment by bcgit** [comment]
I've added a jdk15to18 version.

**Comment by gaellalire** [comment]
perfect TLS is now working on Java6
