### ISSUE TITLE
RSASSA-PSS change breaks BCRSAPrivateKey Java serialization

### ISSUE THREAD

**Issue by lipnitsk** [bcgit/bc-java#682]
It appears that a309b4f573eb4a1314649480541cecf2da11827a broke Java serialization (for both RSA and RSASSA-PSS keys). This simple test case proves it:

```diff
diff --git a/prov/src/test/java/org/bouncycastle/jce/provider/test/RSATest.java b/prov/src/test/java/org/bouncycastle/jce/provider/test/RSATest.java
index 58043eb0f..9cef962ad 100644
--- a/prov/src/test/java/org/bouncycastle/jce/provider/test/RSATest.java
+++ b/prov/src/test/java/org/bouncycastle/jce/provider/test/RSATest.java
@@ -753,6 +753,10 @@ private void testPSSKeys()
 
         isTrue("RSASSA-PSS".equals(privateKey.getAlgorithm()));
 
+        privateKey = (PrivateKey)serializeDeserialize(kp.getPrivate());
+
+        isTrue("RSASSA-PSS".equals(privateKey.getAlgorithm()));
+
         SubjectPublicKeyInfo subKey = SubjectPublicKeyInfo.getInstance(publicKey.getEncoded());
 
         isTrue(null == subKey.getAlgorithm().getParameters());
```

Results in:
```
> Task :prov:RSATest.main()
java.lang.NullPointerException
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.BCRSAPrivateKey.getAlgorithm(BCRSAPrivateKey.java:79)
	at org.bouncycastle.jce.provider.test.RSATest.testPSSKeys(RSATest.java:758)
	at org.bouncycastle.jce.provider.test.RSATest.performTest(RSATest.java:721)
	at org.bouncycastle.util.test.SimpleTest.perform(SimpleTest.java:180)
	at org.bouncycastle.util.test.SimpleTest.runTest(SimpleTest.java:203)
	at org.bouncycastle.util.test.SimpleTest.runTest(SimpleTest.java:198)
	at org.bouncycastle.jce.provider.test.RSATest.main(RSATest.java:990)
RSATest: Exception: java.lang.NullPointerException
```

**Comment by bcgit** [comment]
Should be fixed in https://www.bouncycastle.org/betas 166b03 or later.

**Comment by bcgit** [comment]
Official patch release now at:
https://downloads.bouncycastle.org/java/bcprov-jdk15on-165.01.jar
https://downloads.bouncycastle.org/java/bcprov-debug-jdk15on-165.01.jar
https://downloads.bouncycastle.org/java/bcprov-ext-jdk15on-165.01.jar
https://downloads.bouncycastle.org/java/bcprov-ext-debug-jdk15on-165.01.jar

**Comment by lipnitsk** [comment]
@bcgit, thank you! Will try it once it shows up at https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on (we use gradle to manage dependencies)

**Comment by bcgit** [comment]
Would you try it locally first. We can only upload a release once to the maven repository. Thanks.

**Comment by lipnitsk** [comment]
@bcgit makes sense. I have just downloaded [bcprov-jdk15on-165.01.jar](https://downloads.bouncycastle.org/java/bcprov-jdk15on-165.01.jar) and verified that our code works with 1.64, is broken with 1.65, but is fixed with 1.65.01.

One question. Is there a git branch for 1.65.01? If so, could you please point me to it? Would be good to have visibility into the changes that went into it.

**Comment by msohn** [comment]
Could you please publish 1.65.01 on Maven central ?

**Comment by msohn** [comment]
Several Eclipse projects depend on 1.65 and might be affected, we are close to rampdown for the next simultaneous release and would appreciate if you could make 1.65.01 available on Maven central. Otherwise we'll rollback to 1.64 and also have to revert https://git.eclipse.org/r/#/c/161962/ in JGit which depends on a new feature introduced in 1.65.

**Comment by dghbc** [comment]
Sure, it should appear within 24 hours.

**Comment by dghbc** [comment]
@lipnitsk the principal commit was in: https://github.com/bcgit/bc-java/commit/789a03bba275fc555266c3177a6d7afd4ae16de5#diff-327453b17606a3ef48c1cf7aa58bdc05

we ended up just adding a new field to preserve the state as it reduced the compatibility issues.

**Comment by dghgit** [comment]
Now closed.
