### ISSUE TITLE
[Version 1.65] Serialized RSA private key does not maintain its algorithm causing 'getAlgorithm()' NPE

### ISSUE THREAD

**Issue by lgoldstein** [bcgit/bc-java#684]
Version 1.65

Serializing a `RSAPrivateKey` implemented via `BCRSAPrivateCrtKey` does not restore its algorithm after being de-serialized:

When examining the differences between version 1.64 and 1.65 the following difference emerges:

* In version 1.64

```java
public String getAlgorithm() {
    return "RSA";
}
```

*  In version 1.65

```java
public String getAlgorithm()
    {
        if (algorithmIdentifier.getAlgorithm().equals(PKCSObjectIdentifiers.id_RSASSA_PSS))
        {
            return "RSASSA-PSS";
        }
        return "RSA";
    }
```

However - `algorithmIdentifier` is defined as

```java
protected transient AlgorithmIdentifier algorithmIdentifier = BCRSAPublicKey.DEFAULT_ALGORITHM_IDENTIFIER;
```

which means that in a serialization and then subsequent de-serialization its value will be _null_ and thus cause an NPE when `getAlgorithm` is called.

Note that removing `transient` definition is not enough since `AlgorithmIdentifier` is not `Serializable`.

**Comment by lgoldstein** [comment]
Note this also affects `getEncoded()` since in version 1.65 it is defined as

```java
return KeyUtil.getEncodedPrivateKeyInfo(algorithmIdentifier, new RSAPrivateKey(getModulus(), getPublicExponent(), getPrivateExponent(), getPrimeP(), getPrimeQ(), getPrimeExponentP(), getPrimeExponentQ(), getCrtCoefficient()));
```

which means that if `algorithmIdentifier` is deserialized as _null_ will return null.

**Comment by lgoldstein** [comment]
Here is a stack trace of an attempt to sign data using a de-serialized RSA key

```
java.lang.NullPointerException
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.BCRSAPrivateKey.getAlgorithm(Unknown Source)
	at sun.security.rsa.RSAKeyFactory.engineTranslateKey(RSAKeyFactory.java:184)
	at sun.security.rsa.RSAKeyFactory.toRSAKey(RSAKeyFactory.java:111)
	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:106)
	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:99)
	at java.security.Signature$Delegate.init(Signature.java:1155)
	at java.security.Signature$Delegate.chooseProvider(Signature.java:1115)
	at java.security.Signature$Delegate.engineInitSign(Signature.java:1179)
	at java.security.Signature.initSign(Signature.java:530)
```

**Comment by bcgit** [comment]
This should now be fixed. See https://www.bouncycastle.org/betas 166b03 or later

**Comment by lgoldstein** [comment]
Thx - will check it in the next few days...

**Comment by lgoldstein** [comment]
Yes - the published beta versions seem to have fixed this issue
