### ISSUE TITLE
module-info missing `provides` declarations

### ISSUE THREAD

**Issue by AlanBateman** [bcgit/bc-java#687]
bcprov-jdk15on-165.jar contains the service configuration META-INF/services/java.security.Provider so that the security providers can be discovered when the JAR fie is on the class path. The module declaration doesn't have the equivalent `provides` so it will not be resolved unless some other module explicitly requires it or --add-modules is used to add it as a root on the command line. There are also 3 `opens` clauses in the module declaration that open packages to java.base that may not be needed.

**Comment by dghgit** [comment]
The provides statement has been added to the current beta at https://www.bouncycastle.org/betas

**Comment by dghgit** [comment]
Closed as now in current release.
