### ISSUE TITLE
no such algorithm: 1.2.156.10197.1.301.3.2.1 for provider BC

### ISSUE THREAD

**Issue by zhanglei-1987** [bcgit/bc-java#688]
```
JceCMSContentEncryptorBuilder encryptorBuilder = new JceCMSContentEncryptorBuilder(GMObjectIdentifiers.sm2encrypt_with_sm3);
		encryptorBuilder.setProvider( new BouncyCastleProvider());

OutputEncryptor outputEncryptor = encryptorBuilder.build();
```

org.bouncycastle.cms.CMSException: cannot create key generator: no such algorithm: 1.2.156.10197.1.301.3.2.1 for provider BC
	at org.bouncycastle.cms.jcajce.EnvelopedDataHelper.createKeyGenerator(Unknown Source)
	at org.bouncycastle.cms.jcajce.JceCMSContentEncryptorBuilder$CMSOutputEncryptor.<init>(Unknown Source)
	at org.bouncycastle.cms.jcajce.JceCMSContentEncryptorBuilder.build(Unknown Source)

**Comment by bcgit** [comment]
That's a signature algorithm. What exactly are you trying to do?

**Comment by zhanglei-1987** [comment]
> That's a signature algorithm. What exactly are you trying to do?

Sorry, I copied the wrong code, I want to express the consciousness of JceCMSContentEncryptorBuilder does not support GM algorithm

**Comment by Gsealy** [comment]
@zhanglei-1987 GM standard is extend PKCS7 v1.5 not CMS, [see GM/T 0010](https://github.com/guanzhi/GM-Standards/blob/master/GMT%E6%AD%A3%E5%BC%8F%E6%A0%87%E5%87%86/GMT%200010-2012%20SM2%E5%AF%86%E7%A0%81%E7%AE%97%E6%B3%95%E5%8A%A0%E5%AF%86%E7%AD%BE%E5%90%8D%E6%B6%88%E6%81%AF%E8%AF%AD%E6%B3%95%E8%A7%84%E8%8C%83.pdf). object's (data, SignedData, EnvelopedData, etc.) oid is different. so you should implement by your self.

**Comment by Gsealy** [comment]
@winfriedgerlach yes, pls close
