### ISSUE TITLE
X500Name is not RDN order aware

### ISSUE THREAD

**Issue by partheinstein** [bcgit/bc-java#693]
```
(new X500Name("serialNumber=1234,cn=bla")).equals(new X500Name("cn=bla,serialNumber=1234"))
```
This is true but I would have expected it to be false since X500Name is RDN**Sequence**. 

It is false with javax.security.auth.x500.X500Principal:

```
(new X500Principal("serialNumber=1234,cn=bla")).equals(new X500Principal("cn=bla,serialNumber=1234"))
```

**Comment by bcgit** [comment]
Hi, this is a common misconception, and one I am very sympathetic with. For a full, and somewhat humorous,  discourse on how this came about see:

https://www.cs.auckland.ac.nz/~pgut001/pubs/x509guide.txt

X500Name does allow a variety of styles though to enable people to enforce the interpretation they need, in some cases these are mandated, so it helps to be flexible. To create ones which will always evaluate by order you can use:

new X500Name(BCStrictStyle.INSTANCE, "serialNumber=1234,cn=bla");

**Comment by partheinstein** [comment]
Thank you @bcgit. That link was a humorous read indeed.
