### ISSUE TITLE
Add support for ecdsa-sha2-nistp521 in OpenSSHPublicKeyUtil

### ISSUE THREAD

**Issue by matelang** [bcgit/bc-java#696]
On bouncy castle version 1.65 if I try to parse an SSH public key of type `ecdsa-sha2-nistp521` I get an Illegal Argument Exception with the following message: 
```
java.lang.IllegalArgumentException: unable to derive ssh curve name for org.bouncycastle.math.ec.custom.sec.SecP521R1Curve
```

I checked in source code and it seems that there is support just for nistp256. The exception is thrown from line 91 on my version of bc.

Can we add support for nistp521?

**Comment by dghgit** [comment]
This has now been done and is in the latest beta on https://www.bouncycastle.org/betas.
