### ISSUE TITLE
wrong description in pom.xml for bc*-jdk15on

### ISSUE THREAD

**Issue by tony--** [bcgit/bc-java#697]
Description: The Bouncy Castle Java API for handling the OpenPGP protocol. This jar contains the OpenPGP API for JDK 1.5 to JDK 1.8. The APIs can be used in conjunction with a JCE/JCA provider such as the one provided with the Bouncy Castle Cryptography APIs.

Instead of "JDK 1.5 to JDK 1.8" this should say something like "JDK 1.5 and up".

See the description fields in:
https://search.maven.org/artifact/org.bouncycastle/bcpg-jdk15on/1.65/jar
https://search.maven.org/artifact/org.bouncycastle/bcpkix-jdk15on/1.65/jar
https://search.maven.org/artifact/org.bouncycastle/bcprov-jdk15on/1.65/jar

**Comment by dghbc** [comment]
Good point. I've changed the generator to say "JDK 1.5 and up". Thanks.
