### ISSUE TITLE
Maven repo is not up to date

### ISSUE THREAD

**Issue by florentinRB** [bcgit/bc-java#699]
https://repo1.maven.org/maven2/org/bouncycastle/
The latest versions are 1.46

**Comment by gaellalire** [comment]
You have to look only for artifact ending with -jdk15on (or -jdk15to18 if you target JDK7 and older).

**Comment by florentinRB** [comment]
Thanks. I already noticed and recently tested it.
I think there is potential to update the notes on the maven repo ([bcprov-jdk15](https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15)) and maybe the homepage as well 🙂
