### ISSUE TITLE
XMSS/XMSS^MT testfiles are using deprecated StateAwareSignature-class

### ISSUE THREAD

**Issue by java-crypto** [bcgit/bc-java#701]
I'm testing PQC-Signatures and worked with XMSSTest.java and XMSSMTTest.java (found in folder https://github.com/bcgit/bc-java/blob/master/prov/src/test/java/org/bouncycastle/pqc/jcajce/provider/test/) but the StateAwareSignature-class is **deprecated since version 1.64**.

Could you kindly share some examples with the new **extraKeyShard()** method as I cannot find any documentation and/or examples?
Thanks in advance.

Best regards
Michael

**Comment by bcgit** [comment]
org.bouncycastle.pqc.jcajce.provider.test.XMSSTest.testShardedKeyExhaustion() is probably a good place to start.

**Comment by dghgit** [comment]
Closing as resolved.
