### ISSUE TITLE
BUG: bcprov-jdk15on v1.65 does not work in OSGi environments

### ISSUE THREAD

**Issue by xipki** [bcgit/bc-java#702]
Tested in the OSGi environment apache-karaf 4.2.8 and got the error message ` java.lang.NoClassDefFoundError: javax/security/auth/Destroyable`. The missing class `Destroyable` should be introduced to the class `org.bouncycastle.jcajce.provider.symmetric.util.BCPBEKey` in the version 1.65, but not considered in the OSGi headers. 

For the test I modified the MANIFEST.MF file and it worked. Please find attached the original and patched MANIFEST.MF file.

[original MANIFEST.MF](https://github.com/bcgit/bc-java/files/4568290/MANIFEST.MF.orig.txt)
[patched MANIFEST.MF](https://github.com/bcgit/bc-java/files/4568291/MANIFEST.MF.patched.txt)

**Comment by bcgit** [comment]
Thanks for the report. Config typo... please try the latest beta https://www.bouncycastle.org/betas 166b05 or later. I think the config is now correct for bnd, and should stay that way now that we've moved to a version of it that is on this side of the dinosaur era...

**Comment by xipki** [comment]
Thanks for the bug fix. Just tested bcprov 166b05, and it worked. :+1:
