### ISSUE TITLE
bcmail not compatible with Karaf (OSGi)

### ISSUE THREAD

**Issue by elmuerte** [bcgit/bc-java#704]
The registration of CommandInfos in [SMIMESignedGenerator](https://github.com/bcgit/bc-java/blob/master/mail/src/main/java/org/bouncycastle/mail/smime/SMIMESignedGenerator.java#L123) produces problems.
In Apache Karaf this results in these commands being registered with the last OSGi bundle that was loaded with commands registered via a `META-INF/mailcap` file. With as result that the content handler class of those commands cannot be loaded due to the nature of OSGi class loaders.

Suggested fix is for bcmail to also make use of a `META-INF/mailcap` file. This ensures proper registration of the content handlers in an OSGi environment.

**Comment by elmuerte** [comment]
Additionally, the [ContentSigner](https://github.com/bcgit/bc-java/blob/master/mail/src/main/java/org/bouncycastle/mail/smime/SMIMESignedGenerator.java#L616) keeps registering the commands for every message which is signed. This causes a memory leak.

**Comment by bcgit** [comment]
Thanks for the report. Yes, can see how that would really suck. Sorry. I think it's now fixed, try the latest on https://www.bouncycastle.org/betas (166b05 or later) and let us know how you go. I think this one will also fix  issue #702 (although you may not have seen it yet).

**Comment by elmuerte** [comment]
I've checked the changed code. That does take care of the memory leak. But it does not fix the problem with the classes not being found in a OSGi environment. I have not checked out other OSGi runtimes handle the javax.activation complications. But Karaf does not really handle command registration via CommandMap api calls really well.

The real problem is obviously the whole javax.activation framework and how it is deeply tied into by Java Mail. It is simply a really bad construction for modern day Java. For OSGi the problem has to do with the runtime class loading being done in the CommandMap. The `CommandMap.createDataContentHandler` might not be using the correct ClassLoader to instantiate the BC handler classes when they are registered via `MailcapCommandMap.addMailcap`. 
In Karaf `mailcap` files will result in proper registrations where the classes can be instantiated via the right ClassLoader. But not for the `addMailcap` calls, because when these are executed it is not known which OSGi bundle is executing the code.

It briefly checked the Eclipse OSGi runtime handles the javax.activation complications. But it looks like they also used the Geronimo implementation of that framework, thus they also would suffer from the memory leak, which is now fixed. But I don't know if it will properly load the smime content handlers when they are registered via `addMailcap`.

PS. I also logged an issue to make the implementation in Karaf more resilient: https://issues.apache.org/jira/browse/SM-4383

**Comment by bcgit** [comment]
I added a META-INF/mailcap to the jar as well. I have to admit I haven't had a chance to check what Karaf does with it yet, did you have a chance to try the beta jar? I might have fallen for the old semi-colon in the wrong place trick...

**Comment by elmuerte** [comment]
I haven't tried the beta yet, I will probably take it for a test run tomorrow. These OSGi environment are nice in concept, but they are basically incredible complex dynamic ClassLoader constructions. Which results in hard to find and debug issues at runtime. I want to pace myself with it so I don't go insane ;)

**Comment by elmuerte** [comment]
Tested with 1.66b05 and confirmed that registration within Karaf is proper; and that no memory leak occurs. 👍
So I'm closing this issue.

**Comment by bcgit** [comment]
Thanks! It's good to know it's now resolved.
