### ISSUE TITLE
bctls-jdk15on_1.65: AbstractTlsContext#exportKeyingMaterial() checks for securityParametersConnection for null

### ISSUE THREAD

**Issue by cmeng-git** [bcgit/bc-java#707]
The method AbstractTlsContext#exportKeyingMaterial()  checks  securityParametersConnection
for null and throws IllegalStateException. However  securityParametersConnection is always set to null in method handshakeComplete(). 
May be should consider to use getSecurityParameters() instead.

```
    public byte[] exportKeyingMaterial(String asciiLabel, byte[] context_value, int length)
    {
        SecurityParameters sp = getSecurityParametersConnection();
        if (null == sp)
        {
            throw new IllegalStateException("Export of key material unavailable before handshake completion");
        }
        if (!sp.isExtendedMasterSecret())
        {
            /*
             * RFC 7627 5.4. If a client or server chooses to continue with a full handshake without
             * the extended master secret extension, [..] the client or server MUST NOT export any
             * key material based on the new master secret for any subsequent application-level
             * authentication. In particular, it MUST disable [RFC5705] [..].
             */
            throw new IllegalStateException("cannot export keying material without extended_master_secret");
        }

        if (TlsUtils.isTLSv13(sp.getNegotiatedVersion()))
        {
            // TODO[tls13]
            TlsSecret exporter_secret = null; // exporter_master_secret

            return exportKeyingMaterial13(exporter_secret, asciiLabel, context_value, length);
        }

        byte[] seed = TlsUtils.calculateExporterSeed(sp, context_value);

        return TlsUtils.PRF(sp, sp.getMasterSecret(), asciiLabel, seed, length).extract();
    }

```

```
    synchronized void handshakeComplete(TlsPeer peer, TlsSession session) throws IOException
    {
        if (null == securityParametersHandshake)
        {
            throw new TlsFatalAlert(AlertDescription.internal_error);
        }

        this.session = session;

        securityParametersConnection = securityParametersHandshake;

        peer.notifyHandshakeComplete();

        securityParametersHandshake = null;
    }
```

**Comment by peterdettman** [comment]
I think you're misreading something. `securityParametersConnection` begins as null, then gets set to the handshake parameters once a handshake successfully completes. It is never reset to null.

If you are seeing NPE it is more likely to be coming from the master secret having been nulled after `handshakeComplete(...)` returns. It is intended that client code export keying material (only) during the "peer.notifyHandshakeComplete()" callback.

**Comment by cmeng-git** [comment]
Please refer to https://github.com/cmeng-git/atalk-android class DtlsPacketTransformer.java

Yes you are right, the problem is due to master secret being null. I incorrectly reported the problem.

During the aTalk implementation and testing of DTLS features, aTalk also faced the exact same problem as reported in [DTLS Can't exportKeyingMaterial after handshake completed (DTLS fails) #203](https://github.com/bcgit/bc-java/issues/203). As recommended, aTalk was trying to use the notifyHandshakeComplete() callback. 

However I found that the parameter masterSecret derived during the callback, its 'byte[] data' array contains no data?; but not the case when the masterSecret is retrieved from the sessionParameters.
Personally no sure if the 'byte[] data' is actually being used. Coupled that aTalk DTLS implementation flow also uses byte[] keyingMaterial to derive the srtpTransformer.

To avoid major changes to the aTalk (forked from jitsi) source, I decided to use the masterSecret from the sessionParameters, and call via below method with tlsSecret as pass-in parameter.
> TlsUtils.PRF(context, tlsSecret, asciiLabel, seed, length).extract();

Following up with your comment, I just realize that the problem is not due to getSecurityParametersConnection(), but getSecurityParametersHandshake() as used in
> PRF(context.getSecurityParametersHandshake(), secret, asciiLabel, seed, length);

May be this is where it should be changed to i.e. context.getSecurityParametersConnection()

aTalk was changed to call using
> TlsUtils.PRF(sp, tlsSecret, asciiLabel, seed, length).extract();

**Comment by cmeng-git** [comment]
I retest the callback notifyHandshakeComplete() for both the TlsClientImpl and TlsServerImp, and confirmed that 'byte[] data' does contain the data. Not sure if the previous problem experienced was due to my incorrect test setup.

**Comment by peterdettman** [comment]
Happy to hear it.

**Comment by cmeng-git** [comment]
```
Following up with your comment, I just realize that the problem is not due to 
getSecurityParametersConnection(),
But getSecurityParametersHandshake() as used in

PRF(context.getSecurityParametersHandshake(), secret, asciiLabel, seed, length);

May be this is where it should be changed to i.e. context.getSecurityParametersConnection()
```

Did you verify and confirm the correctness on the comment I have on:
> PRF(context.getSecurityParametersHandshake(), secret, asciiLabel, seed, length);

**Comment by peterdettman** [comment]
TlsUtils.PRF(TlsContext, ...) just calls TlsUtils.PRF(SecurityParameters, ...) with the handshake SecurityParameters. If you for some reason want to use the connection SecurityParameters instead, you would just call the other PRF method directly.

However, during a notifyHandshakeComplete call, both SecurityParameters reference the same instance anyway (neither is null), so I'm unclear why you thought there was a problem.

**Comment by cmeng-git** [comment]
There is no problem when an app calls the method during the notifyHandshakeComplete() callback.
However the method is defined as general method, a developer may not aware this method must never be used outside notifyHandshakeComplete();  as context.getSecurityParametersHandshake() will return null. Actually aTalk fallen into this trap during srtp earlier implementation when notifyHandshakeComplete() was not used.

May be the team would consider to change context.getSecurityParametersConnection instead so the method works at all time.

```
    public static TlsSecret PRF(TlsContext context, TlsSecret secret, String asciiLabel, byte[] seed, int length)
    {
        return PRF(context.getSecurityParametersHandshake(), secret, asciiLabel, seed, length);
    }
```

**Comment by peterdettman** [comment]
We have now deprecated this method to avoid any confusion.
