### ISSUE TITLE
Generating RSA private key with specified lengths of prime factors p1,p2,q1,q2 

### ISSUE THREAD

**Issue by yeongk** [bcgit/bc-java#708]
Per FIPS186-4 (C.10), we need to generate RSA private keys based on specified bit lengths of prime factors p1, p2, q1, q2. Is it feasible to do it with Bouncy Castle?

A related question, Bouncy Castle expose the API that computes prime factors p and q?

**Comment by dghgit** [comment]
BC does not use Auxiliary Primes for generating RSA keys, but instead uses method A, outlined on page 51 of FIPS PUB 186-4. 

The key generation code is in org.bouncycastle.crypto.fips.RsaKeyPairGenerator. The prime generation code is not directly exposed, although the supporting functions in org.bouncycastle.math are.
