### ISSUE TITLE
BCv1.65 - RSA Key Generation of odd bit length always fails

### ISSUE THREAD

**Issue by Masa2k** [bcgit/bc-java#711]
Dear BC team,

When trying to generate a RSA key pair of odd bit length, the following check fails when trying to generate 'q' prime number:

    protected BigInteger chooseRandomPrime(int bitlength, BigInteger e, BigInteger sqrdBound)
       [..]
            if (p.multiply(p).compareTo(sqrdBound) < 0)
            {
                continue;
            }

When starting generation p and q sizes are computed and, for example, for 1001-bits keypair, p size = 501-bits and q = 1001-501 = 500-bits.
This check always fails for 'q' prime number, because q size is too small and I suppose the multiplication can never be higher than 'sqrdBound' value

Not sure how it was working before, and when exactly it was "broken", but **on BCv1.55 such odd bit length RSA key size generation was seemingly working fine**

Actually, I'm not a pure crypto specialist and I'm not sure that such odd key lengths makes any sense for RSA... If it makes no sense, I would suggest to gracefully reject right away.

Thank you.

**Comment by dghgit** [comment]
It's a bit of an odd one, but yes I'd stay away from odd bit lengths. The tests are there to ensure the validity of the keys, I don't think watering them down to allow for this would turn out to be a long term benefit. Sorry.
