### ISSUE TITLE
JCE cannot authenticate the provider BC 

### ISSUE THREAD

**Issue by bigbang489** [bcgit/bc-java#712]
In sapjvm runtime, we got the error: JCE cannot authenticate the provider BC
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:330)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:263)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:318)
	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:386)
	at java.util.jar.JarFile.getInputStream(JarFile.java:453)
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:468)
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:363)
	at javax.crypto.JarVerifier.verify(JarVerifier.java:289)
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190)
	at javax.crypto.Cipher.getInstance(Cipher.java:652)

**"jarsigner -verify" result: **
...
sm       625 Sat May 16 11:57:32 ICT 2020 org/bouncycastle/x509/util/StreamParsingException.class

      >>> Signer
      X.509, CN=Legion of the Bouncy Castle Inc., OU=Java Software Code Signing, O=Sun Microsystems Inc
      [certificate expired on 4/25/20 2:00 PM]
      X.509, CN=JCE Code Signing CA, OU=Java Software Code Signing, O=Sun Microsystems Inc, L=Palo Alto, ST=CA, C=US
      [certificate expired on 4/25/20 2:00 PM]
      [Invalid certificate chain: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]

      [entry was signed on 5/16/20 9:00 AM]
...
jar verified.

Warning:
This jar contains entries whose signer certificate has expired.
This jar contains entries whose certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**I noticed that the signer certificate has already expired in 04/25/2020. I think it may be the root cause of the issue. May I know if you have a plan to re-new the signer certificate? and the date for next release?** this issue is urgent for me, because it happening in our production. Many thanks

**Comment by bcgit** [comment]
Which version of bcprov is this on?

**Comment by bigbang489** [comment]
I am using version 1.60

**Comment by bcgit** [comment]
The full name of the jar would usually help, but I don't think we had a 15to18 release back then. The exception above is usually caused by a class loader issue, if it was related to the expiry of the old JCE certificate you would have seen it weeks ago - you'd also need to be running the last public release of the Oracle JVM for Java 7. Has the way the jar is being loaded changed recently?

The jar is signed with 2 JCE signing certificates. Neither of these are present in the cacerts file though so jarsigner will never be able to identify them.

**Comment by bigbang489** [comment]
This is the build I used:
<dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-ext-jdk15on</artifactId>
      <version>1.60</version>
</dependency>

I tested on 1.65, it failed with same error. I use Oracle JDK for development and it works well, but In our production, we use SAP JVM, it failed.
I appreciate if you give me an explanation on how the class loader may cause the error
Many thanks

**Comment by zalizko** [comment]
We have similar issue with upgrading  org.bouncycastle:bcprov-jdk15on to 1.60:
`java.lang.SecurityException: JCE cannot authenticate the provider BC`

**Comment by dghgit** [comment]
Try the jdk15to18 release.

**Comment by dghgit** [comment]
Closing as resolved.
