### ISSUE TITLE
Commit e5b8a305 puts too much GC pressure on G1

### ISSUE THREAD

**Issue by fluxroot** [bcgit/bc-java#713]
Our application's memory allocation profile is mainly driven by scrypt. We have upgraded from BC 1.60 to 1.64 for some time now and we're seeing too many garbage collection cycles coming from 16MB allocations. We tracked down these allocations to commit e5b8a305 where you change V from a two-dimensional array to a one-dimensional array.

What is the reasoning behind this change? Could it be reverted?

We currently look into several options like optimizing G1 to this new allocation pattern or switching completely to another garbage collector. However, our preferred option would be to revert this commit.

**Comment by peterdettman** [comment]
The change was made to reduce total memory usage, in reaction to OutOfMemory reports on mobile devices. It replaces what was N separate (small) allocations with a single allocation of the same total storage, but since each allocation has some memory overhead this substantially reduces the total memory footprint.

I would also have expected that to be kinder to the GC in general. Do you have some insight as to why you think this is causing increased GC cycles?

**Comment by fluxroot** [comment]
I see. I'm not an expert on scrypt or garbage collection. But as I understand, G1 has some issues with short-lived large allocations.

In our case, we have a heap size of 4GB and a G1 region size of 1MB. Allocating 16MB blocks means that G1 handles them as Humongous Allocations. Our GC logs show that short-lived Humongous Allocations causes G1 to Stop-The-World more often.

We ran one of our use cases with the latest Bouncy Castle version twice. The first time we ran our application with the current master and the second time we reverted commit e5b8a305. As you see from the images, reverting commit e5b8a305 has a major impact on Young GC.

Short-lived small allocations are far better for G1. We know that we are optimizing here for G1 and maybe reverting this commit makes other use cases worse. However, seeing that G1 is the default GC on Java 11 (LTS), we would very much like to see this commit reverted.

**Comment by fluxroot** [comment]
Memory (latest): ![Memory-1dim-Large-Allocations](https://user-images.githubusercontent.com/247365/82544844-01eca480-9b56-11ea-992d-16e765a9b9fd.png)
Memory (commit reverted): ![Memory-2dim-Small-Allocations](https://user-images.githubusercontent.com/247365/82544845-01eca480-9b56-11ea-806d-5e3d85d217c4.png)
GC Time (latest): ![GC-Time-1dim-Large-Allocations](https://user-images.githubusercontent.com/247365/82544831-0022e100-9b56-11ea-989b-b8928c0cecc6.png)
GC Time (commit reverted): ![GC-Time-2dim-Small-Allocations](https://user-images.githubusercontent.com/247365/82544837-01540e00-9b56-11ea-873f-59f40c41db06.png)

**Comment by peterdettman** [comment]
I've pushed a change for SCrypt that tries to strike a balance by chunking the memory allocations into 32KiB chunks (somewhat arbitrary but tested well). Once the change mirrors to GitHub (may take a day), please test it out and let us know whether it addresses your issue.

@schildbach This change affects SCrypt memory allocation. I think it should still be fine for the OOM issues you reported last year, but it might be best if you can test the changes once they're available.

**Comment by fluxroot** [comment]
Holy cow, this change takes GC activity to the level it was before. Nice work!

Thanks for taking the time to fix this issue.

![Memory-fixed](https://user-images.githubusercontent.com/247365/82644665-fa8ad100-9c11-11ea-862a-85756139030f.png)
![GC-Time-fixed](https://user-images.githubusercontent.com/247365/82644669-fbbbfe00-9c11-11ea-9920-68c4f8168e9e.png)

**Comment by peterdettman** [comment]
Great, thanks for confirming. I still want to hear back from @schildbach before closing this out, but I am not expecting there to be problems.

**Comment by schildbach** [comment]
So originally it used to be n allocations of r*32 bytes, then with e5b8a305 it went down to 1 allocation of n*r*32 bytes, and now its n*r/1024 allocations of 32*1024 bytes?

**Comment by schildbach** [comment]
For my `n = 65536, r = 8` usecase that's `512` allocations. Sounds easily doable.

**Comment by peterdettman** [comment]
@schildbach The allocations can be a little smaller if r is not a power of 2, but that's basically right, and yes, in your case it would be 512 allocations of 32KiB.
