### ISSUE TITLE
BC-Provider-1.5.7 performance issues with Java11

### ISSUE THREAD

**Issue by navjotsingh83** [bcgit/bc-java#715]
Hi,

We have been using bc-provider-jdk1.5.7 from the last two years in our project with openjdk version "1.8.0_191"

We use it for RSA decryption, SHA-256, MGF1 with PKCS8 encoded private key and there have been no performance issues whatsoever.

Now, in our recent release, we see that for the same load, the CPU cycles went up from the range of 68-69% to 80-81%, which is a substantial increase.

As, the bouncy castle code is fairly stable and our requirements have not change even a bit, so there is no code change in the application side. **Only change is that we have moved to openjdk-11.05**

We think that might be causing the problem. Our assumption is based on the fact that we had seen massive improvements two years back (when we just started using bcprov), the moment we move from Java1.7 to Java1.8 due to improved implementation of BigInteger. So not sure if any recent change in Java11 has caused the performance to drop.

Unfortunatley, I do not have any more analysis to share as of now as we cannot patch the current release again with Java8 and re-test since there are massive dependencies of the current application software on Java11.

Have you seen similar issues being reported?

**Comment by dghbc** [comment]
This is the first we've heard of it. Is it connected with BigInteger performance? Changes to the garbage collector sometimes feature as well.

**Comment by navjotsingh83** [comment]
Well, I just took a JFR and analyzed further. All the method profiling points to BigInteger only.

_The most sampled method was MutableBigInteger.add(MutableBigInteger), with 4.52 % of possible samples during a 30 s window of the recording.
The following methods are the most interesting candidates for code optimization: 
•java.math.MutableBigInteger.add(MutableBigInteger) (4.52 %) 13/07/2020, 6:26:02 PM – 6:26:32 PM_

Also, I tested with bcprov-1.6.6 (latest one), but % increase in CPU is still present. The above run where JFR is collected was with bcprov-1.5.7.

The only major change when I compare with previous runs (where all was fine) was the movement to Java11 from Java8.

**Comment by peterdettman** [comment]
That's not much to go on. We can't even know if that is related to BC code at all.

Are you able to run your application under a profiler (e.g. VisualVM) and send us the results? Of course we are interested in any hotspots you might identify in BC code, or if BigInteger methods are where the time is spent, then we would want to see backtraces into BC code to see if there's anything we can do about it.

We're also happy to do the profiling ourselves if you are able to send us some sample code that demonstrates substantially worse performance on openjdk11 than openjdk8.

**Comment by navjotsingh83** [comment]
Here's the backtrace for the BigInteger Method.. See if it helps. I have omitted our application code from the backtrace...

_void java.math.MutableBigInteger.add(MutableBigInteger)	
MutableBigInteger java.math.MutableBigInteger.modInverse(MutableBigInteger)	
MutableBigInteger java.math.MutableBigInteger.mutableModInverse(MutableBigInteger)	
BigInteger java.math.BigInteger.modInverse(BigInteger)	
byte[] org.bouncycastle.crypto.engines.RSABlindedEngine.processBlock(byte[], int, int)	
byte[] org.bouncycastle.crypto.encodings.OAEPEncoding.decodeBlock(byte[], int, int)	
byte[] org.bouncycastle.crypto.encodings.OAEPEncoding.processBlock(byte[], int, int)	
byte[] org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.getOutput()	
byte[] org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(byte[], int, int)	
byte[] javax.crypto.Cipher.doFinal(byte[])
...
...
_

**Comment by peterdettman** [comment]
Is it possible your new release deployed an updated RSA key that is larger than for the previous release? e.g. 1024 bit key replaced by 2048 bit key. A decrease in BigInteger.modInverse performance seems unlikely to me, but the result is naturally explained if it involves a larger RSA modulus.

**Comment by navjotsingh83** [comment]
Unfortunately that's not the case. We have not done any change from the day when we started with decryption using bouncy castle.

I have some test results for you. I extracted the decryption code from my application into a separate JAVA program.  I took a working encrypted text + private key and hardcoded the same in the program. Then I build and ran the same with openjdk-1.8.0.191 and openjdk-11.0.5 and here are the results.

For 1000 decryptions (in a loop with same encrypted message and private key)
openjdk-1.8.0.191  - Time taken is 2839ms
openjdk-11.0.5 - Time taken is 3562ms
Increase of 25% in Java11

For 10000 decryptions:
openjdk-1.8.0.191  - Time taken is 19833ms 
openjdk-11.0.5 - Time taken is 21656ms
Increase of 9% in Java11

For 100000 decryptions:
openjdk-1.8.0.191  - Time taken is 216394ms
openjdk-11.0.5 - Time taken is 220879ms
Increase of 2% in Java11

So, the test results show that Java11 based test take more time than Java8 based tests. However, the difference is reducing when the number of iterations increases.

In our production tests, there are 1750 decryptions happening per second and in Java8 based release the CPU consumption of the node performing these tests was around 69%. However with Java11 based release the CPU consumption increased to around 80%

Attached is the sample code so that you can have a look.
[decryption.zip](https://github.com/bcgit/bc-java/files/4923140/decryption.zip)

**Comment by navjotsingh83** [comment]
Hi,

I did some more tests. The problem with my earlier approach was that the test was run in an Oracle VMBox setup on my laptop so obviously the results will be dependent on the load on the host (my lappie). So, I ran the same program with a small enhancement - i.e. the ability to specify how many decryptions I want to do in a set and how many times I want to execute that set.

I ran the above program on the production test bed with JDK-1.8.0.191, JDK-11.0.5 and JDK-14.0.1. Here are the results


Number   of Decryptions (Set Size) | Num of Set   repetitions | Avg time in ms   taken in Java8 | Avg time in ms   taken in Java11 | Avg time in ms   taken in Java14 | Java8 vs Java11 | Java14 vs Java11
-- | -- | -- | -- | -- | -- | --
1750 | 100 | 4027.62 | 4138.71 | 3979.48 | 111.09 | 159.23
10000 | 5 | 23097.2 | 23967.6 | 22925.6 | 870.4 | 1042
100000 | 1 | 230809 | 237272 | 228715 | 6463 | 8557

**Comment by navjotsingh83** [comment]
Hi @peterdettman 

Any clue on this?

Navjot

**Comment by peterdettman** [comment]
It's very interesting that there are such performance swings across the java versions, but it doesn't appear to have anything to do with BC code, so we can't spare much time to look into it further.

BTW, in the past we have written our own version of BigInteger.modPow to try and improve RSA performance, but the actual BigInteger.modPow gets its speed from intrinsic methods i.e. native code, so it's basically impossible to compete with that in pure java.

**Comment by whitingjr** [comment]
@navjotsingh83 have you tried capturing a CPU / memory allocation flame graph. Try using [async profiler](https://github.com/jvm-profiling-tools/async-profiler) for perf analysis with low intrusion. They can be very revealing and accurate.

**Comment by dghgit** [comment]
I just had a thought about this. There's a bug in Java 11, now fixed, around what happens if someone is calling "new SecureRandom()"in the provider, it's fixed in Java 14 though, it is performance related and shows up in unexpected ways. There's a partial fix in Java 11.0.8 and a full fix in the release coming on the 20th October 2020. Have you tried 11.0.8?

**Comment by navjotsingh83** [comment]
Hi @dghgit 

Thanks a  ton for the suggestion. It worked. I had tried testing with latest 11JDK weeks back, but looks like I downloaded from an archived URL so what I thought as latest actually wasn't.

Anyways, I have tested with 11.08 and the problem is solved. I think you can close this issue.

Thanks again
