### ISSUE TITLE
"sn" lookup mapped to SURNAME instead of SERIALNUMBER

### ISSUE THREAD

**Issue by e4711s** [bcgit/bc-java#717]
When upgrading from BC 1.60 to 1.65 I noticed that the lookup in BCStyle.java now maps "sn" to SURNAME.

Most notably this line was changed:
    
    DefaultLookUp.put("sn", SN);

became

    DefaultLookUp.put("sn", SURNAME);

Whereas further up in the same class SN is still defined with the same OID as SERIALNUMBER like before:

    /**
     * device serial number name - StringType(SIZE(1..64))
     * @deprecated use SERIALNUMBER or SURNAME
     */
    public static final ASN1ObjectIdentifier SN = new ASN1ObjectIdentifier("2.5.4.5").intern();

and

    /**
     * device serial number name - StringType(SIZE(1..64))
     */
    public static final ASN1ObjectIdentifier SERIALNUMBER = new ASN1ObjectIdentifier("2.5.4.5").intern();

**Comment by dghbc** [comment]
Yes, it turned out we were transgressing on RFC 4519 - for a long time no-one noticed but the arrival of e-passport standards appears to have changed that. We left the static alone, but we had to fix the interpretation.
