### ISSUE TITLE
Problem verifying a certificate

### ISSUE THREAD

**Issue by arvind5** [bcgit/bc-java#719]
I have a problem with certificate verification. The certificate looks OK. I can verify it using JRE native mechanisms, like this one:

    @Test
    public void verifyUsingStandardJre() throws Exception {

        String cIssuer = "MIICBjCCAaygAwIBAgIIEDiqn2SaqGMwCgYIKoZIzj0EAwIwVTFTMB8GA1UEAxMYTnV2b3RvbiBUUE0gUm9vdCBDQSAxMTEwMCUGA1UEChMeTnV2b3RvbiBUZWNobm9sb2d5IENvcnBvcmF0aW9uMAkGA1UEBhMCVFcwHhcNMTUwNTExMDg0MzMzWhcNMzUwNTA3MDg0MzMzWjBVMVMwHwYDVQQDExhOdXZvdG9uIFRQTSBSb290IENBIDExMTAwJQYDVQQKEx5OdXZvdG9uIFRlY2hub2xvZ3kgQ29ycG9yYXRpb24wCQYDVQQGEwJUVzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDVkEOpuyhuviaDH6xQj3faaV2Z4FvXSdwUkTiB1JjPDgv1PU0SFYtEE1W9VmI1GcOn5FAUi2/QM36DPhmPTd+qjZjBkMA4GA1UdDwEB/wQEAwICBDASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBQVkdS26vmNAQSGS2kDpI3QAmB30zAfBgNVHSMEGDAWgBQVkdS26vmNAQSGS2kDpI3QAmB30zAKBggqhkjOPQQDAgNIADBFAiEAlfxysfHDcxYDed5dmRbvHPKHLEEq9Y9PwAxoKqH7Q5kCIGfsxiLr2j9nJ9jELwXz0/VWN9PhUNdM3qmsx2JEne6p";
        String cSigCert = "MIID2zCCA4GgAwIBAgILAOvxfKjRf66wl9UwCgYIKoZIzj0EAwIwVTFTMB8GA1UEAxMYTnV2b3RvbiBUUE0gUm9vdCBDQSAxMTEwMCUGA1UEChMeTnV2b3RvbiBUZWNobm9sb2d5IENvcnBvcmF0aW9uMAkGA1UEBhMCVFcwHhcNMTgwNDMwMDc0NjQ3WhcNMzgwNDI2MDc0NjQ3WjAAMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtl6U8hTHtUDwym/PPcv3KdHeiPZLu1syGfhW1RC9v8a4OzfulGahwCOZbiu60Daqr20BndCxP8sdDyLjwSyffQb8TolCrq/vdUVj+OPuOBA+xypwEFg4m/QlR6FwzJyo6PPR2oeeAhZ/N5O8i6O1dmGxNJTvLaHT0r0TFZ32iMG5hhs8XL4kroF0OAl7JK09iAs4D0g/T17k7gNTVtf8rPzS8vhfN+JBj+k4nZ/HlG+PM23rw36T/Nk+eK4ZgBmV0LMN84++ZDuqccPSJ3zk3jvsKp/HFzvQkDqcriQsTSkY4cFqP7HR5vFhDSVeTBK7fNm3yNa/jb++q3XCx9dihQIDAQABo4IBwDCCAbwwSgYDVR0RAQH/BEAwPqQ8MDoxODAUBgVngQUCARMLaWQ6NEU1NDQzMDAwEAYFZ4EFAgITB05QQ1Q2eHgwDgYFZ4EFAgMTBWlkOjEzMAwGA1UdEwEB/wQCMAAwEAYDVR0lBAkwBwYFZ4EFCAEwHwYDVR0jBBgwFoAUFZHUtur5jQEEhktpA6SN0AJgd9MwDgYDVR0PAQH/BAQDAgUgMHAGA1UdCQRpMGcwFgYFZ4EFAhAxDTALDAMyLjACAQACAXQwTQYFZ4EFAhIxRDBCAgEAAQH/oAMKAQGhAwoBAKIDCgEAoxUwExYDMy4xCgEECgEBAQH/oAMKAQKkDzANFgUxNDAtMgoBAgEBAKUDAQEAMEEGA1UdIAQ6MDgwNgYEVR0gADAuMCwGCCsGAQUFBwIBFiBodHRwOi8vd3d3Lm51dm90b24uY29tL3NlY3VyaXR5LzBoBggrBgEFBQcBAQRcMFowWAYIKwYBBQUHMAKGTGh0dHA6Ly93d3cubnV2b3Rvbi5jb20vc2VjdXJpdHkvTlRDLVRQTS1FSy1DZXJ0L051dm90b24gVFBNIFJvb3QgQ0EgMTExMC5jZXIwCgYIKoZIzj0EAwIDSAAwRQIhAIo91KWNJlXWH4m6rGeNDXDvWYwIdb/i3AjPazGyrDc0AiB6lDa4q0f/+2c7bb8u6wJ7o18l3B5mVWTe2B33Lzrq/w==";

        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        Certificate issuer = cf.generateCertificate(new ByteArrayInputStream(Base64.getDecoder().decode(cIssuer)));
        Certificate sigCert = cf.generateCertificate(new ByteArrayInputStream(Base64.getDecoder().decode(cSigCert)));
        sigCert.verify(issuer.getPublicKey());
    }

but when I use the BouncyCastle, I get the following error:

> java.security.SignatureException: certificate does not verify with supplied key

I debugged the code and it fails in this fragment of checkSignature method in X509CertificateImpl class:

            if (!var2.verify(this.getSignature())) {
                throw new SignatureException("certificate does not verify with supplied key");
            }

Here is the code to reproduce:

    @Test
    public void verifyUsingBouncyCastle() throws Exception {

        String cIssuer = "MIICBjCCAaygAwIBAgIIEDiqn2SaqGMwCgYIKoZIzj0EAwIwVTFTMB8GA1UEAxMYTnV2b3RvbiBUUE0gUm9vdCBDQSAxMTEwMCUGA1UEChMeTnV2b3RvbiBUZWNobm9sb2d5IENvcnBvcmF0aW9uMAkGA1UEBhMCVFcwHhcNMTUwNTExMDg0MzMzWhcNMzUwNTA3MDg0MzMzWjBVMVMwHwYDVQQDExhOdXZvdG9uIFRQTSBSb290IENBIDExMTAwJQYDVQQKEx5OdXZvdG9uIFRlY2hub2xvZ3kgQ29ycG9yYXRpb24wCQYDVQQGEwJUVzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDVkEOpuyhuviaDH6xQj3faaV2Z4FvXSdwUkTiB1JjPDgv1PU0SFYtEE1W9VmI1GcOn5FAUi2/QM36DPhmPTd+qjZjBkMA4GA1UdDwEB/wQEAwICBDASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBQVkdS26vmNAQSGS2kDpI3QAmB30zAfBgNVHSMEGDAWgBQVkdS26vmNAQSGS2kDpI3QAmB30zAKBggqhkjOPQQDAgNIADBFAiEAlfxysfHDcxYDed5dmRbvHPKHLEEq9Y9PwAxoKqH7Q5kCIGfsxiLr2j9nJ9jELwXz0/VWN9PhUNdM3qmsx2JEne6p";
        String cSigCert = "MIID2zCCA4GgAwIBAgILAOvxfKjRf66wl9UwCgYIKoZIzj0EAwIwVTFTMB8GA1UEAxMYTnV2b3RvbiBUUE0gUm9vdCBDQSAxMTEwMCUGA1UEChMeTnV2b3RvbiBUZWNobm9sb2d5IENvcnBvcmF0aW9uMAkGA1UEBhMCVFcwHhcNMTgwNDMwMDc0NjQ3WhcNMzgwNDI2MDc0NjQ3WjAAMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtl6U8hTHtUDwym/PPcv3KdHeiPZLu1syGfhW1RC9v8a4OzfulGahwCOZbiu60Daqr20BndCxP8sdDyLjwSyffQb8TolCrq/vdUVj+OPuOBA+xypwEFg4m/QlR6FwzJyo6PPR2oeeAhZ/N5O8i6O1dmGxNJTvLaHT0r0TFZ32iMG5hhs8XL4kroF0OAl7JK09iAs4D0g/T17k7gNTVtf8rPzS8vhfN+JBj+k4nZ/HlG+PM23rw36T/Nk+eK4ZgBmV0LMN84++ZDuqccPSJ3zk3jvsKp/HFzvQkDqcriQsTSkY4cFqP7HR5vFhDSVeTBK7fNm3yNa/jb++q3XCx9dihQIDAQABo4IBwDCCAbwwSgYDVR0RAQH/BEAwPqQ8MDoxODAUBgVngQUCARMLaWQ6NEU1NDQzMDAwEAYFZ4EFAgITB05QQ1Q2eHgwDgYFZ4EFAgMTBWlkOjEzMAwGA1UdEwEB/wQCMAAwEAYDVR0lBAkwBwYFZ4EFCAEwHwYDVR0jBBgwFoAUFZHUtur5jQEEhktpA6SN0AJgd9MwDgYDVR0PAQH/BAQDAgUgMHAGA1UdCQRpMGcwFgYFZ4EFAhAxDTALDAMyLjACAQACAXQwTQYFZ4EFAhIxRDBCAgEAAQH/oAMKAQGhAwoBAKIDCgEAoxUwExYDMy4xCgEECgEBAQH/oAMKAQKkDzANFgUxNDAtMgoBAgEBAKUDAQEAMEEGA1UdIAQ6MDgwNgYEVR0gADAuMCwGCCsGAQUFBwIBFiBodHRwOi8vd3d3Lm51dm90b24uY29tL3NlY3VyaXR5LzBoBggrBgEFBQcBAQRcMFowWAYIKwYBBQUHMAKGTGh0dHA6Ly93d3cubnV2b3Rvbi5jb20vc2VjdXJpdHkvTlRDLVRQTS1FSy1DZXJ0L051dm90b24gVFBNIFJvb3QgQ0EgMTExMC5jZXIwCgYIKoZIzj0EAwIDSAAwRQIhAIo91KWNJlXWH4m6rGeNDXDvWYwIdb/i3AjPazGyrDc0AiB6lDa4q0f/+2c7bb8u6wJ7o18l3B5mVWTe2B33Lzrq/w==";

        Security.addProvider(new BouncyCastleProvider());
        CertificateFactory cf = CertificateFactory.getInstance("X.509", BouncyCastleProvider.PROVIDER_NAME);
        Certificate issuer = cf.generateCertificate(new ByteArrayInputStream(Base64.getDecoder().decode(cIssuer)));
        Certificate sigCert = cf.generateCertificate(new ByteArrayInputStream(Base64.getDecoder().decode(cSigCert)));
        sigCert.verify(issuer.getPublicKey());
    }

**Comment by dghgit** [comment]
sigCert is invalid. If you DER encode the TBS certificate you'll find it is different from how it is presented in the encoding, there's nothing wrong with this intrinsically providing the signature is calculated over the DER encoding, however in this case the signature has not been calculated over the DER encoding, but, I'd guess, the literal encoding, so the verification fails.

**Comment by martijnbrinkers** [comment]
I think this was introduced in commit 382c162d5b9bd654dfdbb7feb64c88e21c0e2e51 for org.bouncycastle.jcajce.provider.asymmetric.x509.PEMUtil.

Before this change, PEMUtil allowed importing a text file containing PEM encoded certificates embedded within a text file containing other content. Example which I think worked previously:

```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE----- 

Some text

```

This seems to be no longer supported because PEMUtil chockes on the text after END CERTIFICATE

**Comment by dghgit** [comment]
Not a bug, Issue regarded resolved.
