### ISSUE TITLE
Cipher suite ECDHE-RSA-AES128-GCM-SHA256 fails with org.bouncycastle.tls.TlsFatalAlertReceived: handshake_failure(40)

### ISSUE THREAD

**Issue by kul** [bcgit/bc-java#724]
BouncyCastleJsseProvider is failing for ECDHE-RSA-AES128-GCM-SHA256 cipher suite on TLSv1.2 servers. 

Java: OpenJDK11
bctls: 1.65
Note: This is also failing for bctls fips 1.0.10 library

```
org.bouncycastle.tls.TlsFatalAlertReceived: handshake_failure(40)
	at org.bouncycastle.tls.TlsProtocol.handleAlertMessage(TlsProtocol.java:241)
	at org.bouncycastle.tls.TlsProtocol.processAlertQueue(TlsProtocol.java:669)
	at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:518)
	at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:197)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:785)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:398)
	at org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:86)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:434)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:415)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1337)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
```

**Comment by peterdettman** [comment]
Are you using BCJSSE in FIPS mode? Are you using the BCFIPS provider?

All GCM cipher suites are disabled when BCJSSE is in FIPS mode, unless you are using bctls-fips AND it is being used with the BCFIPS provider. This was required to meet the (perhaps somewhat overly strict) FIPS requirements related to GCM nonce/IV generation.

If that doesn't explain what your are seeing, you will need to give a lot more details, especially details about the client and server configuration; note that the error is coming from the server here - a "reasonable" guess is that no suitable cipher suite could be agreed upon. I am guessing that you are trying to offer a single (GCM) cipher suite, BCJSSE is ignoring it because it's not supported, and an empty list of cipher suites is sent to the server, which then complains and aborts.

**Comment by kul** [comment]
Hi @peterdettman ,

Thanks for the reply! I should have perhaps provided more context here. 

- Yes I have tried this with both fips and non-fips bouncy castle libraires and I am seeing this issue consistently. I am setting appropriate properties as mentioned in the TLS guide for setting BC jsse provider to fips mode too. Yes, I am using -fips mvn deps for fips mode.
- I though it had to do with the ciphers initially but does not looks like as I am able to connect with another server which has similar tls configuration and the connection works fine.
- You should be able to reproduce this with following snippet

```
        URL url = new URL("https://marketplace.vmware.com"); // Handshake fails
//        URL url = new URL("https://aws.amazon.com"); // Succeeds here

        SSLContext context = SSLContext.getInstance("TLS", "BCJSSE");
        context.init(null, null, null);
        HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
        connection.setSSLSocketFactory(context.getSocketFactory());
        connection.setInstanceFollowRedirects(false);
        connection.setHostnameVerifier((ss, sslSession) ->  true);
        connection.connect();

```
- Lastly the SunJSSE seems to be working fine here. I tested by replacing BCJSSE with SunJSSE.

**Comment by kul** [comment]
I would like to add some more information on this if it helps
- There is a difference in cipher suites being offered by both servers
```
For: marketplace.vmware.com
Preferred TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  AES128-GCM-SHA256            
Accepted  TLSv1.2  256 bits  AES256-GCM-SHA384            
Accepted  TLSv1.2  128 bits  AES128-SHA256

For aws.amazon.com
Preferred TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  AES128-GCM-SHA256            
Accepted  TLSv1.2  256 bits  AES256-GCM-SHA384            
Accepted  TLSv1.2  128 bits  AES128-SHA256
Accepted  TLSv1.2  256 bits  AES256-SHA
Accepted  TLSv1.2  128 bits  AES128-SHA
Preferred TLSv1.1  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.1  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.1  256 bits  AES256-SHA
Accepted  TLSv1.1  128 bits  AES128-SHA
Preferred TLSv1.0  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.0  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.0  256 bits  AES256-SHA
Accepted  TLSv1.0  128 bits  AES128-SHA

```
- Here is the provider configuration I have 
```
# For fips
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS
security.provider.3=SUN
#security.provider.4=SunJCE
#security.provider.5=SunJSSE

```
```
# For regular
security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider
security.provider.3=SUN
#security.provider.4=SunJCE
#security.provider.5=SunJSSE

```
- I can see that for the BC fips libraries, the provider has the prefered cipher available
![Selection_019](https://user-images.githubusercontent.com/1580309/84353872-8bcfe080-abdd-11ea-99dd-e986eead479f.jpg)

**Comment by gstanchev** [comment]
Are you sure this is related to the cipher suites and not to client SNI extension? We ran into public servers (hosted on CloudFlare) terminating handshake because BCFIPS doesn't send SNI with the handshake . After manually injecting client SNI via custom SSF, calls started succeeding

**Comment by peterdettman** [comment]
@gstanchev has the right idea. See https://github.com/bcgit/bc-java/issues/460, https://github.com/bcgit/bc-java/issues/660, https://github.com/bcgit/bc-java/issues/709 .

"BCFIPS doesn't send SNI" is a bit wonky though. Trivially because BCJSSE is presumably meant, but more to the point: BCJSSE sends SNI whenever it's given a name to send. That an SNI name is not sent is entirely at the feet of the HttpsURLConnection implementation.

In any case, your example works for marketplace.vmware.com if the SNI is set explicitly:

```
        connection.setSSLSocketFactory(new CustomSSLSocketFactory(context.getSocketFactory()) {
            @Override
            protected Socket configureSocket(Socket s)
            {
                SSLParameters sslParams = new SSLParameters();
                sslParams.setServerNames(
                    Collections.<SNIServerName>singletonList(new SNIHostName(HOST)));
                ((SSLSocket)s).setSSLParameters(sslParams);
                return s;
            }
        });
```

Alternatively use one of the several third-party HTTPS client libraries that play nice with third-party JSSE providers.

**Comment by kul** [comment]
Thanks @peterdettman and @gstanchev ,

I did not get a chance to try this out yet. But since @peterdettman already tried out the example with injecting SNI, I guess there is no need for further triaging here. I will close the issue once I try it out.

Thanks for the help!
