### ISSUE TITLE
DTLS handshake gets stuck with high latency between the client and the server

### ISSUE THREAD

**Issue by NicFontana** [bcgit/bc-java#726]
## Issue description
If there is a latency >= 500ms between the client and the server the handshake won't complete.

## How to reproduce it
I am experimenting with the example classes ```DTLSServerTest``` and ```DTLSClientTest``` under the package ```org.bouncycastle.tls.test```.
Before running the test I've set a latency of 500ms on my loopback interface with ```sudo tc qdisc add dev lo root netem delay 500ms```.

## Cause description
With this configuration, the __client receives the ```Hello Verify Request``` after its resend timeout (initially set to 1000ms) expires__, so it sends another ```Client Hello``` before it can receive the aforementioned ```Hello Verify Request```.

This causes an infinite loop where the client will continuously send (every time its resend timeout expires) the patched ```Client Hello + Cookie``` ignoring every response coming from the server.
On the other side, the server will continuously receive the ```Client Hello + Cookie``` replying with the ```Server Hello``` sequence (```Certificate```, ```ServerKeyExchange```, ```CertificateRequest```, ```ServerHelloDone```) that will be ignored by the client.

**Comment by peterdettman** [comment]
Thanks for the report. The main problem appears to be the message sequence number logic for non-trivial message flows involving HelloVerifyRequest, but there are other complications. We will need to review the RFC and check the behaviour of other TLS implementations in these situations.

**Comment by peterdettman** [comment]
A fix has been pushed to our git repo (can take some time to mirror here), along with some related improvements. Tested on macOS 10.15.5 using PF/dummynet to add delays, including interop with GnuTLS 3.6.13.

It would be great if you could verify the fix once it appears here, or in the next beta version (should be 166b12) once it appears at https://downloads.bouncycastle.org/betas/ .

**Comment by NicFontana** [comment]
Nice, thank you!

**Comment by NicFontana** [comment]
Hi @peterdettman, I've tested the fix and everything worked well even on my side. :+1: 

Do you know when the next release will be released?

**Comment by peterdettman** [comment]
Great. 1.66 is imminent, should be within the next week.
