### ISSUE TITLE
Using cobertura as a code coverage mechanism?

### ISSUE THREAD

**Issue by vicnete** [bcgit/bc-java#728]
Hey everyone, 

I see you are using cobertura as the code coverage mechanism. 

Cobertura is giving me issues when building the project using gradle. 

A simple gradle build command provides me with the following output 

A problem occurred evaluating root project 'bc-java-master'.
> Failed to apply plugin [id 'net.saliman.cobertura']
   > Could not create task ':generateCoberturaReport'.
      > Could not create task of type 'GenerateReportTask'.
         > Could not create an instance of type net.saliman.gradle.plugin.cobertura.CoberturaReportsImpl.
            > org.gradle.api.reporting.internal.TaskReportContainer.<init>(Ljava/lang/Class;Lorg/gradle/api/Task;)V

Furthermore, looking into it,  I have seen the ecobertura eclipse plugin reccomended as an alternative to see code coverage. As of today eclipse gives me the following error when installing ecobertura from its marketplace. 

No repository found at http://ecobertura.johoop.de/update.

Is ecobertura still active?
Any clue why I may be unable to outright build the project?

**Comment by dghgit** [comment]
I've cleaned out the cobertura code. I think I might be the only person on the planet that still has the jars to run it...

Updated files should appear on github shortly.

**Comment by kimmerin** [comment]
> I've cleaned out the cobertura code. I think I might be the only person on the planet that still has the jars to run it...

FWIW: We still use it with some (old) projects but for current developement we've switched to JaCoCo due to its better performance and Java 11 support.
