### ISSUE TITLE
SecureRandom Instance creation

### ISSUE THREAD

**Issue by RashmiSunil** [bcgit/bc-java#729]
Hi Team,

I am using BCFIPS for FIPS 140-2 complaincy.
I want to understand the algorithm used in SecureRandom instance in below example.
SecureRandom.getInstance("DEFAULT", "BCFIPS");

Which algorithm is used if "DEFAULT" is set.
What is the way to create HMACDRBG algorithm?

**Comment by dghgit** [comment]
By default it's an SP 800-90A DRBG based on SHA-512. Configuration of the default DRBG is discussed in Section 2.3 of the BC-FJA User Guide.
