### ISSUE TITLE
1.65.01 and 1.65 on maven central

### ISSUE THREAD

**Issue by holgerhaag** [bcgit/bc-java#733]
Hello,

we've noticed that there are 1.65.01 and 1.65 on maven central.

https://search.maven.org/artifact/org.bouncycastle/bcprov-jdk15on

releases page here (https://github.com/bcgit/bc-java/releases) only shows 1.65

Is 1.65.01 a different release?

**Comment by dghgit** [comment]
It's a patch release on 1.65 fixing a regression detailed in https://github.com/bcgit/bc-java/issues/682

If it's not an issue for you I would wait for 1.66, which will be coming out in July.

**Comment by holgerhaag** [comment]
ok, thanks for the information!
