### ISSUE TITLE
Performance issue with Base64OutputStream

### ISSUE THREAD

**Issue by dilipcrd** [bcgit/bc-java#738]
Base64OutputStream class is extremely slow. It takes about 10 minutes to process a file that is 100 MB in size. 

Switching to the Apache Commons implementation of the same class gets the same file processed in seconds!

**Comment by kimmerin** [comment]
Can you provide a testcase that shows how you use that class?

**Comment by dilipcrd** [comment]
I have not used it directly. It is used by the BasicMimeParser class' processStream function. I used the MimeParser to decrypt a large CMS enveloped base64 encoded binary message


	public void decrypt(InputStream encryptedStream, OutputStream plainTextStream, DecryptionParameters decryptionParameters) {
		try {
			MimeParserProvider provider = new SMimeParserProvider("7bit", new BcDigestCalculatorProvider());
			MimeParser parser = provider.createParser(encryptedStream);
			parser.parse(new ParserListener(decryptionParameters, plainTextStream));
		} catch (Exception e) {
			logger.log("Failed to decrypt file", e);
		}
	}

Due to the noticed performance issue, I replaced the code with this - 

	public void decrypt(InputStream encryptedStream, OutputStream plainTextStream, DecryptionParameters decryptionParameters) {
		try {
			MimeParser parser = new MyMimeParser(new SMimeParserContext("base64", new BcDigestCalculatorProvider()), encryptedStream);
			parser.parse(new ParserListener(decryptionParameters, plainTextStream));
		} catch (Exception e) {
			logger.log("Failed to decrypt file", e);
		}
	}

In the MyMimeParse class, I just copied the implementation of the BasicMimeParser class and switched the use of Base64InputStream to that from Apache Commons. That fixed my performance issue.

**Comment by dilipcrd** [comment]
I have not used it directly. This class is instantiated by the SMIMEEnvelopedWriter class' getContentStream method for base64 encoded messages.

After I created my own implementation of the MimeWriter interface (by mostly copying the SMIMEEnvelopedWriter class' implementation but replacing the instantiation of Base64OutputStream with that from Apache commons), the noticed performance issue went away. , 

	public void encrypt(InputStream plainTextStream, OutputStream outputStream, X509Certificate encryptionCertificate) {
		try {
			SMIMEEnvelopedWriter.Builder envBldr = new SMIMEEnvelopedWriter.Builder();
			KeyTransRecipientInfoGenerator issuerSerialNumberRecipientInfoGenerator = new JceKeyTransRecipientInfoGenerator(encryptionCertificate)
					.setProvider(BouncyCastleProvider.PROVIDER_NAME);
			PublicKey publicKey = encryptionCertificate.getPublicKey();
			SubjectKeyIdentifier subjectKeyIdentifier = new JcaX509ExtensionUtils().createSubjectKeyIdentifier(publicKey);
			KeyTransRecipientInfoGenerator subjectKeyRecipientInfoGenerator = new JceKeyTransRecipientInfoGenerator(subjectKeyIdentifier.getKeyIdentifier(), publicKey)
					.setProvider(BouncyCastleProvider.PROVIDER_NAME);
			envBldr.addRecipientInfoGenerator(issuerSerialNumberRecipientInfoGenerator);
			envBldr.addRecipientInfoGenerator(subjectKeyRecipientInfoGenerator);
			ASN1ObjectIdentifier encryptionAlgorithm = CMSAlgorithm.AES256_CBC;
			OutputEncryptor outputEncryptor = new JceCMSContentEncryptorBuilder(encryptionAlgorithm).setProvider(BouncyCastleProvider.PROVIDER_NAME).build();
			SMIMEEnvelopedWriter envelopedWriter = envBldr.build(outputStream, outputEncryptor);
			OutputStream envelopedWriterStream = envelopedWriter.getContentStream();
			copyToOutputStream(plainTextStream, envelopedWriterStream);
		} catch (Exception e) {
			logger.log("Failed to encrypt file", e);
		}
	}

	private static void copyToOutputStream(InputStream in, OutputStream out) throws IOException {
		byte[] buffer = new byte[BUFFER_SIZE];
		int numRead;
		while ((numRead = in.read(buffer)) >= 0) {
			out.write(buffer, 0, numRead);
		}
		out.flush();
		out.close();
	}




There is an additional performance issue in the SMIMEEnvelopedWriter class (not sure if I should create a separate report for this) -



The getContentStream method returns an instance of a nested class - ContentOutputStream. During the instantiation of that class in the getContentStream method, a call is made to SMimeUtils.createUncloseable. That method returns an instance of the FilterOutputStream class. That class has overrides for the write method that copies data, one byte at a time (even for overloads that accept an array of bytes). This is extremely inefficient and noticeably slow, especially if the destination stream is a File. 

I would suggest updating the write method in that class that accepts byte arrays to this - 

            public void write(byte b[], int off, int len) throws IOException {
                if ((off | len | (b.length - (len + off)) | (off + len)) < 0)
                    throw new IndexOutOfBoundsException();
                out.write(b, off, len);
            }

Once that is done, the ContentOutputStream method can be updated like so - 


     // Output stream for deterministically closing the backing stream
    private static class ContentOutputStream extends OutputStream {
        private final OutputStream main;
        private final OutputStream backing;

        ContentOutputStream(OutputStream main, OutputStream backing) {
            this.main = main;
            this.backing = backing;
        }

        public void write(int i) throws IOException {
            main.write(i);
        }

        public void write(byte[] b) throws IOException {
            main.write(b, 0, b.length);
        }

        public void write(byte[] b, int off, int len) throws IOException {
            main.write(b, off, len);
        }

        public void close() throws IOException {
            main.close();
            if (backing != null) {
                backing.close();
            }
        }
    }

This will significantly improve the performance of the CMS / S/MIME streaming interface.

**Comment by dghgit** [comment]
I was a bit surprise by this. When I tried a side by side I got a difference of about 5 times, not fantastic, but well below what's described here. You mention writing to a file, the code is using a BufferedOutputStream isn't it? The BC library doesn't introduce any extra buffering assuming the developer should make that decision.

**Comment by dilipcrd** [comment]
Did you make both changes? 
1. Replace Base64OutputStream with the Apache Commons implementation and 
2. Replace ContentOutputStream + Update FilterOutputStream?

My code isn't using a BufferedOutputStream. It is directly writing to a FileOutputStream. 

Are you suggesting that using a BufferedOutputStream will improve things?

**Comment by dilipcrd** [comment]
I made the following change to my copyToOutputStream method. 

	private static void copyToOutputStream(InputStream in, OutputStream out) throws IOException {
		try (BufferedOutputStream bos = new BufferedOutputStream(out, BUFFER_SIZE)) {
			byte[] buffer = new byte[BUFFER_SIZE];
			int numRead;
			while ((numRead = in.read(buffer)) >= 0) {
				bos.write(buffer, 0, numRead);
			}
			bos.flush();
		}
		out.close();
	}

my buffer size is 8K.

It made no difference in timing. The encryption took more than 10 minutes (my file size is 89 MB). I gave up after 10 minutes. 

I'm not sure how this would have helped anyways. The byte-by-byte writing is being done inside the BC library (in the FilterOutputStream class) .  The more significant performance hit is coming from the Base64OutputStream class though.

On the other hand, after switching to my implementation (mentioned in my second post), the same encryption took only 10 seconds (even without BufferedOutputStream)!

So, yes, the performance is really that terrible!

**Comment by dilipcrd** [comment]
I made the following change to my copyToOutputStream method. 

	private static void copyToOutputStream(InputStream in, OutputStream out) throws IOException {
		try (BufferedOutputStream bos = new BufferedOutputStream(out, BUFFER_SIZE)) {
			byte[] buffer = new byte[BUFFER_SIZE];
			int numRead;
			while ((numRead = in.read(buffer)) >= 0) {
				bos.write(buffer, 0, numRead);
			}
			bos.flush();
		}
		out.close();
	}

my buffer size is 8K.

It made no difference in timing. The encryption took more than 10 minutes (my file size is 89 MB). I gave up after 10 minutes. 

The more significant performance hit is coming from the Base64OutputStream class though.

On the other hand, after switching to my implementation (mentioned in my second post), the same encryption took only 10 seconds (even without BufferedOutputStream)!

So, yes, the performance is really that terrible!

**Comment by dilipcrd** [comment]
Okay. I did more testing. 

This is my updated version of getContentStream - 

    @Override
    public OutputStream getContentStream() throws IOException {
        headers.dumpHeaders(mimeOut);
        mimeOut.write(Strings.toByteArray("\r\n"));

        OutputStream outputStream = CONTENT_TRANSFER_ENCODING_BASE64.equals(contentTransferEncoding)
                ? new  org.bouncycastle.mime.encoding.Base64OutputStream(mimeOut)
                : mimeOut;

        OutputStream uncloseable = new BufferedOutputStream(outputStream) {
            public void close() throws IOException {
                // output stream must not be closed here
            }
        };

        try {
            return new ContentOutputStream(envelopedDataStreamGenerator.open(uncloseable, outputEncryptor), outputStream);
        } catch (CMSException e) {
            throw new MimeIOException(e.getMessage(), e);
        }
    }

This takes more than 10 minutes to complete since I am instantiating org.bouncycastle.mime.encoding.Base64OutputStream. However, when I switch to org.apache.commons.codec.binary.Base64OutputStream, the encryption completes in under 6 seconds (for the same 89MB file).

Looks like using BufferedOutputStream makes a slight improvement over FilteredOutputStream here. The biggest gain is from switching to Base64OutputStream from Apache.

**Comment by kimmerin** [comment]
Hm, I can set up a Testcase and start my profiler to confirm but I can see that Base64OutputStream is using Base64 to encode chunks of 54 bytes. Every encode-operation creates an instance of ByteArrayOutputStream and a new byte[] when calling toByteArray() that returns a byte-array whose content is copied again when written to the underlying stream.

I think there is some potential for improvement ;-)

**Comment by dilipcrd** [comment]
Thanks for looking into this! There may be a similar issue with Base64InputStream as well because I am seeing similar performance issues during decryption as well.

**Comment by dghgit** [comment]
I benchmarked both classes side by side. As in the Apache one and the BC equivalent. I get a difference of about 4 times in speed (actually 3.76 to be more precise).

If your code is writing to a FileOutputStream that is not wrapped in a BufferedOutputStream it will be painfully slow if you are using the BC version.

**Comment by dghgit** [comment]
Try https://www.bouncycastle.org/betas - the base64 code is now benchmarks at twice the speed of the commons one. Note there is still minimal internal buffering being done.

**Comment by dilipcrd** [comment]
Thanks!

**Comment by dghgit** [comment]
Closing as resolved.
