### ISSUE TITLE
Performance Issue with Base64InputStream used in BasicMimeParser

### ISSUE THREAD

**Issue by dilipcrd** [bcgit/bc-java#739]
It is used by the BasicMimeParser class' processStream function. I used the MimeParser to decrypt a large CMS enveloped base64 encoded binary message

public void decrypt(InputStream encryptedStream, OutputStream plainTextStream, DecryptionParameters decryptionParameters) {
	try {
		MimeParserProvider provider = new SMimeParserProvider("7bit", new BcDigestCalculatorProvider());
		MimeParser parser = provider.createParser(encryptedStream);
		parser.parse(new ParserListener(decryptionParameters, plainTextStream));
	} catch (Exception e) {
		logger.log("Failed to decrypt file", e);
	}
}

Due to the noticed performance issue, I replaced the code with this -

public void decrypt(InputStream encryptedStream, OutputStream plainTextStream, DecryptionParameters decryptionParameters) {
	try {
		MimeParser parser = new MyMimeParser(new SMimeParserContext("base64", new BcDigestCalculatorProvider()), encryptedStream);
		parser.parse(new ParserListener(decryptionParameters, plainTextStream));
	} catch (Exception e) {
		logger.log("Failed to decrypt file", e);
	}
}

In the MyMimeParse class, I just copied the implementation of the BasicMimeParser class and switched the use of Base64InputStream to that from Apache Commons. That fixed my performance issue.

**Comment by dghgit** [comment]
This also sounds an awful lot like buffering...

**Comment by dilipcrd** [comment]
Could you elaborate?

**Comment by dghgit** [comment]
Maybe we should sort out #738 first.

**Comment by dghgit** [comment]
Assume resolved (#738 appears to have dealt with it)
