### ISSUE TITLE
Supported psk in DTLS

### ISSUE THREAD

**Issue by jsinghuy** [bcgit/bc-java#743]
Hello, 
I am implementing CoAP secure client-server application using this library. I am sending CoAPS request (PSK based security) by using scandium library. My server using bouncycastle library. 
Getting error at server : " raised alert: fatal(2), handshake_failure(40)"  
and getting values like: 
Processing Client Hello Message
Print client_random : [B@696bd94c
Print buffer : java.io.ByteArrayInputStream@340f8d31
Print state.clientExtensions  : {10=[B@4a36778f, 20=[B@662ef237, 11=[B@51b8e607}
Print SecurityParameters.getEntity : 0 
Print SecurityParameters.getPskIdentity : null second : null
Print state.offeredCipherSuites  : [I@3074e5bc
Arrays.contains(state.offeredCipherSuites, CipherSuite.TLS_EMPTY_RENEGOTIATION_INFO_SCSV) : false
Print renegExtData : null
Print state.secure_renegotiation: false
Print secureRenegotiation false
  
Is it supporting psk security for DTLS or not?

**Comment by peterdettman** [comment]
I added a new test case demonstrating DTLS client/server using PSK cipher suites: https://github.com/bcgit/bc-java/blob/master/tls/src/test/java/org/bouncycastle/tls/test/DTLSPSKProtocolTest.java .
