### ISSUE TITLE
NegativeArraySizeException in RFC5649WrapEngine

### ISSUE THREAD

**Issue by simon-greatrix** [bcgit/bc-java#744]
When unwrapping invalid data, or unwrapping with the wrong key, the engine can throw a NegativeArraySizeException.

This occurs when the MLI (message length indicator) exceeds the actual number of message bytes so the calculated length of the padding is negative.

**Comment by simon-greatrix** [comment]
I have created a pull request with extended tests to catch this issue and a proposed fix.

**Comment by dghgit** [comment]
Closed as pull request applied as of 1.68
