### ISSUE TITLE
Issues of Storing PGP Secret key and other's Public Key

### ISSUE THREAD

**Issue by macknight** [bcgit/bc-java#747]
I'm new to PGP. And I'm using Java.

I wonder if I use Java to generate PGP secret key and import other people's public key, how can I store it? using Java Keystore?
Anyone can tell me how to do it? Any docs or links about this?
I checked online, someone says PGP keys can't be stored in java keystore because PGP key is not compatible with Java keystore and will lose information when storing into Java store.
So where should I store these keys?
Is it the only way that storing these keys in *.asc file which is protected by a passphrase?

**Comment by peterdettman** [comment]
We only provide the low-level cryptography involved in OpenPGP, which does include reading/writing keys/keyrings in their basic format. Higher-level key management features are out of scope (actually out of scope of OpenPGP itself). I expect you could find existing tools built over our OpenPGP implementation, but don't know enough to recommend any.

**Comment by winfriedgerlach** [comment]
@macknight @peterdettman can this issue be closed?
