### ISSUE TITLE
Interoperability issue between BC PGP encryption and gpg using ECDH and AES128

### ISSUE THREAD

**Issue by martijnbrinkers** [bcgit/bc-java#749]
We found an interoperability issue between BC and gpg2 if data is encrypted with AES128 using a ECDH PGP key.

Section "13.5. EC DH Algorithm (ECDH)" of rfc4880bis[1] describes a mechanism of key obfuscation, i.e., to hide the symmetric encryption strength (128,256 etc.) by padding all encrypted session keys to 40 bytes.

BC by default implements this key obfuscation (see PGPPad#padSessionData) technique.

When we encrypt content with a AES128 using an ECDH PGP key, gpg is unable to decrypt the data and reports:

```
gpg: encrypted with 256-bit ECDH key, ID AF8B30CEB2B736DE, created 2020-07-10
      "CipherMail test NIST P-256 <nist-p-256@example.com>"
gpg: public key decryption failed: Wrong secret key used
gpg: decryption failed: No secret key
```

If we use AES256 instead of AES128, it works, i.e., gpg is able to decrypt.

According to this bug report https://dev.gnupg.org/T3763 gpg does not support key obfuscation. 

If I replace the passing with PKCS5 padding (as described in the bug report [2]), gpg can decrypt the AES128 encrypted data (and also AES256 etc.)

org.bouncycastle.openpgp.operator.PGPPad:

```
    public static byte[] padSessionData(byte[] sessionInfo)
    {
//        byte[] result = new byte[40];
        byte[] result = new byte[(sessionInfo.length / 8 + 1) * 8];

        System.arraycopy(sessionInfo, 0, result, 0, sessionInfo.length);

        byte padValue = (byte)(result.length - sessionInfo.length);

        for (int i =  sessionInfo.length; i != result.length; i++)
        {
            result[i] = padValue;
        }

        return result;
    }
```

Because gpg is the de facto standard for PGP, it would be good to remove the key obfuscation from BC

(1) https://tools.ietf.org/html/draft-ietf-openpgp-rfc4880bis-04
(2) https://dev.gnupg.org/T3763

**Comment by martijnbrinkers** [comment]
It looks like the issue has been fixed in the latest gnupg version. However it will take a long time until this updated version is in use because most Linux distro's will not update to the latest version.

It would be nice if key obfuscation can be configurable.

Pseudo code:

```
    public static byte[] padSessionData(byte[] sessionInfo, boolean obfuscate)
    {
        byte[] result = obfuscate ? new byte[40]: new byte[(sessionInfo.length / 8 + 1) * 8];

        System.arraycopy(sessionInfo, 0, result, 0, sessionInfo.length);

        byte padValue = (byte)(result.length - sessionInfo.length);

        for (int i =  sessionInfo.length; i != result.length; i++)
        {
            result[i] = padValue;
        }

        return result;
    }
```

**Comment by peterdettman** [comment]
Yes, I think making it configurable is reasonable. Thanks for your investigation efforts.

**Comment by peterdettman** [comment]
Obfuscation is now controlled by `PublicKeyKeyEncryptionMethodGenerator.setSessionKeyObfuscation`, with default value  configurable using the boolean system property _org.bouncycastle.openpgp.session_key_obfuscation_, or else defaulting to `true` i.e. enabled (the current behaviour).

**Comment by peterdettman** [comment]
Github has the updates now if you would like to test them.

**Comment by martijnbrinkers** [comment]
I can confirm that the fix works. Thanks.
