### ISSUE TITLE
NTRU Encryption with parameter set ntruhps4096821

### ISSUE THREAD

**Issue by java-crypto** [bcgit/bc-java#752]
BC has a NTRU Encryption method set that lets me encrypt some data using predefined parameter sets. In round 2 of NIST Post-Quantum Cryptography the submitters added some "longeer" parameter sets like ntruhps4096821 (some details in https://github.com/PQClean/PQClean/blob/master/crypto_kem/ntruhps4096821/clean/api.h) or more details on page 9 [1.6 Summary of recommended parameters and derived constants] of the PDF available under http://ntruprime.cr.yp.to/nist/ntruprime-20190330.pdf.

In know that I can setup my own parameter set using 
NTRUEncryptionKeyGenerationParameters(int N, int q, int df, int dm0, int db, int c, int minCallsR, int minCallsMask, boolean hashSeed, byte[] oid, boolean sparse, boolean fastFp, Digest hashAlg, SecureRandom random)
but I did not find ALL input parameters used for this method.

When do you expect to include this parameter set into BC (I checked with actual 1.66) or can you provide the params for ntruhps4096821 ?

Kind regards
Michael

**Comment by dghgit** [comment]
This is now available in 172b06 or later.
