### ISSUE TITLE
Trouble 

### ISSUE THREAD

**Issue by gaoxt9** [bcgit/bc-java#753]
Hi, my team recently upgraded our Bouncy Castle from 1.47 to 1.63. In the meanwhile, we found a malformed PEM certificate accidentally got into our database. The certificate has an invalid footer that doesn't have a space between two words (---EndCertificate----). It's hard for us to roll back and find out is the bug from the previous Bouncy Castle or from our code. This case has driven me nuts and any advice will be appreciated.
Thanks.

**Comment by martijnbrinkers** [comment]
Since you read the PEM certificate from the database yourself, why can't you replace ---EndCertificate---- by the correct value before BC loads the certificate?

**Comment by peterdettman** [comment]
I'm not aware that BC ever had a bug in the writing out of PEM footers. The header and footer are independent of the contents so it's easy to fix by just replacing the footer, as @martijnbrinkers pointed out.

**Comment by dghgit** [comment]
Yes, we've always had a space. If you need to confirm you can find the source for the 1.47 PEM generator at:

https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk15on/1.47/bcpkix-jdk15on-1.47-sources.jar

The class you want is in org/bouncycastle/openssl/MiscPEMGenerator.java

The rest of 1.47 can be found at: https://repo1.maven.org/maven2/org/bouncycastle/

**Comment by martijnbrinkers** [comment]
This most likely related to issue #758. The certificate was imported with an older BC release which had a more forgiven PEM parser.
