### ISSUE TITLE
Difference between `bcprov-ext-jdk15to18-166.jar` and `bcprov-jdk15to18-166.jar` ?

### ISSUE THREAD

**Issue by jayjupdhig** [bcgit/bc-java#759]
Hi there

What's the difference between `bcprov-ext-jdk15to18-166.jar` and `bcprov-jdk15to18-166.jar` ? When i open them, it seems (at least for the firsdt view) as they both have same same content / classes...

Thank you very much for your feedbacks! :-)

With best regards from Switzerland,
Jan

**Comment by martijintro** [comment]
Is the correct what i read here?
-> https://stackoverflow.com/questions/29211582/how-do-bcprov-and-bcprov-ext-differ#:~:text=bcprov%20is%20typically%20the%20library,the%20main%20release%20since%20v1.&text=From%20release%201.40%20some%20implementations,of%20a%20number%20of%20users.

Regards, Jan

**Comment by martijintro** [comment]
And what .jar file do i need to resolve that dependencies?

![Unbenannt](https://user-images.githubusercontent.com/42765391/89286177-08b58e80-d652-11ea-8337-a4bbbbf3667c.JPG)

**Comment by martijintro** [comment]
-> Neither the .jar with "ext" nor the other one (without "ext") contains that classes - only import `org.bouncycastle.jce.provider.BouncyCastleProvider` is resolveduntil now...

**Comment by martijintro** [comment]
Now i inspected all that jars on `https://www.bouncycastle.org/latest_releases.html` for some content - that was a real orgy of try and error!! ;-)

...but that one seems to be the right one:
https://www.bouncycastle.org/download/bcpkix-jdk15to18-166.jar


So please correct me please if i'm wrong with that.


Kind regards, Jan

**Comment by martijintro** [comment]
NO ANWSER?!

**Comment by dghgit** [comment]
From https://www.bouncycastle.org/latest_releases.html

"From release 1.40 some implementations of encryption algorithms were removed from the regular jar files at the request of a number of users. Jars with names of the form *-ext-* still include these (at the moment the list is: NTRU)."

If you are in a rush for answers I would recommend considering the support program offered at https://www.cryptoworkshop.com
