### ISSUE TITLE
Wrong implementation of AES-GCM within Cryptographic Message Syntax

### ISSUE THREAD

**Issue by rdoepke** [bcgit/bc-java#763]
Hello everyone,

initially, I posted the problem within  #528 , but as the title of the issue does not match at all with the issue and there was yet no reaction, I am creating a new issue.

We discovered that RFC 5084 seems to have a faulty implementation in Bouncycastle: The message authentication code (MAC) gets appended to the cipher text.

The MAC value therefore can be found twice in the generated ASN.1 structure. It gets both appended to the ciphertext field and set in the dedicated AuthEnvelopedData mac field. The latter one is set and mandatory, as its length in octets must match the aes-ICVlen parameter according to RFC 5084. The fact that the MAC can also be found in the ciphertext field is, however, not explicitly forbidden by the specification, but is at least unusual within DER encoded data, as it being duplicated. I'd therefore interpret the RFC it as it shouldn't be there a second time.

This can be observed within the `AuthEnvelopedDataTest`. The Sample1 CMS structure already contains the duplicate data, as can be seen here:
http://lapo.it/asn1js/#MIAGCyqGSIb3DQEJEAEXoIAwgAIBADGBmzCBmAIBAoABATANBgkqhkiG9w0BAQEFAASBgG9yJPC3zFmIbPTtSrrTD-71lluua3F1_V_XzzDOczjdymy4tI4sle5HSxJN8yrw-m2JdWKb4s_u4frvmNqE6fcqfFtLpLEMXJneoEWWXZFKbndoqQNRMgfKGCncpeWhktRcSRtbEEk_H4hWggJGmVClS7f_nmCDjwyANBnI3shYMIAGCSqGSIb3DQEHATAfBglghkgBZQMEAQYwEgQQLO0PwnuhYXRk8pLLhgik0aCABB8KvxIkbmBKT73Oz4xtf0DNNGmdn-tzPcOldJUQWCEnAAAAAAQMn-tzPcOldJUQWCEnAAAAAAAA
The MAC (Offset 265) is also appended in the cipher text (Offset 228)

I am currently not sure, if this is an issue with the `org.bouncycastle.crypto.modes.GCMBlockCipher` which appends the MAC to the cipher. However, it is also used outside of CMS contexts. This leads to the impression that `CMSAuthEnvelopedDataGenerator` should strip it from the encrypted content.

Either way, the implementation is wrong and is backed by a faulty test case. This leads to interoperability issues when not en-/decrypting with bouncycastle. Any thoughts on this?

Regards,
Roland

**Comment by dghgit** [comment]
Yes, the implementation is incomplete, it seems it's fallen off a few people's radars, including mine. It's a bit of a weird one though, it's not that the BC implementation is incorrect for GCM (the MAC needs to be appended for use with EnvelopedData) it's just not designed for this particular use case.

I think you're correct though in your assumption about how it should be working though, the GCM MAC shouldn't be at the end of the encrypted content as it doesn't actually make sense for it to be there - the DER encoding of the authenticated attributes is meant to provide the associated data in this case - clearly impossible if the usual streaming model for CMS data is being applied. With GCM I think it would just be a matter of removing the MAC on output, CCM I'd need to think about, probably the same, but the MAC is encrypted. Parsing the data is going to be a bit interesting though.

**Comment by dghgit** [comment]
Fixed in 169b03. Should appear in https://www.bouncycastle.org/betas in the next day or so.
