### ISSUE TITLE
how to update the expiration date for the PGP key?

### ISSUE THREAD

**Issue by sreedharj** [bcgit/bc-java#766]
Hi,

I was able to generate the PGP Secret key and set the expiration days using setKeyExpirationDays on the PGPSignatureSubpacketGenerator.

After generating the secret,  I wan to read the same key and update the  expiration days.  But could not figure out how to update the expiration.   Please let me know how to update the key with expiration days?

**Comment by sreedharj** [comment]
any updates on this?    
My question is, how to update the expiration days for the existing key?

**Comment by dghgit** [comment]
Changing the expiration date means changing the certification. You can use PGPPublicKey.addCertification/PGPPublicKey.removeCertification to replace the existing certification's expiration date with a new one.
