### ISSUE TITLE
No way to create BCEdDSAPublicKey from raw key data

### ISSUE THREAD

**Issue by cyberphone** [bcgit/bc-java#773]
If you only have the public key value and curve name which is the case when using https://tools.ietf.org/html/rfc8037 it is unclear to me how to proceed.  None of the "spec" methods seem to fit and the BC tests do not include such transformations either.

```json
{
  "kty":"OKP",
  "crv":"Ed25519",
  "x":"11qYAYKxCrfVS_7TyWQHOg7hcvPapiMlrwIaaPcHURo"
}
```

**Comment by dghgit** [comment]
Try this: 

   private static X509EncodedKeySpec createEdDSAPublicKeySpec(byte[] rawPoint)
        throws IOException
    {
        AlgorithmIdentifier algId;
        if (rawPoint.length == 32)
        {
            algId = new AlgorithmIdentifier(EdECObjectIdentifiers.id_Ed25519);
        }
        else
        {
            algId = new AlgorithmIdentifier(EdECObjectIdentifiers.id_Ed448);
        }

        return new X509EncodedKeySpec(new SubjectPublicKeyInfo(algId, rawPoint).getEncoded());
    }

**Comment by cyberphone** [comment]
Thanx!
