### ISSUE TITLE
Please remove synchronized from ECCurve.getMultiplier()

### ISSUE THREAD

**Issue by gabor-hargitai-privitar** [bcgit/bc-java#778]
Hi,

I've noticed recently while working on a performance issue that must of the times the threads of my application were blocked waiting on ECCurve.getMultiplier(). All the threads of my application were using the same ECCurve - acquired via CustomNamedCurves.getByName - so the ECCurve instance was basically a singleton so all my threads were synchronizing on a singleton, albeit only for a very short time.

ECCurve.getMultiplier() has the synchronized keyword because it creates the multiplier lazily.

I can see two solutions to this problem:
 - create the multiplier eagerly
 - or remove the synchronised keyword from ECCurve.getMultiplier(). This would mean that if ECCurve.getMultiplier() is called from multiple threads at the same time when the multiplier is still null then they could all create a multiplier object, which is a bit wasteful, however all threads would create an instance of the same class with the same configuration, and the multiplier objects seem to be quite lightweight and stateless so this isn't a huge issue, and eventually the different CPU cores would converge to seeing the same multiplier objects. This might sound unsafe, but for example java.lang.String caches its hashcode internally without any sort of synchronization, and the worst thing that can happen is that it might have to calculate it multiple times.

Creating the multiplier eagerly would be the easier option, but I am not familiar enough with the library to tell whether it is a good idea or not, and I would be happy with either solution.

I am happy to raise a PR for either solution, but it would be good to discuss with a core developer which approach is better.

Thanks,
Gabor

**Comment by peterdettman** [comment]
Thanks for the report. We have now removed the synchronized keyword. We may in future look at eager initialization but the construction/configuration of ECCurve is quite complicated and there are backward-compatibility issues.

**Comment by gabor-hargitai-privitar** [comment]
Thanks Peter, do you know when will this make its way into a release? Also, I don't seem to be able to find the pull request or commit that removed the synchronized keyword.

**Comment by gabor-hargitai-privitar** [comment]
Ah, that makes sense. Thank you for your help

**Comment by gaellalire** [comment]
Hello,

I saw you removed the synchronized in code allowing multiple instances.
You can have both a single instance and good performance with double check locking.
The link below explain it

https://www.baeldung.com/java-singleton-double-checked-locking

However if you want best performances you should avoid volatile after the first access, see example below

```java
public class DclSingleton {
	
    // can be cached in processor memory
    private static DclSingleton instance;
    
    // will only be set when the object is fully initialized
    // volatile will work correctly only after Java 1.4
    private static volatile DclSingleton volatileInstance;
    
    public static DclSingleton getInstance() {
        if (instance == null) {
        	if (volatileInstance == null) {
                    synchronized (DclSingleton.class) {
                        if (volatileInstance == null) {
                            volatileInstance = new DclSingleton();
                        }
                    }
        	}
        	instance = volatileInstance;
        }
        return instance;
    }
 
}
```

**Comment by peterdettman** [comment]
@gaellalire Thanks for the suggestion. Currently all ECMultiplier implementations are very lightweight, so in this case it seems better to simply not bother, but such a pattern could be useful elsewhere.

**Comment by worsaae** [comment]
Please enlighten me. Why do this not break due to 'double checked locking
is broken'
https://www.cs.cornell.edu/courses/cs6120/2019fa/blog/double-checked-locking/
Wiki have a similar warning

Rgds Lars

tir. 13. okt. 2020 04.43 skrev Peter Dettman <notifications@github.com>:

**Comment by gaellalire** [comment]
@worsaae The answer is in your link, just search for "volatile".
Starting with JDK5 a volatile reference will not be set while the constructor job is not finished.
Your article also notes that volatile variable triggers cache coherence protocol, that why I'm using both a volatile and not volatile reference.
