### ISSUE TITLE
No able to get the key usage from the Key rings of PGP version 6.5.8 Network Associates

### ISSUE THREAD

**Issue by Susmit07** [bcgit/bc-java#779]
No able to get the key usage from the Key rings of PGP version 6.5.8 Network Associates

Iterator<PGPSignature> sigItr = secretKey.getPublicKey().getSignatures(); StringBuilder keyUsage = new StringBuilder(); while (sigItr.hasNext()) { PGPSignature sig = sigItr.next(); PGPSignatureSubpacketVector subPacks = sig.getHashedSubPackets(); if (subPacks != null) { if ((subPacks.getKeyFlags() & KeyFlags.ENCRYPT_COMMS) == 4) {

Expected behavior

It should fetch me the actual key usages, it's working for all keys except for PGP version 6.5.8 Network associates types key

** System (please complete the following information):**

OS: [Windows, Linux]
Java [1.8]

**Comment by martijnbrinkers** [comment]
With this bug report I don't think you will get much help. You need to provide more information, complete code and a test key ring.

**Comment by Susmit07** [comment]
Hello Martin thank you. Sharing the file

**Comment by Susmit07** [comment]
[secring.txt](https://github.com/bcgit/bc-java/files/5161627/secring.txt)

**Comment by Susmit07** [comment]
The java code file here it is 

[App.txt](https://github.com/bcgit/bc-java/files/5162592/App.txt)

**Comment by Susmit07** [comment]
@martijnbrinkers Any help will be highly appreciated as we have release round the corner, and it's a blacker. Thank you again

**Comment by martijnbrinkers** [comment]
It looks like the secring.txt file does not contain any "Key flags". Perhaps the software that created this did not support "Key flags". There are DSA and RSA keys. This is I think the old way of saying which keys can be used for what

From https://tools.ietf.org/html/rfc4880#section-13.5

> There are algorithm types for RSA Sign-Only, and RSA Encrypt-Only
   keys.  These types are deprecated.  The "key flags" subpacket in a
   signature is a much better way to express the same idea, and
   generalizes it to all algorithms.

**Comment by Susmit07** [comment]
Thank you for you response, then how do you suggest that i will deduce the E C S A usage, as when i import the file in GnuPG it is able to display all the 4 usages.

**Comment by martijnbrinkers** [comment]
My guess is that GnuPG allows the key to be used for all purposes if the key flags are missing assuming the public key is allowed for signing and/or encrypting. For example an Elgamal encrypt key can only be used for encryption.

**Comment by Susmit07** [comment]
How will I deduce the A usage out of ECSA?

I am doing secretKey.getPublicKey().getAlgorithm(), but how will I calculate  C and A

**Comment by Susmit07** [comment]
@martijnbrinkers can you please help me with the issue below

https://github.com/bcgit/bc-java/issues/792

I am stuck
