### ISSUE TITLE
Any possibility that bcprov and bc-fips co-exist

### ISSUE THREAD

**Issue by complanboy2** [bcgit/bc-java#783]
We are facing issues when upgrading the third-party libs which have transitive dependency with bcprov. 
To be specific OpenSAML, Cryptacular, iText-Kernel libraries. Their current versions depend on bcprov and do NOT have a version where they depend on bc-fips.

Now, given this scenario, we can not enforce to use  bc-fips unless the corresponding libraries upgrade themselves. So, in this case, is there a possibility that we continue to use bcprov for these libraries  while other libraries use bc-fips ?

TIA>

**Comment by dghgit** [comment]
Sorry, not in the same JVM.
