### ISSUE TITLE
Support for Ed25519ph and Ed448ph with Asn1SignatureFactory

### ISSUE THREAD

**Issue by JulesP96** [bcgit/bc-java#789]
Hi,

Currently Asn1SignatureFactory supports Ed25519 and Ed448 with algorithm identifier 1.3.101.112 and 1.3.101.113 however when using either 1.3.101.114 or 1.3.101.115 (respectively for Ed25519ph and Ed448ph) the signer fails with a signer not recognized error. 

I'm using the following documentation: https://tools.ietf.org/id/draft-ietf-curdle-pkix-03.html#rfc.section.10.1

Is there a way to sign a certificate with either of this algorithm?

Regards,

**Comment by peterdettman** [comment]
Firstly, this appears to be a question about the C# API, which has its own project at https://github.com/bcgit/bc-csharp .

As to the draft you link to, it ultimately became [RFC 8410](https://tools.ietf.org/html/rfc8410), which no longer specifies OIDs for Ed25519ph or Ed448ph.

We have crypto support for the Ed25519ph and Ed448ph algorithms but I believe Asn1SignatureFactory can only (currently) be used with algorithms for which we know an OID. Also there is not currently any way to specify the "context" parameter for EdDSA variants.

**Comment by JulesP96** [comment]
I am indeed using the C# version of bouncy castle. I honestly thought that the code underneath was similar and since this is not really a bug report I choose to ask the java community. 

Thanks for your explanation, I did notice that I was reading the draft version of the document. I did manage to implement ed25519ph and ed448ph signer. I'll give up for the certificate signature then. 

Regards,
