### ISSUE TITLE
Out of Memory Exception Streams.pipeAll

### ISSUE THREAD

**Issue by Susmit07** [bcgit/bc-java#792]
Hello Team,

Streams.pipeAll(((PGPLiteralData) message).getInputStream(), decryptedOutput);

I am seeing OOM error with the compressed file size of ~60Mb (uncompressed size ~7Gb). 

Java Stack | at   java/util/Arrays.copyOf(Arrays.java:3580(Compiled Code))   at java/io/ByteArrayOutputStream.grow(ByteArrayOutputStream.java:129(Compiled   Code))   at   java/io/ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:104(Compiled   Code))   at   java/io/ByteArrayOutputStream.write(ByteArrayOutputStream.java:164(Compiled   Code))   at org/bouncycastle/util/io/Streams.pipeAll(Bytecode PC:23(Compiled Code))   at     

Any help will be appreciated

**Comment by peterdettman** [comment]
What are you trying to write 7GB of output to a ByteArrayOutputStream?

**Comment by Susmit07** [comment]
@peterdettman we are writing back the byte array to the UI to generate a report, yes the 7 gb file is creating the OOM, can you suggest an ideal way to write a large content to the output stream

**Comment by peterdettman** [comment]
This forum is for questions related to the bc-java project, not general programming advice.

Either don't write 7GB of output, or write it to an OutputStream that can accept it. You may be able to get an answer at e.g. https://stackoverflow.com , but I would recommend you explain better what you are trying to do.
