### ISSUE TITLE
Support of EdDSA with JDK 15

### ISSUE THREAD

**Issue by bsanchezb** [bcgit/bc-java#797]
In the latest JDK 15 an EdDSA algorithm support has been introduced : https://openjdk.java.net/jeps/339
The classes [EdDSAPrivateKeyImpl](https://github.com/openjdk/jdk15/blob/master/src/jdk.crypto.ec/share/classes/sun/security/ec/ed/EdDSAPrivateKeyImpl.java) and [EdDSAPublicKeyImpl](https://github.com/openjdk/jdk15/blob/master/src/jdk.crypto.ec/share/classes/sun/security/ec/ed/EdDSAPublicKeyImpl.java) are used for the keys definition.

The BC class [SignatureSpi](https://github.com/bcgit/bc-java/blob/master/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/edec/SignatureSpi.java) fails to initialize the signer because newly introduced key implementations are not supported.

Would be nice to add a support of JDK's EdDSA implementation into BC.

Best regards,
Aleksandr.

**Comment by dghgit** [comment]
Which version of BC are you using?

**Comment by bsanchezb** [comment]
Hello, yes, the current version we use is 1.66. It seems to be not supported so far.

**Comment by dghgit** [comment]
Weird, do you see the multi-release classes for it in the jar file? (under META-INF/versions).

**Comment by bsanchezb** [comment]
We load two BC modules with Maven : _bcprov-jdk15on_ and _bcpkix-jdk15on_

**Comment by dghgit** [comment]
Have you got a small sample program that shows the issue - it could just be that we've not covered everything off.

**Comment by bsanchezb** [comment]
Here is a simple test that passes in Java 14 and fails with Java 15:
```
@Test
public void bcTest() throws Exception {
	String base64Cert = "MIICKzCCAd2gAwIBAgICBEwwBQYDK2VwMFUxGDAWBgNVBAMMD0VkMjU1MTktZ29vZC1jYTEZMBcGA1UECgwQTm93aW5hIFNvbHV0aW9uczERMA8GA1UECwwIUEtJLVRFU1QxCzAJBgNVBAYTAkxVMB4XDTE5MTExNDA2MzgzOVoXDTIxMDkxNDA1MzgzOVowVzEaMBgGA1UEAwwRRWQyNTUxOS1nb29kLXVzZXIxGTAXBgNVBAoMEE5vd2luYSBTb2x1dGlvbnMxETAPBgNVBAsMCFBLSS1URVNUMQswCQYDVQQGEwJMVTAqMAUGAytlcAMhAB+6MntRr6dWLmCC8uZfoMWhxMRHPDnrTVz8wJIlzW88o4HOMIHLMA4GA1UdDwEB/wQEAwIGQDCBmQYIKwYBBQUHAQEEgYwwgYkwQQYIKwYBBQUHMAGGNWh0dHA6Ly9kc3Mubm93aW5hLmx1L3BraS1mYWN0b3J5L29jc3AvRWQyNTUxOS1nb29kLWNhMEQGCCsGAQUFBzAChjhodHRwOi8vZHNzLm5vd2luYS5sdS9wa2ktZmFjdG9yeS9jcnQvRWQyNTUxOS1nb29kLWNhLmNydDAdBgNVHQ4EFgQU5Cf9+sOF2L2SNadlEriSE3erKE8wBQYDK2VwA0EA1kdAmC8cIRFVg10R/P++5Wru9fYcUhLjwVN85Uwq/a4JyKfoamxv9hlEq9LWkgJ1QKT3/VDngQ1+pyPrYmXDCA==";
	byte[] certBinaries = Base64.getDecoder().decode(base64Cert);
	try (InputStream is = new ByteArrayInputStream(certBinaries)) {
		CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
		Certificate certificate = certificateFactory.generateCertificate(is);

		Signature signature = Signature.getInstance("Ed25519", "BC");
		signature.initVerify(certificate.getPublicKey());
	}
}
```

**Comment by dghgit** [comment]
Ah, so you're trying to auto-convert a SunEC key into a BC one without using a key factory... Hmmm... I think we can support that.

Try 167b07 now available in https://www.bouncycastle.org/betas and let me know how you go.

**Comment by bsanchezb** [comment]
Hello again,

I've executed the test with 167b07 and indeed it seems working now with JDK 15!

Thank you! Looking forward for the 1.67 release. 

The issue can be closed.

Best regards,
Aleksandr.

**Comment by bsanchezb** [comment]
Seems working well with 1.67 version.
I close the ticket.

Regards,
Aleksandr.
