### ISSUE TITLE
RSA KeyFactory does not prefer RSAPrivateCrtKeySpec

### ISSUE THREAD

**Issue by SalusaSecondus** [bcgit/bc-java#798]
`RSAPrivateCrtKeySpec` inherits from `RSAPrivateKeySpec` and it appears that the intent of Java is for an RSA KeyFactory to opportunistically return an instance of `RSAPrivateCrtKeySpec` even when `RSAPrivateKeySpec` is requested (if possible). (This intent is also supported by the [order of the if branches in JDK8](https://github.com/corretto/corretto-8/blob/develop/src/jdk/src/share/classes/sun/security/rsa/RSAKeyFactory.java#L423-L441). Please note that there is [another bug](https://bugs.openjdk.java.net/browse/JDK-8254717) in the current JDK implementation which should not be duplicated.)

However, the [BouncyCastle implementation of the RSA KeyFactory](https://github.com/bcgit/bc-java/blob/07604208a773d2334fb09276796288404804e557/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/rsa/KeyFactorySpi.java#L49-L65) checks for a match against `RSAPrivateKeySpec` first and so will not return the more detailed `KeySpec` unless explicitly requested. This means that the CRT parameters will be lost and any keys created from the returned KeySpec will lack the CRT parameters and be less efficient.

**Comment by dghgit** [comment]
Yes, I'd agree that's less than ideal. This is now fixed properly in 1.67b06. You should find it on:

https://www.bouncycastle.org/betas

soon. Thanks for the report.
