### ISSUE TITLE
IOException in SubjectPublicKeyInfo.getEncoded 

### ISSUE THREAD

**Issue by FlorianDeutsch-secryptGmbH** [bcgit/bc-java#799]
When i parse the current Telesec's ocsp signing certificate and try to get the encoded public key, an IOException occures.
java.io.IOException: corrupted stream - out of bounds length found: 93 >= 65
	at org.bouncycastle.asn1.DefiniteLengthInputStream.toByteArray(DefiniteLengthInputStream.java:133)

Here is the test code:

@Test
	public void telesecKeyError1() throws IOException{

		byte[] certB = DatatypeConverter.parseHexBinary(
				"30820336308202DAA00302010202100A7871741F9CD8043A689CAEE637A14B300C06082A8648CE3D04030205003071310B3009060355040613024445311C301A060355040A0C1344657574736368652054656C656B6F6D2041473123302106035504030C1A54656C6553656320504B53206549444153205145532043412031311F301D06035504610C165553742D49644E722E20444520313233343735323233301E170D3230303430383130303830305A170D3231303431313233353930305A307D310B3009060355040613024445311C301A060355040A0C1344657574736368652054656C656B6F6D204147311F301D06035504610C165553742D49644E722E20444520313233343735323233312F302D06035504030C264F4353502D5369676E65722054656C6553656320504B532065494441532051455320434120313059301306072A8648CE3D020106082A8648CE3D030107034200045DF9C8AAB104D4E13FF958E155588C6BA1EAD93AC83EF1653A8EB452E578D6371C39DB5D81D8E651FA4F9EDC334B89EAB8B2D6F1A162FBB906396A9A57207C90A382014430820140301F0603551D23041830168014FFF489EA75ACC5D3D22434F9652A06F2CCE9BA81301D0603551D0E0416041419A9D7E99251850FE2D4DBBF0834450F1919BFDD300E0603551D0F0101FF04040302064030130603551D25040C300A06082B06010505070309300C0603551D130101FF04023000303F0603551D2004383036303406092B06010401BD470D1B3027302506082B060105050702011619687474703A2F2F706B732E74656C657365632E64652F63707330818906082B06010505070101047D307B304B06082B06010505073002863F687474703A2F2F7471726361312E706B692E74656C657365632E64652F6372742F54656C655365635F504B535F65494441535F5145535F43415F312E637274302C06082B060105050730018620687474703A2F2F6F6373702E706B732E74656C657365632E64652F6F63737072300C06082A8648CE3D040302050003480030450220652D10F9DB6C0BA4DBD0353B48074EB1679E29C91A5CE7A53A59DF4B6671833C0221008B8B9CCB01D70D9CA7BA466486B8C18D579547DC938F5E1498508A3C3ECC6466");

		X509CertificateHolder h= new X509CertificateHolder(certB);
		SubjectPublicKeyInfo sk = h.getSubjectPublicKeyInfo();
		byte[] certEncoded = h.getEncoded();
		byte[] kh = sk.parsePublicKey().getEncoded();
	}

A possible workarround is using the ASN1 objects instead of X509CertificateHolder. This method works:
private byte[] getSubjectPublicKeyInfoBytes(byte[] c) throws IOException {
		ASN1Encodable co = ASN1Primitive.fromByteArray(c);
		DLSequence cos = (DLSequence) co;
		DLSequence tbs = (DLSequence) cos.getObjectAt(0);
		DLSequence sk = (DLSequence) tbs.getObjectAt(6);
		DERBitString pk = (DERBitString) sk.getObjectAt(1);
		return pk.getBytes();
	}

**Comment by dghgit** [comment]
The encoded public key is the data represented by the encoding of the SubjectPublicKeyInfo (assuming you want to use it with an X509EncodedKeySpec). As it's an EC key the bit string is made up of an EC point encoding. While this is "an encoding" the format is not related to ASN.1 and so it cannot be parsed using the parsePublicKey() method.
