### ISSUE TITLE
X500Name hashcode is not thread safe

### ISSUE THREAD

**Issue by AdamXiaotCao** [bcgit/bc-java#806]
The way X500Name calculates hashcode is not thread safe.

https://github.com/bcgit/bc-java/blob/master/core/src/main/j2me/org/bouncycastle/asn1/x500/X500Name.java#L243-L252

This is because we are updating `isHashCodeCalculated` to true before we are updating `hashCodeValue`.

We can solve this by moving the hashcode calculation into the constructors.

**Comment by martijnbrinkers** [comment]
It looks like calculating the hash code is a heave operation (see AbstractX500NameStyle) so this is something you only want to do when you have to and therefore better not doing it in the constructor. One option might be to make hashCode thread safe. That said, if a class does not explicitly says that it's thread safe, you must assume it's not.

**Comment by AdamXiaotCao** [comment]
We can also reorder those statements inside hashCode() if the hashcode calculation is consistent. Would that be okay?

**Comment by dghgit** [comment]
It's an improvement. Patch for this now merged.
