### ISSUE TITLE
DSAOutputVerifier return negative sig sometimes.

### ISSUE THREAD

**Issue by Ricord** [bcgit/bc-java#817]
version: java fips 1.0.2

description: Sometimes, the org.bouncycastle.crypto.general.DSAOutputVerifier will return negative sig when in default DSA situation. When the raw bytes were decoded, then you use ASN1Integer.getInstance(s.getObjectAt(0)).getValue(); to generate the BigInteger. However, it cannot promise to return the positive value. When using the sig to verify it, the result is false. 

But we should return the positive value here.

**Comment by dghgit** [comment]
No, a negative means the signature is invalid and should not be accepted. Please inform whoever is generating these signatures of the issue.
