### ISSUE TITLE
X509CertificateImpl.toString() throws exception if signature is shorter than 20 bytes

### ISSUE THREAD

**Issue by mkarasik** [bcgit/bc-java#819]
https://github.com/bcgit/bc-java/blob/master/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/x509/X509CertificateImpl.java#L496

There is no signature lengh validation. An invalid signature shouldn't affect toString() function.

**Comment by dghgit** [comment]
Fixed in 167b06, see https://www.bouncycastle.org/betas Thanks for the report.
