### ISSUE TITLE
PKIFailureInfo javadocs and constants are mismatched

### ISSUE THREAD

**Issue by amberream** [bcgit/bc-java#821]
The ints assigned in the javadocs for PKIFailureInfo do not match the ints defined as constants in the source.  For example, look at the first 7 bits.  From the javadocs:
```
 * PKIFailureInfo ::= BIT STRING {
 * badAlg               (0),
 *   -- unrecognized or unsupported Algorithm Identifier
 * badMessageCheck      (1), -- integrity check failed (e.g., signature did not verify)
 * badRequest           (2),
 *   -- transaction not permitted or supported
 * badTime              (3), -- messageTime was not sufficiently close to the system time, as defined by local policy
 * badCertId            (4), -- no certificate could be found matching the provided criteria
 * badDataFormat        (5),
 *   -- the data submitted has the wrong format
 * wrongAuthority       (6), -- the authority indicated in the request is different from the one creating the response token
 * incorrectData        (7), -- the requester's data is incorrect (for notary services)
```
And from the source:
```
    public static final int badAlg               = (1 << 7); // unrecognized or unsupported Algorithm Identifier
    public static final int badMessageCheck      = (1 << 6); // integrity check failed (e.g., signature did not verify)
    public static final int badRequest           = (1 << 5);
    public static final int badTime              = (1 << 4); // -- messageTime was not sufficiently close to the system time, as defined by local policy
    public static final int badCertId            = (1 << 3); // no certificate could be found matching the provided criteria
    public static final int badDataFormat        = (1 << 2);
    public static final int wrongAuthority       = (1 << 1); // the authority indicated in the request is different from the one creating the response token
    public static final int incorrectData        = 1;        // the requester's data is incorrect (for notary services)
```
i..e The docs say the first bit indicates "bad algorithm", the source shows the first bit indicates "incorrect data".  Note that the javadocs are in increasing order, but the constants are in reverse order...

**Comment by peterdettman** [comment]
It's confusing, but not an error. badAlg (0) refers to its position within the BIT STRING, an ASN.1 type. Here we are dealing with a BER encoding, so according to X.690 8.6.2.1:

> The bits in the bitstring value, commencing with the leading bit and proceeding to the trailing bit, shall be placed in bits 8 to 1 of the first subsequent octet, followed by...

Bit 8 is the MSB, so it's a bit weird. The actual constants in the class are intended as masking values for use with PKIFailureInfo.intValue(), which returns the octets in little-endian order, but the bytes themselves still have the original big-endian order.

**Comment by amberream** [comment]
Ok got it, that helps.  So if I get a failure status of 0x4 for example, that corresponds to 0000100.  Which is 5 in the bit string or 1 << 2 in the code so it's bad data format.

The docs do already say it's a bit string... But maybe some added explanation would help clarify this for others?  Although I'm apparently the first person to be confused by this. :-)
