### ISSUE TITLE
PKCS12: InvalidKeyException pad block corrupted

### ISSUE THREAD

**Issue by melloware** [bcgit/bc-java#823]
**Version:**
BouncyCastle 1.66

**Environment:**
```
Java version: 1.8.0_265, vendor: AdoptOpenJDK, 
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Issue:**
We are using a PFX file from a vendor that according to all our tools and using it in the browser it works fine.    Other certificates from this vendor load fine but we have had a few that don't with the same error.

The error when trying to use BC 1.66 to load the certifcate is `java.io.IOException: exception unwrapping private key - java.security.InvalidKeyException: pad block corrupted`.  

**Stack trace:**
```
java.io.IOException: exception unwrapping private key - java.security.InvalidKeyException: pad block corrupted
        at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.unwrapKey(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
        at java.base/java.security.KeyStore.load(KeyStore.java:1479)
```

**Reproducer:**
```java
if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
      Security.addProvider(new BouncyCastleProvider());
}

final InputStream certStream = new BufferedInputStream(FileUtils.openInputStream(certFile));
final KeyStore keystore = KeyStore.getInstance("PKCS12", BouncyCastleProvider.PROVIDER_NAME);
keystore.load(inputStream, password.toCharArray());
```

I can provide the PFX cert and password so developers can test and see the problem.  Please provide an email address where I should send it to.  I do not want to attach it to this ticket for obvious reasons.

**Comment by dghgit** [comment]
feedback-crypto@bouncycastle.org

**Comment by dghgit** [comment]
Okay, I had a look at the key and then disposed of it.

I don't understand how this would work in anything. The keystore is PKCS12 using a SHA-256 mac, that much works okay. The key stored inside it is encrypted using PBKDF2 with an iteration count of 2000 and an 8 byte nonce. The PRF in use is HMAC-SHA256.

The key encryption algorithm is AES-256. It's clear from the start of the keystream that the data is not decrypting correctly and as expected it terminates with pad block corrupted error.

I do not believe the key has been wrapped correctly with a key generated with PBKDF2. I can say this with some confidence as we do pass the ACVP tests for PBKDF2, so it seems unlikely the BC implementation is failing. For what it's worth I also checked this with the JVM's version. It also failed.

**Comment by melloware** [comment]
Thank you. This is our only cert behaving this way so it seems invalid. Thank you for investigating.

**Comment by dghgit** [comment]
Thanks for the report. This wasn't actually the same thing. I've been able to reproduce it and fix it though - it's actually an issue with cipher precedence when using the key tool. BC 1.70 will take care of the problem.
