### ISSUE TITLE
PGPEncryptedDataGenerator working slow on executable Jar

### ISSUE THREAD

**Issue by xianlong198x** [bcgit/bc-java#824]
Hi, 

Currently, I am working on a project which used the encryption method OpenPGP.
Everything going well until I deploy the application as executable Jar with

`<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<executable>true</executable>
				</configuration>
			</plugin>`

The method 
`PGPEncryptedDataGenerator cPk = new PGPEncryptedDataGenerator(
                new JcePGPDataEncryptorBuilder(PGPPBEEncryptedData.AES_256)
                        .setSecureRandom(new SecureRandom())
                        .setProvider(BouncyCastleProvider.PROVIDER_NAME));
cPk.addMethod(new JcePublicKeyKeyEncryptionMethodGenerator(encKey).setProvider(BouncyCastleProvider.PROVIDER_NAME));
        byte[] bytes = bOut.toByteArray();
        try( OutputStream cOut = cPk.open(out, bytes.length)) {
            cOut.write(bytes);
        } catch (IOException | PGPException ex) {
            log.error("error encrypt data in PGPEncrypt", ex);
        }`

the line cPk.open(out, bytes.length)  ran very slow (take 2 minutes more).
But when I ran it into IDE env, everything became normal again.

After that, I have to copy all dependencies to an output directory and everything worked fine
`<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>
								${project.build.directory}/libs
							</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<classpathPrefix>libs/</classpathPrefix>
							<mainClass>
								com.example.MyMainApplication
							</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>`

Please help...!

**Comment by dghgit** [comment]
I'd suspect it's having trouble finding the regular JVM seed generator and has to run using the old threaded seed generator. That could explain the performance hit.

**Comment by dghgit** [comment]
Closed as no further details.
