### ISSUE TITLE
DH Implementation classes are missing from bcprov 1.4.7

### ISSUE THREAD

**Issue by vthangar0202** [bcgit/bc-java#826]
We were using the below DH implementation classes from bcprov-jdk15-1.44 in our product . 

               put("AlgorithmParameterGenerator.DH", "org.bouncycastle.jce.provider.JDKAlgorithmParameterGenerator$DH");
		put("Alg.Alias.AlgorithmParameterGenerator.DIFFIEHELLMAN", "DH");
		
		put("AlgorithmParameters.DH", "org.bouncycastle.jce.provider.JDKAlgorithmParameters$DH");
		put("Alg.Alias.AlgorithmParameters.DIFFIEHELLMAN", "DH");
		
		put("KeyAgreement.DH", "org.bouncycastle.jce.provider.JCEDHKeyAgreement");
		put("Alg.Alias.KeyAgreement.DIFFIEHELLMAN", "DH");
		
		put("KeyPairGenerator.DH", "org.bouncycastle.jce.provider.JDKKeyPairGenerator$DH");
		put("Alg.Alias.KeyPairGenerator.DIFFIEHELLMAN", "DH");
		
		put("KeyFactory.DH", "org.bouncycastle.jce.provider.JDKKeyFactory$DH");
		put("Alg.Alias.KeyFactory.DIFFIEHELLMAN", "DH");_

It looks those classes and all removed from the **version 1.47**. All of them moved to some other classes?  
If we upgrade to **bcprov-jdk15on-1.60** or **bc-fips-1.0.2** ,  which classes i need to refer. Could you please help me.

**Comment by dghgit** [comment]
You can find out where they were moved by looking in org.bouncycastle.jcajce.provider.asymmetric.DH

There's no equivalent in FIPS, I would strongly recommend only invoking these via the JCE.
