### ISSUE TITLE
The commit "updated CMP classes for new RFC profile" may be incorrect

### ISSUE THREAD

**Issue by xipki** [bcgit/bc-java#828]
Related to the [commit updated CMP classes for new RFC profile](https://github.com/bcgit/bc-java/commit/0d152d8505940fd1a178b2a0865b86b546b1003c). Which RFC new profile do you mean here? According to https://tools.ietf.org/html/rfc4210 nothing should have been changed to the definition of CertifiedKeyPair.

BTW, even the standard changes, please do not just remove existing public methods or change the method signature, instead you may mark it as deprecated. Otherwise, the existing application (e.g. my open-source PKI project https://github.com/xipki/xipki) cannot use the newest version (v1.67) of BC.

**Comment by dghgit** [comment]
Sorry about that. Okay, the update is from here:

https://tools.ietf.org/html/draft-ietf-lamps-cmp-updates-06

I did try to minimize the changes, but there are other drafts and projects that depend on the updated syntax. If there's anything we can do to improve backwards compatibility please feel free to suggest it.

**Comment by xipki** [comment]
Since you changed the return type of CertOrEncCert.getEncryptedCert(), and CertifiedKeyPair.getPrivateKey() from EncrytedValue to EncryptedKey, it is not possible to provide a version providing backwards compatibility to both 1.67 and 1.66-.

Before the release of 1.67, I can image the following solution:

`CertOrEncCert.java`:
   `EncryptedValue getEncryptedCert()` (remaing unchanged as in v1.66)
   `EncryptedKey getEncryptedCertEK()` (newly added in v1.67)

`CertifiedKeyPair.java`:
   `EncryptedValue getPrivateKey()` (remaing unchanged as in v1.66)
   `EncryptedKey getPrivateKeyEK()` (newly added in v1.67)

**Comment by dghgit** [comment]
You could use reflection, or just rewrite that section to use the underlying sequence. I'd be happy to help with that. Strictly speaking, for other reasons, you do want people to get off 1.66 though. I would recommend moving to 1.67 and advising your users to do likewise.

**Comment by dghgit** [comment]
Sorry about  the late notice, but 1.68 will be coming out around December 17. Please ensure you have moved to 1.67 by then and please advise your users to do likewise. If you have any questions about this, please feel free to email me directly.

**Comment by dghgit** [comment]
Closing as inactive.
