### ISSUE TITLE
Support for the Jakarta Mail library

### ISSUE THREAD

**Issue by phax** [bcgit/bc-java#832]
Hi guys,
It would be great if you could provide a version that supports the Jakarta Mail library using the "jakarta" package names.
There was already a discussion on the mailing list http://bouncy-castle.1462172.n4.nabble.com/Bouncy-Castle-s-S-Mime-library-and-the-future-of-the-JavaMail-project-td4659985.html which clearly startes, that this is inevitable for the future.

According to https://eclipse-ee4j.github.io/mail/ the minimum Java version for this is 1.8, so that will be an issue for the < 1.8 JDK versions....

Thanks in advance,
Philip

**Comment by dghgit** [comment]
There's now a bcjmail API available in https://www.bouncycastle.org/betas

**Comment by phax** [comment]
Cool thanks

**Comment by yersan** [comment]
Hello @dghgit, my understanding is BC mail will be released in two flavors; bcmail.jar (javax) and bcjmail.jar (Jakarta). 
So, we will be able to use any of them based on whether we are in a Jakarta EE environment. Would you mind confirming if that is correct? Thank you!

**Comment by dghgit** [comment]
Yes, that's the plan. At the moment it's a simple text substitution for all but the handlers. We'll just have to see how we go in future - the libraries will eventually diverge and at that point we may need to make a decision about what we keep supporting, but there's no problem at the moment.

**Comment by yersan** [comment]
Ok, thank you very much for confirming it.
