### ISSUE TITLE
Please remove test classes from lib

### ISSUE THREAD

**Issue by yschimke** [bcgit/bc-java#834]
e.g. org.bouncycastle.jsse.provider.test.KeyManagerFactoryTest in bctls-jdk15to18-1.67.jar

![image](https://user-images.githubusercontent.com/231923/99141910-bc61ed80-2647-11eb-815c-eeeaa088d79c.png)

**Comment by dghgit** [comment]
Sorry about that. I've worked out how it happened. It shouldn't happen again. Thanks for the report.
