### ISSUE TITLE
Is there any way to invoke as public BCECPublicKey getpublicKey() in class BCECPrivateKey?

### ISSUE THREAD

**Issue by SamYuan1990** [bcgit/bc-java#835]
https://github.com/bcgit/bc-java/blob/07604208a773d2334fb09276796288404804e557/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/ec/BCECPrivateKey.java#L46

**Comment by SamYuan1990** [comment]
I want to get public key from private key.
I want to invoke as
```java
pubkey = privKey.getPublickey();
```

**Comment by SamYuan1990** [comment]
or is there any existing sample for me to reference?

**Comment by czdsdo** [comment]
定义sm2曲线参数，使用私钥的D恢复出公钥的XY值。曲线上运算（X,Y）=DG。G为曲线上基点
	`import org.bouncycastle.crypto.generators.ECKeyPairGenerator;
import org.bouncycastle.crypto.params.ECDomainParameters;
import org.bouncycastle.crypto.params.ECKeyGenerationParameters;
import org.bouncycastle.crypto.signers.DSAKCalculator;
import org.bouncycastle.crypto.signers.RandomDSAKCalculator;
import org.bouncycastle.math.ec.ECCurve;
import org.bouncycastle.math.ec.ECFieldElement;
import org.bouncycastle.math.ec.ECPoint;

public class SM2 
{

public static String[] ecc_param = { 
		"FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFF",
		"FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFC",
		"28E9FA9E9D9F5E344D5A9E4BCF6509A7F39789F515AB8F92DDBCBD414D940E93",
		"FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFF7203DF6B21C6052B53BBF40939D54123",
		"32C4AE2C1F1981195F9904466A39C9948FE30BBFF2660BE1715A4589334C74C7",
		"BC3736A2F4F6779C59BDCEE36B692153D0A9877CC62A474002DF32E52139F0A0"
	};

	public static SM2 Instance() 
	{
		return new SM2();
	}
	private final DSAKCalculator kCalculator = new RandomDSAKCalculator();
	public final BigInteger ecc_p;
	public final BigInteger ecc_a;
	public final BigInteger ecc_b;
	public final BigInteger ecc_n;
	public final BigInteger ecc_gx;
	public final BigInteger ecc_gy;
	public final ECCurve ecc_curve;
	public final ECPoint ecc_point_g;
	public final ECDomainParameters ecc_bc_spec;
	public final ECKeyPairGenerator ecc_key_pair_generator;
	public final ECFieldElement ecc_gx_fieldelement;
	public final ECFieldElement ecc_gy_fieldelement;
    //素数域椭圆曲线
	public SM2() 
	{   //素数
		this.ecc_p = new BigInteger(ecc_param[0], 16);
		this.ecc_a = new BigInteger(ecc_param[1], 16);
		this.ecc_b = new BigInteger(ecc_param[2], 16);
		this.ecc_n = new BigInteger(ecc_param[3], 16);
		this.ecc_gx = new BigInteger(ecc_param[4], 16);
		this.ecc_gy = new BigInteger(ecc_param[5], 16);
		//根据a,b,p创建曲线
		//基域：Fp为素数域，F2m为二元扩域
		this.ecc_curve = new ECCurve.Fp(this.ecc_p, this.ecc_a, this.ecc_b);
		this.ecc_gx_fieldelement = ecc_curve.fromBigInteger(this.ecc_gx);
		this.ecc_gy_fieldelement = ecc_curve.fromBigInteger(this.ecc_gy);
        this.ecc_point_g =ecc_curve.createPoint(ecc_gx, ecc_gy);
		/*this.ecc_gx_fieldelement = new Fp(this.ecc_p, this.ecc_gx);
		this.ecc_gy_fieldelement = new Fp(this.ecc_p, this.ecc_gy);*/
		//this.ecc_curve = new ECCurve.Fp(this.ecc_p, this.ecc_a, this.ecc_b);
		//this.ecc_point_g = new ECPoint.Fp(this.ecc_curve, this.ecc_gx_fieldelement, this.ecc_gy_fieldelement);
		this.ecc_bc_spec = new ECDomainParameters(this.ecc_curve, this.ecc_point_g, this.ecc_n);
		ECKeyGenerationParameters ecc_ecgenparam;
		ecc_ecgenparam = new ECKeyGenerationParameters(this.ecc_bc_spec, new SecureRandom());
		this.ecc_key_pair_generator = new ECKeyPairGenerator();
		this.ecc_key_pair_generator.init(ecc_ecgenparam);
		kCalculator.init(this.ecc_n, new SecureRandom());
	}
}
	public byte[] priToPubKey(byte[]privateKey){
                SM2 factory = SM2.Instance();
		BigInteger userD = new  BigInteger(1,privateKey);
		ECPoint userKey = factory.ecc_point_g.multiply(userD);
		byte[] pubx =userKey.getXCoord().getEncoded();
                byte[] puby =userKey.getYCoord().getEncoded();
                byte[] pubkbytes = userKey.getEncoded(false);
        return pubkbytes ;
    }`
