### ISSUE TITLE
bc jars in -Xbootclasspath causing cipher issues

### ISSUE THREAD

**Issue by SubhraB** [bcgit/bc-java#836]
I was going through the bc source code. Looking at this method org.bouncycastle.jsse.provider.FipsUtils.lookup("org.bouncycastle.crypto.fips.FipsNonceGenerator").

My issue is, when I try to load the bc-fips and bctls-fips jar via -Xbootclasspath/a option, the above method always returns null resulting in GCM ciphers getting excluded. And causing "no common cipher suites" error.

But when I load the jars using regular classpath, everything works fine.

We are going fully fips compliant and we are supposed to embed this jars into our jvm via -Xbootclasspath/a .

Is there any other solution to this?

**Comment by gstanchev** [comment]
Why "full fips" requires to load BCFIPS via -Xbootclasspath/a?

**Comment by SubhraB** [comment]
Thank you for responding. We need the bc jars to be available to both the application as well as the "-javaagent" process. Only way its possible is xbootclasspath.

**Comment by SubhraB** [comment]
It will be nice to have one combined bc-fips and bctls-fips jar. That will resolve our issue.

**Comment by gstanchev** [comment]
I am just an observer, not part of the BC team, but wondering why do you think the FIPS libraries need to be loaded through the boot classloader to be "fully compliant". Have you considered passing them through "-Djava.ext.dirs=/path/to/fips/libs"?

**Comment by SubhraB** [comment]
It looks like "-Djava.ext.dirs" is no longer supported since jdk 9. Only way is  "-Xbootclasspath/a" right now.

**Comment by SubhraB** [comment]
@peterdettman could you help with this?

**Comment by peterdettman** [comment]
This is due to `getClassLoader` returning null for classes loaded by the bootstrap class loader, which then causes a NullPointerException in the `lookup` method. We have fixed this and successfully tested it using `-Xbootclasspath/a`. A new snapshot version of bctls-fips-1.0.11 contains the fix, and it will appear in the next full release, expected in a couple of weeks.

**Comment by SubhraB** [comment]
Thank you!!!
