### ISSUE TITLE
Feature request: Add AES-GCM-SIV

### ISSUE THREAD

**Issue by MariusVolkhart** [bcgit/bc-java#840]
AES-GCM-SIV offers an alternative to AES-GCM with improved nonce collision resistance, thus making it more suitable for AEAD scenarios where a random nonce is used than existing solutions such as AES-GCM.

**Comment by mouse07410** [comment]
I second this request. 

From cryptographic point of view AES-GCM-SIV is much stronger/safer than AES-GCM. 

Please add it.

**Comment by dghgit** [comment]
This is now added to the lightweight API in the current beta at https://www.bouncycastle.org/betas

**Comment by mouse07410** [comment]
Thank you!

Looking forward to seeing it in the bcprov-ext.

P.S. "Improved nonce collision resistance" here means the difference between catastrophic failure if **one** collision occurs, and ability to reuse nonce values (practically) at will.

**Comment by dghgit** [comment]
This is now also added as GCM-SIV in the latest beta for the JCE provider as well. See https://www.bouncycastle.org/betas for details.

**Comment by mouse07410** [comment]
I must say - thank you!

**Comment by dghgit** [comment]
And thank you!

**Comment by debjitk** [comment]
Thank you

**Comment by Jeeppler** [comment]
A big thank you from my side as well.

**Comment by thomasmost** [comment]
Hi, sorry to raise this issue from the dead, but what is the algorithm identifier for AES-SIV? I've tried `AES-GCM-SIV`, `AES-SIV`, `GCM-SIV` etc to no avail. Each time I get

`java.security.NoSuchAlgorithmException: No such algorithm: GCM-SIV`
