### ISSUE TITLE
org.bouncycastle.util.encoders.DecoderException: unable to decode base64 string: invalid characters encountered in base64 data

### ISSUE THREAD

**Issue by devOpsDocker1x** [bcgit/bc-java#843]
i got  the DecoderException using this lib from bouncycastle, i konw is not latest version but i used too the version xxx-jdk16to18 but i got same issue.

Maven depencencies:
		
`<dependency>`
		    `<groupId>org.bouncycastle</groupId>`
		   ` <artifactId>bcprov-jdk15on</artifactId>`
		    `<version>1.67</version>`
		`</dependency>`
		`<dependency>`
		    `<groupId>org.bouncycastle</groupId>`
		    `<artifactId>bcpkix-jdk15on</artifactId>`
		    `<version>1.67</version>`
		`</dependency>`
		`<dependency>`
		    `<groupId>org.bouncycastle</groupId>`
		    `<artifactId>bcprov-ext-jdk15on</artifactId>`
		    `<version>1.66</version>`
		`</dependency>`

Someone do know how fix it?

**Comment by peterdettman** [comment]
Show the exception please, and we'll probably need an example piece of data that fails to decode.

**Comment by dghgit** [comment]
closed as inactive and insufficient information.
