### ISSUE TITLE
Clone hash algorithm, when cloning NTRUEncryptionParameters

### ISSUE THREAD

**Issue by rhergenreder** [bcgit/bc-java#844]
Hello,

as I'm using multiplie instances of the `NTRUEngine` to run encryptiom/decryption multi-threaded, I also need to ensure that the `NTRUEncryptionParameters` returned by the constants in `NTRUEncryptionKeyGenerationParameters` don't share any internal instances. 
However, when calling `NTRUEncryptionKeyGenerationParameters.getEncryptionParameters()` or `NTRUEncryptionParameters.clone()`, new `NTRUEncryptionParameters` instaces are created while the internal `Digest hashAlg` instance is just passed via constructor without cloning it. This causes unexpected behaviour in parallel computations. Is there any better approach than the following?

```
private NTRUEncryptionParameters copyParameters(NTRUEncryptionKeyGenerationParameters params) {
    NTRUEncryptionParameters newParams = params.getEncryptionParameters();
    if (newParams.hashAlg instanceof SHA256Digest) {
      newParams.hashAlg = new SHA256Digest();
    } else if (newParams.hashAlg instanceof SHA512Digest) {
      newParams.hashAlg = new SHA512Digest();
    } else {
      throw new UnsupportedOperationException("Hash algorithm clone not implemented for: " + newParams.hashAlg.getClass().getSimpleName());
    }

    return newParams;
  }
```

**Comment by peterdettman** [comment]
I think most of our digests implement `org.bouncycastle.util.Memoable`. Just check for the interface, cast, and call `copy`.

**Comment by dghgit** [comment]
This should now be fixed in 169b05, see https://www.bouncycastle.org/betas for details.
