### ISSUE TITLE
DL-Encoding produces mixed DL- and DER-output 

### ISSUE THREAD

**Issue by martin2306** [bcgit/bc-java#845]
Hello everybody,

I have code, that reads DL-encoded signatures, updates them and rewrites them, DL-encoded, back to file.
This worked for years, but now, since at least version 1.64, the resulting signatures are verified as being technically invalid.

The reason for this is the following (as I think):

Many classes such as `ASN1Set`, `ASN1Sequence`, `ASN1TaggedObject` etc. exist in a DER- and a DL-encoding variant implemented as subclasses, e.g. `DERSet` and `DLSet`. Dependent whether you want to produce an DER- or DL-encoded output, internally `DEROutputStream` or `DLOutputStream` is used to generate the encoded result. 
The `*OutputStream` objects use either the respective DER- or the DL-version of the primitive for encoding, by switching to the appropriate subclass. To do so, each the of the `ASN1*` classes implement a `toDERObject()` and a `toDLObject()` method which is called by the `*OutputStream` returning the appropriate variant of the primitive for encoding. For instance `ASN1Set` implements `toDERObject()` by returning `new DERSet(..)` and `toDLObject()` by returning `new DLSet(..)` as a new instance of the requested type. For efficiency reasons (as I guess) some subclasses overwrite the `to*Object()` methods for their own type by simply returning `this`, to avoid to create a redundant new object of identical type.
Consequently the `DL*` objects overwrite the `toDLObject()` methods with `return this;`, which is fine. However, the corresponding `DER*` objects do not only overwrite their `toDERObject()` methods with `return this;`, but also the  `toDLObject()` methods with `return this;`. This is not OK, since the `toDLObject()` will return a DER-object rather then the corresponding DL-object.

As a result, `DEROutputStream` will produce DER correctly, but `DLOutputStream` will produce mixed DL and DER.
As a fix, the `toDLObject()` methods in DER-object should simply be removed. In this case the `toDLObject()` methods of the superclass will apply and will return the correct DL-object. 
I tried this change locally and the DL-output is correct now, the signatures are valid.

This problem still exists in the last recent version 1.67. Does somebody know if this problem is even known and when and in which release it will be fixed? 

Thank you.

**Comment by Shekii** [comment]
I have also encountered the same problem, thus resulting in the following error:

org.bouncycastle.asn1.DLSet cannot be cast to org.bouncycastle.asn1.DLSequence

Anyone else had this problem?

**Comment by dghgit** [comment]
I don't think this is right, to start with DER is a subset of DL which is a subset of the more general BER, so returning "this" is correct. The issue sounds more like there are some places where DERSet is being used that should be replace with DLSet.

I'm also not sure why you would be generating signatures using a mutable format though - DER is specifically to address security problems around this.

@Shekii your issue is completely different. The object stream is not what your code is trying to parse.

**Comment by martin2306** [comment]
What we are doing is not to create a new signature. We have documents with older signatures from 2017 and before. These documents have to be retransmitted on demand to law courts. For this, they have to be signed once again.
So what we do is, we add the new signature to an existing PKCS#7 container already containing old signatures. We have to do this because the transfer structure has room only for one PKCS#7 container to convey the signatures.  For this, we use `CMSSignedData.replaceSigners` with a `Store` that contains both, the old and the new signatures. 
This worked fine untill at least BC V1.60, because it left the old signatures unchanged while DL-encoding the `ContentInfo` again with an `DLOutputStream`. 
Doing this with at least BC V1.64 and above the old-style signatures are always reformatted changing the existing `DLSets` in `DERSets` which resorts the signed attributes. This changes the hash and makes old-style signatures mathematically invalid.
Reason is, that the `return this` in `toDLObject()` always returns a `DERSet `rather than a `DLSet`, even if it is called on `DLSets`.

I agree, that signatures should be in an immutable format, this may be reason why this has been changed some-when in 2017/2018. I don't know if this changed in general or only our signing software from OpenLimit did this. However, we have to deal with existing signatures in different formats containing also `DLSets`. Changing their existing structure destroys them.

We wanted to upgrade to BC V1.64 because of the security issue. Since the new version destroys our old signatures we have to rollback to BC V1.60 or patch the newer versions, removing the `return this`. For the moment we rolled back, hoping for a solution.

**Comment by dghgit** [comment]
Okay, so check, but I think you'll find the signature is not getting reformatted - the BC code will DER encoded for the purposes of verification and signing, but will still write things out as they were originally. The one point where this might not happen is on the line:

        ASN1Set             signers = new DERSet(vec);

which could be changed to 
       ASN1Set             signers = new DLSet(vec);

without causing any issues. For the verification of signatures which are "old" you want to override the SignerInfomation object as on line 1342 of NewSignedDataTest. Let me know how it goes. I'd try the SignerInformation override first.

**Comment by dghgit** [comment]
DLSet change has been made. Marking resolved.
