### ISSUE TITLE
SSLContext init use for a long time

### ISSUE THREAD

**Issue by lyy4j** [bcgit/bc-java#846]
jdk 1.8
code:
1)javax.net.ssl.SSLContext sslContext = SSLContext.getInstance("TLS", "BCJSSE");
2)sslContext.init(keyMgrFact.getKeyManagers(), trustMgrFact.getTrustManagers(), new SecureRandom());

question:
when the code run in the centos virtual machine, the step "2)" (sslContext.init(...)) used for a long time(about 15 minutes), but it can work normally and quickly in the  physical machine.

please help, thanks!

**Comment by peterdettman** [comment]
Sounds like an entropy problem in the VM. The sslContext.init call generates a small amount of random data, which is intended to fully initialize the SecureRandom instance prior to any connections being attempted.

Typically the solution is to install rng-tools in the VM and run the rngd service, but I can't speak specifically to CentOS.

**Comment by lyy4j** [comment]
> Sounds like an entropy problem in the VM. The sslContext.init call generates a small amount of random data, which is intended to fully initialize the SecureRandom instance prior to any connections being attempted.
> 
> Typically the solution is to install rng-tools in the VM and run the rngd service, but I can't speak specifically to CentOS.

thanks, I will have try

**Comment by lyy4j** [comment]
> rng-tools

yes, it case by entropy problem, thank you very much

**Comment by lyy4j** [comment]
> > rng-tools
> 
> yes, it case by entropy problem, thank you very much

and reslove the problem by
