### ISSUE TITLE
java.lang.NoSuchMethodError: org.bouncycastle.util.Properties.isOverrideSetTo

### ISSUE THREAD

**Issue by Yaya1234567** [bcgit/bc-java#853]
Hi,

I encountered the

java.lang.NoSuchMethodError: org.bouncycastle.util.Properties.isOverrideSetTo

when trying to use the bcpg-jdk15to18-167.jar version. Think the issue lies in the PublicKeyKeyEncryptionMethodGenerator.java.
Any help, pls. Thanks a lot in advance!

**Comment by dghgit** [comment]
Which bcprov are you using?

**Comment by Yaya1234567** [comment]
Hi,

I am using bcprov-jdk15to18-167.jar.
I managed to resolve the issue after setting the prefer loading of the libraries.

Thanks a lot for your help!

**Comment by cristianchan-mulesoft** [comment]
Hey Sorry what do you mean with prefer loading of the libraries.?

**Comment by dghgit** [comment]
Check your class path, there's another version of the provider installed somewhere.
