### ISSUE TITLE
typo in JceOpenSSLPKCS8EncryptorBuilder

### ISSUE THREAD

**Issue by Gsealy** [bcgit/bc-java#856]
passsword -> password

https://github.com/bcgit/bc-java/blob/77f56d558fc703b9b592cea537d1dc1c4fe2a334/pkix/src/main/java/org/bouncycastle/openssl/jcajce/JceOpenSSLPKCS8EncryptorBuilder.java#L83

**Comment by dghgit** [comment]
Thanks for the report. Well at least the argument was spelt properly. I've fixed it and deprecated the old spelling.
