### ISSUE TITLE
TLS Handshake failures with BCJSSE on the server side and a client using SunJSSE with Java 1.8.0_181

### ISSUE THREAD

**Issue by kimmerin** [bcgit/bc-java#864]
When trying to connect to a ServerSocket that is using BCJSSE as provider and the client is using Java 1.8.0_181 the handshake fails because the TlsServer claims that no fitting cipher can be used. When doing the same test the other way around, i.e. a BCJSSE provider based Socket is connecting to a SunJSSE based ServerSocket the handshake succeeds. After trying out many things I found out the reason. Java 1.8.0_181 reports 10 algorithms in the extension signature_algorithms where the BC TlsServer doesn't seem to like any.

The strange thing about this is that as BC-based client the agreed on signature algorithm rsa_pkcs1_sha256 (0x0401) is used which is also in the list of signature-algs when SunJSSE is the client.

I've attached a Wireshark trace showing the failing handshake (plus some others because it's been created while testing something else, session resumption related) and a JUnit testcase where it's shown that it's the signature_algorithms extension leading to the handshake failure.
[tlstest_bcjsse_sunjsse.zip](https://github.com/bcgit/bc-java/files/5821556/tlstest_bcjsse_sunjsse.zip)
[__Run_SunJSSE_BCJSSE_ProblemRecreation.zip](https://github.com/bcgit/bc-java/files/5821566/__Run_SunJSSE_BCJSSE_ProblemRecreation.zip)

**Comment by peterdettman** [comment]
@kimmerin Hi Lothar, sorry it took so long to take a look at this. I've now run your unit tests using latest BC code, and saw one failed test in `testConnectWithExtensionsOfOtherWiresharkTrace`. Debugging, I noticed that the test was using SunX509 KMF and TMF, which is not supported by BCJSSE (in the general case).

So, replacing the KMF/TMF creation in your `createContext` with:

```
KeyManagerFactory km = KeyManagerFactory.getInstance("PKIX", BC_JSSE_PROVIDER); 
TrustManagerFactory tm = TrustManagerFactory.getInstance("PKIX", BC_JSSE_PROVIDER);
```

all the tests now pass.

**Comment by kimmerin** [comment]
Thanks for taking a look into it.

> Debugging, I noticed that the test was using SunX509 KMF and TMF, which is not supported by BCJSSE (in the general case).

If that's the case, wouldn't it be helpful for a user to throw an exception in SSLContext.init(KMF, TMF, random) if the passed KeyManager and/or TrustManager are not supported?

**Comment by peterdettman** [comment]
We still allow "wrapper" implementations, as long as they essentially decorate an underlying BCJSSE one. We could consider some sort of detection for JDK implementation classes specifically.

**Comment by kimmerin** [comment]
Changed my implementation to use not use SunX509 (PKIX is supported as well if SunJSSE is used as provider, so it was a simple change) and my (real) tests run through now as well. They still fail when using Java 16 but I have to dig into that in more detail but I don't think it has something to do with this particular case.
