### ISSUE TITLE
how to use PBKDF2WithHmacSHA1And8bit

### ISSUE THREAD

**Issue by xiguayizu** [bcgit/bc-java#865]
Sorry I don't understand how to use PBKDF2WithHmacSHA1And8bit.
Can anyone help me?

thank anyone very much

**Comment by dghgit** [comment]
See the checkPBE() method of org.bouncycastle.jce.provider.test.PBETest for some examples of use of the various PBKDF2 algorithms. In general the best way to use it is via a SecretKeyFactory passing a PBEKeySpec to generateSecret() that is carrying the details for generation.
