### ISSUE TITLE
bc 1.67 version library loading issue

### ISSUE THREAD

**Issue by akshaygh1** [bcgit/bc-java#867]
Hi,
We are facing bc1.67 library loading issue on jdk 1.8 with jboss eap 6.
it takes ~ 1 min to load it for the first time and later on its fine.
Is there any known issue with the library, any solution or workaround is available?

Urgent help is much appreciated.

Thanks,
Akshay

**Comment by akshaygh1** [comment]
Any updates

**Comment by dghgit** [comment]
No idea on this one. I'd guess it's jboss validating the jar signature. I can't think of anything else it would be doing. There's two signatures in the jar file, as this is for 1.8 you could try removing the 1024 bit one:

META-INF/BC1024KE.SF
META-INF/BC1024KE.DSA

Use:

zip -d bcprov-jdk15on-167.jar  META-INF/BC1024KE.SF META-INF/BC1024KE.DSA

(or ...1.67 if off Maven). The certificate for this signature has actually expired so the delay you might be seeing will be the server checking the time stamp.

Please note commercial level support is available from https://www.cryptoworkshop.com - if you want things done quickly, you are welcome to sign up.

**Comment by dghgit** [comment]
Inactive.
