### ISSUE TITLE
Malformed file(?)

### ISSUE THREAD

**Issue by davide-malagoli** [bcgit/bc-java#869]
Hello,
 I use this dependency in my java code

```
 <dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcpkix-jdk15on</artifactId>
    <version>1.67</version>
 </dependency>
```

and I'm getting this error trying to decode [this file](https://drive.google.com/file/d/1zlQTjjSVZEmckWm0VASqGY_RxdsWJ3pO/view?usp=sharing)

```
Caused by: java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.DLApplicationSpecific
at org.bouncycastle.asn1.ASN1Sequence.getInstance(ASN1Sequence.java:105)
at org.bouncycastle.asn1.cms.ContentInfo.getInstance(Unknown Source)
```

I tried parsing the file with openssl asn1parse but it seems to work without problem (output in the link below).
https://drive.google.com/file/d/1i81vOfRCd_c4lXEsrAMcJXERj2UwSrvL/view?usp=sharing

My code is really simple, but in this case it enters in the first catch and returns an empty array of bytes

```
public static byte[] getData(final byte[] p7bytes) {
        CMSSignedData cms = null;
        try {
            cms = new CMSSignedData(p7bytes);
        } catch (CMSException e) {
            log.error("Error while converting bytes to CMSSignedData : " + e.getMessage(), e);
        }
        if( cms == null || cms.getSignedContent() == null) {
            log.error("p7m signed content is null");
            return new byte[0];
        }
        return (byte[]) cms.getSignedContent().getContent();
    }
```

Can you tell me where is the problem?

Thanks,

**Comment by davide-malagoli** [comment]
Same thing also happens with different library versions, I've tried 1.52 (downgrade) and 1.68 (upgrade), same stack trace.

**Comment by dghgit** [comment]
p7bytes isn't a Base64 encoded data stream is it?

**Comment by davide-malagoli** [comment]
Thank you, found the problem, didn't know about that
