### ISSUE TITLE
bc-fips 1.0.2 is not compatible with -xbootclasspath/a (Java 11)

### ISSUE THREAD

**Issue by jeremyspb** [bcgit/bc-java#873]
Bouncy castle provider source code is not compatible with -xbootclasspath/a option if bc-fips provider is loaded by this option. In our project we use static provider initialization through java.security and we decided to load bcfips provider at bootstrap level. It helps us to create basic VM image with fips compatible java for any our application. By the reason of we use java 11, we can't use lib/ext mechanism (the mechanism was removed) for jdk extention.
During the testing process we found a specific bug that is connected with classloading specific in bc-fips source code. There're several places with same code style, but I give just one example (I kept just interesting for case parts of code, others were cut):
```
class GcmSpecUtil
{
    static final Class gcmSpecClass = lookup("javax.crypto.spec.GCMParameterSpec");


    static boolean isGcmSpec(AlgorithmParameterSpec paramSpec)
    {
        return gcmSpecClass != null && gcmSpecClass.isInstance(paramSpec);
    }


    private static Class lookup(String className)
    {
        try
        {
            return GcmSpecUtil.class.getClassLoader().loadClass(className);
        }
        catch (Exception e)
        {
            return null;
        }
    }
}
```
As we can see, GcmSpecUtil tries to load class javax.crypto.spec.GCMParameterSpec through classloader of GcmSpecUtil itself. However if we take a look on javadoc for https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html, we can see important notice:

> Returns the class loader for the class. Some implementations may use null to represent the bootstrap class loader. **This method will return null in such implementations if this class was loaded by the bootstrap class loader.** If this object represents a primitive type or void, null is returned.
> 

In our case, GcmSpecUtil.class.getClassLoader() returns null that leads to NullPointerException and class is not loaded. 

Proposal:
In all places with same logic, I suggest to use the following code:

```
private static Class lookup(String className)
    {
        try
        {
            ClassLoader cl = GcmSpecUtil.class.getClassLoader();
            if (cl == null) {
                cl = ClassLoader.getSystemClassLoader();
            }
            return cl.loadClass(className);
        }
        catch (Exception e)
        {
            return null;
        }
    }
}
```

**Comment by dghgit** [comment]
Thanks for the report. I've refactored so everything in the provider is now going through ClassUtil and it has an added check to make use of the boot classpath loader.

**Comment by hapuss** [comment]
Is this incorporated in the code? I am facing this issue after adding bc-fips jars using the -Xbootclasspath option. My code rely on "AES/GCM/NoPadding" algorithm but fails due to NullPointerException in the GcmSpecUtil.lookup() method. Is there any other way of adding bc-fips jars globally in the java11?

**Comment by hapuss** [comment]
I was able to find a workaround by not loading BCFIPS jar via `-Xbootclasspath`. I used following solution
1. Set environment variable `JDK_JAVA_OPTIONS` to provide command line arguments to all "java" invocations
2. Use `export JDK_JAVA_OPTIONS="--module-path <dir_containing_bcfips_jars>"`
3. Run the program again and BCFIPS module will be included
