### ISSUE TITLE
URL Base64 decoding is failing 

### ISSUE THREAD

**Issue by hariprasad-tallapalli** [bcgit/bc-java#877]
trying to UrlBase64 decode this data "AAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQA" which is working fine up to version 1.58. But In 1.59 it started suddenly failing with the below error. No idea what changes were made in 1.59 w.r.t to decoding functionality . I am able to decode the same data using JAVA utils Base64URL decoder. 

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 47
	at java.lang.String.charAt(String.java:658)
	at base64test.decode(base64test.java:290)
	at testbase64.main(testbase64.java:37)

**Comment by dghgit** [comment]
We've been progressively moving things to only accept correctly encoded data. The string is 47 characters in length. It's not valid Base64. If it's padded properly with a single '=' you'll be able to process it.
