### ISSUE TITLE
OpenPGP: Encryption with multiple symmetric passwords sometimes fails.

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#880]
Hey!
When I encrypt a message with two passphrases symmetrically, my code sometimes generates a PGP message that cannot be decrypted again.
This issue happens at around 3.5% of all encrypted messages.

I created a [test class](https://github.com/pgpainless/pgpainless/blob/bug72/pgpainless-core/src/test/java/org/bouncycastle/bug72/Bug72.java) to reproduce the issue.

My encryption method looks like this:
```
    /**
     * This method sometimes generates broken ciphertext.
     * @return
     * @throws IOException
     * @throws PGPException
     */
    public byte[] encryptionBouncycastle(byte[] plaintext, String[] passwords) throws IOException, PGPException {
        ByteArrayInputStream in = new ByteArrayInputStream(plaintext);
        ByteArrayOutputStream cipherText = new ByteArrayOutputStream();
        ArmoredOutputStream armorOutputStream = new ArmoredOutputStream(cipherText);

        BcPGPDataEncryptorBuilder dataEncryptorBuilder = new BcPGPDataEncryptorBuilder(SymmetricKeyAlgorithmTags.AES_256);
        dataEncryptorBuilder.setWithIntegrityPacket(true);

        PGPEncryptedDataGenerator encryptedDataGenerator = new PGPEncryptedDataGenerator(dataEncryptorBuilder);

        for (String password : passwords) {
            encryptedDataGenerator.addMethod(new BcPBEKeyEncryptionMethodGenerator(password.toCharArray()));
        }

        OutputStream encryptionStream = encryptedDataGenerator.open(armorOutputStream, new byte[BUFFER_SIZE]);

        PGPCompressedDataGenerator compressedDataGenerator = new PGPCompressedDataGenerator(CompressionAlgorithmTags.UNCOMPRESSED);
        OutputStream compressionStream = new BCPGOutputStream(compressedDataGenerator.open(encryptionStream));

        PGPLiteralDataGenerator literalDataGenerator = new PGPLiteralDataGenerator();
        OutputStream literalDataStream = literalDataGenerator.open(compressionStream, PGPLiteralData.BINARY, PGPLiteralData.CONSOLE, new Date(), new byte[BUFFER_SIZE]);

        OutputStream myOutputStream = new MyOutputStream(literalDataStream, compressionStream, encryptionStream, armorOutputStream);
        Streams.pipeAll(in, myOutputStream);
        myOutputStream.close();

        return cipherText.toByteArray();
    }
```

An example of a broken message would be this:
```
-----BEGIN PGP MESSAGE-----
Version: BCPG v1.68

jC4ECQMC3HsxjIBGJ7lg9pXvZ93TZpD76Lv+JVxpi3DWKNGRh7QKqhE+FqnMA96n
jC4ECQMCLYvyr3wa8qlggqbncZuhOh6M4o3/d9UkeDHYRY5JwGQ9rfjmYhp45e7d
0kgBS4Xxaim+KHeavy36u/ohad0BkR8sQCWmAlSIfYT7yXR8sKj4zjqIT6/FqGcF
wZ9QgP/uwqVI/d/PC/1CCE2QaJ1Pp9XAQQw=
=9iqo
-----END PGP MESSAGE-----
```
It was created using the code above and encrypted for "password1" and "password2".
Decrypting it with "password2" fails in this case, while "password1" works.
GnuPG complains that the sessionkey is broken.

Some observation I made is that in some cases `pbeEncryptedData.getSymmetricAlgorithm(passphraseDecryptor)` would return the wrong symmetric algorithm tag (eg. Camellia-256 while AES-256 is being used. This would strengthen my encoding issue theory.

Is there an encoding issue happening?
Or did I simply made a mistake in my code?

**Comment by vanitasvitae** [comment]
Downstream issue for reference: https://github.com/pgpainless/pgpainless/issues/72

**Comment by vanitasvitae** [comment]
I did some more digging and it turns out that we for some reason hit [this line](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pg/src/main/j2me/org/bouncycastle/openpgp/PGPPBEEncryptedData.java#L127).
Where are these quick check bytes being written?

**Comment by vanitasvitae** [comment]
Update: Whenever decryption fails, [dataDecryptor.getBlockSize()](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pg/src/main/j2me/org/bouncycastle/openpgp/PGPPBEEncryptedData.java#L93) returns a value unequal to 16.

**Comment by vanitasvitae** [comment]
Note that apparently the IV length (equal to return value of dataDecryptor.getBlockSize()) is always equal to 16 when decryption succeeds.
Whenever it is equal to 8 (but not only then), decryption fails.

**Comment by vanitasvitae** [comment]
Apparently the issue is as follows:
BC tries to decrypt the first SKESK (encrypted with "password1") packet with "password2".
It does not immediatelly run into an exception, as the decrypted session key appears to be valid (we got lucky and the first byte matches one of the algorithm identifiers).
It then tries to decrypt the SEIP with the session key and runs into a PGPDataValidationException.

Unfortunately this leaves some side-effect, as now all consequent decryption passes with the other SKESK session keys fail as well.

Funnily I originally had ruled out a decryption issue and suspected faulty encoding during the encryption phase, as GnuPG also failed to decrypt messages where this happened.

So GnuPG is affected by the same bug as BC (or my test code of course) is.

**Comment by vanitasvitae** [comment]
The mentioned sideeffect is that [this inputstream](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pg/src/main/j2me/org/bouncycastle/openpgp/PGPPBEEncryptedData.java#L82) is being read from twice without the data being pushed back after decryption with the wrong sessionkey failed.

A solution would be to use a PushbackInputStream and pushing the bytes back after a failure when reading inside `getDataStream()`.

**Comment by vanitasvitae** [comment]
Should be fixed by https://github.com/bcgit/bc-java/pull/886

**Comment by dghgit** [comment]
Thanks, patch in #886 now merged with some revisions.
