### ISSUE TITLE
Avoid hardcoded salt and insufficient iteration length in creating PBE

### ISSUE THREAD

**Issue by Mahir92** [bcgit/bc-java#882]
We found a security vulnerability in file: https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/prov/src/test/java/org/bouncycastle/jce/provider/test/PBETest.java line 789,  PBEKeySpec use a hard-coded salt defined and iteration = 100

Security Impact:

The salt is expected as a random string. A hardcoded salt may compromise system security in a way that cannot be easily remedied. Also to achieve strong encryption, the iteration should be larger than 1000. 

Useful links:

https://vulncat.fortify.com/en/detail?id=desc.semantic.cpp.weak_cryptographic_hash_hardcoded_pbe_salt

https://cwe.mitre.org/data/definitions/760.html

http://www.crypto-it.net/eng/theory/pbe.html#part_salt

https://www.appmarq.com/public/tqi,1039022,CWE-916Cryptographic-HashAvoid-using-Insecure-PBE-Iteration-Count

Solution we suggest

We suggest generating a random default salt by SecureRandom class, set the iteration larger than 1000

Please share with us your opinions/comments if there is any

Is the bug report helpful?

**Comment by dghgit** [comment]
It's actually a regression test, so there is no vulnerability here. The method does start with the comment saying "for regression testing only - don't try this at home." I'll add something a bit more explicit. Keep in mind both the salt and the iteration count are public parameters.
