### ISSUE TITLE
CMS EnvelopedData: KeyAgreeRecipientInformation does not offer option to retrieve originator

### ISSUE THREAD

**Issue by gnarea** [bcgit/bc-java#894]
I need to get the public key from the `OriginatorIdentifierOrKey`, but the originator is inside the private field `info` in `KeyAgreeRecipientInformation`

https://github.com/bcgit/bc-java/blob/6b3ba0e60c6cbfc46f77e74c042488d3cd08f394/pkix/src/main/java/org/bouncycastle/cms/KeyAgreeRecipientInformation.java#L26

Unless I'm missing something, there's no way to get this key -- short of dealing with the low-level ASN.1 value for the EnvelopedData.

Would you accept a PR that adds the following to `KeyAgreeRecipientInformation`?

```
public OriginatorIdentifierOrKey getOriginator() {
    return this.info.getOriginator()
}
```

**Comment by dghgit** [comment]
Can you say why? It sounds an awful lot like you probably want to override getRecipientOperator() in KeyAgreeRecipientInformation. Let me know though.

**Comment by gnarea** [comment]
Hi @dghgit!

> Can you say why?

I need the originator's public key so that I can use it to encrypt future plaintexts.

To give you more context:

I'm implementing a protocol based on the Signal Protocol, where two peers exchange messages which are E2E encrypted with ECDH and the keys are constantly rotated. Each node needs to store the last ECDH public key from its peer, so that it can send encrypted messages to its peer using that key and its own freshly-generated ECDH key pair.

> It sounds an awful lot like you probably want to override getRecipientOperator() in KeyAgreeRecipientInformation

Not sure if I'm missing something, but the output of that method would only help me with decryption, not encryption. Per the above, I need to get the originator's public key so that I can encrypt future messages.

**Comment by dghgit** [comment]
Ah, okay, no I think I was missing something. I've pushed a patch adding the method described. It will also show in 169b04 on https://www.bouncycastle.org/betas which should come out in the next few hours.
