### ISSUE TITLE
IllegalStateException: attempt to get non-octet aligned data from BIT STRING

### ISSUE THREAD

**Issue by gino0631** [bcgit/bc-java#896]
`getSignature()` on an instance of `org.bouncycastle.jcajce.provider.asymmetric.x509.X509CertificateObject` obtained using:
```
        X509Certificate cert = (X509Certificate)CertificateFactory.getInstance("X.509", "BC")
                .generateCertificate(Files.newInputStream(path));
        cert.getSignature();
```
produces:
```
Exception in thread "main" java.lang.IllegalStateException: attempt to get non-octet aligned data from BIT STRING
	at org.bouncycastle.asn1.ASN1BitString.getOctets(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.x509.X509CertificateImpl.getSignature(Unknown Source)
```
with this [this certificate](https://github.com/bcgit/bc-java/files/6063207/IT.pem.txt).

With `sun.security.x509.X509CertImpl` (`CertificateFactory.getInstance("X.509")`), it does work.

Is there something wrong with the certificate in question, or the certificate parsing in BC can't handle certain data?

**Comment by peterdettman** [comment]
The certificate is incorrect. The signature algorithm is `SHA256withRSA`, i.e. it is an RSA PKCS#1 signature. Such signatures are in the form of a (fixed-size) octet string (i.e. 8-bit aligned) - refer to the "I2OSP" function. Therefore in converting such a signature to the `BIT STRING` required in the certificate's `signatureValue` field, there should never be any padding bits.

Before saying that `X509CertImpl` "works" you ought to check whether the certificate signature can actually be verified. Yes it tolerates the strange non-zero padding in this `BIT STRING`, but the returned array may not be a valid signature in the form it is returned; it depends on the specifics of the (incorrect) certificate generation.

**Comment by gino0631** [comment]
Thank you for the information. I contacted the issuer and pointed to it.

Of course, by "works" I meant "returns some value". Under these circumstances, it is nonsensical, and the verification should also fail (it is not possible to test, as we do not have the public key of the issuer - the certificate is supposed to be trusted directly).

Thanks for your help.
