### ISSUE TITLE
getCACerts not able to retrieve cacerts from OpenXPKI ca server through est , it throws ESTException

### ISSUE THREAD

**Issue by dipakbag** [bcgit/bc-java#901]
In the file ../pkix/src/main/java/org/bouncycastle/est/ESTService.java  at getCACerts() function it checks the content-type exactly as "application/pkcs7-mime", But in OpenXPKI ca server response the content-type as "application/pkcs7-mime; smime-type=certs-only". So, this check need to be changed at line number 143

 if (!"application/pkcs7-mime".equals(resp.getHeaders().getFirstValue("Content-Type")))

**Comment by dghgit** [comment]
I think this is now fixed and pushed. The fix will appear in 169b04, which will appear on https://www.bouncycastle.org/betas in a few hours.
