### ISSUE TITLE
EdDSA signature created with JDK fails BC verification on JDK 15+

### ISSUE THREAD

**Issue by bsanchezb** [bcgit/bc-java#909]
Hello,

Recently I have created a ticket #797 with EdDSA issue support after upgrading to JDK 15. The referenced issue has been resolved successfully in v1.67, however now we have encountered another issue with validation of a EdDSA signature, created with Java security provider, instead of BC provider. What is more (maybe ?) important is that the used public key has a JDK's implementation in Java 15+ [EdDSAPublicKeyImpl](https://github.com/openjdk/jdk15/blob/master/src/jdk.crypto.ec/share/classes/sun/security/ec/ed/EdDSAPublicKeyImpl.java), while before it was loaded with [BCEdDSAPublicKey](https://github.com/bcgit/bc-java/blob/r1rv68/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/edec/BCEdDSAPublicKey.java).

Here you can find a unit test that fails in JDK 15+, but passes with older versions:
```
        @Test
	public void bcTest() throws Exception {
		byte[] toSign = "Hello World!".getBytes();

		KeyPairGenerator ed25519 = KeyPairGenerator.getInstance("Ed25519");
		KeyPair keyPair = ed25519.generateKeyPair();

		Signature signatureSign = Signature.getInstance("Ed25519");
		signatureSign.initSign(keyPair.getPrivate());
		signatureSign.update(toSign);
		byte[] signatureValue = signatureSign.sign();

		Signature signatureVerify = Signature.getInstance("Ed25519", "BC");
		signatureVerify.initVerify(keyPair.getPublic());
		signatureVerify.update(toSign);
		org.junit.jupiter.api.Assertions.assertTrue(signatureVerify.verify(signatureValue));
	}
```

Could please check what is the issue and if it can be fixed?

Best regards,
Aleksandr.

**Comment by peterdettman** [comment]
Please test with latest beta: https://downloads.bouncycastle.org/betas/ .

**Comment by bsanchezb** [comment]
Hello @peterdettman ,

I have tested with 1.69b03 and indeed it seems working! Looking forward to 1.69 release.

Best regards,
Aleksandr.
