### ISSUE TITLE
Load cacerts as a jks file

### ISSUE THREAD

**Issue by Syed-SnapLogic** [bcgit/bc-java#912]
I am trying to load the "cacerts" file that is bundled with JDK11 by default.  And my IDE is set to use JDK11 for execution.

  However, without BouncyCastle provider, the default SUN provider is able to load the "cacerts" successfully, but when I add BouncyCaslte then my program fails.

  The SUN provider works because, it uses "PKCS12" as primary format, and uses "JKS" as secondary format.  See the code here. https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/sun/security/pkcs12/PKCS12KeyStore.java#L140

   "cacerts" is ideally "JKS" type and not "PKCS12".  I suggest bouncycastle should also follow the same approach as SUN provider.

Sample code to replicate this issue: https://github.com/Syed-SnapLogic/SyedsPublicRepo/tree/master/bctestcacerts

Note: Use JDK11 for executing the above sample code.

**Comment by dghgit** [comment]
I think this is now working - it won't load private keys, but it should be good for things like cacerts. Now up on https://www.bouncycastle.org/betas (note there is now an extra jar, bcutils which contains ASN.1 classes that don't need to be in the provider)
