### ISSUE TITLE
Caused by: java.io.IOException: error constructing MAC: java.security.InvalidAlgorithmParameterException: inappropriate parameter type: javax.crypto.spec.PBEParameterSpec

### ISSUE THREAD

**Issue by wangchongbin** [bcgit/bc-java#918]
this is the calling code:
=====================================

  public static String generateRSAPFX(String key, String cert, String password)
    throws IOException, NoSuchAlgorithmException, InvalidKeySpecException, CertificateException, NoSuchProviderException, KeyStoreException, UnrecoverableKeyException {

    try (
      ByteArrayInputStream certInput = new ByteArrayInputStream(Base64.getDecoder().decode(cert));
      ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    ) {

      PKCS8EncodedKeySpec encodedKeySpec = new PKCS8EncodedKeySpec(Base64.getDecoder().decode(key));
      KeyFactory keyFactory = KeyFactory.getInstance("RSA");
      PrivateKey privateKey = keyFactory.generatePrivate(encodedKeySpec);

      CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509", BC);
      Certificate certificate = certificateFactory.generateCertificate(certInput);

      KeyStore keyStore = KeyStore.getInstance("pkcs12", BC);
      keyStore.load(null, null);
      keyStore.setKeyEntry("test", privateKey, password.toCharArray(), new Certificate[]{certificate});
      keyStore.store(outputStream, password.toCharArray());
      outputStream.flush();
      byte[] pfx = outputStream.toByteArray();
      return Base64.getEncoder().encodeToString(pfx);
    }
  }

**Comment by dghgit** [comment]
I can't reproduce this. From the description, it's almost certainly a class loader issue.
