### ISSUE TITLE
Provide a clean way to stop EntropyGatherer daemon

### ISSUE THREAD

**Issue by gaellalire** [bcgit/bc-java#928]
```java
                    Thread gatherer = new Thread(new EntropyGatherer(byteLength));
                    gatherer.setDaemon(true);
                    gatherer.start();
```

gatherer should be kept somewhere, and a shutdown / close / ... method will interrupt it.

Without that BC will create classloader leak for each classloader which loads BC.

**Comment by dghgit** [comment]
We've found a way to deal with this that appears to work - seems this ended up causing strife in Maven. An interrupt will now terminate the daemon as well,

Closing, sorted, see also #1254
