### ISSUE TITLE
Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG to constructor sun.security.provider.Sun()

### ISSUE THREAD

**Issue by valentinacupac** [bcgit/bc-java#929]
I get the following warning:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/C:/Users/Name.Surname/.m2/repository/org/bouncycastle/bcprov-jdk15on/1/57/org/bouncycastle/bcprov-jdk15on/1.57/bcprov-jdk15on-1.57.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

This appears to be a similar error as reported in https://github.com/bcgit/bc-java/issues/510

**Comment by dghgit** [comment]
Please upgrade the BC provider jar.

**Comment by valentinacupac** [comment]
Thank you, it works now.
