### ISSUE TITLE
Elgamal Key with size 4096 going in an infinite loop

### ISSUE THREAD

**Issue by Susmit07** [bcgit/bc-java#931]
```
/**
     * 
     * @param keySize - 1024, 2048, 4096
     * @return the El Gamal generated key pair
     * @throws Exception 
     */
    public static final KeyPair generateElGamalKeyPair(int keySize) throws Exception
    {
        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("ELGAMAL", "BC");
        keyPairGenerator.initialize(keySize);
        KeyPair keyPair = keyPairGenerator.generateKeyPair();
        return keyPair;
    }

```

The call to generateKeyPair() when I use ELGAMAL and keySize 3072, 4096 it goes on forever and never ends. Am I doing the right way to generate the KeyPair of type ELGAMAL?

Note the issue never arises for 1024, 2048 keySize, only in 3072, 4096 it's seen.

**Comment by dghgit** [comment]
Try using the initialize method that takes parameters - there's no defaults for 3072 and 4096 at the moment. Creating generators that size will take quite a while

**Comment by Susmit07** [comment]
![image](https://user-images.githubusercontent.com/32009785/115100325-7cd26100-9f59-11eb-99b3-52af48505abf.png)

Do you find any issue with the code snippet

**Comment by Susmit07** [comment]
`
public PGPKeyPair getPGPKeyPair() throws PGPException {
		ElGamalKeyPairGenerator elGamalKeyPairGenerator = new ElGamalKeyPairGenerator();
		elGamalKeyPairGenerator.init(new KeyGenerationParameters(new SecureRandom(), 4096));
		AsymmetricCipherKeyPair elgKp = elGamalKeyPairGenerator.generateKeyPair();
		return new BcPGPKeyPair(PGPPublicKey.ELGAMAL_ENCRYPT, elgKp, new Date());
}
`

Or this ?

**Comment by Susmit07** [comment]
The issue is fixed thanks

**Comment by Susmit07** [comment]
@dghgit  Need your guidance:

![image](https://user-images.githubusercontent.com/32009785/115117901-732f1480-9fbe-11eb-9862-9dde79979dea.png)

Can you please let me know how to set the unknown field for the master public key (just beside the email user id), any BC Apis can I use. Shall be really helpful if you can guide me

**Comment by dghgit** [comment]
I'm guess a bit at what you are asking here, but only a signing key can be a master key. Encryption keys must be sub-keys.

**Comment by Susmit07** [comment]
I meant the 7 th line [unknown] == in gpg it shows Ultimate, do we have any apis to set that value

**Comment by Susmit07** [comment]
> The issue is fixed thanks

Shall I add my code changes in PGP examples, currently we do have ElgamalKeyGeneratorExample, but mine do have the flexibility to create different size keys from 1024-4096 size

**Comment by dghgit** [comment]
Sure. Thanks. Others might find that useful.

**Comment by dghgit** [comment]
Closed as resolved.

**Comment by Malshalaan** [comment]
> > The issue is fixed thanks
> 
> Shall I create a PR add my code changes in PGP examples, currently we do have ElgamalKeyGeneratorExample, but mine do have the flexibility to create different size keys from 1024-4096 size

Can we have the full example that has flexible key size, I'm facing similar issue and couldn't resolve it.

**Comment by dghgit** [comment]
There's an example of this in the DSAElGamalKeyRingGenerator example. It uses the DHParameterSpec to set the key size - for a larger key it's just a matter of using larger Diffie-Hellman parameters.
