### ISSUE TITLE
BC failures in FIPS mode in TLSv1.2

### ISSUE THREAD

**Issue by sumeetbadwal** [bcgit/bc-java#933]
We just update BC jars:
bctls-fips-1.0.11.jar from bctls-fips-1.0.5.jar
bc-fips-debug-1.0.2.jar from bc-fips-1.0.1.jar
bcpkix-fips-1.0.5.jar from bcpkix-fips-1.0.1.jar

Here is security file regarding providers:
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider C:DEFRND[HmacSHA512];ENABLE{ALL};
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider  fips:BCFIPS
security.provider.3=sun.security.provider.Sun

Java: java-1.8.0-openjdk
After updating versions of BC jars, these messages are appearing in FIPS mode:
Apr 19, 2021 8:21:11 PM org.bouncycastle.jsse.provider.PropertyUtils getBooleanSecurityProperty
INFO: Found boolean security property [keystore.type.compat]: true
Apr 19, 2021 8:21:11 PM org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
INFO: Found string security property [jdk.tls.disabledAlgorithms]: SSLv3, RC4, MD5withRSA, DH keySize < 1024, EC keySize < 224, DES40_CBC, RC4_40, 3DES_EDE_CBC
Apr 19, 2021 8:21:11 PM org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
INFO: Found string security property [jdk.certpath.disabledAlgorithms]: MD2, MD5, SHA1 jdkCA & usage TLSServer, RSA keySize < 1024, DSA keySize < 1024, EC keySize < 224
Apr 19, 2021 8:21:11 PM org.bouncycastle.jsse.provider.DisabledAlgorithmConstraints create
WARNING: Ignoring unsupported entry in 'jdk.certpath.disabledAlgorithms': SHA1 jdkCA & usage TLSServer
Apr 19, 2021 8:21:12 PM org.bouncycastle.jsse.provider.ProvKeyManagerFactorySpi getDefaultKeyStore
INFO: Initializing empty key store

Please suggest.

**Comment by peterdettman** [comment]
What exactly are you asking about?

**Comment by dghgit** [comment]
Not a bug.
