### ISSUE TITLE
Possible a bug in the CMSUtils helper class: duplicated code

### ISSUE THREAD

**Issue by Mingun** [bcgit/bc-java#935]
https://github.com/bcgit/bc-java/blob/871449efddb76e90ef649b0c792d71ccefd5335d/pkix/src/main/java/org/bouncycastle/cms/CMSUtils.java#L53-L60

Lines 58-59 are identical. This could be or excess line, or forgotten algorithm

**Comment by Mingun** [comment]
The same problem in
https://github.com/bcgit/bc-java/blob/871449efddb76e90ef649b0c792d71ccefd5335d/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/util/DESUtil.java#L14-L22

Lines 18-20 are identical.

**Comment by dghgit** [comment]
Thanks for the report. Fortunately just a duplicate entry. Now fixed.
