### ISSUE TITLE
handshake_failure when trying to connect to MySQL server with custom ssl_cipher list

### ISSUE THREAD

**Issue by majumdartanmay** [bcgit/bc-java#939]
**Jars used:**
bc-fips-1.0.2.jar
bcpkix-fips-1.0.3.jar
bctls-fips-1.0.9.jar

I am getting a handshake_failure  when trying to connect to a MySQL server via SSL. 
In my MySQL server, I have provided the following ciphers for ssl using the ssl_cipher variabel in my.ini:

`ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-SHA384:ECDH-RSA-AES256-GCM-SHA384:ECDH-RSA-AES256-SHA384:DH-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256`

Now let me talk about the client's bouncy castle configuration. I am adding the security providers using java.policy

```
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS
security.provider.3=sun.security.provider.Sun
```

I am adding the bc-fips-1.0.2.jar, bcpkix-fips-1.0.3.jar, bctls-fips-1.0.9.jar using -xBootclasspath and I am using open-jdk-11

Now these are the logs produced:

```
Caused by: org.bouncycastle.tls.TlsFatalAlertReceived: handshake_failure(40)
at org.bouncycastle.tls.TlsProtocol.handleAlertMessage(Unknown Source)
at org.bouncycastle.tls.TlsProtocol.processAlertQueue(Unknown Source)
at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(Unknown Source)
at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(Unknown Source)
at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:317)
at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:97)
at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:331)
```
**Naïve Workaround:**
Right now, I have reluctantly used a workaround (_But I absolutely want to remove this_). Basically, I am manipulating the security provider hierarchy just before db connection and reverting it back after the db connection. To clarify, this is my code (sort of)

```
// Before connection
Security.removeProvider(BouncyCastleJsseProvider.PROVIDER_NAME); Security.insertProviderAt(new BouncyCastleJsseProvider(), 1);
.
.
// driver.connect is called
.
.
// After connection
Security.removeProvider(BouncyCastleFipsProvider.PROVIDER_NAME);
Security.removeProvider(BouncyCastleJsseProvider.PROVIDER_NAME);
Security.insertProviderAt(new BouncyCastleFipsProvider(), 1);
Security.insertProviderAt(new BouncyCastleJsseProvider("fips:BCFIPS"), 2);
```

PS: Any help is appreciated.
Thanks

Update:

Correction. My SSL cipher list is this:
`ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-AES256-SHA384,ECDHE-RSA-AES256-SHA384,ECDH-ECDSA-AES256-GCM-SHA384,ECDH-ECDSA-AES256-SHA384,ECDH-RSA-AES256-GCM-SHA384,ECDH-RSA-AES256-SHA384,DH-RSA-AES256-SHA256,DHE-RSA-AES256-SHA256,DH-DSS-AES256-SHA2563`

**Comment by majumdartanmay** [comment]
I took a rough look-around of bouncy castle code. Correct me if I am wrong, some of my MySQL SSL ciphers are supported even in FIPS mode. What could be the reason for this to happen then.

**Comment by peterdettman** [comment]
The error message indicates the server raised a handshake_failure alert, so you might find the reason in the server logs. TLS doesn't add any error detail to the alert itself, so there's no specifics in the client logs.

If I understand you, the connection works if you disable fips mode for BCJSSE? Some of the ciphers you list should still be available in fips mode, but do you actually have both RSA and ECDSA credentials available to the server? I would try to find a specific cipher suite that works for non-fips, but fails for fips (of course it should be a fips-permitted cipher suite). If you can get wireshark packet captures we could compare the ClientHello between the working and non-working cases.

I would also suggest upgrading to the most recent fips jars, or at least testing with them.

Finally, please send us more detailed logs in case something shows up there, e.g. edit your JAVA_HOME/conf/logging properties:

```
#java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.level = FINEST
org.bouncycastle.jsse.level = FINEST
```

**Comment by majumdartanmay** [comment]
Hello @peterdettman .
Thanks for the prompt response. 

Firstly, I have updated the mentioned SSL cipher list in the issue description. So, please take a look at that. Apologies for the redundancy. 

I have updated bcpkix-fips and bcptls-fips jar to the latest version and **the issue seems to be resolved**.  (Thanks for pointing this out.) Maybe some of the SSL ciphers were added in the latest version .

The reason I was certain that it's a ssl cipher issue because once I used the default list of SSL cipher by commenting out ssl_cipher variable in my.ini, I didn't have the handshake failure. 

It's worth nothing that modifying the log properties in JDK didn't produce some extra info for me. Maybe it's because I am using log4j.xml for my log configurations?
