### ISSUE TITLE
McElieceKobaraImaiCipher - Getting randomly "Bad Padding: invalid ciphertext" exception while decrypting

### ISSUE THREAD

**Issue by mcarleio** [bcgit/bc-java#942]
First of, I am using JDK 11 and bcprov-ext-jdk15on in version 1.68.

When you execute below code, you will often pass 100 iterations before the following error is raised:

    Exception in thread "main" org.bouncycastle.crypto.InvalidCipherTextException: Bad Padding: invalid ciphertext
	at org.bouncycastle.pqc.crypto.mceliece.McElieceKobaraImaiCipher.messageDecrypt(Unknown Source)

Short explanation of the code:

1. generate random bytes
2. generate McEliece KeyPair
3. In a loop:
    1. Encrypt the bytes
    2. Decrypt the encrypted bytes

Here is the demo code:

    import org.bouncycastle.crypto.AsymmetricCipherKeyPair;
    import org.bouncycastle.crypto.params.AsymmetricKeyParameter;
    import org.bouncycastle.pqc.crypto.mceliece.McElieceCCA2KeyGenerationParameters;
    import org.bouncycastle.pqc.crypto.mceliece.McElieceCCA2KeyPairGenerator;
    import org.bouncycastle.pqc.crypto.mceliece.McElieceCCA2Parameters;
    import org.bouncycastle.pqc.crypto.mceliece.McElieceKobaraImaiCipher;
    import java.security.SecureRandom;
    import java.util.Arrays;

    public class Encrypter {

        public static final SecureRandom SECURE_RANDOM;

        static {
            SecureRandom tmp = null;
            try {
                tmp = SecureRandom.getInstance("SHA1PRNG");
            } catch (Exception nsae) {
                throw new RuntimeException(nsae);
            } finally {
                SECURE_RANDOM = tmp;
            }
        }

        public static void main(String[] args) throws Exception {
            // Generate random data
            byte[] dataToEncrypt = new byte[250];
            SECURE_RANDOM.nextBytes(dataToEncrypt);

            // Generate key pair
            AsymmetricCipherKeyPair keyPair = generateMcElieceKeyPair(new McElieceCCA2Parameters());

            // Repeat a few times, because the error will not occur on every run
            for (int iteration = 0; iteration < 1000; iteration++) {

                byte[] encrypted = encryptMcEliece(dataToEncrypt, keyPair.getPublic());
                byte[] decrypted = decryptMcEliece(encrypted, keyPair.getPrivate());

                System.out.println((iteration+1) + ". iteration result: " + Arrays.equals(dataToEncrypt, decrypted));
            }
        }

        public static AsymmetricCipherKeyPair generateMcElieceKeyPair(McElieceCCA2Parameters parameters) {
            McElieceCCA2KeyPairGenerator mcElieceKeyPairGenerator = new McElieceCCA2KeyPairGenerator();
            mcElieceKeyPairGenerator.init(new McElieceCCA2KeyGenerationParameters(SECURE_RANDOM, parameters));
            return mcElieceKeyPairGenerator.generateKeyPair();
        }

        private static byte[] encryptMcEliece(
                final byte[] bytesToEncrypt,
                final AsymmetricKeyParameter publicKey
        ) {
            McElieceKobaraImaiCipher cipher = new McElieceKobaraImaiCipher();
            cipher.init(true, publicKey);
            return cipher.messageEncrypt(bytesToEncrypt);
        }

        private static byte[] decryptMcEliece(
                final byte[] bytesToDecrypt,
                final AsymmetricKeyParameter privateKey
        ) throws Exception {
            McElieceKobaraImaiCipher cipher = new McElieceKobaraImaiCipher();
            cipher.init(false, privateKey);
            return cipher.messageDecrypt(bytesToDecrypt);
        }
    }

**Comment by tonywasher** [comment]
Running your code through a debugger and a patched koboraImai cipher shows up the error.

The encryptor creates a value called c2c1 which is the concatenation of c2 and c1. This is then remapped as c6c5c4 and split into c6 c5 and c4.  c5 and c4 are then encrypted into encC4 and then the concatenation of c6 and encC4 is returned as the cipher text

The decryptor splits the cipher text into c6 and encC4 and derives c4 and c5 from encC4 and here is where the problem occurs.

The derived value of c5 in the decryptor has leading zeroes removed. This should not happen and the derived c5 needs to have the missing zeroes restored. The length of c5 is a fixed value derived from the key parameters, and so the situation can be easily detected and the missing zeroes restored. I have tested and verified a fix based on this and will raise a corresponding pull request

**Comment by mcarleio** [comment]
Thank you very much for your fix :+1:  Now I just have to wait for the next release :thinking:

**Comment by dghgit** [comment]
The fixed version is now available at https://www.bouncycastle.org/betas in 169b08.
