### ISSUE TITLE
Infinite loop in DTLSRecordLayer.receive with timeMillis=0

### ISSUE THREAD

**Issue by t-ivan-gr** [bcgit/bc-java#945]
In order to process data without blocking it may be useful to call org.bouncycastle.tls.DTLSTransport.receive with timeMillis=0 to process available data and exit immediately if underlying transport has no packets to receive. This used to work, however it seems to be broken with commit f13147153dc827a9bc9bcf0f82b1f32be4d93b42

Now DTLSRecordLayer.receive enters infinite busy loop if timeMillis=0 and transport keeps throwing SocketTimeoutException.

**Comment by peterdettman** [comment]
This is an inherently blocking API. DatagramTransport models DatagramSocket in that timeout is either 0 for infinite timeout, or >0 for a limited timeout. Yes, parts of this were not working correctly earlier. Looping on SocketTimeoutException is correct behaviour; the underlying DatagramTransport/DatagramSocket is not invalidated. If you are using a timeout of 0 you shouldn't be seeing this though, unless perhaps the implementation of DatagramTransport that you have supplied to the API is not respecting the timeout argument of 'receive'.

If you really still need this, using a timeout of 1 (ms) may be good enough, but if you don't have a thread dedicated to the socket e.g. the heartbeat mechanism can't work properly (in case you're using it). I guess even the socket may drop packets if you are not processing it.

**Comment by t-ivan-gr** [comment]
Peter, thanks for clarifying. Yes, we do supply an implementation of DatagramTransport that treats timeMillis=0 as non-blocking request, not as infinite wait. I could not find documentation about timeMillis=0 signifying infinite wait so I assumed that it is ok to use it as non-blocking mechanism, and it worked with older versions of BC. 

For a bit of context as to why we're supplying custom transport - we are implementing WebRTC solution which needs to demultiplex packets into SRTP/ICE/DTLS before submitting them to corresponding layer (see https://tools.ietf.org/html/rfc5764#section-5.1.2). Having non-blocking dtls processing makes a lot of sense in this application, but since it turns out that BC doesn't really support non-blocking processing I guess we'll need to find another way around it.

**Comment by makkarpov** [comment]
> but since it turns out that BC doesn't really support non-blocking processing I guess we'll need to find another way around it.

I made an non-blocking impl, by the way, exactly for the same purpose: WebRTC.

https://github.com/bcgit/bc-java/issues/443
