### ISSUE TITLE
How to build bcprov-jdk15on-<version>.jar with Gradle?

### ISSUE THREAD

**Issue by SMUsamaShah** [bcgit/bc-java#950]
Version 1.56

Gradle build on bcprov creates `prov-1.56-SNAPSHOT.jar` which is very different from the `bcprov-jdk15on-156.jar` I get with `./build15+` ant/bash script.

How to build the same jar as `./build15+` with Gradle?

**Comment by dghgit** [comment]
If you build using the current Gradle script (based on Gradle 6) using Java 8, you should get something close to what you get with the ./build15+ script - the only difference at the moment being the lack of lcrypto. It just has "jdk15to18" in the name instead.

Note the actual bcprov-jdk15on jars are multi-release jars, with the alternate classes being added as a separate process.

**Comment by winfriedgerlach** [comment]
@SMUsamaShah @dghgit is this question answered? Can the ticket be closed?

**Comment by SMUsamaShah** [comment]
@winfriedgerlach It never worked correctly. I made a build with maven probably, Haven't touched BC since then therefore don't remember much anyway.
