### ISSUE TITLE
Encoding of KeyAgreeRecipientInfo structures is omitting ukm field

### ISSUE THREAD

**Issue by carl-wallace** [bcgit/bc-java#952]
JceKeyAgreeRecipientInfoGenerator::generateRecipientEncryptedKeys determines whether or not to utilize UserKeyingMaterial based on inspection of the key agreement algorithm OID (see [line 162 in JceKeyAgreeRecipientInfoGenerator.java](https://github.com/bcgit/bc-java/blob/master/pkix/src/main/java/org/bouncycastle/cms/jcajce/JceKeyAgreeRecipientInfoGenerator.java#L162)). 

KeyAgreeRecipientInfoGenerator::generate determines whether or not to encode a UserKeyingMaterial value based on retrieving the value from the derived implementation of getUserKeyMaterial (see [line 55 in KeyAgreeRecipientInfoGenerator.java](https://github.com/bcgit/bc-java/blob/master/pkix/src/main/java/org/bouncycastle/cms/KeyAgreeRecipientInfoGenerator.java#L55)).

The derived implementation of getUserKeyMaterial in JceKeyAgreeRecipientInfoGenerator returns the userKeyingMaterial member variable (see [line 273 of JceKeyAgreeRecipientInfoGenerator.java](https://github.com/bcgit/bc-java/blob/29fc749a872674d352431f5231f69dc44651fde4/pkix/src/main/java/org/bouncycastle/cms/jcajce/JceKeyAgreeRecipientInfoGenerator.java#L273)). However, this value is not set so the ukm field is omitted in the encoded structure despite having been used when generating the encrypted recipient keys.

It looks to me like that userKeyMaterial value generated in generateRecipientEncryptedKeys should be saved to ```this.userKeyMaterial```. For example: 

```
else if (CMSUtils.isEC(keyAgreementOID))
{
    byte[] ukmKeyingMaterial = ecc_cms_Generator.generateKDFMaterial(keyEncryptionAlgorithm, keySizeProvider.getKeySize(keyEncAlg), userKeyingMaterial);
    agreementParamSpec = new UserKeyingMaterialSpec(ukmKeyingMaterial);
    setUserKeyingMaterial(ukmKeyingMaterial); // add this line
}
```

When this change is made, the resulting encoding features the ukm field.

**Comment by dghgit** [comment]
userKeyingMaterial is encoded, and in accordance with RFC 5652.

ukmKeyingMaterial is a calculated field from userKeyingMaterial, and the approach for calculating it does vary, although it is always based in some way on the userKeyingMaterial with the simplest approach being to use just the value for userKeyingMaterial. Encoding ukmMaterial as above may mean that any other recipient keys specified in the info block would no longer work as they may not make the same use of ukmKeyingMaterial as the EC key does.

I seem to be missing something. Exactly what is the problem you are running into?

**Comment by carl-wallace** [comment]
I was conflating ECC-CMS-SharedInfo encoding with the value of UKM itself (in 3.1.3 of 5753). You can close this. Sorry for the noise.

**Comment by carl-wallace** [comment]
I was conflating ECC-CMS-SharedInfo encoding with the value of UKM itself (in 3.1.3 of 5753). You can close this. Sorry for the noise.
