### ISSUE TITLE
ECDH/0x18: unknown tag

### ISSUE THREAD

**Issue by bmarwell** [bcgit/bc-java#954]
Using a secret OpenPGP key  containing a curve25519 algo yields this exception:

```
Caused by: org.bouncycastle.openpgp.PGPException: unknown algorithm tag in signature:18
        at org.bouncycastle.openpgp.operator.jcajce.OperatorHelper.createSignature(Unknown Source)
        at org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentSignerBuilder.build(Unknown Source)
        at org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentSignerBuilder.build(Unknown Source)
        at org.bouncycastle.openpgp.PGPSignatureGenerator.init(Unknown Source)
        at org.jreleaser.engine.sign.Signer.initSignatureGenerator(Signer.java:214)
        ... 19 more               
```

Fix:
The case here:
https://github.com/bcgit/bc-java/blob/4a937ecd3ed3934fecb742063ea2fea6e7b9af8d/pg/src/main/java/org/bouncycastle/openpgp/operator/jcajce/OperatorHelper.java#L271-L277

Must contain this algo, too:

https://github.com/bcgit/bc-java/blob/4a937ecd3ed3934fecb742063ea2fea6e7b9af8d/pg/src/main/java/org/bouncycastle/bcpg/PublicKeyAlgorithmTags.java#L17

Affected projects:
https://github.com/jreleaser/jreleaser/issues/152
Also probably sonatype nexus at some point.

**Comment by dghgit** [comment]
ECDH is not a signature algorithm. If the key is being used for ECDSA it should be tagged as that. Little if any good is believed to come from using key-agreement/encryption-keys for signing and visa-versa.

**Comment by bmarwell** [comment]
@dghgit I retraced from your comment in the jreleaser issue the OpenPGP initialization. I do not see where Andres could have done something wrong, he uses `pgpSecretKey.getPublicKey().getAlgorithm()` which is `ed25519`:
```
sec   ed25519/0x31605D40DD2A99F4 2021-05-16 [SC] [expires: 2025-05-15]
      Key fingerprint = 331C 8E5F F20D 3A48 C8E1  81A9 3160 5D40 DD2A 99F4
uid                   [ultimate] bmarwell <------------------>
```

I think there must be a problem with parsing the key on your side, because it should not have been `18` in the first place, but 22 (https://github.com/bcgit/bc-java/blob/4a937ecd3ed3934fecb742063ea2fea6e7b9af8d/pg/src/main/java/org/bouncycastle/bcpg/PublicKeyAlgorithmTags.java#L21).
