### ISSUE TITLE
Include counter-signature hash algorithm into SignedData.digestAlgorithms 

### ISSUE THREAD

**Issue by bsanchezb** [bcgit/bc-java#955]
Hello,

RFC 5652 highly recommends to add used hash algorithms within the _SignedData.digestAlgorithms_ field:
>  **digestAlgorithms** is a collection of message digest algorithm identifiers.
> ...
>  **Implementations MAY fail to validate signatures** that use a digest algorithm that is not included in this set. 

and

> **The message digest algorithm SHOULD be among those listed in the digestAlgorithms field** of the associated SignerData.

However, with BC I have a problem to fulfil this requirement when working with counter-signatures.

When I create a counter-signature with a hash algorithm different from the one used in the main signature, the produced _CMSSignedData_ does not contain the new hash algorithm and I do not see a way to add it.

The code what I use to create a counter-signature is:
```
SignerInformationStore signerInformationStore = originalCMSSignedData.getSignerInfos();
List<SignerInformation> result = new LinkedList<>();
for (SignerInformation signerInformation : signerInformationStore) {
    CMSSignedDataGenerator cmsSignedDataGenerator = *build the generator*;
    SignerInformationStore counterSignatureSignerInfoStore = CMSUtils.generateCounterSigners(cmsSignedDataGenerator, signerInformation);
    result.add(SignerInformation.addCounterSigners(signerInformation, counterSignatureSignerInfoStore));
}
CMSSignedData updatedCMSSignedData = CMSSignedData.replaceSigners(originalCMSSignedData, new SignerInformationStore(result));
```

The resulting _updatedCMSSignedData_ does not contain the hash algorithm used to create the counter-signature, which is stored within a _SignerInformation_ object corresponding to the counter-signature.

The method [CMSSignedData.replaceSigners(...)](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pkix/src/main/java/org/bouncycastle/cms/CMSSignedData.java#L492) collects all digest algorithms from the SignerInformations, therefore it collects the algorithms in case of parallel signatures, however it does not take counter-signatures into account.
Would be nice to collect the algorithms from counter-signatures as well, especially that the code could be adapted easely:
```
Iterator it = signerInformationStore.getSigners().iterator();
while (it.hasNext()) {
    SignerInformation signer = (SignerInformation)it.next();            
    digestAlgs.add(CMSSignedHelper.INSTANCE.fixAlgID(signer.getDigestAlgorithmID()));
    SignerInformationStore counterSignaturesStore = signerInformation.getCounterSignatures();
    Iterator<SignerInformation> counterSignatureIt = counterSignatureStore.iterator();
    while (counterSignatureIt.hasNext()) {
        SignerInformation counterSigner = counterSignatureIt.next();
        digestAlgs.add(CMSSignedHelper.INSTANCE.fixAlgID(counterSigner.getDigestAlgorithmID()));
    }
    vec.add(signer.toASN1Structure());        
}
```

Or, as an alternative, a new method, similar to [CMSSignedData.replaceCertificatesAndCRLs(...)](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pkix/src/main/java/org/bouncycastle/cms/CMSSignedData.java#L560) could be added, allowed replacing the _digestAlgorithms_ field value.

If another solution is possible, I would appreciate any help as well.

Thank you.

Best regards,
Aleksandr.

**Comment by dghgit** [comment]
So, I've done this, as it's probably an improvement and does no harm. A word of caution though, I'm not entirely sure the interpretation is correct though as the purpose of digestAlgorithms is to allow for 1 pass processing of encapsulated signed data. This isn't required for countersignatures, but it very helpful if you have to stream your way through a gig of BER encoded data to get to the signers. For this reason I would not assume that counter signatures would be represented in the digestAlgorithms field as for large objects it will involved rewriting the start of the structure because of a change made to the end of it. 

Update should appear here shortly and just made the cut for 1.69.

**Comment by bsanchezb** [comment]
Thanks! Seems very good!

Regards,
Aleksandr.
