### ISSUE TITLE
Add support of PLAIN-ECDSA with SHA3- hash algorithms

### ISSUE THREAD

**Issue by bsanchezb** [bcgit/bc-java#956]
Hello,

BouncyCastle does not support a group of PLAIN-ECDSA algorithms with SHA3- hash algorithm, in particular:
0.4.0.127.0.7.1.1.4.1.8 - ecdsa-plain-SHA3-224(8)
0.4.0.127.0.7.1.1.4.1.9 - ecdsa-plain-SHA3-256(9)
0.4.0.127.0.7.1.1.4.1.10 - ecdsa-plain-SHA3-384(10)
0.4.0.127.0.7.1.1.4.1.11 - ecdsa-plain-SHA3-512(11)

More information can be found in the [document](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03151/TR-03151.pdf?__blob=publicationFile&v=4).

It does not seem to be a big problem to add, especially that BC already supports standard ECDSA with SHA3 hash family.

Best regards,
Aleksandr.

**Comment by dghgit** [comment]
These are now added and available in the current beta off https://www.bouncycastle.org/betas

**Comment by bsanchezb** [comment]
Thank you!
