### ISSUE TITLE
The certificate chain sorting error in the PKIXCertPath.java class

### ISSUE THREAD

**Issue by ai-houzi** [bcgit/bc-java#960]
When I used the import certificate chain function, a certificate chain sorting error occurred, and then I read the code and found that there is some problem with the certificate sorting in this place, and I also commented that it was abandoned. Can it be fixed here? I use www.baidu. com's certificate chain. The specific code is the sortCerts method in PKIXCertPath.java:
```java
    

**// can only have one end entity cert - something's wrong, give up.** 

 
    if (retList.size() > 1)        {           
       return orig;       
   }
```

**Comment by dghgit** [comment]
Try using the CertPathBuilder on the imported certificates first.

**Comment by ai-houzi** [comment]
Yes, I use CertPathBuilder to build a trusted certificate chain. But because of the sorting problem, I can't get the root certificate accurately. I imported a certificate chain file in .p7b format. I have always used this method before. Now I am not sure if my code is standard written. Could you please review it for me? Thank you very much，My code is as follows:
```java
        certPath = cf.generateCertPath(new ByteArrayInputStream(certs), "PKCS7");
        X509Certificate rootCert = certPath.get(certPath.size() - 1); //Get root certificate
        X509Certificate endCert = certPath.get(0); // Get node certificate

        CollectionCertStoreParameters params = new CollectionCertStoreParameters(certPath);
        CertStore store = CertStore.getInstance("Collection", params);
        // build the path
        CertPathBuilder builder = CertPathBuilder.getInstance("PKIX", ProviderUtil.getProvider());
        X509CertSelector pathConstraints = new X509CertSelector();
        pathConstraints.setSubject(endCert.getSubjectX500Principal().getName());
        PKIXBuilderParameters buildParams = new PKIXBuilderParameters(Collections.singleton(new TrustAnchor(rootCert, null)), pathConstraints);

        buildParams.addCertStore(store);
        buildParams.setDate(new Date());
        buildParams.setRevocationEnabled(false);

        PKIXCertPathBuilderResult result = (PKIXCertPathBuilderResult) builder.build(buildParams);
        CertPath path = result.getCertPath();
```

**Comment by dghgit** [comment]
The root cert is supposed to be one you already have. It's very unusual for it to be passed in. I think you're probably looking at a CA cert and mistaking that for the root cert. At any rate, while the code is basically correct the line fetching the rootCert is likely to be incorrect.
