### ISSUE TITLE
org.eclipse.ease.ScriptExecutionException: SyntaxError: Java constructor for "org.bouncycastle.crypto.BufferedBlockCipher" with arguments "org.bouncycastle.crypto.modes.CBCBlockCipher" not found

### ISSUE THREAD

**Issue by siddeshas** [bcgit/bc-java#963]
Hi Team,
I am facing below issue while using bouncy castle API. Could you please help me on this

fallowing is the code snippet.
function aes_cbc_decrypt(key, iv, plaintext) {
	
	var keyParam = new org.bouncycastle.crypto.params.KeyParameter(key);
	var cipherParam = new org.bouncycastle.crypto.params.ParametersWithIV(keyParam, iv)
	
	var cipher = new org.bouncycastle.crypto.BufferedBlockCipher(new org.bouncycastle.crypto.modes.CBCBlockCipher(new org.bouncycastle.crypto.engines.AESEngine()));
	cipher.init(false, cipherParam);
	var buf = Converter.hexStringToByteArray(resolveDecorators("<[" + cipher.getOutputSize(plaintext.length) + "*] DATA 00>"));
	var len = cipher.processBytes(plaintext, 0, plaintext.length, buf, 0);
	len += cipher.doFinal(buf, len);
	
	return Converter.byteArrayToHexString(buf);
}

**Comment by dghgit** [comment]
Sorry, no idea on this one. I'd suspect a class loader issue of some sort, the constructor does exist, but no idea what.

**Comment by siddeshas** [comment]
issue resolved. there were two bc plugins in product installer. i have removed plugin with older version started working.
