### ISSUE TITLE
ClearSignedFileProcessor#signFile(...) : set Hashed Subpackets outside UserID Loop?

### ISSUE THREAD

**Issue by DanskerDave** [bcgit/bc-java#964]
I noticed the Hashed Subpackets are not being set in...
[ClearSignedFileProcessor#signFile(...)](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pg/src/main/java/org/bouncycastle/openpgp/examples/ClearSignedFileProcessor.java#L266)
...when no Users are associated with the PublicKey.

Perhaps the line `sGen.setHashedSubpackets(spGen.generate());` should be moved _after_ the UserID loop?

Maybe replace the entire block with:
```
pgpSecKey.getPublicKey().getUserIDs().forEachRemaining(userID -> {
	spGen.addSignerUserID(false, userID);
});
sGen.setHashedSubpackets(spGen.generate());

```

**Comment by dghgit** [comment]
In the example the only reason to add them is if the user packet is added. I can see how that might not translate well if the code is modified to add others. Is that what happened?

**Comment by DanskerDave** [comment]
That's true, but Subpackets are not specific to that, so the correct place to append them is _after_ the loop, not _within_ it.

**Comment by DanskerDave** [comment]
...and yes, that's how I noticed it, as I was trying to add a Custom Subpacket using a PublicKey with no UserID's associated & couldn't figure out why it wasn't being appended.

**Comment by dghgit** [comment]
I have modified the code as a courtesy to those who might come later - PGPSignatureGenerator does actually handle zero length adds correctly so there is no need for the optimization.
