### ISSUE TITLE
org.bouncycastle.asn1.ASN1ObjectIdentifier"'s

### ISSUE THREAD

**Issue by yehia** [bcgit/bc-java#967]
Hello, i get this error when try to execute my weld project...

`Caused by: java.lang.SecurityException: class "org.bouncycastle.asn1.ASN1ObjectIdentifier"'s signer information does not match signer information of other classes in the same package`

Itext version: 5.5.13.2
bouncycastle version: jdk15to18 (1.68)

does anyone know the reason?

**Comment by dghgit** [comment]
there's two versions of the jar on the same classpath. Either that or it's dueling class loaders - usually a class loader other than the system class loader has picked up the class first, and then the system class loader tries to get it but doesn't trust the other one.
