### ISSUE TITLE
Base64 encoder bug

### ISSUE THREAD

**Issue by zc19860419-cfca** [bcgit/bc-java#971]
the method of class org.bouncycastle.util.encoders.Base64Encoder: public int encode(byte[] buf, int off, int len, OutputStream out) throws IOException. Expect to return the number of bytes after encoding, but the actual result is 0

**Comment by dghgit** [comment]
Whoops, argument assignment considered dangerous! Thank for the report. Now fixed. Will show up in 170b02.
