### ISSUE TITLE
Missing 1.69 jars in Maven Central

### ISSUE THREAD

**Issue by chrismathews** [bcgit/bc-java#973]
I might be missing something but there seems to be a number of jars missing from the 1.69 release in Maven Central.

Looking at: https://www.bouncycastle.org/latest_releases.html, it mentions the addition of new bcutil-* jars but makes no mention of any jars being removed.

Right now, I can see the following 1.69 jars published in Maven Central (13 jars total):
- org.bouncycastle:bctls-jdk15to18:1.69:jar
- org.bouncycastle:bcpkix-jdk15to18:1.69:jar
- org.bouncycastle:bcpg-jdk15to18:1.69:jar
- org.bouncycastle:bcutil-jdk15to18:1.69:jar
- org.bouncycastle:bcprov-jdk15to18:1.69:jar
- org.bouncycastle:bcpg-jdk15on:1.69:jar
- org.bouncycastle:bcutil-jdk15on:1.69:jar
- org.bouncycastle:bcpkix-jdk15on:1.69:jar
- org.bouncycastle:bcmail-jdk15on:1.69:jar
- org.bouncycastle:bcjmail-jdk15on:1.69:jar
- org.bouncycastle:bcprov-ext-jdk15on:1.69:jar
- org.bouncycastle:bctls-jdk15on:1.69:jar
- org.bouncycastle:bcprov-jdk15on:1.69:jar

However these 1.68 jars are available but don't have a 1.69 equivalent (14 jars total):
- org.bouncycastle:bctls-jdk14:1.68:jar
- org.bouncycastle:bcprov-jdk14:1.68:jar
- org.bouncycastle:bcprov-ext-jdk14:1.68:jar
- org.bouncycastle:bcprov-ext-debug-jdk14:1.68:jar
- org.bouncycastle:bcprov-debug-jdk14:1.68:jar
- org.bouncycastle:bcpkix-jdk14:1.68:jar
- org.bouncycastle:bcpg-jdk14:1.68:jar
- org.bouncycastle:bcmail-jdk14:1.68:jar
- org.bouncycastle:bcprov-ext-jdk15to18:1.68:jar
- org.bouncycastle:bcprov-ext-debug-jdk15to18:1.68:jar
- org.bouncycastle:bcprov-debug-jdk15to18:1.68:jar
- org.bouncycastle:bcmail-jdk15to18:1.68:jar
- org.bouncycastle:bcprov-ext-debug-jdk15on:1.68:jar
- org.bouncycastle:bcprov-debug-jdk15on:1.68:jar

Is this expected?

**Comment by dghgit** [comment]
Working on it... publishing is actually a manual process.

**Comment by selbitschka** [comment]
I just seen that most files are published now but bcmail-jdk15to18 is still missing version 1.69.

**Comment by dghgit** [comment]
There's always one... bcmail-jdk15to18 and bcjmail-jdk15to18 (the jakarta S/MIME jar) should both be up now.
