### ISSUE TITLE
ProvBCFKS engine.load(KeyStore.LoadStoreParameter parameter) implementation is not compliant with The Java interface

### ISSUE THREAD

**Issue by DimoDonchev** [bcgit/bc-java#974]
When engine.load((KeyStore.LoadStoreParameter) null) is called it throws an illegalArgumentException.
However the official Java documentation in Oracle states that the LoadStoreParameter may be null
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/KeyStoreSpi.html#engineLoad(java.security.KeyStore.LoadStoreParameter)
a quick fix might be when LoadStoreParameter is null to call engineLoad((InputStream)null, (char[])null);

**Comment by dghgit** [comment]
Thanks for the report. This was fixed in the general release a while ago, the patch didn't make it in BC-FJA 2.0.0, but it will be in BC-FJA 1.0.3 and in the 2.0.X series later.

**Comment by DimoDonchev** [comment]
@dghgit We are having this issue for BC-FIPS 1.0.2. 
Also I do not see 1.03 being released in the roadmap https://www.bouncycastle.org/fips_java_roadmap.html

**Comment by dghgit** [comment]
Sorry to hear it. We haven't set a release date for 1.0.3 yet. I'd expect mid next year for submission.

**Comment by DimoDonchev** [comment]
Hello @dghgit is there any progress regarding this issue?

**Comment by dghgit** [comment]
We actually had to do a 140-3 related update, the fix for this went into it as well.
