### ISSUE TITLE
Unable to create a CMS signature with PLAIN-ECDSA with SHA3

### ISSUE THREAD

**Issue by bsanchezb** [bcgit/bc-java#975]
Hello,

The support of SHA-3 digest algorithms has been added for PLAIN-ECDSA in the ticket #956 .

However, it is still not possible to create a CMS signature with the algorithms, because the respective identifiers for the algorithms have not been added to the classes : [DefaultDigestAlgorithmIdentifierFinder](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pkix/src/main/java/org/bouncycastle/operator/DefaultDigestAlgorithmIdentifierFinder.java) and [DefaultSignatureAlgorithmIdentifierFinder](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pkix/src/main/java/org/bouncycastle/operator/DefaultSignatureAlgorithmIdentifierFinder.java) . Probably some additional changes can be required.

You can try to add the following unit tests to the class [NewSignedDataTest](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pkix/src/test/java/org/bouncycastle/cms/test/NewSignedDataTest.java) to see it currently does not work:

```
public void testPLAIN_ECDSASHA3_224Encapsulated() throws Exception {
        encapsulatedTest(_signEcDsaKP, _signEcDsaCert, "SHA3-224withPLAIN-ECDSA");   
 }

public void testPLAIN_ECDSASHA3_256Encapsulated() throws Exception {
        encapsulatedTest(_signEcDsaKP, _signEcDsaCert, "SHA3-256withPLAIN-ECDSA");    
}

public void testPLAIN_ECDSASHA3_384Encapsulated()  throws Exception {
        encapsulatedTest(_signEcDsaKP, _signEcDsaCert, "SHA3-384withPLAIN-ECDSA");    
}

public void testPLAIN_ECDSASHA3_512Encapsulated() throws Exception {
        encapsulatedTest(_signEcDsaKP, _signEcDsaCert, "SHA3-512withPLAIN-ECDSA");    
}
```

Unfortunately, I did not test the changes on my side before the 1.69 version release, but I hope the full support as well as support for a CMS Signature creation will be added in the next version.

Thank you in advance.

Best regards,
Aleksandr.

**Comment by dghgit** [comment]
These are now added and available on https://www.bouncycastle.org/betas 170b11 or later.

**Comment by bsanchezb** [comment]
Thank you!

BR,
Aleksandr.
