### ISSUE TITLE
Some BCPG `InputStream`s are missing a `close()` method

### ISSUE THREAD

**Issue by bjansen** [bcgit/bc-java#983]
I'm using BouncyGPG to decrypt files, which uses bcpg-jdk15on behind the scenes. My code is basically passing a `FileInputStream` to BouncyCastle, and getting another `InputStream` back that contains the decrypted data. 

I would expect that when I call `close()` on the returned input stream, it would automatically close the underlying `FileInputStream`, but it doesn't. 

The debugger shows that two custom `InputStream`s are wrapping another `InputStream` and don't override `close()` to close the wrapped input automatically:

* `org.bouncycastle.bcpg.BCPGInputStream.PartialInputStream`
* `org.bouncycastle.openpgp.PGPEncryptedData.TruncatedStream`

When I add the missing methods, my `FileInputStream` is ultimately closed.

I can provide a PR to fix the problem if you're interested.

**Comment by dghgit** [comment]
We made this mistake when we first implemented it. GPG is actually an on the wire protocol - so it actually does make sense for multiple messages to appear on a single stream, which means it can sometimes be fatal to propagate a close. I'd recommend providing your own wrapping stream to provide an outer layer that does the close for the times when you find this behavior is required.
