### ISSUE TITLE
SICBlockCypher.processBytes throws DataLengthException wrongly in v1.69

### ISSUE THREAD

**Issue by dmitry-et** [bcgit/bc-java#987]
Independently from the number of bytes requested for processing (`len`), if `in.length - inOff` is smaller then `blockSize` the exception is thrown. In particular, the exception is thrown when `in.length - inOff` equals `len` and `len` is smaller than `blockSIze`.

The issue is not present in v1.68.

**Comment by peterdettman** [comment]
Thanks for the report. This has now been fixed, including previously missing test coverage.
