### ISSUE TITLE
Key Usage for a Public RSA key will key usages as Certify and Authenticate giving wrong output

### ISSUE THREAD

**Issue by Susmit07** [bcgit/bc-java#989]
Hello Team,

I am not able to get correct key usage from the below code:

```
        @SuppressWarnings("unchecked")
	private static StringBuilder evaluateKeyUsage(PGPPublicKey publicKey) {
		Iterator<PGPSignature> sigItr = publicKey.getSignatures();
		StringBuilder keyUsage = new StringBuilder();
		while (sigItr.hasNext()) {
			PGPSignature sig = sigItr.next();
			PGPSignatureSubpacketVector subPacks = sig.getHashedSubPackets();
			if (subPacks != null) {
				int keyFlags = subPacks.getKeyFlags();
				boolean isEncryptComms = (keyFlags & KeyFlags.ENCRYPT_COMMS) > 0;
				boolean isEncryptStorage = (keyFlags & KeyFlags.ENCRYPT_STORAGE) > 0;
				if (isEncryptComms || isEncryptStorage) {
					if (keyUsage.indexOf("E") == -1) {
						keyUsage.append("E");
					}
				}
				if ((keyFlags & KeyFlags.CERTIFY_OTHER) > 0) {
					if (keyUsage.indexOf("C") == -1) {
						keyUsage.append("C");
					}
				}
				if ((keyFlags & KeyFlags.SIGN_DATA) > 0) {
					if (keyUsage.indexOf("S") == -1) {
						keyUsage.append("S");
					}
				}
				if ((keyFlags & KeyFlags.AUTHENTICATION) > 0) {
					if (keyUsage.indexOf("A") == -1) {
						keyUsage.append("A");
					}
				}
			}
		}
		return keyUsage;

	}
```
   
The key is of type RSA with certify and authenticate but at the end of the loop it evaluates to ECSA am I doing anything wrong?

Public Key: (type DSA 1024)

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.68

mI0EYOhnDgEEANUAeeEzowZfKd5kO1kNSV0podJ/SMTfV09xJlrfGxQG+Pvjt3Ng
KoiIlvgt8O7l/SnmueEvrpvsf1ZLjk4DK8ZtlibHA0I+6AyZxAAphLX1/Yg+Uoiu
HlPNLldOThPRobgYBSUb4JUSIH2T8cilg535ZvW/jlaZWlIn+fWp/EuhABEBAAG0
CERTQV9zaWduiKUEEAEKAA8FAmDoZw4CGwMFCQAnjQAACgkQVva+2l4lpsHdrAP/
QABR30qzPZHFFrP4tjJyUVKLm7a7R5ieqK8WqohIVDT73EyHhJLeKeYxF6qAeGA/
ALbPz0bO0+PL4OJDMx4qvg4eZwaitgPdbKS8ET0/9umWoEdOiiVvZG5A6NvlyB8V
A5bCS9d16+h3JHGlebar0n3vk6pCg62ArSQ/RdjJ5qaIxAQQAQoALgUCYOvdjQUJ
ACOYgAwLAQIDBAcICQoLDA0FFgABAgMIFQECAwgJCgsCHgECGy0ACgkQVva+2l4l
psHxEwP/XYWubre2sP0gbCqq2HOzfHImLALkEk8/OUPWMDDOJEjkqXy7LrGC7tHU
bl4U4vGqlEb8UduCQBocYvtQeIoE6kw277cyWqn7M218hCYU5f97GmMnBuew+kci
dcb4qHYrpqSyDOv+HOFlTNgKtOUJcYfT4DGnDKXA90D2lt4Xxi2IxAQQAQoALgUC
YOvdqwUJACOYgAwLAQIDBAcICQoLDA0FFgABAgMIFQECAwgJCgsCHgECGyEACgkQ
Vva+2l4lpsGBAgP/WF6Hoho0PyEyA5SpyYas1wRpaUDTHl4pQGi0GG//QfPOY0eD
uL1UkQADquT8x5pfQAO3Z58RNbJhZWcUDaLWmLy+YLzrivu+DoBA4ifO7IPGzCjc
6S0F9qk70EAEllSszVmqRpUBoZbCmaruVTPrhVyFdyX+3afqtyUdgo0Gx40=
=yHdH
-----END PGP PUBLIC KEY BLOCK-----

When I check-in in GPG i only get CA but in bouncy castle above code its CSEA

**Comment by Susmit07** [comment]
@peterdettman @dghgit  Guys we need your help, its a blocker for us

**Comment by dghgit** [comment]
gpg --list-packets /tmp/x.gpg shows why:

# off=0 ctb=98 tag=6 hlen=2 plen=141
:public key packet:
	version 4, algo 1, created 1625843470, expires 0
	pkey[0]: [1024 bits]
	pkey[1]: [17 bits]
	keyid: 56F6BEDA5E25A6C1
# off=143 ctb=b4 tag=13 hlen=2 plen=8
:user ID packet: "DSA_sign"
# off=153 ctb=88 tag=2 hlen=2 plen=165
:signature packet: algo 1, keyid 56F6BEDA5E25A6C1
	version 4, created 1625843470, md5len 0, sigclass 0x10
	digest algo 10, begin of digest dd ac
	hashed subpkt 2 len 4 (sig created 2021-07-09)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 9 len 4 (key expires after 30d0h0m)
	subpkt 16 len 8 (issuer key ID 56F6BEDA5E25A6C1)
	data: [1023 bits]
# off=320 ctb=88 tag=2 hlen=2 plen=196
:signature packet: algo 1, keyid 56F6BEDA5E25A6C1
	version 4, created 1626070413, md5len 0, sigclass 0x10
	digest algo 10, begin of digest f1 13
	hashed subpkt 2 len 4 (sig created 2021-07-12)
	hashed subpkt 9 len 4 (key expires after 27d0h0m)
	hashed subpkt 11 len 11 (pref-sym-algos: 1 2 3 4 7 8 9 10 11 12 13)
	hashed subpkt 22 len 4 (pref-zip-algos: 0 1 2 3)
	hashed subpkt 21 len 7 (pref-hash-algos: 1 2 3 8 9 10 11)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 27 len 1 (key flags: 2D)
	subpkt 16 len 8 (issuer key ID 56F6BEDA5E25A6C1)
	data: [1023 bits]
# off=518 ctb=88 tag=2 hlen=2 plen=196
:signature packet: algo 1, keyid 56F6BEDA5E25A6C1
	version 4, created 1626070443, md5len 0, sigclass 0x10
	digest algo 10, begin of digest 81 02
	hashed subpkt 2 len 4 (sig created 2021-07-12)
	hashed subpkt 9 len 4 (key expires after 27d0h0m)
	hashed subpkt 11 len 11 (pref-sym-algos: 1 2 3 4 7 8 9 10 11 12 13)
	hashed subpkt 22 len 4 (pref-zip-algos: 0 1 2 3)
	hashed subpkt 21 len 7 (pref-hash-algos: 1 2 3 8 9 10 11)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 27 len 1 (key flags: 21)
	subpkt 16 len 8 (issuer key ID 56F6BEDA5E25A6C1)
	data: [1023 bits]

gpg is only using the last signature.

**Comment by Susmit07** [comment]
@peterdettman thank you .. you rocked I solved the issue with the below logic:

```
        @SuppressWarnings("unchecked")
	private static StringBuilder evaluateKeyUsage(PGPPublicKey publicKey) {
		// Iterator to find the signature list size.
		Iterator<PGPSignature> sigCountItr = publicKey.getSignatures();
		// Iterator to fetch actual signatures
		Iterator<PGPSignature> sigItr = publicKey.getSignatures();
		
		int sigItrSize = 0;
		while (sigCountItr.hasNext()) {
			sigCountItr.next();
			sigItrSize++;
		}
		
		if (PGPlogger.debug) {
			if (sigItrSize > 1) {
				PGPlogger.logDebug(CLASS_NAME, "evaluateKeyUsage(pubKey)",
						"There are multiple signatures associated with the secret key: " + sigItrSize);
			}
		}
		StringBuilder keyUsage = new StringBuilder();
		int loopCount = 1;
		while (sigItr.hasNext()) {
			PGPSignature sig = sigItr.next();
			if (loopCount == sigItrSize) {
				PGPSignatureSubpacketVector subPacks = sig.getHashedSubPackets();
				if (subPacks != null) {
					int keyFlags = subPacks.getKeyFlags();
					boolean isEncryptComms = (keyFlags & KeyFlags.ENCRYPT_COMMS) > 0;
					boolean isEncryptStorage = (keyFlags & KeyFlags.ENCRYPT_STORAGE) > 0;
					if (isEncryptComms || isEncryptStorage) {
						if (keyUsage.indexOf("E") == -1) {
							keyUsage.append("E");
						}
					}
					if ((keyFlags & KeyFlags.CERTIFY_OTHER) > 0) {
						if (keyUsage.indexOf("C") == -1) {
							keyUsage.append("C");
						}
					}
					if ((keyFlags & KeyFlags.SIGN_DATA) > 0) {
						if (keyUsage.indexOf("S") == -1) {
							keyUsage.append("S");
						}
					}
					if ((keyFlags & KeyFlags.AUTHENTICATION) > 0) {
						if (keyUsage.indexOf("A") == -1) {
							keyUsage.append("A");
						}
					}
				}
			}
			loopCount++;
		}
		return keyUsage;

	}
```
