### ISSUE TITLE
GF2mField.exp(0,0) incorrect result

### ISSUE THREAD

**Issue by jcflack** [bcgit/bc-java#99]
The first lines of org.bouncycastle.pqc.math.linearalgebra.GF2mField.exp() are "if (a == 0) { return 0; }" but I believe the rule that k == 0 --> a^k == 1 for all a even applies when a == 0.

Perhaps there are few algorithms that would normally call exp with a==0 so it may rarely or never cause a problem, but it seems safest to make sure it's correct.

Originally caught while testing a _different_ GF256 implementation by comparing it _to_ GF2mField (Archistar/archistar-smc#23).

**Comment by bcgit** [comment]
Thanks. Fixed.
