### ISSUE TITLE
PKCS12 KeyStore dropping a Certificate with bc 1.64

### ISSUE THREAD

**Issue by yash196** [bcgit/bc-java#992]
Hi I am using a PKCS 12 keystore with bouncyCastle 1.64, but while using : setKeyEntry(String alias, Key key, char[] password,Certificate[] chain) a certificate is getting deleted/dropped from chain automatically. 
This was working fine in bc 1.51, then after upgrade to 1.64, we started seeing this issue.

Is there any bug/known issue? Or did anything changed the functionality between 1.51-1.64 ?

**Comment by dghgit** [comment]
You'd need to provide a sample. A lot changed between those two releases.

**Comment by dghgit** [comment]
Unable to reproduce.
