### ISSUE TITLE
Question for SignerInformation.verify()

### ISSUE THREAD

**Issue by hwann1001** [bcgit/bc-java#994]
Hi guys
I have question for verify action in BC.
codes is below : 
SignerInformation signer = (SignerInformation) it.next();
            Collection certCollection = certs.getMatches(signer.getSID());
            Iterator certIt = certCollection.iterator();
            X509Certificate cert = SMIMEFactory.getJcaX509CertificateConverterInstance().getCertificate((X509CertificateHolder) certIt.next());
            // verify that the sign is correct and that it was generated
            // when the certificate was current
         JcaSimpleSignerInfoVerifierBuilder() builder = new JcaSimpleSignerInfoVerifierBuilder();
            if (signer.verify(builder.build(cert))) {
                certificates[index] = cert;
            } 

The question is two.
1. signerInformation.verify() is check validate of certificate also?
I means, the certificate was issued from trust  issuer or not.
If it is not, how can I check the certificate valid?

**Comment by dghgit** [comment]
Verify doesn't validate the certificate. You can use the CertPath API to validate the certificate.
