### ISSUE TITLE
SignedData : add an util method to replace digest algorithms

### ISSUE THREAD

**Issue by bsanchezb** [bcgit/bc-java#996]
Hello,

A similar problem firstly has been raised within the issue #955 . The problem concerned counter-signatures and was resolved properly. Thank you for this again!

However, after reviewing of [ETSI EN 319 122-1](https://www.etsi.org/deliver/etsi_en/319100_319199/31912201/01.01.01_60/en_31912201v010101p.pdf), we have found another requirement to enrich _SignedData.digestAlgorithms_ attribute with new algorithms, namely when extending a signature to the LTA level with the _archive-time-stamp-v3_ attribute:

> **5.5.3 The archive-time-stamp-v3 attribute**
> ...
> 2) The octets representing the hash of the signed data. The hash is computed on the same content that was used 
> for computing the hash value that is encapsulated within the message-digest signed attribute of the 
> CAdES signature being archive-time-stamped. The hash algorithm applied shall be the same as the hash 
> algorithm used for computing the archive time-stamp's message imprint. **The hash algorithm identifier should 
> be included in the SignedData.digestAlgorithms set.**

When extending a signature with a hash algorithm different than the one(s) used for a signature creation, the condition (even if it is not strict) fails.
In order to be compliant with the standard, we would like to request a new method within [CMSSignedData](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pkix/src/main/java/org/bouncycastle/cms/CMSSignedData.java) class, similar to [replaceCertificatesAndCRLs(...)](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pkix/src/main/java/org/bouncycastle/cms/CMSSignedData.java#L560) and/or [replaceSigners(...)](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pkix/src/main/java/org/bouncycastle/cms/CMSSignedData.java#L492), allowing to enrich (or replace) externally the set of digest algorithms within the _SignedData_.

Thank you very much!

Best regards,
Aleksandr.

**Comment by dghgit** [comment]
I've done this. You'll find it in 170b08 now up on https://www.bouncycastle.org/betas. Let us know how it goes.

**Comment by bsanchezb** [comment]
Hello,

I have tested the beta version 1.70b08 and it seems working well!

Thank you so much!

Best regards,
Aleksandr.
